CREATE PROCEDURE [REPORTING_BLITZ].[usp_TBL_M6_BDT_REJECTS_OVERTOLERANCE]
AS
    SET XACT_ABORT, NOCOUNT ON;
BEGIN TRY

    DECLARE @EVENTID INT;

    -- Log the execution of the stored procedure
    INSERT INTO [LOG].tbl_StoreProc
    (
        [EVENTNAME],
        [EVENTSTART],
        [EVENTTYPE],
        [EVENTDESCRIPTION]
    )
    VALUES
    (
        'REPORTING_BLITZ.TBL_M6_BDT_REJECTS_OVERTOLERANCE',
        CAST(GETDATE() AS DATETIME),
        'STORE PROC',
        'SINGLE_INGESTION'
    );

    SET @EVENTID = SCOPE_IDENTITY();

    BEGIN TRANSACTION

        DELETE FROM REPORTING_BLITZ.TBL_M6_BDT_REJECTS_OVERTOLERANCE;

        INSERT INTO REPORTING_BLITZ.TBL_M6_BDT_REJECTS_OVERTOLERANCE
        SELECT * FROM LZ.TBL_M6_BDT_REJECTS_OVERTOLERANCE;

    COMMIT TRANSACTION

END TRY
BEGIN CATCH
    IF @@trancount > 0 ROLLBACK TRANSACTION
    EXEC usp_error_handler
    RETURN 55555
END CATCH
GO
