CREATE TABLE [forecast].[ForecastExportCopy] (
    [ProjectNumber]               VARCHAR (7)    NOT NULL,
    [SubprojectNumber]            VARCHAR (1)    NOT NULL,
    [ProjectSubNumber]            INT            NULL,
    [BudgetLineNumber]            INT            NULL,
    [BudgetLineName]              VARCHAR (100)  NULL,
    [ClassOfPlant]                CHAR (2)       NULL,
    [LinkCode]                    VARCHAR (25)   NULL,
    [BudgetCategory]              VARCHAR (112)  NULL,
    [FinanceCategory]             VARCHAR (50)   NULL,
    [JustificationCode]           TINYINT        NULL,
    [FunctionalGroup]             CHAR (1)       NULL,
    [ProjectDescription]          VARCHAR (200)  NULL,
    [Billable]                    CHAR (1)       NULL,
    [ProjectStatusCode]           CHAR (2)       NULL,
    [ApprovalCode]                CHAR (2)       NULL,
    [ProjectType]                 CHAR (1)       NULL,
    [Company]                     SMALLINT       NULL,
    [Exchange]                    VARCHAR (50)   NULL,
    [OperatingArea]               SMALLINT       NULL,
    [State]                       CHAR (2)       NULL,
    [Engineer]                    VARCHAR (50)   NULL,
    [ProjectOwner]                VARCHAR (50)   NULL,
    [ApprovalDate]                DATE           NULL,
    [EstimatedStartDate]          DATE           NULL,
    [EstimatedCompleteDate]       DATE           NULL,
    [ActualStartDate]             DATE           NULL,
    [ReadyForServiceDate]         DATE           NULL,
    [TentativeCloseDate]          DATE           NULL,
    [CloseDate]                   DATE           NULL,
    [AuthorizedDirect]            MONEY          NULL,
    [AuthorizedIndirect]          MONEY          NULL,
    [AuthorizedTotal]             MONEY          NULL,
    [PriorYearsSpendDirect]       MONEY          NOT NULL,
    [PriorYearsSpendIndirect]     MONEY          NOT NULL,
    [PriorYearsSpendTotal]        MONEY          NOT NULL,
    [SpendingForecast]            INT            NULL,
    [JanuaryDirect]               MONEY          NOT NULL,
    [JanuaryIndirect]             MONEY          NOT NULL,
    [FebruaryDirect]              MONEY          NOT NULL,
    [FebruaryIndirect]            MONEY          NOT NULL,
    [MarchDirect]                 MONEY          NOT NULL,
    [MarchIndirect]               MONEY          NOT NULL,
    [AprilDirect]                 MONEY          NOT NULL,
    [AprilIndirect]               MONEY          NOT NULL,
    [MayDirect]                   MONEY          NOT NULL,
    [MayIndirect]                 MONEY          NOT NULL,
    [JuneDirect]                  MONEY          NOT NULL,
    [JuneIndirect]                MONEY          NOT NULL,
    [JulyDirect]                  MONEY          NOT NULL,
    [JulyIndirect]                MONEY          NOT NULL,
    [AugustDirect]                MONEY          NOT NULL,
    [AugustIndirect]              MONEY          NOT NULL,
    [SeptemberDirect]             MONEY          NOT NULL,
    [SeptemberIndirect]           MONEY          NOT NULL,
    [OctoberDirect]               MONEY          NOT NULL,
    [OctoberIndirect]             MONEY          NOT NULL,
    [NovemberDirect]              MONEY          NOT NULL,
    [NovemberIndirect]            MONEY          NOT NULL,
    [DecemberDirect]              MONEY          NOT NULL,
    [DecemberIndirect]            MONEY          NOT NULL,
    [GrossAddsDirect]             MONEY          NOT NULL,
    [GrossAddsIndirect]           MONEY          NOT NULL,
    [GrossAddsTotal]              MONEY          NOT NULL,
    [CIACSpend]                   MONEY          NULL,
    [FutureYearsSpendInfinium]    MONEY          NULL,
    [FutureYearsSpend]            MONEY          NULL,
    [SpendingNotNeededDirect]     INT            NOT NULL,
    [SpendingNotNeededIndirect]   INT            NOT NULL,
    [SpendingNotNeeded]           MONEY          NULL,
    [RemainderToSpendDirect]      INT            NOT NULL,
    [RemainderToSpendIndirect]    INT            NOT NULL,
    [RemainderToSpend]            INT            NOT NULL,
    [AdditionalDollarsNeeded]     MONEY          NULL,
    [CIACBudget]                  MONEY          NULL,
    [AnalystNotes]                VARCHAR (4000) NULL,
    [SubprojectStatus]            VARCHAR (50)   NULL,
    [VarassetStatus]              VARCHAR (100)  NULL,
    [VarassetStatusDate]          DATE           NULL,
    [VarassetClosingIssue]        VARCHAR (100)  NULL,
    [VarassetScheduledFinishDate] DATE           NULL,
    [CarryIn]                     VARCHAR (8)    NOT NULL,
    [SentToClosing]               VARCHAR (25)   NULL
);

