CREATE TABLE [forecast].[SpendingTrendData] (
    [ProjectNumber]            INT           NOT NULL,
    [SubprojectNumber]         SMALLINT      NOT NULL,
    [ProjectSubNumber]         INT           NULL,
    [BudgetLineNumber]         INT           NULL,
    [BudgetLineName]           VARCHAR (100) NULL,
    [ClassOfPlant]             CHAR (2)      NULL,
    [LinkCode]                 VARCHAR (25)  NULL,
    [BudgetCategory]           VARCHAR (112) NULL,
    [JustificationCode]        TINYINT       NULL,
    [FunctionalGroup]          CHAR (1)      NULL,
    [ProjectDescription]       VARCHAR (200) NULL,
    [Billable]                 CHAR (1)      NULL,
    [ProjectStatusCode]        CHAR (2)      NULL,
    [ApprovalCode]             CHAR (2)      NULL,
    [ProjectType]              CHAR (1)      NULL,
    [Company]                  SMALLINT      NULL,
    [Exchange]                 VARCHAR (50)  NULL,
    [OperatingArea]            SMALLINT      NULL,
    [State]                    CHAR (2)      NULL,
    [Engineer]                 VARCHAR (50)  NULL,
    [ProjectOwner]             VARCHAR (50)  NULL,
    [ApprovalDate]             DATE          NULL,
    [EstimatedStartDate]       DATE          NULL,
    [EstimatedCompleteDate]    DATE          NULL,
    [ActualStartDate]          DATE          NULL,
    [ReadyForServiceDate]      DATE          NULL,
    [TentativeCloseDate]       DATE          NULL,
    [CloseDate]                DATE          NULL,
    [AuthorizedDirect]         MONEY         NULL,
    [AuthorizedIndirect]       MONEY         NULL,
    [AuthorizedTotal]          MONEY         NULL,
    [JanuaryDirect2017]        MONEY         NULL,
    [JanuaryIndirect2017]      MONEY         NULL,
    [FebruaryDirect2017]       MONEY         NULL,
    [FebruaryIndirect2017]     MONEY         NULL,
    [MarchDirect2017]          MONEY         NULL,
    [MarchIndirect2017]        MONEY         NULL,
    [AprilDirect2017]          MONEY         NULL,
    [AprilIndirect2017]        MONEY         NULL,
    [MayDirect2017]            MONEY         NULL,
    [MayIndirect2017]          MONEY         NULL,
    [JuneDirect2017]           MONEY         NULL,
    [JuneIndirect2017]         MONEY         NULL,
    [JulyDirect2017]           MONEY         NULL,
    [JulyIndirect2017]         MONEY         NULL,
    [AugustDirect2017]         MONEY         NULL,
    [AugustIndirect2017]       MONEY         NULL,
    [SeptemberDirect2017]      MONEY         NULL,
    [SeptemberIndirect2017]    MONEY         NULL,
    [OctoberDirect2017]        MONEY         NULL,
    [OctoberIndirect2017]      MONEY         NULL,
    [NovemberDirect2017]       MONEY         NULL,
    [NovemberIndirect2017]     MONEY         NULL,
    [DecemberDirect2017]       MONEY         NULL,
    [DecemberIndirect2017]     MONEY         NULL,
    [JanuaryDirect2018]        MONEY         NULL,
    [JanuaryIndirect2018]      MONEY         NULL,
    [FebruaryDirect2018]       MONEY         NULL,
    [FebruaryIndirect2018]     MONEY         NULL,
    [MarchDirect2018]          MONEY         NULL,
    [MarchIndirect2018]        MONEY         NULL,
    [AprilDirect2018]          MONEY         NULL,
    [AprilIndirect2018]        MONEY         NULL,
    [MayDirect2018]            MONEY         NULL,
    [MayIndirect2018]          MONEY         NULL,
    [JuneDirect2018]           MONEY         NULL,
    [JuneIndirect2018]         MONEY         NULL,
    [JulyDirect2018]           MONEY         NULL,
    [JulyIndirect2018]         MONEY         NULL,
    [AugustDirect2018]         MONEY         NULL,
    [AugustIndirect2018]       MONEY         NULL,
    [SeptemberDirect2018]      MONEY         NULL,
    [SeptemberIndirect2018]    MONEY         NULL,
    [OctoberDirect2018]        MONEY         NULL,
    [OctoberIndirect2018]      MONEY         NULL,
    [NovemberDirect2018]       MONEY         NULL,
    [NovemberIndirect2018]     MONEY         NULL,
    [DecemberDirect2018]       MONEY         NULL,
    [DecemberIndirect2018]     MONEY         NULL,
    [JanuaryDirect2019]        MONEY         NULL,
    [JanuaryIndirect2019]      MONEY         NULL,
    [FebruaryDirect2019]       MONEY         NULL,
    [FebruaryIndirect2019]     MONEY         NULL,
    [MarchDirect2019]          MONEY         NULL,
    [MarchIndirect2019]        MONEY         NULL,
    [AprilDirect2019]          MONEY         NULL,
    [AprilIndirect2019]        MONEY         NULL,
    [MayDirect2019]            MONEY         NULL,
    [MayIndirect2019]          MONEY         NULL,
    [JuneDirect2019]           MONEY         NULL,
    [JuneIndirect2019]         MONEY         NULL,
    [JulyDirect2019]           MONEY         NULL,
    [JulyIndirect2019]         MONEY         NULL,
    [AugustDirect2019]         MONEY         NULL,
    [AugustIndirect2019]       MONEY         NULL,
    [SeptemberDirect2019]      MONEY         NULL,
    [SeptemberIndirect2019]    MONEY         NULL,
    [OctoberDirect2019]        MONEY         NULL,
    [OctoberIndirect2019]      MONEY         NULL,
    [NovemberDirect2019]       MONEY         NULL,
    [NovemberIndirect2019]     MONEY         NULL,
    [DecemberDirect2019]       MONEY         NULL,
    [DecemberIndirect2019]     MONEY         NULL,
    [CIACSpend]                MONEY         NULL,
    [CIACBudget]               MONEY         NULL,
    [FutureYearsSpendInfinium] MONEY         NULL,
    [FutureYearsSpend]         MONEY         NULL,
    [JanuaryDirect2020]        MONEY         NULL,
    [JanuaryIndirect2020]      MONEY         NULL,
    [FebruaryDirect2020]       MONEY         NULL,
    [FebruaryIndirect2020]     MONEY         NULL,
    [MarchDirect2020]          MONEY         NULL,
    [MarchIndirect2020]        MONEY         NULL,
    [AprilDirect2020]          MONEY         NULL,
    [AprilIndirect2020]        MONEY         NULL,
    [MayDirect2020]            MONEY         NULL,
    [MayIndirect2020]          MONEY         NULL,
    [JuneDirect2020]           MONEY         NULL,
    [JuneIndirect2020]         MONEY         NULL,
    [JulyDirect2020]           MONEY         NULL,
    [JulyIndirect2020]         MONEY         NULL,
    [AugustDirect2020]         MONEY         NULL,
    [AugustIndirect2020]       MONEY         NULL,
    [SeptemberDirect2020]      MONEY         NULL,
    [SeptemberIndirect2020]    MONEY         NULL,
    [OctoberDirect2020]        MONEY         NULL,
    [OctoberIndirect2020]      MONEY         NULL,
    [NovemberDirect2020]       MONEY         NULL,
    [NovemberIndirect2020]     MONEY         NULL,
    [DecemberDirect2020]       MONEY         NULL,
    [DecemberIndirect2020]     MONEY         NULL,
    [JanuaryDirect2021]        MONEY         NULL,
    [JanuaryIndirect2021]      MONEY         NULL,
    [FebruaryDirect2021]       MONEY         NULL,
    [FebruaryIndirect2021]     MONEY         NULL,
    [MarchDirect2021]          MONEY         NULL,
    [MarchIndirect2021]        MONEY         NULL,
    [AprilDirect2021]          MONEY         NULL,
    [AprilIndirect2021]        MONEY         NULL,
    [MayDirect2021]            MONEY         NULL,
    [MayIndirect2021]          MONEY         NULL,
    [JuneDirect2021]           MONEY         NULL,
    [JuneIndirect2021]         MONEY         NULL,
    [JulyDirect2021]           MONEY         NULL,
    [JulyIndirect2021]         MONEY         NULL,
    [AugustDirect2021]         MONEY         NULL,
    [AugustIndirect2021]       MONEY         NULL,
    [SeptemberDirect2021]      MONEY         NULL,
    [SeptemberIndirect2021]    MONEY         NULL,
    [OctoberDirect2021]        MONEY         NULL,
    [OctoberIndirect2021]      MONEY         NULL,
    [NovemberDirect2021]       MONEY         NULL,
    [NovemberIndirect2021]     MONEY         NULL,
    [DecemberDirect2021]       MONEY         NULL,
    [DecemberIndirect2021]     MONEY         NULL,
    [JanuaryDirect2022]        MONEY         NULL,
    [JanuaryIndirect2022]      MONEY         NULL,
    [FebruaryDirect2022]       MONEY         NULL,
    [FebruaryIndirect2022]     MONEY         NULL,
    [MarchDirect2022]          MONEY         NULL,
    [MarchIndirect2022]        MONEY         NULL,
    [AprilDirect2022]          MONEY         NULL,
    [AprilIndirect2022]        MONEY         NULL,
    [MayDirect2022]            MONEY         NULL,
    [MayIndirect2022]          MONEY         NULL,
    [JuneDirect2022]           MONEY         NULL,
    [JuneIndirect2022]         MONEY         NULL,
    [JulyDirect2022]           MONEY         NULL,
    [JulyIndirect2022]         MONEY         NULL,
    [AugustDirect2022]         MONEY         NULL,
    [AugustIndirect2022]       MONEY         NULL,
    [SeptemberDirect2022]      MONEY         NULL,
    [SeptemberIndirect2022]    MONEY         NULL,
    [OctoberDirect2022]        MONEY         NULL,
    [OctoberIndirect2022]      MONEY         NULL,
    [NovemberDirect2022]       MONEY         NULL,
    [NovemberIndirect2022]     MONEY         NULL,
    [DecemberDirect2022]       MONEY         NULL,
    [DecemberIndirect2022]     MONEY         NULL
);

