CREATE TABLE [QBR].[TBL_COMPLETED_ORDERS] (
    [DOCNO]        INT           NULL,
    [REQ]          VARCHAR (10)  NULL,
    [ACT]          VARCHAR (10)  NULL,
    [BUILD]        VARCHAR (20)  NULL,
    [BUILD_IOF]    VARCHAR (255) NULL,
    [BUILD_OSP]    VARCHAR (255) NULL,
    [INIT]         DATETIME      NULL,
    [CLEAN]        DATETIME      NULL,
    [DD]           DATETIME      NULL,
    [COMP_DT]      DATETIME      NULL,
    [DD_COMP]      DATETIME      NULL,
    [NC]           VARCHAR (5)   NULL,
    [PROD]         VARCHAR (15)  NULL,
    [PNUM]         VARCHAR (25)  NULL,
    [PON]          VARCHAR (25)  NULL,
    [CKT]          VARCHAR (75)  NULL,
    [ICSC]         VARCHAR (10)  NULL,
    [ACNA]         VARCHAR (10)  NULL,
    [WHY_MISS1]    VARCHAR (10)  NULL,
    [MISS_REASON1] VARCHAR (100) NULL,
    [PROJ]         VARCHAR (25)  NULL,
    [STATE]        VARCHAR (2)   NULL,
    [REGION]       VARCHAR (15)  NULL,
    [PRODUCT]      VARCHAR (25)  NULL,
    [PRODUCT2]     VARCHAR (15)  NULL,
    [SEI]          VARCHAR (10)  NULL,
    [BDW]          VARCHAR (10)  NULL,
    [DD_MET]       FLOAT (53)    NULL,
    [DLR]          VARCHAR (10)  NULL,
    [UPDATED_DT]   DATE          NULL
);

