SELECT PON, MAX(INIT_AS) INIT_ASR, MAX(FIRST_CLEAN) FIRST_CLEAN, MAX(CLEAN_AS) CLEAN_ASR, MAX(INIT_CONF) INIT_CONF, MAX(CLEAN_CONF) CLEAN_CONF
FROM(
--
SELECT PON, MIN(DT) INIT_AS, NULL FIRST_CLEAN, MAX(DT) CLEAN_AS, NULL INIT_CONF, NULL CLEAN_CONF
FROM (
SELECT PON, VERSION, ORDERSTATUS, TRUNC(CREATIONDATETIME) DT
FROM WHSL_ADV_HIST.VFO_ORDERHISTORYINFO_THIST ORD
WHERE PON IN (
'7NSC2006679'
)
AND ORDERSTATUS IN ('Accepted_Submitted')
)
GROUP BY PON
--
UNION ALL
--
SELECT PON, NULL INIT_AS, TRUNC(FIRST_CLEAN) FIRST_CLEAN, NULL CLEAN_AS, NULL INIT_CONF, NULL CLEAN_CONF
FROM (
--
SELECT SUBQ1.PON, CAST(MAX(VFO2.CREATIONDATETIME) AS DATE) AS FIRST_CLEAN
  FROM (      
--
SELECT PON, CAST(MIN(CREATIONDATETIME) AS DATE) FIRST_CONF_DT
FROM WHSL_ADV_HIST.VFO_ORDERHISTORYINFO_THIST ORD
WHERE ORDERSTATUS IN ('Confirmed_Submitted','Confirmed_Sent')
AND PON IN (
'7NSC2006679'
) 
GROUP BY PON
) SUBQ1,
--
  WHSL_ADV_HIST.VFO_ORDERHISTORYINFO_THIST VFO2
  WHERE SUBQ1.PON = VFO2.PON
  AND VFO2.CREATIONDATETIME < SUBQ1.FIRST_CONF_DT
  AND VFO2.ORDERSTATUS = 'Accepted_Submitted'
  GROUP BY SUBQ1.PON
)
--
UNION ALL
--
SELECT PON, NULL INIT_AS, NULL FIRST_CLEAN, NULL CLEAN_AS, MIN(DT) INIT_CONF, MAX(DT) CLEAN_CONF
FROM (
SELECT PON, VERSION, ORDERSTATUS, TRUNC(CREATIONDATETIME) DT
FROM WHSL_ADV_HIST.VFO_ORDERHISTORYINFO_THIST ORD
WHERE PON IN (
'7NSC2006679'
)
AND ORDERSTATUS IN ('Confirmed_Submitted','Confirmed_Sent')
)
GROUP BY PON
--
)
GROUP BY PON;

