SELECT DISTINCT C.EXCHANGE_CARRIER_CIRCUIT_ID CKT, C.STATUS, SR.ACNA, SR.DOCUMENT_NUMBER, EVC_IND, TRUNC(ACTUAL_COMPLETION_DATE) DD_COMP,
       ASR.SERVICE_AND_PRODUCT_ENHANC_COD UNI_SPEC, PROMOTION_NBR PNUM, ASR.SUPPLEMENT_TYPE SUPP, ASR.ACTIVITY_INDICATOR ACT,
       ASR.LATA_NUMBER LATA, CO.LATA_NUMBER, A.ADDR_LN1 ADDRESS, GA2.INSTANCE_VALUE CITY, GA.INSTANCE_VALUE_ABBREV STATE,C.CIRCUIT_DESIGN_ID, 
       CASE WHEN CUD.UNI_OR_NNI = '435' THEN 'UNI'
            WHEN CUD.UNI_OR_NNI = '436' THEN 'NNI'
            ELSE NULL END UNI_OR_NNI        
FROM SERV_REQ SR, 
     ACCESS_SERVICE_REQUEST ASR, 
     TASK T, 
     ASR_USER_DATA AUD,
     SERVICE_REQUEST_CIRCUIT SRC, 
     CIRCUIT C,
     SERV_ITEM SI,
     (SELECT DISTINCT *
        FROM (SELECT D.DESIGN_ID,
                     D.ISSUE_NBR,
                     D.SERV_ITEM_ID,
                     D.ISSUE_STATUS,
                     ROW_NUMBER() OVER (PARTITION BY SERV_ITEM_ID ORDER BY ISSUE_STATUS ASC) R
                   FROM ASAP.DESIGN D)
                    WHERE R = 1) D,
     (SELECT DISTINCT *
        FROM (SELECT D.LOCATION_ID,
                     D.ADDRESS_ID,
                     D.ACTIVE_IND,
                     ROW_NUMBER() OVER (PARTITION BY LOCATION_ID ORDER BY ADDRESS_ID DESC) R
                   FROM ASAP.NET_LOC_ADDR D
                    WHERE ACTIVE_IND = 'Y')
                     WHERE R = 1) NLA,                            
     ADDRESS A,
     GA_INSTANCE GA,
     GA_INSTANCE GA2,
     NETWORK_LOCATION NL,
     CENTRAL_OFFICE_EXCHANGE_AREA CO,
     CIRCUIT_USER_DATA CUD
     
WHERE SR.DOCUMENT_NUMBER = ASR.DOCUMENT_NUMBER
  AND SR.DOCUMENT_NUMBER = T.DOCUMENT_NUMBER
  AND SR.DOCUMENT_NUMBER = AUD.DOCUMENT_NUMBER (+)
  AND SR.DOCUMENT_NUMBER = SRC.DOCUMENT_NUMBER
  AND SRC.CIRCUIT_DESIGN_ID = C.CIRCUIT_DESIGN_ID (+)
  AND C.CIRCUIT_DESIGN_ID = SI.CIRCUIT_DESIGN_ID (+)
  AND SI.SERV_ITEM_ID = D.SERV_ITEM_ID (+)
  AND C.LOCATION_ID = NLA.LOCATION_ID (+)
  AND NLA.ADDRESS_ID = A.ADDRESS_ID (+)
  AND A.GA_INSTANCE_ID_STATE_CD = GA.GA_INSTANCE_ID (+)
  AND A.GA_INSTANCE_ID_CITY = GA2.GA_INSTANCE_ID (+)
  AND C.LOCATION_ID_2 = NL.LOCATION_ID(+)
  AND NL.EXCHANGE_AREA_CLLI = CO.EXCHANGE_AREA_CLLI (+)
  AND C.CIRCUIT_DESIGN_ID = CUD.CIRCUIT_DESIGN_ID (+)
  AND T.TASK_TYPE = 'DD'
  AND (EVC_IND = 'B' OR EVC_IND IS NULL)
  AND T.ACTUAL_COMPLETION_DATE IS NOT NULL
  AND SUBSTR(ASR.NETWORK_CHANNEL_SERVICE_CODE,1,1) = 'K'
  AND SUBSTR(C.EXCHANGE_CARRIER_CIRCUIT_ID,4,2) <> 'VL'
  AND SR.ACTIVITY_IND IN ('N','C','R')
  --AND SR.DOCUMENT_NUMBER in ('3649251')
  --AND TO_CHAR(T.ACTUAL_COMPLETION_DATE,'yyyymmdd') >= '20211017'     --CHANGE DATE TO SHOW THE PREVIOUS SUNDAY  
  AND SR.ACNA in ('AAV','AVA','ATX','LOA','SBB','SBZ','SUV','TPM')
  AND C.STATUS NOT IN ('8','A')
  AND (ASR.SUPPLEMENT_TYPE <> 1 OR ASR.SUPPLEMENT_TYPE IS NULL)
ORDER BY 1, 6 DESC;
;



SELECT lata_number FROM ACCESS_SERVICE_REQUEST
WHERE DOCUMENT_NUMBER = '3616568';


SELECT * FROM NETWORK_LOCATION
WHERE location_id in ('819920','3173034')
;

SELECT * FROM CIRCUIT
WHERE EXCHANGE_CARRIER_CIRCUIT_ID = '39/HCGS/381054/   /CZUC/   '
;

select * from lata
where lata_number in ('730','122','420','961')
;

select *
from CENTRAL_OFFICE_EXCHANGE_AREA
where EXCHANGE_AREA_CLLI like 'ABCDEF%'
;

select * from service_request_circuit
where circuit_design_id = '10636821';