SELECT REPLACE(REPLACE(CKT,'/'),' ') CLEAN, CKT, CIRCUIT_DESIGN_ID, PNUM, ADDRESS, CITY, STATE, 
       CASE WHEN UNI_OR_NNI = '435' THEN 'UNI'
            WHEN UNI_OR_NNI = '436' THEN 'NNI'
            WHEN SUBSTR(CKT,4,2) = 'VL' THEN 'EVC'
            ELSE 'CHECK' END CKT_TYPE,
       CASE WHEN LOS = ('EBE') THEN 'Silver'
            WHEN LOS = ('EBS') THEN 'Silver'
            WHEN LOS = ('EPD') THEN 'Gold' 
            WHEN LOS = ('ERT') THEN 'Platinum'
            WHEN LOS = ('BASIC') THEN 'Silver'
            WHEN LOS = ('PD') THEN 'Gold' 
            WHEN LOS = ('RT') THEN 'Platinum'
            WHEN EVC_SPEC = 'EVPLSE' THEN 'Silver'
            WHEN EVC_SPEC = 'EPATHES' THEN 'Silver'
            WHEN EVC_SPEC = 'EPATHEG' THEN 'Gold'
            WHEN EVC_SPEC = 'EPATHEP' THEN 'Platinum'
            ELSE NULL END CKT_LEVEL,
       CASE WHEN ACT = 'N' THEN DD_COMP ELSE NULL END INSTALL_DT, 
       ACT, DD_COMP     
 FROM (           
SELECT SR.DOCUMENT_NUMBER,  
       TRUNC(T.ACTUAL_COMPLETION_DATE)  DD_COMP,
       MAX(ASR.NETWORK_CHANNEL_SERVICE_CODE) KEEP (DENSE_RANK LAST ORDER BY ASR.LAST_MODIFIED_DATE) NC, 
       MAX(ASR.PON) KEEP (DENSE_RANK LAST ORDER BY ASR.LAST_MODIFIED_DATE) PON,  
       MAX(SR.ACNA) ACNA,  
       MAX(ASR.ACTIVITY_INDICATOR) KEEP (DENSE_RANK LAST ORDER BY ASR.LAST_MODIFIED_DATE) ACT,     
       MAX(ASR.SUPPLEMENT_TYPE) KEEP (DENSE_RANK LAST ORDER BY ASR.LAST_MODIFIED_DATE) SUPP,
       MAX(ASR.EVC_IND) KEEP (DENSE_RANK LAST ORDER BY ASR.LAST_MODIFIED_DATE) EVC_IND,
       MAX(ASR.PROMOTION_NBR) KEEP (DENSE_RANK LAST ORDER BY ASR.LAST_MODIFIED_DATE) PNUM,
       C.EXCHANGE_CARRIER_CIRCUIT_ID CKT,  
       C.CIRCUIT_DESIGN_ID,
       MAX(C.SERVICE_TYPE_CODE) KEEP (DENSE_RANK LAST ORDER BY C.LAST_MODIFIED_DATE) SVC_CD,
       MAX(ASR.LATA_NUMBER) KEEP (DENSE_RANK LAST ORDER BY ASR.LAST_MODIFIED_DATE) LATA,
       UNI_OR_NNI,
       ELS.LVL_OF_SERV_NM AS LOS,
       ELS.SERVICE_AND_PRODUCT_ENHANC_COD AS EVC_SPEC, 
       TRIM(ADDR.STREET_NBR||' '||ADDR.STREET_NM||' '||ADDR.STREET_SUF) ADDRESS,
       GA2.INSTANCE_VALUE CITY,
       GA.INSTANCE_VALUE_ABBREV STATE      
FROM ACCESS_SERVICE_REQUEST ASR,
     SERV_REQ SR,
     SERVICE_REQUEST_CIRCUIT SRC,
     TASK T,
     CIRCUIT C,
     CIRCUIT_USER_DATA CUD,
     EVC_UNI_MAP EUM,
     EVC_LVL_SERV ELS,
     (SELECT DISTINCT *
        FROM (SELECT D.LOCATION_ID,
                     D.ADDRESS_ID,
                     D.ACTIVE_IND,
                     ROW_NUMBER() OVER (PARTITION BY LOCATION_ID ORDER BY ADDRESS_ID DESC) R
                   FROM ASAP.NET_LOC_ADDR D
                    WHERE ACTIVE_IND = 'Y')
                     WHERE R = 1) NLA,
     ADDRESS ADDR,
     GA_INSTANCE GA,
     GA_INSTANCE GA2
WHERE SR.DOCUMENT_NUMBER = ASR.DOCUMENT_NUMBER
  AND SR.DOCUMENT_NUMBER = SRC.DOCUMENT_NUMBER
  AND SRC.CIRCUIT_DESIGN_ID = C.CIRCUIT_DESIGN_ID (+)
  AND SR.DOCUMENT_NUMBER = EUM.DOCUMENT_NUMBER (+)
  AND EUM.DOCUMENT_NUMBER = ELS.DOCUMENT_NUMBER (+)
  AND EUM.EVC_UNI_MAP_ID = ELS.EVC_UNI_MAP_ID(+)
  AND SR.DOCUMENT_NUMBER = T.DOCUMENT_NUMBER
  AND C.CIRCUIT_DESIGN_ID = CUD.CIRCUIT_DESIGN_ID (+)
  AND C.LOCATION_ID = NLA.LOCATION_ID (+)
  AND NLA.ADDRESS_ID = ADDR.ADDRESS_ID (+)
  AND ADDR.GA_INSTANCE_ID_STATE_CD = GA.GA_INSTANCE_ID (+)
  AND ADDR.GA_INSTANCE_ID_CITY = GA2.GA_INSTANCE_ID (+)
  AND TO_CHAR(T.ACTUAL_COMPLETION_DATE,'yyyymm') = '202311'    --CURRENT REPORTING MONTH 
  AND ASR.REQUEST_TYPE IN ('S','E')
  AND ASR.ACTIVITY_INDICATOR IN ('N','C','R')
  AND ASR.ORDER_TYPE = 'ASR'
  AND T.TASK_TYPE = 'DD'
  AND ASR.PROMOTION_NBR in ('EPAV001999SCM792','EPAV001ATXSCM792BK')
  AND SR.ACNA IN ('AAV','AVA','ATX','LOA','SBB','SBZ','SUV','TPM')
GROUP BY SR.DOCUMENT_NUMBER, T.ACTUAL_COMPLETION_DATE, UNI_OR_NNI, C.EXCHANGE_CARRIER_CIRCUIT_ID,
         C.CIRCUIT_DESIGN_ID, ELS.LVL_OF_SERV_NM, ELS.SERVICE_AND_PRODUCT_ENHANC_COD, 
         ADDR.STREET_NBR, ADDR.STREET_NM, ADDR.STREET_SUF, GA2.INSTANCE_VALUE, GA.INSTANCE_VALUE_ABBREV
)
WHERE (SUPP <> 1 OR SUPP IS NULL) 
ORDER BY INSTALL_DT, DOCUMENT_NUMBER        