SELECT REPLACE(REPLACE(REPLACE(CKT,'/'),'-'),' ') AS CLEAN_ID,
       CKT, B.CIRCUIT_DESIGN_ID, PNUM, ADDR_LN1, GA2.INSTANCE_VALUE CITY, GA.INSTANCE_VALUE_ABBREV STATE, 
       CASE WHEN CUD.UNI_OR_NNI = '436' THEN 'NNI'
            WHEN CUD.UNI_OR_NNI = '435' THEN 'UNI'
            WHEN SUBSTR(CKT,4,2) = 'VL' THEN 'EVC'
            ELSE NULL END PROD_TYPE,
       STATUS     
FROM (
SELECT SI.SERV_ITEM_DESC CKT, SI.STATUS, C.CIRCUIT_DESIGN_ID, LOCATION_ID, CA_VALUE PNUM
FROM (
SELECT DISTINCT CIRCUIT_DESIGN_ID, CA_VALUE, CA_VALUE_LABEL
      FROM (
            SELECT CIRCUIT_DESIGN_ID, 
            CA_VALUE, 
            CA_VALUE_LABEL,
            ROW_NUMBER() OVER (PARTITION BY CIRCUIT_DESIGN_ID ORDER BY CONN_CA_VALUE_ID DESC) R
         FROM CONN_CA_VALUE
          WHERE CA_ID = '100070' )  --UNI IP   
              WHERE R = 1
              AND CA_VALUE IN ('EPAV001ATXSCM792BK','EPAV001999SCM792')  
) A, SERV_ITEM SI, CIRCUIT C
WHERE A.CIRCUIT_DESIGN_ID = SI.CIRCUIT_DESIGN_ID
  AND A.CIRCUIT_DESIGN_ID = C.CIRCUIT_DESIGN_ID
--and SI.STATUS = '6'
--AND A.CIRCUIT_DESIGN_ID = '5082012'
) B, 
  (SELECT DISTINCT *
        FROM (SELECT D.LOCATION_ID,
                     D.ADDRESS_ID,
                     D.ACTIVE_IND,
                     ROW_NUMBER() OVER (PARTITION BY LOCATION_ID ORDER BY ADDRESS_ID DESC) R
                   FROM ASAP.NET_LOC_ADDR D
                    WHERE ACTIVE_IND = 'Y')
                     WHERE R = 1) NLA,
  ADDRESS ADDR,
  GA_INSTANCE GA,
  GA_INSTANCE GA2,                   
  CIRCUIT_USER_DATA CUD                   
WHERE B.LOCATION_ID = NLA.LOCATION_ID (+)
  AND NLA.ADDRESS_ID = ADDR.ADDRESS_ID (+)
  AND ADDR.GA_INSTANCE_ID_STATE_CD = GA.GA_INSTANCE_ID (+)
  AND ADDR.GA_INSTANCE_ID_CITY = GA2.GA_INSTANCE_ID (+)
  AND B.CIRCUIT_DESIGN_ID = CUD.CIRCUIT_DESIGN_ID
;


