SELECT *
FROM (
SELECT ASR.DOCUMENT_NUMBER,
       C.EXCHANGE_CARRIER_CIRCUIT_ID CKT,
       MAX(ASR.PON) KEEP (DENSE_RANK LAST ORDER BY ASR.LAST_MODIFIED_DATE) PON, 
       MAX(ASR.PROJECT_IDENTIFICATION) KEEP (DENSE_RANK LAST ORDER BY ASR.LAST_MODIFIED_DATE) PROJECT,
       MIN(ACCEPTANCE_DATE) KEEP (DENSE_RANK LAST ORDER BY AUD.LAST_MODIFIED_DATE) ACCEPT_DT, 
       TRUNC(T.ACTUAL_COMPLETION_DATE) DD_COMP,
       MAX(SR.ACNA) ACNA,  
       MAX(ASR.ACTIVITY_INDICATOR) KEEP (DENSE_RANK LAST ORDER BY ASR.LAST_MODIFIED_DATE) ACT, 
       MAX(ASR.NETWORK_CHANNEL_SERVICE_CODE) KEEP (DENSE_RANK LAST ORDER BY ASR.LAST_MODIFIED_DATE) NC,
       MAX(ASR.SUPPLEMENT_TYPE) KEEP (DENSE_RANK LAST ORDER BY ASR.LAST_MODIFIED_DATE) SUPP,   
       MAX(ASR.EVC_IND) KEEP (DENSE_RANK LAST ORDER BY ASR.LAST_MODIFIED_DATE) EVC_IND
FROM ACCESS_SERVICE_REQUEST ASR,
     ASR_USER_DATA AUD,
     SERV_REQ SR,
     NETWORK_LOCATION NL1,
     TASK T,
     CIRCUIT C,
     SERVICE_REQUEST_CIRCUIT SRC
WHERE SR.DOCUMENT_NUMBER = ASR.DOCUMENT_NUMBER
  AND SR.DOCUMENT_NUMBER = AUD.DOCUMENT_NUMBER
  AND SR.DOCUMENT_NUMBER = T.DOCUMENT_NUMBER
  AND SR.DOCUMENT_NUMBER = SRC.DOCUMENT_NUMBER (+)
  AND SRC.CIRCUIT_DESIGN_ID = C.CIRCUIT_DESIGN_ID (+)
  AND C.LOCATION_ID = NL1.LOCATION_ID(+)
  AND TO_CHAR(T.ACTUAL_COMPLETION_DATE,'yyyymm') = ('202311')      --CHANGE DATE TO SHOW THE PREVIOUS SUNDAY     
  AND ASR.REQUEST_TYPE IN ('S','E')
  AND ASR.ACTIVITY_INDICATOR IN ('D')
  AND ASR.ORDER_TYPE = 'ASR' 
  AND T.TASK_TYPE = 'DD'
  AND SR.ACNA IN ('AAV','AVA','ATX','LOA','SBB','SBZ','SUV','TPM')
  --AND EVC_IND IS NOT NULL
  AND SUBSTR(C.EXCHANGE_CARRIER_CIRCUIT_ID,4,1) in ('K', 'V')
GROUP BY ASR.DOCUMENT_NUMBER, ASR.REQUEST_TYPE, T.ACTUAL_COMPLETION_DATE, C.EXCHANGE_CARRIER_CIRCUIT_ID
)
WHERE (SUPP <> 1 OR SUPP IS NULL)

ORDER BY 6,2;