CREATE TABLE STG_DPI_VW.[ACOCUFL]
(
	[CO] [varchar](4) NULL,
	[IXC] [varchar](4) NULL,
	[ACCTTYPE] [varchar](1) NULL,
	[FACTYPE] [varchar](2) NULL,
	[OCCDATE] [numeric](8, 0) NULL,
	[SO] [varchar](12) NULL,
	[CIRCUIT] [varchar](47) NULL,
	[LEG] [varchar](4) NULL,
	[AZIND] [varchar](1) NULL,
	[OCN] [varchar](4) NULL,
	[SWSPL] [varchar](2) NULL,
	[OCCTYPE] [varchar](1) NULL,
	[USOC] [varchar](8) NULL,
	[JURIS] [varchar](1) NULL,
	[FROMDATE] [date] NULL,
	[THRUDATE] [date] NULL,
	[OCUIND] [varchar](1) NULL,
	[BILLDATE] [date] NULL,
	[BEENAPPL] [varchar](1) NULL,
	[STATE] [varchar](2) NULL,
	[PHRASECODE] [varchar](3) NULL,
	[BIP] [numeric](3, 0) NULL,
	[BIP2] [numeric](3, 0) NULL,
	[PERMONTH] [numeric](11, 2) NULL,
	[AMOUNT] [numeric](11, 2) NULL,
	[SURCHARGE] [varchar](1) NULL,
	[TAX] [varchar](1) NULL,
	[OCCDAYS] [numeric](5, 0) NULL,
	[USOCDESIG] [varchar](1) NULL,
	[LEC] [varchar](4) NULL,
	[QTY] [numeric](6, 0) NULL,
	[TETQTYL] [varchar](4) NULL,
	[TETREVL] [varchar](4) NULL,
	[FLEXBAND] [varchar](3) NULL,
	[MILERDT] [numeric](3, 0) NULL,
	[GEOCODE] [varchar](9) NULL,
	[TAXCAT] [varchar](2) NULL,
	[TAXSER] [varchar](2) NULL,
	[SPLITPCT] [numeric](3, 0) NULL,
	[SPLITGEO] [varchar](9) NULL,
	[PLANLVL] [numeric](1, 0) NULL,
	[USORATE] [varchar](6) NULL,
	[USOCOS] [varchar](5) NULL,
	[USOCOMP] [varchar](1) NULL,
	[USOTIER] [varchar](3) NULL,
	[USOSEQ] [numeric](9, 0) NULL,
	[USOFAC] [numeric](11, 4) NULL,
	[USOMON] [numeric](11, 4) NULL,
	[FILLER1] [varchar](38) NULL,
	[UPDFUNC] [varchar](1) NULL,
	[UPDDATE] [date] NULL,
	[UPDTIME] [numeric](6, 0) NULL,
	[UPDOPID] [varchar](10) NULL,
	[DW_USER] [varchar](10) NULL,
	[DW_LOAD_TIMESTAMP] [datetime2](7) NULL,
	[BILL_SUBSYS_CD] [varchar](10) NULL
)
