USE [WAD_PRD_Integration];
GO

IF EXISTS (
    SELECT 1
    FROM [ADDRESS_BILLING].[CARS_ADDR_PRD_PIVOT]
    WHERE LEN([ADDRESS]) > 200
       OR LEN([CITY]) > 100
       OR LEN([STATE]) > 50
)
BEGIN
    PRINT 'ERROR: Some rows exceed the planned lengths for CARS_ADDR_PRD_PIVOT.';
    RETURN;
END

ALTER TABLE [ADDRESS_BILLING].[CARS_ADDR_PRD_PIVOT]
    ALTER COLUMN [ADDRESS] VARCHAR(200) NULL;
ALTER TABLE [ADDRESS_BILLING].[CARS_ADDR_PRD_PIVOT]
    ALTER COLUMN [CITY]    VARCHAR(100) NULL;
ALTER TABLE [ADDRESS_BILLING].[CARS_ADDR_PRD_PIVOT]
    ALTER COLUMN [STATE]   VARCHAR(50)  NULL;

-- Possibly also fix ZIP:
-- ALTER TABLE [ADDRESS_BILLING].[CARS_ADDR_PRD_PIVOT]
--     ALTER COLUMN [ZIP] VARCHAR(20) NULL;

CREATE NONCLUSTERED INDEX [IX_CARS_PIVOT_AddressCityState]
    ON [ADDRESS_BILLING].[CARS_ADDR_PRD_PIVOT] ([ADDRESS], [CITY], [STATE])
    INCLUDE ([ZIP], [BB], [BUS_DIA], [VOICE], [WHSL_DIA])
    WITH (
        FILLFACTOR = 90,
        SORT_IN_TEMPDB = ON,
        ONLINE = ON
    );
GO
