CREATE TABLE [LZ].[M6_CIRCUIT_INVENTORY_SITE_MAPPING](
	[EXCHANGE_CARRIER_CIRCUIT_ID] [varchar](100) NULL,
	[SITE_ID] [varchar](100) NULL,
	[STATUS] [varchar](1) NULL,
	[CLEAN_ID] [varchar](100) NULL,
	[SERVICE_TYPE_CODE] [varchar](10) NULL,
	[ACNA] [varchar](5) NULL,
	[IN_SERVICE_DATE] [varchar](500) NULL,
	[DD_COMPLETION_DATE] [varchar](500) NULL
)