CREATE TABLE [LZ].[TBL_SR_EMBEDDED_BASE]
(
	CKT_ID VARCHAR(50) NOT NULL 
	,CLEC_ID VARCHAR(10)
	,SERVICE_TYPE_CAT VARCHAR(50)
	,STATE_CD VARCHAR(5)
	,SVC_CD VARCHAR(5)
	,PRODUCT VARCHAR(50)
	,BDW VARCHAR(10)
	,STATUS VARCHAR(2)
	,SI_STATUS VARCHAR(2)

)