CREATE TABLE LZ.[TBL_COMPLETED_ORDERS]
(
 [DOCNO] int,
    [REQ] varchar(1),
    [ACT] varchar(1),
    [BUILD] varchar(11),
    [BUILD_IOF] varchar(255),
    [BUILD_OSP] varchar(255),
    [UNI_OR_NNI] varchar(255),
    [INIT] datetime,
    [CLEAN] datetime,
    [DD] datetime,
    [COMP_DT] datetime,
    [DD_COMP] datetime,
    [NC] varchar(2),
    [PROD] varchar(8),
    [PNUM] varchar(20),
    [PON] varchar(16),
    [CKT] varchar(53),
    [ICSC] varchar(4),
    [ACNA] varchar(3),
    [COMP] varchar(3),
    [WHY_MISS1] varchar(4),
    [MISS_REASON1] varchar(79),
    [PROJ] varchar(16),
    [STATE] varchar(2),
    [REGION] varchar(7),
    [PRODUCT] varchar(200),
    [PRODUCT2] varchar(200),
    [SEI] varchar(1),
    [BDW] varchar(4),
    [DD_MET] float,
    [DLR] varchar(3),
    [CRDD] VARCHAR(10),
    [CRDD_STATUS] float
)
