CREATE TABLE LZ.[TBL_VFO_PONS]
([DOCNO] VARCHAR(15) NOT NULL,
    [REQ] varchar(1),
    [ACT] varchar(1),
    [BUILD] varchar(25),
    [BUILD_IOF] varchar(255),
    [BUILD_OSP] varchar(255),
    [INIT] datetime,
    [CLEAN] datetime,
    [DD] datetime,
    [COMP_DT] datetime,
    [DD_COMP] datetime,
    [NC] varchar(5),
    [PROD] varchar(15),
    [PNUM] varchar(20),
    [PON] varchar(20),
    [CKT] varchar(60),
    [ICSC] varchar(5),
    [ACNA] varchar(5),
    [WHY_MISS1] varchar(5),
    [MISS_REASON1] varchar(125),
    [PROJ] varchar(20),
    [STATE] varchar(2),
    [REGION] varchar(7),
    [PRODUCT] varchar(22),
    [PRODUCT2] varchar(8),
    [SEI] varchar(1),
    [BDW] varchar(4),
    [DD_MET] float,
    [DLR] varchar(3)
)
