CREATE TABLE LZ.[TBL_DELAY_ORDERS]
(
	DOCUMENT_NUMBER VARCHAR(25) NOT NULL,
	NOTES_ID VARCHAR(100),
	NOTE_TEXT VARCHAR(2500),
	USER_ID VARCHAR(50),
	LAST_MODIFIED_DT DATE,
	ACNA VARCHAR(10),
	COMP_DT DATE
)
