CREATE TABLE LZ.[TBL_WABB_SERVICE_ORDERS]
(
[ORDNO] [varchar](9) NULL,
	[ENV] [varchar](2) NULL,
	[PON] [varchar](20) NULL,
	[ACT] [varchar](1) NULL,
	[ORD_TYPE] [varchar](8) NULL,
	[SERV_TYPE] [varchar](3) NULL,
	[STATUS] [varchar](8) NULL,
	[WTN] [numeric](10, 0) NULL,
	[BTN] [numeric](10, 0) NULL,
	[SE_CODE] [varchar](5) NULL,
	[NETWORK] [varchar](10) NULL,
	[CCNA] [varchar](4) NULL,
	[CARRIER] [varchar](100) NULL,
	[CUSTNM] [varchar](30) NULL,
	[SO_CREATE_DT] [date] NULL,
	[SO_EFF_COMP_DT] [date] NULL,
	[SO_ACT_COMP_DT] [date] NULL,
	[POST_DT] [date] NULL,
	[AGING] [int] NULL,
	[AGING_GRP] [varchar](5) NULL,
	[ADDRESS] [varchar](4000) NULL,
	[CITY] [varchar](20) NULL,
	[STATE] [varchar](2) NULL,
	[ZIP] [varchar](5) NULL,
	[MRC] [numeric](15, 2) NULL,
	[TERM_CODE] [varchar](5) NULL,
	[TERM2] [varchar](13) NULL,
	[TERM_DESC] [varchar](10) NULL
)
