CREATE TABLE [LZ].[TBL_SAAFACTFEATUREMONTHLYSNAP_SUM](
	[DATESTART] [date] NULL,
	[WTN] [numeric](11, 0) NULL,
	[BTN] [varchar](10) NULL,
	[CARRIER] [varchar](50) NULL,
	[PRD_FAMLY_DS] [varchar](50) NULL,
	[NATRL_ACCT_CD] [varchar](3) NULL,
	[NATRL_ACCT_DS] [varchar](50) NULL,
	[INC_STMT_CAT_DS] [varchar](50) NULL,
	[CURRENTPRICE] [numeric](15, 5) NULL,
	[CURRENTQTY] [numeric](7, 0) NULL,
	[CURRENTAMT] [numeric](15, 5) NULL,
	[STATUSCODE] [varchar](1) NULL,
	[ENDINGACTIVE] [numeric](15, 0) NULL,
	[COUNTABLE] [nvarchar](1) NULL,
	[UNIT_COUNT_IND] [varchar](1) NULL,
	[ENV] [varchar](4) NULL,
	[CNTRL] [numeric](9, 0) NULL,
	[CNTRL_IND] [varchar](2) NULL,
	[ADDRESS] [varchar](155) NULL,
	[CITY] [varchar](32) NULL,
	[STATE] [varchar](2) NULL,
	[ZIPCODE] [varchar](5) NULL,
	[CLLI] [varchar](12) NULL,
	[LINEOFBUSINESS] [int] NULL,
	[TARIFF_CD] [varchar](3) NULL,
	[CREDITCLASSCODE] [varchar](1) NULL,
	[SERVICETYPECODE] [varchar](2) NULL,
	[PRODUCTSERVICECODE] [varchar](10) NULL,
	[RECURRINGNONRECURRING] [varchar](1) NULL,
	[DIRECT_SALES_REV_TYPE_CD] [smallint] NULL,
	[BILLINGADDRESS] [varchar](155) NULL,
	[BILLINGCITY] [varchar](32) NULL,
	[COMPANYNAME] [varchar](100) NULL,
	[FIRSTNAME] [varchar](30) NULL,
	[LASTNAME] [varchar](30) NULL,
	[CapableNetworkType] [varchar](15) NULL,
	[ServiceableNetworkType] [varchar](15) NULL,
	[ProvisionedNetworkType] [varchar](15) NULL,
	[ProvisionedSpeed] [varchar](20) NULL,
	[PURCHASEDSPEED] [varchar](20) NULL,
	[PurchasedTechnology] [varchar](10) NULL,
	[PRD_DS] [varchar](55) NULL,
	[PRD_RATE_TYPE_NM] [varchar](7) NULL,
	[PRD_RATE_TYPE_DS] [varchar](50) NULL,
	[PRD_GRP2_DS] [varchar](50) NULL,
	[PRD_GRP1_DS] [varchar](50) NULL,
	[PRD_GRP1_TYPE_DS] [varchar](50) NULL,
	[PRD_GRP2_TYPE_DS] [varchar](50) NULL,
	[PRD_SVC_CD_DS] [varchar](50) NULL,
	[CUST_NO] [varchar](10) NULL,
	[CUSTOMERNUMBER] [varchar](32) NULL,
	[ACCOUNTNUMBER] [varchar](32) NULL,
	[ACCT_CUST_TYPE_CD] [smallint] NULL,
	[ACCT_CUST_TYPE_DS] [varchar](30) NULL,
	[CUST_TYPE_DS] [varchar](30) NULL,
	[CUST_GRP_DS] [varchar](30) NULL,
	[CUST_FAMLY_DS] [varchar](30) NULL,
	[DEFAULT_CUST_IND] [varchar](1) NULL,
	[ACCT_JOIN_KEY] [int] NULL,
	[CUST_ACCT_JOIN_KEY] [varchar](16) NULL,
	[CUST_SEG_CD] [varchar](2) NULL,
	[CUST_SEG_NM] [varchar](40) NULL
);