CREATE TABLE LZ.[TBL_LSPANM]
(
	CCNA NVARCHAR(5)
	,ENV NVARCHAR(10)
	,STATE_CD NVARCHAR(2)
	,TARIFF NVARCHAR(10)
	,SUMMARY_TYPE NVARCHAR (20)
	,PRIMARY_CARRIER_NM NVARCHAR(250)
	,STN NVARCHAR(10)
	,DATE NVARCHAR(8)
	,OCN NVARCHAR(5)
	,CC NVARCHAR(5)
)
