CREATE TABLE [Brownfield].[BrownfieldByMatrix] (
    [Project]            NVARCHAR (50)  NULL,
    [Sub]                NVARCHAR (50)  NULL,
    [EMC]                NVARCHAR (10)  NULL,
    [111]                MONEY          NULL,
    [276]                MONEY          NULL,
    [277]                MONEY          NULL,
    [278]                MONEY          NULL,
    [279]                MONEY          NULL,
    [280]                MONEY          NULL,
    [281]                MONEY          NULL,
    [322]                MONEY          NULL,
    [329]                MONEY          NULL,
    [342]                MONEY          NULL,
    [343]                MONEY          NULL,
    [344]                MONEY          NULL,
    [345]                MONEY          NULL,
    [361]                MONEY          NULL,
    [362]                MONEY          NULL,
    [363]                MONEY          NULL,
    [364]                MONEY          NULL,
    [365]                MONEY          NULL,
    [367]                MONEY          NULL,
    [401]                MONEY          NULL,
    [405]                MONEY          NULL,
    [411]                MONEY          NULL,
    [412]                MONEY          NULL,
    [414]                MONEY          NULL,
    [415]                MONEY          NULL,
    [420]                MONEY          NULL,
    [421]                MONEY          NULL,
    [422]                MONEY          NULL,
    [423]                MONEY          NULL,
    [424]                MONEY          NULL,
    [425]                MONEY          NULL,
    [427]                MONEY          NULL,
    [428]                MONEY          NULL,
    [429]                MONEY          NULL,
    [434]                MONEY          NULL,
    [437]                MONEY          NULL,
    [440]                MONEY          NULL,
    [441]                MONEY          NULL,
    [445]                MONEY          NULL,
    [456]                MONEY          NULL,
    [457]                MONEY          NULL,
    [461]                MONEY          NULL,
    [471]                MONEY          NULL,
    [472]                MONEY          NULL,
    [473]                MONEY          NULL,
    [475]                MONEY          NULL,
    [477]                MONEY          NULL,
    [486]                MONEY          NULL,
    [487]                MONEY          NULL,
    [501]                MONEY          NULL,
    [502]                MONEY          NULL,
    [503]                MONEY          NULL,
    [504]                MONEY          NULL,
    [505]                MONEY          NULL,
    [544]                MONEY          NULL,
    [902]                MONEY          NULL,
    [939]                MONEY          NULL,
    [990]                MONEY          NULL,
    [991]                MONEY          NULL,
    [992]                MONEY          NULL,
    [993]                MONEY          NULL,
    [994]                MONEY          NULL,
    [995]                MONEY          NULL,
    [996]                MONEY          NULL,
    [997]                MONEY          NULL,
    [998]                MONEY          NULL,
    [999]                MONEY          NULL,
    [ClassOfPlant]       NVARCHAR (50)  NULL,
    [LinkCode]           NVARCHAR (50)  NULL,
    [JustificationCode]  NVARCHAR (50)  NULL,
    [ProjectStatusCode]  NVARCHAR (50)  NULL,
    [ProjectDescription] NVARCHAR (MAX) NULL
);

