CREATE TABLE [Brownfield].[LZ_BKSTIME00F] (
    [WorkDate] NVARCHAR (25) NULL,
    [CO#]      NVARCHAR (25) NULL,
    [PROJECT]  NVARCHAR (25) NULL,
    [SUBPROJ]  NVARCHAR (25) NULL,
    [Hours]    NVARCHAR (25) NULL,
    [CostCode] NVARCHAR (25) NULL
);

