CREATE TABLE [Brownfield].[LZ_BulkReelUsage] (
    [BulkUsageEntryID]         NVARCHAR (50)  NULL,
    [PROJECTNumber]            NVARCHAR (7)   NULL,
    [WarehouseCode]            NVARCHAR (50)  NULL,
    [Part#]                    NVARCHAR (50)  NULL,
    [MaterialDescription]      NVARCHAR (50)  NULL,
    [StorageLocation]          NVARCHAR (50)  NULL,
    [CableType]                NVARCHAR (50)  NULL,
    [G/LAccountCode]           NVARCHAR (100) NULL,
    [ACCOUNT#(AE/UG/BU)]       NVARCHAR (50)  NULL,
    [UseLocation]              NVARCHAR (50)  NULL,
    [UOM]                      NVARCHAR (50)  NULL,
    [InsideSEQ#]               NVARCHAR (50)  NULL,
    [OutsideSEQ#]              NVARCHAR (50)  NULL,
    [Usage]                    NVARCHAR (50)  NULL,
    [RemainingOnHandOSE]       NVARCHAR (50)  NULL,
    [State]                    NVARCHAR (50)  NULL,
    [ExchangeNumber]           NVARCHAR (50)  NULL,
    [Contractor]               NVARCHAR (50)  NULL,
    [Comments]                 NVARCHAR (MAX) NULL,
    [ReasonTaken]              NVARCHAR (MAX) NULL,
    [SubmittedBy]              NVARCHAR (50)  NULL,
    [SubmittedDateTime]        NVARCHAR (50)  NULL,
    [LOC1]                     NVARCHAR (50)  NULL,
    [MAIN]                     NVARCHAR (10)  NULL,
    [Exchange]                 NCHAR (10)     NULL,
    [MTF_ID]                   NVARCHAR (50)  NULL,
    [BeginningOnHandQty]       NVARCHAR (50)  NULL,
    [INNERDUCT]                BIT            NULL,
    [TAPE]                     BIT            NULL,
    [INNERDUCT_Usage]          NVARCHAR (50)  NULL,
    [TAPE_Usage]               NVARCHAR (50)  NULL,
    [INNERDUCT_Part]           NVARCHAR (50)  NULL,
    [TAPE_Part]                NVARCHAR (50)  NULL,
    [Gap_SEQ_Validation]       BIT            NULL,
    [SubmittedBy_Contractor]   NVARCHAR (50)  NULL,
    [SubmittedWhen_Contractor] NVARCHAR (50)  NULL
);

