CREATE TABLE [Brownfield].[LZ_JHFFTRDCBX] (
    [LINEJUSTIFICATCODE] NVARCHAR (4)  NULL,
    [PROJECTMASTERNUMBR] NVARCHAR (20) NULL,
    [LINESUB_PROJECT#]   NVARCHAR (20) NULL,
    [LINESTATEABBRV]     NVARCHAR (10) NULL,
    [COSTCODE]           NVARCHAR (20) NULL,
    [SUMLINBUD]          NVARCHAR (20) NULL
);

