CREATE TABLE [Brownfield].[MasterGoldenReport] (
    [ProjectNumber]              NVARCHAR (50)  NULL,
    [SubprojectNumber]           NVARCHAR (50)  NULL,
    [ProjectSubNumber]           NVARCHAR (50)  NULL,
    [ClassOfPlant]               NVARCHAR (50)  NULL,
    [LinkCode]                   NVARCHAR (50)  NULL,
    [JustificationCode]          NVARCHAR (50)  NULL,
    [FunctionalGroup]            NVARCHAR (50)  NULL,
    [CurrentProjectDescription]  NVARCHAR (MAX) NULL,
    [ProjectStatusCode]          NVARCHAR (50)  NULL,
    [ApprovalCode]               NVARCHAR (50)  NULL,
    [Company]                    NVARCHAR (50)  NULL,
    [ExchangeName]               NVARCHAR (50)  NULL,
    [OperatingArea]              NVARCHAR (50)  NULL,
    [State]                      NVARCHAR (50)  NULL,
    [Region]                     NVARCHAR (25)  NULL,
    [Engineer]                   NVARCHAR (50)  NULL,
    [ProjectOwner]               NVARCHAR (50)  NULL,
    [ApprovalDate]               NVARCHAR (50)  NULL,
    [EstimatedStartDate]         NVARCHAR (50)  NULL,
    [EstimatedCompleteDate]      NVARCHAR (50)  NULL,
    [ActualStartDate]            NVARCHAR (50)  NULL,
    [ReadyForServiceDate]        NVARCHAR (50)  NULL,
    [TentativeCloseDate]         NVARCHAR (50)  NULL,
    [CloseDate]                  NVARCHAR (50)  NULL,
    [BudgetLineNumber]           NVARCHAR (50)  NULL,
    [BudgetLineName]             NVARCHAR (200) NULL,
    [PercentMaterialsUsed]       FLOAT (53)     NULL,
    [EMC]                        NVARCHAR (50)  NULL,
    [Vendor]                     NVARCHAR (50)  NULL,
    [OriginalAuthorizedDirect]   MONEY          NULL,
    [OriginalAuthorizedIndirect] MONEY          NULL,
    [OriginalAuthorizedTotal]    MONEY          NULL,
    [CurrentAuthorizedDirect]    MONEY          NULL,
    [CurrentAuthorizedIndirect]  MONEY          NULL,
    [CurrentAuthorizedTotal]     MONEY          NULL,
    [PriorYearsSpendDirect]      MONEY          NULL,
    [PriorYearsSpendIndirect]    MONEY          NULL,
    [PriorYearsSpendTotal]       MONEY          NULL,
    [JanuaryDirect]              MONEY          NULL,
    [JanuaryIndirect]            MONEY          NULL,
    [FebruaryDirect]             MONEY          NULL,
    [FebruaryIndirect]           MONEY          NULL,
    [MarchDirect]                MONEY          NULL,
    [MarchIndirect]              MONEY          NULL,
    [AprilDirect]                MONEY          NULL,
    [AprilIndirect]              MONEY          NULL,
    [MayDirect]                  MONEY          NULL,
    [MayIndirect]                MONEY          NULL,
    [JuneDirect]                 MONEY          NULL,
    [JuneIndirect]               MONEY          NULL,
    [JulyDirect]                 MONEY          NULL,
    [JulyIndirect]               MONEY          NULL,
    [AugustDirect]               MONEY          NULL,
    [AugustIndirect]             MONEY          NULL,
    [SeptemberDirect]            MONEY          NULL,
    [SeptemberIndirect]          MONEY          NULL,
    [OctoberDirect]              MONEY          NULL,
    [OctoberIndirect]            MONEY          NULL,
    [NovemberDirect]             MONEY          NULL,
    [NovemberIndirect]           MONEY          NULL,
    [DecemberDirect]             MONEY          NULL,
    [DecemberIndirect]           MONEY          NULL,
    [CurrentYearDirect]          MONEY          NULL,
    [CurrentYearInDirect]        MONEY          NULL,
    [CurrentYearTotal]           MONEY          NULL,
    [TotalDirect]                MONEY          NULL,
    [TotalIndirect]              MONEY          NULL,
    [TotalGrossAdds]             MONEY          NULL,
    [FutureYearsSpendInfinium]   MONEY          NULL,
    [FutureYearsSpend]           MONEY          NULL,
    [CATSHours]                  NVARCHAR (50)  NULL
);

