CREATE PROCEDURE ADDRESS_BILLING.usp_SAAFACTFEATUREMONTHLYSNAP_SUM
AS
	SET XACT_ABORT, NOCOUNT ON;
BEGIN TRY

	DECLARE @EVENTID INT;

	INSERT INTO [LOG].tbl_StoreProc
	(
		[EVENTNAME],
		[EVENTSTART],
		[EVENTTYPE],
		[EVENTDESCRIPTION]
	)
	VALUES
	(
		'ADDRESS_BILLING.usp_SAAFACTFEATUREMONTHLYSNAP_SUM',
		CAST(GETDATE() AS DATETIME),
		'STORE PROC',
		'SINGLE_INGESTION'
	)

	SET @EVENTID = SCOPE_IDENTITY();

	BEGIN TRANSACTION

	DELETE FROM ADDRESS_BILLING.SAAFACTFEATUREMONTHLYSNAP_SUM  WHERE DATESTART>=DATEADD(month, DATEDIFF(MONTH, -1, GETDATE()) - 2, 0)

	INSERT INTO ADDRESS_BILLING.SAAFACTFEATUREMONTHLYSNAP_SUM
	SELECT * FROM LZ.TBL_SAAFACTFEATUREMONTHLYSNAP_SUM
	
	COMMIT TRANSACTION

	UPDATE L
    SET L.EVENTEND = CAST(GETDATE() AS DATETIME)
    FROM LOG.tbl_StoreProc L
    WHERE L.EVENTID = @EventID;

END TRY
BEGIN CATCH
	IF @@trancount > 0 ROLLBACK TRANSACTION
	EXEC usp_error_handler
	RETURN 55555
END CATCH