create PROCEDURE dbo.[usp_M6_CIRCUIT_INVENTORY_SITE_MAPPING]
AS
	SET XACT_ABORT, NOCOUNT ON;
BEGIN TRY

	DECLARE @EVENTID INT;

	INSERT INTO [LOG].tbl_StoreProc
    (
		[EVENTNAME],
		[EVENTSTART],
		[EVENTTYPE],
		[EVENTDESCRIPTION]
	)
	VALUES
	(
		'dbo.[usp_M6_CIRCUIT_INVENTORY_SITE_MAPPING]',
		CAST(GETDATE() AS DATETIME),
		'STORE PROC',
		'move site ID mapping data from LZ to DBO with datetime conversion'
	)

	SET @EVENTID = SCOPE_IDENTITY();

	BEGIN TRANSACTION

	TRUNCATE TABLE [dbo].[M6_CIRCUIT_INVENTORY_SITE_MAPPING]

	INSERT INTO [dbo].[M6_CIRCUIT_INVENTORY_SITE_MAPPING]
	SELECT
		EXCHANGE_CARRIER_CIRCUIT_ID
		,SITE_ID
		,STATUS
		,CLEAN_ID
		,SERVICE_TYPE_CODE
		,ACNA
		,CASE 
			WHEN ISDATE(IN_SERVICE_DATE) = 0 and IN_SERVICE_DATE is not null THEN '01-01-1900'
			ELSE CAST(IN_SERVICE_DATE AS DATETIME)
			END
		,CASE 
			WHEN ISDATE(DD_COMPLETION_DATE) = 0 and DD_COMPLETION_DATE is not null THEN '01-01-1900'
			ELSE CAST(DD_COMPLETION_DATE AS DATETIME)
			END
	FROM LZ.M6_CIRCUIT_INVENTORY_SITE_MAPPING

	COMMIT TRANSACTION

	UPDATE L
    SET L.EVENTEND = CAST(GETDATE() AS DATETIME)
    FROM LOG.tbl_StoreProc L
    WHERE L.EVENTID = @EventID;

END TRY
BEGIN CATCH
	IF @@trancount > 0 ROLLBACK TRANSACTION
	EXEC usp_error_handler
	RETURN 55555
END CATCH