CREATE PROCEDURE usp_ETH_ENABLED_SWC
AS
BEGIN

    -- Perform the bulk insert
    BULK INSERT DBO.ETH_ENABLED_SWC
    FROM '\\Wadinfwwapv02\lz\PLAYGROUND\ETH_ENABLED_SWC.csv'
    WITH (
        FIRSTROW = 2,
        FIELDTERMINATOR = ',',
        ROWTERMINATOR = '\n',
        TABLOCK,
        ERRORFILE = 'd:\LZ\PLAYGROUND\ETH_ENABLED_SWC_ERROR_ROWS.log',
        MAXERRORS = 10
    );
END
GO
