
CREATE PROCEDURE dbo.usp_TBL_LZ_DSAT_MATRIX_UPLOAD
/*
	-- Add any parameters for the stored procedure here
	@var1 int,
	@var2 int
*/
AS
	SET XACT_ABORT, NOCOUNT ON;
BEGIN TRY

	DECLARE @EVENTID INT;

	INSERT INTO [LOG].tbl_storeproc
    (
		[EVENTNAME],
		[EVENTSTART],
		[EVENTTYPE],
		[EVENTDESCRIPTION]
	)
	VALUES
	(
		'dbo.TBL_LZ_DSAT_MAXTRIX',
		CAST(GETDATE() AS DATETIME),
		'STORE PROC',
		'SINGLE_INGESTION'
	)

	SET @EVENTID = SCOPE_IDENTITY();

	BEGIN TRANSACTION

	insert INTO dbo.TBL_DSAT_MATRIX
	SELECT * 
	FROM LZ.TBL_DSAT_MATRIX
	
	COMMIT TRANSACTION

	UPDATE L
    SET L.EVENTEND = CAST(GETDATE() AS DATETIME)
    FROM LOG.tbl_StoreProc L
    WHERE L.EVENTID = @EventID;

END TRY
BEGIN CATCH
	IF @@trancount > 0 ROLLBACK TRANSACTION
	EXEC usp_error_handler
	RETURN 55555
END CATCH