
CREATE PROCEDURE dbo.[usp_TBL_NEUSTAR_ORDERS]
AS
	SET XACT_ABORT, NOCOUNT ON;
BEGIN TRY

    DECLARE @EVENTID INT;

	INSERT INTO [LOG].tbl_StoreProc
    (
        [EVENTNAME],
        [EVENTSTART],
        [EVENTTYPE],
        [EVENTDESCRIPTION]
    )
    VALUES
    (
        'dbo.TBL_NEUSTAR_ORDERS',
        CAST(GETDATE() AS DATETIME),
        'STORE PROC',
        'SINGLE_INGESTION'
    );

    SET @EVENTID = SCOPE_IDENTITY();

	BEGIN TRANSACTION

    INSERT INTO dbo.TBL_NEUSTAR_ORDERS
    SELECT * FROM LZ.TBL_NEUSTAR_ORDERS

	COMMIT TRANSACTION

    UPDATE L
    SET L.EVENTEND = CAST(GETDATE() AS DATETIME)
    FROM LOG.tbl_StoreProc L
    WHERE L.EVENTID = @EventID;

END TRY
BEGIN CATCH
	IF @@trancount > 0 ROLLBACK TRANSACTION
	EXEC usp_error_handler
	RETURN 55555
END CATCH
GO


