CREATE PROCEDURE dbo.usp_TBL_CONSOLIDATED_ETHERNET_REV
AS
    SET XACT_ABORT, NOCOUNT ON;
BEGIN TRY

    DECLARE @EVENTID INT;

    INSERT INTO [LOG].tbl_StoreProc
    (
        [EVENTNAME],
        [EVENTSTART],
        [EVENTTYPE],
        [EVENTDESCRIPTION]
    )
    VALUES
    (
        'dbo.usp_TBL_CONSOLIDATED_ETHERNET_REV',
        CAST(GETDATE() AS DATETIME),
        'STORE PROC',
        'INSERTING CONSOLIDATED ETHERNET REV DATA'
    );

    SET @EVENTID = SCOPE_IDENTITY();

    BEGIN TRANSACTION

    -- delete current and prior month before insert
    DELETE from dbo.TBL_CONSOLIDATED_ETHERNET_REV  WHERE BILL_MONTH >= DATEADD(MONTH, DATEDIFF(MONTH, 0, GETDATE()) - 1, 0)

    -- Insert data from LZ.TBL_CONSOLIDATED_ETHERNET_REV into dbo.CONSOLIDATED_ETHERNET_REV
    INSERT INTO dbo.TBL_CONSOLIDATED_ETHERNET_REV
    (
        [GL_CMPY_NO],
        [CUST_NM],
        [ACCT_BTN],
        [CUST_NO],
        [PRD_SVC_CD],
        [BILL_MONTH],
        [PRC_SVC_CD_DS],
        [DIRECT_SALES_REV_TYPE_CD],
        [TOTAL_BILL_AMT_NET],
        [GL_MATRIX_NO]
    )
    SELECT 
        [GL_CMPY_NO],
        [CUST_NM],
        [ACCT_BTN],
        [CUST_NO],
        [PRD_SVC_CD],
        [BILL_MONTH],
        [PRC_SVC_CD_DS],
        [DIRECT_SALES_REV_TYPE_CD],
        [TOTAL_BILL_AMT_NET],
        [GL_MATRIX_NO]
    FROM LZ.TBL_CONSOLIDATED_ETHERNET_REV;

    COMMIT TRANSACTION;

    UPDATE L
    SET L.EVENTEND = CAST(GETDATE() AS DATETIME)
    FROM LOG.tbl_StoreProc L
    WHERE L.EVENTID = @EventID;

END TRY
BEGIN CATCH
    IF @@trancount > 0 ROLLBACK TRANSACTION;
    EXEC usp_error_handler;
    RETURN 55555;
END CATCH;
GO
