CREATE TABLE [LZ_Py].[CB_FRONTIER_DEMAND_ENGINE_ACTIVITIES_819] (
    [ID]                 NVARCHAR (MAX) NULL,
    [LOGIN_ID]           NVARCHAR (MAX) NULL,
    [ROUTE_NAME]         NVARCHAR (MAX) NULL,
    [REQUESTING_COMPANY] NVARCHAR (MAX) NULL,
    [ADDRESS]            NVARCHAR (MAX) NULL,
    [CITY]               NVARCHAR (MAX) NULL,
    [STATE]              NVARCHAR (MAX) NULL,
    [ZIP]                NVARCHAR (MAX) NULL,
    [COUNTY]             NVARCHAR (MAX) NULL,
    [COUNTRY]            NVARCHAR (MAX) NULL,
    [USER_COMPANY]       NVARCHAR (MAX) NULL,
    [TARGET_COMPANY_ID]  NVARCHAR (MAX) NULL,
    [TARGET_COMPANY]     NVARCHAR (MAX) NULL,
    [REQUEST_DATE]       NVARCHAR (MAX) NULL,
    [RESULT]             NVARCHAR (MAX) NULL,
    [SERVICENAME]        NVARCHAR (MAX) NULL,
    [ERROR_MESSAGE]      NVARCHAR (MAX) NULL,
    [file_name]          NVARCHAR (MAX) NULL
);

