CREATE PROCEDURE EDW_VWMC.usp_TBL_C2F_EXCHANGE_SUBSCRIBERS
/*
	-- Add any parameters for the stored procedure here
	@var1 int,
	@var2 int
*/
AS
	SET XACT_ABORT, NOCOUNT ON;
BEGIN TRY
	BEGIN TRANSACTION
	DROP TABLE IF EXISTS #t
INSERT INTO [LOG].tbl_storeproc
    ([EVENTNAME]
    ,[EVENTSTART]
    ,[EVENTTYPE]
    ,[EVENTDESCRIPTION])

--enter values below

VALUES
('EDW_VWMC.TBL_C2F_EXCHANGE_SUBSCRIBERS'
    ,CAST(GETDATE() AS DATETIME)
    ,'STORE PROC'
    ,'SINGLE_INGESTION')



SELECT MAX(EVENTID) AS LATESTID  INTO #t
FROM [LOG].tbl_storeproc



insert INTO EDW_VWMC.TBL_C2F_EXCHANGE_SUBSCRIBERS
SELECT 
A.* 
,CAST(GETDATE() AS DATE) AS UPDATED_DT
FROM LZ.TBL_EDW_VWMC_C2F_EXCHANGE_SUBSCRIBERS A

	
	
UPDATE L
SET L.EVENTEND=CAST(GETDATE() AS DATETIME)
FROM LOG.tbl_storeproc L
INNER JOIN #t
ON L.EVENTID = #t.LATESTID
DROP TABLE IF EXISTS #t


	
	COMMIT TRANSACTION
END TRY
BEGIN CATCH
	IF @@trancount > 0 ROLLBACK TRANSACTION
	EXEC usp_error_handler
	RETURN 55555
END CATCH
GO
