CREATE TABLE WCF.[CONSOLIDATED_DATA_TABLE]
(
[wireCenterClli] [nvarchar](255) NULL,
	[STATE] [nvarchar](255) NULL,
	[Copper troubles] [float] NULL,
	[Fiber troubles] [float] NULL,
	[Copper new adds] [float] NULL,
	[Fiber new adds] [float] NULL,
	[Cost per fiber trouble] [float] NULL,
	[Cost per copper trouble ticket] [float] NULL,
	[Cost per copper new add] [float] NULL,
	[Cost per fiber new add] [float] NULL,
	[Copper Trouble OOP Labor] [float] NULL,
	[Fiber trouble OOP Labor] [float] NULL,
	[Fiber new add labor] [float] NULL,
	[Copper new add OOP labor] [float] NULL,
	[Copper Labor] [float] NULL,
	[Fiber Labor] [float] NULL,
	[TSO Calls] [float] NULL,
	[Cost per call] [float] NULL,
	[TSO Costs] [float] NULL,
	[Network Operations] [float] NULL,
	[Network Distribution] [float] NULL,
	[Assignment] [float] NULL,
	[Network Core] [float] NULL,
	[Circuits COGS] [float] NULL,
	[Network Ops Support] [float] NULL,
	[Voice COGS] [float] NULL,
	[SS7 Circuit] [float] NULL,
	[Cable Locates] [float] NULL,
	[Plant Maintenance] [float] NULL,
	[Poles] [float] NULL,
	[Jointly Owned Poles] [float] NULL,
	[Plant Maintenance and Constructions] [float] NULL,
	[Network Access] [float] NULL,
	[Total] [float] NULL,
	[ABU > 81% of Customers] [float] NULL,
	[ABU 61-80% of Customers] [float] NULL,
	[ABU 41-60% of Customers] [float] NULL,
	[ABU 21-40% of Customers] [float] NULL,
	[ABU 1-20% of Customers] [float] NULL,
	[ABU 0% of Customers] [float] NULL,
	[BEAD > 81% of Customers] [float] NULL,
	[BEAD 61-80% of Customers] [float] NULL,
	[BEAD 41-60% of Customers] [float] NULL,
	[BEAD 21-40% of Customers] [float] NULL,
	[BEAD 1-20% of Customers] [float] NULL,
	[BEAD 0% of Customers] [float] NULL,
	[Hyperion] [float] NULL,
	[Regulatory Guidance - Green] [float] NULL,
	[Regulatory Guidance - Yellow] [float] NULL,
	[Regulatory Guidance - Red] [float] NULL,
	[Tarriff Restrictions - Green] [float] NULL,
	[Tarriff Restrictions - Yellow] [float] NULL,
	[Tarriff Restrictions - Red] [float] NULL,
	[2023 New Copper Installs] [float] NULL,
	[Applied SAC per install] [float] NULL,
	[SAC] [float] NULL,
	[Extractable Copper Power Expense] [float] NULL,
	[Consumer - Total Fiber Customers] [float] NULL,
	[Consumer - Fiber Voice Only Customers] [float] NULL,
	[Consumer - Fiber Broadband Only Customers] [float] NULL,
	[Consumer - Fiber Video Only Customers] [float] NULL,
	[Consumer - Fiber Voice & Broadband Customers] [float] NULL,
	[Consumer - Fiber Broadband & Video Customers] [float] NULL,
	[Consumer - Fiber Voice & Video] [float] NULL,
	[Consumer - Fiber No Core Products Customers] [float] NULL,
	[Consumer - Total Copper Customers] [float] NULL,
	[Consumer - Copper Voice Only Customers] [float] NULL,
	[Consumer - Copper Broadband Only Customers] [float] NULL,
	[Consumer - Copper Video Only Customers] [float] NULL,
	[Consumer - Copper Voice & Broadband Customers] [float] NULL,
	[Consumer - Copper Broadband & Video Customers] [float] NULL,
	[Consumer - Copper Voice & Video] [float] NULL,
	[Consumer - Copper Broadband & Voice & Video] [float] NULL,
	[Consumer - Copper No Core Products Customers] [float] NULL,
	[SMB - Fiber Customers] [float] NULL,
	[SMB- Fiber Voice Only Customers] [float] NULL,
	[SMB - Fiber Broadband Only Customers] [float] NULL,
	[SMB - Fiber Video Only Customers] [float] NULL,
	[SMB - Fiber Voice & Broadband Customers] [float] NULL,
	[SMB - Fiber Broadband & Video Customers] [float] NULL,
	[SMB - Fiber Voice & Video] [float] NULL,
	[SMB - Fiber No Core Products Customers] [float] NULL,
	[SMB - Total Copper Customers] [float] NULL,
	[SMB - Copper Voice Only Customers] [float] NULL,
	[SMB - Copper Broadband Only Customers] [float] NULL,
	[SMB - Copper Video Only Customers] [float] NULL,
	[SMB - Copper Voice & Broadband Customers] [float] NULL,
	[SMB - Copper Broadband & Video Customers] [float] NULL,
	[SMB - Copper Voice & Video] [float] NULL,
	[SMB - Copper Broadband & Voice & Video] [float] NULL,
	[SMB - Copper No Core Products Customers] [float] NULL,
	[ENT - Total Fiber Customers] [float] NULL,
	[ENT - Fiber Voice Only Customers] [float] NULL,
	[ENT - Fiber Broadband Only Customers] [float] NULL,
	[ENT - Fiber Video Only Customers] [float] NULL,
	[ENT - Fiber Voice & Broadband Customers] [float] NULL,
	[ENT - Fiber Broadband & Video Customers] [float] NULL,
	[ENT - Fiber Voice & Video] [float] NULL,
	[ENT - Fiber No Core Products Customers] [float] NULL,
	[ENT - Total Copper Customers] [float] NULL,
	[ENT - Copper Voice Only Customers] [float] NULL,
	[ENT - Copper Broadband Only Customers] [float] NULL,
	[ENT - Copper Video Only Customers] [float] NULL,
	[ENT - Copper Voice & Broadband Customers] [float] NULL,
	[ENT - Copper Broadband & Video Customers] [float] NULL,
	[ENT - Copper Voice & Video] [float] NULL,
	[ENT - Copper Broadband & Voice & Video] [float] NULL,
	[ENT - Copper No Core Products Customers] [float] NULL,
	[ENT - Circuits] [float] NULL,
	[Paystation -  Total Customers (Voice)] [float] NULL,
	[Wholesale - Total Fiber Customers] [float] NULL,
	[Wholesale - Fiber Voice Only Customers] [float] NULL,
	[Wholesale - Fiber Broadband Only Customers] [float] NULL,
	[Wholesale - Fiber Video Only Customers] [float] NULL,
	[Wholesale - Fiber Voice & Broadband Customers] [float] NULL,
	[Wholesale - Fiber Broadband & Video Customers] [float] NULL,
	[Wholesale - Fiber Voice & Video] [float] NULL,
	[Wholesale - Fiber No Core Products Customers] [float] NULL,
	[Wholesale - Total Copper Customers] [float] NULL,
	[Wholesale - Copper Voice Only Customers] [float] NULL,
	[Wholesale - Copper Broadband Only Customers] [float] NULL,
	[Wholesale - Copper Video Only Customers] [float] NULL,
	[Wholesale - Copper Voice & Broadband Customers] [float] NULL,
	[Wholesale - Copper Broadband & Video Customers] [float] NULL,
	[Wholesale - Copper Voice & Video] [float] NULL,
	[Wholesale - Copper Broadband & Voice & Video] [float] NULL,
	[Wholesale - Copper No Core Products Customers] [float] NULL,
	[Wholesale - Circuits] [float] NULL,
	RPT_MTH DATE,
	RUN_TS DATETIME2,
	MODEL_RUN_ID INT

)
