CREATE TABLE WCF.[TBL_REV_BY_LOB_AND_PRODUCT]
(
[Wirecenter] [nvarchar](255) NULL,
	[Consumer - Total Fiber Customers] [float] NULL,
	[Consumer - Fiber Voice Only Customers] [float] NULL,
	[Consumer - Fiber Broadband Only Customers] [float] NULL,
	[Consumer - Fiber Video Only Customers] [float] NULL,
	[Consumer - Fiber Voice & Broadband Customers] [float] NULL,
	[Consumer - Fiber Broadband & Video Customers] [float] NULL,
	[Consumer - Fiber Voice & Video] [float] NULL,
	[Consumer - Fiber No Core Products Customers] [float] NULL,
	[Consumer - Total Copper Customers] [float] NULL,
	[Consumer - Copper Voice Only Customers] [float] NULL,
	[Consumer - Copper Broadband Only Customers] [float] NULL,
	[Consumer - Copper Video Only Customers] [float] NULL,
	[Consumer - Copper Voice & Broadband Customers] [float] NULL,
	[Consumer - Copper Broadband & Video Customers] [float] NULL,
	[Consumer - Copper Voice & Video] [float] NULL,
	[Consumer - Copper Broadband & Voice & Video] [float] NULL,
	[Consumer - Copper No Core Products Customers] [float] NULL,
	[SMB - Fiber Customers] [float] NULL,
	[SMB- Fiber Voice Only Customers] [float] NULL,
	[SMB - Fiber Broadband Only Customers] [float] NULL,
	[SMB - Fiber Video Only Customers] [float] NULL,
	[SMB - Fiber Voice & Broadband Customers] [float] NULL,
	[SMB - Fiber Broadband & Video Customers] [float] NULL,
	[SMB - Fiber Voice & Video] [float] NULL,
	[SMB - Fiber No Core Products Customers] [float] NULL,
	[SMB - Total Copper Customers] [float] NULL,
	[SMB - Copper Voice Only Customers] [float] NULL,
	[SMB - Copper Broadband Only Customers] [float] NULL,
	[SMB - Copper Video Only Customers] [float] NULL,
	[SMB - Copper Voice & Broadband Customers] [float] NULL,
	[SMB - Copper Broadband & Video Customers] [float] NULL,
	[SMB - Copper Voice & Video] [float] NULL,
	[SMB - Copper Broadband & Voice & Video] [float] NULL,
	[SMB - Copper No Core Products Customers] [float] NULL,
	[ENT - Total Fiber Customers] [float] NULL,
	[ENT - Fiber Voice Only Customers] [float] NULL,
	[ENT - Fiber Broadband Only Customers] [float] NULL,
	[ENT - Fiber Video Only Customers] [float] NULL,
	[ENT - Fiber Voice & Broadband Customers] [float] NULL,
	[ENT - Fiber Broadband & Video Customers] [float] NULL,
	[ENT - Fiber Voice & Video] [float] NULL,
	[ENT - Fiber No Core Products Customers] [float] NULL,
	[ENT - Total Copper Customers] [float] NULL,
	[ENT - Copper Voice Only Customers] [float] NULL,
	[ENT - Copper Broadband Only Customers] [float] NULL,
	[ENT - Copper Video Only Customers] [float] NULL,
	[ENT - Copper Voice & Broadband Customers] [float] NULL,
	[ENT - Copper Broadband & Video Customers] [float] NULL,
	[ENT - Copper Voice & Video] [float] NULL,
	[ENT - Copper Broadband & Voice & Video] [float] NULL,
	[ENT - Copper No Core Products Customers] [float] NULL,
	[ENT - Circuits] [float] NULL,
	[Paystation -  Total Customers (Voice)] [float] NULL,
	[Wholesale - Total Fiber Customers] [float] NULL,
	[Wholesale - Fiber Voice Only Customers] [float] NULL,
	[Wholesale - Fiber Broadband Only Customers] [float] NULL,
	[Wholesale - Fiber Video Only Customers] [float] NULL,
	[Wholesale - Fiber Voice & Broadband Customers] [float] NULL,
	[Wholesale - Fiber Broadband & Video Customers] [float] NULL,
	[Wholesale - Fiber Voice & Video] [float] NULL,
	[Wholesale - Fiber No Core Products Customers] [float] NULL,
	[Wholesale - Total Copper Customers] [float] NULL,
	[Wholesale - Copper Voice Only Customers] [float] NULL,
	[Wholesale - Copper Broadband Only Customers] [float] NULL,
	[Wholesale - Copper Video Only Customers] [float] NULL,
	[Wholesale - Copper Voice & Broadband Customers] [float] NULL,
	[Wholesale - Copper Broadband & Video Customers] [float] NULL,
	[Wholesale - Copper Voice & Video] [float] NULL,
	[Wholesale - Copper Broadband & Voice & Video] [float] NULL,
	[Wholesale - Copper No Core Products Customers] [float] NULL,
	[Wholesale - Circuits] [float] NULL,
	RPT_MTH DATE
)
