CREATE TABLE [LZ].[sitetracker_project_c] (
    [Approval_Status__c]                             NVARCHAR (100)  NULL,
    [Associated_Project__c]                          NVARCHAR (100)  NULL,
    [Associated_Projects__c]                         NVARCHAR (100)  NULL,
    [Authorized_Budget__c]                           DECIMAL (10, 2) NULL,
    [Billing_Code__c]                                NVARCHAR (100)  NULL,
    [Budget__c]                                      NVARCHAR (100)  NULL,
    [Budget_Year__c]                                 NVARCHAR (100)  NULL,
    [Budget_Nonbudget__c]                            NVARCHAR (100)  NULL,
    [Capital_Budget_Manager__c]                      NVARCHAR (100)  NULL,
    [Class_Of_Plant__c]                              NVARCHAR (100)  NULL,
    [Closing_Comments__c]                            NVARCHAR (2000) NULL,
    [Closing_Comments_History__c]                    NVARCHAR (MAX)  NULL,
    [Company__c]                                     NVARCHAR (100)  NULL,
    [sitetracker__Customer__c]                       NVARCHAR (100)  NULL,
    [Customer_Locations__c]                          DECIMAL (10, 2) NULL,
    [Customer_Locations_Alt_Program__c]              DECIMAL (10, 2) NULL,
    [Customer_Locations_Partial__c]                  DECIMAL (10, 2) NULL,
    [Customer_Locations_Partial_2nd_Half__c]         DECIMAL (10, 2) NULL,
    [Completion_Date__c]                             DATETIME        NULL,
    [Project_Start_Date__c]                          DATETIME        NULL,
    [Estimate_Complete__c]                           DATETIME        NULL,
    [Estimate_Start__c]                              DATETIME        NULL,
    [Exchange_Name__c]                               NVARCHAR (100)  NULL,
    [Expense_Only__c]                                INT             NULL,
    [Feeder_or_Distribution__c]                      NVARCHAR (100)  NULL,
    [Finance__c]                                     NVARCHAR (100)  NULL,
    [FTTH__c]                                        NVARCHAR (100)  NULL,
    [In_Service_Date_A__c]                           DATETIME        NULL,
    [In_Service_Date_F__c]                           DATETIME        NULL,
    [Infinium_Location__c]                           NVARCHAR (100)  NULL,
    [Infinium_Project_Number__c]                     NVARCHAR (100)  NULL,
    [Infinium_Status__c]                             NVARCHAR (100)  NULL,
    [Justification_Code__c]                          NVARCHAR (100)  NULL,
    [LastModifiedById]                               NVARCHAR (100)  NULL,
    [Operating_Area__c]                              NVARCHAR (100)  NULL,
    [Approved_On__c]                                 DATETIME        NULL,
    [Original_In_Service_Date__c]                    DATETIME        NULL,
    [Primary_Subproject__c]                          NVARCHAR (100)  NULL,
    [sitetracker__Project__c]                        NVARCHAR (100)  NULL,
    [Project_Approved_A__c]                          DATETIME        NULL,
    [Project_Approved_F__c]                          DATETIME        NULL,
    [Project_Closed_A__c]                            DATETIME        NULL,
    [Project_Closed_F__c]                            DATETIME        NULL,
    [sitetracker__Project_Comments__c]               NVARCHAR (100)  NULL,
    [sitetracker__Project_Comments_History__c]       NVARCHAR (MAX)  NULL,
    [sitetracker__Project_Complete_A__c]             DATETIME        NULL,
    [Project_Complete_A__c]                          DATETIME        NULL,
    [sitetracker__Project_Complete_F__c]             DATETIME        NULL,
    [Project_Complete_F__c]                          DATETIME        NULL,
    [Project_Description_Reason__c]                  NVARCHAR (1000) NULL,
    [Name]                                           NVARCHAR (100)  NULL,
    [sitetracker__Project_Issue__c]                  INT             NULL,
    [sitetracker__Project_Issue_Reason__c]           NVARCHAR (100)  NULL,
    [sitetracker__Project_Status__c]                 NVARCHAR (100)  NULL,
    [sitetracker__Project_Status_Override__c]        INT             NULL,
    [sitetracker__Project_Status_Override_Reason__c] NVARCHAR (100)  NULL,
    [Infinium_Project_Title__c]                      NVARCHAR (100)  NULL,
    [sitetracker__Site__c]                           NVARCHAR (100)  NULL,
    [State__c]                                       NVARCHAR (100)  NULL,
    [Total_Budget_Amount__c]                         DECIMAL (10, 2) NULL,
    [Total_Change_Amount__c]                         DECIMAL (18, 2) NULL
);

