CREATE TABLE [m2m].[GA] (
    [GACO#]   INT           NULL,
    [GAACT]   VARCHAR (255) NULL,
    [GAPRJ#]  INT           NULL,
    [GAPRJS]  INT           NULL,
    [GAPRJL]  INT           NULL,
    [GAMTSK]  INT           NULL,
    [GASTSK]  INT           NULL,
    [GAMTRX]  INT           NULL,
    [GASORC]  VARCHAR (255) NULL,
    [GAPO#]   VARCHAR (255) NULL,
    [GAPOLN]  INT           NULL,
    [GARCPT]  VARCHAR (255) NULL,
    [GARCP$]  FLOAT (53)    NULL,
    [GALIN$]  FLOAT (53)    NULL,
    [GARPT$]  FLOAT (53)    NULL,
    [GATDTE]  INT           NULL,
    [GAACTY]  INT           NULL,
    [GAACTP]  INT           NULL,
    [GAL2CD]  INT           NULL,
    [GAEDTE]  INT           NULL,
    [GAJTCD]  INT           NULL,
    [GAOBUD]  FLOAT (53)    NULL,
    [GAR1BD]  FLOAT (53)    NULL,
    [GAR2BD]  FLOAT (53)    NULL,
    [GALDSC]  VARCHAR (255) NULL,
    [GA1COD]  INT           NULL,
    [GAOPRA]  INT           NULL,
    [GAINV#]  VARCHAR (255) NULL,
    [GAIDTE]  INT           NULL,
    [GAVEND]  INT           NULL,
    [GAVNNM]  VARCHAR (255) NULL,
    [GACHS2]  INT           NULL,
    [GAVOUC]  FLOAT (53)    NULL,
    [GAREF]   VARCHAR (255) NULL,
    [GADESC]  VARCHAR (255) NULL,
    [GAEXCH]  VARCHAR (255) NULL,
    [GAPRJT]  VARCHAR (255) NULL,
    [GAFUNC]  VARCHAR (255) NULL,
    [STATE]   VARCHAR (255) NULL,
    [HRS]     INT           NULL,
    [QTY]     INT           NULL,
    [UNITCST] FLOAT (53)    NULL
);

