
SELECT DOCUMENT_NUMBER, PON, ACT_IND, REQ_TYPE, SEI,DREC, DD, DDD,  
         CASE WHEN DD_TASK_COMP IS NULL AND ACCEPT_DT > DREC THEN ACCEPT_DT
	        WHEN ACCEPT_DT IS NULL THEN DD_TASK_COMP
	        WHEN ACCEPT_DT <= DD_TASK_COMP AND ACCEPT_DT > DREC THEN ACCEPT_DT 
	        ELSE DD_TASK_COMP END COMP_DT, 
         DD_TASK_COMP, NPA||NXX NPANXX, ICSC, ACNA, 
         ACCT.PRIMARY_CARRIER_NAME CUSTOMER,  					
         CASE WHEN STATE1 IS NOT NULL THEN STATE1
              WHEN SUBSTR(ICSC,1,4) = 'FV03' AND SUBSTR(CKT,1,2) = '83' THEN 'ID'
              WHEN SUBSTR(ICSC,1,4) = 'FV03' AND SUBSTR(CKT,1,2) = '85' THEN 'OR'
              WHEN SUBSTR(ICSC,1,4) = 'FV03' AND SUBSTR(CKT,1,2) = '86' THEN 'WA'
              ELSE NULL END STATE, 
         CASE WHEN (SUBSTR(RATE_CODE,1,2) = 'OC' OR SUBSTR(NC,1,1) = 'O') THEN 'OCN'
              WHEN (NC = 'HC' OR SUBSTR(CKT,4,2) = 'HC') THEN 'DS1'
              WHEN (NC = 'HF' OR SUBSTR(CKT,4,2) = 'HF') THEN 'DS3'
              WHEN SUBSTR(CKT,7,2) = 'T1' THEN 'DS1'
              WHEN SUBSTR(CKT,7,2) = 'T3' THEN 'DS3'
              WHEN SUBSTR(NC,1,1) IN ('L','X') THEN 'DS0'
              WHEN SUBSTR(CKT,4,1) IN ('L','X') THEN 'DS0'
              WHEN SUBSTR(CKT,4,2) IN ('OS','FX','UC','UG','CL') THEN 'DS0'
              WHEN SUBSTR(CKT,4,2) IN ('YG','QG','DH','YB') THEN 'DS0'
              WHEN (SUBSTR(NC,1,1) = 'K' OR SUBSTR(CKT,4,1) = 'K') THEN 'ETHERNET-UNI'
              WHEN NC = 'SN' THEN 'ETHERNET_NNI'
              WHEN SUBSTR(CKT,4,1) = 'V' THEN 'ETHERNET-EVC'
			  WHEN SUBSTR(PROJ,1,10) = 'ATTMOB-TLS' THEN 'ETHERNET-UNI'
			  WHEN SUBSTR(PROJ,1,10) = 'ATTMOB-EVC' THEN 'ETHERNET-EVC'
              ELSE RATE_CODE END PRODUCT,
         CKT
FROM
(
SELECT SR.PON,
  SR.DOCUMENT_NUMBER,
  ASR.REQUEST_TYPE REQ_TYPE,
  GA.INSTANCE_VALUE_ABBREV STATE1,     
  MAX(SR.ACTIVITY_IND) keep (dense_rank last order by sr.last_modified_date) ACT_IND,
  MAX(ASR.SWITCHED_ETHERNET_INDICATOR) keep (dense_rank last order by asr.last_modified_date) SEI,
  MAX(SR.SUPPLEMENT_TYPE) keep (dense_rank last order by sr.last_modified_date) SUPP_TYPE,
  MAX(ASR2.DATE_TIME_SENT) KEEP (DENSE_RANK LAST ORDER BY ASR2.LAST_MODIFIED_DATE) DREC, 
  MAX(ASR.DESIRED_DUE_DATE) KEEP (DENSE_RANK LAST ORDER BY ASR.LAST_MODIFIED_DATE) DD, 
  MAX(AUD.CRDD) KEEP (DENSE_RANK LAST ORDER BY AUD.LAST_MODIFIED_DATE) DDD, 
  MIN(ACCEPTANCE_DATE) KEEP (DENSE_RANK LAST ORDER BY AUD.LAST_MODIFIED_DATE) ACCEPT_DT, 
  MAX(TRUNC(ASAP.PKG_GMT.SF_GMT_AS_PASSED_TIMEZONE(T.ACTUAL_COMPLETION_DATE,1222))) keep (dense_rank last order by T.last_modified_date) DD_TASK_COMP,
  MAX(ASR.ACCESS_PROVIDER_SERV_CTR_CODE) keep (dense_rank last order by asr.last_modified_date) ICSC,
  MAX(SR.PROJECT_IDENTIFICATION) keep (dense_rank last order by sr.last_modified_date) PROJ,
  MAX(SR.ACNA) keep (dense_rank last order by sr.last_modified_date) ACNA,
  MAX(CIR.RATE_CODE) keep (dense_rank last order by cir.last_modified_date) RATE_CODE,
  MAX(ASR.NETWORK_CHANNEL_SERVICE_CODE) keep (dense_rank last order by asr.last_modified_date) NC,
  MAX(JEOPARDY_REASON_CODE) KEEP (DENSE_RANK LAST ORDER BY JEOP.LAST_MODIFIED_DATE) JEOP,
  CIR.EXCHANGE_CARRIER_CIRCUIT_ID CKT,
  MAX(ASR.NPA) KEEP (DENSE_RANK LAST ORDER BY ASR.LAST_MODIFIED_DATE) NPA,
  MAX(ASR.NXX) KEEP (DENSE_RANK LAST ORDER BY ASR.LAST_MODIFIED_DATE) NXX
--
FROM SERV_REQ SR, 
     ACCESS_SERVICE_REQUEST ASR,
	 ACCESS_SERVICE_REQUEST ASR2,
	 ASR_USER_DATA AUD,
     CIRCUIT CIR, 
     TASK T,
	 TASK_JEOPARDY_WHYMISS JEOP,
     ASAP.SERVICE_REQUEST_CIRCUIT SRC,
     (SELECT DISTINCT *
        FROM (SELECT d.location_id,
                     d.address_id,
                     d.active_ind,
                     ROW_NUMBER() OVER (PARTITION BY location_id ORDER BY address_id DESC) r
                   FROM asap.net_loc_addr d
                    WHERE active_ind = 'Y')
                     WHERE r = 1) NLA,                            
     ADDRESS A,
     GA_INSTANCE GA
--
WHERE SR.DOCUMENT_NUMBER = ASR.DOCUMENT_NUMBER(+)
AND SR.DOCUMENT_NUMBER = ASR2.DOCUMENT_NUMBER(+)
AND SR.DOCUMENT_NUMBER = SRC.DOCUMENT_NUMBER (+)
AND SR.DOCUMENT_NUMBER = AUD.DOCUMENT_NUMBER (+)
AND SRC.CIRCUIT_DESIGN_ID = CIR.CIRCUIT_DESIGN_ID (+)
AND SR.DOCUMENT_NUMBER = T.DOCUMENT_NUMBER (+)
AND T.TASK_NUMBER = JEOP.TASK_NUMBER(+)
AND CIR.LOCATION_ID = NLA.LOCATION_ID
AND NLA.ADDRESS_ID = A.ADDRESS_ID
AND A.GA_INSTANCE_ID_STATE_CD = GA.GA_INSTANCE_ID
AND SR.TYPE_OF_SR = 'ASR'
AND T.TASK_TYPE = 'DD'
AND ASR.REQUEST_TYPE IN ('S','E')
AND ASR.ACTIVITY_INDICATOR IN ('N','C')
AND JEOP.JEOPARDY_TYPE_CD(+) = 'W' 
AND SR.DOCUMENT_NUMBER > '1000000' 
AND TO_CHAR(T.ACTUAL_COMPLETION_DATE,'YYYYMM') IN ('202009') --CHANGE DATE TO SHOW PREVIOUS REPORTING MONTH   
--
GROUP BY SR.DOCUMENT_NUMBER,
  SR.PON,
  SR.TYPE_OF_SR, 
  ASR.REQUEST_TYPE, 
  CIR.EXCHANGE_CARRIER_CIRCUIT_ID,
   GA.INSTANCE_VALUE_ABBREV
) A, ASR_OM.ASR_ACCOUNT_MANAGER ACCT 
--
WHERE A.ACNA = ACCT.SECONDARY_ID (+) 
 AND (SUPP_TYPE <> '1' OR SUPP_TYPE IS NULL)
 AND SUBSTR(CKT,7,1) <> 'U'
 AND (acna not in ('FLR','ZTK','BLI','BNK','CMW','COY','CQV','CUS','CZE','CZJ','CZN','CZX','EPX','ERR','EXC','FBA','FCA','FIS',
                   'FLX','GOP','GTO','GVN','IZH','NNR','OGD','RGD','ROU','T05','VAC','VZN','WDK','ZAP','ZWV','ZZZ','XYY') or acna is null);



