CREATE PROCEDURE [QBR].[usp_TBL_NCFR]

AS
	SET XACT_ABORT, NOCOUNT ON;
BEGIN TRY
	BEGIN TRANSACTION
	DROP TABLE IF EXISTS #t
INSERT INTO [LOG].tbl_StoreProc
    ([EVENTNAME]
    ,[EVENTSTART]
    ,[EVENTTYPE]
    ,[EVENTDESCRIPTION])

--enter values below

VALUES
('QBR.usp_TBL_NCFR'
    ,CAST(GETDATE() AS DATETIME)
    ,'STORE PROC'
    ,'SINGLE_INGESTION')



SELECT MAX(EVENTID) AS LATESTID  INTO #t
FROM [LOG].tbl_StoreProc


TRUNCATE TABLE QBR.TBL_NCFR



  INSERT INTO QBR.TBL_NCFR
  SELECT A.*, CAST(GETDATE() AS DATE) AS UPDATE_DT FROM LZ.QBR_TBL_NCFR A


	
	
UPDATE L
SET L.EVENTEND=CAST(GETDATE() AS DATETIME)
FROM LOG.tbl_StoreProc L
INNER JOIN #t
ON L.EVENTID = #t.LATESTID
DROP TABLE IF EXISTS #t


	
	COMMIT TRANSACTION
END TRY
BEGIN CATCH
	IF @@trancount > 0 ROLLBACK TRANSACTION
	EXEC usp_error_handler
	RETURN 55555
END CATCH