CREATE PROCEDURE QBR.usp_VFO_PONS_V

AS
	SET XACT_ABORT, NOCOUNT ON;
BEGIN TRY

	DECLARE @EVENTID INT;

	INSERT INTO [LOG].tbl_StoreProc
    (
		[EVENTNAME],
		[EVENTSTART],
		[EVENTTYPE],
		[EVENTDESCRIPTION]
	)
	VALUES
	(
		'QBR.usp_VFO_PONS_V',
		CAST(GETDATE() AS DATETIME),
		'STORE PROC',
		'SINGLE_INGESTION'
	)

	SET @EVENTID = SCOPE_IDENTITY();

	BEGIN TRANSACTION

	--UPDATE TBL_WHSL_ADV_HIST_VFO_ORDERHISTORYINFO_THIST
	DELETE FROM [QBR].[TBL_WHSL_ADV_HIST_VFO_ORDERHISTORYINFO_THIST] WHERE YEAR(CREATIONDATETIME)>=2024

	INSERT INTO QBR.[TBL_WHSL_ADV_HIST_VFO_ORDERHISTORYINFO_THIST]
	SELECT A.*, CAST(GETDATE() AS DATE) AS UPDATE_DT FROM LZ.[TBL_WHSL_ADV_HIST_VFO_ORDERHISTORYINFO_THIST] a

	--UPDATE TBL_VFO_PONS
	DELETE FROM [QBR].TBL_VFO_PONS WHERE YEAR(DD_COMP)>=2024

	INSERT INTO QBR.TBL_VFO_PONS
	SELECT A.*, CAST(GETDATE() AS DATE) AS UPDATE_DT FROM LZ.TBL_VFO_PONS A
		
	COMMIT TRANSACTION

	UPDATE L
    SET L.EVENTEND = CAST(GETDATE() AS DATETIME)
    FROM LOG.tbl_StoreProc L
    WHERE L.EVENTID = @EventID;

END TRY
BEGIN CATCH
	IF @@trancount > 0 ROLLBACK TRANSACTION
	EXEC usp_error_handler
	RETURN 55555
END CATCH