CREATE PROCEDURE QBR.[usp_TBL_FOC_ON_TIME]

AS
	SET XACT_ABORT, NOCOUNT ON;
BEGIN TRY

	DECLARE @EVENTID INT;

	INSERT INTO [LOG].tbl_StoreProc
    (
		[EVENTNAME],
		[EVENTSTART],
		[EVENTTYPE],
		[EVENTDESCRIPTION]
	)
	VALUES
	(
		'QBR.usp_TBL_FOC_ON_TIME',
		CAST(GETDATE() AS DATETIME),
		'STORE PROC',
		'SINGLE_INGESTION'
	)

	SET @EVENTID = SCOPE_IDENTITY();

	BEGIN TRANSACTION

	TRUNCATE TABLE QBR.TBL_FOC_ON_TIME

	INSERT INTO QBR.TBL_FOC_ON_TIME
	SELECT A.*, CAST(GETDATE() AS DATE) AS UPDATE_DT FROM LZ.QBR_TBL_FOC_ON_TIME A
	
	COMMIT TRANSACTION

	UPDATE L
    SET L.EVENTEND = CAST(GETDATE() AS DATETIME)
    FROM LOG.tbl_StoreProc L
    WHERE L.EVENTID = @EventID;

END TRY
BEGIN CATCH
	IF @@trancount > 0 ROLLBACK TRANSACTION
	EXEC usp_error_handler
	RETURN 55555
END CATCH