CREATE PROCEDURE QBR.[usp_TBL_TRBL_FOUND_REMEDY]

AS
	SET XACT_ABORT, NOCOUNT ON;
BEGIN TRY

	DECLARE @EVENTID INT;

	INSERT INTO [LOG].tbl_StoreProc
    (
		[EVENTNAME],
		[EVENTSTART],
		[EVENTTYPE],
		[EVENTDESCRIPTION]
	)
	VALUES
	(
		'EDW_VWMC.[usp_TBL_TRBL_FOUND_REMEDY]',
		CAST(GETDATE() AS DATETIME),
		'STORE PROC',
		'SINGLE_INGESTION'
	)

	SET @EVENTID = SCOPE_IDENTITY();

	BEGIN TRANSACTION

	TRUNCATE TABLE QBR.TBL_TRBL_FOUND_REMEDY;

	INSERT INTO QBR.TBL_TRBL_FOUND_REMEDY SELECT * FROM LZ.TBL_TRBL_FOUND_REMEDY
	
	COMMIT TRANSACTION

	UPDATE L
    SET L.EVENTEND = CAST(GETDATE() AS DATETIME)
    FROM LOG.tbl_StoreProc L
    WHERE L.EVENTID = @EventID;

END TRY
BEGIN CATCH
	IF @@trancount > 0 ROLLBACK TRANSACTION
	EXEC usp_error_handler
	RETURN 55555
END CATCH