SELECT DISTINCT
nvl(GEOG.REGION_DS, --FIND REGION FROM EDW OGM FOR OFFICIAL ALIGNMENT AND IF NOT FOUND USE STATE LOOKUP BELOW
   case when subq.state in ('CT','NY','PA','MD','AL','FL','GA','MS','NC','SC','TN') then 'Eastern'
        when subq.state in ('IA','IL','IN','MI','MN','NE','WI','KY','TX','WV','VA','OH') then 'Central'
        when subq.state in ('CA','AZ','NM','NV','UT','ID','MT') then 'Western'
        else null end) as region_ds, 
PON, DOCNO, ACNA, ACT_IND, CKT, SUPP, D_REC, 
tsk.actual_completion_date  as ASR_CONF_DT, 
DD, DDD, COMP_DT, ADDRESS, CITY, STATE, ICSC, PRODUCT, PROJ, RATE_CODE, EUNAME, NC, NCI, SECNCI,    
  SPEC, RUID1, RUID2, LOS, BDW, PNUM, EXPEDITE, ACTL, PMO_USER_ID, PM_NAME, M6_NOTES, DATE_ENTERED, NPANXX,
listagg(subq.ready_task, ' / ') WITHIN GROUP (ORDER BY subq.ready_task) as ready_task,
listagg(subq.ready_workq, ' / ') WITHIN GROUP (ORDER BY subq.ready_task) as ready_workq,
listagg(subq.WkDays_in_Task, ' / ') WITHIN GROUP (ORDER BY subq.ready_task) as WkDays_in_Task,
party.party_name as M6_CUSTOMER_NAME,
MCL.PRIMARY_CARRIER_NAME MCL_PRIMARY_CARRIER_NAME,
MCL.SALES_MANAGER SALES_MANAGER,
MCL.ACCT_EXECUTIVE ACCT_EXECUTIVE,
CASE WHEN SUPP = '1' THEN 'CANCELLED' 
     WHEN COMP_DT IS NOT NULL THEN 'COMPLETED'
     ELSE 'PENDING' END STATUS,
EVCI     
FROM
(--SUBQUERY
SELECT DISTINCT
       SR.PON,
       SR.DOCUMENT_NUMBER AS DOCNO,
       SR.ACNA,
       SR.ACTIVITY_IND AS ACT_IND,
       SR.FIRST_ECCKT_ID AS CKT,
       SR.SUPPLEMENT_TYPE AS SUPP,
       ASR.DATE_TIME_SENT AS D_REC,
       ASR.DESIRED_DUE_DATE AS DD,
       AUD.CRDD AS DDD,
       TRUNC(T.ACTUAL_COMPLETION_DATE) COMP_DT,
       TRIM (SALI.SANO||' '||SALI.SASN||' '||SALI.SATH) AS ADDRESS,  --||SALI.SASD||' '
       SALI.CITY,
       CASE
          WHEN SALI.STATE IS NOT NULL THEN SUBSTR (SALI.STATE, 1, 2)
          WHEN ASR.ACCESS_PROVIDER_SERV_CTR_CODE = 'FV01' THEN 'WV'
          WHEN ASR.ACCESS_PROVIDER_SERV_CTR_CODE = 'SN01' AND SUBSTR (SR.FIRST_ECCKT_ID, 1, 2) = 'FA' THEN 'CT'
          WHEN SUBSTR (ASR.ACCESS_PROVIDER_SERV_CTR_CODE, 1, 2) = 'FV' AND SUBSTR (SR.FIRST_ECCKT_ID, 1, 2) = '30' THEN 'IL'
          WHEN SUBSTR (ASR.ACCESS_PROVIDER_SERV_CTR_CODE, 1, 2) = 'FV' AND SUBSTR (SR.FIRST_ECCKT_ID, 1, 2) = '31' THEN 'IN'
          WHEN SUBSTR (ASR.ACCESS_PROVIDER_SERV_CTR_CODE, 1, 2) = 'FV' AND SUBSTR (SR.FIRST_ECCKT_ID, 1, 2) = '33' THEN 'MI'
          WHEN SUBSTR (ASR.ACCESS_PROVIDER_SERV_CTR_CODE, 1, 2) = 'FV' AND SUBSTR (SR.FIRST_ECCKT_ID, 1, 2) = '36' THEN 'OH'
          WHEN SUBSTR (ASR.ACCESS_PROVIDER_SERV_CTR_CODE, 1, 2) = 'FV' AND SUBSTR (SR.FIRST_ECCKT_ID, 1, 2) = '39' THEN 'WI'
          WHEN SUBSTR (ASR.ACCESS_PROVIDER_SERV_CTR_CODE, 1, 2) = 'FV' AND SUBSTR (SR.FIRST_ECCKT_ID, 1, 2) = '43' THEN 'OR'
          WHEN SUBSTR (ASR.ACCESS_PROVIDER_SERV_CTR_CODE, 1, 2) = 'FV' AND SUBSTR (SR.FIRST_ECCKT_ID, 1, 2) in ('61','63') THEN 'NC'
          WHEN SUBSTR (ASR.ACCESS_PROVIDER_SERV_CTR_CODE, 1, 2) = 'FV' AND SUBSTR (SR.FIRST_ECCKT_ID, 1, 2) = '62' THEN 'SC'
          WHEN SUBSTR (ASR.ACCESS_PROVIDER_SERV_CTR_CODE, 1, 2) = 'FV' AND SUBSTR (SR.FIRST_ECCKT_ID, 1, 2) = '83' THEN 'ID'
          WHEN SUBSTR (ASR.ACCESS_PROVIDER_SERV_CTR_CODE, 1, 2) = 'FV' AND SUBSTR (SR.FIRST_ECCKT_ID, 1, 2) = '85' THEN 'OR'
          WHEN SUBSTR (ASR.ACCESS_PROVIDER_SERV_CTR_CODE, 1, 2) = 'FV' AND SUBSTR (SR.FIRST_ECCKT_ID, 1, 2) = '86' THEN 'WA'
          WHEN SUBSTR (ASR.ACCESS_PROVIDER_SERV_CTR_CODE, 1, 2) <> 'FV' AND SUBSTR (SR.FIRST_ECCKT_ID, 1, 2) = '61' THEN 'PA'
          WHEN SUBSTR (ASR.ACCESS_PROVIDER_SERV_CTR_CODE, 1, 2) = 'GT' AND SUBSTR (SR.FIRST_ECCKT_ID, 1, 2) in ('45','80','81') THEN 'CA'
          WHEN SUBSTR (ASR.ACCESS_PROVIDER_SERV_CTR_CODE, 1, 2) = 'GT' AND SUBSTR (SR.FIRST_ECCKT_ID, 1, 2) in ('12','13') THEN 'TX'
          WHEN SUBSTR (ASR.ACCESS_PROVIDER_SERV_CTR_CODE, 1, 2) = 'GT' AND SUBSTR (SR.FIRST_ECCKT_ID, 1, 2) in ('65','69') THEN 'FL'
          WHEN SUBSTR (SR.FIRST_ECCKT_ID, 1, 2) = '23' THEN 'MN'
          WHEN SUBSTR (SR.FIRST_ECCKT_ID, 1, 2) = '50' THEN 'WV'
          WHEN SUBSTR (SR.FIRST_ECCKT_ID, 1, 2) = '11' THEN 'AZ'
          WHEN SUBSTR (SR.FIRST_ECCKT_ID, 1, 2) = '97' THEN 'NY'
          WHEN ASR.ACCESS_PROVIDER_SERV_CTR_CODE = 'RT01' THEN 'NY'
          ELSE NULL END AS STATE,
       ASR.ACCESS_PROVIDER_SERV_CTR_CODE AS ICSC,
       CASE 
          WHEN SUBSTR (ASR.NETWORK_CHANNEL_SERVICE_CODE, 1, 2) IN ('SN') THEN 'Ethernet-NNI'
          WHEN SUBSTR (ASR.SERVICE_AND_PRODUCT_ENHANC_COD, 1, 6) IN ('EVPLSN', 'EVPLGN', 'EVPLPN')    THEN 'Ethernet-NNI'       
              WHEN SUBSTR (ASR.NETWORK_CHANNEL_SERVICE_CODE, 1, 1) IN ('K') AND ASRD.ACTL IS NOT NULL AND SALI.EUNAME IS NULL
            AND ASR.SERVICE_AND_PRODUCT_ENHANC_COD <> 'GGAMAN' THEN 'Ethernet-NNI'
          WHEN SUBSTR (ASR.NETWORK_CHANNEL_SERVICE_CODE, 1, 1) IN ('K') THEN 'Ethernet-UNI'
          WHEN SUBSTR (C.SERVICE_TYPE_CODE, 1, 2) IN ('VL') THEN 'Ethernet-EVC'
          WHEN SUBSTR (SR.FIRST_ECCKT_ID, 4, 1) IN ('K') THEN 'Ethernet-UNI'
          WHEN SUBSTR (SR.FIRST_ECCKT_ID, 4, 2) IN ('VL') THEN 'Ethernet-EVC'
          WHEN SUBSTR (ASR.NETWORK_CHANNEL_SERVICE_CODE, 1, 1) = 'O' THEN 'OCN'
          WHEN EVC.RUID IS NOT NULL AND EVC2.RUID IS NOT NULL THEN 'Ethernet-EVC'
          ELSE NULL END AS PRODUCT,
       SR.PROJECT_IDENTIFICATION AS PROJ,
       C.RATE_CODE,
       REGEXP_REPLACE (SALI.EUNAME,'[[:cntrl:]]*') EUNAME,
       ASR.NETWORK_CHANNEL_SERVICE_CODE AS NC,
       ASR.NETWORK_CHANNEL_INTERFACE_CODE AS NCI,
       ASR.EVC_IND EVCI,
       MAX(DLR.SEC_NETWORK_CHANNEL_INTERFACE) AS SECNCI,
       ASR.SERVICE_AND_PRODUCT_ENHANC_COD AS SPEC,
       EVC.RUID AS RUID1,
       EVC2.RUID AS RUID2,
       EVC.LOS,
       CASE
          WHEN EVC.BDW IS NOT NULL THEN EVC.BDW || ' ' || EVC.BDW2
          WHEN ASR.NETWORK_CHANNEL_SERVICE_CODE = 'KD' THEN '10M'
          WHEN ASR.NETWORK_CHANNEL_SERVICE_CODE = 'KE' THEN '100M'
          WHEN ASR.NETWORK_CHANNEL_SERVICE_CODE = 'KF' THEN '1G'
          WHEN ASR.NETWORK_CHANNEL_SERVICE_CODE = 'KG' THEN '10G'
          WHEN ASR.NETWORK_CHANNEL_SERVICE_CODE = 'KP' THEN '10M Adj'
          WHEN ASR.NETWORK_CHANNEL_SERVICE_CODE = 'KQ' THEN '100M Adj'
          WHEN ASR.NETWORK_CHANNEL_SERVICE_CODE = 'KR' THEN '1G Adj'
          WHEN C.service_type_code = 'KD' THEN '10M'
          WHEN C.service_type_code = 'KE' THEN '100M'
          WHEN C.service_type_code = 'KF' THEN '1G'
          WHEN C.service_type_code = 'KG' THEN '10G'
          WHEN C.service_type_code = 'KP' THEN '10M Adj'
          WHEN C.service_type_code = 'KQ' THEN '100M Adj'
          WHEN C.service_type_code = 'KR' THEN '1G Adj'
          ELSE 'OTHER'
       END
          AS BDW,
       ASRD.BILL_PNUM AS PNUM,
       ASR.EXPEDITE_INDICATOR AS EXPEDITE,
       ASRD.ACTL,
       MAX (N.USER_ID) KEEP (DENSE_RANK LAST ORDER BY N.LAST_MODIFIED_DATE) AS PMO_USER_ID,
       MAX (R."UserName") KEEP (DENSE_RANK LAST ORDER BY N.LAST_MODIFIED_DATE) AS PM_NAME,
       MAX (REGEXP_REPLACE (N.NOTE_TEXT, '[[:cntrl:]]*')) KEEP (DENSE_RANK LAST ORDER BY N.LAST_MODIFIED_DATE) AS M6_NOTES,
       MAX (N.DATE_ENTERED) KEEP (DENSE_RANK LAST ORDER BY N.LAST_MODIFIED_DATE) AS DATE_ENTERED,
       ASR.NPA||ASR.NXX as NPANXX,
       --listagg(tskr.task_type, ' / ') WITHIN GROUP (ORDER BY tskr.sequence) as ready_task
       --listagg(tskr.work_queue_id, ' / ') WITHIN GROUP (ORDER BY tskr.sequence) as ready_workq
       tskr.task_type as ready_task,
       tskr.work_queue_id as ready_workq,
       case when trunc(sysdate) = trunc(tskr.actual_release_date) then 0
            when trunc(sysdate) >= trunc(tskr.actual_release_date) 
            then (SELECT COUNT(*) FROM DUAL WHERE TO_CHAR(tskr.actual_release_date + LEVEL - 1, 'DY') NOT IN ('SAT', 'SUN')
            CONNECT BY LEVEL <= trunc(sysdate) - trunc(tskr.actual_release_date)) 
            else (SELECT COUNT(*) FROM DUAL WHERE TO_CHAR(sysdate + LEVEL - 1, 'DY') NOT IN ('SAT', 'SUN')
            CONNECT BY LEVEL <= trunc(tskr.actual_release_date) - trunc(sysdate))*-1 end AS WkDays_in_Task
  FROM ASAP.NOTES N
                 INNER JOIN LAA122.RW_TM R ON (N.USER_ID = R."UserLogin")
                 RIGHT OUTER JOIN ASAP.SERV_REQ SR ON (SR.DOCUMENT_NUMBER = N.DOCUMENT_NUMBER)
               LEFT OUTER JOIN ASAP.DESIGN_LAYOUT_REPORT DLR ON (SR.DOCUMENT_NUMBER = DLR.DOCUMENT_NUMBER)
              LEFT OUTER JOIN ASAP.CIRCUIT C ON (DLR.CIRCUIT_DESIGN_ID = C.CIRCUIT_DESIGN_ID)
             LEFT OUTER JOIN ASAP.ASR_USER_DATA AUD ON (SR.DOCUMENT_NUMBER = AUD.DOCUMENT_NUMBER)
            LEFT OUTER JOIN DATA_EXT.ASR_SALI SALI ON (SR.DOCUMENT_NUMBER = SALI.DOCUMENT_NUMBER)
           LEFT OUTER JOIN DATA_EXT.ASR_DETAIL ASRD ON (SR.DOCUMENT_NUMBER = ASRD.DOCUMENT_NUMBER)
          LEFT OUTER JOIN ASAP.ACCESS_SERVICE_REQUEST ASR ON (SR.DOCUMENT_NUMBER = ASR.DOCUMENT_NUMBER)
         LEFT OUTER JOIN DATA_EXT.ASR_EVC EVC ON (SR.DOCUMENT_NUMBER = EVC.DOCUMENT_NUMBER)
        LEFT OUTER JOIN DATA_EXT.ASR_EVC EVC2 ON (SR.DOCUMENT_NUMBER = EVC2.DOCUMENT_NUMBER)
       LEFT OUTER JOIN ASAP.TASK T ON (SR.DOCUMENT_NUMBER = T.DOCUMENT_NUMBER)
       left outer join task tskr on sr.document_number = tskr.document_number and tskr.task_status = 'Ready' 
       --LEFT OUTER JOIN LAA122.GEOG_201604 GEOG
         -- ON (ASR.NPA || '' || ASR.NXX = GEOG.NPANXX)
 WHERE     (   (SR.ACNA NOT IN ('FLR','ZZZ','CUS','FCA','ZWV','CQV','ZTK','AWL','XYY','SNE','MJC','OPT','WCG'))
            OR (SR.ACNA IS NULL))
       AND (   (SUBSTR (SR.FIRST_ECCKT_ID, 4, 1) NOT IN ('H', 'L', 'X'))
            OR (SR.FIRST_ECCKT_ID IS NULL))
       AND (   (    SR.PROJECT_IDENTIFICATION NOT LIKE 'ATTMOB%'
                AND SR.PROJECT_IDENTIFICATION NOT LIKE 'MPAEVC%')
            OR (SR.PROJECT_IDENTIFICATION IS NULL))
       AND (   (C.RATE_CODE NOT IN ('DS0', 'DS1', 'DS3'))
            OR (C.RATE_CODE IS NULL))
       AND (   (SUBSTR (ASR.NETWORK_CHANNEL_SERVICE_CODE, 1, 1) NOT IN
                   ('H', 'L', 'X'))
            OR (ASR.NETWORK_CHANNEL_SERVICE_CODE IS NULL))
       AND ( (EVC.UREF = '01') OR (EVC.UREF IS NULL))
       AND ( (EVC2.UREF = '02') OR (EVC2.UREF IS NULL))
       AND ( T.TASK_TYPE IN ('DD') OR T.TASK_TYPE IS NULL)
       AND (SR.TYPE_OF_SR = 'ASR')
       AND (ASR.REQUEST_TYPE IN ('S', 'E'))
       AND (ASR.ACTIVITY_INDICATOR IN ('N', 'C'))
       AND (TO_CHAR(T.ACTUAL_COMPLETION_DATE,'YYYY') >= '2023' or T.ACTUAL_COMPLETION_DATE is null)
       AND (SR.DOCUMENT_NUMBER > 1251000)
       --AND ( (SR.SUPPLEMENT_TYPE <> '1') OR (SR.SUPPLEMENT_TYPE IS NULL))
GROUP BY SR.PON,
         SR.DOCUMENT_NUMBER,
         SR.ACNA,
         SR.ACTIVITY_IND,
         SR.SUPPLEMENT_TYPE,
         SR.FIRST_ECCKT_ID,
         ASR.DATE_TIME_SENT,
         ASR.DESIRED_DUE_DATE,
         AUD.CRDD,
         T.ACTUAL_COMPLETION_DATE,
         TRIM (SALI.SANO||' '||SALI.SASN||' '||SALI.SATH),
         SALI.CITY,
         ASR.ACCESS_PROVIDER_SERV_CTR_CODE,
         SR.PROJECT_IDENTIFICATION,
         C.RATE_CODE,
         C.NETWORK_CHANNEL_SERVICE_CODE,
         C.SERVICE_TYPE_CODE,
         SALI.EUNAME,
         ASR.NETWORK_CHANNEL_SERVICE_CODE,
         ASR.NETWORK_CHANNEL_INTERFACE_CODE,
         ASR.EVC_IND,
         --DLR.SEC_NETWORK_CHANNEL_INTERFACE,
         ASR.SERVICE_AND_PRODUCT_ENHANC_COD,
         EVC.RUID,
         EVC2.RUID,
         EVC.LOS,
         ASRD.BILL_PNUM,
         ASR.EXPEDITE_INDICATOR,
         ASRD.ACTL,
         CASE
            WHEN EVC.BDW IS NOT NULL THEN EVC.BDW || ' ' || EVC.BDW2
            WHEN ASR.NETWORK_CHANNEL_SERVICE_CODE = 'KD' THEN '10M'
            WHEN ASR.NETWORK_CHANNEL_SERVICE_CODE = 'KE' THEN '100M'
            WHEN ASR.NETWORK_CHANNEL_SERVICE_CODE = 'KF' THEN '1G'
            WHEN ASR.NETWORK_CHANNEL_SERVICE_CODE = 'KG' THEN '10G'
            WHEN ASR.NETWORK_CHANNEL_SERVICE_CODE = 'KP' THEN '10M Adj'
            WHEN ASR.NETWORK_CHANNEL_SERVICE_CODE = 'KQ' THEN '100M Adj'
            WHEN ASR.NETWORK_CHANNEL_SERVICE_CODE = 'KR' THEN '1G Adj'
            WHEN C.service_type_code = 'KD' THEN '10M'
            WHEN C.service_type_code = 'KE' THEN '100M'
            WHEN C.service_type_code = 'KF' THEN '1G'
            WHEN C.service_type_code = 'KG' THEN '10G'
            WHEN C.service_type_code = 'KP' THEN '10M Adj'
            WHEN C.service_type_code = 'KQ' THEN '100M Adj'
            WHEN C.service_type_code = 'KR' THEN '1G Adj'
            ELSE 'OTHER'
         END,
 CASE 
          WHEN SUBSTR (C.NETWORK_CHANNEL_SERVICE_CODE, 1, 2) IN ('SN') THEN 'Ethernet-NNI'
          WHEN SUBSTR (ASR.SERVICE_AND_PRODUCT_ENHANC_COD, 1, 6) IN ('EVPLSN', 'EVPLGN', 'EVPLPN')    THEN 'Ethernet-NNI'       
              WHEN SUBSTR (C.NETWORK_CHANNEL_SERVICE_CODE, 1, 1) IN ('K') AND ASRD.ACTL IS NOT NULL AND SALI.EUNAME IS NULL
            AND ASR.SERVICE_AND_PRODUCT_ENHANC_COD <> 'GGAMAN' THEN 'Ethernet-NNI'
          WHEN SUBSTR (C.NETWORK_CHANNEL_SERVICE_CODE, 1, 1) IN ('K') THEN 'Ethernet-UNI'
          WHEN SUBSTR (C.SERVICE_TYPE_CODE, 1, 1) IN ('V') THEN 'Ethernet-EVC'
          WHEN SUBSTR (SR.FIRST_ECCKT_ID, 4, 1) IN ('K') THEN 'Ethernet-UNI'
          WHEN SUBSTR (SR.FIRST_ECCKT_ID, 4, 1) IN ('V') THEN 'Ethernet-EVC'
          WHEN SUBSTR (C.NETWORK_CHANNEL_SERVICE_CODE, 1, 1) = 'O' THEN 'OCN'
          ELSE NULL END,
        CASE
          WHEN SALI.STATE IS NOT NULL THEN SUBSTR (SALI.STATE, 1, 2)
          WHEN ASR.ACCESS_PROVIDER_SERV_CTR_CODE = 'FV01' THEN 'WV'
          WHEN ASR.ACCESS_PROVIDER_SERV_CTR_CODE = 'SN01' AND SUBSTR (SR.FIRST_ECCKT_ID, 1, 2) = 'FA' THEN 'CT'
          WHEN SUBSTR (ASR.ACCESS_PROVIDER_SERV_CTR_CODE, 1, 2) = 'FV' AND SUBSTR (SR.FIRST_ECCKT_ID, 1, 2) = '30' THEN 'IL'
          WHEN SUBSTR (ASR.ACCESS_PROVIDER_SERV_CTR_CODE, 1, 2) = 'FV' AND SUBSTR (SR.FIRST_ECCKT_ID, 1, 2) = '31' THEN 'IN'
          WHEN SUBSTR (ASR.ACCESS_PROVIDER_SERV_CTR_CODE, 1, 2) = 'FV' AND SUBSTR (SR.FIRST_ECCKT_ID, 1, 2) = '33' THEN 'MI'
          WHEN SUBSTR (ASR.ACCESS_PROVIDER_SERV_CTR_CODE, 1, 2) = 'FV' AND SUBSTR (SR.FIRST_ECCKT_ID, 1, 2) = '36' THEN 'OH'
          WHEN SUBSTR (ASR.ACCESS_PROVIDER_SERV_CTR_CODE, 1, 2) = 'FV' AND SUBSTR (SR.FIRST_ECCKT_ID, 1, 2) = '39' THEN 'WI'
          WHEN SUBSTR (ASR.ACCESS_PROVIDER_SERV_CTR_CODE, 1, 2) = 'FV' AND SUBSTR (SR.FIRST_ECCKT_ID, 1, 2) = '43' THEN 'OR'
          WHEN SUBSTR (ASR.ACCESS_PROVIDER_SERV_CTR_CODE, 1, 2) = 'FV' AND SUBSTR (SR.FIRST_ECCKT_ID, 1, 2) in ('61','63') THEN 'NC'
          WHEN SUBSTR (ASR.ACCESS_PROVIDER_SERV_CTR_CODE, 1, 2) = 'FV' AND SUBSTR (SR.FIRST_ECCKT_ID, 1, 2) = '62' THEN 'SC'
          WHEN SUBSTR (ASR.ACCESS_PROVIDER_SERV_CTR_CODE, 1, 2) = 'FV' AND SUBSTR (SR.FIRST_ECCKT_ID, 1, 2) = '83' THEN 'ID'
          WHEN SUBSTR (ASR.ACCESS_PROVIDER_SERV_CTR_CODE, 1, 2) = 'FV' AND SUBSTR (SR.FIRST_ECCKT_ID, 1, 2) = '85' THEN 'OR'
          WHEN SUBSTR (ASR.ACCESS_PROVIDER_SERV_CTR_CODE, 1, 2) = 'FV' AND SUBSTR (SR.FIRST_ECCKT_ID, 1, 2) = '86' THEN 'WA'
          WHEN SUBSTR (ASR.ACCESS_PROVIDER_SERV_CTR_CODE, 1, 2) <> 'FV' AND SUBSTR (SR.FIRST_ECCKT_ID, 1, 2) = '61' THEN 'PA'
          WHEN SUBSTR (ASR.ACCESS_PROVIDER_SERV_CTR_CODE, 1, 2) = 'GT' AND SUBSTR (SR.FIRST_ECCKT_ID, 1, 2) in ('45','80','81') THEN 'CA'
          WHEN SUBSTR (ASR.ACCESS_PROVIDER_SERV_CTR_CODE, 1, 2) = 'GT' AND SUBSTR (SR.FIRST_ECCKT_ID, 1, 2) in ('12','13') THEN 'TX'
          WHEN SUBSTR (ASR.ACCESS_PROVIDER_SERV_CTR_CODE, 1, 2) = 'GT' AND SUBSTR (SR.FIRST_ECCKT_ID, 1, 2) in ('65','69') THEN 'FL'
          WHEN SUBSTR (SR.FIRST_ECCKT_ID, 1, 2) = '23' THEN 'MN'
          WHEN SUBSTR (SR.FIRST_ECCKT_ID, 1, 2) = '50' THEN 'WV'
          WHEN SUBSTR (SR.FIRST_ECCKT_ID, 1, 2) = '11' THEN 'AZ'
          WHEN SUBSTR (SR.FIRST_ECCKT_ID, 1, 2) = '97' THEN 'NY'
          WHEN ASR.ACCESS_PROVIDER_SERV_CTR_CODE = 'RT01' THEN 'NY'
          ELSE NULL END,
          ASR.NPA||ASR.NXX,
          tskr.task_type,
          tskr.work_queue_id,
          tskr.actual_release_date
) subq         
LEFT OUTER JOIN LAA122.EDW_OGM_REGIONS GEOG ON (SUBQ.NPANXX = GEOG.NPANXX_CD)
LEFT OUTER JOIN LAA122.MASTERCUSTOMERLIST MCL ON SUBQ.ACNA = MCL.SECONDARY_ID
left outer join access_cust cust on subq.acna = cust.customer_name_abbreviation
left outer join party on cust.party_id = party.party_id
left outer join task tsk on subq.docno = tsk.document_number and tsk.task_type = 'ASR-CONF'
group by 
   nvl(GEOG.REGION_DS, --FIND REGION FROM EDW OGM FOR OFFICIAL ALIGNMENT AND IF NOT FOUND USE STATE LOOKUP BELOW
      case when subq.state in ('CT','NY','PA','MD','AL','FL','GA','MS','NC','SC','TN') then 'Eastern'
        when subq.state in ('IA','IL','IN','MI','MN','NE','WI','KY','TX','WV','VA','OH') then 'Central'
        when subq.state in ('CA','AZ','NM','NV','UT','ID','MT') then 'Western'
           else null end), 
   PON, DOCNO, ACNA, ACT_IND, SUPP, CKT, D_REC, tsk.actual_completion_date, DD, DDD, COMP_DT, ADDRESS, CITY, STATE, ICSC, PRODUCT, PROJ, RATE_CODE, EUNAME, NC, NCI, SECNCI,    
     SPEC, RUID1, RUID2, LOS, BDW, PNUM, EXPEDITE, ACTL, PMO_USER_ID, PM_NAME, M6_NOTES, DATE_ENTERED, NPANXX,
   party.party_name,
   MCL.PRIMARY_CARRIER_NAME,
   MCL.SALES_MANAGER,
   MCL.ACCT_EXECUTIVE,
   EVCI
ORDER BY 12, 10;
