SELECT SR.DOCUMENT_NUMBER, 
       ASR.REQUEST_TYPE, 
       MAX(ASR.PROJECT_IDENTIFICATION) KEEP (DENSE_RANK LAST ORDER BY ASR.LAST_MODIFIED_DATE) PROJECT, 
       MAX(ASR.DATE_TIME_SENT) KEEP (DENSE_RANK LAST ORDER BY ASR.LAST_MODIFIED_DATE) DREC, 
       MAX(ASR.DESIRED_DUE_DATE) KEEP (DENSE_RANK LAST ORDER BY ASR.LAST_MODIFIED_DATE) DD, 
       MAX(AUD.CRDD) KEEP (DENSE_RANK LAST ORDER BY AUD.LAST_MODIFIED_DATE) DDD, 
       MIN(ACCEPTANCE_DATE) KEEP (DENSE_RANK LAST ORDER BY AUD.LAST_MODIFIED_DATE) ACCEPT_DT, 
       MAX(ASR.NETWORK_CHANNEL_SERVICE_CODE) KEEP (DENSE_RANK LAST ORDER BY ASR.LAST_MODIFIED_DATE) NC, 
       MAX(ASR.PON) KEEP (DENSE_RANK LAST ORDER BY ASR.LAST_MODIFIED_DATE) PON,  
       MAX(ACCESS_PROVIDER_SERV_CTR_CODE) ICSC, 
       MAX(SR.ACNA) ACNA,  
       MAX(ASR.ACTIVITY_INDICATOR) KEEP (DENSE_RANK LAST ORDER BY ASR.LAST_MODIFIED_DATE) ACT, 
       MAX(JEOPARDY_REASON_CODE) KEEP (DENSE_RANK LAST ORDER BY JW.LAST_MODIFIED_DATE) JEOP,
       MAX(SUBSTR(NL1.CLLI_CODE,1,6)) KEEP (DENSE_RANK LAST ORDER BY NL1.LAST_MODIFIED_DATE) CLLIZ, 
       TRUNC(T.ACTUAL_COMPLETION_DATE-4/24) DD_COMP,
       MAX(SR.SUPPLEMENT_TYPE) KEEP (DENSE_RANK LAST ORDER BY SR.LAST_MODIFIED_DATE) SUPP,
       MAX(SR.FIRST_ECCKT_ID) KEEP (DENSE_RANK LAST ORDER BY SR.LAST_MODIFIED_DATE) CKT,
       MAX(EXPEDITE_INDICATOR) KEEP (DENSE_RANK LAST ORDER BY ASR.LAST_MODIFIED_DATE) EXPEDITE,
       MAX(ASR.EVC_IND) KEEP (DENSE_RANK LAST ORDER BY ASR.LAST_MODIFIED_DATE) EVC_IND,
       MAX(ASR.UNBUNDLED_NETWORK_ELEMENT) KEEP (DENSE_RANK LAST ORDER BY ASR.LAST_MODIFIED_DATE) UNE,
       MAX(ASR.NPA) KEEP (DENSE_RANK LAST ORDER BY ASR.LAST_MODIFIED_DATE) NPA,
       MAX(ASR.NXX) KEEP (DENSE_RANK LAST ORDER BY ASR.LAST_MODIFIED_DATE) NXX,
       MIN(NTS.LAST_MODIFIED_DATE) KEEP (DENSE_RANK FIRST ORDER BY NTS.LAST_MODIFIED_DATE) M6_INIT,
       TRUNC(MIN(VFO.CREATIONDATETIME) KEEP (DENSE_RANK FIRST ORDER BY VFO.UPDATEDATETIME)) VFO_INIT
FROM WHSL_ADV_HIST.M6_ASR_USER_DATA_THIST AUD, 
     WHSL_ADV_HIST.M6_ACCS_SVC_REQUEST_THIST ASR,
     WHSL_ADV_HIST.M6_SERV_REQ_THIST SR,
     WHSL_ADV_HIST.M6_NTWK_LOC_THIST NL1,
     WHSL_ADV_HIST.M6_TASK_JEOPARDY_WHYMISS_THIST JW,
     WHSL_ADV_HIST.M6_TASK_THIST T,
     WHSL_ADV_HIST.M6_CIRCUIT_THIST C,
     WHSL_ADV_HIST.M6_NOTES_THIST NTS,
     WHSL_ADV_HIST.VFO_ORDERHISTORYINFO_THIST VFO    
WHERE SR.DOCUMENT_NUMBER = ASR.DOCUMENT_NUMBER
  AND SR.DOCUMENT_NUMBER = AUD.DOCUMENT_NUMBER(+)
  AND SR.FIRST_ECCKT_ID = C.EXCHANGE_CARRIER_CIRCUIT_ID
  AND C.LOCATION_ID_2 = NL1.LOCATION_ID(+)
  AND SR.DOCUMENT_NUMBER = T.DOCUMENT_NUMBER
  AND SR.DOCUMENT_NUMBER = NTS.DOCUMENT_NUMBER (+)
  AND SR.PON = VFO.PON (+)
  AND T.TASK_NUMBER = JW.TASK_NUMBER(+)
  AND VFO.ORDERSTATUS(+) = 'Accepted_Submitted'
  AND TO_CHAR(T.ACTUAL_COMPLETION_DATE,'yyyymm') = '201707'   --CHANGE EACH MONTH - CURRENT REPORTING MONTH  
  AND ASR.REQUEST_TYPE IN ('S','E')
  AND ASR.ACTIVITY_INDICATOR IN ('N','C')
  AND ASR.ORDER_TYPE = 'ASR'
  AND JW.JEOPARDY_TYPE_CD(+) = 'W' 
  AND T.TASK_TYPE = 'DD'
  AND SR.DOCUMENT_NUMBER = '2606658'
  GROUP BY SR.DOCUMENT_NUMBER, ASR.REQUEST_TYPE, T.ACTUAL_COMPLETION_DATE