SELECT DOCUMENT_NUMBER, PON, VERSION, ORDER_STATUS, SUPP_TYPE, VFO_STATUS, 
       ACT, CCNA, 
       CASE WHEN TO_CHAR(DATE_ENTERED,'YYYYMMDD') < '20211107' THEN DATE_ENTERED-4/24   --DID THIS TO MATCH THE TIMES SHOWN FROM VFO DATE_ENTERED FIELD   
            ELSE DATE_ENTERED-5/24 END DATE_ENTERED, 
       USER_ID, NOTE_TEXT
FROM (
SELECT
  NTS.DOCUMENT_NUMBER,
  null PON,
  null VERSION,
  null ORDER_STATUS,
  null SUPP_TYPE,
  null VFO_STATUS,
  null ACT,
  null CCNA,
  NTS.DATE_ENTERED,
  NTS.USER_ID,
  CASE WHEN USER_ID = 'ASR_OM' AND NOTE_TEXT NOT LIKE 'AUTO-CNR%' THEN 'EXCLUDE' ELSE 'INCLUDE' END STATUS,
  NTS.NOTE_TEXT
  FROM NOTES NTS  
  WHERE (UPPER(NTS.NOTE_TEXT) LIKE '%VERSION%CNR%' OR UPPER(NTS.NOTE_TEXT) LIKE '%SENT%CNR%' OR UPPER(NTS.NOTE_TEXT) LIKE '%CNR%SENT%' OR UPPER(NTS.NOTE_TEXT) LIKE '%CLARIFICATION%SENT%') 
  AND TO_CHAR(DATE_ENTERED,'YYYYMM') >= '202109'
  AND (NOTE_TEXT NOT LIKE '%FOLLOWUP%' AND NOTE_TEXT NOT LIKE '%BDT%' AND NOTE_TEXT NOT LIKE '%BOLD CHAT%' AND NOTE_TEXT NOT LIKE '%SHORT INTERVAL%' AND NOTE_TEXT NOT LIKE '%INFORMATION%')
  AND USER_ID NOT IN ('EWO_CNL','INFO_CNR')
  AND DOCUMENT_NUMBER IN 
  (
'3650095',
'3652966'         
) 
---
)WHERE STATUS = 'INCLUDE'
ORDER BY 1,9
;

