SELECT DISTINCT ASR.DOCUMENT_NUMBER, PON, VERSION_IDENTIFICATION VER, PON||VERSION_IDENTIFICATION PONVER, 
       DATE_TIME_SENT, DATE_RECEIVED, SUPPLEMENT_TYPE, 
CASE WHEN T.ACTUAL_COMPLETION_DATE IS NULL THEN 'PENDING'
     WHEN T.ACTUAL_COMPLETION_DATE IS NOT NULL AND SUPPLEMENT_TYPE = 1 THEN 'CANCELLED'
     ELSE 'COMPLETE' END STATUS
FROM CASDW.ACCESS_SERVICE_REQUEST ASR , CASDW.TASK T 
WHERE ASR.DOCUMENT_NUMBER = T.DOCUMENT_NUMBER (+)
--AND T.TASK_STATUS (+) = 'Ready'
AND TASK_TYPE(+) = 'DD'
AND ASR.DOCUMENT_NUMBER in (
'3615408'
)
ORDER BY 1,2,3,4,5;
;


