SELECT *
FROM (
SELECT
  NTS.DOCUMENT_NUMBER,
  NTS.NOTES_SEQUENCE,
  NTS.DATE_ENTERED,
  NTS.USER_ID,
  CASE WHEN USER_ID = 'ASR_OM' AND NOTE_TEXT NOT LIKE 'AUTO-CNR%' THEN 'EXCLUDE' ELSE 'INCLUDE' END STATUS,
  NTS.NOTE_TEXT,
---------------------  
  (SELECT DISTINCT 
  LISTAGG(DT_VER_SUP, ' / ') WITHIN GROUP (ORDER BY DT) OVER (PARTITION BY DOCUMENT_NUMBER) AS DT_VER_SUP
  FROM
  (
  SELECT DISTINCT
  AAH.DOCUMENT_NUMBER,
  TO_CHAR(AAH.LAST_MODIFIED_DATE,'YYYY-MM-DD HH:MI') AS DT,
  TO_CHAR(AAH.LAST_MODIFIED_DATE,'YYYY-MM-DD HH:MI')||': '||
  AAH.FIELD_NAME||' '|| AAH.CURRENT_FIELD_VALUE||' '|| AAH2.FIELD_NAME||' '|| AAH2.CURRENT_FIELD_VALUE AS DT_VER_SUP
  FROM ASR_AUDIT_HISTORY AAH
  LEFT OUTER JOIN ASR_AUDIT_HISTORY AAH2 ON AAH2.FIELD_NAME = 'SUP' 
    AND AAH.DOCUMENT_NUMBER = AAH2.DOCUMENT_NUMBER
    AND AAH.VERSION = AAH2.VERSION
    --AND TO_CHAR(AAH.LAST_MODIFIED_DATE,'YYYY-MM-DD HH') = TO_CHAR(AAH2.LAST_MODIFIED_DATE,'YYYY-MM-DD HH')
  WHERE AAH.FIELD_NAME IN('VER')
  ) SUBQ1
 WHERE SUBQ1.DOCUMENT_NUMBER = NTS.DOCUMENT_NUMBER) AS dt_ver_sup
-------------------------
  FROM NOTES NTS  
  WHERE (NTS.NOTE_TEXT LIKE '%VERSION%CNR%' OR NTS.NOTE_TEXT LIKE '%SENT%CNR%' OR NTS.NOTE_TEXT LIKE '%CNR%SENT%' OR NTS.NOTE_TEXT LIKE '%CLARIFICATION%SENT%' OR NTS.NOTE_TEXT LIKE '%JEOPARDY%CODE%')
  AND TO_CHAR(DATE_ENTERED,'YYYYMM') >= '202109'
  AND (NOTE_TEXT NOT LIKE '%FOLLOWUP%' AND NOTE_TEXT NOT LIKE '%BDT%' AND NOTE_TEXT NOT LIKE '%BOLD CHAT%' AND NOTE_TEXT NOT LIKE '%SHORT INTERVAL%' AND NOTE_TEXT NOT LIKE '%INFORMATION%')
  AND USER_ID NOT IN ('EWO_CNL','INFO_CNR')
  AND DOCUMENT_NUMBER IN 
  (
----  
'3685111',
'3684608',
'3671805',
'3686421',
'3686726',
'3685439',
'3684588',
'3679745',
'3680296',
'3685847'  
) 
)WHERE STATUS = 'INCLUDE'
ORDER BY 1,2
;
