select a.CCNA,a.SPEC,b.ECCKT,b.IC_ECCKT,a.PON,a.D_REC,A.PSTAT,KSTAT,a.DSTAT,a.ESTAT,a.ISTAT,
a.D_PSTAT,a.T_PSTAT,a.D_KSTAT,a.T_KSTAT,a.D_ESTAT,a.T_ESTAT,a.D_ISTAT,a.T_ISTAT,a.D_DSTAT,a.T_DSTAT,a.ICSC,a.ASR,a.EVC_LATA,a.DT_STAMP,a.DT_EXTRACT,
a.T_REC,a.T_PROC,a.TM_STAMP,a.TM_EXTRACT,a.EXACT_REL,a.COMP_ADM||a.COMP_VCF||a.COMP_MSL||a.COMP_ACI||a.COMP_TRK||a.COMP_WAT||a.COMP_SPE||a.COMP_FGA||a.COMP_FGB||a.COMP_EUS||a.COMP_SOC||
a.COMP_MEC||a.COMP_EUA||a.COMP_EOD||a.COMP_TQ1||a.COMP_TQ2||a.COMP_TQ3||a.COMP_TQ4||a.FILLER3||a.COMP_FB2||a.COMP_SP2||a.COMP_TQA||a.COMP_RNG||a.COMP_ARI||a.COMP_NAI||a.COMP_SAL||a.COMP_TQ6||a.COMP_TQ7||a.COMP_PC||
a.COMP_TQB||a.COMP_EVC||a.COMP_VC1||a.COMP_VC2||a.COMP_VC3 COMP,a.JEP,a.EXPECTED_MSL,a.EXPECTED_CKR,a.NEXT_CKTREF,a.CKT_CNT,a.CONFIRM_FLAG,a.READY_FLAG,a.PENDING_FLAG,a.COMPLETE_FLAG,a.JEP_CNT,a.LEG_CNT,
a.AUDITED,a.PREV_READY,a.SUPP_ADD,a.SUPP_FLAG,a.ASI,a.SUPP#,a.AUDIT_SEQ#,a.BATCH_FLAG,a.FTS_DEST_ID,a.EXTRACT_FLGS,a.D_CNF,a.T_CNF,a.REQTYP,a.ACT,a.DDD,a.EXP,a.D_SENT,
a.T_SENT,a.ACTL,a.ACTL_PRI_LSO,a.ACTL_LATA,a.BAN,a.SUPP,a.CKTQTY,a.PIU,a.AENG,a.ALBR,a.NOR_G,a.NOR_T,a.OR3_IND,a.CCVN,a.CB_TEL_AREA||a.CB_TEL_EXCH||a.CB_TEL_NUM CB_TEL,a.CCI,a.TUF_SOWA_IND,
a.TSC,a.NQ,a.AGAUTH,a.DATED,a.CUST,a.QA,a.TRKGRP,a.PROJECT,a.RPON,a.VER,a.AFO,a.BIC,a.BIC_AREA,a.BIC_EXCH,a.BIC_NUM BIC_TEL,a.BIC_ID,a.APOT,a.QTY,a.D_PROC,a.PREVAL_IND,a.ASR_REMARKS,a.ACNA,
a.BILLNM,a.SBILLNM,a.BILL_STR,a.BILL_FL,a.BILL_RM,a.BILL_CITY,a.DV_CNF_TYPE,a.DV_XCLEAR,a.BILLCON,a.BILLCON_AREA||a.BILLCON_EXCH||a.BILLCON_NUM||a.BILLCON_EXT BILLCON_TEL,a.FNT,a.PRILOC_PI,a.SAN,a.INIT,
a.INIT_AREA_CD||a.INIT_EXCH||a.INIT_NUM||a.INIT_EXT INIT_TEL,a.BILL_EMAIL,a.PALCON_AREA||a.PALCON_EXCH||a.PALCON_NUM||a.PALCON_EXT PALCON_TEL,a.PALCON_EMAIL,a.DSGCON,a.DSGCON_AREA||a.DSGCON_EXCH||a.DSGCON_NUM||a.DSGCON_EXT DSGCON_TEL,a.DSGCON_STR,a.DSGCON_FL,
a.DSGCON_RM,a.DSGCON_CITY,a.WSI,a.WSI_P, a.PSD,a.IMPCON,a.IMPCON_AREA||a.IMPCON_EXCH||a.IMPCON_NUM||a.IMPCON_EXT IMPCON_TEL,a.NC,a.NCI,a.SECNCI,a.TLV_T,a.TLV_R,a.SECTLV_T,a.SECTLV_R,a.RTR,a.FMT,a.FG,
a.CBTEL_AREA_P||a.CBTEL_EXCH_P||a.CBTEL_NUM_P CBTEL_TEL,a.SERV_REMARKS,a.EXACT_CON,a.RSP,a.SR2,a.DTO,a.OTC,a.DRL,a.GETO,a.QSA,a.EXPECTED_SA,a.SA_CNT,
a.S25,a.PRI_EUNAME,a.PRILOC_AFT,a.PRILOC_SAPR,a.PRILOC_SANO,a.PRILOC_SASF,a.PRILOC_SASD,a.SAP_ADDRESS,a.PRILOC_SATH,a.PRILOC_SASS,a.PRILOC_LD1,a.PRILOC_LV1,a.PRILOC_LD2,a.PRILOC_LV2,a.PRILOC_LD3,PRILOC_LV3,
a.CBD,a.SAP_IND,a.CKLT,a.NSL,a.HPF,a.TTT,a.SCD,a.FUSF,a.HNTYP,a.SCRT,a.CNR_VER,a.CHOK,a.CGAP,a.UNIT,a.CAD,a.SVC_TYPE_MLH,a.SYSMSG1,a.NAC_RMKS,a.ICSC_RMKS,
a.PRILOC_S25,a.ESN,a.PRILOC_NCON,a.ACTI,a.HVP,a.EVCI,a.LAG,a.EUCON,a.EUCON_AREA||a.EUCON_EXCH||a.EUCON_NUM||a.EUCON_EXT EUCON_TEL,a.EUCON_STR,a.EUCON_CITY,a.EUCON_FL,a.EUCON_RM,a.EUCON_ZIP,
a.BILL_ZIP,a.DSGCON_ZIP,a.D_OWNER,a.T_OWNER,a.LADATED,a.LANM,a.LATA,a.MWA_MSG_IND,a.MWA_MSG_FUNC,a.PRI_ALCON,a.ACTL_PRI_SWC,a.TRFTYP_ORIG,a.TRFTYP_TERM,
a.PRE_RED_MUSER,a.POST_RED_MUSER,a.RECCKT2,a.NPA_NXX,a.CAC_CONTACT,a.CAC_AREA||a.CAC_EXCH||a.CAC_NUM CAC_TEL,a.CAC_REMARK1||a.CAC_REMARK2 CAC_REMARK,a.PRILOC_I||a.PRILOC_C PRILOC,a.PRILOC_CITY,
a.PRILOC_STATE,a.PRILOC_SASN,a.PRILOC_ZIP,a.MWA_USER,a.PRILOC_OTC,a.PRILOC_AREA||a.PRILOC_EXCH||a.PRILOC_NUM PRILOC_TEL,a.PRILOC_ICOL,a.MCO_EXT,a.PRILOC_JKCDE,a.PRILOC_PCA,a.PRILOC_JKNUM,a.PRILOC_JKPOS,a.PRILOC_JS,a.PNUM,a.SFNI,a.SMUXLOC,a.PPTD,a.PRILOC_AAI,a.PRILOC_LCON,a.PRILOC_ACC,
a.ECREP,a.ECREP_AREA||a.ECREP_EXCH||a.ECREP_NUM ECREP_TEL,a.ECVER,a.EXTRACT_MODE,a.CUS,a.SLS,a.SPO,a.TSC4,a.CD,a.ORIGINAL_DD,a.ICSC_NOTES,a.DEPAMT,
a.CFM_NOTES,a.CBPC,a.EVC_SVCD,a.REFL,a.DEPNUM,a.MCO_AREA||a.MCO_EXCH||a.MCO_NUM MCO_TEL,a.OCO,a.DIST_CD1,a.DIST_CD2,a.DIST_CD3,a.DIST_CD4,a.DIST_CD5,
a.DIST_CD6,a.DIST_CD7,a.DIST_CD8,a.DIST_CD9,a.DIST_CD10, 
a.CBPC_PROV,a.LAG_P,a.EDA,a.RFNI,a.NAG,a.PRILOC_AAI,a.LAGID_PROV,a.SBDW,a.ICOL2,a.NFRT,a.JPR,
---T_ESTCON,
a.POP,a.FUP,a.TE,a.DRC,a.MTCE,a.MTCE_AREA||a.MTCE_EXCH||a.MTCE_NUM MTCE_TEL,a.TBE,a.CIC,a.LUP,a.MREC_IND,a.TSP_TRACK,a.TSP_PRIOR,a.EBP,a.VTA,a.PRILOC_SPOT,a.NFI,a.NFQTY,a.FDLRD,a.FDD,
a.PRN,a.EXPN,a.SAVE_KSTAT,a.SAVE_PSTAT,a.SAVE_SUPP1,a.ACTUAL_RT,a.BAN_MAN_IND,a.ASC_OEC_IND,a.ACI_MSL_IND,a.EXR,a.PRILOC_EXR,a.PREV_SUPPID,a.CSPC1||a.CSPC2||a.CSPC3 CSPC,a.ECSPC1||a.ECSPC2||a.ECSPC3 ECSPC,a.TCIC1||a.TCIC2 TCIC,a.LT,a.SLC,a.MUXLOC,a.SPA1,a.SEI,a.AFG,
a.TQ,a.FDT,a.SPEC,a.QCFA,a.SECLOC_GETO,a.PRILOC_GCON,a.PRIGTEL_AREA||a.PRIGTEL_EXCH||a.PRIGTEL_NUM||a.PRIGTEL_EXT PRIGTEL_TEL,a.LAST_OEC_SEQ,a.OEC_ICSC1,a.OEC_ICSC2,a.OEC_ICSC3,a.OEC_ICSC4,a.OEC_ICSC5,a.NFR,a.LTP,a.FCDLRD,a.FSID,a.FRID,a.FWOT,a.FPTD,a.QACI,a.FACTL,a.NC1,
a.FIMPTEL_AREA||a.FIMPTEL_EXCH||a.FIMPTEL_NUM||a.FIMPTEL_EXT FIMPTEL_TEL,a.HCUS,a.ASR_MWA_IND,a.ASR_BYPASS,a.LA,a.FNI,a.REL_TSC_11,a.PRIGBTN_AREA||a.PRIGBTN_EXCH||a.PRIGBTN_NUM PRIGBTN_TEL,
a.CM_LTERM_KEY||a.CM_UOM_SOURCE||a.CM_FWD_REPLY||a.CM_FWD_LTERM||a.CM_REV_REPLY||a.CM_REV_LTERM CM_TCIS_LTRM,a.CM_PROCESS_ID||a.CM_SOURCE||a.CM_DEST_ID||a.CM_PRIORITY||a.CM_PARAM_ID||a.CM_ACOS_TYPE||a.CM_EXACT_TYPE||a.CM_RESERVED,
a.DV_FCLEAR,a.PRILOC_SI,a.PRI_WKTEL_AREA||a.PRI_WKTEL_EXCH||a.PRI_WKTEL_NUM PRIWKTEL_TEL,a.CSL,
a.CST,a.DV_RCLEAR,a.DV_ECLEAR,a.FDRC,a.PCACT,a.PCU1,a.PCU2,a.PCU3,a.PCU4,a.PCU5,a.PCU6,a.PCU7,a.PCU8,a.SSPC1_1||a.SSPC1_2||a.SSPC1_3||a.SSPC2_1||a.SSPC2_2||a.SSPC2_3||a.SSPC3_1||
a.SSPC3_2||a.SSPC3_3||a.SSPC4_1||a.SSPC4_2||a.SSPC4_3||a.SSPC5_1||a.SSPC5_2||a.SSPC5_3||a.SSPC6_1||a.SSPC6_2||a.SSPC6_3||a.SSPC7_1||a.SSPC7_2||a.SSPC7_3||a.SSPC8_1||a.SSPC8_2||a.SSPC8_3 SSPC,
--a.OEC_ICSC6,a.OEC_ICSC7,a.OEC_ICSC8,a.OEC_ICSC9,a.OEC_ICSC10,a.OEC_ICSC11,
a.SSPCTYP1,a.SSPCTYP2,a.SSPCTYP3,a.SSPCTYP4,a.SSPCTYP5,a.SSPCTYP6,a.SSPCTYP7,a.SSPCTYP8,a.SEGACT,
a.NID,a.CFNI,a.PRI_ADM,a.SEC_ADM,a.CPT1,a.CPT2,a.EXPECTED_ARI,a.ARI_CNT,a.OWNER,a.LMP,a.NU,a.LAST_ITD_CHAR,a.NVC,a.PSPEED,a.NEXT_VCNUM,a.EXPECTED_VC,a.VC_CNT,a.VC_REMARKS,a.SVCD,a.RT,
----from extg_vma01egs A
a.CASENUM,a.PLU,a.CC,a.FPI,a.LPIC,a.PRI_PNO,a.SEC_PNO,a.OCO_EXT,a.MTCE_EMAIL,a.BILL_STATE,a.DSGCON_STATE,a.EUCON_STATE,a.D_PROC_CC,a.D_REC_CC,a.D_PSTAT_CC,a.D_ISTAT_CC,a.RINGSPEC,a.NS,a.PSAP,a.BSC,a.VCVTA_ADM,
a.ETET,a.MWA_WRKGRP,a.DV_SEND_CNT,a.DV_ASR_FULL,a.QNAI,a.ACFA,a.AFACTL,a.EXPECTED_NAI,a.NAI_CNT,a.ASR_NAI_IND,a.ISTN_AREA||a.ISTN_EXCH||a.ISTN_NUM ISTN_TEL,a.ECREP_EXT,a.CRF_FLAG,a.WST,a.STDMR,a.UNE,a.PSL,a.PSLI,a.IWBAN,a.IFAX_AREA||a.IFAX_EXCH||a.IFAX_NUM IFAX_TEL
,a.INIT_EMAIL,a.DFAX_AREA||a.DFAX_EXCH||a.DFAX_NUM DFAX_TEL,
a.DSGCON_EMAIL,a.REP_EMAIL,a.CIWBAN,a.PIA,a.PAACTEL_AREA||a.PAACTEL_EXCH||a.PAACTEL_NUM||a.PAACTEL_EXT PAACTEL_TEL,a.PRI_ACPGN,a.PRI_ACPPN,a.CONFIRM_EXECUTED,
a.PCTYP1,a.PCTYP2,a.PCTYP3,a.PCTYP4,a.PCTYP5,a.SSN1,a.SSN2,a.SSN3,a.SSN4,a.SSN5,a.SSPCLOC1,a.SSPCLOC2,a.SSPCLOC3,a.SSPCLOC4,a.SSPCLOC5,
a.SSPCLOC6,a.TTN1,a.TTN2,a.TTN3,a.TTN4,a.TTN5,a.PCNA1,a.PCNA2,a.PCNA3,a.PCNA4,a.PCNA5,a.APC_NETID||a.APC_NETCLUS||a.APC_NODE APSNET,a.TSC2,a.TSC3,a.TSPC1_1||a.TSPC1_2||a.TSPC1_3 TSPC1,
a.TSPC2_1||a.TSPC2_2||a.TSPC2_3 TSPC2,a.TSPC3_1||a.TSPC3_2||a.TSPC3_3 TSPC3,a.TSPC4_1||a.TSPC4_2||a.TSPC4_3 TSPC4,a.TSPC5_1||a.TSPC5_2||a.TSPC5_3 TSPC5,
a.TSPCLOC1,a.TSPCLOC2,a.TSPCLOC3,a.TSPCLOC4,a.TSPCLOC5,a.SRN, a.MCLAG, a.MCLAG_ID,a.MCLAG_P, a.CI, 
---select 
b.ASR,b.ORD,b.ECCKT,b.ORD_CD,b.REFNUM,b.DD,b.CFA,b.SCFA,b.ESP,b.CRO,b.RORD,b.NHN_EXCH,b.NHN_NUM,b.NHNI,b.HBAN,b.FNIA,b.FNIZ,
b.TDM,b.TOTAL_INTVL,b.INV,b.DT_CKT_PROC,b.TM_CKT_PROC,b.DT_CKT_STAMP,b.TM_CKT_STAMP,b.CKR,b.IC_ECCKT,b.SCFAU,b.DIVPON,b.JKNUM,b.JKPOS,b.JS,
b.PSM,b.HML,b.STN_AREA||b.STN_EXCH||b.STN_NUM STN_TEL,b.TN_AREA||b.TN_EXCH||b.TN_NUM TN_TEL,
b.CAC_TSC,
b.TRK_TO,b.ASG,b.RAC,b.RRO,b.TGN,b.RTG,b.TRKQTY,b.TRFTYP,b.BHMQTY,b.TRFTYP2,b.BHMQTY2,b.LEGCKLT,b.SECLOC_I,b.SAL_IND,b.LD1,b.LD2,b.LD3,b.LEGSECNCI,b.LEGSECTLV_T,b.LEGSECTLV_R,b.LV1,b.LV2,b.LV3,b.SA_CITY,
b.CKT_S25,b.VCAT_IND_VC1||b.VCAT_IND_VC2||b.VCAT_IND_VC3 VCAT_IND,b.SAPR,b.SA_STATE,b.ACC,b.LEGACT,b.LEGS25,b.PI,b.AFT,b.LEGNC,b.LCON,b.AAI,b.SPOT,b.LEGSEG,
b.SANO,b.SASS,b.SATH,b.LEGOTC,b.SECLOC_SWC,b.SECLOC_LSO,b.ACTEL_AREA||b.ACTEL_EXCH||b.ACTEL_NUM||b.ACTEL_EXT ACTEL,b.LEG_REMARKS,b.SASF,b.NAC_PREPOP,                   b.TRID,b.CKTACT,b.ORD_JEP1_IND,b.ORD_ECD,b.TD2_ORD,b.CKT_EXR,b.LEG_EXR,b.CKT_SCFA,
b.LEG_GETO,b.IPAI,b.ES,b.PRILOC_CFAU,b.CFAU,b.CKT_TCIC1,b.CKT_TCIC2,b.CKT_TRN1,b.CKT_TRN2,b.FCKT,b.FORD,b.LEG_PRI_JKCD,b.LEG_PRI_JS,b.LEG_PRI_PCA,b.FASG,b.FORDCD,b.FORDCRD,
b.LEG_GCON,b.LEGGTEL_AREA||b.LEGGTEL_EXCH||b.LEGGTEL_NUM||b.LEGGTEL_EXT LEG_GTEL,b.WACD1,b.WACD2,b.RECCKT,b.GBTN_AREA||b.GBTN_EXCH||b.GBTN_NUM GBTN_TEL,b.SI,
b.WKTEL_AREA||b.WKTEL_EXCH||b.WKTEL_NUM WKTEL_TEL,b.CKR1,b.SEG_INCH,b.SEG_NCI,b.SEG_NMO,b.SEG_SEGACT,b.SEG_SR,b.SEG_NID,b.SEG_PRI_I||b.SEG_PRI_C SEG_PRI,b.ZIP,b.SEG_PRISPOT,b.CKT_CPT1,b.CKT_CPT2,b.SEG_PRI_PNO,
b.LEGSEC_PNO,b.TGN2,b.LEGSPEC,b.PRILOC_SMJK,b.SMJK,b.NAI_IND,b.CCEA,b.P_HBAN,b.PORTS,b.SEG_PORTS,b.ICFA1,b.ICFAU1,b.ICFA2,b.ICFAU2,b.ICFA3,b.ICFAU3,b.ICFA4,b.ICFAU4,b.DIR1,b.DIR2,b.DIR3,b.DIR4,b.DPEAA,b.DPEAZ,
b.VTIA_START||b.VTIA_END VTIA,b.VTIZ_START||b.VTIZ_END VTIZ,b.NK,b.SCCEA,b.DIR,b.SDIR,b.AACTEL_AREA||b.AACTEL_EXCH||b.AACTEL_NUM||b.AACTEL_EXT AACTEL,b.ACPGN,b.ACPPN,b.SASN,b.SA_EUNAME,b.SA_ADDRESS,b.SASD,b.LEGSPOT,b.ICOL,b.NCON,
b.ALCON,b.ALCON_AREA||b.ALCON_EXCH||b.ALCON_NUM||b.ALCON_EXT ALCON_TEL,b.ALCON_EMAIL,b.PQPR,b.QPR,b.P_EXP_PORT,b.EXP_PORT,b.P_PORT_CNT,b.PORT_CNT,
b.PORT_PAGES,b.IFNI1,b.IFNI2,b.IFNI3,b.IFNI4,b.CKT_TSP_CNTL,b.CKT_TSP_PRI,b.SUBNET_MASK,b.DIVCKT,b.IP_ADDRESS,b.PROFE,b.PROFI,                
b.JKCODE,b.CRO2,b.R_SECLOC_I||b.R_SECLOC_C,b.AALCON_AREA||b.AALCON_EXCH||b.AALCON_NUM||b.AALCON_EXT AALCON_TEL,b.AAI,
---select 
c.ASR,c.EVCNUM,c.EVCID,c.NUT,c.REMARKS_EVC,c.UREF_CNT,c.R_L_REQ,c.EVCORD_PROV,c.EVCID_PROV,c.EVC_ORD_CD,c.EVC_ORD_CRD,c.E_ACT_CDLRD,
c.EVC_ACT_DLRD,c.EVC_APP,c.EVC_DD,c.EVC_EBD,c.EVC_SID,c.EVC_LAM,
c.EVC_EIRD,c.EVC_DLRD,c.EVC_CDLRD,c.EVC_AD,c.EVC_RID,c.EVC_DVA,c.EVC_WOT,
c.EVC_FCD,c.EVC_PTD,c.EVC_CTA,c.EVC_IAD,c.EVC_TRID,c.EVC_CRO,c.EVC_CRO2,c.EVC_ASG,
c.EVCCKR,c.ECKTGEN_FLAG,c.EVC_NC,                    
---select     
d.ASR,d.PACEVLAN,d.VACT1,d.VACT2,d.VACT3,d.VACT4,d.VACT5,d.OTC_UNI,d.EI,d.EVP_IND,d.EVCMPID,d.SVACT1,d.SVACT2,d.SVACT3,d.LREF5,
d.UACT,d.RPON_UNI,d.NCI_UNI,d.AUNT,d.EVCSP,d.RUID,d.LREF1,d.LOSACT1,d.LOS1,d.SPEC1,d.PBIT1,d.BDW1,d.DSCP1,d.TOS1,d.LREF2,d.LOSACT2,d.LOS2,d.SPEC2,d.PBIT2,d.BDW2,d.DSCP2,d.TOS2,d.LREF3,d.LOSACT3,d.LOS3,d.SPEC3,d.PBIT3,d.BDW3,d.DSCP3,d.TOS3,d.ROOT_LEAF,
d.DSCP1_2,d.DSCP2_2,d.DSCP3_2,d.DSCP4_2,d.CEVLAN,d.CEVLAN_2, d.P_BITC_I4, d.P_BITC_E4,d.P_BITC_I3,d.P_BITC_E3,d.P_BITC_I2,d.P_BITC_E2,d.P_BITC_I1,d.P_BITC_E1,d.P_BITC_I5,d.P_BITC_E5
  from STAGING.VMA01EGS a
  left join  STAGING.vma02egs b --I changed this join from inner to left becuse the 02 table is missing records
  on a.asr = b.asr
  left join  staging.vma27egs c
  on a.asr = c.asr
  left join  staging.vma28egs d
  on a.asr = d.asr
where a.d_rec > '131231'---> (a.d_rec > '140101' and a.d_rec < '141231')
--a.d_rec > '141231'
AND (a.kstat)not in('K','D')
and a.pstat <> 'C'
and a.PON= 'HWS03483675'
and substr(a.NC,1,1)= 'K';