SELECT DOCUMENT_NUMBER, PON, ACT_IND, DREC, DD, DDD,  
         CASE WHEN DD_TASK_COMP IS NULL AND ACCEPT_DT > DREC THEN ACCEPT_DT
            WHEN ACCEPT_DT IS NULL THEN DD_TASK_COMP
            WHEN ACCEPT_DT <= DD_TASK_COMP AND ACCEPT_DT > DREC THEN ACCEPT_DT 
            ELSE DD_TASK_COMP END COMP_DT, 
         DD_TASK_COMP, NPA||NXX NPANXX, CLLIZ CLLI, ICSC, ACNA, CUSTOMER,                    
         CASE WHEN STATE1 IS NOT NULL THEN STATE1
              WHEN SEC_STATE IS NOT NULL THEN SEC_STATE
              WHEN PRI_STATE IS NOT NULL THEN PRI_STATE
              WHEN ICSC = 'FV01' THEN 'WV'
              WHEN ICSC = 'RT01' THEN 'NY'
              WHEN ICSC = 'SN01' THEN 'CT'
              WHEN SUBSTR(ICSC,1,2) = 'FV' AND SUBSTR(CKT,1,2) = '83' THEN 'ID'
              WHEN SUBSTR(ICSC,1,2) = 'FV' AND SUBSTR(CKT,1,2) = '85' THEN 'OR'
              WHEN SUBSTR(ICSC,1,2) = 'FV' AND SUBSTR(CKT,1,2) = '86' THEN 'WA'
              WHEN SUBSTR(ICSC,1,2) = 'FV' AND SUBSTR(CKT,1,2) = '30' THEN 'IL'
              WHEN SUBSTR(ICSC,1,2) = 'FV' AND SUBSTR(CKT,1,2) = '61' THEN 'NC'
              WHEN SUBSTR(ICSC,1,2) = 'FV' AND SUBSTR(CKT,1,2) = '62' THEN 'SC'
              WHEN SUBSTR(ICSC,1,2) = 'FV' AND SUBSTR(CKT,1,2) = '31' THEN 'IN'
              WHEN SUBSTR(ICSC,1,2) = 'FV' AND SUBSTR(CKT,1,2) = '33' THEN 'MI'
              WHEN SUBSTR(ICSC,1,2) = 'FV' AND SUBSTR(CKT,1,2) = '36' THEN 'OH'
              WHEN SUBSTR(ICSC,1,2) = 'FV' AND SUBSTR(CKT,1,2) = '39' THEN 'WI'
              WHEN ICSC IN ('GT10','GT11') AND SUBSTR(CKT,1,2) IN ('81','45') THEN 'CA'
              WHEN ICSC IN ('GT10','GT11') AND SUBSTR(CKT,1,2) IN ('69','65') THEN 'FL'
              WHEN ICSC IN ('GT10','GT11') AND SUBSTR(CKT,1,2) IN ('12','13') THEN 'TX'
              WHEN SUBSTR(PROJ,1,7) = 'ATTMOB-' THEN SUBSTR(PROJ,12,2)
              ELSE NULL END STATE, 
         CASE WHEN (SUBSTR(RATE_CODE,1,2) = 'OC' OR SUBSTR(NC,1,1) = 'O') THEN 'OCN'
              WHEN (NC = 'HC' OR SUBSTR(CKT,4,2) = 'HC') THEN 'DS1'
              WHEN (NC = 'HF' OR SUBSTR(CKT,4,2) = 'HF') THEN 'DS3'
              WHEN SUBSTR(CKT,7,2) = 'T1' THEN 'DS1'
              WHEN SUBSTR(CKT,7,2) = 'T3' THEN 'DS3'
              WHEN SUBSTR(NC,1,2) IN ('LX') THEN 'DS3'
              WHEN SUBSTR(NC,1,1) IN ('L','X') THEN 'DS0'
              WHEN SUBSTR(CKT,4,1) IN ('L','X') THEN 'DS0'
              WHEN SUBSTR(CKT,4,2) IN ('OS','FX','UC','UG','CL') THEN 'DS0'
              WHEN SUBSTR(CKT,4,2) IN ('YG','QG','DH','YB') THEN 'DS0'
              WHEN UNI_OR_NNI = '435' THEN 'ETHERNET-UNI'
              WHEN UNI_OR_NNI = '436' THEN 'ETHERNET-NNI'
              WHEN (SUBSTR(NC,1,2) IN ('KG','SN') OR SUBSTR(CKT,4,2) IN('KG','SX')) THEN 'ETHERNET-UNI'
              WHEN (SUBSTR(NC,1,2) IN ('KP','KD','KQ','KE') OR SUBSTR(CKT,4,2) IN ('KP','KD','KQ','KE')) THEN 'ETHERNET-UNI'
              WHEN SUBSTR(CKT,4,1) = 'V' THEN 'ETHERNET-EVC'
              WHEN (SUBSTR(NC,1,1) = 'K' OR SUBSTR(CKT,4,1) = 'K') THEN 'ETHERNET-UNI'
              ELSE 'CHECK' END PRODUCT,
         CKT
FROM
(
SELECT SR.PON,
  SR.DOCUMENT_NUMBER,
  ASR.REQUEST_TYPE,
  CASE WHEN NL1.CLLI_CODE IS NOT NULL THEN SUBSTR(NL1.CLLI_CODE,5,2)
       WHEN NL2.CLLI_CODE IS NOT NULL THEN SUBSTR(NL2.CLLI_CODE,5,2)
       ELSE NULL END STATE1,
  MAX(SR.ACTIVITY_IND) keep (dense_rank last order by sr.last_modified_date) ACT_IND,
  MAX(SR.SUPPLEMENT_TYPE) keep (dense_rank last order by sr.last_modified_date) SUPP_TYPE,
  MAX(ASR2.DATE_TIME_SENT) KEEP (DENSE_RANK LAST ORDER BY ASR2.LAST_MODIFIED_DATE) DREC, 
  MAX(ASR.DESIRED_DUE_DATE) KEEP (DENSE_RANK LAST ORDER BY ASR.LAST_MODIFIED_DATE) DD, 
  MAX(AUD.CRDD) KEEP (DENSE_RANK LAST ORDER BY AUD.LAST_MODIFIED_DATE) DDD, 
  MIN(AUD.ACCEPTANCE_DATE) KEEP (DENSE_RANK LAST ORDER BY AUD.LAST_MODIFIED_DATE) ACCEPT_DT, 
  MAX(TRUNC(ASAP.PKG_GMT.SF_GMT_AS_PASSED_TIMEZONE(T.ACTUAL_COMPLETION_DATE,1222))) keep (dense_rank last order by T.last_modified_date) DD_TASK_COMP,
  MAX(ASR.ACCESS_PROVIDER_SERV_CTR_CODE) keep (dense_rank last order by asr.last_modified_date) ICSC,
  MAX(SR.PROJECT_IDENTIFICATION) keep (dense_rank last order by sr.last_modified_date) PROJ,
  MAX(SR.ACNA) keep (dense_rank last order by sr.last_modified_date) ACNA,
  MAX(PRILOC_STATE) keep (dense_rank last order by dlr.last_modified_date) PRI_STATE,
  MAX(SECLOC_STATE) keep (dense_rank last order by dlr.last_modified_date) SEC_STATE,
  MAX(CIR.RATE_CODE) keep (dense_rank last order by cir.last_modified_date) RATE_CODE,
  MAX(ASR.NETWORK_CHANNEL_SERVICE_CODE) keep (dense_rank last order by asr.last_modified_date) NC,
  MAX(JEOPARDY_REASON_CODE) KEEP (DENSE_RANK LAST ORDER BY JEOP.LAST_MODIFIED_DATE) JEOP,
  CIR.EXCHANGE_CARRIER_CIRCUIT_ID CKT,
  MAX(ASR.NPA) KEEP (DENSE_RANK LAST ORDER BY ASR.LAST_MODIFIED_DATE) NPA,
  MAX(ASR.NXX) KEEP (DENSE_RANK LAST ORDER BY ASR.LAST_MODIFIED_DATE) NXX,
  MAX(SUBSTR(NL2.CLLI_CODE,1,6)) KEEP (DENSE_RANK LAST ORDER BY NL2.LAST_MODIFIED_DATE) CLLIZ,
  MAX(CUD.UNI_OR_NNI) KEEP (DENSE_RANK LAST ORDER BY CUD.LAST_MODIFIED_DATE) UNI_OR_NNI,
  ACCT.PRIMARY_CARRIER_NAME CUSTOMER 
--
FROM SERV_REQ SR, 
     ACCESS_SERVICE_REQUEST ASR,
     ACCESS_SERVICE_REQUEST ASR2,
     ASR_USER_DATA AUD,
     NETWORK_LOCATION NL1,
     NETWORK_LOCATION NL2,
     CIRCUIT CIR,
     DESIGN_LAYOUT_REPORT DLR, 
     TASK T,
     TASK_JEOPARDY_WHYMISS JEOP,
     ASAP.SERVICE_REQUEST_CIRCUIT SRC,
     CIRCUIT_USER_DATA CUD,
     ASR_OM.ASR_ACCOUNT_MANAGER ACCT
--
WHERE SR.DOCUMENT_NUMBER = ASR.DOCUMENT_NUMBER(+)
AND SR.DOCUMENT_NUMBER = ASR2.DOCUMENT_NUMBER(+)
AND SR.DOCUMENT_NUMBER = SRC.DOCUMENT_NUMBER (+)
AND SR.DOCUMENT_NUMBER = AUD.DOCUMENT_NUMBER (+)
AND SRC.CIRCUIT_DESIGN_ID = CIR.CIRCUIT_DESIGN_ID (+)
AND CIR.LOCATION_ID = NL1.LOCATION_ID (+)
AND CIR.LOCATION_ID_2 = NL2.LOCATION_ID (+)
AND SR.DOCUMENT_NUMBER = DLR.DOCUMENT_NUMBER (+)
AND SR.DOCUMENT_NUMBER = T.DOCUMENT_NUMBER (+)
AND T.TASK_NUMBER = JEOP.TASK_NUMBER(+)
AND CIR.CIRCUIT_DESIGN_ID = CUD.CIRCUIT_DESIGN_ID (+)
AND SR.ACNA = ACCT.SECONDARY_ID (+)
AND SR.TYPE_OF_SR = 'ASR'
AND T.TASK_TYPE = 'DD'
AND ASR.REQUEST_TYPE IN ('S','E')
AND ASR.ACTIVITY_INDICATOR IN ('N','C')
AND JEOP.JEOPARDY_TYPE_CD(+) = 'W' 
AND SR.DOCUMENT_NUMBER > '1000000' 
AND TO_CHAR(T.ACTUAL_COMPLETION_DATE,'YYYYMM') = ('202312')   
--
GROUP BY SR.DOCUMENT_NUMBER,
  SR.PON,
  SR.TYPE_OF_SR, 
  ASR.REQUEST_TYPE, 
  CIR.EXCHANGE_CARRIER_CIRCUIT_ID,
  NL1.CLLI_CODE,
  NL2.CLLI_CODE,
  ACCT.PRIMARY_CARRIER_NAME 
)
--
WHERE (SUPP_TYPE <> '1' OR SUPP_TYPE IS NULL)
 AND SUBSTR(CKT,7,1) <> 'U'
 AND (NC NOT IN ('TD') OR NC IS NULL)
 AND (acna not in ('FLR','ZTK','BLI','BNK','CMW','COY','CQV','CUS','CZE','CZJ','CZN','CZX','EPX','ERR','EXC','FBA','FCA','FIS',
                   'FLX','GOP','GTO','GVN','IZH','NNR','OGD','RGD','ROU','T05','VAC','VZN','WDK','ZAP','ZWV','ZZZ','XYY') or acna is null);
