--FOR NCFR DETAIL - NUMERATOR   

SELECT DOCUMENT_NUMBER, PON, ACT_IND, COMP_DT, DD_TASK_COMP, NPANXX, CLLI, ICSC, ACNA, CUSTOMER,
 REGION, TERRITORY, DIRECTOR, STATE, PRODUCT, CKT, 
 MIN(TICKET_ID) TICKET_ID, 
 MIN(ASSIGNMENTPROFILE) KEEP (DENSE_RANK FIRST ORDER BY TICKET_ID) ASSIGNMENTPROFILE,
 MIN(REPAIR_CODE) KEEP (DENSE_RANK FIRST ORDER BY TICKET_ID) REPAIR_CODE, 
 MIN(DISP) KEEP (DENSE_RANK FIRST ORDER BY TICKET_ID) DISP,
 MIN(TRBL_CREATE_DATE) KEEP (DENSE_RANK FIRST ORDER BY TICKET_ID) TRBL_CREATE_DATE,
 MIN(TRBL_CLEARED_DT) KEEP (DENSE_RANK FIRST ORDER BY TICKET_ID) TRBL_CLEARED_DT,
 MIN(TRBL_CLOSED_DT) KEEP (DENSE_RANK FIRST ORDER BY TICKET_ID) TRBL_CLOSED_DT,
 CASE WHEN MON = 12 THEN 1 ELSE MON+1 END MON                                               --USE PLUS 1 TO ACCOMODATE THE SPREADSHEET WITH THIS ONE MONTH IN ARREARS              
 FROM (
    SELECT DISTINCT DOCUMENT_NUMBER, PON, ACT_IND, COMP_DT, DD_TASK_COMP, NPANXX, CLLI, ICSC, ACNA, CUSTOMER,
    REGION, TERRITORY, DIRECTOR, STATE, PRODUCT, CKT, TICKET_ID, ASSIGNMENTPROFILE, REPAIR_CODE, TFR.DISP, TO_CHAR(DD_TASK_COMP,'MM') MON,  
    TRBL_CREATE_DATE, TRBL_CLEARED_DT, 
    CASE WHEN CLOSED_DT IS NOT NULL THEN CLOSED_DT
         ELSE TRBL_CLEARED_DT END TRBL_CLOSED_DT
    FROM (
        SELECT DISTINCT DOCUMENT_NUMBER, PON, ACT_IND, COMP_DT, DD_TASK_COMP, NPANXX, CLLI, ICSC, A.ACNA, CUSTOMER,
        REGION, TERRITORY, DIRECTOR, STATE, PRODUCT, CKT,
        TT.FLD_REQUESTID TICKET_ID,
        MAX(TT.FLD_COMPLETE_REPAIRCODE) KEEP (DENSE_RANK LAST ORDER BY TT.FLD_MODIFIEDDATE) REPAIR_CODE,
        MAX(TRIM(TT.FLD_ASSIGNMENTPROFILE)) KEEP (DENSE_RANK FIRST ORDER BY TT.FLD_MODIFIEDDATE) ASSIGNMENTPROFILE, 
        MAX(TT.FLD_REQUESTSTATUS) KEEP (DENSE_RANK LAST ORDER BY TT.FLD_MODIFIEDDATE) REQSTAT,
        MAX(TT.FLD_REQUESTTYPE) KEEP (DENSE_RANK LAST ORDER BY TT.FLD_MODIFIEDDATE) REQUEST_TYPE,
        MAX(TT.FLD_STARTDATE) KEEP (DENSE_RANK LAST ORDER BY TT.FLD_MODIFIEDDATE) TRBL_CREATE_DATE,
        MAX(TT.FLD_EVENT_END_TIME) KEEP (DENSE_RANK LAST ORDER BY TT.FLD_MODIFIEDDATE) TRBL_CLEARED_DT, 
        MAX(TT.DTE_CLOSEDDATETIME) KEEP (DENSE_RANK LAST ORDER BY TT.FLD_MODIFIEDDATE) CLOSED_DT,
        MAX(TT.FLD_MODIFIEDDATE) MOD_DATE
        FROM ( 
            SELECT DOCUMENT_NUMBER, PON, ACT_IND, DREC, DD, DDD, COMP_DT, DD_TASK_COMP, 
            NCFR.NPANXX, NCFR.CLLI, ICSC, NCFR.ACNA, CUSTOMER, PRODUCT, CKT, 
            CASE WHEN DIRN.AREA IS NOT NULL THEN DIRN.AREA ELSE DIRC.AREA END REGION,
            CASE WHEN DIRN.TERRITORY IS NOT NULL THEN DIRN.TERRITORY ELSE DIRC.TERRITORY END TERRITORY,
            CASE WHEN DIRN.DIRECTOR IS NOT NULL THEN DIRN.DIRECTOR ELSE DIRC.DIRECTOR END DIRECTOR,
            CASE WHEN DIRN.STATE IS NOT NULL THEN DIRN.STATE
            WHEN DIRC.STATE IS NOT NULL THEN DIRC.STATE ELSE NCFR.STATE END STATE
            FROM rvv827.NCFRORDERS NCFR, 
                 rvv827.DIRECTOR_NPANXX_4 DIRN,
                 rvv827.DIRECTOR_CLLI_4 DIRC
            WHERE NCFR.NPANXX = DIRN.NPANXX (+)
            AND NCFR.CLLI = DIRC.CLLI (+) 
            AND ACT_IND = 'N'
            AND TO_CHAR(DD_TASK_COMP,'YYYYMM') = '202304' --ONE MONTH IN ARREARS FROM REPORTING MONTH - MAKE SURE TO CHANGE EVERY MONTH   
            AND NCFR.STATE NOT IN ('WA','OR','ID','MT')  
        )A, CASDW.TROUBLE_TICKET_R TT
     WHERE A.CKT = TT.EXCHANGE_CARRIER_CIRCUIT_ID
     AND TT.FLD_TROUBLEREPORTSTATE = 'closed'
     AND TT.FLD_ASSIGNMENTPROFILE IN ('CNOC','Commercial-CTF')
     AND TO_CHAR(FLD_STARTDATE,'yyyymm') IN ('202304','202305')  --MUST CHANGE THESE DATES EACH MONTH TO SHOW PREVIOUS AND CURRENT MONTH  
     AND TO_CHAR(TT.FLD_STARTDATE,'YYYYMMDD') >= TO_CHAR(A.COMP_DT,'YYYYMMDD') 
     GROUP BY DOCUMENT_NUMBER, PON, ACT_IND, COMP_DT, DD_TASK_COMP, NPANXX, CLLI, ICSC, A.ACNA, CUSTOMER, 
              REGION, TERRITORY, DIRECTOR, STATE, PRODUCT, CKT, TT.FLD_REQUESTID
   )B, rvv827.TRBL_FOUND_REMEDY TFR           
   WHERE B.REPAIR_CODE = TFR.TRBL_FOUND_DESC (+)  
   AND REQUEST_TYPE IN ('Agent','Alarm','Customer','Maintenance')
   AND TFR.DISP IN ('CO','FAC')           
)
WHERE TRBL_CREATE_DATE - COMP_DT <31
AND TO_CHAR(TRBL_CREATE_DATE,'YYYYMMDD') >= TO_CHAR(COMP_DT,'YYYYMMDD')
and document_number not in ('2926777')
GROUP BY DOCUMENT_NUMBER, PON, ACT_IND, COMP_DT, DD_TASK_COMP, NPANXX, CLLI, ICSC, ACNA, CUSTOMER, 
         REGION, TERRITORY, DIRECTOR, STATE, PRODUCT, CKT, MON
ORDER BY 11,12,13,16;
         
    
 
 
--FOR NCFR DENOMINATOR  
          
SELECT REGION, TERRITORY, DIRECTOR, PRODUCT, COUNT(*), 
       CASE WHEN MON = 12 THEN 1 ELSE MON+1 END MON  --USE PLUS 1 TO ACCOMODATE THE SPREADSHEET WITH THIS ONE MONTH IN ARREARS  
FROM (           
            SELECT DOCUMENT_NUMBER, DD_TASK_COMP, NCFR.NPANXX, NCFR.CLLI, ACNA, CUSTOMER, 
            CASE WHEN SUBSTR(PRODUCT,1,8) = 'ETHERNET' THEN 'ETHERNET' ELSE PRODUCT END PRODUCT, CKT, 
            CASE WHEN DIRN.AREA IS NOT NULL THEN DIRN.AREA ELSE DIRC.AREA END REGION,
            CASE WHEN DIRN.TERRITORY IS NOT NULL THEN DIRN.TERRITORY ELSE DIRC.TERRITORY END TERRITORY,
            CASE WHEN DIRN.DIRECTOR IS NOT NULL THEN DIRN.DIRECTOR ELSE DIRC.DIRECTOR END DIRECTOR,
            TO_CHAR(DD_TASK_COMP,'mm') MON,
            TO_CHAR(DD_TASK_COMP,'yyyymm') dd_task
            FROM rvv827.NCFRORDERS NCFR, 
                 rvv827.DIRECTOR_NPANXX_4 DIRN,
                 rvv827.DIRECTOR_CLLI_4 DIRC
            WHERE NCFR.NPANXX = DIRN.NPANXX (+)
            AND NCFR.CLLI = DIRC.CLLI (+) 
            AND ACT_IND = 'N'
  ) WHERE DD_TASK = '202304'                     --CHANGE THIS EACH MONTH  - SHOULD SHOW PREVIOUS MONTH     
  GROUP BY REGION, TERRITORY, DIRECTOR, PRODUCT, MON
  ORDER BY 1,2,3;          
  
  
