SELECT DISTINCT DOCNO, STATE, REGION,  CLEC_ID, 
	   CASE WHEN CLEC_ID IN ('ATX','TPM','AAV','SBB','SBZ','SUV') THEN 'ATT COMMUNICATIONS'
	        WHEN CLEC_ID IN ('AAX','ACF','ACH','ADM','AEC','AGS','AGZ','AHA','AHD','AHM','AHO',
	   		      'AIL','AIN','AIS','AKZ','ALY','AMH','AMP','AWL','AWN','AZE','BAC','BAK','BAO','BCU','BFL','BGH','BPN',
				  'BSM','CBL','CCB','CDA','CEO','CEU','CFN','CIV','CIW','CKQ','CLQ','COW','CQW','CRF','CRJ','CSG','CSO',
			      'CSU','CSX','CTJ','CUO','CUY','CZB','DNC','ETP','EST','ETX','FLA','FSC','FSI','FSV','GEE','GLV','GSL',
				  'HGN','HLU','HNC','HTN','IMP','IND','ISZ','IUW','JCT','LAA','LAC','LBH','LNZ','LSZ','MBN','MBQ','MCA',
			      'MCC','MCE','MCQ','MCV','MCW','MCZ','MFN','MIB','MIR','MLA','MLZ','MMV','MOB','MOE','MTX','MUI','MWB',
				  'MWZ','NBC','NWW','OAK','OCL','ORV','OSU','OCK','PFM','PIG','RAD','RMC','RMF','RRC','SBG','SBM','SBN',
				  'SCU','SHI','SLL','SMC','SNP','STH','SUF','SWM','SWP','SWT','SWV','SYC','SZM','TGH','TQU','UMT','VGD',
				  'VRA','WBT','WGL','WLG','WLZ','WVO','WWC') THEN 'ATT MOBILITY'
			WHEN CLEC_ID IN ('MCI','WTL','MPL','FED','LNT','WUA','MFZ','ICF','BFC','UUN') THEN 'VERIZON BUSINESS'
			WHEN CLEC_ID IN ('EBA','CCQ','DTC','GMT','CUM','UNV','PPM','BAM','FCS','DUG','CCE','NVC','PUL','RMB') THEN 'VERIZON WIRELESS'
			WHEN CLEC_ID IN ('UTC') THEN 'SPRINT'
			WHEN CLEC_ID IN ('MJC','SZC','NLZ','NXT','UBQ','IGW','WSO','CXJ') THEN 'SPRINT PCS'
			WHEN CLEC_ID IN ('LGT','LTL','DTI') THEN 'CENTURYLINK-QWEST'
			WHEN CLEC_ID IN ('LVC','ALN','WCA','IMR','ICG','FOC','SSM','SCH','HTJ') THEN 'LEVEL 3'
			WHEN CLEC_ID IN ('FET','FWN') THEN 'LUMOS'
			WHEN CLEC_ID IN ('IOR','UHC','PUA') THEN 'PAETEC'
			WHEN CLEC_ID IN ('WCG','OPT','ABW','TZV','PWR') THEN 'TMOBILE'
			WHEN CLEC_ID IN ('TQW','AFY') THEN 'XO COMMUNICATIONS'
			WHEN CLEC_ID IN ('CUS','ZZZ') THEN 'END USER'
		ELSE PARTY_NAME END CARRIER, 
		PREMISE_NAME, CKT_ID, PRODUCT, TICKET_ID, CREATE_DT, CLEARED_DT, CLOSE_DT, TOTAL_DURATION TOT_DUR, TTR,
		TRBL_ID, TRBL_DESC, CLLI_CODE, DISPOSITION, SERV_CODE, SUBSTR(CLOSE_DT,7,4)||SUBSTR(CLOSE_DT,1,2) MONTH,
		CASE WHEN DISPOSITION IN ('CPE','REF','EXC') THEN 'NO' ELSE 'YES' END COUNT_IN_MTTR
FROM (
SELECT 
 CASE WHEN STATE IN ('IL','MO','MN','ND','OH') THEN 'Central'
      WHEN STATE IN ('IN','KY','MI') THEN 'Midwest'
	  WHEN STATE IN ('NC','SC','WV','MD','VA') THEN 'Southeast'
	  WHEN STATE IN ('CA','OR','WA') THEN 'West'
	  WHEN STATE IN ('NY','PA') THEN 'Northeast'
	  WHEN STATE IN ('AL','AZ','FL','GA','IA','ID','MS','MT','NE','NM','NV','TN','UT','WI') THEN 'National'
	  ELSE 'Unknown' END REGION, 
      STATE, 
       CASE WHEN PRODUCT_LEVEL IN ('DS0','DS1','DS3') THEN PRODUCT_LEVEL
	        WHEN SUBSTR(SERV_CODE,1,1) IN ('K','V') THEN 'Ethernet'
			WHEN CKT LIKE '%GIG%' THEN 'Ethernet'
			WHEN SUBSTR(SERV_CODE,1,1) = 'O' THEN 'OCN'
			WHEN CKT_ID LIKE '%/OC%' THEN 'OCN'
			WHEN SUBSTR(SERV_CODE,1,1) IN ('L','X') THEN 'DS0'
			WHEN SERV_CODE = 'HC' THEN 'DS1'
			WHEN CKT_ID LIKE '%/T1%' THEN 'DS1'
			WHEN SERV_CODE = 'HF' THEN 'DS3'
			WHEN CKT_ID LIKE '%/T3%' THEN 'DS3'
			WHEN SUBSTR(CKT,3,2) = 'HC' THEN 'DS1'
			WHEN SUBSTR(SERV_CODE,1,2) IN ('DI','ST','ID','CS','OS','FD') THEN 'DS0'
			ELSE PRODUCT_LEVEL END PRODUCT,
	   DOCUMENT_NUMBER DOCNO, CREATE_DT, CLEARED_DT, CLOSE_DT, TT_TYPE, CURRENT_STATE, TICKET_ID,
       CKT_ID, CLLI_CODE, SERV_ITEM_TYPE_CD, CUSTOMER_TICKET_ID, 
       CASE WHEN ACNA IS NOT NULL THEN ACNA
	        WHEN CCNA IS NOT NULL THEN CCNA
			ELSE USER_DATA_ACNA END CLEC_ID, 
	   SERV_CODE, TRBL_DESC, TRBL_ID, DISPOSITION, TTR, TOTAL_DURATION, PREMISE_NAME
FROM (
SELECT MAX(C.RATE_CODE) KEEP (DENSE_RANK LAST ORDER BY C.LAST_MODIFIED_DATE) AS PRODUCT_LEVEL,
 CASE WHEN NL1.CLLI_CODE IS NOT NULL THEN SUBSTR(NL1.CLLI_CODE,5,2)
      WHEN NL2.CLLI_CODE IS NOT NULL THEN SUBSTR(NL2.CLLI_CODE,5,2)
	  WHEN TT.OFFICE_CLLI_CD IS NOT NULL THEN SUBSTR(TT.OFFICE_CLLI_CD,5,2)
	  ELSE NULL END STATE,
 TT.DOCUMENT_NUMBER, 
 TT.CREATE_DATE CREATE_DT,
 TO_CHAR(ASAP.PKG_GMT.SF_GMT_AS_PASSED_TIMEZONE(TT.CLEARED_DT,'1222'),'MM/DD/YYYY HH:MI:SS AM') AS CLEARED_DT, -- GMT CONVERTED  
 TO_CHAR(ASAP.PKG_GMT.SF_GMT_AS_PASSED_TIMEZONE(TT.CLOSE_DT,'1222'),'MM/DD/YYYY HH:MI:SS AM') AS CLOSE_DT, --GMT CONVERTED  
 TT.TT_TYPE_CD AS TT_TYPE,
 TT.CURRENT_STATE AS CURRENT_STATE,
 TO_CHAR(TT.TICKET_ID) TICKET_ID,
 TT.SERV_ITEM_DESC CKT_ID,
 REPLACE(REPLACE(TT.SERV_ITEM_DESC,' '),'/') CKT, 
 TT.OFFICE_CLLI_CD CLLI_CODE,
 TT.SERV_ITEM_TYPE_CD, 
 TT.CUSTOMER_TICKET_ID,
 D.ACNA USER_DATA_ACNA,
 MAX(DLR.ACNA) KEEP (DENSE_RANK LAST ORDER BY DLR.LAST_MODIFIED_DATE) ACNA,
 MAX(DLR.CCNA) KEEP (DENSE_RANK LAST ORDER BY DLR.LAST_MODIFIED_DATE) CCNA,
 MAX(C.SERVICE_TYPE_CODE) KEEP (DENSE_RANK LAST ORDER BY C.LAST_MODIFIED_DATE) SERV_CODE,
 D.CUSTOMER_PREMISE_NAME PREMISE_NAME,
 TFT.TROUBLE_FOUND_CD TRBL_DESC,
 TT.TRBL_FOUND_ID TRBL_ID,
 CASE WHEN TT.TRBL_FOUND_ID IN ('253','261','263','266','267','268') THEN 'NTF'  
      WHEN TT.TRBL_FOUND_ID IN ('241') THEN 'CC'  
	  WHEN TT.TRBL_FOUND_ID IN ('242','243','276','289','290','291') THEN 'CO'  
	  WHEN TT.TRBL_FOUND_ID IN ('245','246','247','254','255','256','257','258','259','260',
	                            '284','285','286','287','288','297','300') THEN 'FAC'  
	  WHEN TT.TRBL_FOUND_ID IN ('244','265','271','292','293','294','296') THEN 'CPE'
	  WHEN TT.TRBL_FOUND_ID IN ('248','277','295','299') THEN 'REF'
	  ELSE 'EXC' END DISPOSITION,
 ROUND((TTR/3600),2) TTR,
 ROUND((TOT_DUR/3600),2) TOTAL_DURATION
 --
 FROM TROUBLE_USER_DATA D,
 CIRCUIT C,
 DESIGN_LAYOUT_REPORT DLR,
 NETWORK_LOCATION NL1,
 NETWORK_LOCATION NL2,
 TROUBLE_FOUND_TYPE TFT,
 TROUBLE_TICKET TT
 WHERE TT.DOCUMENT_NUMBER = D.DOCUMENT_NUMBER(+)
 AND TT.SERV_ITEM_DESC = C.EXCHANGE_CARRIER_CIRCUIT_ID(+)
 AND C.CIRCUIT_DESIGN_ID = DLR.CIRCUIT_DESIGN_ID
 AND C.LOCATION_ID = NL1.LOCATION_ID(+)
 AND C.LOCATION_ID_2 = NL2.LOCATION_ID(+)
 AND TT.TRBL_FOUND_ID = TFT.TRBL_FOUND_ID (+)
 AND TT.CURRENT_STATE = 'closed'
 AND (TO_CHAR(ASAP.PKG_GMT.SF_GMT_AS_PASSED_TIMEZONE(TT.CLOSE_DT,'1222'),'yyyymm') = substr((TO_CHAR(SYSDATE-9,'YYYYMMDD')),1,6)
   OR TO_CHAR(ASAP.PKG_GMT.SF_GMT_AS_PASSED_TIMEZONE(TT.CLOSE_DT,'1222'),'yyyymm') = TO_CHAR(SYSDATE,'YYYYMM'))
 AND RESP_ORG_PARTY_ID IN ('518336','540992','541368')
 AND TT.SERV_ITEM_TYPE_CD = 'CIRCUIT'
 AND SUBSTR(TT.SERV_ITEM_DESC,7,1) <> 'U'
 AND TT.TT_TYPE_CD = 'CUSTOMER'
 AND DLR.ISSUE_STATUS = '2'
 AND (C.TYPE <> 'T' OR TYPE IS NULL)
 --
 GROUP BY NL1.CLLI_CODE, NL2.CLLI_CODE, TT.DOCUMENT_NUMBER, TT.CREATE_DATE, TT.CLEARED_DT, TT.CLOSE_DT,   
 TT.TT_TYPE_CD, TT.CURRENT_STATE, TT.TICKET_ID, TT.SERV_ITEM_DESC, TT.OFFICE_CLLI_CD, TT.SERV_ITEM_TYPE_CD, 
 TT.CUSTOMER_TICKET_ID, D.ACNA, TFT.TROUBLE_FOUND_CD, TT.TRBL_FOUND_ID, TTR, TOT_DUR, CUSTOMER_PREMISE_NAME
 )) Z, access_cust ac, party p
 where z.clec_id = ac.customer_name_abbreviation (+)
   and ac.PARTY_ID = p.PARTY_ID (+)
   and (CLEC_ID <> 'ZTK' OR CLEC_ID IS NULL)
   ORDER BY REGION, STATE, CLOSE_DT DESC