SELECT DISTINCT TYPE, PON, DOCNO, ACNA, ACT_IND, CKT, D_REC, DD, CRDD, 
       CASE WHEN STATE IS NOT NULL THEN STATE ELSE NPASTATE END STATE,
       NC, NC_OPT, NCI, SECNCI, ACTL, SPEC, VTA, PNUM, TASK_AT_READY, TASK_AT_JEOP, JEOP_CODE, JEOP_DESC,
       INIT, INIT_TEL_NO, INIT_EMAIL, DSGCON, DSG_TEL_NO, LCON, LCON_EMAIL, ACTEL 
FROM (
SELECT PON, DOCUMENT_NUMBER DOCNO, ACNA, ACT_IND, CKT, D_REC, DD, CRDD, ICSC,     
       PROJ, RATE_CODE, NC, NC_OPT, EUNAME, NCI, SECNCI, STATE, SUBSTR(NPA.EXCHANGE_AREA_CLLI,5,2) NPASTATE,
       SPEC, PNUM, VTA, ACTL, INIT, INIT_TEL_NO, INIT_EMAIL,
       DSGCON, DSG_TEL_NO, LCON, LCON_EMAIL, ACTEL, CNO, TASK_AT_READY, TASK_AT_JEOP, JEOP_CODE, JT.JEOPARDY_REASON_DESCRIPTION JEOP_DESC,
       CASE WHEN SPEC = 'EPATHCP' AND NC = 'SN' THEN 'E-PATH NNI CORE POP'
            WHEN SPEC = 'EPATHN' AND SUBSTR(NCI,3,1) = 'Q' AND SUBSTR(ACTL,1,8) NOT IN (
            'BLTNCAAD','ELSGCA12','BRBNCA11','CLCYCA11','HLWDCA01','NHWDCA02','LSANCARC','SNPDCA01','LSANCA12',
            'GLDLCA11','CNPKCA01','LSANCA01','BRBNCA13','IRVNCA11','LSANCA06','LSANCA07','LSANCA09','WLMGCA01',
            'TUSTCA11','RVSDCA01','COTNCA11','FNTACA11','SNLOCA01','DLLSTX37','DLLSTXRN','DLLSTXRI','DLLSTXTL',
            'DLLSTXTA','DLLSTXNO','DLLSTXME','FTWOTXED','RONKTXWO','DLLSTXRO','HSTNTXAD','HSTNTXCA','FRSCTXES',
            'DLLSTX97','LSANCAVJ','STTLWAWB','MPLSMNGT','MPLSMNCD','ENWDCOUH','MIASFLTT','NYCMNY83','PLALCA01',
            'LSANCA89','BHLHPAEA','HVTPPABJ','BMBGPAEZ','BMBGPAGH','SUTSPA01','CPHLPAES','HRBGPA29','LMYNPAAY',
            'SRDLPAAC','SRDLPAAE','HZTNPACH','HZTNPADI','HZTNPAED','HZTNPAHY','HZTNPAIU','EWVLPABI','FRFTPAAB',
            'KGTNPAAA','KGTNPAAK','KGTNPADT','KGTNPAEO','EHMTPA26','LNCSPAKN','LNCSPAOX','LNCSPAPH','LNCSPAUG',
            'LBNNPALH','NNTCPAAD','NNTCPABL','NNTCPABM','BEWKPA19','DAVLPABQ','DAVLPAGH','LKHRPAAD','LKHRPAAE',
            'LKHRPAAF','LKHRPAAG','LKHRPAAH','LKHRPAAI','LKHRPAAJ','LKHRPAAK','LKHRPAAL','LKHRPAAM','LKHRPAAN',
            'LKHRPAAO','LKHRPAAP','LKHRPAAQ','LKHRPAAR','LKHRPAAS','LKHRPAAT','LKHRPAAU','LKHRPAAV','LKHRPAAW',
            'LKHRPAAX','LKHRPAAY','LKHRPAAZ','PLNSPAAR','PLNSPAEF','WLBPPABI','WLBPPABJ','WLBRPAKJ','WLBRPAMY',
            'WLBRPANC','WLBRPAPB','WLBRPAPS','WLBSPADA','WLBSPADC','LRKVPAAG','LRKVPAAH','PLTSPAAA','PLMGPAAX',
            'MHBGPAAC','MHTSPAAC','MHTSPAEE','WRDNPABW','DNMRPA24','DNMRPACX','JSSPPA04','SCTNPA13','SCTNPADA',
            'SCTNPAEO','SCTNPAER','SCTNPAIA','SCTNPAPL','SCTNPASC','SCTNPAUE','SCTNPAVH','WPTNPAAX','HRTPPAAN',
            'PLNSPADT','WLBPPAAV','WLBPPABC','WLBRPA15','WLBRPAAK','WLBRPAAV','WLBRPABO','WLBRPAFD','WLBRPAFM',
            'WLBRPAHV','WLBRPAIK','WLBRPAIZ','WLBRPAKN','WLBRPAMI','WLBRPAMP','WLBRPAMS','WLBRPANG','WLBRPANH',
            'WLBRPAOS','WLBRPAWB','WLBRPAXA','WLBSPACC','WLBSPACE','WLBSPACF','WLBSPACG','WLBSPACH','WLBSPACK',
            'WLBOPACJ','WLPTPA46','WLPTPAPC','EXTLPA03','WPTNPAAW','WWYMPAAA','EMGVPAAO','GRNLPA02','WMCTPAAW',
            'YORKPAFE','YORKPAKB','YORKPALQ','YORKPAYK','YORKPAZB','YORKPAZD','YORLPAKJ','YORLPAMK','YORLPAUH',
            'HRBGPAHA'
            ) THEN 'E-PATH NNI COLO'
            WHEN SPEC = 'EPATHN' AND SUBSTR(NC,1,2) IN ('KF','KR','KG','KS','KJ','KU') AND SUBSTR(NCI,3,1) <> 'Q' THEN 'E-PATH NNI CARRIER POP'
            WHEN SPEC = 'EPATHN' AND (NC = 'SN' OR SUBSTR(NC,1,1) = 'K') AND SUBSTR(ACTL,1,8) IN (
            'BLTNCAAD','ELSGCA12','BRBNCA11','CLCYCA11','HLWDCA01','NHWDCA02','LSANCARC','SNPDCA01','LSANCA12',
            'GLDLCA11','CNPKCA01','LSANCA01','BRBNCA13','IRVNCA11','LSANCA06','LSANCA07','LSANCA09','WLMGCA01',
            'TUSTCA11','RVSDCA01','COTNCA11','FNTACA11','SNLOCA01','DLLSTX37','DLLSTXRN','DLLSTXRI','DLLSTXTL',
            'DLLSTXTA','DLLSTXNO','DLLSTXME','FTWOTXED','RONKTXWO','DLLSTXRO','HSTNTXAD','HSTNTXCA','FRSCTXES',
            'DLLSTX97','LSANCAVJ','STTLWAWB','MPLSMNGT','MPLSMNCD','ENWDCOUH','MIASFLTT','NYCMNY83','PLALCA01',
            'LSANCA89','BHLHPAEA','HVTPPABJ','BMBGPAEZ','BMBGPAGH','SUTSPA01','CPHLPAES','HRBGPA29','LMYNPAAY',
            'SRDLPAAC','SRDLPAAE','HZTNPACH','HZTNPADI','HZTNPAED','HZTNPAHY','HZTNPAIU','EWVLPABI','FRFTPAAB',
            'KGTNPAAA','KGTNPAAK','KGTNPADT','KGTNPAEO','EHMTPA26','LNCSPAKN','LNCSPAOX','LNCSPAPH','LNCSPAUG',
            'LBNNPALH','NNTCPAAD','NNTCPABL','NNTCPABM','BEWKPA19','DAVLPABQ','DAVLPAGH','LKHRPAAD','LKHRPAAE',
            'LKHRPAAF','LKHRPAAG','LKHRPAAH','LKHRPAAI','LKHRPAAJ','LKHRPAAK','LKHRPAAL','LKHRPAAM','LKHRPAAN',
            'LKHRPAAO','LKHRPAAP','LKHRPAAQ','LKHRPAAR','LKHRPAAS','LKHRPAAT','LKHRPAAU','LKHRPAAV','LKHRPAAW',
            'LKHRPAAX','LKHRPAAY','LKHRPAAZ','PLNSPAAR','PLNSPAEF','WLBPPABI','WLBPPABJ','WLBRPAKJ','WLBRPAMY',
            'WLBRPANC','WLBRPAPB','WLBRPAPS','WLBSPADA','WLBSPADC','LRKVPAAG','LRKVPAAH','PLTSPAAA','PLMGPAAX',
            'MHBGPAAC','MHTSPAAC','MHTSPAEE','WRDNPABW','DNMRPA24','DNMRPACX','JSSPPA04','SCTNPA13','SCTNPADA',
            'SCTNPAEO','SCTNPAER','SCTNPAIA','SCTNPAPL','SCTNPASC','SCTNPAUE','SCTNPAVH','WPTNPAAX','HRTPPAAN',
            'PLNSPADT','WLBPPAAV','WLBPPABC','WLBRPA15','WLBRPAAK','WLBRPAAV','WLBRPABO','WLBRPAFD','WLBRPAFM',
            'WLBRPAHV','WLBRPAIK','WLBRPAIZ','WLBRPAKN','WLBRPAMI','WLBRPAMP','WLBRPAMS','WLBRPANG','WLBRPANH',
            'WLBRPAOS','WLBRPAWB','WLBRPAXA','WLBSPACC','WLBSPACE','WLBSPACF','WLBSPACG','WLBSPACH','WLBSPACK',
            'WLBOPACJ','WLPTPA46','WLPTPAPC','EXTLPA03','WPTNPAAW','WWYMPAAA','EMGVPAAO','GRNLPA02','WMCTPAAW',
            'YORKPAFE','YORKPAKB','YORKPALQ','YORKPAYK','YORKPAZB','YORKPAZD','YORLPAKJ','YORLPAMK','YORLPAUH',
            'HRBGPAHA'
            ) THEN 'E-PATH NNI CARRIER HOTEL'
            ELSE 'EXCLUDE' END TYPE
FROM
(
SELECT SR.PON,
  SR.DOCUMENT_NUMBER,    
  MAX(SR.ACTIVITY_IND) KEEP (DENSE_RANK LAST ORDER BY SR.LAST_MODIFIED_DATE) ACT_IND,
  MAX(SR.SUPPLEMENT_TYPE) KEEP (DENSE_RANK LAST ORDER BY SR.LAST_MODIFIED_DATE) SUPP_TYPE,
  MAX(SR.FIRST_ECCKT_ID) KEEP (DENSE_RANK LAST ORDER BY SR.LAST_MODIFIED_DATE) CKT,
  MAX(ASR.DATE_TIME_SENT) KEEP (DENSE_RANK LAST ORDER BY ASR.LAST_MODIFIED_DATE) D_REC, 
  MAX(ASR.DESIRED_DUE_DATE) KEEP (DENSE_RANK LAST ORDER BY ASR.LAST_MODIFIED_DATE) DD, 
  MAX(AUD.CRDD) KEEP (DENSE_RANK LAST ORDER BY AUD.LAST_MODIFIED_DATE) CRDD,
  MAX(ASR.ACCESS_PROVIDER_SERV_CTR_CODE) KEEP (DENSE_RANK LAST ORDER BY ASR.LAST_MODIFIED_DATE) ICSC,
  MAX(ASR.CASE_NUMBER) KEEP (DENSE_RANK LAST ORDER BY ASR.LAST_MODIFIED_DATE) CNO,
  MAX(REPLACE(SR.PROJECT_IDENTIFICATION,' ')) KEEP (DENSE_RANK LAST ORDER BY SR.LAST_MODIFIED_DATE) PROJ,
  MAX(SR.ACNA) KEEP (DENSE_RANK LAST ORDER BY SR.LAST_MODIFIED_DATE) ACNA,
  MAX(CIR.RATE_CODE) KEEP (DENSE_RANK LAST ORDER BY CIR.LAST_MODIFIED_DATE) RATE_CODE,
  MAX(CIR.SERVICE_TYPE_CODE) KEEP (DENSE_RANK LAST ORDER BY CIR.LAST_MODIFIED_DATE) SVC_CODE,
  MAX(ASR.NETWORK_CHANNEL_SERVICE_CODE) KEEP (DENSE_RANK LAST ORDER BY ASR.LAST_MODIFIED_DATE) NC,
  MAX(ASR.NETWORK_CHANNEL_OPTION_CODE) KEEP (DENSE_RANK LAST ORDER BY ASR.LAST_MODIFIED_DATE) NC_OPT,
  MAX(ASR.NETWORK_CHANNEL_INTERFACE_CODE) KEEP (DENSE_RANK LAST ORDER BY ASR.LAST_MODIFIED_DATE) NCI,
  MAX(DLR.SEC_NETWORK_CHANNEL_INTERFACE) KEEP (DENSE_RANK LAST ORDER BY DLR.LAST_MODIFIED_DATE) SECNCI,
  MAX(CIR.EXCHANGE_CARRIER_CIRCUIT_ID) KEEP (DENSE_RANK LAST ORDER BY CIR.LAST_MODIFIED_DATE) CIRCKT,
  MAX(ASR.NPA) KEEP (DENSE_RANK LAST ORDER BY ASR.LAST_MODIFIED_DATE) NPA,
  MAX(ASR.NXX) KEEP (DENSE_RANK LAST ORDER BY ASR.LAST_MODIFIED_DATE) NXX,
  SALI.EUNAME, 
  SUBSTR(SALI.STATE,1,2) STATE,
  MAX(ASR.SERVICE_AND_PRODUCT_ENHANC_COD) KEEP (DENSE_RANK LAST ORDER BY ASR.LAST_MODIFIED_DATE) SPEC,
  DET.BILL_PNUM PNUM,
  DET.BILL_VTA VTA,
  DET.ACTL,
  DET.INIT,
  DET.INIT_TEL_NO,
  DET.INIT_EMAIL,
  DET.DSGCON,
  DET.DSG_TEL_NO,
  SALI.LCON,
  EULU.LOCAL_CONTACT_EMAIL LCON_EMAIL,
  SALI.ACTEL,
  TSK2.TASK_TYPE TASK_AT_READY,
  TSK3.TASK_TYPE TASK_AT_JEOP,
  JW.JEOPARDY_REASON_CODE JEOP_CODE
--
FROM SERV_REQ SR, 
     ACCESS_SERVICE_REQUEST ASR, 
     CIRCUIT CIR,
     DESIGN_LAYOUT_REPORT DLR, 
     TASK TSK,
     TASK TSK2,
     TASK_JEOPARDY_WHYMISS JW,
     TASK TSK3,
     ASR_USER_DATA AUD,
     DATA_EXT.ASR_SALI SALI,
     DATA_EXT.ASR_DETAIL DET,
     END_USER_LOCATION_USAGE EULU
--
WHERE SR.DOCUMENT_NUMBER = ASR.DOCUMENT_NUMBER(+)
AND SR.DOCUMENT_NUMBER = TSK.DOCUMENT_NUMBER (+)
AND SR.DOCUMENT_NUMBER = TSK2.DOCUMENT_NUMBER (+)
AND SR.DOCUMENT_NUMBER = JW.DOCUMENT_NUMBER (+)
AND JW.TASK_NUMBER = TSK3.TASK_NUMBER (+)
AND SR.DOCUMENT_NUMBER = DLR.DOCUMENT_NUMBER (+)
AND SR.DOCUMENT_NUMBER = AUD.DOCUMENT_NUMBER (+)
AND DLR.CIRCUIT_DESIGN_ID = CIR.CIRCUIT_DESIGN_ID (+)
AND SR.DOCUMENT_NUMBER = SALI.DOCUMENT_NUMBER(+)
AND SR.DOCUMENT_NUMBER = DET.DOCUMENT_NUMBER (+)
AND SR.DOCUMENT_NUMBER = EULU.DOCUMENT_NUMBER (+)
AND SR.TYPE_OF_SR IN ('ASR')
AND ASR.REQUEST_TYPE IN ('S','E')
AND ASR.ACTIVITY_INDICATOR IN ('N','C','R')
AND TSK.TASK_TYPE(+) = 'DD'
AND TSK.ACTUAL_COMPLETION_DATE IS NULL
AND TSK2.TASK_STATUS (+) = 'Ready'
AND JW.JEOPARDY_TYPE_CD (+) = 'J'
AND JW.DATE_CLOSED (+) IS NULL
AND (ASR.SERVICE_AND_PRODUCT_ENHANC_COD IN ('EPATHCP','EPATHN','EVPLSN','EVPLPN','EVPLGN','EPLELSN','EPLELPN','ERSNPA','ERSNPN')
 OR SUBSTR(ASR.NETWORK_CHANNEL_SERVICE_CODE,1,2) = 'SN')
--
GROUP BY SR.DOCUMENT_NUMBER,
  SR.PON, SALI.EUNAME, DET.BILL_PNUM, SALI.STATE, DET.ACTL,
  DET.BILL_VTA,
  DET.INIT,
  DET.INIT_TEL_NO,
  DET.INIT_EMAIL,
  DET.DSGCON,
  DET.DSG_TEL_NO,
  SALI.LCON,
  EULU.LOCAL_CONTACT_EMAIL,
  SALI.ACTEL,
  TSK2.TASK_TYPE,
  TSK3.TASK_TYPE,
  JW.JEOPARDY_REASON_CODE
)
--
DATA, NPA_NXX NPA, JEOPARDY_TYPE JT
WHERE DATA.NPA = NPA.NPA (+)
  AND DATA.NXX = NPA.NXX (+)
  AND DATA.JEOP_CODE = JT.JEOPARDY_REASON_CODE (+)
  AND JT.JEOPARDY_TYPE_CD (+) = 'J'
AND (SUPP_TYPE <> '1' OR SUPP_TYPE IS NULL)
)
WHERE TYPE <> 'EXCLUDE'
 ORDER BY 1 DESC,8;
 
 
 
 
 
 
