SELECT STATE, EPATH_CKT_ID, CIRCUIT, SPEC, ACTL, STATUS, A_CLLI, A_LOCATION_NAME, Z_CLLI, Z_LOCATION_NAME, BIT_RATE||'G' BIT_RATE,
CONCAT(SUM(CIR),'G') "M6 ALLOCATED CIR {GE}",
concat(round(((sum(CIR)/(BIT_RATE*"QoS Prevention Threshold"/100)))*100,1),'%') "M6 ALLOCATED CIR %",
concat(round((((BIT_RATE*"QoS Prevention Threshold"/100) - sum(CIR)))*1,3),'G') "M6 AVAILABLE CIR {GE}",
concat(round((((BIT_RATE*("QoS Prevention Threshold"/100))) - SUM(CIR))*1,3)/(((BIT_RATE)*("QoS Prevention Threshold"/100)))*100,'%') "M6 AVAILABLE CIR %",
concat((((BIT_RATE)*("QoS Warning Threshold"/100))),'G') MIN_THRESHOLD,
concat(round(((BIT_RATE)*("QoS Prevention Threshold"/100))*1,3),'G') MAX_THRESHOLD, PNUM, NODE_ADDRESS
FROM (
SELECT DISTINCT STATE, EPATH_CKT_ID, CIRCUIT, SPEC, ACTL, STATUS, 
       A_CLLI, A_LOCATION_NAME, Z_CLLI, Z_LOCATION_NAME, NODE_ADDRESS,
       CA_VALUE, CA_VALUE_LABEL, UNI_CA, UNI_LABEL, PNUM
FROM (       
SELECT DISTINCT
       GA.INSTANCE_VALUE_ABBREV STATE,
       C1.CIRCUIT_DESIGN_ID EPATH_CKT_ID,
       CASE WHEN CUD.SPEC_CODE IS NOT NULL THEN CUD.SPEC_CODE||' - '||CUD.SPEC_DESCRIPTION ELSE ASR.SERVICE_AND_PRODUCT_ENHANC_COD END SPEC,
       C1.EXCHANGE_CARRIER_CIRCUIT_ID CIRCUIT,
       decode( c1.status, '1', 'Pending', '3', 'In Progress', '4', 'CLR Issued', '5', 'DLR Issued',
                                 '6', 'In Service', '7', 'Pending Disconnect', '8', 'Disconnected', '9',
                                 'Problem', 'A', 'Cancelled','P', 'Planned', c1.status ) STATUS,
       CASE WHEN CCV2.CA_VALUE_UOM = 'M' THEN TO_CHAR(CCV2.CA_VALUE/1000) ELSE CCV2.CA_VALUE END UNI_CA,
       --CCV2.CA_VALUE UNI_CA,
       CCV2.CA_VALUE_LABEL UNI_LABEL,
       NL1.CLLI_CODE A_CLLI,
       NL1.LOCATION_NAME A_LOCATION_NAME,
       NL2.CLLI_CODE Z_CLLI,
       NL2.LOCATION_NAME Z_LOCATION_NAME,
       NL3.CLLI_CODE||': '||NL3.LOCATION_NAME ACTL,
       (SELECT ACTUAL_COMPLETION_DATE FROM TASK T WHERE T.DOCUMENT_NUMBER = SRC.DOCUMENT_NUMBER AND T.TASK_TYPE = 'DD') COMPLETION_DATE,
       CASE
                  WHEN CCV.CA_VALUE_LABEL = 'QoS (Num)' THEN 'CIR'
                  WHEN CCV.CA_VALUE_LABEL = 'QoS' THEN 'CIR'
                  WHEN CCV.CA_VALUE_LABEL = 'Service Level' THEN 'Class of Service'
                  WHEN CCV.CA_VALUE_LABEL = 'VLAN_TYPE' THEN 'EVC Type'
                  WHEN CCV.CA_VALUE_LABEL = 'S-VLAN ID1' THEN 'RUID #1 S-VLAN ID'
                  WHEN CCV.CA_VALUE_LABEL = 'Data VLAN #1' THEN 'RUID #1 S-VLAN ID'
                  WHEN CCV.CA_VALUE_LABEL = 'S-VLAN ID-1' THEN 'RUID #1 S-VLAN ID'
                  WHEN CCV.CA_VALUE_LABEL = 'Data VLAN #2' THEN 'RUID #2 S-VLAN ID'
                  WHEN CCV.CA_VALUE_LABEL = 'S-VLAN ID2' THEN 'RUID #2 S-VLAN ID'
                  WHEN CCV.CA_VALUE_LABEL = 'CE_VLAN' THEN 'CE-VLAN ID1'
                  WHEN CCV.CA_VALUE_LABEL = 'CE-VLAN ID-1' THEN 'CE-VLAN ID1'
                  WHEN CCV.CA_VALUE_LABEL = 'CE-VLAN ID6' THEN 'CE-VLAN ID2'
                  ELSE CCV.CA_VALUE_LABEL
               END
               CA_VALUE_LABEL,
       CASE WHEN CCV.CA_ID = 100222 AND CCV.CA_VALUE_UOM = 'M' THEN TO_CHAR(CCV.CA_VALUE/1000) ELSE CCV.CA_VALUE END CA_VALUE,
       --CCV.CA_VALUE,
       C2.CIRCUIT_DESIGN_ID EVC_ID,
       C2.EXCHANGE_CARRIER_CIRCUIT_ID EVC_CIRCUIT,
       ASR.PROMOTION_NBR PNUM
  FROM CIRCUIT C1,
       NETWORK_LOCATION NL1,
       NETWORK_LOCATION NL2,
       NET_LOC_ADDR NLA,
       ADDRESS A,
       GA_INSTANCE GA,
       DLR_CONN_CA_VALUE DLRCCV,
       (SELECT CIRCUIT_DESIGN_ID, MAX(ISSUE_NBR) ISSUE_NBR FROM DESIGN_LAYOUT_REPORT GROUP BY CIRCUIT_DESIGN_ID) DLR,
       CIRCUIT_USER_DATA CUD,
       CONN_CA_VALUE CCV2,
       (SELECT CIRCUIT_DESIGN_ID_PARENT, CIRCUIT_DESIGN_ID_CHILD FROM NS_CON_REL WHERE NS_CON_REL_STATUS_CD != 4) NSCR,
         (SELECT distinct * FROM ( SELECT  
          D.DOCUMENT_NUMBER, D.CIRCUIT_DESIGN_ID, D.CIRCUIT_ACTIVITY_IND,
          ROW_NUMBER() OVER (partition by CIRCUIT_DESIGN_ID order by DOCUMENT_NUMBER DESC, CIRCUIT_ACTIVITY_IND DESC) r
          FROM  
          SERVICE_REQUEST_CIRCUIT D WHERE CIRCUIT_ACTIVITY_IND IN ('N','R'))
          WHERE r = 1) SRC,
       ACCESS_SERVICE_REQUEST ASR,
       NETWORK_LOCATION NL3,
       CIRCUIT C2,
       SERV_ITEM SI,
       CUST_ACCT CA,
       (SELECT distinct * FROM
               (SELECT D.DESIGN_ID, D.ISSUE_NBR, D.SERV_ITEM_ID, D.CKT_IDENT,
               ROW_NUMBER() OVER (partition BY SERV_ITEM_ID order by ISSUE_NBR DESC) r
               FROM ASAP.DESIGN D) WHERE R = 1) DS,
       DESIGN_CONN_CA_VALUE DCCV,
       CONN_CA_VALUE CCV
 WHERE C1.CIRCUIT_DESIGN_ID = NSCR.CIRCUIT_DESIGN_ID_PARENT(+)
   AND C1.LOCATION_ID = NL1.LOCATION_ID
   AND C1.LOCATION_ID_2 = NL2.LOCATION_ID(+)
   AND NL1.LOCATION_ID = NLA.LOCATION_ID
   AND NLA.ADDRESS_ID = A.ADDRESS_ID
   AND A.GA_INSTANCE_ID_STATE_CD = GA.GA_INSTANCE_ID
   AND C1.CIRCUIT_DESIGN_ID = CUD.CIRCUIT_DESIGN_ID
   AND C1.CIRCUIT_DESIGN_ID = CCV2.CIRCUIT_DESIGN_ID
   AND CCV2.CIRCUIT_DESIGN_ID = DLRCCV.CIRCUIT_DESIGN_ID
   AND CCV2.CONN_CA_VALUE_ID = DLRCCV.CONN_CA_VALUE_ID
   AND DLRCCV.CIRCUIT_DESIGN_ID = DLR.CIRCUIT_DESIGN_ID
   AND DLRCCV.ISSUE_NBR = DLR.ISSUE_NBR
   AND NSCR.CIRCUIT_DESIGN_ID_CHILD = C2.CIRCUIT_DESIGN_ID(+)
   AND C1.CIRCUIT_DESIGN_ID = SRC.CIRCUIT_DESIGN_ID(+)
   AND SRC.DOCUMENT_NUMBER = ASR.DOCUMENT_NUMBER(+)
   AND ASR.LOCATION_ID = NL3.LOCATION_ID(+)
   AND C2.CIRCUIT_DESIGN_ID = SI.CIRCUIT_DESIGN_ID(+)
   AND SI.CUST_ACCT_ID = CA.CUST_ACCT_ID(+)
   AND SI.SERV_ITEM_ID = DS.SERV_ITEM_ID(+)
   AND DS.DESIGN_ID = DCCV.DESIGN_ID(+)
   AND DCCV.CONN_CA_VALUE_ID = CCV.CONN_CA_VALUE_ID(+)
   AND C1.TYPE = 'C'
   AND C1.STATUS != 'A'
   AND GA.INSTANCE_VALUE_ABBREV NOT IN ('WA','OR','ID','MT')
   --AND C1.CIRCUIT_DESIGN_ID IN (6062537)
   AND (ASR.SERVICE_AND_PRODUCT_ENHANC_COD IN ('EPATHN','EPATHCP') OR CUD.SPEC_CODE IN ('EPATHN','EPATHCP'))
   )B, 
    (SELECT DISTINCT * FROM
      (SELECT CIRCUIT_DESIGN_ID, EQUIPMENT_ID, PORTADDR_SEQ, NODE_ADDRESS, 
       ROW_NUMBER() OVER (PARTITION BY CIRCUIT_DESIGN_ID ORDER BY LAST_MODIFIED_DATE desc, equipment_id desc) R 
      FROM PORT_ADDRESS
        WHERE SUBSTR(NODE_ADDRESS,1,3) = 'ETH')
         WHERE R = 1) PA
    WHERE B.EPATH_CKT_ID = PA.CIRCUIT_DESIGN_ID (+) 
   )
   PIVOT (MAX(CA_VALUE)
           FOR(CA_VALUE_LABEL)
           IN  ('CIR' "CIR"))
    PIVOT (MAX(UNI_CA)
           FOR(UNI_LABEL)
           IN  ('Bit Rate' "BIT_RATE",
           'QoS Warning Threshold' "QoS Warning Threshold",
           'QoS Prevention Threshold' "QoS Prevention Threshold"))
    GROUP BY STATE, EPATH_CKT_ID, CIRCUIT, SPEC, ACTL, STATUS, A_CLLI, A_LOCATION_NAME, Z_CLLI, Z_LOCATION_NAME, BIT_RATE, "QoS Prevention Threshold", "QoS Warning Threshold", PNUM, NODE_ADDRESS
ORDER BY 1, 3;
