SELECT DISTINCT DOCUMENT_NUMBER, PON, FIRST_ECCKT_ID, ACNA, DATE_RECEIVED, DESIRED_DUE_DATE,
       ACTIVITY_IND, CIRCUIT_ACTIVITY_IND, SUPPLEMENT_TYPE, PLAN_NAME, STATE,
       CASE WHEN STATE IN ('CT','NY','PA','AL','FL','GA','MS','NC','SC','TN') then 'Eastern'
            WHEN STATE IN ('IA','IL','IN','MI','MN','NE','WI','KY','TX','OH','WV','MD','VA') then 'Central'
       		WHEN STATE IN ('CA','AZ','NM','NV','UT') then 'Western'
            ELSE 'Unknown' END REGION,
       CASE WHEN STATE IN ('AL','GA','MS','TN') THEN 'SOUTH STATES'
            WHEN STATE IN ('IA','MN','NE') THEN 'MID STATES'
            WHEN STATE IN ('AZ','NM','NV') THEN 'SOUTHWEST'
            WHEN STATE IN ('KY') THEN 'IN'
            WHEN STATE IN ('MO') THEN 'IL'
            WHEN STATE IN ('MD','VA') THEN 'WV'
            ELSE STATE END AREA
FROM (
--
SELECT DISTINCT DOCUMENT_NUMBER, PON, FIRST_ECCKT_ID, ACNA, DATE_RECEIVED, DESIRED_DUE_DATE,
       ACTIVITY_IND, CIRCUIT_ACTIVITY_IND, SUPPLEMENT_TYPE, PLAN_NAME,
       CASE WHEN NPASTATE2 IS NOT NULL THEN NPASTATE2
            WHEN NPASTATE1 IS NOT NULL THEN NPASTATE1
            WHEN NPASTATE4 IS NOT NULL THEN NPASTATE4
            ELSE NPASTATE3 END STATE
FROM (         
--
SELECT DISTINCT DOCUMENT_NUMBER, PON, FIRST_ECCKT_ID, ACNA,
       CASE WHEN ASR_DATE_RECEIVED IS NOT NULL THEN ASR_DATE_RECEIVED
            WHEN PSR_CONTRACT_DATE IS NOT NULL AND PSR_CONTRACT_DATE < DESIRED_DUE_DATE 
             AND TO_CHAR(PSR_CONTRACT_DATE,'YYYY') > '2018' AND PSR_CONTRACT_DATE < SYSDATE
             THEN PSR_CONTRACT_DATE ELSE NOTE_DATE END DATE_RECEIVED,
       DESIRED_DUE_DATE, ACTIVITY_IND, CIRCUIT_ACTIVITY_IND,
       SUPPLEMENT_TYPE, PLAN_NAME,
       SUBSTR(NPA1.EXCHANGE_AREA_CLLI,5,2) NPASTATE1,
       SUBSTR(NPA2.EXCHANGE_AREA_CLLI,5,2) NPASTATE2,
       SUBSTR(NPA3.EXCHANGE_AREA_CLLI,5,2) NPASTATE3,
       SUBSTR(NPA4.EXCHANGE_AREA_CLLI,5,2) NPASTATE4
FROM (            
--
SELECT DISTINCT SR.DOCUMENT_NUMBER, SR.PON, FIRST_ECCKT_ID, SR.ACNA, TRUNC(DATE_RECEIVED) ASR_DATE_RECEIVED, 
       PSR.CONTRACT_DATE PSR_CONTRACT_DATE, SR.DESIRED_DUE_DATE, ACTIVITY_IND, SRC.CIRCUIT_ACTIVITY_IND,
       SR.SUPPLEMENT_TYPE, PROV.PLAN_NAME,
       min(trunc(date_entered)) note_date,
       ASR.NPA, ASR.NXX, SUBSTR(PSR.NPA_NXX,1,3) NPA1, SUBSTR(PSR.NPA_NXX,4,3) NXX1                                       
FROM SERV_REQ SR, 
     ACCESS_SERVICE_REQUEST ASR,
     SERVICE_REQUEST_CIRCUIT SRC, 
     PSR_USER_DATA PSR,
     TASK T,  
     SVCREQ_PROVPLAN PP, 
     PROVISIONING_PLAN PROV,
     NOTES NTS                                        
WHERE SR.DOCUMENT_NUMBER = ASR.DOCUMENT_NUMBER (+)                                       
AND SR.DOCUMENT_NUMBER = PSR.DOCUMENT_NUMBER (+)
AND SR.DOCUMENT_NUMBER = SRC.DOCUMENT_NUMBER (+)
AND SR.DOCUMENT_NUMBER = T.DOCUMENT_NUMBER (+) 
AND SR.DOCUMENT_NUMBER = NTS.DOCUMENT_NUMBER (+)
AND T.REQ_PLAN_ID = PP.REQ_PLAN_ID (+)                                        
AND PP.PLAN_ID = PROV.PLAN_ID (+) 
AND T.TASK_TYPE = 'DD'
AND PROV.PLAN_ID IN ('13607','13606')                                                                               
AND (SR.SUPPLEMENT_TYPE <> 1 OR SR.SUPPLEMENT_TYPE IS NULL)
AND T.ACTUAL_COMPLETION_DATE IS NULL
AND (ACNA IN ('FLR','BLI','BNK','CMW','COY','CQV','CUS','CZE','CZJ','CZN','CZX','EPX','ERR','EXC','FBA','FCA','FIS',
              'FLX','GOP','GTO','GVN','IZH','NNR','OGD','RGD','ROU','T05','VAC','VZN','WDK','ZAP','ZWV','ZZZ','XYY') OR ACNA IS NULL)
GROUP BY SR.DOCUMENT_NUMBER, SR.PON, FIRST_ECCKT_ID, SR.ACNA, DATE_RECEIVED, PSR.CONTRACT_DATE, SR.DESIRED_DUE_DATE, 
         ACTIVITY_IND, SRC.CIRCUIT_ACTIVITY_IND, SR.SUPPLEMENT_TYPE, PROV.PLAN_NAME, ASR.NPA, ASR.NXX, PSR.NPA_NXX
--
)A, NPA_NXX NPA1, NPA_NXX NPA2, NPA_NXX NPA3, NPA_NXX NPA4 
WHERE A.NPA = NPA1.NPA (+)
  AND A.NXX = NPA1.NXX (+)
  AND A.NPA1 = NPA2.NPA (+)
  AND A.NXX1 = NPA2.NXX (+)
  AND A.NPA = NPA3.NPA (+)
  AND (A.NPA1 = NPA4.NPA (+) and substr(npa4.exchange_area_clli,5,2) <> 'EF')
)
-- 
)
--                       
ORDER BY 5,1
;
