SELECT DOCUMENT_NUMBER, DREC, DD, COMP_DT, WMRCA, WMDESC,
       CASE WHEN (COMP_DT <= DD OR DD IS NULL) THEN 'Met'
            WHEN (COMP_DT > DD AND WMRCA IN ('CU01','CU02','CU03','CU04','CU05','DS02','CA22','EX01','CU51','CU52','CU53','CU54','DS52','PM52','PM53','PM54','PM55')) THEN 'Met'
            ELSE 'Miss' END ORIG_DD_STATUS,
       FOC_DT, TYPE_OF_SR, FIRST_NOTE INIT_REC     
FROM (
--
SELECT DOCUMENT_NUMBER, FIRST_NOTE, TYPE_OF_SR, DREC, DD, ACCEPT_DT, DD_COMP, WMRCA, REGEXP_REPLACE (WMDESC,'[[:cntrl:]]*') WMDESC, FOC_DT,
       CASE WHEN DD_COMP IS NULL AND ACCEPT_DT > FIRST_NOTE THEN ACCEPT_DT
            WHEN ACCEPT_DT IS NULL THEN DD_COMP
            WHEN ACCEPT_DT <= DD_COMP AND ACCEPT_DT > FIRST_NOTE THEN ACCEPT_DT 
            ELSE DD_COMP END COMP_DT
FROM (
--
SELECT DOCUMENT_NUMBER, DD, TYPE_OF_SR, 
       CASE WHEN TYPE_OF_SR = 'SO' THEN PSR_DREC
        ELSE DREC END DREC,
       CASE WHEN TYPE_OF_SR = 'SO' THEN PSR_ACCEPT_DT
        ELSE ACCEPT_DT END ACCEPT_DT,
       DD_COMP, WMRCA, JT.JEOPARDY_REASON_DESCRIPTION WMDESC, FIRST_NOTE,
       CASE WHEN PSR_FOC_DT IS NOT NULL THEN PSR_FOC_DT
        ELSE ASR_FOC_DT END FOC_DT
FROM (
--       
SELECT SR.DOCUMENT_NUMBER, SR.TYPE_OF_SR, 
       MAX(TRUNC(ASR.DATE_TIME_SENT)) KEEP (DENSE_RANK LAST ORDER BY ASR.LAST_MODIFIED_DATE) DREC, 
       MAX(TRUNC(PUD.CONTRACT_DATE)) KEEP (DENSE_RANK LAST ORDER BY PUD.LAST_MODIFIED_DATE) PSR_DREC, 
       MAX(SR.DESIRED_DUE_DATE) KEEP (DENSE_RANK LAST ORDER BY SR.LAST_MODIFIED_DATE) DD, 
       MIN(AUD.ACCEPTANCE_DATE) KEEP (DENSE_RANK LAST ORDER BY AUD.LAST_MODIFIED_DATE) ACCEPT_DT,
       MIN(PUD.ACCEPTANCE_DATE) KEEP (DENSE_RANK LAST ORDER BY PUD.LAST_MODIFIED_DATE) PSR_ACCEPT_DT,
       TRUNC(T.ACTUAL_COMPLETION_DATE) DD_COMP, 
       MAX(JWRCA.JEOPARDY_REASON_CODE) KEEP (DENSE_RANK LAST ORDER BY JWRCA.LAST_MODIFIED_DATE) WMRCA,
       MIN(TRUNC(NTS.DATE_ENTERED)) FIRST_NOTE,
       MIN(TRUNC(NTS2.DATE_ENTERED)) PSR_FOC_DT,
       MIN(TRUNC(NTS3.DATE_ENTERED)) ASR_FOC_DT
FROM ASR_USER_DATA AUD,
     PSR_USER_DATA PUD,
     ACCESS_SERVICE_REQUEST ASR,
     SERV_REQ SR,
     TASK_JEOPARDY_WHYMISS JW,
     TASK_JEOPARDY_WHYMISS JWRCA,
     TASK T,
     TASK TRCA,
     NOTES NTS,
     NOTES NTS2,
     NOTES NTS3
WHERE SR.DOCUMENT_NUMBER = ASR.DOCUMENT_NUMBER (+)
  AND SR.DOCUMENT_NUMBER = AUD.DOCUMENT_NUMBER(+)
  AND SR.DOCUMENT_NUMBER = PUD.DOCUMENT_NUMBER(+)
  AND SR.DOCUMENT_NUMBER = T.DOCUMENT_NUMBER
  AND SR.DOCUMENT_NUMBER = TRCA.DOCUMENT_NUMBER (+)
  AND SR.DOCUMENT_NUMBER = NTS.DOCUMENT_NUMBER (+)
  AND SR.DOCUMENT_NUMBER = NTS2.DOCUMENT_NUMBER (+)
  AND SR.DOCUMENT_NUMBER = NTS3.DOCUMENT_NUMBER (+)
  AND T.TASK_NUMBER = JW.TASK_NUMBER(+)
  AND TRCA.TASK_NUMBER = JWRCA.TASK_NUMBER(+)
  AND JW.JEOPARDY_TYPE_CD(+) = 'W' 
  AND T.TASK_TYPE = 'DD'
  AND TRCA.TASK_TYPE (+) = 'RCA'
  AND NTS2.NOTE_TEXT (+) = 'PSR-CONF TASK COMPLETED' 
  AND NTS3.NOTE_TEXT (+) = 'ASR-CONF TASK COMPLETED' 
  AND SR.DOCUMENT_NUMBER IN (
'3505268',
'3505435',
'3506154',
'3507825'
)
  GROUP BY SR.DOCUMENT_NUMBER, SR.TYPE_OF_SR, T.ACTUAL_COMPLETION_DATE,T.REVISED_COMPLETION_DATE 
--
)A,
 JEOPARDY_TYPE JT
 WHERE A.WMRCA = JT.JEOPARDY_REASON_CODE (+)
 AND JEOPARDY_TYPE_CD (+) = 'W'
--
)  
--
);