SELECT CLEAN, EVC_CKT, EVC_CKT_DESIGN, EVC_DOCNO, EVC_PON, EVC_RECEIVED, EVC_CRDD, EVC_PNUM, EVC_SUPP, EVC_IND, EVC_RPON, EVC_RPON_ACT, EVC_PROJ, EVC_REMARK, EVC_DD_COMP,
       UNI_CKT, UNI_CKT_DESIGN, UNI_DOCNO, UNI_PON, UNI_RECEIVED, UNI_CRDD, UNI_SUPP, UNI_RPON, SR3.ACTIVITY_IND UNI_RPON_ACT, UNI_PROJ, UNI_REMARK, UNI_DD_COMP            
  FROM (
----
SELECT REPLACE(REPLACE(EVC_CKT,'/'),' ') CLEAN,
       EVC_CKT, EVC_CKT_DESIGN, EVC_DOCNO, EVC_PON, EVC_RECEIVED, EVC_CRDD, EVC_PNUM, EVC_SUPP, F.EVC_IND, EVC_RPON, EVC_RPON_ACT, EVC_PROJ, EVC_REMARK, EVC_DD_COMP,
       UNI_CKT, UNI_CKT_DESIGN, UNI_DOCNO, ASR.PON UNI_PON, ASR.DATE_TIME_SENT UNI_RECEIVED, AUD.CRDD UNI_CRDD, ASR.SUPPLEMENT_TYPE UNI_SUPP, 
       ASR.RELATED_PON UNI_RPON, ASR.PROJECT_IDENTIFICATION UNI_PROJ, RMRK.REMARK UNI_REMARK, T2.ACTUAL_COMPLETION_DATE UNI_DD_COMP            
  FROM (
----      
SELECT EVC_DOCNO, EVC_PON, CRDD EVC_CRDD, DATE_TIME_SENT EVC_RECEIVED, EVC_PNUM, EVC_CKT, EVC_CKT_DESIGN, EVC_REMARK, EVC_IND, EVC_RPON, EVC_RPON_ACT, EVC_PROJ, EVC_SUPP, EVC_DD_COMP,
       RUID, UNI_CKT, UNI_CKT_DESIGN, SRC.DOCUMENT_NUMBER UNI_DOCNO
  FROM (
----
SELECT EVC_DOCNO, EVC_PON, CRDD, DATE_TIME_SENT, EVC_PNUM, EVC_CKT, EVC_CKT_DESIGN, EVC_REMARK, EVC_IND, EVC_SUPP, EVC_RPON, EVC_RPON_ACT, EVC_PROJ, EVC_DD_COMP, 
       RUID, C2.EXCHANGE_CARRIER_CIRCUIT_ID UNI_CKT, C2.CIRCUIT_DESIGN_ID UNI_CKT_DESIGN
  FROM (
----
SELECT EVC_DOCNO, EVC_PON, CRDD, DATE_TIME_SENT, EVC_PNUM, EVC_CKT, EVC_CKT_DESIGN, EVC_REMARK, EVC_IND, EVC_RPON, EVC_RPON_ACT, EVC_PROJ, EVC_SUPP, EVC_DD_COMP,
      REGEXP_REPLACE(REL_UNI_IDENT,'[^a-zA-Z0-9'']','') RUID
  FROM (
----
SELECT EVC_DOCNO, EVC_PON, CRDD, DATE_TIME_SENT, EVC_PNUM, EVC_CKT, EVC_CKT_DESIGN, EVC_REMARK, EVC_IND, EVC_RPON, SR2.ACTIVITY_IND EVC_RPON_ACT, EVC_PROJ, EVC_SUPP, EVC_DD_COMP,
       MAX(SRC.DOCUMENT_NUMBER) UNI_DOCNO 
  FROM (
----
SELECT ASR.DOCUMENT_NUMBER EVC_DOCNO, ASR.PON EVC_PON, AUD.CRDD, ACTIVITY_INDICATOR ACT, EVC_IND, ASR.RELATED_PON EVC_RPON, ASR.PROJECT_IDENTIFICATION EVC_PROJ, DATE_RECEIVED, DATE_TIME_SENT, ASR.SUPPLEMENT_TYPE EVC_SUPP, 
       PROMOTION_NBR EVC_PNUM, EXCHANGE_CARRIER_CIRCUIT_ID EVC_CKT, C.CIRCUIT_DESIGN_ID EVC_CKT_DESIGN, RMRK.REMARK EVC_REMARK, T.ACTUAL_COMPLETION_DATE EVC_DD_COMP
FROM SERV_REQ SR, ACCESS_SERVICE_REQUEST ASR, ASR_USER_DATA AUD, SERVICE_REQUEST_CIRCUIT SRC, CIRCUIT C, REMARK RMRK, TASK T
WHERE SR.DOCUMENT_NUMBER = ASR.DOCUMENT_NUMBER
  AND ASR.DOCUMENT_NUMBER = AUD.DOCUMENT_NUMBER
  AND ASR.DOCUMENT_NUMBER = SRC.DOCUMENT_NUMBER
  AND SRC.CIRCUIT_DESIGN_ID = C.CIRCUIT_DESIGN_ID 
  AND ASR.DOCUMENT_NUMBER = RMRK.DOCUMENT_NUMBER (+)
  AND ASR.DOCUMENT_NUMBER = T.DOCUMENT_NUMBER (+)
  AND T.TASK_TYPE = 'DD'
--AND PROMOTION_NBR IN ('EPAV001999SCM792','EPAV001ATXSCM792BK')
AND SR.ACNA IN ('ATX','AAV','AVA','LOA','SBB','SBZ','SUV','TPM')
AND ACTIVITY_INDICATOR = 'D'
AND EVC_IND IN ('A','B')
AND SUBSTR(EXCHANGE_CARRIER_CIRCUIT_ID,4,2) = 'VL'
AND RMRK.FORM_ID (+) = 'ASR'
AND TO_CHAR(AUD.CRDD,'YYYYMMDD') BETWEEN '20230701' AND '20231231'
----
) 
A, SERVICE_REQUEST_CIRCUIT SRC, CIRCUIT C, SERV_REQ SR, SERV_REQ SR2
WHERE A.EVC_CKT_DESIGN = SRC.CIRCUIT_DESIGN_ID 
AND SRC.CIRCUIT_DESIGN_ID = C.CIRCUIT_DESIGN_ID
AND SRC.DOCUMENT_NUMBER = SR.DOCUMENT_NUMBER
AND A.EVC_RPON = SR2.PON (+)
AND SR.ORDER_COMPL_DT IS NOT NULL
AND (SR.SUPPLEMENT_TYPE <> 1 OR SR.SUPPLEMENT_TYPE IS NULL)
AND SR.ACTIVITY_IND <> 'D' 
GROUP BY EVC_DOCNO, EVC_PON, CRDD, DATE_TIME_SENT, EVC_PNUM, EVC_CKT, EVC_CKT_DESIGN, EVC_REMARK, EVC_IND, EVC_RPON, EVC_PROJ, EVC_SUPP, EVC_DD_COMP, SR2.ACTIVITY_IND
----
) 
B, EVC_UNI_MAP EUM
WHERE B.UNI_DOCNO = EUM.DOCUMENT_NUMBER
----
)
D, CIRCUIT C2, CIRCUIT_USER_DATA CUD
WHERE D.RUID = REGEXP_REPLACE(C2.EXCHANGE_CARRIER_CIRCUIT_ID,'[^a-zA-Z0-9'']','')
 AND C2.CIRCUIT_DESIGN_ID = CUD.CIRCUIT_DESIGN_ID
 AND CUD.UNI_OR_NNI = '435'
---- 
)
E, SERVICE_REQUEST_CIRCUIT SRC
WHERE E.UNI_CKT_DESIGN = SRC.CIRCUIT_DESIGN_ID (+) 
AND CIRCUIT_ACTIVITY_IND (+) = 'D'
----
)
F, ACCESS_SERVICE_REQUEST ASR, ASR_USER_DATA AUD, REMARK RMRK, TASK T2
WHERE F.UNI_DOCNO = ASR.DOCUMENT_NUMBER
  AND ASR.DOCUMENT_NUMBER = AUD.DOCUMENT_NUMBER
  AND ASR.DOCUMENT_NUMBER = RMRK.DOCUMENT_NUMBER (+)
  AND ASR.DOCUMENT_NUMBER = T2.DOCUMENT_NUMBER (+)
  AND T2.TASK_TYPE = 'DD'
  AND RMRK.FORM_ID (+) = 'ASR'
)
G, SERV_REQ SR3
WHERE G.UNI_RPON = SR3.PON (+)   
ORDER BY 2,4 
;


