Select clli_code, h_coordinate, v_coordinate
from network_location
where clli_code like 'ONTRNY%'
;

SELECT DISTINCT C.EXCHANGE_CARRIER_CIRCUIT_ID, C.CIRCUIT_DESIGN_ID, C.STATUS, CIRCUIT_XREF_ECCKT 
FROM CIRCUIT_XREF X, CIRCUIT C
--WHERE CIRCUIT_XREF_ECCKT LIKE '87/VLXP/101796%'
WHERE X.CIRCUIT_DESIGN_ID = C.CIRCUIT_DESIGN_ID
AND SUBSTR(C.EXCHANGE_CARRIER_CIRCUIT_ID,4,1) = 'V'
AND CIRCUIT_XREF_ECCKT in (
'R2LMMQ2043B'
)
ORDER BY 4,1,2
;

SELECT c.exchange_carrier_circuit_id, SRC.DOCUMENT_NUMBER, src.circuit_design_id, SR.ACTIVITY_IND, SR.SUPPLEMENT_TYPE, sr.pon, actual_completion_date
FROM circuit c, SERVICE_REQUEST_CIRCUIT SRC, SERV_REQ SR, task t
WHERE c.circuit_design_id = src.circuit_design_id 
and SRC.DOCUMENT_NUMBER = SR.DOCUMENT_NUMBER
and src.document_number = t.document_number
and t.task_type = 'DD'
--AND src.CIRCUIT_DESIGN_ID in ( '9226272')
and c.exchange_carrier_circuit_id like '87/VLXP/025347/%'
order by 2,1
;   

--UNI 
SELECT UNI_DESIGN_ID, UNI_STATUS, 
CASE WHEN UNI_CLLI IS NOT NULL THEN UNI_CLLI ELSE UNI_CLLI2 END UNI_CLLI,
CASE WHEN UNI_LOC IS NOT NULL THEN UNI_LOC ELSE UNI_LOC2 END UNI_LOC,
CASE WHEN UNI_H_COORD IS NOT NULL THEN UNI_H_COORD ELSE UNI_H_COORD2 END UNI_H_COORD,
CASE WHEN UNI_V_COORD IS NOT NULL THEN UNI_V_COORD ELSE UNI_V_COORD2 END UNI_V_COORD,UNI_IP
FROM (
SELECT EXCHANGE_CARRIER_CIRCUIT_ID UNI_CKT, C2A.STATUS UNI_STATUS, C2A.CIRCUIT_DESIGN_ID UNI_DESIGN_ID,  
       NL1.CLLI_CODE UNI_CLLI, NL1.LOCATION_NAME UNI_LOC, NL1.H_COORDINATE UNI_H_COORD, NL1.V_COORDINATE UNI_V_COORD,
       NL2.CLLI_CODE UNI_CLLI2, NL2.LOCATION_NAME UNI_LOC2, NL2.H_COORDINATE UNI_H_COORD2, NL2.V_COORDINATE UNI_V_COORD2,
       CCV1.CA_VALUE UNI_IP
FROM CIRCUIT C2A,   
  NETWORK_LOCATION NL1,
  NETWORK_LOCATION NL2,
  (SELECT DISTINCT CIRCUIT_DESIGN_ID, CA_VALUE, CA_VALUE_LABEL
      FROM (
            SELECT CIRCUIT_DESIGN_ID, 
            CA_VALUE, 
            CA_VALUE_LABEL,
            ROW_NUMBER() OVER (PARTITION BY CIRCUIT_DESIGN_ID ORDER BY CONN_CA_VALUE_ID DESC) R
         FROM CONN_CA_VALUE
          WHERE CA_USAGE_ID = '100521' )  --RAD IP   
              WHERE R = 1 ) CCV1 
 WHERE C2A.LOCATION_ID_2 = NL1.LOCATION_ID (+)
    AND C2A.LOCATION_ID = NL2.LOCATION_ID (+)
    AND C2A.CIRCUIT_DESIGN_ID = CCV1.CIRCUIT_DESIGN_ID (+) 
    AND C2A.CIRCUIT_DESIGN_ID in (
'8763875')    
)    
;    

SELECT NNI_DESIGN_ID, NNI_STATUS, 
CASE WHEN NNI_CLLI IS NOT NULL THEN NNI_CLLI ELSE NNI_CLLI2 END NNI_CLLI,
CASE WHEN NNI_LOC IS NOT NULL THEN NNI_LOC ELSE NNI_LOC2 END NNI_LOC,
CASE WHEN NNI_H_COORD IS NOT NULL THEN NNI_H_COORD ELSE NNI_H_COORD2 END NNI_H_COORD,
CASE WHEN NNI_V_COORD IS NOT NULL THEN NNI_V_COORD ELSE NNI_V_COORD2 END NNI_V_COORD, NNI_IP, NNI_COPPER_IP
FROM (
SELECT exchange_Carrier_circuit_id NNI_CKT, C3A.STATUS NNI_STATUS, c3a.circuit_design_id NNI_DESIGN_ID,
       NL3.CLLI_CODE NNI_CLLI, NL3.LOCATION_NAME NNI_LOC, NL3.H_COORDINATE NNI_H_COORD, NL3.V_COORDINATE NNI_V_COORD,
       NL4.CLLI_CODE NNI_CLLI2, NL4.LOCATION_NAME NNI_LOC2, NL4.H_COORDINATE NNI_H_COORD2, NL4.V_COORDINATE NNI_V_COORD2,
       CCV3.CA_VALUE NNI_IP, CCV4.CA_VALUE NNI_COPPER_IP
FROM    
 CIRCUIT C3A,           
  NETWORK_LOCATION NL3,
  NETWORK_LOCATION NL4,
  (SELECT DISTINCT CIRCUIT_DESIGN_ID, CA_VALUE, CA_VALUE_LABEL
      FROM (
            SELECT CIRCUIT_DESIGN_ID, 
            CA_VALUE, 
            CA_VALUE_LABEL,
            ROW_NUMBER() OVER (PARTITION BY CIRCUIT_DESIGN_ID ORDER BY CONN_CA_VALUE_ID DESC) R
         FROM CONN_CA_VALUE
          WHERE CA_USAGE_ID = '100521' )  --RAD IP   
              WHERE R = 1 ) CCV3,
  (SELECT DISTINCT CIRCUIT_DESIGN_ID, CA_VALUE, CA_VALUE_LABEL
      FROM (
            SELECT CIRCUIT_DESIGN_ID, 
            CA_VALUE, 
            CA_VALUE_LABEL,
            ROW_NUMBER() OVER (PARTITION BY CIRCUIT_DESIGN_ID ORDER BY CONN_CA_VALUE_ID DESC) R
         FROM CONN_CA_VALUE
          WHERE CA_USAGE_ID = '100246' )  --RAD IP   
              WHERE R = 1 ) CCV4      
    where C3A.LOCATION_ID_2 = NL3.LOCATION_ID (+)
    AND C3A.LOCATION_ID = NL4.LOCATION_ID (+)
    AND C3A.CIRCUIT_DESIGN_ID = CCV3.CIRCUIT_DESIGN_ID (+)  
    AND C3A.CIRCUIT_DESIGN_ID = CCV4.CIRCUIT_DESIGN_ID (+)
    and c3a.circuit_design_id in (
'8791063',
'9101657')    
)
;

--VLAN  
select c6.circuit_design_id, 
CASE WHEN CCV5.CA_VALUE IS NOT NULL AND CCV5.CA_VALUE <> '0' THEN CCV5.CA_VALUE  --RAD 
     WHEN CCV6.CA_VALUE IS NOT NULL AND CCV6.CA_VALUE <> '0' THEN CCV6.CA_VALUE  --RAD  
     WHEN CCV7.CA_VALUE IS NOT NULL AND CCV7.CA_VALUE <> '0' THEN CCV7.CA_VALUE  --CIENA 
     WHEN CCV8.CA_VALUE IS NOT NULL AND CCV8.CA_VALUE <> '0' THEN CCV8.CA_VALUE  --CIENA  
     ELSE NULL END VLAN 
from CIRCUIT C6, 
  (SELECT DISTINCT CIRCUIT_DESIGN_ID, CA_VALUE, CA_VALUE_LABEL
      FROM (
            SELECT CIRCUIT_DESIGN_ID, 
            CA_VALUE, 
            CA_VALUE_LABEL,
            ROW_NUMBER() OVER (PARTITION BY CIRCUIT_DESIGN_ID ORDER BY CONN_CA_VALUE_ID DESC) R
         FROM CONN_CA_VALUE
          WHERE CA_USAGE_ID = '100253' )    
              WHERE R = 1 ) CCV5,
  (SELECT DISTINCT CIRCUIT_DESIGN_ID, CA_VALUE, CA_VALUE_LABEL
      FROM (
            SELECT CIRCUIT_DESIGN_ID, 
            CA_VALUE, 
            CA_VALUE_LABEL,
            ROW_NUMBER() OVER (PARTITION BY CIRCUIT_DESIGN_ID ORDER BY CONN_CA_VALUE_ID DESC) R
         FROM CONN_CA_VALUE
          WHERE CA_USAGE_ID = '100254' )   
              WHERE R = 1 ) CCV6, 
  (SELECT DISTINCT CIRCUIT_DESIGN_ID, CA_VALUE, CA_VALUE_LABEL
      FROM (
            SELECT CIRCUIT_DESIGN_ID, 
            CA_VALUE, 
            CA_VALUE_LABEL,
            ROW_NUMBER() OVER (PARTITION BY CIRCUIT_DESIGN_ID ORDER BY CONN_CA_VALUE_ID DESC) R
         FROM CONN_CA_VALUE
          WHERE CA_USAGE_ID = '100577' )    
              WHERE R = 1 ) CCV7,
  (SELECT DISTINCT CIRCUIT_DESIGN_ID, CA_VALUE, CA_VALUE_LABEL
      FROM (
            SELECT CIRCUIT_DESIGN_ID, 
            CA_VALUE, 
            CA_VALUE_LABEL,
            ROW_NUMBER() OVER (PARTITION BY CIRCUIT_DESIGN_ID ORDER BY CONN_CA_VALUE_ID DESC) R
         FROM CONN_CA_VALUE
          WHERE CA_USAGE_ID = '100583' )    
              WHERE R = 1 ) CCV8                    
WHERE c6.CIRCUIT_DESIGN_ID = CCV5.CIRCUIT_DESIGN_ID (+)
AND c6.CIRCUIT_DESIGN_ID = CCV6.CIRCUIT_DESIGN_ID (+)
AND c6.CIRCUIT_DESIGN_ID = CCV7.CIRCUIT_DESIGN_ID (+)
AND c6.CIRCUIT_DESIGN_ID = CCV8.CIRCUIT_DESIGN_ID (+)
and c6.circuit_design_id in (
'8814727')
;

--BDW, PNUM, COS from CONN CA VALUE 
select c.exchange_carrier_circuit_id, c.circuit_design_id, ccv1.CA_VALUE BDW, ccv2.CA_VALUE PNUM, ccv3.CA_VALUE COS, ccv4.CA_VALUE COS2
FROM circuit c, 
(SELECT DISTINCT CIRCUIT_DESIGN_ID, CA_VALUE, CA_VALUE_LABEL
      FROM (
            SELECT CIRCUIT_DESIGN_ID, 
            CA_VALUE, 
            CA_VALUE_LABEL,
            ROW_NUMBER() OVER (PARTITION BY CIRCUIT_DESIGN_ID ORDER BY CONN_CA_VALUE_ID DESC) R
         FROM CONN_CA_VALUE
          WHERE CA_USAGE_ID = '100367' )  --BDW   
              WHERE R = 1 ) CCV1,
(SELECT DISTINCT CIRCUIT_DESIGN_ID, CA_VALUE, CA_VALUE_LABEL
      FROM (
            SELECT CIRCUIT_DESIGN_ID, 
            CA_VALUE, 
            CA_VALUE_LABEL,
            ROW_NUMBER() OVER (PARTITION BY CIRCUIT_DESIGN_ID ORDER BY CONN_CA_VALUE_ID DESC) R
         FROM CONN_CA_VALUE
          WHERE CA_USAGE_ID = '100741' )  --PNUM   
              WHERE R = 1 ) CCV2,
(SELECT DISTINCT CIRCUIT_DESIGN_ID, CA_VALUE, CA_VALUE_LABEL
      FROM (
            SELECT CIRCUIT_DESIGN_ID, 
            CA_VALUE, 
            CA_VALUE_LABEL,
            ROW_NUMBER() OVER (PARTITION BY CIRCUIT_DESIGN_ID ORDER BY CONN_CA_VALUE_ID DESC) R
         FROM CONN_CA_VALUE
          WHERE CA_USAGE_ID = '100252' )  --COS    
              WHERE R = 1 ) CCV3,
(SELECT DISTINCT CIRCUIT_DESIGN_ID, CA_VALUE, CA_VALUE_LABEL
      FROM (
            SELECT CIRCUIT_DESIGN_ID, 
            CA_VALUE, 
            CA_VALUE_LABEL,
            ROW_NUMBER() OVER (PARTITION BY CIRCUIT_DESIGN_ID ORDER BY CONN_CA_VALUE_ID DESC) R
         FROM CONN_CA_VALUE
          WHERE CA_USAGE_ID = '100257' )  --COS2    
              WHERE R = 1 ) CCV4                           
WHERE C.CIRCUIT_DESIGN_ID = CCV1.CIRCUIT_DESIGN_ID (+)
AND C.CIRCUIT_DESIGN_ID = CCV2.CIRCUIT_DESIGN_ID (+) 
AND C.CIRCUIT_DESIGN_ID = CCV3.CIRCUIT_DESIGN_ID (+)
AND C.CIRCUIT_DESIGN_ID = CCV4.CIRCUIT_DESIGN_ID (+)
AND substr(exchange_carrier_circuit_id,1,21) IN (
'  /VLXP/100643/   /SN')                        
ORDER BY 1;

--use LOCATION ID to pull in the NNI Address  
SELECT NLA2.LOCATION_ID, replace(addr.addr_ln1,'MSAG ') as Z_Address, trim(ga1.instance_value) z_city, 
ga2.instance_value_abbrev z_state
FROM (SELECT DISTINCT *
        FROM (SELECT d.location_id,
                     d.address_id,
                     d.active_ind,
                     ROW_NUMBER() OVER (PARTITION BY location_id ORDER BY address_id DESC) r
                   FROM net_loc_addr d
                    WHERE active_ind = 'Y')
                     WHERE r = 1) NLA2,                              
  address addr,
  mv_ga_instance ga1,
  mv_ga_instance ga2
WHERE nla2.address_id = addr.address_id
  and addr.ga_instance_id_city = ga1.ga_instance_id
  and addr.ga_instance_id_state_cd = ga2.ga_instance_id
  AND NLA2.LOCATION_ID IN (
'3082706') 