SELECT STATE, EVC_CKT_ID, EVC_CIRCUIT, CUSTOMER_NM, STATUS, ISSUE_STATUS, CIR, EVC_TYPE, CLASS_OF_SERVICE, "CoS", CE_VLAN_ID1,CE_VLAN_ID2, 
RUID_#1_S_VLAN_ID, RUID_#2_S_VLAN_ID,UNI_CKT_ID, UNI_CIRCUIT, ORIG_ELEMENT_NM, TERM_ELEMENT_NM, 
TERM_ELEMENT_TYPE, CONN2, CONN2_ORIG_ELEMENT_NM,CONN2_ORIG_ELEMENT_TYPE, CONN2_TERM_ELEMENT_NM, 
CONN2_TERM_ELEMENT_TYPE, CONN3, CONN3_ORIG_ELEMENT_NM,CONN3_ORIG_ELEMENT_TYPE, CONN3_TERM_ELEMENT_NM, CONN3_TERM_ELEMENT_TYPE, 
CONN4, CONN4_ORIG_ELEMENT_NM, CONN4_ORIG_ELEMENT_TYPE,CONN4_TERM_ELEMENT_NM, CONN4_TERM_ELEMENT_TYPE, 
CONN5, CONN5_ORIG_ELEMENT_NM, CONN5_ORIG_ELEMENT_TYPE,CONN5_TERM_ELEMENT_NM, CONN5_TERM_ELEMENT_TYPE, 
CONN6, CONN6_ORIG_ELEMENT_NM, CONN6_ORIG_ELEMENT_TYPE, CONN6_TERM_ELEMENT_NM,CONN6_TERM_ELEMENT_TYPE, 
CONN7, CONN7_ORIG_ELEMENT_NM, CONN7_ORIG_ELEMENT_TYPE, CONN7_TERM_ELEMENT_NM, CONN7_TERM_ELEMENT_TYPE,
CONN8, CONN8_ORIG_ELEMENT_NM, CONN8_ORIG_ELEMENT_TYPE, CONN8_TERM_ELEMENT_NM, CONN8_TERM_ELEMENT_TYPE,
CONN9, CONN8_ORIG_ELEMENT_NM, CONN9_ORIG_ELEMENT_TYPE, CONN9_TERM_ELEMENT_NM, CONN9_TERM_ELEMENT_TYPE,
RTRIM(REGEXP_SUBSTR(CONN10, '[^|]+', 1, 1), '|') CONN10,                  
(SELECT NS_COMP_NM                     
FROM NS_COMPONENT N                    
WHERE N.NS_COMP_ID = RTRIM(REGEXP_SUBSTR(CONN10, '[^|]+', 1, 2), '|'))                     CONN10_ORIG_ELEMENT_NM,                  
(SELECT NE_TYPE_NM FROM NE_TYPE NT, NETWORK_NODE NN, NS_COMPONENT NC                   
WHERE NT.NE_TYPE_ID = NN.NE_TYPE_ID AND NN.NETWORK_NODE_ID = NC.NETWORK_NODE_ID AND NC.NS_COMP_ID = RTRIM(REGEXP_SUBSTR(CONN10, '[^|]+', 1, 2), '|')) CONN10_ORIG_ELEMENT_TYPE,                  
(SELECT NS_COMP_NM FROM NS_COMPONENT N                    
WHERE N.NS_COMP_ID = RTRIM(REGEXP_SUBSTR(CONN10, '[^|]+', 1, 3), '|')) CONN10_TERM_ELEMENT_NM,                  
(SELECT NE_TYPE_NM FROM NE_TYPE NT, NETWORK_NODE NN, NS_COMPONENT NC                   
WHERE NT.NE_TYPE_ID = NN.NE_TYPE_ID AND NN.NETWORK_NODE_ID = NC.NETWORK_NODE_ID AND NC.NS_COMP_ID = RTRIM(REGEXP_SUBSTR(CONN10, '[^|]+', 1, 3), '|')) CONN10_TERM_ELEMENT_TYPEFROM 
(SELECT STATE, EVC_CKT_ID, EVC_CIRCUIT, CUSTOMER_NM, STATUS, ISSUE_STATUS, CIR, EVC_TYPE, CLASS_OF_SERVICE, "CoS", CE_VLAN_ID1,CE_VLAN_ID2, RUID_#1_S_VLAN_ID, 
RUID_#2_S_VLAN_ID,UNI_CKT_ID, UNI_CIRCUIT, ORIG_ELEMENT_NM, TERM_ELEMENT_NM, TERM_ELEMENT_TYPE, CONN2, CONN2_ORIG_ELEMENT_NM,CONN2_ORIG_ELEMENT_TYPE, 
CONN2_TERM_ELEMENT_NM, CONN2_TERM_ELEMENT_TYPE, CONN3, CONN3_ORIG_ELEMENT_NM,CONN3_ORIG_ELEMENT_TYPE, CONN3_TERM_ELEMENT_NM, CONN3_TERM_ELEMENT_TYPE, 
CONN4, CONN4_ORIG_ELEMENT_NM, CONN4_ORIG_ELEMENT_TYPE,CONN4_TERM_ELEMENT_NM, CONN4_TERM_ELEMENT_TYPE, CONN5, CONN5_ORIG_ELEMENT_NM, 
CONN5_ORIG_ELEMENT_TYPE,CONN5_TERM_ELEMENT_NM, CONN5_TERM_ELEMENT_TYPE, CONN6, CONN6_ORIG_ELEMENT_NM, CONN6_ORIG_ELEMENT_TYPE, CONN6_TERM_ELEMENT_NM,
CONN6_TERM_ELEMENT_TYPE, CONN7, CONN7_ORIG_ELEMENT_NM, CONN7_ORIG_ELEMENT_TYPE, CONN7_TERM_ELEMENT_NM, CONN7_TERM_ELEMENT_TYPE,CONN8, 
CONN8_ORIG_ELEMENT_NM, CONN8_ORIG_ELEMENT_TYPE, CONN8_TERM_ELEMENT_NM, CONN8_TERM_ELEMENT_TYPE,RTRIM(REGEXP_SUBSTR(CONN9, '[^|]+', 1, 1), '|') CONN9,                  
(SELECT NS_COMP_NM FROM NS_COMPONENT N    
WHERE N.NS_COMP_ID = RTRIM(REGEXP_SUBSTR(CONN9, '[^|]+', 1, 2), '|')) CONN9_ORIG_ELEMENT_NM,                  
(SELECT NE_TYPE_NM FROM NE_TYPE NT, NETWORK_NODE NN, NS_COMPONENT NC                   
WHERE NT.NE_TYPE_ID = NN.NE_TYPE_ID AND NN.NETWORK_NODE_ID = NC.NETWORK_NODE_ID AND NC.NS_COMP_ID = RTRIM(REGEXP_SUBSTR(CONN9, '[^|]+', 1, 2), '|')) CONN9_ORIG_ELEMENT_TYPE,                  
(SELECT NS_COMP_NM FROM NS_COMPONENT N                    
WHERE N.NS_COMP_ID = RTRIM(REGEXP_SUBSTR(CONN9, '[^|]+', 1, 3), '|')) CONN9_TERM_ELEMENT_NM,                  
(SELECT NE_TYPE_NM FROM NE_TYPE NT, NETWORK_NODE NN, NS_COMPONENT NC                   
WHERE NT.NE_TYPE_ID = NN.NE_TYPE_ID  AND NN.NETWORK_NODE_ID = NC.NETWORK_NODE_ID AND NC.NS_COMP_ID = RTRIM(REGEXP_SUBSTR(CONN9, '[^|]+', 1, 3), '|')) CONN9_TERM_ELEMENT_TYPE,                   
(SELECT C4.EXCHANGE_CARRIER_CIRCUIT_ID || '|' || NSC4.NS_COMP_ID_PARENT || '|' || NSC4.NS_COMP_ID_CHILD || '|' || C4.CIRCUIT_DESIGN_ID                    
FROM CIRCUIT C4, NS_CON_REL NS4, NS_CONNECTION NSC4                   
WHERE C4.CIRCUIT_DESIGN_ID = NS4.CIRCUIT_DESIGN_ID_PARENT AND NS4.CIRCUIT_DESIGN_ID_CHILD = EVC_CKT_ID  AND NS4.CIRCUIT_DESIGN_ID_PARENT = NSC4.CIRCUIT_DESIGN_ID AND C4.EXCHANGE_CARRIER_CIRCUIT_ID != UNI_CIRCUIT     
AND C4.CIRCUIT_DESIGN_ID != RTRIM(REGEXP_SUBSTR(CONN9, '[^|]+', 1, 4), '|') AND TRIM(C4.EXCHANGE_CARRIER_CIRCUIT_ID) != TRIM(CONN3)                     
AND TRIM(C4.EXCHANGE_CARRIER_CIRCUIT_ID) != TRIM(CONN2) AND TRIM(C4.EXCHANGE_CARRIER_CIRCUIT_ID) != TRIM(CONN5) AND TRIM(C4.EXCHANGE_CARRIER_CIRCUIT_ID) != TRIM(CONN6)                     
AND TRIM(C4.EXCHANGE_CARRIER_CIRCUIT_ID) != TRIM(CONN8) AND TRIM(C4.EXCHANGE_CARRIER_CIRCUIT_ID) != TRIM(UNI_CIRCUIT) AND (((NSC4.NS_COMP_ID_PARENT = RTRIM(REGEXP_SUBSTR(CONN9, '[^|]+', 1, 2), '|')                            
AND ROWNUM = 1)  OR NSC4.NS_COMP_ID_CHILD = RTRIM(REGEXP_SUBSTR(CONN9, '[^|]+', 1, 2), '|')  
AND ROWNUM = 1)  OR (NSC4.NS_COMP_ID_PARENT = RTRIM(REGEXP_SUBSTR(CONN9, '[^|]+', 1, 3), '|')                          
AND ROWNUM = 1)  OR NSC4.NS_COMP_ID_CHILD = RTRIM(REGEXP_SUBSTR(CONN9, '[^|]+', 1, 3), '|')                        
AND ROWNUM = 1)  AND NS4.NS_CON_REL_STATUS_CD <> '4') CONN10FROM 
(SELECT STATE, EVC_CKT_ID, EVC_CIRCUIT, CUSTOMER_NM, STATUS, ISSUE_STATUS, CIR, EVC_TYPE, CLASS_OF_SERVICE, "CoS", CE_VLAN_ID1,CE_VLAN_ID2, RUID_#1_S_VLAN_ID, 
RUID_#2_S_VLAN_ID,UNI_CKT_ID, UNI_CIRCUIT, ORIG_ELEMENT_NM, TERM_ELEMENT_NM, TERM_ELEMENT_TYPE, CONN2, CONN2_ORIG_ELEMENT_NM,CONN2_ORIG_ELEMENT_TYPE, 
CONN2_TERM_ELEMENT_NM, CONN2_TERM_ELEMENT_TYPE, CONN3, CONN3_ORIG_ELEMENT_NM,CONN3_ORIG_ELEMENT_TYPE, CONN3_TERM_ELEMENT_NM, CONN3_TERM_ELEMENT_TYPE, CONN4, 
CONN4_ORIG_ELEMENT_NM, CONN4_ORIG_ELEMENT_TYPE,CONN4_TERM_ELEMENT_NM, CONN4_TERM_ELEMENT_TYPE, CONN5, CONN5_ORIG_ELEMENT_NM, CONN5_ORIG_ELEMENT_TYPE,CONN5_TERM_ELEMENT_NM, 
CONN5_TERM_ELEMENT_TYPE, CONN6, CONN6_ORIG_ELEMENT_NM, CONN6_ORIG_ELEMENT_TYPE, CONN6_TERM_ELEMENT_NM,CONN6_TERM_ELEMENT_TYPE, CONN7, CONN7_ORIG_ELEMENT_NM, 
CONN7_ORIG_ELEMENT_TYPE, CONN7_TERM_ELEMENT_NM, CONN7_TERM_ELEMENT_TYPE,RTRIM(REGEXP_SUBSTR(CONN8, '[^|]+', 1, 1), '|') CONN8,                  
(SELECT NS_COMP_NM FROM NS_COMPONENT N                    
WHERE N.NS_COMP_ID = RTRIM(REGEXP_SUBSTR(CONN8, '[^|]+', 1, 2), '|')) CONN8_ORIG_ELEMENT_NM,                  
(SELECT NE_TYPE_NM FROM NE_TYPE NT, NETWORK_NODE NN, NS_COMPONENT NC                   
WHERE NT.NE_TYPE_ID = NN.NE_TYPE_ID AND NN.NETWORK_NODE_ID = NC.NETWORK_NODE_ID                   
AND NC.NS_COMP_ID = RTRIM(REGEXP_SUBSTR(CONN8, '[^|]+', 1, 2), '|')) CONN8_ORIG_ELEMENT_TYPE,                  
(SELECT NS_COMP_NM FROM NS_COMPONENT N                    
WHERE N.NS_COMP_ID = RTRIM(REGEXP_SUBSTR(CONN8, '[^|]+', 1, 3), '|'))  CONN8_TERM_ELEMENT_NM,                  
(SELECT NE_TYPE_NM FROM NE_TYPE NT, NETWORK_NODE NN, NS_COMPONENT NC                   
WHERE NT.NE_TYPE_ID = NN.NE_TYPE_ID AND   NN.NETWORK_NODE_ID = NC.NETWORK_NODE_ID AND NC.NS_COMP_ID = RTRIM(REGEXP_SUBSTR(CONN8, '[^|]+', 1, 3), '|')) CONN8_TERM_ELEMENT_TYPE,                   
(SELECT C4.EXCHANGE_CARRIER_CIRCUIT_ID || '|' || NSC4.NS_COMP_ID_PARENT || '|' || NSC4.NS_COMP_ID_CHILD || '|' || C4.CIRCUIT_DESIGN_ID                    
FROM CIRCUIT C4, NS_CON_REL NS4, NS_CONNECTION NSC4    
WHERE C4.CIRCUIT_DESIGN_ID = NS4.CIRCUIT_DESIGN_ID_PARENT AND NS4.CIRCUIT_DESIGN_ID_CHILD = EVC_CKT_ID AND NS4.CIRCUIT_DESIGN_ID_PARENT = NSC4.CIRCUIT_DESIGN_ID  
AND C4.EXCHANGE_CARRIER_CIRCUIT_ID != UNI_CIRCUIT  AND C4.CIRCUIT_DESIGN_ID != RTRIM(REGEXP_SUBSTR(CONN8, '[^|]+', 1, 4), '|') AND TRIM(C4.EXCHANGE_CARRIER_CIRCUIT_ID) != TRIM(CONN3)                     
AND TRIM(C4.EXCHANGE_CARRIER_CIRCUIT_ID) != TRIM(CONN2) AND TRIM(C4.EXCHANGE_CARRIER_CIRCUIT_ID) != TRIM(CONN5) AND TRIM(C4.EXCHANGE_CARRIER_CIRCUIT_ID) != TRIM(CONN6) 
AND TRIM(C4.EXCHANGE_CARRIER_CIRCUIT_ID) != TRIM(CONN7) AND TRIM(C4.EXCHANGE_CARRIER_CIRCUIT_ID) != TRIM(UNI_CIRCUIT) 
AND (((NSC4.NS_COMP_ID_PARENT = RTRIM(REGEXP_SUBSTR(CONN8, '[^|]+', 1, 2), '|')                            
AND ROWNUM = 1) OR NSC4.NS_COMP_ID_CHILD = RTRIM(REGEXP_SUBSTR(CONN8, '[^|]+', 1, 2), '|')                           
AND ROWNUM = 1) OR (NSC4.NS_COMP_ID_PARENT = RTRIM(REGEXP_SUBSTR(CONN8, '[^|]+', 1, 3), '|')                          
AND ROWNUM = 1) OR NSC4.NS_COMP_ID_CHILD = RTRIM(REGEXP_SUBSTR(CONN8, '[^|]+', 1, 3), '|')                        
AND ROWNUM = 1) AND NS4.NS_CON_REL_STATUS_CD <> '4')  CONN9FROM 
(SELECT STATE, EVC_CKT_ID, EVC_CIRCUIT, CUSTOMER_NM, STATUS, ISSUE_STATUS, CIR, EVC_TYPE, CLASS_OF_SERVICE, "CoS", CE_VLAN_ID1,CE_VLAN_ID2, RUID_#1_S_VLAN_ID, 
RUID_#2_S_VLAN_ID,UNI_CKT_ID, UNI_CIRCUIT, ORIG_ELEMENT_NM, TERM_ELEMENT_NM, TERM_ELEMENT_TYPE, CONN2, CONN2_ORIG_ELEMENT_NM,CONN2_ORIG_ELEMENT_TYPE, 
CONN2_TERM_ELEMENT_NM, CONN2_TERM_ELEMENT_TYPE, CONN3, CONN3_ORIG_ELEMENT_NM,CONN3_ORIG_ELEMENT_TYPE, CONN3_TERM_ELEMENT_NM, CONN3_TERM_ELEMENT_TYPE, CONN4, 
CONN4_ORIG_ELEMENT_NM, CONN4_ORIG_ELEMENT_TYPE,CONN4_TERM_ELEMENT_NM, CONN4_TERM_ELEMENT_TYPE, CONN5, CONN5_ORIG_ELEMENT_NM, CONN5_ORIG_ELEMENT_TYPE,
CONN5_TERM_ELEMENT_NM, CONN5_TERM_ELEMENT_TYPE, CONN6, CONN6_ORIG_ELEMENT_NM, CONN6_ORIG_ELEMENT_TYPE, CONN6_TERM_ELEMENT_NM,CONN6_TERM_ELEMENT_TYPE,
RTRIM(REGEXP_SUBSTR(CONN7, '[^|]+', 1, 1), '|') CONN7,                  
(SELECT NS_COMP_NM  FROM NS_COMPONENT N                    
WHERE N.NS_COMP_ID = RTRIM(REGEXP_SUBSTR(CONN7, '[^|]+', 1, 2), '|')) CONN7_ORIG_ELEMENT_NM,                  
(SELECT NE_TYPE_NM FROM NE_TYPE NT, NETWORK_NODE NN, NS_COMPONENT NC                   
WHERE NT.NE_TYPE_ID = NN.NE_TYPE_ID AND NN.NETWORK_NODE_ID = NC.NETWORK_NODE_ID AND NC.NS_COMP_ID = RTRIM(REGEXP_SUBSTR(CONN7, '[^|]+', 1, 2), '|')) CONN7_ORIG_ELEMENT_TYPE,                  
(SELECT NS_COMP_NM FROM NS_COMPONENT N WHERE N.NS_COMP_ID = RTRIM(REGEXP_SUBSTR(CONN7, '[^|]+', 1, 3), '|')) CONN7_TERM_ELEMENT_NM,                  
(SELECT NE_TYPE_NM FROM NE_TYPE NT, NETWORK_NODE NN, NS_COMPONENT NC 
WHERE NT.NE_TYPE_ID = NN.NE_TYPE_ID  AND NN.NETWORK_NODE_ID = NC.NETWORK_NODE_ID AND NC.NS_COMP_ID = RTRIM(REGEXP_SUBSTR(CONN7, '[^|]+', 1, 3), '|')) CONN7_TERM_ELEMENT_TYPE,                   
(SELECT C4.EXCHANGE_CARRIER_CIRCUIT_ID || '|' || NSC4.NS_COMP_ID_PARENT || '|' || NSC4.NS_COMP_ID_CHILD || '|' || C4.CIRCUIT_DESIGN_ID                    
FROM CIRCUIT C4, NS_CON_REL NS4, NS_CONNECTION NSC4                   
WHERE C4.CIRCUIT_DESIGN_ID = NS4.CIRCUIT_DESIGN_ID_PARENT AND NS4.CIRCUIT_DESIGN_ID_CHILD = EVC_CKT_ID AND NS4.CIRCUIT_DESIGN_ID_PARENT = NSC4.CIRCUIT_DESIGN_ID                     
AND C4.EXCHANGE_CARRIER_CIRCUIT_ID != UNI_CIRCUIT AND C4.CIRCUIT_DESIGN_ID != RTRIM(REGEXP_SUBSTR(CONN7, '[^|]+', 1, 4), '|') AND TRIM(C4.EXCHANGE_CARRIER_CIRCUIT_ID) != TRIM(CONN3)                     
AND TRIM(C4.EXCHANGE_CARRIER_CIRCUIT_ID) != TRIM(CONN2) AND TRIM(C4.EXCHANGE_CARRIER_CIRCUIT_ID) != TRIM(CONN5) AND TRIM(C4.EXCHANGE_CARRIER_CIRCUIT_ID) != TRIM(CONN6)                     
AND TRIM(C4.EXCHANGE_CARRIER_CIRCUIT_ID) != TRIM(UNI_CIRCUIT) AND (((NSC4.NS_COMP_ID_PARENT = RTRIM(REGEXP_SUBSTR(CONN7, '[^|]+', 1, 2), '|')                            
AND ROWNUM = 1) OR NSC4.NS_COMP_ID_CHILD = RTRIM(REGEXP_SUBSTR(CONN7, '[^|]+', 1, 2), '|')                          
AND ROWNUM = 1) OR (NSC4.NS_COMP_ID_PARENT = RTRIM(REGEXP_SUBSTR(CONN7, '[^|]+', 1, 3), '|')                          
AND ROWNUM = 1) OR NSC4.NS_COMP_ID_CHILD = RTRIM(REGEXP_SUBSTR(CONN7, '[^|]+', 1, 3), '|')                        
AND ROWNUM = 1) AND NS4.NS_CON_REL_STATUS_CD <> '4') CONN8FROM  
(SELECT STATE, EVC_CKT_ID, EVC_CIRCUIT, CUSTOMER_NM, STATUS, ISSUE_STATUS, CIR, EVC_TYPE, CLASS_OF_SERVICE, "CoS", CE_VLAN_ID1,CE_VLAN_ID2, RUID_#1_S_VLAN_ID, RUID_#2_S_VLAN_ID,
UNI_CKT_ID, UNI_CIRCUIT, ORIG_ELEMENT_NM, TERM_ELEMENT_NM, TERM_ELEMENT_TYPE, CONN2, CONN2_ORIG_ELEMENT_NM,CONN2_ORIG_ELEMENT_TYPE, CONN2_TERM_ELEMENT_NM, CONN2_TERM_ELEMENT_TYPE, 
CONN3, CONN3_ORIG_ELEMENT_NM,CONN3_ORIG_ELEMENT_TYPE, CONN3_TERM_ELEMENT_NM, CONN3_TERM_ELEMENT_TYPE, CONN4, CONN4_ORIG_ELEMENT_NM, CONN4_ORIG_ELEMENT_TYPE,CONN4_TERM_ELEMENT_NM, 
CONN4_TERM_ELEMENT_TYPE, CONN5, CONN5_ORIG_ELEMENT_NM, CONN5_ORIG_ELEMENT_TYPE,CONN5_TERM_ELEMENT_NM, CONN5_TERM_ELEMENT_TYPE, RTRIM(REGEXP_SUBSTR(CONN6, '[^|]+', 1, 1), '|') CONN6,                  
(SELECT NS_COMP_NM FROM NS_COMPONENT N                    
WHERE N.NS_COMP_ID = RTRIM(REGEXP_SUBSTR(CONN6, '[^|]+', 1, 2), '|')) CONN6_ORIG_ELEMENT_NM, 
(SELECT NE_TYPE_NM FROM NE_TYPE NT, NETWORK_NODE NN, NS_COMPONENT NC                   
WHERE NT.NE_TYPE_ID = NN.NE_TYPE_ID AND NN.NETWORK_NODE_ID = NC.NETWORK_NODE_ID AND NC.NS_COMP_ID = RTRIM(REGEXP_SUBSTR(CONN6, '[^|]+', 1, 2), '|')) CONN6_ORIG_ELEMENT_TYPE,                  
(SELECT NS_COMP_NM FROM NS_COMPONENT N WHERE N.NS_COMP_ID = RTRIM(REGEXP_SUBSTR(CONN6, '[^|]+', 1, 3), '|')) CONN6_TERM_ELEMENT_NM,                  
(SELECT NE_TYPE_NM FROM NE_TYPE NT, NETWORK_NODE NN, NS_COMPONENT NC                   
WHERE NT.NE_TYPE_ID = NN.NE_TYPE_ID AND NN.NETWORK_NODE_ID = NC.NETWORK_NODE_ID AND NC.NS_COMP_ID = RTRIM(REGEXP_SUBSTR(CONN6, '[^|]+', 1, 3), '|')) CONN6_TERM_ELEMENT_TYPE,                   
(SELECT C4.EXCHANGE_CARRIER_CIRCUIT_ID || '|' || NSC4.NS_COMP_ID_PARENT || '|' || NSC4.NS_COMP_ID_CHILD || '|' || C4.CIRCUIT_DESIGN_ID                    
FROM CIRCUIT C4, NS_CON_REL NS4, NS_CONNECTION NSC4 WHERE C4.CIRCUIT_DESIGN_ID = NS4.CIRCUIT_DESIGN_ID_PARENT AND NS4.CIRCUIT_DESIGN_ID_CHILD = EVC_CKT_ID                     
AND NS4.CIRCUIT_DESIGN_ID_PARENT = NSC4.CIRCUIT_DESIGN_ID AND C4.EXCHANGE_CARRIER_CIRCUIT_ID != UNI_CIRCUIT AND C4.CIRCUIT_DESIGN_ID != RTRIM(REGEXP_SUBSTR(CONN6, '[^|]+', 1, 4), '|')                     
AND TRIM(C4.EXCHANGE_CARRIER_CIRCUIT_ID) != TRIM(CONN4) AND TRIM(C4.EXCHANGE_CARRIER_CIRCUIT_ID) != TRIM(CONN3) AND TRIM(C4.EXCHANGE_CARRIER_CIRCUIT_ID) != TRIM(CONN2)                     
AND TRIM(C4.EXCHANGE_CARRIER_CIRCUIT_ID) != TRIM(CONN5) AND TRIM(C4.EXCHANGE_CARRIER_CIRCUIT_ID) != TRIM(UNI_CIRCUIT) AND (((((((NSC4.NS_COMP_ID_PARENT = RTRIM(REGEXP_SUBSTR(CONN6, '[^|]+', 1, 2), '|')      
AND ROWNUM = 1) OR NSC4.NS_COMP_ID_CHILD = RTRIM(REGEXP_SUBSTR(CONN6, '[^|]+', 1, 2), '|')                           
AND ROWNUM = 1)) OR (NSC4.NS_COMP_ID_PARENT = RTRIM(REGEXP_SUBSTR(CONN6, '[^|]+', 1, 3), '|')                          
AND ROWNUM = 1) OR NSC4.NS_COMP_ID_CHILD = RTRIM(REGEXP_SUBSTR(CONN6, '[^|]+', 1, 3), '|'))                        
AND ROWNUM = 1) AND NS4.NS_CON_REL_STATUS_CD <> '4')))  CONN7FROM 
(SELECT STATE, EVC_CKT_ID, EVC_CIRCUIT, CUSTOMER_NM, STATUS, ISSUE_STATUS, CIR, EVC_TYPE, CLASS_OF_SERVICE, "CoS", CE_VLAN_ID1,CE_VLAN_ID2, RUID_#1_S_VLAN_ID, RUID_#2_S_VLAN_ID,
UNI_CKT_ID, UNI_CIRCUIT, ORIG_ELEMENT_NM, TERM_ELEMENT_NM, TERM_ELEMENT_TYPE, CONN2, CONN2_ORIG_ELEMENT_NM,CONN2_ORIG_ELEMENT_TYPE, CONN2_TERM_ELEMENT_NM, CONN2_TERM_ELEMENT_TYPE, 
CONN3, CONN3_ORIG_ELEMENT_NM,CONN3_ORIG_ELEMENT_TYPE, CONN3_TERM_ELEMENT_NM, CONN3_TERM_ELEMENT_TYPE, CONN4, CONN4_ORIG_ELEMENT_NM, CONN4_ORIG_ELEMENT_TYPE,CONN4_TERM_ELEMENT_NM, 
CONN4_TERM_ELEMENT_TYPE,RTRIM(REGEXP_SUBSTR(CONN5, '[^|]+', 1, 1), '|') CONN5,                  
(SELECT NS_COMP_NM FROM NS_COMPONENT N WHERE N.NS_COMP_ID = RTRIM(REGEXP_SUBSTR(CONN5, '[^|]+', 1, 2), '|')) CONN5_ORIG_ELEMENT_NM,                  
(SELECT NE_TYPE_NM FROM NE_TYPE NT, NETWORK_NODE NN, NS_COMPONENT NC                   
WHERE NT.NE_TYPE_ID = NN.NE_TYPE_ID AND NN.NETWORK_NODE_ID = NC.NETWORK_NODE_ID AND NC.NS_COMP_ID = RTRIM(REGEXP_SUBSTR(CONN5, '[^|]+', 1, 2), '|')) CONN5_ORIG_ELEMENT_TYPE,                  
(SELECT NS_COMP_NM FROM NS_COMPONENT N WHERE N.NS_COMP_ID = RTRIM(REGEXP_SUBSTR(CONN5, '[^|]+', 1, 3), '|')) CONN5_TERM_ELEMENT_NM,                  
(SELECT NE_TYPE_NM FROM NE_TYPE NT, NETWORK_NODE NN, NS_COMPONENT NC                   
WHERE NT.NE_TYPE_ID = NN.NE_TYPE_ID AND NN.NETWORK_NODE_ID = NC.NETWORK_NODE_ID AND NC.NS_COMP_ID = RTRIM(REGEXP_SUBSTR(CONN5, '[^|]+', 1, 3), '|')) CONN5_TERM_ELEMENT_TYPE,                  
(SELECT C4.EXCHANGE_CARRIER_CIRCUIT_ID || '|' || NSC4.NS_COMP_ID_PARENT || '|' || NSC4.NS_COMP_ID_CHILD || '|' || C4.CIRCUIT_DESIGN_ID                    
FROM CIRCUIT C4, NS_CON_REL NS4, NS_CONNECTION NSC4                   
WHERE C4.CIRCUIT_DESIGN_ID = NS4.CIRCUIT_DESIGN_ID_PARENT AND NS4.CIRCUIT_DESIGN_ID_CHILD = EVC_CKT_ID AND NS4.CIRCUIT_DESIGN_ID_PARENT = NSC4.CIRCUIT_DESIGN_ID                     
AND C4.EXCHANGE_CARRIER_CIRCUIT_ID != UNI_CIRCUIT AND C4.CIRCUIT_DESIGN_ID != RTRIM(REGEXP_SUBSTR(CONN5, '[^|]+', 1, 4), '|') AND TRIM(C4.EXCHANGE_CARRIER_CIRCUIT_ID) != TRIM(CONN4)                     
AND TRIM(C4.EXCHANGE_CARRIER_CIRCUIT_ID) != TRIM(CONN3) AND TRIM(C4.EXCHANGE_CARRIER_CIRCUIT_ID) != TRIM(CONN2) AND TRIM(C4.EXCHANGE_CARRIER_CIRCUIT_ID) != TRIM(UNI_CIRCUIT)                     
AND (((((((NSC4.NS_COMP_ID_PARENT = RTRIM(REGEXP_SUBSTR(CONN5, '[^|]+', 1, 2), '|')                            
AND ROWNUM = 1) OR NSC4.NS_COMP_ID_CHILD = RTRIM(REGEXP_SUBSTR(CONN5, '[^|]+', 1, 2), '|')                           
AND ROWNUM = 1)) OR (NSC4.NS_COMP_ID_PARENT = RTRIM(REGEXP_SUBSTR(CONN5, '[^|]+', 1, 3), '|')                          
AND ROWNUM = 1) OR NSC4.NS_COMP_ID_CHILD = RTRIM(REGEXP_SUBSTR(CONN5, '[^|]+', 1, 3), '|'))                        
AND ROWNUM = 1) AND NS4.NS_CON_REL_STATUS_CD <> '4')))  CONN6FROM 
(SELECT DISTINCT STATE, EVC_CKT_ID, EVC_CIRCUIT, CUSTOMER_NM, STATUS, ISSUE_STATUS, CIR, EVC_TYPE, CLASS_OF_SERVICE, "CoS", CE_VLAN_ID1, CE_VLAN_ID2, RUID_#1_S_VLAN_ID, RUID_#2_S_VLAN_ID,
UNI_CKT_ID, UNI_CIRCUIT, ORIG_ELEMENT_NM, TERM_ELEMENT_NM,                  
(SELECT NE_TYPE_NM FROM NE_TYPE NT, NETWORK_NODE NN, NS_COMPONENT NC   
WHERE NT.NE_TYPE_ID = NN.NE_TYPE_ID AND NN.NETWORK_NODE_ID = NC.NETWORK_NODE_ID AND NC.NS_COMP_ID = TERM_ELEMENT_ID) TERM_ELEMENT_TYPE, CONN2, CONN2_ORIG_ELEMENT_NM,                  
(SELECT NE_TYPE_NM FROM NE_TYPE NT, NETWORK_NODE NN, NS_COMPONENT NC                   
WHERE NT.NE_TYPE_ID = NN.NE_TYPE_ID AND NN.NETWORK_NODE_ID = NC.NETWORK_NODE_ID AND NC.NS_COMP_ID = CONN2_ORIG_ELEMENT_ID) CONN2_ORIG_ELEMENT_TYPE, CONN2_TERM_ELEMENT_NM,                  
(SELECT NE_TYPE_NM FROM NE_TYPE NT, NETWORK_NODE NN, NS_COMPONENT NC                   
WHERE NT.NE_TYPE_ID = NN.NE_TYPE_ID  AND NN.NETWORK_NODE_ID = NC.NETWORK_NODE_ID AND NC.NS_COMP_ID = CONN2_TERM_ELEMENT_ID) CONN2_TERM_ELEMENT_TYPE,                  
--CONN2_CKT_XREF,                  CONN3,                  CONN3_ORIG_ELEMENT_NM,                  (SELECT NE_TYPE_NM FROM NE_TYPE NT,                                          NETWORK_NODE NN,                                          NS_COMPONENT NC                   WHERE NT.NE_TYPE_ID = NN.NE_TYPE_ID                   AND   NN.NETWORK_NODE_ID = NC.NETWORK_NODE_ID                   AND NC.NS_COMP_ID = CONN3_ORIG_ELEMENT_ID) CONN3_ORIG_ELEMENT_TYPE,                  CONN3_TERM_ELEMENT_NM,                  (SELECT NE_TYPE_NM FROM NE_TYPE NT,                                          NETWORK_NODE NN,                                          NS_COMPONENT NC                   WHERE NT.NE_TYPE_ID = NN.NE_TYPE_ID                   AND   NN.NETWORK_NODE_ID = NC.NETWORK_NODE_ID                   AND NC.NS_COMP_ID = CONN3_TERM_ELEMENT_ID) CONN3_TERM_ELEMENT_TYPE,                  --CONN3_CKT_XREF,                  RTRIM(REGEXP_SUBSTR(CONN4, '[^|]+', 1, 1), '|') CONN4,                  (SELECT NS_COMP_NM                     FROM NS_COMPONENT N                    WHERE N.NS_COMP_ID = RTRIM(REGEXP_SUBSTR(CONN4, '[^|]+', 1, 2), '|'))                     CONN4_ORIG_ELEMENT_NM,                  (SELECT NE_TYPE_NM FROM NE_TYPE NT,                                          NETWORK_NODE NN,                                          NS_COMPONENT NC                   WHERE NT.NE_TYPE_ID = NN.NE_TYPE_ID                   AND   NN.NETWORK_NODE_ID = NC.NETWORK_NODE_ID                   AND NC.NS_COMP_ID = RTRIM(REGEXP_SUBSTR(CONN4, '[^|]+', 1, 2), '|')) CONN4_ORIG_ELEMENT_TYPE,                  (SELECT NS_COMP_NM                     FROM NS_COMPONENT N                    WHERE N.NS_COMP_ID = RTRIM(REGEXP_SUBSTR(CONN4, '[^|]+', 1, 3), '|'))                     CONN4_TERM_ELEMENT_NM,                  (SELECT NE_TYPE_NM FROM NE_TYPE NT,                                          NETWORK_NODE NN,                                          NS_COMPONENT NC                   WHERE NT.NE_TYPE_ID = NN.NE_TYPE_ID                   AND   NN.NETWORK_NODE_ID = NC.NETWORK_NODE_ID                   AND NC.NS_COMP_ID = RTRIM(REGEXP_SUBSTR(CONN4, '[^|]+', 1, 3), '|')) CONN4_TERM_ELEMENT_TYPE,                   (SELECT C4.EXCHANGE_CARRIER_CIRCUIT_ID || '|' || NSC4.NS_COMP_ID_PARENT || '|' || NSC4.NS_COMP_ID_CHILD || '|' || C4.CIRCUIT_DESIGN_ID                    FROM CIRCUIT C4,                         NS_CON_REL NS4,                         NS_CONNECTION NSC4                   WHERE C4.CIRCUIT_DESIGN_ID = NS4.CIRCUIT_DESIGN_ID_PARENT                     AND NS4.CIRCUIT_DESIGN_ID_CHILD = EVC_CKT_ID                     AND NS4.CIRCUIT_DESIGN_ID_PARENT = NSC4.CIRCUIT_DESIGN_ID                     AND C4.EXCHANGE_CARRIER_CIRCUIT_ID != UNI_CIRCUIT                     AND C4.CIRCUIT_DESIGN_ID != RTRIM(REGEXP_SUBSTR(CONN4, '[^|]+', 1, 4), '|')                     AND TRIM(C4.EXCHANGE_CARRIER_CIRCUIT_ID) != TRIM(CONN3)                     AND TRIM(C4.EXCHANGE_CARRIER_CIRCUIT_ID) != TRIM(CONN2)                     AND TRIM(C4.EXCHANGE_CARRIER_CIRCUIT_ID) != TRIM(UNI_CIRCUIT)                     AND (((((((NSC4.NS_COMP_ID_PARENT = RTRIM(REGEXP_SUBSTR(CONN4, '[^|]+', 1, 2), '|')                            AND ROWNUM = 1)                            OR NSC4.NS_COMP_ID_CHILD = RTRIM(REGEXP_SUBSTR(CONN4, '[^|]+', 1, 2), '|')                           AND ROWNUM = 1))                          OR (NSC4.NS_COMP_ID_PARENT = RTRIM(REGEXP_SUBSTR(CONN4, '[^|]+', 1, 3), '|')                          AND ROWNUM = 1)                          OR NSC4.NS_COMP_ID_CHILD = RTRIM(REGEXP_SUBSTR(CONN4, '[^|]+', 1, 3), '|'))                        AND ROWNUM = 1)                       AND NS4.NS_CON_REL_STATUS_CD <> '4')))                    CONN5    FROM (SELECT STATE,                 EVC_CKT_ID,                 EVC_CIRCUIT,                 CUSTOMER_NM,                 STATUS,                 ISSUE_STATUS,                 CIR,                 EVC_TYPE,                 CLASS_OF_SERVICE,                 "CoS",                 CE_VLAN_ID1,                 CE_VLAN_ID2,                 RUID_#1_S_VLAN_ID,                 RUID_#2_S_VLAN_ID,                 UNI_CKT_ID,                 UNI_CIRCUIT,                 ORIG_ELEMENT_NM,                 TERM_ELEMENT_ID,                 TERM_ELEMENT_NM,                 CONN2,                 CONN2_ORIG_ELEMENT_NM,                 CONN2_ORIG_ELEMENT_ID,                 CONN2_TERM_ELEMENT_NM,                 CONN2_TERM_ELEMENT_ID,                 RTRIM(REGEXP_SUBSTR(CONN3, '[^|]+', 1, 1), '|') CONN3,                 (SELECT NS_COMP_NM                    FROM NS_COMPONENT N                   WHERE N.NS_COMP_ID = RTRIM(REGEXP_SUBSTR(CONN3, '[^|]+', 1, 2), '|'))                    CONN3_ORIG_ELEMENT_NM,                    RTRIM(REGEXP_SUBSTR(CONN3, '[^|]+', 1, 2), '|') CONN3_ORIG_ELEMENT_ID,                 (SELECT NS_COMP_NM                    FROM NS_COMPONENT N                   WHERE N.NS_COMP_ID = RTRIM(REGEXP_SUBSTR(CONN3, '[^|]+', 1, 3), '|'))                    CONN3_TERM_ELEMENT_NM,                    RTRIM(REGEXP_SUBSTR(CONN3, '[^|]+', 1, 3), '|') CONN3_TERM_ELEMENT_ID,                 (SELECT C4.EXCHANGE_CARRIER_CIRCUIT_ID || '|' || NSC4.NS_COMP_ID_PARENT || '|' || NSC4.NS_COMP_ID_CHILD || '|' || C4.CIRCUIT_DESIGN_ID                    FROM CIRCUIT C4,                         NS_CON_REL NS4,                         NS_CONNECTION NSC4                   WHERE C4.CIRCUIT_DESIGN_ID = NS4.CIRCUIT_DESIGN_ID_PARENT                     AND NS4.CIRCUIT_DESIGN_ID_CHILD = EVC_CKT_ID                     AND NS4.CIRCUIT_DESIGN_ID_PARENT = NSC4.CIRCUIT_DESIGN_ID                     AND C4.EXCHANGE_CARRIER_CIRCUIT_ID != UNI_CIRCUIT                     AND C4.CIRCUIT_DESIGN_ID != RTRIM(REGEXP_SUBSTR(CONN3, '[^|]+', 1, 4), '|')                     AND TRIM(C4.EXCHANGE_CARRIER_CIRCUIT_ID) != TRIM(CONN2)                     AND TRIM(C4.EXCHANGE_CARRIER_CIRCUIT_ID) != TRIM(UNI_CIRCUIT)                     AND (((((((NSC4.NS_COMP_ID_PARENT = RTRIM(REGEXP_SUBSTR(CONN3, '[^|]+', 1, 2), '|')                            AND ROWNUM = 1)                            OR NSC4.NS_COMP_ID_CHILD = RTRIM(REGEXP_SUBSTR(CONN3, '[^|]+', 1, 2), '|')                           AND ROWNUM = 1))                          OR (NSC4.NS_COMP_ID_PARENT = RTRIM(REGEXP_SUBSTR(CONN3, '[^|]+', 1, 3), '|')                          AND ROWNUM = 1)                          OR NSC4.NS_COMP_ID_CHILD = RTRIM(REGEXP_SUBSTR(CONN3, '[^|]+', 1, 3), '|'))                        AND ROWNUM = 1)                       AND NS4.NS_CON_REL_STATUS_CD <> '4')))                    CONN4            FROM (SELECT DISTINCT                         STATE,                         EVC_CKT_ID,                         EVC_CIRCUIT,                         CUSTOMER_NM,                         STATUS,                         ISSUE_STATUS,                         CIR,                         EVC_TYPE,                         CLASS_OF_SERVICE,                         "CoS",                         CE_VLAN_ID1,                         CE_VLAN_ID2,                         RUID_#1_S_VLAN_ID,                         RUID_#2_S_VLAN_ID,                         UNI_CKT_ID,                         UNI_CIRCUIT,                         ORIG_ELEMENT_NM,                         TERM_ELEMENT_ID,                         TERM_ELEMENT_NM,                         RTRIM(REGEXP_SUBSTR(CONN2, '[^|]+', 1, 1), '|') CONN2,                         (SELECT NS_COMP_NM                            FROM NS_COMPONENT N                           WHERE N.NS_COMP_ID = RTRIM(REGEXP_SUBSTR(CONN2, '[^|]+', 1, 2), '|'))                            CONN2_ORIG_ELEMENT_NM,                            RTRIM(REGEXP_SUBSTR(CONN2, '[^|]+', 1, 2), '|') CONN2_ORIG_ELEMENT_ID,                         (SELECT NS_COMP_NM                            FROM NS_COMPONENT N                           WHERE N.NS_COMP_ID = RTRIM(REGEXP_SUBSTR(CONN2, '[^|]+', 1, 3), '|'))                            CONN2_TERM_ELEMENT_NM,                         RTRIM(REGEXP_SUBSTR(CONN2, '[^|]+', 1, 3), '|') CONN2_TERM_ELEMENT_ID,                         (SELECT C3.EXCHANGE_CARRIER_CIRCUIT_ID || '|' || NSC3.NS_COMP_ID_PARENT || '|' || NSC3.NS_COMP_ID_CHILD || '|' || C3.                                 CIRCUIT_DESIGN_ID                            FROM CIRCUIT C3,                                 NS_CON_REL NS3,                                 NS_CONNECTION NSC3                           WHERE C3.CIRCUIT_DESIGN_ID = NS3.CIRCUIT_DESIGN_ID_PARENT                             AND NS3.CIRCUIT_DESIGN_ID_CHILD = EVC_CKT_ID                             AND NS3.CIRCUIT_DESIGN_ID_PARENT = NSC3.CIRCUIT_DESIGN_ID                             AND C3.CIRCUIT_DESIGN_ID != RTRIM(REGEXP_SUBSTR(CONN2, '[^|]+', 1, 4), '|')                             AND TRIM(C3.EXCHANGE_CARRIER_CIRCUIT_ID) != TRIM(UNI_CIRCUIT)                             AND (((((((NSC3.NS_COMP_ID_PARENT = RTRIM(REGEXP_SUBSTR(CONN2, '[^|]+', 1, 2), '|')                                    AND ROWNUM = 1)                                    OR NSC3.NS_COMP_ID_CHILD = RTRIM(REGEXP_SUBSTR(CONN2, '[^|]+', 1, 2), '|')                                   AND ROWNUM = 1))                                  OR (NSC3.NS_COMP_ID_PARENT = RTRIM(REGEXP_SUBSTR(CONN2, '[^|]+', 1, 3), '|')                                  AND ROWNUM = 1)                             
