SELECT BAN, ACNA, CUSTOMER, ADDRESS, CITY, STATE, LATA, EVC_CKR, PNUM,  
ETHERNET_READY_DT, LAST_ORDER_NO, LAST_COMP_DT,  ACT, EVC_BDW, EVC_LEVEL, PRODUCT, HBE_CIRCUIT,
EVC_DESIGN_ID, EVC, UNI, NNI, EVC_CKT2, UNI_CKT2, NNI_CKT2,
EVC_CKT_CLEAN, UNI_CKT_CLEAN, NNI_CKT_CLEAN, 
UNI_DESIGN_ID, UNI_STATUS, UNI_CLLI, UNI_LOC, UNI_H_COORD, UNI_V_COORD, UNI_IP,
NNI_DESIGN_ID, NNI_STATUS, NNI_CLLI, NNI_LOC, NNI_H_COORD, NNI_V_COORD, NNI_IP, NNI_COPPER_IP,
REPLACE(ADDR.ADDR_LN1,'MSAG ') AS Z_ADDRESS, TRIM(GA1.INSTANCE_VALUE) Z_CITY, 
GA2.INSTANCE_VALUE_ABBREV Z_STATE, 
NID_TYPE, REPLACE(VLAN,' ','') VLAN, REMARK
FROM (
-- 8 
SELECT BAN, ACNA, CUSTOMER, REPLACE(ADDRESS,'  ',' ') ADDRESS, TRIM(CITY) CITY, STATE, LATA, EVC_CKR, PNUM,  
CASE WHEN ACT = 'N' THEN DD_COMP ELSE NULL END ETHERNET_READY_DT,
A2.DOCUMENT_NUMBER LAST_ORDER_NO, DD_COMP LAST_COMP_DT,  ACT, EVC_BDW, EVC_LEVEL,
'Carrier HBE' PRODUCT, HBE_CIRCUIT, EVC_DESIGN_ID, EVC, UNI, NNI, 
REPLACE(EVC_CKT2,' ','') EVC_CKT2, REPLACE(UNI_CKT2,' ','') UNI_CKT2, REPLACE(NNI_CKT2,' ','') NNI_CKT2,
EVC_CKT_CLEAN, UNI_CKT_CLEAN, NNI_CKT_CLEAN, 
UNI_DESIGN_ID, UNI_STATUS, UNI_CLLI, UNI_LOC, UNI_H_COORD, UNI_V_COORD, UNI_IP,
NNI_DESIGN_ID, NNI_STATUS, NNI_CLLI, NNI_LOC, NNI_H_COORD, NNI_V_COORD, NNI_IP, NNI_COPPER_IP,
NID_TYPE,
CASE WHEN NID_TYPE IN ('RAD','CANOGA') AND CCV5.CA_VALUE IS NOT NULL AND CCV5.CA_VALUE <> '0' THEN CCV5.CA_VALUE
     WHEN NID_TYPE IN ('RAD','CANOGA') AND CCV6.CA_VALUE IS NOT NULL AND CCV6.CA_VALUE <> '0' THEN CCV6.CA_VALUE
     WHEN NID_TYPE = 'CIENA' AND CCV7.CA_VALUE IS NOT NULL AND CCV7.CA_VALUE <> '0' THEN CCV7.CA_VALUE
     WHEN NID_TYPE = 'CIENA' AND CCV8.CA_VALUE IS NOT NULL AND CCV8.CA_VALUE <> '0' THEN CCV8.CA_VALUE
     ELSE NULL END VLAN,
C5.LOCATION_ID, REGEXP_REPLACE (RMK.REMARK,'[[:cntrl:]]*') REMARK          
FROM (
-- 7 
SELECT BAN, ACNA, CUSTOMER, ADDRESS, CITY, STATE, LATA, EVC_CKR, PNUM, ETHERNET_READY_DT, DOCUMENT_NUMBER, ICSC,
       DD_COMP, ACT, EVC_BDW, EVC_LEVEL, PRODUCT, HBE_CIRCUIT, EVC_DESIGN_ID, EVC, UNI, NNI, RTRIM(EVC_CKT2,'.') EVC_CKT2, RTRIM(UNI_CKT2,'.') UNI_CKT2,
       RTRIM(NNI_CKT2,'.') NNI_CKT2, EVC_CKT_CLEAN, UNI_CKT_CLEAN, NNI_CKT_CLEAN, UNI_DESIGN_ID, UNI_STATUS,
       UNI_CLLI, UNI_LOC, UNI_H_COORD, UNI_V_COORD, UNI_IP, NNI_DESIGN_ID, NNI_STATUS,
       NNI_CLLI, NNI_LOC, NNI_H_COORD, NNI_V_COORD, NNI_IP, NNI_COPPER_IP,
       CEIL(SQRT((((UNI_H_COORD-NNI_H_COORD)*(UNI_H_COORD-NNI_H_COORD))+((UNI_V_COORD-NNI_V_COORD)*(UNI_V_COORD-NNI_V_COORD)))/10)) MILES,
       CASE WHEN UNI_LOC LIKE '%CIENA%' THEN 'CIENA'
            WHEN UNI_LOC LIKE'%RAD%' THEN 'RAD'
            WHEN UNI_LOC LIKE'%CANOGA%' THEN 'CANOGA'
            WHEN STATE = 'CT' THEN 'CIENA' ELSE 'RAD' END NID_TYPE
FROM (
-- 6 
SELECT BAN, ACNA, CUSTOMER, REPLACE(ADDRESS,',','') ADDRESS, REPLACE(CITY,',','') CITY,  REPLACE(STATE,',','') STATE, ICSC,
       LATA, EVC_CKR, PNUM, ETHERNET_READY_DT, DOCUMENT_NUMBER,  DD_COMP, ACT, EVC_BDW, 
       EVC_LEVEL, PRODUCT, HBE_CIRCUIT, EVC_DESIGN_ID, EVC, UNI, NNI, EVC_CKT2,
       UNI_CKT2, NNI_CKT2, EVC_CKT_CLEAN, UNI_CKT_CLEAN, NNI_CKT_CLEAN, UNI_DESIGN_ID, UNI_STATUS,
       CASE WHEN UNI_CLLI IS NOT NULL THEN UNI_CLLI ELSE UNI_CLLI2 END UNI_CLLI,
       CASE WHEN UNI_LOC IS NOT NULL THEN UNI_LOC ELSE UNI_LOC2 END UNI_LOC,
       CASE WHEN UNI_H_COORD IS NOT NULL THEN UNI_H_COORD ELSE UNI_H_COORD2 END UNI_H_COORD,
       CASE WHEN UNI_V_COORD IS NOT NULL THEN UNI_V_COORD ELSE UNI_V_COORD2 END UNI_V_COORD,
       UNI_IP, NNI_DESIGN_ID, NNI_STATUS,
       CASE WHEN NNI_CLLI IS NOT NULL THEN NNI_CLLI ELSE NNI_CLLI2 END NNI_CLLI,
       CASE WHEN NNI_LOC IS NOT NULL THEN NNI_LOC ELSE NNI_LOC2 END NNI_LOC,
       CASE WHEN NNI_H_COORD IS NOT NULL THEN NNI_H_COORD ELSE NNI_H_COORD2 END NNI_H_COORD,
       CASE WHEN NNI_V_COORD IS NOT NULL THEN NNI_V_COORD ELSE NNI_V_COORD2 END NNI_V_COORD, NNI_IP, NNI_COPPER_IP
FROM (
-- 5 
SELECT BAN, ACNA, ACCT.PRIMARY_CARRIER_NAME CUSTOMER, ADDRESS, CITY, STATE, LATA, EVC_CKR, PNUM, ETHERNET_READY_DT, DOCUMENT_NUMBER, ICSC,
       DD_COMP, ACT, EVC_BDW, EVC_LEVEL, PRODUCT, HBE_CIRCUIT, EVC_DESIGN_ID, EVC, UNI, NNI, 
       SUBSTR(REPLACE(REPLACE(EVC,'/','.'),' ',''),1,20) EVC_CKT2,
       SUBSTR(REPLACE(REPLACE(UNI,'/','.'),' ',''),1,20) UNI_CKT2,
       CASE WHEN SUBSTR(NNI,3,1) = '/' THEN SUBSTR(REPLACE(REPLACE(NNI,'/','.'),' ',''),1,20) 
        ELSE SUBSTR(REPLACE(NNI,'/','.'),-23) END NNI_CKT2,
       SUBSTR(REPLACE(REPLACE(EVC,'/',''),' ',''),1,20) EVC_CKT_CLEAN,
       SUBSTR(REPLACE(REPLACE(UNI,'/',''),' ',''),1,20) UNI_CKT_CLEAN,
       CASE WHEN SUBSTR(NNI,3,1) = '/' THEN SUBSTR(REPLACE(REPLACE(NNI,'/',''),' ',''),1,20)
        ELSE SUBSTR(REPLACE(REPLACE(NNI,'/',''),' ',''),-22) END NNI_CKT_CLEAN,
       C2A.CIRCUIT_DESIGN_ID UNI_DESIGN_ID, C2A.STATUS UNI_STATUS, NL1.CLLI_CODE UNI_CLLI, NL1.LOCATION_NAME UNI_LOC,  
       NL1.H_COORDINATE UNI_H_COORD, NL1.V_COORDINATE UNI_V_COORD, NL2.CLLI_CODE UNI_CLLI2, NL2.LOCATION_NAME UNI_LOC2, 
       NL2.H_COORDINATE UNI_H_COORD2, NL2.V_COORDINATE UNI_V_COORD2, CCV1.CA_VALUE UNI_IP, 
       C3A.CIRCUIT_DESIGN_ID NNI_DESIGN_ID, C3A.STATUS NNI_STATUS, NL3.CLLI_CODE NNI_CLLI, NL3.LOCATION_NAME NNI_LOC, 
       NL3.H_COORDINATE NNI_H_COORD, NL3.V_COORDINATE NNI_V_COORD, NL4.CLLI_CODE NNI_CLLI2, NL4.LOCATION_NAME NNI_LOC2, 
       NL4.H_COORDINATE NNI_H_COORD2, NL4.V_COORDINATE NNI_V_COORD2, CCV3.CA_VALUE NNI_IP, CCV4.CA_VALUE NNI_COPPER_IP
FROM (
-- 4 
SELECT BAN, ACNA, ADDRESS, CITY, STATE, LATA, EVC_CKR, PNUM, ETHERNET_READY_DT, DOCUMENT_NUMBER,
       DD_COMP, ACT, EVC_BDW, EVC_LEVEL, PRODUCT, HBE_CIRCUIT, EVC_DESIGN_ID, CKT EVC, ICSC,
       CASE WHEN CUD1 = '435' THEN UNI1
            WHEN CUD2 = '435' THEN UNI2
            ELSE NULL END UNI,     
       CASE WHEN CUD1 = '435' THEN CDI1
            WHEN CUD2 = '435' THEN CDI2
            ELSE NULL END UNI_DESIGN_ID,           
       CASE WHEN CUD1 = '436' THEN UNI1
            WHEN CUD2 = '436' THEN UNI2
            ELSE NULL END NNI,
       CASE WHEN CUD1 = '436' THEN CDI1
            WHEN CUD2 = '436' THEN CDI2
            ELSE NULL END NNI_DESIGN_ID         
FROM ( 
-- 3                     
SELECT A.*, C.EXCHANGE_CARRIER_CIRCUIT_ID UNI1, C.CIRCUIT_DESIGN_ID CDI1, CUD.UNI_OR_NNI CUD1, C.LOCATION_ID LOC_ID1, C.LOCATION_ID_2 LOC_ID1_2, 
       C2.EXCHANGE_CARRIER_CIRCUIT_ID UNI2, C2.CIRCUIT_DESIGN_ID CDI2, CUD2.UNI_OR_NNI CUD2, C2.LOCATION_ID LOC_ID2, C2.LOCATION_ID_2 LOC_ID2_2
FROM 
(
-- 2
SELECT DISTINCT BAN, ACNA,
       REPLACE(ADDRESS,'MSAG ') AS ADDRESS, CITY, STATE, 
       CASE WHEN LATA IS NOT NULL THEN LATA ELSE LATA_NUMBER END LATA,
       EVC_CKR, CASE WHEN PNUM IS NOT NULL THEN PNUM ELSE OEC_PNUM END PNUM,  
       CASE WHEN ACT = 'N' THEN DD_COMP ELSE NULL END ETHERNET_READY_DT,
       DOCUMENT_NUMBER, DD_COMP, ACT, 
       CASE WHEN UOM = 'G' THEN TO_NUMBER(REGEXP_REPLACE(BDW,'[^.^0-9'']','')) *1000 
        ELSE TO_NUMBER(REGEXP_REPLACE(BDW,'[^.^0-9'']','')) END AS EVC_BDW,
       CASE WHEN LOS = ('EBE') THEN 'Silver'
            WHEN LOS = ('EPD') THEN 'Gold' 
            WHEN LOS = ('ERT') THEN 'Platinum'
            WHEN LOS = ('BASIC') THEN 'Silver'
            WHEN LOS = ('PD') THEN 'Gold' 
            WHEN LOS = ('RT') THEN 'Platinum'
            WHEN EVC_SPEC = 'EVPLSE' THEN 'Silver'
            WHEN EVC_SPEC = 'EPATHES' THEN 'Silver'
            WHEN EVC_SPEC = 'EPATHEG' THEN 'Gold'
            WHEN EVC_SPEC = 'EPATHEP' THEN 'Platinum'
            ELSE NULL END EVC_LEVEL,
       NULL PRODUCT,  
       CASE WHEN HBE_CIRCUIT = '207' THEN 'Y' ELSE 'N' END HBE_CIRCUIT,     
       CIRCUIT_DESIGN_ID EVC_DESIGN_ID, CKT,
       EVC_STATUS, EVC_STATUS_DESC, ICSC, EVC_IND, 
       ROW_NUMBER() OVER (PARTITION BY CKT ORDER BY DD_COMP DESC) R 
FROM (
-- 1 
SELECT DISTINCT C.EXCHANGE_CARRIER_CIRCUIT_ID CKT, SR.ACNA, SR.DOCUMENT_NUMBER, EVC_IND, TRUNC(ACTUAL_COMPLETION_DATE) DD_COMP,
       ASR.SERVICE_AND_PRODUCT_ENHANC_COD UNI_SPEC, PROMOTION_NBR PNUM, PC.OEC_PNUM, ASR.SUPPLEMENT_TYPE SUPP, ASR.ACTIVITY_INDICATOR ACT,
       ASR.LATA_NUMBER LATA, CO.LATA_NUMBER, A.ADDR_LN1 ADDRESS, GA2.INSTANCE_VALUE CITY, GA.INSTANCE_VALUE_ABBREV STATE,
       ELS.LVL_OF_SERV_NM AS LOS, ELS.SERVICE_AND_PRODUCT_ENHANC_COD AS EVC_SPEC, ELS.BANDWIDTH BDW, ELS.BANDWIDTH_UOM UOM,
       ED.EVC_CKR, AUD.BAN, C2.STATUS EVC_STATUS, C.CIRCUIT_DESIGN_ID, ACCESS_PROVIDER_SERV_CTR_CODE ICSC, CUDEVC.HBE_CIRCUIT,
       DECODE (C2.STATUS,
                  '1', 'Pending',
                  '2', 'Assigned',
                  '3', 'In Progress',
                  '4', 'Record Issued',
                  '5', 'DLR Issued',
                  '6', 'In Service',
                  '7', 'Pending Disconnect',
                  '8', 'Disconnected',
                  '9', 'Problem',
                  'A', 'Cancelled',
                  NULL
                 ) EVC_STATUS_DESC        
FROM SERV_REQ SR, 
     ACCESS_SERVICE_REQUEST ASR, 
     TASK T, 
     ASR_USER_DATA AUD,
     PROMO_CONTRACT PC,
     SERVICE_REQUEST_CIRCUIT SRC, 
     CIRCUIT C,
     EVC_UNI_MAP EUM,
     EVC_LVL_SERV ELS,
     EVC_DETAIL ED,
     SERV_ITEM SI,
     (SELECT DISTINCT *
        FROM (SELECT D.DESIGN_ID,
                     D.ISSUE_NBR,
                     D.SERV_ITEM_ID,
                     D.ISSUE_STATUS,
                     ROW_NUMBER() OVER (PARTITION BY SERV_ITEM_ID ORDER BY ISSUE_STATUS ASC) R
                   FROM ASAP.DESIGN D)
                    WHERE R = 1) D,
     (SELECT DISTINCT *
        FROM (SELECT D.LOCATION_ID,
                     D.ADDRESS_ID,
                     D.ACTIVE_IND,
                     ROW_NUMBER() OVER (PARTITION BY LOCATION_ID ORDER BY ADDRESS_ID DESC) R
                   FROM ASAP.NET_LOC_ADDR D
                    WHERE ACTIVE_IND = 'Y')
                     WHERE R = 1) NLA,                            
     ADDRESS A,
     GA_INSTANCE GA,
     GA_INSTANCE GA2,
     NETWORK_LOCATION NL,
     CENTRAL_OFFICE_EXCHANGE_AREA CO,
     CIRCUIT C2,
     CIRCUIT_USER_DATA CUDEVC
WHERE SR.DOCUMENT_NUMBER = ASR.DOCUMENT_NUMBER
  AND SR.DOCUMENT_NUMBER = T.DOCUMENT_NUMBER
  AND SR.DOCUMENT_NUMBER = AUD.DOCUMENT_NUMBER (+)
  AND SR.DOCUMENT_NUMBER = PC.DOCUMENT_NUMBER (+)
  AND SR.DOCUMENT_NUMBER = SRC.DOCUMENT_NUMBER
  AND SR.DOCUMENT_NUMBER = EUM.DOCUMENT_NUMBER (+)
  AND SR.DOCUMENT_NUMBER = ED.DOCUMENT_NUMBER (+)
  AND EUM.DOCUMENT_NUMBER = ELS.DOCUMENT_NUMBER (+)
  AND EUM.EVC_UNI_MAP_ID = ELS.EVC_UNI_MAP_ID(+)
  AND SRC.CIRCUIT_DESIGN_ID = C.CIRCUIT_DESIGN_ID (+)
  AND C.CIRCUIT_DESIGN_ID = SI.CIRCUIT_DESIGN_ID (+)
  AND SI.SERV_ITEM_ID = D.SERV_ITEM_ID (+)
  AND C.LOCATION_ID = NLA.LOCATION_ID (+)
  AND NLA.ADDRESS_ID = A.ADDRESS_ID (+)
  AND A.GA_INSTANCE_ID_STATE_CD = GA.GA_INSTANCE_ID (+)
  AND A.GA_INSTANCE_ID_CITY = GA2.GA_INSTANCE_ID (+)
  AND C.LOCATION_ID_2 = NL.LOCATION_ID(+)
  AND NL.EXCHANGE_AREA_CLLI = CO.EXCHANGE_AREA_CLLI (+)
  AND C.EXCHANGE_CARRIER_CIRCUIT_ID = C2.EXCHANGE_CARRIER_CIRCUIT_ID
  AND C.CIRCUIT_DESIGN_ID = C2.CIRCUIT_DESIGN_ID
  AND C.CIRCUIT_DESIGN_ID = CUDEVC.CIRCUIT_DESIGN_ID (+)
  AND T.TASK_TYPE = 'DD'
  AND EVC_IND IN ('A','B')
  AND T.ACTUAL_COMPLETION_DATE IS NOT NULL
  AND SR.ACTIVITY_IND IN ('N','C','R')
  -- AND SR.DOCUMENT_NUMBER IN ('3937103')
  AND TO_CHAR(T.ACTUAL_COMPLETION_DATE,'yyyymmdd') >= '20231224'     --CHANGE DATE TO SHOW THE PREVIOUS SUNDAY 11/12   
  --AND SR.ACNA IN ('AWL','IUW')
-- 1   
) 
WHERE SUBSTR(CKT,4,1) = 'V'
AND (EVC_SPEC IS NOT NULL OR LOS IS NOT NULL) 
AND (SUPP <> 1 OR SUPP IS NULL)
AND EVC_STATUS NOT IN ('8','A')
AND HBE_CIRCUIT = '207'
-- 2
) 
A,
  EVC_UNI_MAP EUM,
  CIRCUIT C,
  CIRCUIT_USER_DATA CUD,
  EVC_UNI_MAP EUM2,
  CIRCUIT C2,
  CIRCUIT_USER_DATA CUD2
 WHERE A.DOCUMENT_NUMBER = EUM.DOCUMENT_NUMBER (+)
   AND REPLACE(SUBSTR(EUM.REL_UNI_IDENT,1,14),'.','/') = SUBSTR(C.EXCHANGE_CARRIER_CIRCUIT_ID (+),1,14)
   AND C.CIRCUIT_DESIGN_ID = CUD.CIRCUIT_DESIGN_ID (+)
   AND EUM.UNI_REF_NBR (+) = '01'
   AND A.DOCUMENT_NUMBER = EUM2.DOCUMENT_NUMBER  (+)
   AND REPLACE(SUBSTR(EUM2.REL_UNI_IDENT,1,14),'.','/') = SUBSTR(C2.EXCHANGE_CARRIER_CIRCUIT_ID (+),1,14)
   AND C2.CIRCUIT_DESIGN_ID = CUD2.CIRCUIT_DESIGN_ID (+)
   AND EUM2.UNI_REF_NBR (+) = '02'
-- 3    
) 
-- 4
)
B, 
  ASR_OM.ASR_ACCOUNT_MANAGER ACCT, 
  CIRCUIT C2A,   
  NETWORK_LOCATION NL1,
  NETWORK_LOCATION NL2,
  (SELECT DISTINCT CIRCUIT_DESIGN_ID, CA_VALUE, CA_VALUE_LABEL
      FROM (
            SELECT CIRCUIT_DESIGN_ID, 
            CA_VALUE, 
            CA_VALUE_LABEL,
            ROW_NUMBER() OVER (PARTITION BY CIRCUIT_DESIGN_ID ORDER BY CONN_CA_VALUE_ID DESC) R
         FROM CONN_CA_VALUE
          WHERE CA_USAGE_ID = '100521' )  --RAD IP   
              WHERE R = 1 ) CCV1,
  CIRCUIT C3A,           
  NETWORK_LOCATION NL3,
  NETWORK_LOCATION NL4,
  (SELECT DISTINCT CIRCUIT_DESIGN_ID, CA_VALUE, CA_VALUE_LABEL
      FROM (
            SELECT CIRCUIT_DESIGN_ID, 
            CA_VALUE, 
            CA_VALUE_LABEL,
            ROW_NUMBER() OVER (PARTITION BY CIRCUIT_DESIGN_ID ORDER BY CONN_CA_VALUE_ID DESC) R
         FROM CONN_CA_VALUE
          WHERE CA_USAGE_ID = '100521' )  --RAD IP   
              WHERE R = 1 ) CCV3,
  (SELECT DISTINCT CIRCUIT_DESIGN_ID, CA_VALUE, CA_VALUE_LABEL
      FROM (
            SELECT CIRCUIT_DESIGN_ID, 
            CA_VALUE, 
            CA_VALUE_LABEL,
            ROW_NUMBER() OVER (PARTITION BY CIRCUIT_DESIGN_ID ORDER BY CONN_CA_VALUE_ID DESC) R
         FROM CONN_CA_VALUE
          WHERE CA_USAGE_ID = '100246' )  --RAD IP   
              WHERE R = 1 ) CCV4                     
 WHERE B.ACNA = ACCT.SECONDARY_ID (+)
    AND B.UNI_DESIGN_ID = C2A.CIRCUIT_DESIGN_ID (+)
    AND C2A.LOCATION_ID_2 = NL1.LOCATION_ID (+)
    AND C2A.LOCATION_ID = NL2.LOCATION_ID (+)
    AND C2A.CIRCUIT_DESIGN_ID = CCV1.CIRCUIT_DESIGN_ID (+) 
    AND B.NNI_DESIGN_ID = C3A.CIRCUIT_DESIGN_ID (+)  
    AND C3A.LOCATION_ID_2 = NL3.LOCATION_ID (+)
    AND C3A.LOCATION_ID = NL4.LOCATION_ID (+)
    AND C3A.CIRCUIT_DESIGN_ID = CCV3.CIRCUIT_DESIGN_ID (+)  
    AND C3A.CIRCUIT_DESIGN_ID = CCV4.CIRCUIT_DESIGN_ID (+)
-- 5
)
-- 6 
)
-- 7
)

A2,
  REMARK RMK,
  CIRCUIT C5, 
  (SELECT DISTINCT CIRCUIT_DESIGN_ID, CA_VALUE, CA_VALUE_LABEL
      FROM (
            SELECT CIRCUIT_DESIGN_ID, 
            CA_VALUE, 
            CA_VALUE_LABEL,
            ROW_NUMBER() OVER (PARTITION BY CIRCUIT_DESIGN_ID ORDER BY CONN_CA_VALUE_ID DESC) R
         FROM CONN_CA_VALUE
          WHERE CA_USAGE_ID = '100253' )    
              WHERE R = 1 ) CCV5,
  (SELECT DISTINCT CIRCUIT_DESIGN_ID, CA_VALUE, CA_VALUE_LABEL
      FROM (
            SELECT CIRCUIT_DESIGN_ID, 
            CA_VALUE, 
            CA_VALUE_LABEL,
            ROW_NUMBER() OVER (PARTITION BY CIRCUIT_DESIGN_ID ORDER BY CONN_CA_VALUE_ID DESC) R
         FROM CONN_CA_VALUE
          WHERE CA_USAGE_ID = '100254' )   
              WHERE R = 1 ) CCV6, 
  (SELECT DISTINCT CIRCUIT_DESIGN_ID, CA_VALUE, CA_VALUE_LABEL
      FROM (
            SELECT CIRCUIT_DESIGN_ID, 
            CA_VALUE, 
            CA_VALUE_LABEL,
            ROW_NUMBER() OVER (PARTITION BY CIRCUIT_DESIGN_ID ORDER BY CONN_CA_VALUE_ID DESC) R
         FROM CONN_CA_VALUE
          WHERE CA_USAGE_ID = '100577' )    
              WHERE R = 1 ) CCV7,
  (SELECT DISTINCT CIRCUIT_DESIGN_ID, CA_VALUE, CA_VALUE_LABEL
      FROM (
            SELECT CIRCUIT_DESIGN_ID, 
            CA_VALUE, 
            CA_VALUE_LABEL,
            ROW_NUMBER() OVER (PARTITION BY CIRCUIT_DESIGN_ID ORDER BY CONN_CA_VALUE_ID DESC) R
         FROM CONN_CA_VALUE
          WHERE CA_USAGE_ID = '100583' )    
              WHERE R = 1 ) CCV8                    
WHERE A2.NNI_DESIGN_ID = C5.CIRCUIT_DESIGN_ID 
AND A2.DOCUMENT_NUMBER = RMK.DOCUMENT_NUMBER (+)
AND RMK.FORM_ID (+) = 'ASR'
AND A2.EVC_DESIGN_ID = CCV5.CIRCUIT_DESIGN_ID (+)
AND A2.EVC_DESIGN_ID = CCV6.CIRCUIT_DESIGN_ID (+)
AND A2.EVC_DESIGN_ID = CCV7.CIRCUIT_DESIGN_ID (+)
AND A2.EVC_DESIGN_ID = CCV8.CIRCUIT_DESIGN_ID (+)
-- 8 
)
 A3,
 (SELECT DISTINCT *
        FROM (SELECT D.LOCATION_ID,
                     D.ADDRESS_ID,
                     D.ACTIVE_IND,
                     ROW_NUMBER() OVER (PARTITION BY LOCATION_ID ORDER BY ADDRESS_ID DESC) R
                   FROM ASAP.NET_LOC_ADDR D
                    WHERE ACTIVE_IND = 'Y')
                     WHERE R = 1) NLA,            
  ADDRESS ADDR,
  MV_GA_INSTANCE GA1,
  MV_GA_INSTANCE GA2
WHERE A3.LOCATION_ID = NLA.LOCATION_ID
AND NLA.ADDRESS_ID = ADDR.ADDRESS_ID
AND ADDR.GA_INSTANCE_ID_CITY = GA1.GA_INSTANCE_ID
AND ADDR.GA_INSTANCE_ID_STATE_CD = GA2.GA_INSTANCE_ID
ORDER BY 1
;