

SELECT SR.DOCUMENT_NUMBER, 
       MIN(TRUNC(N.LAST_MODIFIED_DATE)) KEEP (DENSE_RANK FIRST ORDER BY N.LAST_MODIFIED_DATE) ASR_INIT, 
       TRUNC(ASR.DATE_TIME_SENT) ASR_CLEAN, 
       ASR.DESIRED_DUE_DATE DD,
       AUD.ORIG_FOC_DD,   
       CASE WHEN ORIG_FOC_DD IS NOT NULL THEN 'Y' ELSE 'N' END FOC_SENT,
       ASR.NETWORK_CHANNEL_SERVICE_CODE NC, 
       ASR.PON PON,   
       SR.ACNA ACNA,
       ACCT.PRIMARY_CARRIER_NAME CUSTOMER,  
       GA.INSTANCE_VALUE_ABBREV STATE,
       ASR.ACTIVITY_INDICATOR ACT,
       ASR.SERVICE_AND_PRODUCT_ENHANC_COD SPEC,
       PROMOTION_NBR PNUM, 
       TRUNC(T.ACTUAL_COMPLETION_DATE) DD_COMP,
       SR.SUPPLEMENT_TYPE SUPP,
       C.EXCHANGE_CARRIER_CIRCUIT_ID CKT_ID,
       CASE WHEN CUD.UNI_OR_NNI = '435' THEN 'ETHERNET-UNI'
            WHEN CUD.UNI_OR_NNI = '436' THEN 'ETHERNET-NNI'
            WHEN EVC_IND = 'B' THEN 'ETHERNET-UNI'
            WHEN ASR.NETWORK_CHANNEL_SERVICE_CODE IN ('KG','SN','SX') THEN 'ETHERNET-NNI'
            ELSE 'ETHERNET-UNI' END PRODUCT,
       ASR.EVC_IND,
       CASE WHEN TO_CHAR(T.ACTUAL_COMPLETION_DATE,'MM') = '01' THEN 'Jan'
            WHEN TO_CHAR(T.ACTUAL_COMPLETION_DATE,'MM') = '02' THEN 'Feb'
            WHEN TO_CHAR(T.ACTUAL_COMPLETION_DATE,'MM') = '03' THEN 'Mar'
            WHEN TO_CHAR(T.ACTUAL_COMPLETION_DATE,'MM') = '04' THEN 'Apr'
            WHEN TO_CHAR(T.ACTUAL_COMPLETION_DATE,'MM') = '05' THEN 'May'
            WHEN TO_CHAR(T.ACTUAL_COMPLETION_DATE,'MM') = '06' THEN 'Jun'
            WHEN TO_CHAR(T.ACTUAL_COMPLETION_DATE,'MM') = '07' THEN 'Jul'
            WHEN TO_CHAR(T.ACTUAL_COMPLETION_DATE,'MM') = '08' THEN 'Aug'
            WHEN TO_CHAR(T.ACTUAL_COMPLETION_DATE,'MM') = '09' THEN 'Sep'
            WHEN TO_CHAR(T.ACTUAL_COMPLETION_DATE,'MM') = '10' THEN 'Oct'
            WHEN TO_CHAR(T.ACTUAL_COMPLETION_DATE,'MM') = '11' THEN 'Nov'
            WHEN TO_CHAR(T.ACTUAL_COMPLETION_DATE,'MM') = '12' THEN 'Dec'
            ELSE NULL END MON,
       TO_CHAR(T.ACTUAL_COMPLETION_DATE,'YYYY') YEAR       
FROM SERV_REQ SR,
     ACCESS_SERVICE_REQUEST ASR,
     ASR_USER_DATA AUD,    
     TASK T,
     SERVICE_REQUEST_CIRCUIT SRC,
     CIRCUIT C,
     CIRCUIT_USER_DATA CUD,
     NOTES N,
     NET_LOC_ADDR NLA,
     ADDRESS ADDR,
     GA_INSTANCE GA,
     ASR_OM.ASR_ACCOUNT_MANAGER ACCT
WHERE SR.DOCUMENT_NUMBER = ASR.DOCUMENT_NUMBER (+)
  AND SR.DOCUMENT_NUMBER = AUD.DOCUMENT_NUMBER (+)
  AND SR.DOCUMENT_NUMBER = T.DOCUMENT_NUMBER (+)
  AND SR.DOCUMENT_NUMBER = SRC.DOCUMENT_NUMBER (+)
  AND SRC.CIRCUIT_DESIGN_ID = C.CIRCUIT_DESIGN_ID
  AND SR.DOCUMENT_NUMBER = N.DOCUMENT_NUMBER (+)
  AND C.CIRCUIT_DESIGN_ID = CUD.CIRCUIT_DESIGN_ID (+)
  AND C.LOCATION_ID = NLA.LOCATION_ID (+)
  AND NLA.ADDRESS_ID = ADDR.ADDRESS_ID (+)
  AND ADDR.GA_INSTANCE_ID_STATE_CD = GA.GA_INSTANCE_ID (+)
  AND SR.ACNA = ACCT.SECONDARY_ID (+)
  AND TO_CHAR(T.ACTUAL_COMPLETION_DATE,'yyyymm') = '202309'   --CHANGE EACH MONTH - CURRENT REPORTING MONTH  
  AND ASR.REQUEST_TYPE IN ('S','E')
  AND ASR.ACTIVITY_INDICATOR IN ('N')
  AND SUBSTR(ASR.NETWORK_CHANNEL_SERVICE_CODE,1,1) NOT IN ('H','X','L','O','P')
  AND SUBSTR(C.EXCHANGE_CARRIER_CIRCUIT_ID,4,1) <> 'V'
  AND (EVC_IND <> 'A' OR EVC_IND IS NULL)
  AND ASR.ORDER_TYPE = 'ASR' 
  AND T.TASK_TYPE = 'DD'
  AND SR.SUPPLEMENT_TYPE = 1
  AND SR.ACNA NOT IN ('BLI','CQV','CZJ','CZX','EPX','FLR','FLX','FTR','GOV','SUV','ZWV','ZZZ',
                      'FIS','W05','ANV','FCA','GVN','ZAP','GSW','WBY','CUS','VZN',
                      'AF1','CXN','EXC','FBA','T05','WWW','ZTK') 
GROUP BY SR.DOCUMENT_NUMBER, T.ACTUAL_COMPLETION_DATE, ASR.DATE_TIME_SENT, 
         ASR.DESIRED_DUE_DATE, ASR.NETWORK_CHANNEL_SERVICE_CODE, 
         ASR.PON, SR.ACNA, ASR.ACTIVITY_INDICATOR, 
         SR.SUPPLEMENT_TYPE, GA.INSTANCE_VALUE_ABBREV,
         C.EXCHANGE_CARRIER_CIRCUIT_ID, ASR.EVC_IND, CUD.UNI_OR_NNI,
         AUD.ORIG_FOC_DD, ACCT.PRIMARY_CARRIER_NAME,
         ASR.SERVICE_AND_PRODUCT_ENHANC_COD, PROMOTION_NBR
ORDER BY 15;         