SELECT DISTINCT CARRIER, --CCNA, 
       STATE, BAN_TYPE, GL_MATRIX_CLASS, COUNT(*)
FROM (
SELECT DISTINCT CARRIER, CCNA, 
       STATE, BAN_TYPE, WTN, GL_MATRIX_CLASS 
FROM (
SELECT DISTINCT CARRIER, CCNA, 
       STATE, BAN_TYPE, WTN, GL_MATRIX_NO 
FROM (
SELECT DISTINCT MCL.PRIMARY_CARRIER_NAME CARRIER, CCNA, 
       STATE, BAN_TYPE, WTN
FROM (
--
SELECT LSPBAN.BANCARCD CCNA, SQ1.WTN, 
       SQ1.STATE,
       CASE WHEN LSPBAN.BANSUMTYP IN ('D','B','C','E','F','G','H','I','J','K') THEN 'DIRECTORY'
            WHEN LSPBAN.BANSUMTYP IN ('P','W','X','Y','Z') THEN 'PLATFORM'
            WHEN LSPBAN.BANSUMTYP IN ('L','M','N','O','A','Q') THEN 'LOOP'
            WHEN LSPBAN.BANSUMTYP IN ('R','S','T','U','V') THEN 'RESALE'
            WHEN LSPBAN.BANSUMTYP IN ('I') THEN 'ISP'
            ELSE NULL END BAN_TYPE
FROM (
--
SELECT SUBSTR(TRIM(TELEPHONENUMBER),1,10) WTN, 
       SUBSTR(TRIM(BILLINGTELEPHONE),1,10) BTN, 
       SUBSTR(TRIM(C2F.MASTERACCOUNTNUMBER),1,10) MASTERACCOUNTNUMBER, 
       C2F.STATE 
FROM EDW_VWMC.C2F_EXCHANGE_SUBSCRIBERS C2F
WHERE MASTERACCOUNTNUMBER IS NOT NULL
--AND C2F.TELEPHONENUMBER in ('7148918099')
)SQ1,
 USER_WORK.CM_LSPBANM LSPBAN
 WHERE SQ1.MASTERACCOUNTNUMBER = LSPBAN.STN
 AND SUBSTR(LSPBAN.BANCARCD,1,1) <> 'Z'
)SQ2
 LEFT OUTER JOIN USER_WORK.CM_CARRIER_ACNA_MCL_202201 AS MCL ON MCL.SECONDARY_ID = SQ2.CCNA
)SQ3 
 LEFT OUTER JOIN EDW_VWMC.EUBS_BILL_REV_ACCT_DETAIL_V AS EUBS ON EUBS.SVC_ACCS_METHD_NO = SQ3.WTN
 WHERE EUBS.BILL_MONTH_DATE ='2022-08-01'
   --AND GL_MATRIX_NO <> '000'
)SQ4
 LEFT OUTER JOIN USER_WORK.CM_GL_MATRIX AS GLM ON GLM.GL_MATRIX_NO = SQ4.GL_MATRIX_NO
)SQ5
--WHERE GL_MATRIX_CLASS = 'VOICE'
 GROUP BY CARRIER, --CCNA, 
          STATE, BAN_TYPE, GL_MATRIX_CLASS
 ORDER BY 1,3,2