SELECT PON, DOCUMENT_NUMBER, TYPE_OF_SR, REQUEST_TYPE, ACT_IND, SUPP_TYPE, VER, COMPLETION_DATE, ICSC, PROJ, CCNA, CCNA_NAME,
         CASE WHEN STATE1 IS NOT NULL THEN STATE1
              WHEN CLLI_STATE IS NOT NULL THEN CLLI_STATE
              WHEN SEC_STATE IS NOT NULL THEN SEC_STATE
              WHEN PRI_STATE IS NOT NULL THEN PRI_STATE
              WHEN ICSC = 'FV01' THEN 'WV'
              WHEN ICSC = 'RT01' THEN 'NY'
              WHEN SUBSTR(ICSC,1,2) = 'FV' AND SUBSTR(CKT,1,2) = '83' THEN 'ID'
              WHEN SUBSTR(ICSC,1,2) = 'FV' AND SUBSTR(CKT,1,2) = '85' THEN 'OR'
              WHEN SUBSTR(ICSC,1,2) = 'FV' AND SUBSTR(CKT,1,2) = '86' THEN 'WA'
              WHEN SUBSTR(ICSC,1,2) = 'FV' AND SUBSTR(CKT,1,2) = '30' THEN 'IL'
              WHEN SUBSTR(ICSC,1,2) = 'FV' AND SUBSTR(CKT,1,2) = '61' THEN 'NC'
              WHEN SUBSTR(ICSC,1,2) = 'FV' AND SUBSTR(CKT,1,2) = '62' THEN 'SC'
              WHEN SUBSTR(ICSC,1,2) = 'FV' AND SUBSTR(CKT,1,2) = '31' THEN 'IN'
              WHEN SUBSTR(ICSC,1,2) = 'FV' AND SUBSTR(CKT,1,2) = '33' THEN 'MI'
              WHEN SUBSTR(ICSC,1,2) = 'FV' AND SUBSTR(CKT,1,2) = '36' THEN 'OH'
              WHEN SUBSTR(ICSC,1,2) = 'FV' AND SUBSTR(CKT,1,2) = '39' THEN 'WI'
              WHEN SUBSTR(PROJ,1,7) = 'ATTMOB-' THEN SUBSTR(PROJ,12,2)
              ELSE CLLI_STATE END STATE, 
         CASE WHEN REQUEST_TYPE = 'M' THEN 'SWITCHED'
              WHEN RATE_CODE IN ('DS0','DS1','DS3') THEN RATE_CODE
              WHEN (SUBSTR(RATE_CODE,1,2) = 'OC' OR SUBSTR(NC,1,1) = 'O') THEN 'OCN'
              WHEN (NC = 'HC' OR SUBSTR(CKT,4,2) = 'HC') THEN 'DS1'
              WHEN (NC = 'HF' OR SUBSTR(CKT,4,2) = 'HF') THEN 'DS3'
              WHEN SUBSTR(CKT,7,2) = 'T1' THEN 'DS1'
              WHEN SUBSTR(CKT,7,2) = 'T3' THEN 'DS3'
              WHEN SUBSTR(NC,1,1) IN ('L','X') THEN 'DS0'
              WHEN SUBSTR(CKT,4,1) IN ('L','X') THEN 'DS0'
              WHEN SUBSTR(CKT,4,2) IN ('OS','FX','UC','UG','CL') THEN 'DS0'
              WHEN SUBSTR(CKT,4,2) IN ('YG','QG','DH','YB') THEN 'DS0'
              WHEN (SUBSTR(NC,1,1) = 'K' OR SUBSTR(CKT,4,1) = 'K') THEN 'ETHERNET-UNI'
              WHEN SUBSTR(CKT,4,1) = 'V' THEN 'ETHERNET-EVC'
			  WHEN SUBSTR(PROJ,1,10) = 'ATTMOB-TLS' THEN 'ETHERNET-UNI'
			  WHEN SUBSTR(PROJ,1,10) = 'ATTMOB-EVC' THEN 'ETHERNET-EVC'
              ELSE RATE_CODE END PRODUCT,
         RATE_CODE, CKT, CATG
FROM
(
SELECT SR.PON,
  SR.DOCUMENT_NUMBER,
  SR.TYPE_OF_SR,
  ASR.REQUEST_TYPE,
  CASE WHEN NL1.CLLI_CODE IS NOT NULL THEN SUBSTR(NL1.CLLI_CODE,5,2)
       WHEN NL2.CLLI_CODE IS NOT NULL THEN SUBSTR(NL2.CLLI_CODE,5,2)
       ELSE NULL END STATE1,
  MAX(SR.ACTIVITY_IND) keep (dense_rank last order by asr.last_modified_date) ACT_IND,
  MAX(SR.SUPPLEMENT_TYPE) keep (dense_rank last order by asr.last_modified_date) SUPP_TYPE,
  MAX(SR.VERSION_IDENTIFICATION) keep (dense_rank last order by asr.last_modified_date) VER,
  MAX(TRUNC(ASAP.PKG_GMT.SF_GMT_AS_PASSED_TIMEZONE(TSK.ACTUAL_COMPLETION_DATE,1222))) keep (dense_rank last order by tsk.last_modified_date) COMPLETION_DATE,
  MAX(ASR.ACCESS_PROVIDER_SERV_CTR_CODE) keep (dense_rank last order by asr.last_modified_date) ICSC,
  MAX(SR.PROJECT_IDENTIFICATION) keep (dense_rank last order by asr.last_modified_date) PROJ,
  MAX(SR.CCNA) keep (dense_rank last order by sr.last_modified_date) CCNA,
  MAX(SR.CCNA_NAME) keep (dense_rank last order by sr.last_modified_date) CCNA_NAME,
  MAX(SUBSTR(NL1.EXCHANGE_AREA_CLLI,5,2)) keep (dense_rank last order by nl1.last_modified_date) CLLI_STATE,
  MAX(PRILOC_STATE) keep (dense_rank last order by dlr.last_modified_date) PRI_STATE,
  MAX(SECLOC_STATE) keep (dense_rank last order by dlr.last_modified_date) SEC_STATE,
  MAX(CIR.RATE_CODE) keep (dense_rank last order by cir.last_modified_date) RATE_CODE,
  MAX(ASR.NETWORK_CHANNEL_SERVICE_CODE) keep (dense_rank last order by asr.last_modified_date) NC,
  CIR.EXCHANGE_CARRIER_CIRCUIT_ID CKT, 
  SC.SVC_CATG_NM CATG
--
FROM SERV_REQ SR, 
     ACCESS_SERVICE_REQUEST ASR, 
     NETWORK_LOCATION NL1,
     NETWORK_LOCATION NL2,
     CIRCUIT CIR,
     DESIGN_LAYOUT_REPORT DLR, 
     TASK TSK,
     ASAP.SERVICE_REQUEST_CIRCUIT SRC,
	 CUST_ACCT_SVC_CATG CASC,
	 SVC_CATG SC
--
WHERE SR.DOCUMENT_NUMBER = ASR.DOCUMENT_NUMBER(+)
AND SR.DOCUMENT_NUMBER = SRC.DOCUMENT_NUMBER (+)
AND SRC.CIRCUIT_DESIGN_ID = CIR.CIRCUIT_DESIGN_ID (+)
AND CIR.LOCATION_ID = NL1.LOCATION_ID (+)
AND CIR.LOCATION_ID_2 = NL2.LOCATION_ID (+)
AND SR.DOCUMENT_NUMBER = DLR.DOCUMENT_NUMBER (+)
AND SR.DOCUMENT_NUMBER = TSK.DOCUMENT_NUMBER (+)
AND SR.CUST_ACCT_ID = CASC.CUST_ACCT_ID (+) 
AND CASC.SVC_CATG_ID = SC.SVC_CATG_ID (+) 
AND SR.TYPE_OF_SR in ('ASR','SO')
AND TSK.TASK_TYPE = 'DD'
AND TO_CHAR(TSK.ACTUAL_COMPLETION_DATE,'YYYYMM') = substr((TO_CHAR(SYSDATE,'YYYYMMDD')-8),1,6)
--
GROUP BY SR.DOCUMENT_NUMBER,
  SR.PON,
  SR.TYPE_OF_SR, 
  ASR.REQUEST_TYPE, 
  CIR.EXCHANGE_CARRIER_CIRCUIT_ID,
  NL1.CLLI_CODE,
  NL2.CLLI_CODE, 
  SC.SVC_CATG_NM 
)
--
WHERE ACT_IND IN ('N','D')
AND (SUPP_TYPE <> '1' OR SUPP_TYPE IS NULL)
AND (CCNA NOT IN ('ZTK') OR CCNA IS NULL)
AND (CATG <> 'Retail' OR CATG IS NULL)
--
ORDER BY 1
