SELECT DOCUMENT_NUMBER, PON, ACTIVITY_INDICATOR, NAME, CCNA, STATE,
       CASE NC
         WHEN 'HC' THEN 'DS1'
         WHEN 'HF' THEN 'DS3'
         WHEN 'KD' THEN 'TLS/Optical'
         WHEN 'KE' THEN 'TLS/Optical'
         WHEN 'KF' THEN 'Optical'
         WHEN 'KQ' THEN 'TLS/Optical'
         WHEN 'KR' THEN 'Optical'
         WHEN 'LD' THEN 'DS0'
         WHEN 'LG' THEN 'DS0'
         WHEN 'OB' THEN 'SONET/Optical'
         WHEN 'SD' THEN 'Switched Facility'
         WHEN 'SH' THEN 'Switched Facility'
         WHEN 'UC' THEN 'DS0'
         WHEN 'XD' THEN 'DS0'
         WHEN 'XG' THEN 'DS0'
         WHEN 'XH' THEN 'DS0'
         ELSE 'OTHER' END SERVICE_CODE,
       NC, ACTUAL_COMP_DT, TASK_TYPE, DD_TASK_STATUS, DUE_DATE
FROM (
SELECT TSK.DOCUMENT_NUMBER, 
       MAX(ASR.PON) KEEP (dense_rank last ORDER BY asr.last_modified_date) PON, 
       ASR.ACTIVITY_INDICATOR, 
       MAX(SR.CCNA_NAME) KEEP (dense_rank last ORDER BY sr.last_modified_date) NAME,  
       MAX(SR.CCNA) KEEP (dense_rank last ORDER BY sr.last_modified_date) CCNA,
       MAX(SUBSTR(NL.CLLI_CODE,5,2)) KEEP (dense_rank last ORDER BY nl.last_modified_date) STATE, 
       MAX(ASR.NETWORK_CHANNEL_SERVICE_CODE) KEEP (dense_rank last ORDER BY asr.last_modified_date) NC,              
       MAX(TSK.ACTUAL_COMPLETION_DATE) KEEP (dense_rank last ORDER BY asr.last_modified_date) Actual_Comp_DT,
         MAX(ASR.SUPPLEMENT_TYPE) KEEP (dense_rank last ORDER BY asr.last_modified_date) SUP,
       TSK.TASK_TYPE,
       TSK.TASK_STATUS DD_TASK_STATUS, 
       MAX(ASR.DESIRED_DUE_DATE) KEEP (dense_rank last ORDER BY asr.last_modified_date) Due_Date
FROM CASDW.TASK TSK, CASDW.ACCESS_SERVICE_REQUEST ASR, CASDW.SERV_REQ SR, CASDW.NETWORK_LOCATION NL
WHERE ASR.DOCUMENT_NUMBER=TSK.DOCUMENT_NUMBER 
AND SR.DOCUMENT_NUMBER=TSK.DOCUMENT_NUMBER 
AND ASR.LOCATION_ID = NL.LOCATION_ID(+) 
AND NOT ASR.ACCESS_PROVIDER_SERV_CTR_CODE IS NULL 
AND SR.CCNA<>'CUS' 
AND TSK.TASK_STATUS IN ('Complete', 'Pending', 'Ready') 
AND TSK.TASK_TYPE='DD' 
AND ASR.ACTIVITY_INDICATOR IN ('D', 'N') 
AND ASR.ORDER_TYPE IN ('ASR','SO') 
AND (TO_CHAR(TSK.ACTUAL_COMPLETION_DATE, 'YYYYMM') BETWEEN '201301' AND '201310' OR TSK.ACTUAL_COMPLETION_DATE IS NULL)
--AND (TO_CHAR(TSK.ACTUAL_COMPLETION_DATE, 'YYYYMM') >= '201211' OR TSK.ACTUAL_COMPLETION_DATE IS NULL)
GROUP BY TSK.DOCUMENT_NUMBER, ASR.ACTIVITY_INDICATOR, TSK.TASK_TYPE, TSK.TASK_STATUS
)
WHERE (SUP <> 1 OR SUP IS NULL)
ORDER BY 1,9
