select DW_LOAD_DATE_TIME, FLD_EVENT_END_TIME, FLD_EVENTSTARTTIME, FLD_MODIFIEDDATE, FLD_ONHOLDUNTILDATE, FLD_REQUESTDATE, FLD_STARTDATE, FLD_WO_CREATED_DATE,  FLD_CUSTOMERTIMEOFPROBLEM, FLD_MTTACKNOWLEDGE, 
FLD_MTTCREATION, FLD_MTTHANDLE, FLD_MTTREPAIR, FLD_OUT_OF_SERVICE, FLD_REQUESTPRIORITY, FLD_REQUESTSTATE, H_PRESENTSTATE, H_PREVIOUS_STATE, H_FLD_TIME_SECS_INASSIGNED, H_FLD_TIME_SECS_INCLEARED, 
H_FLD_TIME_SECS_INNEW_, H_FLD_TIME_SECS_INOPEN_ACTIVE, H_FLD_TIME_SECS_INPENDING, H_FLD_TIMETOTALINSECS, H_FLD_TOTALCLOSEDTIME_SECS_, H_FLD_TOTALOPENTIME_SECS_, H_FLD_TOTALPENDINGTIME_SECS_, H_ACTIVITY, 
H_DESCRIPTIONOFSYMPTOMCOPY, H_FLD_ASSIGNEDPERSON, FLD_REQUESTTITLE, H_SUBJECT001, FLD_CORRELATIONTICKETID, FLD_REQUESTID, FLD_REASONCODEFIELD, FLD_SITENAME, FLD_DESCRIPTIONOFSYMPTON, FLD_IMPACTOFSERVICE, 
FLD_LASTMODIFIEDBY, FLD_SUBMITTER, FLD_NETWORKELEMENT, FLD_RETURNCODEDESCRIPTION, FLD_TECHNOLOGY, H_FLD_CUSTOMERSTATUS, H_PREVIOUSSTATUS, FLD_TICKETPRIORITY, FLD_REQUESTSTATUS, FLD_SITEID, 
H_FLD_TIME_IN_CLEARED, H_FLD_TIMEINOPEN_ACTIVE, H_FLD_TIMEINPENDING, H_FLD_TIMEINQUEUEDASSIGNED, H_FLD_TIMEINQUEUEDNEW, H_FLD_TIMETOTALTEXTVALUE, H_PRESENTSTATUS_, FLD_TOTALCLOSEDTIME, FLD_TOTALOPENTIME, 
FLD_TOTALPENDINGTIME, FLD_REQUESTTYPE, FLD_SLACODE, H__ADDITIONALINFODETAIL
from trouble_ticket_r





select FLD_REQUESTDATE, FLD_AUDITMODIFIEDDATE, FLD_AGREEDSTART, FLD_AGREEDEND, FLD_ACTUALSTART, FLD_ACTUALEND, FLD_REQUESTEDSTART, FLD_ESTIMATEDREADYTIME, FLD_TARGETDATETIME, FLD_TROUBLETICKETDETECTIONDATE, 
FLD_TROUBLE_DETECTION_DATE, FLD_STATUSDATE, DW_LOAD_DATE_TIME, FLD_REQUESTSTATE, STATUS, FLD_TROUBLEREPORTSTATUSNUMBERI, FLD_SEVERITYLEVELINT, FLD_ACTIONTYPE, FLD_TROUBLETYPEINT, FLD_REPEATREPORT, 
FLD_TROUBLETYPE,  FLD_DISPATCH_NOTES, FLD_TICKETSTATEINT, FLD_TROUBLEFOUNDINT, FLD_TICKET_PRIORITYINT, H_TIME_SECS_INNEW_, H_TIME_SECS_INASSIGNED, H_TIME_SECS_INOPEN_ACTIVE, H_TIME_SECS_INPENDING, 
H_TIME_SECS_INCLEARED, H_TOTALOPENTIME_SECS_, H_TOTALPENDINGTIME_SECS_, H_TOTALCLOSEDTIME_SECS_, H_TIMETOTALINSECS, FLD_CITY, FLD_STATE, FLD_REQUESTID, FLD_FAULTTYPE, FLD_DESCRIPTIONOFWORKORDER, 
FLD_CIRCUIT_DESIGN__ID, FLD_REQUESTTITLE, FLD_REQUESTTYPE, FLD_REQUESTSTATUS, FLD_TICKETID, H_PARENTREQUESTID, FLD_STARTDATE, FLD_SEVERITYLEVELTXT, FLD_TICKETSTATETXT, FLD_CUSTOMERPREMISECITY, 
FLD_CUSTOMERPREMISESTATE, FLD_TROUBLETYPETXT, FLD_APPLICATIONIDH, FLD_VFOUSERID, FLD_TROUBLEFOUNDTXT, FLD_ADDITIONALTROUBLEINFO1, FLD_ADDITIONALTROUBLEINFO2, FLD_COMPLETE_CAUSECODE, FLD_COMPLETE_REPAIRCODE, 
FLD_COMPLETE_FAULTLOCATION, FLD_EXCHANGENAME, FLD_OPERATING_COMPANY_NUMBER, FLD_VNETSTATUS, FLD_WOID, FLD_ADDITIONALNOTES, FLD_CAUSECODE, EXCHANGE_CARRIER_CIRCUIT_ID, FLD_SITEID
from work_order_r