SELECT CARRIER, ACNA, ASR_PON, ASR_ORDER_NO, ACT, PROJ_ID, PNUM, UNI, UNI_STATUS, C2.EXCHANGE_CARRIER_CIRCUIT_ID EVC,
       DECODE (C2.STATUS,
                  '1', 'Pending',
                  '2', 'Assigned',
                  '3', 'In Progress',
                  '4', 'Record Issued',
                  '5', 'DLR Issued',
                  '6', 'In Service',
                  '7', 'Pending Disconnect',
                  '8', 'Disconnected',
                  '9', 'Problem',
                  'A', 'Cancelled',
                  NULL
                 ) EVC_STATUS,
       BDW, DATE_REC, DUE_DATE, ACCEPT_DATE, COMP_DT, ADDRESS, CITY, STATE
FROM (
SELECT DISTINCT AM.PRIMARY_CARRIER_NAME CARRIER, SR.ACNA, C.EXCHANGE_CARRIER_CIRCUIT_ID UNI,
       DECODE (C.STATUS,
                  '1', 'Pending',
                  '2', 'Assigned',
                  '3', 'In Progress',
                  '4', 'Record Issued',
                  '5', 'DLR Issued',
                  '6', 'In Service',
                  '7', 'Pending Disconnect',
                  '8', 'Disconnected',
                  '9', 'Problem',
                  'A', 'Cancelled',
                  NULL
                 ) UNI_STATUS, 
       SR.PON ASR_PON, SR.DOCUMENT_NUMBER ASR_ORDER_NO, SR.ACTIVITY_IND ACT, ASR.PROJECT_IDENTIFICATION PROJ_ID, ASR.PROMOTION_NBR PNUM, EVC.BDW||EVC.BDW2 BDW,
       TRUNC(ASR.DATE_TIME_SENT) DATE_REC, TRUNC(ASR.DESIRED_DUE_DATE) DUE_DATE, TRUNC(AUD.ACCEPTANCE_DATE) ACCEPT_DATE, TRUNC(T.ACTUAL_COMPLETION_DATE) COMP_DT,
       TRIM (SALI.SANO||' '||SALI.SASN||' '||SALI.SATH) AS ADDRESS, SALI.CITY, SUBSTR(SALI.STATE,1,2) STATE 
FROM SERV_REQ SR,
     ACCESS_SERVICE_REQUEST ASR,
     TASK T,
     ASR_USER_DATA AUD,
     SERVICE_REQUEST_CIRCUIT SRC,
     CIRCUIT C,
     DATA_EXT.ASR_SALI SALI,
     ASR_OM.ASR_ACCOUNT_MANAGER AM,
     DATA_EXT.ASR_EVC EVC
 WHERE SR.DOCUMENT_NUMBER = ASR.DOCUMENT_NUMBER
   AND SR.DOCUMENT_NUMBER = T.DOCUMENT_NUMBER (+)
   AND SR.DOCUMENT_NUMBER = SALI.DOCUMENT_NUMBER (+)
   AND SR.DOCUMENT_NUMBER = AUD.DOCUMENT_NUMBER (+)
   AND SR.ACNA = AM.SECONDARY_ID (+)
   AND SR.DOCUMENT_NUMBER = EVC.DOCUMENT_NUMBER (+)
   AND SR.DOCUMENT_NUMBER = SRC.DOCUMENT_NUMBER (+)
   AND SRC.CIRCUIT_DESIGN_ID = C.CIRCUIT_DESIGN_ID (+)
   AND SUBSTR(C.EXCHANGE_CARRIER_CIRCUIT_ID,4,1) <> 'V'
   AND T.TASK_TYPE = 'DD'
   AND (SR.SUPPLEMENT_TYPE <> '1' OR SR.SUPPLEMENT_TYPE IS NULL)
   AND SR.ACTIVITY_IND = 'N'  -- DO I NEED TO SEARCH FOR CARRIERS USING A C ORDER FOR THIS OR WILL THOSE BE REJECTED UPFRONT? 
   AND SUBSTR(ASR.PROMOTION_NBR,1,7) = 'EIAV006' AND SUBSTR(ASR.PROMOTION_NBR,8,3) <> 'ICB'
) SQ1,
  SERVICE_REQUEST_CIRCUIT SRC2,
     CIRCUIT C2
  WHERE SQ1.ASR_ORDER_NO = SRC2.DOCUMENT_NUMBER (+)
    AND SRC2.CIRCUIT_DESIGN_ID = C2.CIRCUIT_DESIGN_ID (+)
    AND SUBSTR(C2.EXCHANGE_CARRIER_CIRCUIT_ID,4,1) = 'V' 
       
