commit;

drop table west_hierarchy;

create table west_hierarchy
(
region   		 VARCHAR2(255 BYTE),
territory 		 VARCHAR2(255 BYTE),
NPA		 	     VARCHAR2(255 BYTE),
NXX		 	     VARCHAR2(255 BYTE),
NPANXX		 	 VARCHAR2(255 BYTE),
CLLI6			 VARCHAR2(255 BYTE),
LOCAL_GM	 	 VARCHAR2(255 BYTE),
SVP_GM	 	 	 VARCHAR2(255 BYTE),
AREA_NAME		 VARCHAR2(255 BYTE)
);



INSERT ALL
into west_hierarchy values ('West','Oregon/Washington','360','225','360225','WDLDWA','WAGGONER','ANDERSON','OR')
into west_hierarchy values ('West','Oregon/Washington','360','335','360335','WSHGWA','WAGGONER','ANDERSON','OR')
into west_hierarchy values ('West','Oregon/Washington','360','835','360835','WSHGWA','WAGGONER','ANDERSON','OR')
into west_hierarchy values ('West','Oregon/Washington','360','837','360837','WSRVWA','WAGGONER','ANDERSON','OR')
into west_hierarchy values ('West','Oregon/Washington','503','259','503259','ALOHOR','DANIELSON','ANDERSON','OR')
into west_hierarchy values ('West','Oregon/Washington','503','277','503277','BVTNOR','DANIELSON','ANDERSON','OR')
into west_hierarchy values ('West','Oregon/Washington','503','324','503324','BNKSOR','DANIELSON','ANDERSON','OR')
into west_hierarchy values ('West','Oregon/Washington','503','350','503350','BVTNOR','DANIELSON','ANDERSON','OR')
into west_hierarchy values ('West','Oregon/Washington','503','356','503356','ALOHOR','DANIELSON','ANDERSON','OR')
into west_hierarchy values ('West','Oregon/Washington','503','357','503357','FRGVOR','DANIELSON','ANDERSON','OR')
into west_hierarchy values ('West','Oregon/Washington','503','359','503359','FRGVOR','DANIELSON','ANDERSON','OR')
into west_hierarchy values ('West','Oregon/Washington','503','429','503429','VRNNOR','WAGGONER','ANDERSON','OR')
into west_hierarchy values ('West','Oregon/Washington','503','431','503431','TGRDOR','DANIELSON','ANDERSON','OR')
into west_hierarchy values ('West','Oregon/Washington','503','434','503434','MMVLOR','DANIELSON','ANDERSON','OR')
into west_hierarchy values ('West','Oregon/Washington','503','435','503435','MMVLOR','DANIELSON','ANDERSON','OR')
into west_hierarchy values ('West','Oregon/Washington','503','439','503439','SMRWOR','DANIELSON','ANDERSON','OR')
into west_hierarchy values ('West','Oregon/Washington','503','443','503443','TGRDOR','DANIELSON','ANDERSON','OR')
into west_hierarchy values ('West','Oregon/Washington','503','453','503453','TGRDOR','DANIELSON','ANDERSON','OR')
into west_hierarchy values ('West','Oregon/Washington','503','465','503465','GRHMOR','WAGGONER','ANDERSON','OR')
into west_hierarchy values ('West','Oregon/Washington','503','466','503466','SMRWOR','DANIELSON','ANDERSON','OR')
into west_hierarchy values ('West','Oregon/Washington','503','469','503469','BVTNOR','DANIELSON','ANDERSON','OR')
into west_hierarchy values ('West','Oregon/Washington','503','472','503472','MMVLOR','DANIELSON','ANDERSON','OR')
into west_hierarchy values ('West','Oregon/Washington','503','474','503474','MMVLOR','DANIELSON','ANDERSON','OR')
into west_hierarchy values ('West','Oregon/Washington','503','491','503491','GRHMOR','WAGGONER','ANDERSON','OR')
into west_hierarchy values ('West','Oregon/Washington','503','492','503492','GRHMOR','WAGGONER','ANDERSON','OR')
into west_hierarchy values ('West','Oregon/Washington','503','520','503520','BVTNOR','DANIELSON','ANDERSON','OR')
into west_hierarchy values ('West','Oregon/Washington','503','521','503521','TGRDOR','DANIELSON','ANDERSON','OR')
into west_hierarchy values ('West','Oregon/Washington','503','524','503524','TGRDOR','DANIELSON','ANDERSON','OR')
into west_hierarchy values ('West','Oregon/Washington','503','526','503526','BVTNOR','DANIELSON','ANDERSON','OR')
into west_hierarchy values ('West','Oregon/Washington','503','531','503531','SMRWOR','DANIELSON','ANDERSON','OR')
into west_hierarchy values ('West','Oregon/Washington','503','533','503533','SMRWOR','DANIELSON','ANDERSON','OR')
into west_hierarchy values ('West','Oregon/Washington','503','537','503537','NWBROR','DANIELSON','ANDERSON','OR')
into west_hierarchy values ('West','Oregon/Washington','503','538','503538','NWBROR','DANIELSON','ANDERSON','OR')
into west_hierarchy values ('West','Oregon/Washington','503','547','503547','HLBOOR','DANIELSON','ANDERSON','OR')
into west_hierarchy values ('West','Oregon/Washington','503','554','503554','NWBROR','DANIELSON','ANDERSON','OR')
into west_hierarchy values ('West','Oregon/Washington','503','558','503558','SNSDOR','WAGGONER','ANDERSON','OR')
into west_hierarchy values ('West','Oregon/Washington','503','570','503570','WIVLOR','DANIELSON','ANDERSON','OR')
into west_hierarchy values ('West','Oregon/Washington','503','574','503574','BVTNOR','DANIELSON','ANDERSON','OR')
into west_hierarchy values ('West','Oregon/Washington','503','578','503578','BVTNOR','DANIELSON','ANDERSON','OR')
into west_hierarchy values ('West','Oregon/Washington','503','579','503579','TGRDOR','DANIELSON','ANDERSON','OR')
into west_hierarchy values ('West','Oregon/Washington','503','582','503582','WIVLOR','DANIELSON','ANDERSON','OR')
into west_hierarchy values ('West','Oregon/Washington','503','590','503590','TGRDOR','DANIELSON','ANDERSON','OR')
into west_hierarchy values ('West','Oregon/Washington','503','591','503591','ALOHOR','DANIELSON','ANDERSON','OR')
into west_hierarchy values ('West','Oregon/Washington','503','596','503596','BVTNOR','DANIELSON','ANDERSON','OR')
into west_hierarchy values ('West','Oregon/Washington','503','598','503598','TGRDOR','DANIELSON','ANDERSON','OR')
into west_hierarchy values ('West','Oregon/Washington','503','603','503603','TGRDOR','DANIELSON','ANDERSON','OR')
into west_hierarchy values ('West','Oregon/Washington','503','605','503605','BVTNOR','DANIELSON','ANDERSON','OR')
into west_hierarchy values ('West','Oregon/Washington','503','612','503612','TULTOR','DANIELSON','ANDERSON','OR')
into west_hierarchy values ('West','Oregon/Washington','503','614','503614','SMRWOR','DANIELSON','ANDERSON','OR')
into west_hierarchy values ('West','Oregon/Washington','503','615','503615','HLBOOR','DANIELSON','ANDERSON','OR')
into west_hierarchy values ('West','Oregon/Washington','503','617','503617','SMRWOR','DANIELSON','ANDERSON','OR')
into west_hierarchy values ('West','Oregon/Washington','503','618','503618','GRHMOR','WAGGONER','ANDERSON','OR')
into west_hierarchy values ('West','Oregon/Washington','503','620','503620','TGRDOR','DANIELSON','ANDERSON','OR')
into west_hierarchy values ('West','Oregon/Washington','503','622','503622','HDLDOR','WAGGONER','ANDERSON','OR')
into west_hierarchy values ('West','Oregon/Washington','503','624','503624','TGRDOR','DANIELSON','ANDERSON','OR')
into west_hierarchy values ('West','Oregon/Washington','503','625','503625','SHWDOR','DANIELSON','ANDERSON','OR')
into west_hierarchy values ('West','Oregon/Washington','503','626','503626','BVTNOR','DANIELSON','ANDERSON','OR')
into west_hierarchy values ('West','Oregon/Washington','503','627','503627','BVTNOR','DANIELSON','ANDERSON','OR')
into west_hierarchy values ('West','Oregon/Washington','503','628','503628','SCHLOR','DANIELSON','ANDERSON','OR')
into west_hierarchy values ('West','Oregon/Washington','503','629','503629','SMRWOR','DANIELSON','ANDERSON','OR')
into west_hierarchy values ('West','Oregon/Washington','503','638','503638','STFROR','DANIELSON','ANDERSON','OR')
into west_hierarchy values ('West','Oregon/Washington','503','639','503639','TGRDOR','DANIELSON','ANDERSON','OR')
into west_hierarchy values ('West','Oregon/Washington','503','640','503640','HLBOOR','DANIELSON','ANDERSON','OR')
into west_hierarchy values ('West','Oregon/Washington','503','641','503641','BVTNOR','DANIELSON','ANDERSON','OR')
into west_hierarchy values ('West','Oregon/Washington','503','642','503642','ALOHOR','DANIELSON','ANDERSON','OR')
into west_hierarchy values ('West','Oregon/Washington','503','643','503643','BVTNOR','DANIELSON','ANDERSON','OR')
into west_hierarchy values ('West','Oregon/Washington','503','644','503644','BVTNOR','DANIELSON','ANDERSON','OR')
into west_hierarchy values ('West','Oregon/Washington','503','645','503645','SMRWOR','DANIELSON','ANDERSON','OR')
into west_hierarchy values ('West','Oregon/Washington','503','646','503646','BVTNOR','DANIELSON','ANDERSON','OR')
into west_hierarchy values ('West','Oregon/Washington','503','648','503648','HLBOOR','DANIELSON','ANDERSON','OR')
into west_hierarchy values ('West','Oregon/Washington','503','649','503649','ALOHOR','DANIELSON','ANDERSON','OR')
into west_hierarchy values ('West','Oregon/Washington','503','658','503658','SNSDOR','WAGGONER','ANDERSON','OR')
into west_hierarchy values ('West','Oregon/Washington','503','660','503660','GRHMOR','WAGGONER','ANDERSON','OR')
into west_hierarchy values ('West','Oregon/Washington','503','661','503661','GRHMOR','WAGGONER','ANDERSON','OR')
into west_hierarchy values ('West','Oregon/Washington','503','662','503662','YMHLOR','DANIELSON','ANDERSON','OR')
into west_hierarchy values ('West','Oregon/Washington','503','663','503663','ORNTOR','WAGGONER','ANDERSON','OR')
into west_hierarchy values ('West','Oregon/Washington','503','665','503665','GRHMOR','WAGGONER','ANDERSON','OR')
into west_hierarchy values ('West','Oregon/Washington','503','666','503666','GRHMOR','WAGGONER','ANDERSON','OR')
into west_hierarchy values ('West','Oregon/Washington','503','667','503667','GRHMOR','WAGGONER','ANDERSON','OR')
into west_hierarchy values ('West','Oregon/Washington','503','668','503668','SNDYOR','DANIELSON','ANDERSON','OR')
into west_hierarchy values ('West','Oregon/Washington','503','669','503669','GRHMOR','WAGGONER','ANDERSON','OR')
into west_hierarchy values ('West','Oregon/Washington','503','670','503670','TGRDOR','DANIELSON','ANDERSON','OR')
into west_hierarchy values ('West','Oregon/Washington','503','671','503671','BVTNOR','DANIELSON','ANDERSON','OR')
into west_hierarchy values ('West','Oregon/Washington','503','672','503672','BVTNOR','DANIELSON','ANDERSON','OR')
into west_hierarchy values ('West','Oregon/Washington','503','673','503673','STFROR','DANIELSON','ANDERSON','OR')
into west_hierarchy values ('West','Oregon/Washington','503','674','503674','GRHMOR','WAGGONER','ANDERSON','OR')
into west_hierarchy values ('West','Oregon/Washington','503','677','503677','BVTNOR','DANIELSON','ANDERSON','OR')
into west_hierarchy values ('West','Oregon/Washington','503','681','503681','HLBOOR','DANIELSON','ANDERSON','OR')
into west_hierarchy values ('West','Oregon/Washington','503','682','503682','WIVLOR','DANIELSON','ANDERSON','OR')
into west_hierarchy values ('West','Oregon/Washington','503','684','503684','TGRDOR','DANIELSON','ANDERSON','OR')
into west_hierarchy values ('West','Oregon/Washington','503','685','503685','WIVLOR','DANIELSON','ANDERSON','OR')
into west_hierarchy values ('West','Oregon/Washington','503','690','503690','SMRWOR','DANIELSON','ANDERSON','OR')
into west_hierarchy values ('West','Oregon/Washington','503','692','503692','TULTOR','DANIELSON','ANDERSON','OR')
into west_hierarchy values ('West','Oregon/Washington','503','693','503693','HLBOOR','DANIELSON','ANDERSON','OR')
into west_hierarchy values ('West','Oregon/Washington','503','698','503698','VYVWOR','WAGGONER','ANDERSON','OR')
into west_hierarchy values ('West','Oregon/Washington','503','728','503728','CLTSOR','WAGGONER','ANDERSON','OR')
into west_hierarchy values ('West','Oregon/Washington','503','743','503743','TRNROR','WAGGONER','ANDERSON','OR')
into west_hierarchy values ('West','Oregon/Washington','503','749','503749','AMVLOR','WAGGONER','ANDERSON','OR')
into west_hierarchy values ('West','Oregon/Washington','503','825','503825','SHWDOR','DANIELSON','ANDERSON','OR')
into west_hierarchy values ('West','Oregon/Washington','503','826','503826','SNDYOR','DANIELSON','ANDERSON','OR')
into west_hierarchy values ('West','Oregon/Washington','503','835','503835','AMTYOR','DANIELSON','ANDERSON','OR')
into west_hierarchy values ('West','Oregon/Washington','503','844','503844','HLBOOR','DANIELSON','ANDERSON','OR')
into west_hierarchy values ('West','Oregon/Washington','503','846','503846','HLBOOR','DANIELSON','ANDERSON','OR')
into west_hierarchy values ('West','Oregon/Washington','503','848','503848','ALOHOR','DANIELSON','ANDERSON','OR')
into west_hierarchy values ('West','Oregon/Washington','503','854','503854','DTRTOR','WAGGONER','ANDERSON','OR')
into west_hierarchy values ('West','Oregon/Washington','503','864','503864','DYTNOR','DANIELSON','ANDERSON','OR')
into west_hierarchy values ('West','Oregon/Washington','503','868','503868','GDISOR','DANIELSON','ANDERSON','OR')
into west_hierarchy values ('West','Oregon/Washington','503','873','503873','SLTNOR','WAGGONER','ANDERSON','OR')
into west_hierarchy values ('West','Oregon/Washington','503','874','503874','SLTNOR','WAGGONER','ANDERSON','OR')
into west_hierarchy values ('West','Oregon/Washington','503','885','503885','TULTOR','DANIELSON','ANDERSON','OR')
into west_hierarchy values ('West','Oregon/Washington','503','897','503897','MLCYOR','WAGGONER','ANDERSON','OR')
into west_hierarchy values ('West','Oregon/Washington','503','925','503925','SHWDOR','DANIELSON','ANDERSON','OR')
into west_hierarchy values ('West','Oregon/Washington','503','968','503968','TGRDOR','DANIELSON','ANDERSON','OR')
into west_hierarchy values ('West','Oregon/Washington','503','985','503985','GSTNOR','DANIELSON','ANDERSON','OR')
into west_hierarchy values ('West','Oregon/Washington','503','992','503992','FRGVOR','DANIELSON','ANDERSON','OR')
into west_hierarchy values ('West','California','209','394','209394','LVTNCA','VACANT','BADER','CA')
into west_hierarchy values ('West','California','209','398','209398','LVTNCA','VACANT','BADER','CA')
into west_hierarchy values ('West','California','209','892','209892','PASNCA','VACANT','BADER','CA')
into west_hierarchy values ('West','California','209','894','209894','PASNCA','VACANT','BADER','CA')
into west_hierarchy values ('West','California','209','895','209895','PASNCA','VACANT','BADER','CA')
into west_hierarchy values ('West','California','209','928','209928','TLMNCA','VACANT','BADER','CA')
into west_hierarchy values ('West','California','408','897','408897','SNATCA','VACANT','BADER','CA')
into west_hierarchy values ('West','California','530','233','530233','ALTRCA','TAVIS','BADER','CA')
into west_hierarchy values ('West','California','530','234','530234','RADLCA','TAVIS','BADER','CA')
into west_hierarchy values ('West','California','530','251','530251','SSVLCA','TAVIS','BADER','CA')
into west_hierarchy values ('West','California','530','252','530252','SSVLCA','TAVIS','BADER','CA')
into west_hierarchy values ('West','California','530','253','530253','JNVLCA','TAVIS','BADER','CA')
into west_hierarchy values ('West','California','530','254','530254','STNDCA','TAVIS','BADER','CA')
into west_hierarchy values ('West','California','530','256','530256','WSWDCA','TAVIS','BADER','CA')
into west_hierarchy values ('West','California','530','257','530257','SSVLCA','TAVIS','BADER','CA')
into west_hierarchy values ('West','California','530','258','530258','CHTRCA','TAVIS','BADER','CA')
into west_hierarchy values ('West','California','530','259','530259','LKARCA','TAVIS','BADER','CA')
into west_hierarchy values ('West','California','530','279','530279','CDVLCA','TAVIS','BADER','CA')
into west_hierarchy values ('West','California','530','281','530281','KEDDCA','TAVIS','BADER','CA')
into west_hierarchy values ('West','California','530','284','530284','GNVLCA','TAVIS','BADER','CA')
into west_hierarchy values ('West','California','530','294','530294','BIBRCA','TAVIS','BADER','CA')
into west_hierarchy values ('West','California','530','299','530299','ADINCA','TAVIS','BADER','CA')
into west_hierarchy values ('West','California','530','335','530335','BRNYCA','TAVIS','BADER','CA')
into west_hierarchy values ('West','California','530','336','530336','FRMLCA','TAVIS','BADER','CA')
into west_hierarchy values ('West','California','530','337','530337','MNCKCA','TAVIS','BADER','CA')
into west_hierarchy values ('West','California','530','437','530437','GRMSCA','TAVIS','BADER','CA')
into west_hierarchy values ('West','California','530','438','530438','MXWLCA','TAVIS','BADER','CA')
into west_hierarchy values ('West','California','530','439','530439','PRTNCA','TAVIS','BADER','CA')
into west_hierarchy values ('West','California','530','458','530458','COLSCA','TAVIS','BADER','CA')
into west_hierarchy values ('West','California','530','472','530472','OKRNCA','TAVIS','BADER','CA')
into west_hierarchy values ('West','California','530','473','530473','WLMSCA','TAVIS','BADER','CA')
into west_hierarchy values ('West','California','530','474','530474','SHTNCA','TAVIS','BADER','CA')
into west_hierarchy values ('West','California','530','476','530476','ARBCCA','TAVIS','BADER','CA')
into west_hierarchy values ('West','California','530','547','530547','PLCDCA','TAVIS','BADER','CA')
into west_hierarchy values ('West','California','530','549','530549','BLVSCA','TAVIS','BADER','CA')
into west_hierarchy values ('West','California','530','595','530595','MNRLCA','TAVIS','BADER','CA')
into west_hierarchy values ('West','California','530','596','530596','LKARCA','TAVIS','BADER','CA')
into west_hierarchy values ('West','California','530','597','530597','PYCKCA','TAVIS','BADER','CA')
into west_hierarchy values ('West','California','530','796','530796','GUNDCA','VACANT','BADER','CA')
into west_hierarchy values ('West','California','530','825','530825','EGLKCA','TAVIS','BADER','CA')
into west_hierarchy values ('West','California','530','827','530827','HRLNCA','TAVIS','BADER','CA')
into west_hierarchy values ('West','California','530','964','530964','MCLDCA','TAVIS','BADER','CA')
into west_hierarchy values ('West','California','707','374','707374','RIVSCA','CLINE','BADER','CA')
into west_hierarchy values ('West','California','707','378','707378','RIVSCA','CLINE','BADER','CA')
into west_hierarchy values ('West','California','707','629','707629','PTRLCA','TAVIS','BADER','CA')
into west_hierarchy values ('West','California','707','786','707786','FNDLCA','TAVIS','BADER','CA')
into west_hierarchy values ('West','California','916','405','916405','EKGVCA','CLINE','BADER','CA')
into west_hierarchy values ('West','California','916','423','916423','EKGVCA','CLINE','BADER','CA')
into west_hierarchy values ('West','California','916','478','916478','EKGVCA','CLINE','BADER','CA')
into west_hierarchy values ('West','California','916','509','916509','EKGVCA','CLINE','BADER','CA')
into west_hierarchy values ('West','California','916','512','916512','EKGVCA','CLINE','BADER','CA')
into west_hierarchy values ('West','California','916','525','916525','EKGVCA','CLINE','BADER','CA')
into west_hierarchy values ('West','California','916','544','916544','EKGVCA','CLINE','BADER','CA')
into west_hierarchy values ('West','California','916','627','916627','EKGVCA','CLINE','BADER','CA')
into west_hierarchy values ('West','California','916','665','916665','MDVWCA','CLINE','BADER','CA')
into west_hierarchy values ('West','California','916','667','916667','EKGVCA','CLINE','BADER','CA')
into west_hierarchy values ('West','California','916','681','916681','EKGVCA','CLINE','BADER','CA')
into west_hierarchy values ('West','California','916','682','916682','EKGVCA','CLINE','BADER','CA')
into west_hierarchy values ('West','California','916','683','916683','EKGVCA','CLINE','BADER','CA')
into west_hierarchy values ('West','California','916','684','916684','EKGVCA','CLINE','BADER','CA')
into west_hierarchy values ('West','California','916','685','916685','EKGVCA','CLINE','BADER','CA')
into west_hierarchy values ('West','California','916','686','916686','EKGVCA','CLINE','BADER','CA')
into west_hierarchy values ('West','California','916','687','916687','EKGVCA','CLINE','BADER','CA')
into west_hierarchy values ('West','California','916','688','916688','EKGVCA','CLINE','BADER','CA')
into west_hierarchy values ('West','California','916','689','916689','EKGVCA','CLINE','BADER','CA')
into west_hierarchy values ('West','California','916','690','916690','EKGVCA','CLINE','BADER','CA')
into west_hierarchy values ('West','California','916','691','916691','EKGVCA','CLINE','BADER','CA')
into west_hierarchy values ('West','California','916','714','916714','EKGVCA','CLINE','BADER','CA')
into west_hierarchy values ('West','California','916','744','916744','CLBGCA','CLINE','BADER','CA')
into west_hierarchy values ('West','California','916','775','916775','CRLDCA','CLINE','BADER','CA')
into west_hierarchy values ('West','California','916','776','916776','WLGVCA','CLINE','BADER','CA')
into west_hierarchy values ('West','California','916','777','916777','ISTNCA','CLINE','BADER','CA')
into west_hierarchy values ('West','California','916','895','916895','EKGVCA','CLINE','BADER','CA')
into west_hierarchy values ('West','California','916','896','916896','EKGVCA','CLINE','BADER','CA')
into west_hierarchy values ('West','California','916','897','916897','EKGVCA','CLINE','BADER','CA')
into west_hierarchy values ('West','Oregon/Washington','541','247','541247','GLBHOR','MARTIN','BADER','CA')
into west_hierarchy values ('West','Oregon/Washington','541','266','541266','CSBYOR','MARTIN','BADER','CA')
into west_hierarchy values ('West','Oregon/Washington','541','267','541267','CSBYOR','MARTIN','BADER','CA')
into west_hierarchy values ('West','Oregon/Washington','541','269','541269','CSBYOR','MARTIN','BADER','CA')
into west_hierarchy values ('West','Oregon/Washington','541','271','541271','RDPTOR','MARTIN','BADER','CA')
into west_hierarchy values ('West','Oregon/Washington','541','332','541332','PTOROR','MARTIN','BADER','CA')
into west_hierarchy values ('West','Oregon/Washington','541','347','541347','BNDNOR','MARTIN','BADER','CA')
into west_hierarchy values ('West','Oregon/Washington','541','348','541348','LNGLOR','MARTIN','BADER','CA')
into west_hierarchy values ('West','Oregon/Washington','541','396','541396','CQLLOR','MARTIN','BADER','CA')
into west_hierarchy values ('West','Oregon/Washington','541','412','541412','BKNGOR','MARTIN','BADER','CA')
into west_hierarchy values ('West','Oregon/Washington','541','439','541439','PWRSOR','MARTIN','BADER','CA')
into west_hierarchy values ('West','Oregon/Washington','541','469','541469','BKNGOR','MARTIN','BADER','CA')
into west_hierarchy values ('West','Oregon/Washington','541','572','541572','MYPNOR','MARTIN','BADER','CA')
into west_hierarchy values ('West','Oregon/Washington','541','592','541592','CVJTOR','MARTIN','BADER','CA')
into west_hierarchy values ('West','Oregon/Washington','541','596','541596','OBRNOR','MARTIN','BADER','CA')
into west_hierarchy values ('West','Oregon/Washington','541','597','541597','SELMOR','MARTIN','BADER','CA')
into west_hierarchy values ('West','Oregon/Washington','541','751','541751','NBNDOR','MARTIN','BADER','CA')
into west_hierarchy values ('West','Oregon/Washington','541','756','541756','NBNDOR','MARTIN','BADER','CA')
into west_hierarchy values ('West','Oregon/Washington','541','759','541759','LKSDOR','MARTIN','BADER','CA')
into west_hierarchy values ('West','Oregon/Washington','541','825','541825','DYCKOR','MARTIN','BADER','CA')
into west_hierarchy values ('West','Oregon/Washington','541','832','541832','GLDLOR','MARTIN','BADER','CA')
into west_hierarchy values ('West','Oregon/Washington','541','837','541837','AZALOR','MARTIN','BADER','CA')
into west_hierarchy values ('West','Oregon/Washington','541','839','541839','CNVLOR','MARTIN','BADER','CA')
into west_hierarchy values ('West','Oregon/Washington','541','846','541846','PRVTOR','MARTIN','BADER','CA')
into west_hierarchy values ('West','Oregon/Washington','541','860','541860','MYCKOR','MARTIN','BADER','CA')
into west_hierarchy values ('West','Oregon/Washington','541','862','541862','MRPHOR','MARTIN','BADER','CA')
into west_hierarchy values ('West','Oregon/Washington','541','863','541863','MYCKOR','MARTIN','BADER','CA')
into west_hierarchy values ('West','Oregon/Washington','541','866','541866','WLCKOR','MARTIN','BADER','CA')
into west_hierarchy values ('West','Oregon/Washington','541','874','541874','RDDLOR','MARTIN','BADER','CA')
into west_hierarchy values ('West','Oregon/Washington','541','888','541888','EMPROR','MARTIN','BADER','CA')
into west_hierarchy values ('West','Oregon/Washington','707','457','707457','GSQTCA','MARTIN','BADER','CA')
into west_hierarchy values ('West','Oregon/Washington','707','458','707458','HICHCA','MARTIN','BADER','CA')
into west_hierarchy values ('West','Oregon/Washington','707','464','707464','CRCYCA','MARTIN','BADER','CA')
into west_hierarchy values ('West','Oregon/Washington','707','465','707465','CRCYCA','MARTIN','BADER','CA')
into west_hierarchy values ('West','Oregon/Washington','707','482','707482','KLMTCA','MARTIN','BADER','CA')
into west_hierarchy values ('West','Oregon/Washington','707','487','707487','SMRVCA','MARTIN','BADER','CA')
into west_hierarchy values ('West','Oregon/Washington','707','488','707488','ORICCA','MARTIN','BADER','CA')
into west_hierarchy values ('West','Oregon/Washington','206','533','206533','RCBHWA','BURGE','OXLEY','WA')
into west_hierarchy values ('West','Oregon/Washington','206','542','206542','RCBHWA','BURGE','OXLEY','WA')
into west_hierarchy values ('West','Oregon/Washington','206','546','206546','RCBHWA','BURGE','OXLEY','WA')
into west_hierarchy values ('West','Oregon/Washington','206','754','206754','RDMDWA','LARSEN','OXLEY','WA')
into west_hierarchy values ('West','Oregon/Washington','360','267','360267','GRLDWA','BURGE','OXLEY','WA')
into west_hierarchy values ('West','Oregon/Washington','360','268','360268','WSPTWA','BURGE','OXLEY','WA')
into west_hierarchy values ('West','Oregon/Washington','360','387','360387','CMISWA','BALDWIN','OXLEY','WA')
into west_hierarchy values ('West','Oregon/Washington','360','403','360403','ARTNWA','BALDWIN','OXLEY','WA')
into west_hierarchy values ('West','Oregon/Washington','360','435','360435','ARTNWA','BALDWIN','OXLEY','WA')
into west_hierarchy values ('West','Oregon/Washington','360','436','360436','DRTNWA','BALDWIN','OXLEY','WA')
into west_hierarchy values ('West','Oregon/Washington','360','474','360474','ARTNWA','BALDWIN','OXLEY','WA')
into west_hierarchy values ('West','Oregon/Washington','360','563','360563','SNHSWA','BALDWIN','OXLEY','WA')
into west_hierarchy values ('West','Oregon/Washington','360','568','360568','SNHSWA','BALDWIN','OXLEY','WA')
into west_hierarchy values ('West','Oregon/Washington','360','629','360629','STWDWA','BALDWIN','OXLEY','WA')
into west_hierarchy values ('West','Oregon/Washington','360','651','360651','MYVIWA','BALDWIN','OXLEY','WA')
into west_hierarchy values ('West','Oregon/Washington','360','652','360652','LKGWWA','BALDWIN','OXLEY','WA')
into west_hierarchy values ('West','Oregon/Washington','360','653','360653','MYVIWA','BALDWIN','OXLEY','WA')
into west_hierarchy values ('West','Oregon/Washington','360','654','360654','LKGWWA','BALDWIN','OXLEY','WA')
into west_hierarchy values ('West','Oregon/Washington','360','657','360657','MYVIWA','BALDWIN','OXLEY','WA')
into west_hierarchy values ('West','Oregon/Washington','360','658','360658','MYVIWA','BALDWIN','OXLEY','WA')
into west_hierarchy values ('West','Oregon/Washington','360','659','360659','MYVIWA','BALDWIN','OXLEY','WA')
into west_hierarchy values ('West','Oregon/Washington','360','668','360668','CLVWWA','BALDWIN','OXLEY','WA')
into west_hierarchy values ('West','Oregon/Washington','360','677','360677','SKYKWA','LARSEN','OXLEY','WA')
into west_hierarchy values ('West','Oregon/Washington','360','691','360691','GRFLWA','BALDWIN','OXLEY','WA')
into west_hierarchy values ('West','Oregon/Washington','360','716','360716','MYVIWA','BALDWIN','OXLEY','WA')
into west_hierarchy values ('West','Oregon/Washington','360','793','360793','SULTWA','LARSEN','OXLEY','WA')
into west_hierarchy values ('West','Oregon/Washington','360','794','360794','MONRWA','BALDWIN','OXLEY','WA')
into west_hierarchy values ('West','Oregon/Washington','360','799','360799','SULTWA','LARSEN','OXLEY','WA')
into west_hierarchy values ('West','Oregon/Washington','360','805','360805','MONRWA','BALDWIN','OXLEY','WA')
into west_hierarchy values ('West','Oregon/Washington','360','862','360862','SNHSWA','BALDWIN','OXLEY','WA')
into west_hierarchy values ('West','Oregon/Washington','360','863','360863','MONRWA','BALDWIN','OXLEY','WA')
into west_hierarchy values ('West','Oregon/Washington','360','939','360939','STWDWA','BALDWIN','OXLEY','WA')
into west_hierarchy values ('West','Oregon/Washington','360','973','360973','STPSWA','LARSEN','OXLEY','WA')
into west_hierarchy values ('West','Oregon/Washington','425','225','425225','SLLKWA','BALDWIN','OXLEY','WA')
into west_hierarchy values ('West','Oregon/Washington','425','252','425252','EVRTWA','BALDWIN','OXLEY','WA')
into west_hierarchy values ('West','Oregon/Washington','425','257','425257','EVRTWA','BALDWIN','OXLEY','WA')
into west_hierarchy values ('West','Oregon/Washington','425','258','425258','EVRTWA','BALDWIN','OXLEY','WA')
into west_hierarchy values ('West','Oregon/Washington','425','259','425259','EVRTWA','BALDWIN','OXLEY','WA')
into west_hierarchy values ('West','Oregon/Washington','425','261','425261','EVRTWA','BALDWIN','OXLEY','WA')
into west_hierarchy values ('West','Oregon/Washington','425','262','425262','EVRTWA','BALDWIN','OXLEY','WA')
into west_hierarchy values ('West','Oregon/Washington','425','263','425263','EVRTWA','BALDWIN','OXLEY','WA')
into west_hierarchy values ('West','Oregon/Washington','425','265','425265','EVRTWA','BALDWIN','OXLEY','WA')
into west_hierarchy values ('West','Oregon/Washington','425','266','425266','EVRTWA','BALDWIN','OXLEY','WA')
into west_hierarchy values ('West','Oregon/Washington','425','267','425267','EVRTWA','BALDWIN','OXLEY','WA')
into west_hierarchy values ('West','Oregon/Washington','425','288','425288','BOTHWA','BURGE','OXLEY','WA')
into west_hierarchy values ('West','Oregon/Washington','425','290','425290','EVRTWA','BALDWIN','OXLEY','WA')
into west_hierarchy values ('West','Oregon/Washington','425','297','425297','EVRTWA','BALDWIN','OXLEY','WA')
into west_hierarchy values ('West','Oregon/Washington','425','302','425302','BOTHWA','BURGE','OXLEY','WA')
into west_hierarchy values ('West','Oregon/Washington','425','303','425303','EVRTWA','BALDWIN','OXLEY','WA')
into west_hierarchy values ('West','Oregon/Washington','425','304','425304','EVRTWA','BALDWIN','OXLEY','WA')
into west_hierarchy values ('West','Oregon/Washington','425','315','425315','EVRTWA','BALDWIN','OXLEY','WA')
into west_hierarchy values ('West','Oregon/Washington','425','316','425316','SLLKWA','BALDWIN','OXLEY','WA')
into west_hierarchy values ('West','Oregon/Washington','425','317','425317','EVRTWA','BALDWIN','OXLEY','WA')
into west_hierarchy values ('West','Oregon/Washington','425','334','425334','LKSTWA','BALDWIN','OXLEY','WA')
into west_hierarchy values ('West','Oregon/Washington','425','335','425335','LKSTWA','BALDWIN','OXLEY','WA')
into west_hierarchy values ('West','Oregon/Washington','425','337','425337','SLLKWA','BALDWIN','OXLEY','WA')
into west_hierarchy values ('West','Oregon/Washington','425','338','425338','SLLKWA','BALDWIN','OXLEY','WA')
into west_hierarchy values ('West','Oregon/Washington','425','339','425339','EVRTWA','BALDWIN','OXLEY','WA')
into west_hierarchy values ('West','Oregon/Washington','425','347','425347','EVRTWA','BALDWIN','OXLEY','WA')
into west_hierarchy values ('West','Oregon/Washington','425','348','425348','EVRTWA','BALDWIN','OXLEY','WA')
into west_hierarchy values ('West','Oregon/Washington','425','349','425349','EVRTWA','BALDWIN','OXLEY','WA')
into west_hierarchy values ('West','Oregon/Washington','425','353','425353','EVRTWA','BALDWIN','OXLEY','WA')
into west_hierarchy values ('West','Oregon/Washington','425','355','425355','EVRTWA','BALDWIN','OXLEY','WA')
into west_hierarchy values ('West','Oregon/Washington','425','356','425356','EVRTWA','BALDWIN','OXLEY','WA')
into west_hierarchy values ('West','Oregon/Washington','425','357','425357','SLLKWA','BALDWIN','OXLEY','WA')
into west_hierarchy values ('West','Oregon/Washington','425','376','425376','RDMDWA','LARSEN','OXLEY','WA')
into west_hierarchy values ('West','Oregon/Washington','425','377','425377','LKSTWA','BALDWIN','OXLEY','WA')
into west_hierarchy values ('West','Oregon/Washington','425','379','425379','SLLKWA','BALDWIN','OXLEY','WA')
into west_hierarchy values ('West','Oregon/Washington','425','385','425385','SLLKWA','BALDWIN','OXLEY','WA')
into west_hierarchy values ('West','Oregon/Washington','425','388','425388','EVRTWA','BALDWIN','OXLEY','WA')
into west_hierarchy values ('West','Oregon/Washington','425','397','425397','LKSTWA','BALDWIN','OXLEY','WA')
into west_hierarchy values ('West','Oregon/Washington','425','398','425398','BOTHWA','BURGE','OXLEY','WA')
into west_hierarchy values ('West','Oregon/Washington','425','402','425402','BOTHWA','BURGE','OXLEY','WA')
into west_hierarchy values ('West','Oregon/Washington','425','404','425404','EVRTWA','BALDWIN','OXLEY','WA')
into west_hierarchy values ('West','Oregon/Washington','425','407','425407','EVRTWA','BALDWIN','OXLEY','WA')
into west_hierarchy values ('West','Oregon/Washington','425','415','425415','BOTHWA','BURGE','OXLEY','WA')
into west_hierarchy values ('West','Oregon/Washington','425','421','425421','RDMDWA','LARSEN','OXLEY','WA')
into west_hierarchy values ('West','Oregon/Washington','425','423','425423','EVRTWA','BALDWIN','OXLEY','WA')
into west_hierarchy values ('West','Oregon/Washington','425','424','425424','BOTHWA','BURGE','OXLEY','WA')
into west_hierarchy values ('West','Oregon/Washington','425','438','425438','EVRTWA','BALDWIN','OXLEY','WA')
into west_hierarchy values ('West','Oregon/Washington','425','446','425446','EVRTWA','BALDWIN','OXLEY','WA')
into west_hierarchy values ('West','Oregon/Washington','425','481','425481','BOTHWA','BURGE','OXLEY','WA')
into west_hierarchy values ('West','Oregon/Washington','425','482','425482','BOTHWA','BURGE','OXLEY','WA')
into west_hierarchy values ('West','Oregon/Washington','425','483','425483','BOTHWA','BURGE','OXLEY','WA')
into west_hierarchy values ('West','Oregon/Washington','425','485','425485','BOTHWA','BURGE','OXLEY','WA')
into west_hierarchy values ('West','Oregon/Washington','425','486','425486','BOTHWA','BURGE','OXLEY','WA')
into west_hierarchy values ('West','Oregon/Washington','425','487','425487','BOTHWA','BURGE','OXLEY','WA')
into west_hierarchy values ('West','Oregon/Washington','425','488','425488','BOTHWA','BURGE','OXLEY','WA')
into west_hierarchy values ('West','Oregon/Washington','425','489','425489','BOTHWA','BURGE','OXLEY','WA')
into west_hierarchy values ('West','Oregon/Washington','425','493','425493','EVRTWA','BALDWIN','OXLEY','WA')
into west_hierarchy values ('West','Oregon/Washington','425','497','425497','RDMDWA','LARSEN','OXLEY','WA')
into west_hierarchy values ('West','Oregon/Washington','425','498','425498','RDMDWA','LARSEN','OXLEY','WA')
into west_hierarchy values ('West','Oregon/Washington','425','512','425512','EVRTWA','BALDWIN','OXLEY','WA')
into west_hierarchy values ('West','Oregon/Washington','425','514','425514','EVRTWA','BALDWIN','OXLEY','WA')
into west_hierarchy values ('West','Oregon/Washington','425','538','425538','RDMDWA','LARSEN','OXLEY','WA')
into west_hierarchy values ('West','Oregon/Washington','425','556','425556','RDMDWA','LARSEN','OXLEY','WA')
into west_hierarchy values ('West','Oregon/Washington','425','558','425558','RDMDWA','LARSEN','OXLEY','WA')
into west_hierarchy values ('West','Oregon/Washington','425','576','425576','KRLDWA','LARSEN','OXLEY','WA')
into west_hierarchy values ('West','Oregon/Washington','425','580','425580','KRLDWA','LARSEN','OXLEY','WA')
into west_hierarchy values ('West','Oregon/Washington','425','640','425640','HLLKWA','BURGE','OXLEY','WA')
into west_hierarchy values ('West','Oregon/Washington','425','670','425670','HLLKWA','BURGE','OXLEY','WA')
into west_hierarchy values ('West','Oregon/Washington','425','672','425672','HLLKWA','BURGE','OXLEY','WA')
into west_hierarchy values ('West','Oregon/Washington','425','673','425673','HLLKWA','BURGE','OXLEY','WA')
into west_hierarchy values ('West','Oregon/Washington','425','697','425697','HLLKWA','BURGE','OXLEY','WA')
into west_hierarchy values ('West','Oregon/Washington','425','702','425702','RDMDWA','LARSEN','OXLEY','WA')
into west_hierarchy values ('West','Oregon/Washington','425','703','425703','RDMDWA','LARSEN','OXLEY','WA')
into west_hierarchy values ('West','Oregon/Washington','425','704','425704','RDMDWA','LARSEN','OXLEY','WA')
into west_hierarchy values ('West','Oregon/Washington','425','705','425705','RDMDWA','LARSEN','OXLEY','WA')
into west_hierarchy values ('West','Oregon/Washington','425','706','425706','RDMDWA','LARSEN','OXLEY','WA')
into west_hierarchy values ('West','Oregon/Washington','425','707','425707','RDMDWA','LARSEN','OXLEY','WA')
into west_hierarchy values ('West','Oregon/Washington','425','708','425708','RDMDWA','LARSEN','OXLEY','WA')
into west_hierarchy values ('West','Oregon/Washington','425','710','425710','EVRTWA','BALDWIN','OXLEY','WA')
into west_hierarchy values ('West','Oregon/Washington','425','712','425712','HLLKWA','BURGE','OXLEY','WA')
into west_hierarchy values ('West','Oregon/Washington','425','717','425717','EVRTWA','BALDWIN','OXLEY','WA')
into west_hierarchy values ('West','Oregon/Washington','425','722','425722','RDMDWA','LARSEN','OXLEY','WA')
into west_hierarchy values ('West','Oregon/Washington','425','727','425727','RDMDWA','LARSEN','OXLEY','WA')
into west_hierarchy values ('West','Oregon/Washington','425','739','425739','KRLDWA','LARSEN','OXLEY','WA')
into west_hierarchy values ('West','Oregon/Washington','425','741','425741','MRWYWA','BURGE','OXLEY','WA')
into west_hierarchy values ('West','Oregon/Washington','425','742','425742','MRWYWA','BURGE','OXLEY','WA')
into west_hierarchy values ('West','Oregon/Washington','425','743','425743','MRWYWA','BURGE','OXLEY','WA')
into west_hierarchy values ('West','Oregon/Washington','425','744','425744','HLLKWA','BURGE','OXLEY','WA')
into west_hierarchy values ('West','Oregon/Washington','425','745','425745','MRWYWA','BURGE','OXLEY','WA')
into west_hierarchy values ('West','Oregon/Washington','425','755','425755','RDMDWA','LARSEN','OXLEY','WA')
into west_hierarchy values ('West','Oregon/Washington','425','771','425771','HLLKWA','BURGE','OXLEY','WA')
into west_hierarchy values ('West','Oregon/Washington','425','774','425774','HLLKWA','BURGE','OXLEY','WA')
into west_hierarchy values ('West','Oregon/Washington','425','775','425775','HLLKWA','BURGE','OXLEY','WA')
into west_hierarchy values ('West','Oregon/Washington','425','776','425776','HLLKWA','BURGE','OXLEY','WA')
into west_hierarchy values ('West','Oregon/Washington','425','778','425778','HLLKWA','BURGE','OXLEY','WA')
into west_hierarchy values ('West','Oregon/Washington','425','783','425783','EVRTWA','BALDWIN','OXLEY','WA')
into west_hierarchy values ('West','Oregon/Washington','425','787','425787','MRWYWA','BURGE','OXLEY','WA')
into west_hierarchy values ('West','Oregon/Washington','425','788','425788','DVLLWA','BURGE','OXLEY','WA')
into west_hierarchy values ('West','Oregon/Washington','425','803','425803','KRLDWA','LARSEN','OXLEY','WA')
into west_hierarchy values ('West','Oregon/Washington','425','806','425806','BOTHWA','BURGE','OXLEY','WA')
into west_hierarchy values ('West','Oregon/Washington','425','814','425814','JUNTWA','LARSEN','OXLEY','WA')
into west_hierarchy values ('West','Oregon/Washington','425','820','425820','JUNTWA','LARSEN','OXLEY','WA')
into west_hierarchy values ('West','Oregon/Washington','425','821','425821','JUNTWA','LARSEN','OXLEY','WA')
into west_hierarchy values ('West','Oregon/Washington','425','822','425822','KRLDWA','LARSEN','OXLEY','WA')
into west_hierarchy values ('West','Oregon/Washington','425','823','425823','JUNTWA','LARSEN','OXLEY','WA')
into west_hierarchy values ('West','Oregon/Washington','425','825','425825','JUNTWA','LARSEN','OXLEY','WA')
into west_hierarchy values ('West','Oregon/Washington','425','827','425827','KRLDWA','LARSEN','OXLEY','WA')
into west_hierarchy values ('West','Oregon/Washington','425','828','425828','KRLDWA','LARSEN','OXLEY','WA')
into west_hierarchy values ('West','Oregon/Washington','425','836','425836','SMSHWA','LARSEN','OXLEY','WA')
into west_hierarchy values ('West','Oregon/Washington','425','844','425844','DVLLWA','BURGE','OXLEY','WA')
into west_hierarchy values ('West','Oregon/Washington','425','861','425861','RDMDWA','LARSEN','OXLEY','WA')
into west_hierarchy values ('West','Oregon/Washington','425','867','425867','RDMDWA','LARSEN','OXLEY','WA')
into west_hierarchy values ('West','Oregon/Washington','425','868','425868','SMSHWA','LARSEN','OXLEY','WA')
into west_hierarchy values ('West','Oregon/Washington','425','869','425869','RDMDWA','LARSEN','OXLEY','WA')
into west_hierarchy values ('West','Oregon/Washington','425','881','425881','RDMDWA','LARSEN','OXLEY','WA')
into west_hierarchy values ('West','Oregon/Washington','425','882','425882','RDMDWA','LARSEN','OXLEY','WA')
into west_hierarchy values ('West','Oregon/Washington','425','883','425883','RDMDWA','LARSEN','OXLEY','WA')
into west_hierarchy values ('West','Oregon/Washington','425','885','425885','RDMDWA','LARSEN','OXLEY','WA')
into west_hierarchy values ('West','Oregon/Washington','425','889','425889','KRLDWA','LARSEN','OXLEY','WA')
into west_hierarchy values ('West','Oregon/Washington','425','893','425893','KRLDWA','LARSEN','OXLEY','WA')
into west_hierarchy values ('West','Oregon/Washington','425','898','425898','SMSHWA','LARSEN','OXLEY','WA')
into west_hierarchy values ('West','Oregon/Washington','425','899','425899','BOTHWA','BURGE','OXLEY','WA')
into west_hierarchy values ('West','Oregon/Washington','425','908','425908','BOTHWA','BURGE','OXLEY','WA')
into west_hierarchy values ('West','Oregon/Washington','425','918','425918','MRWYWA','BURGE','OXLEY','WA')
into west_hierarchy values ('West','Oregon/Washington','425','923','425923','EVRTWA','BALDWIN','OXLEY','WA')
into west_hierarchy values ('West','Oregon/Washington','425','936','425936','EVRTWA','BALDWIN','OXLEY','WA')
into west_hierarchy values ('West','Oregon/Washington','425','956','425956','RDMDWA','LARSEN','OXLEY','WA')
into west_hierarchy values ('West','East Washington/Idaho/Montana','208','231','208231','RCFRWA','ERKELA','TOWNE','E WA / ID / MT')
into west_hierarchy values ('West','East Washington/Idaho/Montana','208','245','208245','STMRID','ERKELA','TOWNE','E WA / ID / MT')
into west_hierarchy values ('West','East Washington/Idaho/Montana','208','255','208255','SNPNID','THOMPSON','TOWNE','E WA / ID / MT')
into west_hierarchy values ('West','East Washington/Idaho/Montana','208','263','208263','SNPNID','THOMPSON','TOWNE','E WA / ID / MT')
into west_hierarchy values ('West','East Washington/Idaho/Montana','208','264','208264','HOPEID','THOMPSON','TOWNE','E WA / ID / MT')
into west_hierarchy values ('West','East Washington/Idaho/Montana','208','265','208265','SNPNID','THOMPSON','TOWNE','E WA / ID / MT')
into west_hierarchy values ('West','East Washington/Idaho/Montana','208','266','208266','CLFKID','THOMPSON','TOWNE','E WA / ID / MT')
into west_hierarchy values ('West','East Washington/Idaho/Montana','208','267','208267','BNFYID','THOMPSON','TOWNE','E WA / ID / MT')
into west_hierarchy values ('West','East Washington/Idaho/Montana','208','268','208268','FRTNWA','ERKELA','TOWNE','E WA / ID / MT')
into west_hierarchy values ('West','East Washington/Idaho/Montana','208','273','208273','FRFDWA','ERKELA','TOWNE','E WA / ID / MT')
into west_hierarchy values ('West','East Washington/Idaho/Montana','208','274','208274','PSFLID','MURN','TOWNE','E WA / ID / MT')
into west_hierarchy values ('West','East Washington/Idaho/Montana','208','285','208285','GENSID','ERKELA','TOWNE','E WA / ID / MT')
into west_hierarchy values ('West','East Washington/Idaho/Montana','208','325','208325','DNLYID','JAYO','TOWNE','E WA / ID / MT')
into west_hierarchy values ('West','East Washington/Idaho/Montana','208','328','208328','SPFDID','JAYO','TOWNE','E WA / ID / MT')
into west_hierarchy values ('West','East Washington/Idaho/Montana','208','337','208337','HMDLID','JAYO','TOWNE','E WA / ID / MT')
into west_hierarchy values ('West','East Washington/Idaho/Montana','208','347','208347','NWMDID','JAYO','TOWNE','E WA / ID / MT')
into west_hierarchy values ('West','East Washington/Idaho/Montana','208','382','208382','CSCDID','JAYO','TOWNE','E WA / ID / MT')
into west_hierarchy values ('West','East Washington/Idaho/Montana','208','397','208397','ABRDID','JAYO','TOWNE','E WA / ID / MT')
into west_hierarchy values ('West','East Washington/Idaho/Montana','208','428','208428','PRRVID','THOMPSON','TOWNE','E WA / ID / MT')
into west_hierarchy values ('West','East Washington/Idaho/Montana','208','435','208435','WEPPID','ERKELA','TOWNE','E WA / ID / MT')
into west_hierarchy values ('West','East Washington/Idaho/Montana','208','437','208437','NWPTWA','THOMPSON','TOWNE','E WA / ID / MT')
into west_hierarchy values ('West','East Washington/Idaho/Montana','208','443','208443','PRLKID','THOMPSON','TOWNE','E WA / ID / MT')
into west_hierarchy values ('West','East Washington/Idaho/Montana','208','448','208448','PRRVID','THOMPSON','TOWNE','E WA / ID / MT')
into west_hierarchy values ('West','East Washington/Idaho/Montana','208','457','208457','PSFLID','MURN','TOWNE','E WA / ID / MT')
into west_hierarchy values ('West','East Washington/Idaho/Montana','208','462','208462','GRVYID','JAYO','TOWNE','E WA / ID / MT')
into west_hierarchy values ('West','East Washington/Idaho/Montana','208','464','208464','PIRCID','ERKELA','TOWNE','E WA / ID / MT')
into west_hierarchy values ('West','East Washington/Idaho/Montana','208','476','208476','ORFNID','ERKELA','TOWNE','E WA / ID / MT')
into west_hierarchy values ('West','East Washington/Idaho/Montana','208','482','208482','WLDRID','JAYO','TOWNE','E WA / ID / MT')
into west_hierarchy values ('West','East Washington/Idaho/Montana','208','486','208486','PECKID','ERKELA','TOWNE','E WA / ID / MT')
into west_hierarchy values ('West','East Washington/Idaho/Montana','208','556','208556','WLLCID','MURN','TOWNE','E WA / ID / MT')
into west_hierarchy values ('West','East Washington/Idaho/Montana','208','584','208584','SWETID','JAYO','TOWNE','E WA / ID / MT')
into west_hierarchy values ('West','East Washington/Idaho/Montana','208','623','208623','SPLKID','THOMPSON','TOWNE','E WA / ID / MT')
into west_hierarchy values ('West','East Washington/Idaho/Montana','208','628','208628','RGNSID','JAYO','TOWNE','E WA / ID / MT')
into west_hierarchy values ('West','East Washington/Idaho/Montana','208','630','208630','MCCLID','JAYO','TOWNE','E WA / ID / MT')
into west_hierarchy values ('West','East Washington/Idaho/Montana','208','634','208634','MCCLID','JAYO','TOWNE','E WA / ID / MT')
into west_hierarchy values ('West','East Washington/Idaho/Montana','208','664','208664','CRALID','MURN','TOWNE','E WA / ID / MT')
into west_hierarchy values ('West','East Washington/Idaho/Montana','208','665','208665','CRALID','MURN','TOWNE','E WA / ID / MT')
into west_hierarchy values ('West','East Washington/Idaho/Montana','208','666','208666','CRALID','MURN','TOWNE','E WA / ID / MT')
into west_hierarchy values ('West','East Washington/Idaho/Montana','208','667','208667','CRALID','MURN','TOWNE','E WA / ID / MT')
into west_hierarchy values ('West','East Washington/Idaho/Montana','208','668','208668','GRFDWA','ERKELA','TOWNE','E WA / ID / MT')
into west_hierarchy values ('West','East Washington/Idaho/Montana','208','676','208676','CRALID','MURN','TOWNE','E WA / ID / MT')
into west_hierarchy values ('West','East Washington/Idaho/Montana','208','682','208682','PNHRID','MURN','TOWNE','E WA / ID / MT')
into west_hierarchy values ('West','East Washington/Idaho/Montana','208','683','208683','BYVWID','THOMPSON','TOWNE','E WA / ID / MT')
into west_hierarchy values ('West','East Washington/Idaho/Montana','208','686','208686','PLMRID','ERKELA','TOWNE','E WA / ID / MT')
into west_hierarchy values ('West','East Washington/Idaho/Montana','208','687','208687','RTHDID','MURN','TOWNE','E WA / ID / MT')
into west_hierarchy values ('West','East Washington/Idaho/Montana','208','689','208689','HRSNID','ERKELA','TOWNE','E WA / ID / MT')
into west_hierarchy values ('West','East Washington/Idaho/Montana','208','722','208722','PARMID','JAYO','TOWNE','E WA / ID / MT')
into west_hierarchy values ('West','East Washington/Idaho/Montana','208','744','208744','MLLNID','MURN','TOWNE','E WA / ID / MT')
into west_hierarchy values ('West','East Washington/Idaho/Montana','208','752','208752','WLLCID','MURN','TOWNE','E WA / ID / MT')
into west_hierarchy values ('West','East Washington/Idaho/Montana','208','753','208753','WLLCID','MURN','TOWNE','E WA / ID / MT')
into west_hierarchy values ('West','East Washington/Idaho/Montana','208','762','208762','HYLKID','MURN','TOWNE','E WA / ID / MT')
into west_hierarchy values ('West','East Washington/Idaho/Montana','208','764','208764','FRFDID','JAYO','TOWNE','E WA / ID / MT')
into west_hierarchy values ('West','East Washington/Idaho/Montana','208','765','208765','CRALID','MURN','TOWNE','E WA / ID / MT')
into west_hierarchy values ('West','East Washington/Idaho/Montana','208','769','208769','CRALID','MURN','TOWNE','E WA / ID / MT')
into west_hierarchy values ('West','East Washington/Idaho/Montana','208','772','208772','HYLKID','MURN','TOWNE','E WA / ID / MT')
into west_hierarchy values ('West','East Washington/Idaho/Montana','208','773','208773','PSFLID','MURN','TOWNE','E WA / ID / MT')
into west_hierarchy values ('West','East Washington/Idaho/Montana','208','777','208777','PSFLID','MURN','TOWNE','E WA / ID / MT')
into west_hierarchy values ('West','East Washington/Idaho/Montana','208','783','208783','KLLGID','MURN','TOWNE','E WA / ID / MT')
into west_hierarchy values ('West','East Washington/Idaho/Montana','208','784','208784','KLLGID','MURN','TOWNE','E WA / ID / MT')
into west_hierarchy values ('West','East Washington/Idaho/Montana','208','786','208786','KLLGID','MURN','TOWNE','E WA / ID / MT')
into west_hierarchy values ('West','East Washington/Idaho/Montana','208','793','208793','HRBNID','JAYO','TOWNE','E WA / ID / MT')
into west_hierarchy values ('West','East Washington/Idaho/Montana','208','823','208823','CARYID','JAYO','TOWNE','E WA / ID / MT')
into west_hierarchy values ('West','East Washington/Idaho/Montana','208','826','208826','BOVLID','ERKELA','TOWNE','E WA / ID / MT')
into west_hierarchy values ('West','East Washington/Idaho/Montana','208','839','208839','WHBRID','JAYO','TOWNE','E WA / ID / MT')
into west_hierarchy values ('West','East Washington/Idaho/Montana','208','842','208842','EKCYID','JAYO','TOWNE','E WA / ID / MT')
into west_hierarchy values ('West','East Washington/Idaho/Montana','208','858','208858','PALSWA','ERKELA','TOWNE','E WA / ID / MT')
into west_hierarchy values ('West','East Washington/Idaho/Montana','208','874','208874','MSCWID','ERKELA','TOWNE','E WA / ID / MT')
into west_hierarchy values ('West','East Washington/Idaho/Montana','208','875','208875','PTLTID','ERKELA','TOWNE','E WA / ID / MT')
into west_hierarchy values ('West','East Washington/Idaho/Montana','208','877','208877','DERYID','ERKELA','TOWNE','E WA / ID / MT')
into west_hierarchy values ('West','East Washington/Idaho/Montana','208','882','208882','MSCWID','ERKELA','TOWNE','E WA / ID / MT')
into west_hierarchy values ('West','East Washington/Idaho/Montana','208','883','208883','MSCWID','ERKELA','TOWNE','E WA / ID / MT')
into west_hierarchy values ('West','East Washington/Idaho/Montana','208','885','208885','MSCWID','ERKELA','TOWNE','E WA / ID / MT')
into west_hierarchy values ('West','East Washington/Idaho/Montana','208','892','208892','MSCWID','ERKELA','TOWNE','E WA / ID / MT')
into west_hierarchy values ('West','East Washington/Idaho/Montana','208','896','208896','MRNGID','JAYO','TOWNE','E WA / ID / MT')
into west_hierarchy values ('West','East Washington/Idaho/Montana','208','916','208916','CRALID','MURN','TOWNE','E WA / ID / MT')
into west_hierarchy values ('West','East Washington/Idaho/Montana','360','240','360240','OKHRWA','SPERLE','TOWNE','E WA / ID / MT')
into west_hierarchy values ('West','East Washington/Idaho/Montana','360','257','360257','OKHRWA','SPERLE','TOWNE','E WA / ID / MT')
into west_hierarchy values ('West','East Washington/Idaho/Montana','360','279','360279','OKHRWA','SPERLE','TOWNE','E WA / ID / MT')
into west_hierarchy values ('West','East Washington/Idaho/Montana','360','293','360293','ANCRWA','SPERLE','TOWNE','E WA / ID / MT')
into west_hierarchy values ('West','East Washington/Idaho/Montana','360','299','360299','ANCRWA','SPERLE','TOWNE','E WA / ID / MT')
into west_hierarchy values ('West','East Washington/Idaho/Montana','360','312','360312','FNDLWA','SPERLE','TOWNE','E WA / ID / MT')
into west_hierarchy values ('West','East Washington/Idaho/Montana','360','318','360318','LYNDWA','SPERLE','TOWNE','E WA / ID / MT')
into west_hierarchy values ('West','East Washington/Idaho/Montana','360','332','360332','BLANWA','SPERLE','TOWNE','E WA / ID / MT')
into west_hierarchy values ('West','East Washington/Idaho/Montana','360','336','360336','MTVRWA','SPERLE','TOWNE','E WA / ID / MT')
into west_hierarchy values ('West','East Washington/Idaho/Montana','360','354','360354','LYNDWA','SPERLE','TOWNE','E WA / ID / MT')
into west_hierarchy values ('West','East Washington/Idaho/Montana','360','366','360366','CSTRWA','SPERLE','TOWNE','E WA / ID / MT')
into west_hierarchy values ('West','East Washington/Idaho/Montana','360','371','360371','BRBAWA','SPERLE','TOWNE','E WA / ID / MT')
into west_hierarchy values ('West','East Washington/Idaho/Montana','360','380','360380','FNDLWA','SPERLE','TOWNE','E WA / ID / MT')
into west_hierarchy values ('West','East Washington/Idaho/Montana','360','383','360383','FNDLWA','SPERLE','TOWNE','E WA / ID / MT')
into west_hierarchy values ('West','East Washington/Idaho/Montana','360','384','360384','FNDLWA','SPERLE','TOWNE','E WA / ID / MT')
into west_hierarchy values ('West','East Washington/Idaho/Montana','360','398','360398','LARLWA','SPERLE','TOWNE','E WA / ID / MT')
into west_hierarchy values ('West','East Washington/Idaho/Montana','360','416','360416','MTVRWA','SPERLE','TOWNE','E WA / ID / MT')
into west_hierarchy values ('West','East Washington/Idaho/Montana','360','419','360419','MTVRWA','SPERLE','TOWNE','E WA / ID / MT')
into west_hierarchy values ('West','East Washington/Idaho/Montana','360','422','360422','BGLKWA','SPERLE','TOWNE','E WA / ID / MT')
into west_hierarchy values ('West','East Washington/Idaho/Montana','360','424','360424','MTVRWA','SPERLE','TOWNE','E WA / ID / MT')
into west_hierarchy values ('West','East Washington/Idaho/Montana','360','428','360428','MTVRWA','SPERLE','TOWNE','E WA / ID / MT')
into west_hierarchy values ('West','East Washington/Idaho/Montana','360','429','360429','SWLYWA','SPERLE','TOWNE','E WA / ID / MT')
into west_hierarchy values ('West','East Washington/Idaho/Montana','360','445','360445','CNWYWA','SPERLE','TOWNE','E WA / ID / MT')
into west_hierarchy values ('West','East Washington/Idaho/Montana','360','466','360466','LACNWA','SPERLE','TOWNE','E WA / ID / MT')
into west_hierarchy values ('West','East Washington/Idaho/Montana','360','588','360588','ANCRWA','SPERLE','TOWNE','E WA / ID / MT')
into west_hierarchy values ('West','East Washington/Idaho/Montana','360','592','360592','DMNGWA','SPERLE','TOWNE','E WA / ID / MT')
into west_hierarchy values ('West','East Washington/Idaho/Montana','360','595','360595','ACMEWA','SPERLE','TOWNE','E WA / ID / MT')
into west_hierarchy values ('West','East Washington/Idaho/Montana','360','599','360599','MPFLWA','SPERLE','TOWNE','E WA / ID / MT')
into west_hierarchy values ('West','East Washington/Idaho/Montana','360','617','360617','FNDLWA','SPERLE','TOWNE','E WA / ID / MT')
into west_hierarchy values ('West','East Washington/Idaho/Montana','360','675','360675','OKHRWA','SPERLE','TOWNE','E WA / ID / MT')
into west_hierarchy values ('West','East Washington/Idaho/Montana','360','678','360678','CPVLWA','SPERLE','TOWNE','E WA / ID / MT')
into west_hierarchy values ('West','East Washington/Idaho/Montana','360','679','360679','OKHRWA','SPERLE','TOWNE','E WA / ID / MT')
into west_hierarchy values ('West','East Washington/Idaho/Montana','360','707','360707','BURLWA','SPERLE','TOWNE','E WA / ID / MT')
into west_hierarchy values ('West','East Washington/Idaho/Montana','360','724','360724','ALGRWA','SPERLE','TOWNE','E WA / ID / MT')
into west_hierarchy values ('West','East Washington/Idaho/Montana','360','755','360755','BURLWA','SPERLE','TOWNE','E WA / ID / MT')
into west_hierarchy values ('West','East Washington/Idaho/Montana','360','757','360757','BURLWA','SPERLE','TOWNE','E WA / ID / MT')
into west_hierarchy values ('West','East Washington/Idaho/Montana','360','766','360766','EDSNWA','SPERLE','TOWNE','E WA / ID / MT')
into west_hierarchy values ('West','East Washington/Idaho/Montana','360','814','360814','MTVRWA','SPERLE','TOWNE','E WA / ID / MT')
into west_hierarchy values ('West','East Washington/Idaho/Montana','360','817','360817','CAMSWA','SPERLE','TOWNE','E WA / ID / MT')
into west_hierarchy values ('West','East Washington/Idaho/Montana','360','826','360826','HMTNWA','SPERLE','TOWNE','E WA / ID / MT')
into west_hierarchy values ('West','East Washington/Idaho/Montana','360','833','360833','CAMSWA','SPERLE','TOWNE','E WA / ID / MT')
into west_hierarchy values ('West','East Washington/Idaho/Montana','360','834','360834','CAMSWA','SPERLE','TOWNE','E WA / ID / MT')
into west_hierarchy values ('West','East Washington/Idaho/Montana','360','848','360848','MTVRWA','SPERLE','TOWNE','E WA / ID / MT')
into west_hierarchy values ('West','East Washington/Idaho/Montana','360','853','360853','CNCRWA','SPERLE','TOWNE','E WA / ID / MT')
into west_hierarchy values ('West','East Washington/Idaho/Montana','360','854','360854','SWLYWA','SPERLE','TOWNE','E WA / ID / MT')
into west_hierarchy values ('West','East Washington/Idaho/Montana','360','855','360855','SWLYWA','SPERLE','TOWNE','E WA / ID / MT')
into west_hierarchy values ('West','East Washington/Idaho/Montana','360','856','360856','SWLYWA','SPERLE','TOWNE','E WA / ID / MT')
into west_hierarchy values ('West','East Washington/Idaho/Montana','360','873','360873','MRBLWA','SPERLE','TOWNE','E WA / ID / MT')
into west_hierarchy values ('West','East Washington/Idaho/Montana','360','966','360966','EVSNWA','SPERLE','TOWNE','E WA / ID / MT')
into west_hierarchy values ('West','East Washington/Idaho/Montana','360','988','360988','SUMSWA','SPERLE','TOWNE','E WA / ID / MT')
into west_hierarchy values ('West','East Washington/Idaho/Montana','406','283','406283','LBBYMT','THOMPSON','TOWNE','E WA / ID / MT')
into west_hierarchy values ('West','East Washington/Idaho/Montana','406','293','406293','LBBYMT','THOMPSON','TOWNE','E WA / ID / MT')
into west_hierarchy values ('West','East Washington/Idaho/Montana','406','295','406295','TROYMT','THOMPSON','TOWNE','E WA / ID / MT')
into west_hierarchy values ('West','East Washington/Idaho/Montana','406','296','406296','EURKMT','THOMPSON','TOWNE','E WA / ID / MT')
into west_hierarchy values ('West','East Washington/Idaho/Montana','509','222','509222','KNWCWA','LEE','TOWNE','E WA / ID / MT')
into west_hierarchy values ('West','East Washington/Idaho/Montana','509','223','509223','LOMSWA','SANDMAN','TOWNE','E WA / ID / MT')
into west_hierarchy values ('West','East Washington/Idaho/Montana','509','246','509246','SOLKWA','SANDMAN','TOWNE','E WA / ID / MT')
into west_hierarchy values ('West','East Washington/Idaho/Montana','509','283','509283','FRFDWA','ERKELA','TOWNE','E WA / ID / MT')
into west_hierarchy values ('West','East Washington/Idaho/Montana','509','284','509284','TEKOWA','ERKELA','TOWNE','E WA / ID / MT')
into west_hierarchy values ('West','East Washington/Idaho/Montana','509','285','509285','OKDLWA','ERKELA','TOWNE','E WA / ID / MT')
into west_hierarchy values ('West','East Washington/Idaho/Montana','509','286','509286','LATHWA','ERKELA','TOWNE','E WA / ID / MT')
into west_hierarchy values ('West','East Washington/Idaho/Montana','509','287','509287','FRTNWA','ERKELA','TOWNE','E WA / ID / MT')
into west_hierarchy values ('West','East Washington/Idaho/Montana','509','291','509291','RCFRWA','ERKELA','TOWNE','E WA / ID / MT')
into west_hierarchy values ('West','East Washington/Idaho/Montana','509','332','509332','PLMNWA','ERKELA','TOWNE','E WA / ID / MT')
into west_hierarchy values ('West','East Washington/Idaho/Montana','509','333','509333','PLMNWA','ERKELA','TOWNE','E WA / ID / MT')
into west_hierarchy values ('West','East Washington/Idaho/Montana','509','334','509334','PLMNWA','ERKELA','TOWNE','E WA / ID / MT')
into west_hierarchy values ('West','East Washington/Idaho/Montana','509','335','509335','PLMNWA','ERKELA','TOWNE','E WA / ID / MT')
into west_hierarchy values ('West','East Washington/Idaho/Montana','509','336','509336','PLMNWA','ERKELA','TOWNE','E WA / ID / MT')
into west_hierarchy values ('West','East Washington/Idaho/Montana','509','338','509338','PLMNWA','ERKELA','TOWNE','E WA / ID / MT')
into west_hierarchy values ('West','East Washington/Idaho/Montana','509','339','509339','PLMNWA','ERKELA','TOWNE','E WA / ID / MT')
into west_hierarchy values ('West','East Washington/Idaho/Montana','509','371','509371','RCLDWA','LEE','TOWNE','E WA / ID / MT')
into west_hierarchy values ('West','East Washington/Idaho/Montana','509','372','509372','RCLDWA','LEE','TOWNE','E WA / ID / MT')
into west_hierarchy values ('West','East Washington/Idaho/Montana','509','373','509373','RCLDWA','LEE','TOWNE','E WA / ID / MT')
into west_hierarchy values ('West','East Washington/Idaho/Montana','509','374','509374','KNWCWA','LEE','TOWNE','E WA / ID / MT')
into west_hierarchy values ('West','East Washington/Idaho/Montana','509','375','509375','RCLDWA','LEE','TOWNE','E WA / ID / MT')
into west_hierarchy values ('West','East Washington/Idaho/Montana','509','376','509376','RCLDWA','LEE','TOWNE','E WA / ID / MT')
into west_hierarchy values ('West','East Washington/Idaho/Montana','509','447','509447','NWPTWA','THOMPSON','TOWNE','E WA / ID / MT')
into west_hierarchy values ('West','East Washington/Idaho/Montana','509','478','509478','THTNWA','ERKELA','TOWNE','E WA / ID / MT')
into west_hierarchy values ('West','East Washington/Idaho/Montana','509','485','509485','MLSNWA','SANDMAN','TOWNE','E WA / ID / MT')
into west_hierarchy values ('West','East Washington/Idaho/Montana','509','486','509486','TNSKWA','SANDMAN','TOWNE','E WA / ID / MT')
into west_hierarchy values ('West','East Washington/Idaho/Montana','509','523','509523','ROSLWA','ERKELA','TOWNE','E WA / ID / MT')
into west_hierarchy values ('West','East Washington/Idaho/Montana','509','548','509548','LVWOWA','SANDMAN','TOWNE','E WA / ID / MT')
into west_hierarchy values ('West','East Washington/Idaho/Montana','509','569','509569','MLDNWA','ERKELA','TOWNE','E WA / ID / MT')
into west_hierarchy values ('West','East Washington/Idaho/Montana','509','582','509582','KNWCWA','LEE','TOWNE','E WA / ID / MT')
into west_hierarchy values ('West','East Washington/Idaho/Montana','509','585','509585','KNWCWA','LEE','TOWNE','E WA / ID / MT')
into west_hierarchy values ('West','East Washington/Idaho/Montana','509','586','509586','KNWCWA','LEE','TOWNE','E WA / ID / MT')
into west_hierarchy values ('West','East Washington/Idaho/Montana','509','588','509588','BNCYWA','LEE','TOWNE','E WA / ID / MT')
into west_hierarchy values ('West','East Washington/Idaho/Montana','509','627','509627','KNWCWA','LEE','TOWNE','E WA / ID / MT')
into west_hierarchy values ('West','East Washington/Idaho/Montana','509','628','509628','KNWCWA','LEE','TOWNE','E WA / ID / MT')
into west_hierarchy values ('West','East Washington/Idaho/Montana','509','635','509635','GRFDWA','ERKELA','TOWNE','E WA / ID / MT')
into west_hierarchy values ('West','East Washington/Idaho/Montana','509','653','509653','NCHSWA','SANDMAN','TOWNE','E WA / ID / MT')
into west_hierarchy values ('West','East Washington/Idaho/Montana','509','658','509658','NILEWA','SANDMAN','TOWNE','E WA / ID / MT')
into west_hierarchy values ('West','East Washington/Idaho/Montana','509','662','509662','WNTCWA','SANDMAN','TOWNE','E WA / ID / MT')
into west_hierarchy values ('West','East Washington/Idaho/Montana','509','663','509663','WNTCWA','SANDMAN','TOWNE','E WA / ID / MT')
into west_hierarchy values ('West','East Washington/Idaho/Montana','509','664','509664','WNTCWA','SANDMAN','TOWNE','E WA / ID / MT')
into west_hierarchy values ('West','East Washington/Idaho/Montana','509','665','509665','WNTCWA','SANDMAN','TOWNE','E WA / ID / MT')
into west_hierarchy values ('West','East Washington/Idaho/Montana','509','667','509667','WNTCWA','SANDMAN','TOWNE','E WA / ID / MT')
into west_hierarchy values ('West','East Washington/Idaho/Montana','509','682','509682','CHLNWA','SANDMAN','TOWNE','E WA / ID / MT')
into west_hierarchy values ('West','East Washington/Idaho/Montana','509','683','509683','MNFDWA','SANDMAN','TOWNE','E WA / ID / MT')
into west_hierarchy values ('West','East Washington/Idaho/Montana','509','686','509686','BRPTWA','SANDMAN','TOWNE','E WA / ID / MT')
into west_hierarchy values ('West','East Washington/Idaho/Montana','509','687','509687','MNSNWA','SANDMAN','TOWNE','E WA / ID / MT')
into west_hierarchy values ('West','East Washington/Idaho/Montana','509','689','509689','BRWSWA','SANDMAN','TOWNE','E WA / ID / MT')
into west_hierarchy values ('West','East Washington/Idaho/Montana','509','734','509734','KNWCWA','LEE','TOWNE','E WA / ID / MT')
into west_hierarchy values ('West','East Washington/Idaho/Montana','509','735','509735','KNWCWA','LEE','TOWNE','E WA / ID / MT')
into west_hierarchy values ('West','East Washington/Idaho/Montana','509','736','509736','KNWCWA','LEE','TOWNE','E WA / ID / MT')
into west_hierarchy values ('West','East Washington/Idaho/Montana','509','737','509737','KNWCWA','LEE','TOWNE','E WA / ID / MT')
into west_hierarchy values ('West','East Washington/Idaho/Montana','509','745','509745','WTVLWA','SANDMAN','TOWNE','E WA / ID / MT')
into west_hierarchy values ('West','East Washington/Idaho/Montana','509','763','509763','LKWNWA','SANDMAN','TOWNE','E WA / ID / MT')
into west_hierarchy values ('West','East Washington/Idaho/Montana','509','775','509775','RPBLWA','SANDMAN','TOWNE','E WA / ID / MT')
into west_hierarchy values ('West','East Washington/Idaho/Montana','509','779','509779','CRLWWA','SANDMAN','TOWNE','E WA / ID / MT')
into west_hierarchy values ('West','East Washington/Idaho/Montana','509','782','509782','CSHRWA','SANDMAN','TOWNE','E WA / ID / MT')
into west_hierarchy values ('West','East Washington/Idaho/Montana','509','783','509783','KNWCWA','LEE','TOWNE','E WA / ID / MT')
into west_hierarchy values ('West','East Washington/Idaho/Montana','509','784','509784','ENTTWA','SANDMAN','TOWNE','E WA / ID / MT')
into west_hierarchy values ('West','East Washington/Idaho/Montana','509','785','509785','GERGWA','SANDMAN','TOWNE','E WA / ID / MT')
into west_hierarchy values ('West','East Washington/Idaho/Montana','509','787','509787','QNCYWA','SANDMAN','TOWNE','E WA / ID / MT')
into west_hierarchy values ('West','East Washington/Idaho/Montana','509','872','509872','MSCWID','ERKELA','TOWNE','E WA / ID / MT')
into west_hierarchy values ('West','East Washington/Idaho/Montana','509','878','509878','PALSWA','ERKELA','TOWNE','E WA / ID / MT')
into west_hierarchy values ('West','East Washington/Idaho/Montana','509','881','509881','EWNCWA','SANDMAN','TOWNE','E WA / ID / MT')
into west_hierarchy values ('West','East Washington/Idaho/Montana','509','884','509884','EWNCWA','SANDMAN','TOWNE','E WA / ID / MT')
into west_hierarchy values ('West','East Washington/Idaho/Montana','509','886','509886','EWNCWA','SANDMAN','TOWNE','E WA / ID / MT')
into west_hierarchy values ('West','East Washington/Idaho/Montana','509','942','509942','RCLDWA','LEE','TOWNE','E WA / ID / MT')
into west_hierarchy values ('West','East Washington/Idaho/Montana','509','943','509943','RCLDWA','LEE','TOWNE','E WA / ID / MT')
into west_hierarchy values ('West','East Washington/Idaho/Montana','509','946','509946','RCLDWA','LEE','TOWNE','E WA / ID / MT')
into west_hierarchy values ('West','East Washington/Idaho/Montana','509','967','509967','WRLDWA','LEE','TOWNE','E WA / ID / MT')
into west_hierarchy values ('West','East Washington/Idaho/Montana','541','426','541426','ENTROR','LEE','TOWNE','E WA / ID / MT')
into west_hierarchy values ('West','East Washington/Idaho/Montana','541','432','541432','JSPHOR','LEE','TOWNE','E WA / ID / MT')
into west_hierarchy values ('West','East Washington/Idaho/Montana','541','437','541437','ELGNOR','LEE','TOWNE','E WA / ID / MT')
into west_hierarchy values ('West','East Washington/Idaho/Montana','541','534','541534','IMBLOR','LEE','TOWNE','E WA / ID / MT')
into west_hierarchy values ('West','East Washington/Idaho/Montana','541','562','541562','UNINOR','LEE','TOWNE','E WA / ID / MT')
into west_hierarchy values ('West','East Washington/Idaho/Montana','541','568','541568','COVEOR','LEE','TOWNE','E WA / ID / MT')
into west_hierarchy values ('West','East Washington/Idaho/Montana','541','569','541569','LOSTOR','LEE','TOWNE','E WA / ID / MT')
into west_hierarchy values ('West','East Washington/Idaho/Montana','541','577','541577','IMNHOR','LEE','TOWNE','E WA / ID / MT')
into west_hierarchy values ('West','East Washington/Idaho/Montana','541','663','541663','LAGROR','LEE','TOWNE','E WA / ID / MT')
into west_hierarchy values ('West','East Washington/Idaho/Montana','541','886','541886','WLLWOR','LEE','TOWNE','E WA / ID / MT')
into west_hierarchy values ('West','East Washington/Idaho/Montana','541','962','541962','LAGROR','LEE','TOWNE','E WA / ID / MT')
into west_hierarchy values ('West','East Washington/Idaho/Montana','541','963','541963','LAGROR','LEE','TOWNE','E WA / ID / MT')
into west_hierarchy values ('West','East Washington/Idaho/Montana','541','975','541975','LAGROR','LEE','TOWNE','E WA / ID / MT')
into west_hierarchy values ('West','Oregon/Washington','503','264','503264','HLBOOR','DANIELSON','ANDERSON','OR')
into west_hierarchy values ('West','East Washington/Idaho/Montana','360','026','360026','MTVRWA','SPERLE','TOWNE','E WA / ID / MT')
into west_hierarchy values ('West','East Washington/Idaho/Montana','208','446','208446','CRALID','MURN','TOWNE','E WA / ID / MT')
into west_hierarchy values ('West','Oregon/Washington','425','450','425450','EVRTWA','BALDWIN','OXLEY','WA')
into west_hierarchy values ('West','East Washington/Idaho/Montana','208','651','208651','CRALID','MURN','TOWNE','E WA / ID / MT')
into west_hierarchy values ('West','Oregon/Washington','503','691','503691','PTLDOR','DANIELSON','ANDERSON','OR')
into west_hierarchy values ('West','Parker','','','','PRKRAZ','','AZ','AZ')
into west_hierarchy values ('West','Anaheim','','','','ANHMCA','','BADER','CA')
into west_hierarchy values ('West','Arcata','','','','ARCTCA','','BADER','CA')
into west_hierarchy values ('West','','','','','BLTNCA','','BADER','CA')
into west_hierarchy values ('West','Blythe','','','','BLYTCA','','AZ','AZ')
into west_hierarchy values ('West','Coleville','','','','CEVLCA','','NV','AZ')
into west_hierarchy values ('West','Chico','','','','CHICCA','','BADER','CA')
into west_hierarchy values ('West','Covina','','','','COVNCA','','BADER','CA')
into west_hierarchy values ('West','Earp','','','','EARPCA','','AZ','AZ')
into west_hierarchy values ('West','Gardena','','','','GRDNCA','','BADER','CA')
into west_hierarchy values ('West','Huntington Beach','','','','HNBHCA','','BADER','CA')
into west_hierarchy values ('West','Havasu','','','','HVSUCA','','AZ','AZ')
into west_hierarchy values ('West','Irvine','','','','IRVNCA','','BADER','CA')
into west_hierarchy values ('West','Loyalton','','','','LLTNCA','','BADER','CA')
into west_hierarchy values ('West','Long Beach','','','','LNBHCA','','BADER','CA')
into west_hierarchy values ('West','Los Angeles','','','','LSANCA','','BADER','CA')
into west_hierarchy values ('West','Modesto','','','','MDSTCA','','BADER','CA')
into west_hierarchy values ('West','Monrovia','','','','MNRVCA','','BADER','CA')
into west_hierarchy values ('West','Merced','','','','MRCDCA','','BADER','CA')
into west_hierarchy values ('West','','','','','MRVLCA','','NV','AZ')
into west_hierarchy values ('West','Needles','','','','NDLSCA','','AZ','AZ')
into west_hierarchy values ('West','Ontario','','','','ONTRCA','','BADER','CA')
into west_hierarchy values ('West','','','','','PRDMCA','','BADER','CA')
into west_hierarchy values ('West','','','','','RCKLCA','','NV','AZ')
into west_hierarchy values ('West','Redding','','','','RDNGCA','','BADER','CA')
into west_hierarchy values ('West','Rialto','','','','RILTCA','','BADER','CA')
into west_hierarchy values ('West','Riverside','','','','RVSDCA','','BADER','CA')
into west_hierarchy values ('West','Sacramento','','','','SCRMCA','','BADER','CA')
into west_hierarchy values ('West','Sherman Oaks','','','','SHOKCA','','BADER','CA')
into west_hierarchy values ('West','Stockton','','','','SKTNCA','','BADER','CA')
into west_hierarchy values ('West','Stockton','','','','SKTOCA','','BADER','CA')
into west_hierarchy values ('West','Santa Ana','','','','SNANCA','','BADER','CA')
into west_hierarchy values ('West','San Bernadino','','','','SNBRCA','','BADER','CA')
into west_hierarchy values ('West','Santa Rosa','','','','SNRSCA','','BADER','CA')
into west_hierarchy values ('West','Thousand Oaks','','','','THOKCA','','BADER','CA')
into west_hierarchy values ('West','Temecula','','','','TMCLCA','','BADER','CA')
into west_hierarchy values ('West','','','','','TOPZCA','','NV','AZ')
into west_hierarchy values ('West','Tustin','','','','TUSTCA','','BADER','CA')
into west_hierarchy values ('West','Victorville','','','','VTVLCA','','BADER','CA')
into west_hierarchy values ('West','Woodford','','','','WDFRCA','','NV','AZ')
into west_hierarchy values ('West','Whittier','','','','WHTRCA','','BADER','CA')
into west_hierarchy values ('West','Boise','','','','BOISID','','TOWNE','E WA / ID / MT')
into west_hierarchy values ('West','','','','','CNCLID','','TOWNE','E WA / ID / MT')
into west_hierarchy values ('West','','','','','GRNRMT','','TOWNE','E WA / ID / MT')
into west_hierarchy values ('West','','','','','ELKONV','','NV','AZ')
into west_hierarchy values ('West','','','','','RENONV','','NV','AZ')
into west_hierarchy values ('West','','','','','RENPNV','','NV','AZ')
into west_hierarchy values ('West','','','','','SPRKNV','','NV','AZ')
into west_hierarchy values ('West','','','','','BONGOR','','ANDERSON','OR')
into west_hierarchy values ('West','Cannon Beach','','','','CNBHOR','','ANDERSON','OR')
into west_hierarchy values ('West','Eugene','','','','EUGNOR','','ANDERSON','OR')
into west_hierarchy values ('West','Florence','','','','FLRNOR','','ANDERSON','OR')
into west_hierarchy values ('West','Garibaldi','','','','GRBLOR','','ANDERSON','OR')
into west_hierarchy values ('West','','','','','GRNROR','','ANDERSON','OR')
into west_hierarchy values ('West','North Plains','','','','NPLNOR','','ANDERSON','OR')
into west_hierarchy values ('West','Salem','','','','SALMOR','','ANDERSON','OR')
into west_hierarchy values ('West','','','','','SALNOR','','ANDERSON','OR')
into west_hierarchy values ('West','','','','','SBLYOR','','ANDERSON','OR')
into west_hierarchy values ('West','','','','','WLNNOR','','ANDERSON','OR')
into west_hierarchy values ('West','Auburn','','','','AUBNWA','','OXLEY','WA')
into west_hierarchy values ('West','Bellingham','','','','BLHMWA','','TOWNE','E WA / ID / MT')
into west_hierarchy values ('West','Bellevue','','','','BLLVWA','','OXLEY','WA')
into west_hierarchy values ('West','Columbia','','','','CLMAWA','','TOWNE','E WA / ID / MT')
into west_hierarchy values ('West','Connell','','','','CNNLWA','','TOWNE','E WA / ID / MT')
into west_hierarchy values ('West','Eltopia','','','','ELTPWA','','TOWNE','E WA / ID / MT')
into west_hierarchy values ('West','Ephrata','','','','EPHRWA','','TOWNE','E WA / ID / MT')
into west_hierarchy values ('West','Friday Harbor','','','','FRHRWA','','TOWNE','E WA / ID / MT')
into west_hierarchy values ('West','Grandview','','','','GDVWWA','','TOWNE','E WA / ID / MT')
into west_hierarchy values ('West','','','','','GNBNWA','','OXLEY','WA')
into west_hierarchy values ('West','Kingston','','','','KGTNWA','','OXLEY','WA')
into west_hierarchy values ('West','Lynwood','','','','LYWDWA','','OXLEY','WA')
into west_hierarchy values ('West','','','','','MLTBWA','','OXLEY','WA')
into west_hierarchy values ('West','','','','','MLWDWA','','TOWNE','E WA / ID / MT')
into west_hierarchy values ('West','Moses Lake','','','','MSLKWA','','TOWNE','E WA / ID / MT')
into west_hierarchy values ('West','','','','','MTTRWA','','OXLEY','WA')
into west_hierarchy values ('West','Omak','','','','OMAKWA','','TOWNE','E WA / ID / MT')
into west_hierarchy values ('West','Othello','','','','OTHEWA','','TOWNE','E WA / ID / MT')
into west_hierarchy values ('West','Pasco','','','','PASCWA','','TOWNE','E WA / ID / MT')
into west_hierarchy values ('West','Paterson','','','','PASNWA','','TOWNE','E WA / ID / MT')
into west_hierarchy values ('West','Point Roberts','','','','PNRBWA','','OXLEY','WA')
into west_hierarchy values ('West','','','','','PSHSWA','','TOWNE','E WA / ID / MT')
into west_hierarchy values ('West','','','','','RCPTWA','','OXLEY','WA')
into west_hierarchy values ('West','','','','','SNSLWA','','TOWNE','E WA / ID / MT')
into west_hierarchy values ('West','Sunnyslope','','','','SNYSWA','','OXLEY','WA')
into west_hierarchy values ('West','Spokane','','','','SPKNWA','','TOWNE','E WA / ID / MT')
into west_hierarchy values ('West','Seattle','','','','STTLWA','','OXLEY','WA')
into west_hierarchy values ('West','Seattle','','','','STTMWA','','OXLEY','WA')
into west_hierarchy values ('West','Seattle','','','','STTOWA','','OXLEY','WA')
into west_hierarchy values ('West','So Whidbey','','','','SWHDWA','','OXLEY','WA')
into west_hierarchy values ('West','Tacoma','','','','TACMWA','','OXLEY','WA')
into west_hierarchy values ('West','Tukwila','','','','TKWLWA','','OXLEY','WA')
into west_hierarchy values ('West','Vancouver','','','','VANCWA','','TOWNE','E WA / ID / MT')
into west_hierarchy values ('West','','','','','WDVLWA','','OXLEY','WA')
into west_hierarchy values ('West','Winthrop','','','','WNTHWA','','TOWNE','E WA / ID / MT')
into west_hierarchy values ('West','Yakima','','','','YAKMWA','','TOWNE','E WA / ID / MT')
select * from dual;
