CREATE VIEW forecast.[Out_InvoiceErrorAllocation]
	AS SELECT [ProjectNumber]
      ,[SubprojectNumber]
	  ,[GrossAddsTotal]
      ,[PriorYearsSpendTotal]
      ,[GrossAddsTotal]+[PriorYearsSpendTotal] PriorYearPlusGrossAdds FROM [forecast].[ForecastExport]