CREATE TABLE [dbo].[ForecastImport] (
    [ProjectNumber]               INT            NULL,
    [SubprojectNumber]            SMALLINT       NULL,
    [BudgetLineNumber]            INT            NULL,
    [ClassOfPlant]                CHAR (2)       NULL,
    [LinkCode]                    VARCHAR (25)   NULL,
    [BudgetCategory]              VARCHAR (50)   NULL,
    [JustificationCode]           TINYINT        NULL,
    [FunctionalGroup]             CHAR (1)       NULL,
    [ProjectDescription]          VARCHAR (200)  NULL,
    [Billable]                    CHAR (1)       NULL,
    [ProjectStatusCode]           CHAR (2)       NULL,
    [ApprovalCode]                CHAR (2)       NULL,
    [ProjectType]                 CHAR (1)       NULL,
    [Company]                     SMALLINT       NULL,
    [ExchangeName]                VARCHAR (50)   NULL,
    [OperatingArea]               SMALLINT       NULL,
    [State]                       CHAR (2)       NULL,
    [Engineer]                    VARCHAR (50)   NULL,
    [ProjectOwner]                VARCHAR (50)   NULL,
    [ApprovalDate]                DATE           NULL,
    [EstimatedStartDate]          DATE           NULL,
    [EstimatedCompleteDate]       DATE           NULL,
    [ActualStartDate]             DATE           NULL,
    [ReadyForServiceDate]         DATE           NULL,
    [TentativeCloseDate]          DATE           NULL,
    [CloseDate]                   DATE           NULL,
    [AuthorizedDirect]            FLOAT (53)     NULL,
    [AuthorizedIndirect]          FLOAT (53)     NULL,
    [PriorYearsSpent]             FLOAT (53)     NULL,
    [JanuaryDirect]               FLOAT (53)     NULL,
    [JanuaryIndirect]             FLOAT (53)     NULL,
    [FebruaryDirect]              FLOAT (53)     NULL,
    [FebruaryIndirect]            FLOAT (53)     NULL,
    [MarchDirect]                 FLOAT (53)     NULL,
    [MarchIndirect]               FLOAT (53)     NULL,
    [AprilDirect]                 FLOAT (53)     NULL,
    [AprilIndirect]               FLOAT (53)     NULL,
    [MayDirect]                   FLOAT (53)     NULL,
    [MayIndirect]                 FLOAT (53)     NULL,
    [JuneDirect]                  FLOAT (53)     NULL,
    [JuneIndirect]                FLOAT (53)     NULL,
    [JulyDirect]                  FLOAT (53)     NULL,
    [JulyIndirect]                FLOAT (53)     NULL,
    [AugustDirect]                FLOAT (53)     NULL,
    [AugustIndirect]              FLOAT (53)     NULL,
    [SeptemberDirect]             FLOAT (53)     NULL,
    [SeptemberIndirect]           FLOAT (53)     NULL,
    [OctoberDirect]               FLOAT (53)     NULL,
    [OctoberIndirect]             FLOAT (53)     NULL,
    [NovemberDirect]              FLOAT (53)     NULL,
    [NovemberIndirect]            FLOAT (53)     NULL,
    [DecemberDirect]              FLOAT (53)     NULL,
    [DecemberIndirect]            FLOAT (53)     NULL,
    [AllCIAC]                     FLOAT (53)     NULL,
    [FutureYearsSpendingInfinium] FLOAT (53)     NULL,
    [FutureYearsSpending]         FLOAT (53)     NULL,
    [SpendingNotNeeded]           FLOAT (53)     NULL,
    [AdditionalDollarsNeeded]     FLOAT (53)     NULL,
    [CIACBudget]                  FLOAT (53)     NULL,
    [AnalystNotes]                VARCHAR (8000) NULL,
    [SubprojectStatus]            VARCHAR (50)   NULL,
    [CarryIn]                     VARCHAR (8)    NULL,
    [SentToClosing]               VARCHAR (25)   NULL
);

