CREATE TABLE [dbo].[Varasset_FPStatus] (
    [Work Order Id]                NVARCHAR (255) NULL,
    [Project]                      NVARCHAR (255) NULL,
    [Subproject]                   NVARCHAR (255) NULL,
    [Exch Number]                  NVARCHAR (255) NULL,
    [OSP Project Status]           NVARCHAR (255) NULL,
    [COE Project Status]           NVARCHAR (255) NULL,
    [Varasset Work Order Status]   NVARCHAR (255) NULL,
    [Financial Project Status]     NVARCHAR (255) NULL,
    [FP Project Status Updated On] DATETIME       NULL,
    [Closing Issue]                NVARCHAR (255) NULL,
    [TARGET START]                 DATETIME       NULL,
    [ACTUAL START]                 DATETIME       NULL,
    [Estimated In Service Date]    DATETIME       NULL,
    [Actual In Service Date]       DATETIME       NULL,
    [Scheduled Finish]             DATETIME       NULL,
    [ItemCode]                     NVARCHAR (255) NULL,
    [Storeroom]                    NVARCHAR (255) NULL,
    [Vendor]                       NVARCHAR (255) NULL,
    [PO Line Sched Ship Date]      DATETIME       NULL,
    [PO Tracking]                  NVARCHAR (255) NULL,
    [Ship To]                      NVARCHAR (255) NULL,
    [PurchaseOrder]                NVARCHAR (255) NULL,
    [Purchase Order Line]          NVARCHAR (255) NULL,
    [FP Comments]                  NVARCHAR (MAX) NULL,
    [WO Comments]                  NVARCHAR (MAX) NULL,
    [Date Needed]                  DATETIME       NULL,
    [Material Comments]            NVARCHAR (MAX) NULL,
    [Escalate]                     NVARCHAR (255) NULL,
    [OPCEN MND]                    DATETIME       NULL,
    [Promise Date]                 DATETIME       NULL,
    [InfStatus]                    NVARCHAR (255) NULL,
    [EstSchStart]                  DATETIME       NULL,
    [WOAssignedVendor]             NVARCHAR (255) NULL,
    [EngdLocations]                NVARCHAR (255) NULL,
    [PMDBHHCount]                  NVARCHAR (255) NULL,
    [UpdatedOn]                    DATETIME       NULL,
    [POStatus]                     NVARCHAR (255) NULL,
    [OverallProjEstSchStart]       DATETIME       NULL,
    [Subcategory]                  NVARCHAR (255) NULL
);

