CREATE TABLE [ProjApproval].[Compare_BDT_History_LZ] (
    [Opportunity ID]                        VARCHAR (50)  NULL,
    [PostSale STATE]                        VARCHAR (5)   NULL,
    [PostSale PROJECT]                      VARCHAR (10)  NULL,
    [PostSale SUB-PROJECT]                  VARCHAR (1)   NULL,
    [PostSale CIAC]                         MONEY         NULL,
    [PostSale PREQUAL TYPE]                 VARCHAR (10)  NULL,
    [PostSale PREQUAL # (BDT/DSAT)]         VARCHAR (25)  NULL,
    [PostSale DSAT Lit Building?]           VARCHAR (5)   NULL,
    [PostSale ORDER # (STATS/SF/ASR)]       VARCHAR (25)  NULL,
    [PostSale CUST NAME]                    VARCHAR (100) NULL,
    [PostSale DSAT TIERS]                   VARCHAR (10)  NULL,
    [PostSale DSAT BW]                      VARCHAR (50)  NULL,
    [PostSale PREQUAL (BDT/DSAT) $]         MONEY         NULL,
    [PostSale BDT YR APPRVD]                VARCHAR (10)  NULL,
    [PostSale Retail OR Carrier]            VARCHAR (50)  NULL,
    [PostSale Term Months]                  INT           NULL,
    [PostSale MRC]                          MONEY         NULL,
    [PostSale NRC]                          MONEY         NULL,
    [PostSale Contract Signature/ASR Order] VARCHAR (25)  NULL,
    [PostSale VARASSET TICKET]              VARCHAR (50)  NULL,
    [PreSale Exchange]                      VARCHAR (50)  NULL,
    [PreSale OSP Capital]                   MONEY         NULL,
    [PreSale Total NPV Capital]             MONEY         NULL,
    [PreSale Common Capital]                MONEY         NULL,
    [PreSale MRC]                           MONEY         NULL,
    [PreSale NRC]                           MONEY         NULL,
    [PreSale CIAC]                          MONEY         NULL,
    [PreSale NPV]                           MONEY         NULL,
    [PreSale IRR]                           FLOAT (53)    NULL,
    [PreSale Payback]                       FLOAT (53)    NULL
);

