CREATE TABLE [ProjApproval].[Compute_PostSale_MDUSFU] (
    [Opportunity ID]           VARCHAR (50) NOT NULL,
    [ProjectNumber]            INT          NULL,
    [SubProjectNumber]         SMALLINT     NULL,
    [PostSale ISP Capital]     MONEY        NULL,
    [PostSale OSP Capital]     MONEY        NULL,
    [PostSale Total Capital]   MONEY        NULL,
    [PostSale CIAC]            MONEY        NULL,
    [PostSale Term]            INT          NULL,
    [PostSale MRC]             MONEY        NULL,
    [PostSale NRC]             MONEY        NULL,
    [PostSale NPV]             MONEY        NULL,
    [PostSale IRR]             FLOAT (53)   NULL,
    [PostSale PAYBACK]         FLOAT (53)   NULL,
    [TaxRate]                  FLOAT (53)   NULL,
    [Common Capital]           MONEY        NULL,
    [DiscountRate]             FLOAT (53)   NULL,
    [CIAC_ISP]                 MONEY        NULL,
    [CIAC_OSP]                 MONEY        NULL,
    [Payback]                  FLOAT (53)   NULL,
    [Supplement ISP Capital]   MONEY        NULL,
    [Supplement OSP Capital]   MONEY        NULL,
    [Supplement Total Capital] MONEY        NULL,
    [Supplement NPV]           MONEY        NULL,
    [Supplement IRR]           FLOAT (53)   NULL,
    [Supplement PAYBACK]       FLOAT (53)   NULL,
    [State]                    VARCHAR (2)  NULL,
    [DepreciationISP1]         MONEY        NULL,
    [DepreciationOSP1]         MONEY        NULL,
    [Tax1]                     MONEY        NULL,
    [DepreciationISP2]         MONEY        NULL,
    [DepreciationOSP2]         MONEY        NULL,
    [Tax2]                     MONEY        NULL,
    [DepreciationISP3]         MONEY        NULL,
    [DepreciationOSP3]         MONEY        NULL,
    [Tax3]                     MONEY        NULL,
    [DepreciationISP4]         MONEY        NULL,
    [DepreciationOSP4]         MONEY        NULL,
    [Tax4]                     MONEY        NULL,
    [DepreciationISP5]         MONEY        NULL,
    [DepreciationOSP5]         MONEY        NULL,
    [Tax5]                     MONEY        NULL,
    [DepreciationISP6]         MONEY        NULL,
    [DepreciationOSP6]         MONEY        NULL,
    [Tax6]                     MONEY        NULL,
    [DepreciationISP7]         MONEY        NULL,
    [DepreciationOSP7]         MONEY        NULL,
    [Tax7]                     MONEY        NULL,
    [DepreciationISP8]         MONEY        NULL,
    [DepreciationOSP8]         MONEY        NULL,
    [Tax8]                     MONEY        NULL,
    [DepreciationISP9]         MONEY        NULL,
    [DepreciationOSP9]         MONEY        NULL,
    [Tax9]                     MONEY        NULL,
    [DepreciationISP10]        MONEY        NULL,
    [DepreciationOSP10]        MONEY        NULL,
    [Tax10]                    MONEY        NULL,
    [DepreciationISP11]        MONEY        NULL,
    [DepreciationOSP11]        MONEY        NULL,
    [Tax11]                    MONEY        NULL,
    [C0]                       MONEY        NULL,
    [C1]                       MONEY        NULL,
    [C2]                       MONEY        NULL,
    [C3]                       MONEY        NULL,
    [C4]                       MONEY        NULL,
    [C5]                       MONEY        NULL,
    [C6]                       MONEY        NULL,
    [C7]                       MONEY        NULL,
    [C8]                       MONEY        NULL,
    [C9]                       MONEY        NULL,
    [C10]                      MONEY        NULL,
    [C11]                      MONEY        NULL,
    [CC0]                      MONEY        NULL,
    [CC1]                      MONEY        NULL,
    [CC2]                      MONEY        NULL,
    [CC3]                      MONEY        NULL,
    [CC4]                      MONEY        NULL,
    [CC5]                      MONEY        NULL,
    [CC6]                      MONEY        NULL,
    [CC7]                      MONEY        NULL,
    [CC8]                      MONEY        NULL,
    [CC9]                      MONEY        NULL,
    [CC10]                     MONEY        NULL,
    [CC11]                     MONEY        NULL,
    [P0]                       FLOAT (53)   NULL,
    [P1]                       FLOAT (53)   NULL,
    [P2]                       FLOAT (53)   NULL,
    [P3]                       FLOAT (53)   NULL,
    [P4]                       FLOAT (53)   NULL,
    [P5]                       FLOAT (53)   NULL,
    [P6]                       FLOAT (53)   NULL,
    [P7]                       FLOAT (53)   NULL,
    [P8]                       FLOAT (53)   NULL,
    [P9]                       FLOAT (53)   NULL,
    [P10]                      FLOAT (53)   NULL,
    [P11]                      FLOAT (53)   NULL
);

