CREATE TABLE [ProjApproval].[Compare_BDT_History_Trimmed] (
    [Opportunity ID]                        VARCHAR (50)  NULL,
    [PostSale STATE]                        VARCHAR (5)   NULL,
    [PostSale PROJECT]                      VARCHAR (10)  NULL,
    [PostSale SUB-PROJECT]                  VARCHAR (1)   NULL,
    [PostSale CIAC]                         MONEY         NULL,
    [PostSale PREQUAL TYPE]                 VARCHAR (10)  NULL,
    [PostSale PREQUAL # (BDT/DSAT)]         VARCHAR (25)  NULL,
    [PostSale DSAT Lit Building?]           VARCHAR (5)   NULL,
    [PostSale ORDER # (STATS/SF/ASR)]       VARCHAR (25)  NULL,
    [PostSale CUST NAME]                    VARCHAR (100) NULL,
    [PostSale DSAT TIERS]                   VARCHAR (10)  NULL,
    [PostSale DSAT BW]                      VARCHAR (50)  NULL,
    [PostSale PREQUAL (BDT/DSAT) $]         MONEY         NULL,
    [PostSale BDT YR APPRVD]                VARCHAR (10)  NULL,
    [PostSale Retail OR Carrier]            VARCHAR (50)  NULL,
    [PostSale Term Months]                  INT           NULL,
    [PostSale MRC]                          MONEY         NULL,
    [PostSale NRC]                          MONEY         NULL,
    [PostSale Contract Signature/ASR Order] VARCHAR (25)  NULL,
    [PostSale VARASSET TICKET]              VARCHAR (50)  NULL,
    [PreSale Exchange]                      VARCHAR (50)  NULL,
    [PreSale OSP Capital]                   MONEY         NULL,
    [PreSale Total NPV Capital]             MONEY         NULL,
    [PreSale Common Capital]                MONEY         NULL,
    [PreSale MRC]                           MONEY         NULL,
    [PreSale NRC]                           MONEY         NULL,
    [PreSale CIAC]                          MONEY         NULL,
    [PreSale NPV]                           MONEY         NULL,
    [PreSale IRR]                           FLOAT (53)    NULL,
    [PreSale Payback]                       FLOAT (53)    NULL,
    [C0]                                    MONEY         NULL,
    [C1]                                    MONEY         NULL,
    [C2]                                    MONEY         NULL,
    [C3]                                    MONEY         NULL,
    [C4]                                    MONEY         NULL,
    [C5]                                    MONEY         NULL,
    [C6]                                    MONEY         NULL,
    [C7]                                    MONEY         NULL,
    [C8]                                    MONEY         NULL,
    [C9]                                    MONEY         NULL,
    [C10]                                   MONEY         NULL,
    [C11]                                   MONEY         NULL,
    [CC0]                                   MONEY         NULL,
    [CC1]                                   MONEY         NULL,
    [CC2]                                   MONEY         NULL,
    [CC3]                                   MONEY         NULL,
    [CC4]                                   MONEY         NULL,
    [CC5]                                   MONEY         NULL,
    [CC6]                                   MONEY         NULL,
    [CC7]                                   MONEY         NULL,
    [CC8]                                   MONEY         NULL,
    [CC9]                                   MONEY         NULL,
    [CC10]                                  MONEY         NULL,
    [CC11]                                  MONEY         NULL,
    [PostSale ISP Capital]                  MONEY         NULL,
    [PostSale OSP Capital]                  MONEY         NULL,
    [PostSale Total Capital]                MONEY         NULL,
    [PostSale Common Capital]               MONEY         NULL,
    [Post_C0]                               MONEY         NULL,
    [Post_C1]                               MONEY         NULL,
    [Post_C2]                               MONEY         NULL,
    [Post_C3]                               MONEY         NULL,
    [Post_C4]                               MONEY         NULL,
    [Post_C5]                               MONEY         NULL,
    [Post_C6]                               MONEY         NULL,
    [Post_C7]                               MONEY         NULL,
    [Post_C8]                               MONEY         NULL,
    [Post_C9]                               MONEY         NULL,
    [Post_C10]                              MONEY         NULL,
    [Post_C11]                              MONEY         NULL,
    [Post_CC0]                              MONEY         NULL,
    [Post_CC1]                              MONEY         NULL,
    [Post_CC2]                              MONEY         NULL,
    [Post_CC3]                              MONEY         NULL,
    [Post_CC4]                              MONEY         NULL,
    [Post_CC5]                              MONEY         NULL,
    [Post_CC6]                              MONEY         NULL,
    [Post_CC7]                              MONEY         NULL,
    [Post_CC8]                              MONEY         NULL,
    [Post_CC9]                              MONEY         NULL,
    [Post_CC10]                             MONEY         NULL,
    [Post_CC11]                             MONEY         NULL,
    [PostSale NPV]                          MONEY         NULL,
    [PostSale IRR]                          FLOAT (53)    NULL,
    [PostSale Payback]                      FLOAT (53)    NULL
);

