CREATE TABLE [ProjApproval].[EditScreen_PreSale_Compiled] (
    [ID]                               VARCHAR (50)  NULL,
    [SubmitttedDtm]                    VARCHAR (50)  NULL,
    [SubmittedBy]                      VARCHAR (50)  NULL,
    [Opportunity ID]                   VARCHAR (50)  NULL,
    [Project Number]                   VARCHAR (50)  NULL,
    [Project Description]              VARCHAR (MAX) NULL,
    [BDT#]                             VARCHAR (50)  NULL,
    [CRC Date]                         VARCHAR (50)  NULL,
    [Budget Category]                  VARCHAR (50)  NULL,
    [Exchange]                         VARCHAR (50)  NULL,
    [State]                            VARCHAR (5)   NULL,
    [Total ISP Capital - Fully Loaded] VARCHAR (50)  NULL,
    [Total OSP Capital - Fully Loaded] VARCHAR (50)  NULL,
    [Total Capital - Fully Loaded]     VARCHAR (50)  NULL,
    [MRC - Fully Loaded]               VARCHAR (50)  NULL,
    [CIAC - Fully Loaded]              VARCHAR (50)  NULL,
    [NPV - Fully Loaded]               VARCHAR (50)  NULL,
    [IRR - Fully Loaded]               VARCHAR (50)  NULL,
    [Payback - Fully Loaded]           VARCHAR (50)  NULL,
    [Total ISP Capital - 20% Loaded]   VARCHAR (50)  NULL,
    [Total OSP Capital - 20% Loaded]   VARCHAR (50)  NULL,
    [Total Capital - 20% Loaded]       VARCHAR (50)  NULL,
    [MRC - 20% Loaded]                 VARCHAR (50)  NULL,
    [CIAC - 20% Loaded]                VARCHAR (50)  NULL,
    [NPV - 20% Loaded]                 VARCHAR (50)  NULL,
    [IRR - 20% Loaded]                 VARCHAR (50)  NULL,
    [Payback - 20% Loaded]             VARCHAR (50)  NULL,
    [Term in Months]                   VARCHAR (50)  NULL,
    [Bandwidth (Number of Units)]      VARCHAR (50)  NULL,
    [Bandwidth (Unit of Measurement)]  VARCHAR (50)  NULL,
    [NRC]                              VARCHAR (50)  NULL,
    [Monthly Expense]                  VARCHAR (50)  NULL,
    [Capital Request]                  VARCHAR (50)  NULL,
    [Capital Request Q1]               VARCHAR (50)  NULL,
    [Capital Request Q2]               VARCHAR (50)  NULL,
    [Capital Request Q3]               VARCHAR (50)  NULL,
    [Capital Request Q4]               VARCHAR (50)  NULL,
    [Capital Cost Future Years]        VARCHAR (50)  NULL,
    [Street Address]                   VARCHAR (50)  NULL,
    [City]                             VARCHAR (50)  NULL,
    [ZIP]                              VARCHAR (50)  NULL,
    [Link Code]                        VARCHAR (50)  NULL,
    [Build]                            VARCHAR (50)  NULL,
    [Grants Name]                      VARCHAR (50)  NULL,
    [Cost Per Household]               VARCHAR (50)  NULL,
    [Household Forecast]               VARCHAR (50)  NULL,
    [Take Rate]                        VARCHAR (50)  NULL,
    [Cost To Connect]                  VARCHAR (50)  NULL,
    [Video Enabled State]              VARCHAR (50)  NULL,
    [Type of Deal]                     VARCHAR (50)  NULL,
    [Unit Opportunity]                 VARCHAR (50)  NULL,
    [Cost Per Unit]                    VARCHAR (50)  NULL,
    [Unit Forecast]                    VARCHAR (50)  NULL,
    [Take Rate - Engineering/Proforma] VARCHAR (50)  NULL,
    [ROI Take Rate]                    VARCHAR (50)  NULL,
    [Average Take Rate]                VARCHAR (50)  NULL,
    [Total Revenue]                    VARCHAR (50)  NULL,
    [Competitor]                       VARCHAR (50)  NULL,
    [Brownfield/Greenfield]            VARCHAR (50)  NULL,
    [Notes]                            VARCHAR (MAX) NULL,
    [Additional Documents]             VARCHAR (MAX) NULL
);

