CREATE TABLE [ProjApproval].[InputScreen_PreSale_Facilities] (
    [ID]                        VARCHAR (50)  NULL,
    [Start time]                VARCHAR (50)  NULL,
    [SubmitttedDtm]             VARCHAR (50)  NULL,
    [SubmittedBy]               VARCHAR (50)  NULL,
    [Name]                      VARCHAR (50)  NULL,
    [CRC Date]                  VARCHAR (50)  NULL,
    [Budget Category]           VARCHAR (50)  NULL,
    [Street Address]            VARCHAR (50)  NULL,
    [City]                      VARCHAR (50)  NULL,
    [State]                     VARCHAR (50)  NULL,
    [ZIP Code]                  VARCHAR (50)  NULL,
    [Project Number]            VARCHAR (50)  NULL,
    [Project Description]       VARCHAR (MAX) NULL,
    [Total Capital Cost]        VARCHAR (50)  NULL,
    [Capital Request]           VARCHAR (50)  NULL,
    [Capital Request Q1]        VARCHAR (50)  NULL,
    [Capital Request Q2]        VARCHAR (50)  NULL,
    [Capital Request Q3]        VARCHAR (50)  NULL,
    [Capital Request Q4]        VARCHAR (50)  NULL,
    [Capital Cost Future Years] VARCHAR (50)  NULL,
    [Link Code]                 VARCHAR (50)  NULL,
    [Additional Documents]      VARCHAR (MAX) NULL
);

