CREATE TABLE [ProjApproval].[InputScreen_PreSale_BDT] (
    [ID]                               VARCHAR (50)  NULL,
    [Start time]                       VARCHAR (50)  NULL,
    [SubmitttedDtm]                    VARCHAR (50)  NULL,
    [SubmittedBy]                      VARCHAR (50)  NULL,
    [Name]                             VARCHAR (50)  NULL,
    [CRC Date]                         VARCHAR (50)  NULL,
    [BDT#]                             VARCHAR (50)  NULL,
    [Description]                      VARCHAR (MAX) NULL,
    [Budget Category]                  VARCHAR (50)  NULL,
    [Exchange]                         VARCHAR (50)  NULL,
    [State]                            VARCHAR (50)  NULL,
    [Total ISP Capital - Fully Loaded] VARCHAR (50)  NULL,
    [Total OSP Capital - Fully Loaded] VARCHAR (50)  NULL,
    [Total Capital - Fully Loaded]     VARCHAR (50)  NULL,
    [MRC - Fully Loaded]               VARCHAR (50)  NULL,
    [CIAC - Fully Loaded]              VARCHAR (50)  NULL,
    [NPV - Fully Loaded]               VARCHAR (50)  NULL,
    [IRR - Fully Loaded]               VARCHAR (10)  NULL,
    [Payback - Fully Loaded]           VARCHAR (10)  NULL,
    [Total ISP Capital - 20% Loaded]   VARCHAR (50)  NULL,
    [Total OSP Capital - 20% Loaded]   VARCHAR (50)  NULL,
    [Total Capital - 20% Loaded]       VARCHAR (50)  NULL,
    [MRC - 20% Loaded]                 VARCHAR (50)  NULL,
    [CIAC - 20% Loaded]                VARCHAR (50)  NULL,
    [NPV - 20% Loaded]                 VARCHAR (50)  NULL,
    [IRR - 20% Loaded]                 VARCHAR (10)  NULL,
    [Payback - 20% Loaded]             VARCHAR (10)  NULL,
    [Term in Months]                   VARCHAR (10)  NULL,
    [Bandwidth (Number of Units)]      VARCHAR (50)  NULL,
    [Bandwidth (Unit of Measurement)]  VARCHAR (50)  NULL,
    [NRC]                              VARCHAR (50)  NULL,
    [Monthly Expense]                  VARCHAR (50)  NULL,
    [Notes]                            VARCHAR (MAX) NULL,
    [Additional Documents]             VARCHAR (MAX) NULL
);

