CREATE TABLE [ProjApproval].[InputScreen_PreSale_CRC_Trimmed] (
    [Opportunity ID]            VARCHAR (50)  NULL,
    [Start time]                VARCHAR (50)  NULL,
    [SubmitttedDtm]             VARCHAR (50)  NULL,
    [SubmittedBy]               VARCHAR (50)  NULL,
    [Name]                      VARCHAR (50)  NULL,
    [CRC Date]                  VARCHAR (50)  NULL,
    [Budget Category]           VARCHAR (50)  NULL,
    [Project Number]            VARCHAR (10)  NULL,
    [Project Description]       VARCHAR (MAX) NULL,
    [State]                     VARCHAR (50)  NULL,
    [Exchange]                  VARCHAR (50)  NULL,
    [Capital Request]           VARCHAR (50)  NULL,
    [Capital Request Q1]        VARCHAR (50)  NULL,
    [Capital Request Q2]        VARCHAR (50)  NULL,
    [Capital Request Q3]        VARCHAR (50)  NULL,
    [Capital Request Q4]        VARCHAR (50)  NULL,
    [Capital Cost Future Years] VARCHAR (50)  NULL,
    [Total ISP Capital]         VARCHAR (50)  NULL,
    [Total OSP Capital]         VARCHAR (50)  NULL,
    [Total Capital]             VARCHAR (50)  NULL,
    [MRC]                       VARCHAR (50)  NULL,
    [NRC]                       VARCHAR (50)  NULL,
    [Monthly Expense]           VARCHAR (50)  NULL,
    [CIAC]                      VARCHAR (50)  NULL,
    [NPV]                       VARCHAR (50)  NULL,
    [IRR]                       VARCHAR (10)  NULL,
    [Payback]                   VARCHAR (5)   NULL,
    [Terms (in months)]         VARCHAR (10)  NULL,
    [Notes]                     VARCHAR (MAX) NULL,
    [Additional Documents]      VARCHAR (MAX) NULL
);

