CREATE TABLE [ProjApproval].[InputScreen_PreSale_MDUSubdivision_Trimmed] (
    [Opportunity ID]                     VARCHAR (50)  NULL,
    [Start time]                         VARCHAR (50)  NULL,
    [SubmitttedDtm]                      VARCHAR (50)  NULL,
    [SubmittedBy]                        VARCHAR (50)  NULL,
    [Name]                               VARCHAR (50)  NULL,
    [CRC Date]                           VARCHAR (50)  NULL,
    [Budget Category]                    VARCHAR (50)  NULL,
    [Build]                              VARCHAR (50)  NULL,
    [Project Description]                VARCHAR (200) NULL,
    [State]                              VARCHAR (10)  NULL,
    [Exchange]                           VARCHAR (50)  NULL,
    [BDT#]                               VARCHAR (50)  NULL,
    [Project Number]                     VARCHAR (10)  NULL,
    [Unit Opportunity - Number of Units] VARCHAR (10)  NULL,
    [Cost Per Unit]                      VARCHAR (50)  NULL,
    [Unit Forecast]                      VARCHAR (50)  NULL,
    [Take Rate - Engineering/Proforma]   VARCHAR (10)  NULL,
    [ROI Take Rate]                      VARCHAR (10)  NULL,
    [Average Take Rate]                  VARCHAR (10)  NULL,
    [Capital Request]                    VARCHAR (50)  NULL,
    [Capital Request Q1]                 VARCHAR (50)  NULL,
    [Capital Request Q2]                 VARCHAR (50)  NULL,
    [Capital Request Q3]                 VARCHAR (50)  NULL,
    [Capital Request Q4]                 VARCHAR (50)  NULL,
    [Capital Cost Future Years]          VARCHAR (50)  NULL,
    [Cost To Connect]                    VARCHAR (50)  NULL,
    [Total ISP Capital]                  VARCHAR (50)  NULL,
    [Total OSP Capital]                  VARCHAR (50)  NULL,
    [Total Capital]                      VARCHAR (50)  NULL,
    [Total Revenue]                      VARCHAR (50)  NULL,
    [Monthly Expense]                    VARCHAR (50)  NULL,
    [CIAC]                               VARCHAR (50)  NULL,
    [NPV]                                VARCHAR (50)  NULL,
    [IRR]                                VARCHAR (10)  NULL,
    [Payback]                            VARCHAR (10)  NULL,
    [Competitor]                         VARCHAR (100) NULL,
    [Video Enabled State]                VARCHAR (50)  NULL,
    [Terms in Months]                    VARCHAR (10)  NULL,
    [Type of Deal]                       VARCHAR (50)  NULL,
    [Brownfield/Greenfield]              VARCHAR (50)  NULL,
    [Link Code]                          VARCHAR (50)  NULL,
    [Notes]                              VARCHAR (MAX) NULL,
    [Additional Documents]               VARCHAR (MAX) NULL
);

