CREATE TABLE [ProjApproval].[InputScreen_Supplements] (
    [ID]                   VARCHAR (50)  NULL,
    [Start time]           VARCHAR (50)  NULL,
    [SubmitttedDtm]        VARCHAR (50)  NULL,
    [SubmittedBy]          VARCHAR (50)  NULL,
    [Name]                 VARCHAR (50)  NULL,
    [CRC Date]             VARCHAR (50)  NULL,
    [Budget Category]      VARCHAR (50)  NULL,
    [Link Code]            VARCHAR (50)  NULL,
    [Project Description]  VARCHAR (200) NULL,
    [Project Number 1]     VARCHAR (10)  NULL,
    [Project Number 2]     VARCHAR (10)  NULL,
    [Project Number 3]     VARCHAR (10)  NULL,
    [Project Number 4]     VARCHAR (10)  NULL,
    [Project Number 5]     VARCHAR (10)  NULL,
    [Project Number 6]     VARCHAR (10)  NULL,
    [Project Number 7]     VARCHAR (10)  NULL,
    [Project Number 8]     VARCHAR (10)  NULL,
    [Project Number 9]     VARCHAR (10)  NULL,
    [Project Number 10]    VARCHAR (10)  NULL,
    [Total ISP Capital]    VARCHAR (50)  NULL,
    [Total OSP Capital]    VARCHAR (50)  NULL,
    [Total Capital]        VARCHAR (50)  NULL,
    [Monthly Expense]      VARCHAR (50)  NULL,
    [NPV]                  VARCHAR (50)  NULL,
    [IRR]                  VARCHAR (10)  NULL,
    [Payback]              VARCHAR (10)  NULL,
    [State]                VARCHAR (10)  NULL,
    [Exchange]             VARCHAR (50)  NULL,
    [Notes]                VARCHAR (MAX) NULL,
    [Additional Documents] VARCHAR (MAX) NULL
);

