CREATE PROCEDURE WCF.[usp_UPDATE_CONSOLIDATED_DATA_TABLE] AS

TRUNCATE TABLE [WCF].[CONSOLIDATED_DATA_TABLE]
INSERT INTO [WCF].[CONSOLIDATED_DATA_TABLE]

SELECT DSAT.wireCenterClli
	  ,DSAT.STATE
      ,LABOR.[Copper troubles] as [Copper troubles]
      ,LABOR.[Fiber troubles] as [Fiber troubles]
      ,LABOR.[Copper new adds] as [Copper new adds]
      ,LABOR.[Fiber new adds] as [Fiber new adds]
      ,LABOR.[Cost per fiber trouble] as [Cost per fiber trouble]
      ,LABOR.[Cost per copper trouble ticket] as [Cost per copper trouble ticket]
      ,LABOR.[Cost per copper new add] as [Cost per copper new add]
      ,LABOR.[Cost per fiber new add] as [Cost per fiber new add]
      ,LABOR.[Copper Trouble OOP Labor] as [Copper Trouble OOP Labor]
      ,LABOR.[Fiber trouble OOP Labor] as [Fiber trouble OOP Labor]
      ,LABOR.[Fiber new add labor] as [Fiber new add labor]
      ,LABOR.[Copper new add OOP labor] as [Copper new add OOP labor]
      ,LABOR.[Copper Labor] as [Copper Labor]
      ,LABOR.[Fiber Labor] as [Fiber Labor]
      ,TSO.[TSO Calls] as [TSO Calls]
      ,TSO.[Cost per call] as [Cost per call]
      ,TSO.[TSO Costs] as [TSO Costs]
	  ,NETWORK.[Network Operations] as [Network Operations]
      ,NETWORK.[Network Distribution] as [Network Distribution]
      ,NETWORK.[Assignment] as [Assignment]
      ,NETWORK.[Network Core] as [Network Core]
      ,NETWORK.[Circuits COGS] as [Circuits COGS]
      ,NETWORK.[Network Ops Support] as [Network Ops Support]
      ,NETWORK.[Voice COGS] as [Voice COGS]
      ,NETWORK.[SS7 Circuit] as [SS7 Circuit]
      ,NETWORK.[Cable Locates] as [Cable Locates]
      ,NETWORK.[Plant Maintenance] as [Plant Maintenance]
      ,NETWORK.[Poles] as [Poles]
      ,NETWORK.[Jointly Owned Poles] as [Jointly Owned Poles]
      ,NETWORK.[Plant Maintenance and Constructions] as [Plant Maintenance and Constructions]
      ,NETWORK.[Network Access] as [Network Access]
      ,NETWORK.[Total] as [Total]
	  ,SEG.[ABU > 81% of Customers] as [ABU > 81% of Customers]
      ,SEG.[ABU 61-80% of Customers] as [ABU 61-80% of Customers]
      ,SEG.[ABU 41-60% of Customers] as [ABU 41-60% of Customers]
      ,SEG.[ABU 21-40% of Customers] as [ABU 21-40% of Customers]
      ,SEG.[ABU 1-20% of Customers] as [ABU 1-20% of Customers]
      ,SEG.[ABU 0% of Customers] as [ABU 0% of Customers]
      ,SEG.[BEAD > 81% of Customers] as [BEAD > 81% of Customers]
      ,SEG.[BEAD 61-80% of Customers] as [BEAD 61-80% of Customers]
      ,SEG.[BEAD 41-60% of Customers] as [BEAD 41-60% of Customers]
      ,SEG.[BEAD 21-40% of Customers] as [BEAD 21-40% of Customers]
      ,SEG.[BEAD 1-20% of Customers] as [BEAD 1-20% of Customers]
      ,SEG.[BEAD 0% of Customers] as [BEAD 0% of Customers]
      ,SEG.[Hyperion] as [Hyperion]
      ,SEG.[Regulatory Guidance - Green] as [Regulatory Guidance - Green]
      ,SEG.[Regulatory Guidance - Yellow] as [Regulatory Guidance - Yellow]
      ,SEG.[Regulatory Guidance - Red] as [Regulatory Guidance - Red]
      ,SEG.[Tarriff Restrictions - Green] as [Tarriff Restrictions - Green]
      ,SEG.[Tarriff Restrictions - Yellow] as [Tarriff Restrictions - Yellow]
      ,SEG.[Tarriff Restrictions - Red] as [Tarriff Restrictions - Red]
	  ,SUM(SAC.[2023 New Copper Installs]) AS [2023 New Copper Installs]
      ,SUM(SAC.[Applied SAC per install])  AS [Applied SAC per install]
      ,SUM(SAC.[SAC])					   AS [SAC]
	  ,SUM(POWER.[Extractable Copper Power Expense]) AS [Extractable Copper Power Expense]
	  ,SUM(LOB.[Consumer - Total Fiber Customers] ) AS [Consumer - Total Fiber Customers]
      ,SUM(LOB.[Consumer - Fiber Voice Only Customers]) AS [Consumer - Fiber Voice Only Customers]
      ,SUM(LOB.[Consumer - Fiber Broadband Only Customers]) AS [Consumer - Fiber Broadband Only Customers]
      ,SUM(LOB.[Consumer - Fiber Video Only Customers]) AS [Consumer - Fiber Video Only Customers]
      ,SUM(LOB.[Consumer - Fiber Voice & Broadband Customers]) AS [Consumer - Fiber Voice & Broadband Customers]
      ,SUM(LOB.[Consumer - Fiber Broadband & Video Customers]) AS [Consumer - Fiber Broadband & Video Customers]
      ,SUM(LOB.[Consumer - Fiber Voice & Video]) AS [Consumer - Fiber Voice & Video]
      ,SUM(LOB.[Consumer - Fiber No Core Products Customers]) AS [Consumer - Fiber No Core Products Customers]
      ,SUM(LOB.[Consumer - Total Copper Customers]) AS [Consumer - Total Copper Customers]
      ,SUM(LOB.[Consumer - Copper Voice Only Customers]) AS [Consumer - Copper Voice Only Customers]
      ,SUM(LOB.[Consumer - Copper Broadband Only Customers]) AS [Consumer - Copper Broadband Only Customers]
      ,SUM(LOB.[Consumer - Copper Video Only Customers]) AS [Consumer - Copper Video Only Customers]
      ,SUM(LOB.[Consumer - Copper Voice & Broadband Customers]) AS [Consumer - Copper Voice & Broadband Customers]
      ,SUM(LOB.[Consumer - Copper Broadband & Video Customers]) AS [Consumer - Copper Broadband & Video Customers]
      ,SUM(LOB.[Consumer - Copper Voice & Video]) AS [Consumer - Copper Voice & Video]
      ,SUM(LOB.[Consumer - Copper Broadband & Voice & Video]) AS [Consumer - Copper Broadband & Voice & Video]
      ,SUM(LOB.[Consumer - Copper No Core Products Customers]) AS [Consumer - Copper No Core Products Customers]
      ,SUM(LOB.[SMB - Fiber Customers]) AS [SMB - Fiber Customers]
      ,SUM(LOB.[SMB- Fiber Voice Only Customers]) AS [SMB- Fiber Voice Only Customers]
      ,SUM(LOB.[SMB - Fiber Broadband Only Customers]) AS [SMB - Fiber Broadband Only Customers]
      ,SUM(LOB.[SMB - Fiber Video Only Customers]) AS [SMB - Fiber Video Only Customers]
      ,SUM(LOB.[SMB - Fiber Voice & Broadband Customers]) AS [SMB - Fiber Voice & Broadband Customers]
      ,SUM(LOB.[SMB - Fiber Broadband & Video Customers]) AS [SMB - Fiber Broadband & Video Customers]
      ,SUM(LOB.[SMB - Fiber Voice & Video]) AS [SMB - Fiber Voice & Video]
      ,SUM(LOB.[SMB - Fiber No Core Products Customers]) AS [SMB - Fiber No Core Products Customers]
      ,SUM(LOB.[SMB - Total Copper Customers]) AS [SMB - Total Copper Customers]
      ,SUM(LOB.[SMB - Copper Voice Only Customers]) AS [SMB - Copper Voice Only Customers]
      ,SUM(LOB.[SMB - Copper Broadband Only Customers]) AS [SMB - Copper Broadband Only Customers]
      ,SUM(LOB.[SMB - Copper Video Only Customers]) AS [SMB - Copper Video Only Customers]
      ,SUM(LOB.[SMB - Copper Voice & Broadband Customers]) AS [SMB - Copper Voice & Broadband Customers]
      ,SUM(LOB.[SMB - Copper Broadband & Video Customers]) AS [SMB - Copper Broadband & Video Customers]
      ,SUM(LOB.[SMB - Copper Voice & Video]) AS [SMB - Copper Voice & Video]
      ,SUM(LOB.[SMB - Copper Broadband & Voice & Video]) AS [SMB - Copper Broadband & Voice & Video]
      ,SUM(LOB.[SMB - Copper No Core Products Customers]) AS [SMB - Copper No Core Products Customers]
      ,SUM(LOB.[ENT - Total Fiber Customers]) AS [ENT - Total Fiber Customers]
      ,SUM(LOB.[ENT - Fiber Voice Only Customers]) AS [ENT - Fiber Voice Only Customers]
      ,SUM(LOB.[ENT - Fiber Broadband Only Customers]) AS [ENT - Fiber Broadband Only Customers]
      ,SUM(LOB.[ENT - Fiber Video Only Customers]) AS [ENT - Fiber Video Only Customers]
      ,SUM(LOB.[ENT - Fiber Voice & Broadband Customers]) AS [ENT - Fiber Voice & Broadband Customers]
      ,SUM(LOB.[ENT - Fiber Broadband & Video Customers]) AS [ENT - Fiber Broadband & Video Customers]
      ,SUM(LOB.[ENT - Fiber Voice & Video]) AS [ENT - Fiber Voice & Video]
      ,SUM(LOB.[ENT - Fiber No Core Products Customers]) AS [ENT - Fiber No Core Products Customers]
      ,SUM(LOB.[ENT - Total Copper Customers]) AS [ENT - Total Copper Customers]
      ,SUM(LOB.[ENT - Copper Voice Only Customers]) AS [ENT - Copper Voice Only Customers]
      ,SUM(LOB.[ENT - Copper Broadband Only Customers]) AS [ENT - Copper Broadband Only Customers]
      ,SUM(LOB.[ENT - Copper Video Only Customers]) AS [ENT - Copper Video Only Customers]
      ,SUM(LOB.[ENT - Copper Voice & Broadband Customers]) AS [ENT - Copper Voice & Broadband Customers]
      ,SUM(LOB.[ENT - Copper Broadband & Video Customers]) AS [ENT - Copper Broadband & Video Customers]
      ,SUM(LOB.[ENT - Copper Voice & Video]) AS [ENT - Copper Voice & Video]
      ,SUM(LOB.[ENT - Copper Broadband & Voice & Video]) AS [ENT - Copper Broadband & Voice & Video]
      ,SUM(LOB.[ENT - Copper No Core Products Customers]) AS [ENT - Copper No Core Products Customers]
      ,SUM(LOB.[ENT - Circuits]) AS [ENT - Circuits]
      ,SUM(LOB.[Paystation -  Total Customers (Voice)]) AS [Paystation -  Total Customers (Voice)]
      ,SUM(LOB.[Wholesale - Total Fiber Customers]) AS [Wholesale - Total Fiber Customers]
      ,SUM(LOB.[Wholesale - Fiber Voice Only Customers]) AS [Wholesale - Fiber Voice Only Customers]
      ,SUM(LOB.[Wholesale - Fiber Broadband Only Customers]) AS [Wholesale - Fiber Broadband Only Customers]
      ,SUM(LOB.[Wholesale - Fiber Video Only Customers]) AS [Wholesale - Fiber Video Only Customers]
      ,SUM(LOB.[Wholesale - Fiber Voice & Broadband Customers]) AS [Wholesale - Fiber Voice & Broadband Customers]
      ,SUM(LOB.[Wholesale - Fiber Broadband & Video Customers]) AS [Wholesale - Fiber Broadband & Video Customers]
      ,SUM(LOB.[Wholesale - Fiber Voice & Video]) AS [Wholesale - Fiber Voice & Video]
      ,SUM(LOB.[Wholesale - Fiber No Core Products Customers]) AS [Wholesale - Fiber No Core Products Customers]
      ,SUM(LOB.[Wholesale - Total Copper Customers]) AS [Wholesale - Total Copper Customers]
      ,SUM(LOB.[Wholesale - Copper Voice Only Customers]) AS [Wholesale - Copper Voice Only Customers]
      ,SUM(LOB.[Wholesale - Copper Broadband Only Customers]) AS [Wholesale - Copper Broadband Only Customers]
      ,SUM(LOB.[Wholesale - Copper Video Only Customers]) AS [Wholesale - Copper Video Only Customers]
      ,SUM(LOB.[Wholesale - Copper Voice & Broadband Customers]) AS [Wholesale - Copper Voice & Broadband Customers]
      ,SUM(LOB.[Wholesale - Copper Broadband & Video Customers]) AS [Wholesale - Copper Broadband & Video Customers]
      ,SUM(LOB.[Wholesale - Copper Voice & Video]) AS [Wholesale - Copper Voice & Video]
      ,SUM(LOB.[Wholesale - Copper Broadband & Voice & Video]) AS [Wholesale - Copper Broadband & Voice & Video]
      ,SUM(LOB.[Wholesale - Copper No Core Products Customers]) AS [Wholesale - Copper No Core Products Customers]
      ,SUM(LOB.[Wholesale - Circuits]) AS [Wholesale - Circuits]
FROM TOWERS_UNIVERSE.DSAT_MATRIX_V DSAT

LEFT JOIN WCF.TBL_LABOR LABOR
ON DSAT.wireCenterClli = LABOR.CLLI
AND DSAT.STATE = LABOR.STATE

LEFT JOIN WCF.TBL_TSO TSO
ON DSAT.wireCenterClli = TSO.CLLI
AND DSAT.STATE = TSO.STATE

LEFT JOIN WCF.TBL_NETWORK NETWORK
ON DSAT.wireCenterClli = NETWORK.CLLI
AND DSAT.STATE = NETWORK.STATE

LEFT JOIN WCF.TBL_SEGMENTATION SEG
ON DSAT.wireCenterClli = SEG.Wirecenter


LEFT JOIN (select
CLLI
,SUM(SAC.[2023 New Copper Installs]) AS [2023 New Copper Installs]
,SUM(SAC.[Applied SAC per install])  AS [Applied SAC per install]
,SUM(SAC.[SAC])					   AS [SAC]

FROM WCF.TBL_SAC SAC
GROUP BY CLLI) SAC
ON DSAT.wireCenterClli = sac.CLLI

LEFT JOIN (select 
Wirecenter
,sum([extractable copper power expense]) as [extractable copper power expense]

from WCF.TBL_POWER

group by wirecenter) POWER
ON DSAT.wireCenterClli = power.wirecenter

LEFT JOIN (select 
wirecenter
	  ,SUM(LOB.[Consumer - Total Fiber Customers] ) AS [Consumer - Total Fiber Customers]
      ,SUM(LOB.[Consumer - Fiber Voice Only Customers]) AS [Consumer - Fiber Voice Only Customers]
      ,SUM(LOB.[Consumer - Fiber Broadband Only Customers]) AS [Consumer - Fiber Broadband Only Customers]
      ,SUM(LOB.[Consumer - Fiber Video Only Customers]) AS [Consumer - Fiber Video Only Customers]
      ,SUM(LOB.[Consumer - Fiber Voice & Broadband Customers]) AS [Consumer - Fiber Voice & Broadband Customers]
      ,SUM(LOB.[Consumer - Fiber Broadband & Video Customers]) AS [Consumer - Fiber Broadband & Video Customers]
      ,SUM(LOB.[Consumer - Fiber Voice & Video]) AS [Consumer - Fiber Voice & Video]
      ,SUM(LOB.[Consumer - Fiber No Core Products Customers]) AS [Consumer - Fiber No Core Products Customers]
      ,SUM(LOB.[Consumer - Total Copper Customers]) AS [Consumer - Total Copper Customers]
      ,SUM(LOB.[Consumer - Copper Voice Only Customers]) AS [Consumer - Copper Voice Only Customers]
      ,SUM(LOB.[Consumer - Copper Broadband Only Customers]) AS [Consumer - Copper Broadband Only Customers]
      ,SUM(LOB.[Consumer - Copper Video Only Customers]) AS [Consumer - Copper Video Only Customers]
      ,SUM(LOB.[Consumer - Copper Voice & Broadband Customers]) AS [Consumer - Copper Voice & Broadband Customers]
      ,SUM(LOB.[Consumer - Copper Broadband & Video Customers]) AS [Consumer - Copper Broadband & Video Customers]
      ,SUM(LOB.[Consumer - Copper Voice & Video]) AS [Consumer - Copper Voice & Video]
      ,SUM(LOB.[Consumer - Copper Broadband & Voice & Video]) AS [Consumer - Copper Broadband & Voice & Video]
      ,SUM(LOB.[Consumer - Copper No Core Products Customers]) AS [Consumer - Copper No Core Products Customers]
      ,SUM(LOB.[SMB - Fiber Customers]) AS [SMB - Fiber Customers]
      ,SUM(LOB.[SMB- Fiber Voice Only Customers]) AS [SMB- Fiber Voice Only Customers]
      ,SUM(LOB.[SMB - Fiber Broadband Only Customers]) AS [SMB - Fiber Broadband Only Customers]
      ,SUM(LOB.[SMB - Fiber Video Only Customers]) AS [SMB - Fiber Video Only Customers]
      ,SUM(LOB.[SMB - Fiber Voice & Broadband Customers]) AS [SMB - Fiber Voice & Broadband Customers]
      ,SUM(LOB.[SMB - Fiber Broadband & Video Customers]) AS [SMB - Fiber Broadband & Video Customers]
      ,SUM(LOB.[SMB - Fiber Voice & Video]) AS [SMB - Fiber Voice & Video]
      ,SUM(LOB.[SMB - Fiber No Core Products Customers]) AS [SMB - Fiber No Core Products Customers]
      ,SUM(LOB.[SMB - Total Copper Customers]) AS [SMB - Total Copper Customers]
      ,SUM(LOB.[SMB - Copper Voice Only Customers]) AS [SMB - Copper Voice Only Customers]
      ,SUM(LOB.[SMB - Copper Broadband Only Customers]) AS [SMB - Copper Broadband Only Customers]
      ,SUM(LOB.[SMB - Copper Video Only Customers]) AS [SMB - Copper Video Only Customers]
      ,SUM(LOB.[SMB - Copper Voice & Broadband Customers]) AS [SMB - Copper Voice & Broadband Customers]
      ,SUM(LOB.[SMB - Copper Broadband & Video Customers]) AS [SMB - Copper Broadband & Video Customers]
      ,SUM(LOB.[SMB - Copper Voice & Video]) AS [SMB - Copper Voice & Video]
      ,SUM(LOB.[SMB - Copper Broadband & Voice & Video]) AS [SMB - Copper Broadband & Voice & Video]
      ,SUM(LOB.[SMB - Copper No Core Products Customers]) AS [SMB - Copper No Core Products Customers]
      ,SUM(LOB.[ENT - Total Fiber Customers]) AS [ENT - Total Fiber Customers]
      ,SUM(LOB.[ENT - Fiber Voice Only Customers]) AS [ENT - Fiber Voice Only Customers]
      ,SUM(LOB.[ENT - Fiber Broadband Only Customers]) AS [ENT - Fiber Broadband Only Customers]
      ,SUM(LOB.[ENT - Fiber Video Only Customers]) AS [ENT - Fiber Video Only Customers]
      ,SUM(LOB.[ENT - Fiber Voice & Broadband Customers]) AS [ENT - Fiber Voice & Broadband Customers]
      ,SUM(LOB.[ENT - Fiber Broadband & Video Customers]) AS [ENT - Fiber Broadband & Video Customers]
      ,SUM(LOB.[ENT - Fiber Voice & Video]) AS [ENT - Fiber Voice & Video]
      ,SUM(LOB.[ENT - Fiber No Core Products Customers]) AS [ENT - Fiber No Core Products Customers]
      ,SUM(LOB.[ENT - Total Copper Customers]) AS [ENT - Total Copper Customers]
      ,SUM(LOB.[ENT - Copper Voice Only Customers]) AS [ENT - Copper Voice Only Customers]
      ,SUM(LOB.[ENT - Copper Broadband Only Customers]) AS [ENT - Copper Broadband Only Customers]
      ,SUM(LOB.[ENT - Copper Video Only Customers]) AS [ENT - Copper Video Only Customers]
      ,SUM(LOB.[ENT - Copper Voice & Broadband Customers]) AS [ENT - Copper Voice & Broadband Customers]
      ,SUM(LOB.[ENT - Copper Broadband & Video Customers]) AS [ENT - Copper Broadband & Video Customers]
      ,SUM(LOB.[ENT - Copper Voice & Video]) AS [ENT - Copper Voice & Video]
      ,SUM(LOB.[ENT - Copper Broadband & Voice & Video]) AS [ENT - Copper Broadband & Voice & Video]
      ,SUM(LOB.[ENT - Copper No Core Products Customers]) AS [ENT - Copper No Core Products Customers]
      ,SUM(LOB.[ENT - Circuits]) AS [ENT - Circuits]
      ,SUM(LOB.[Paystation -  Total Customers (Voice)]) AS [Paystation -  Total Customers (Voice)]
      ,SUM(LOB.[Wholesale - Total Fiber Customers]) AS [Wholesale - Total Fiber Customers]
      ,SUM(LOB.[Wholesale - Fiber Voice Only Customers]) AS [Wholesale - Fiber Voice Only Customers]
      ,SUM(LOB.[Wholesale - Fiber Broadband Only Customers]) AS [Wholesale - Fiber Broadband Only Customers]
      ,SUM(LOB.[Wholesale - Fiber Video Only Customers]) AS [Wholesale - Fiber Video Only Customers]
      ,SUM(LOB.[Wholesale - Fiber Voice & Broadband Customers]) AS [Wholesale - Fiber Voice & Broadband Customers]
      ,SUM(LOB.[Wholesale - Fiber Broadband & Video Customers]) AS [Wholesale - Fiber Broadband & Video Customers]
      ,SUM(LOB.[Wholesale - Fiber Voice & Video]) AS [Wholesale - Fiber Voice & Video]
      ,SUM(LOB.[Wholesale - Fiber No Core Products Customers]) AS [Wholesale - Fiber No Core Products Customers]
      ,SUM(LOB.[Wholesale - Total Copper Customers]) AS [Wholesale - Total Copper Customers]
      ,SUM(LOB.[Wholesale - Copper Voice Only Customers]) AS [Wholesale - Copper Voice Only Customers]
      ,SUM(LOB.[Wholesale - Copper Broadband Only Customers]) AS [Wholesale - Copper Broadband Only Customers]
      ,SUM(LOB.[Wholesale - Copper Video Only Customers]) AS [Wholesale - Copper Video Only Customers]
      ,SUM(LOB.[Wholesale - Copper Voice & Broadband Customers]) AS [Wholesale - Copper Voice & Broadband Customers]
      ,SUM(LOB.[Wholesale - Copper Broadband & Video Customers]) AS [Wholesale - Copper Broadband & Video Customers]
      ,SUM(LOB.[Wholesale - Copper Voice & Video]) AS [Wholesale - Copper Voice & Video]
      ,SUM(LOB.[Wholesale - Copper Broadband & Voice & Video]) AS [Wholesale - Copper Broadband & Voice & Video]
      ,SUM(LOB.[Wholesale - Copper No Core Products Customers]) AS [Wholesale - Copper No Core Products Customers]
      ,SUM(LOB.[Wholesale - Circuits]) AS [Wholesale - Circuits]
from WCF.TBL_REV_BY_LOB_AND_PRODUCT LOB

group by wirecenter) LOB
ON DSAT.wireCenterClli = LOB.Wirecenter

GROUP BY DSAT.wireCenterClli
	  ,DSAT.STATE
      ,LABOR.[Copper troubles]
      ,LABOR.[Fiber troubles]
      ,LABOR.[Copper new adds]
      ,LABOR.[Fiber new adds]
      ,LABOR.[Cost per fiber trouble]
      ,LABOR.[Cost per copper trouble ticket]
      ,LABOR.[Cost per copper new add]
      ,LABOR.[Cost per fiber new add]
      ,LABOR.[Copper Trouble OOP Labor]
      ,LABOR.[Fiber trouble OOP Labor]
      ,LABOR.[Fiber new add labor]
      ,LABOR.[Copper new add OOP labor]
      ,LABOR.[Copper Labor]
      ,LABOR.[Fiber Labor]
      ,TSO.[TSO Calls]
      ,TSO.[Cost per call]
      ,TSO.[TSO Costs]
	  ,NETWORK.[Network Operations]
      ,NETWORK.[Network Distribution]
      ,NETWORK.[Assignment]
      ,NETWORK.[Network Core]
      ,NETWORK.[Circuits COGS]
      ,NETWORK.[Network Ops Support]
      ,NETWORK.[Voice COGS]
      ,NETWORK.[SS7 Circuit]
      ,NETWORK.[Cable Locates]
      ,NETWORK.[Plant Maintenance]
      ,NETWORK.[Poles]
      ,NETWORK.[Jointly Owned Poles]
      ,NETWORK.[Plant Maintenance and Constructions]
      ,NETWORK.[Network Access]
      ,NETWORK.[Total]
	  ,SEG.[ABU > 81% of Customers]
      ,SEG.[ABU 61-80% of Customers]
      ,SEG.[ABU 41-60% of Customers]
      ,SEG.[ABU 21-40% of Customers]
      ,SEG.[ABU 1-20% of Customers]
      ,SEG.[ABU 0% of Customers]
      ,SEG.[BEAD > 81% of Customers]
      ,SEG.[BEAD 61-80% of Customers]
      ,SEG.[BEAD 41-60% of Customers]
      ,SEG.[BEAD 21-40% of Customers]
      ,SEG.[BEAD 1-20% of Customers]
      ,SEG.[BEAD 0% of Customers]
      ,SEG.[Hyperion]
      ,SEG.[Regulatory Guidance - Green]
      ,SEG.[Regulatory Guidance - Yellow]
      ,SEG.[Regulatory Guidance - Red]
      ,SEG.[Tarriff Restrictions - Green]
      ,SEG.[Tarriff Restrictions - Yellow]
      ,SEG.[Tarriff Restrictions - Red]