DROP TABLE ATTMR
/

CREATE TABLE ATTMR NOLOGGING NOCACHE AS
SELECT DISTINCT TICKET_ID, STATE, CLEC_ID, COMPANY, CKT_ID, PRODUCT, PROD2, BDW, CREATE_DATE,
       CASE WHEN CLEARED_DT IS NULL THEN CLOSED_DT ELSE CLEARED_DT END CLEARED_DT, 
       CASE WHEN CLOSED_DT IS NULL THEN CLEARED_DT ELSE CLOSED_DT END CLOSED_DT, 
       CASE WHEN DISP = 'NTF' THEN 0 ELSE TTR END TTR,   
       REPAIR_CODE, DISP,
	   CASE WHEN CAUSE_CD = 'Fiber/Cable - Cut' THEN 'Y' 
            WHEN FAULT = '11' THEN 'Y'
            WHEN PLANT IN ('0312','0344') THEN 'Y'
            ELSE 'N' END CABLE_CUT, 
       CASE WHEN DISP IN ('CO','FAC') THEN 'Y' ELSE 'N' END FOUND, CAUSE_CD, 
       TROUBLE_DESC, TO_CHAR(CLOSED_DT,'MM') MON
FROM (
SELECT TICKET_ID, STATE, CLEC_ID, CL.CUSTOMER, CKT_ID, PRODUCT,
       CASE WHEN PRODUCT IN ('DS1') AND COMPANY = 'ATX' THEN 'ABS DS1'
            WHEN PRODUCT IN ('DS3') AND COMPANY = 'ATX' THEN 'ABS DS3'
            WHEN PRODUCT IN ('OCN') AND COMPANY = 'ATX' THEN 'ABS OCN'
            WHEN PRODUCT IN ('Ethernet') AND COMPANY = 'ATX' THEN 'ABS Ethernet'       
            WHEN PRODUCT IN ('DS1','DS3','OCN') AND COMPANY = 'MOB' THEN 'Exclude'  
            WHEN PRODUCT = 'Ethernet' AND COMPANY = 'MOB' AND BDW = '1G' THEN 'MOB 1G' 
            WHEN PRODUCT = 'Ethernet' AND COMPANY = 'MOB' AND BDW = '10G' THEN 'MOB 10G'
            ELSE NULL END PROD2, 
       CREATE_DATE, CLEARED_DT, CLOSED_DT, TTR,  
       TOTAL_DURATION, TRBL_FOUND_CD, TRBL_FOUND_DESC, DISP,
	   SITE_ID, REPAIR_CODE, SERVICE_TYPE_CODE,
			CAUSE_CD, COMPANY, BDW, FAULT, PLANT, TROUBLE_DESC
FROM (
SELECT DISTINCT TICKET_ID, STATE, CLEC_ID, CKT_ID, PRODUCT, 
       CASE WHEN CLEC_ID IN ('ATX','AAV','SBB','SBZ','SUV','TPM','LOA','AVA','AYA') THEN 'ATX' ELSE 'MOB' END COMPANY,
       CASE WHEN PRODUCT = 'Ethernet' AND SERVICE_TYPE_CODE IN ('KF','KR') THEN '1G'
            WHEN PRODUCT = 'Ethernet' AND SERVICE_TYPE_CODE IN ('KG','KS') THEN '10G'
            WHEN PRODUCT = 'Ethernet' AND SERVICE_TYPE_CODE IN ('KE','KQ') THEN '1G'   --100M, BUT COUNTED AS 1G  
            WHEN PRODUCT = 'Ethernet' AND SERVICE_TYPE_CODE IN ('KD','KP') THEN '1G'   --10M, BUT COUNTED AS 1G  
            WHEN PRODUCT = 'Ethernet' AND SERVICE_TYPE_CODE IN ('VL') THEN 'EVC' 
            WHEN PRODUCT IN ('DS1','DS3','OCN') THEN NULL
            ELSE 'Check' END BDW,    
       CREATE_DATE, CLEARED_DT, CLOSED_DT, TTR, TOTAL_DURATION, 
	   CASE WHEN TRBL_FOUND_NUMBER IS NOT NULL THEN TRBL_FOUND_NUMBER
	        ELSE TRBL_FOUND_NUMBER2 END TRBL_FOUND_CD,
	   CASE WHEN TRBL_FOUND_DESC IS NOT NULL THEN TRBL_FOUND_DESC
	        ELSE TRBL_FOUND_DESC2 END TRBL_FOUND_DESC,		
	   CASE WHEN DISP3 IS NOT NULL THEN DISP3
	        WHEN DISP IS NOT NULL THEN DISP
	        ELSE DISP2 END DISP, SITE_ID,
       REPAIR_CODE, SERVICE_TYPE_CODE, CAUSE_CD, FAULT, PLANT, TROUBLE_DESC
FROM (
SELECT DISTINCT TICKET_ID, 
       CASE WHEN SITE_STATE IS NOT NULL AND SITE_ID <> 'NON INVENTORIED CIRCUIT'  
	         AND SITE_STATE IN ('OR','WA','ID','MT') THEN SITE_STATE
            WHEN PRILOC IS NOT NULL 
			 AND PRILOC IN ('OR','WA','ID','MT') THEN PRILOC
            ELSE NULL END STATE,
       CASE WHEN ACNA IS NOT NULL THEN ACNA
            WHEN CCNA1 IS NOT NULL THEN CCNA1
            WHEN CCNA2 IS NOT NULL THEN CCNA2
	        ELSE ACNA3 END CLEC_ID, 		
       CKT_ID,  
	   CASE WHEN SERVICE_TYPE_CODE = 'HC' THEN 'DS1'
			WHEN SERVICE_TYPE_CODE = 'HF' THEN 'DS3'
            WHEN SUBSTR(SERVICE_TYPE_CODE,1,1) IN ('K','V') THEN 'Ethernet'
            WHEN SERVICE_TYPE_CODE IN ('OB','OD','OF','OG') THEN 'OCN'
            WHEN SUBSTR(SERVICE_TYPE_CODE,1,1) IN ('X','L') THEN 'DS0'
	   	 	WHEN SUBSTR(CIRCUIT,4,5) LIKE '%T1%' THEN 'DS1'
			WHEN SUBSTR(CIRCUIT,4,5) LIKE '%T3%' THEN 'DS3'
			WHEN SUBSTR(CIRCUIT,1,4) LIKE '%HC%' THEN 'DS1'
			WHEN SUBSTR(CIRCUIT,1,4) LIKE '%HF%' THEN 'DS3'
			WHEN SUBSTR(CIRCUIT,3,1) IN ('X','L') THEN 'DS0'
			WHEN SUBSTR(CIRCUIT,1,10) LIKE '%OC3%' THEN 'OCN'
            WHEN SUBSTR(CIRCUIT,1,10) LIKE '%OC03%' THEN 'OCN'
            WHEN SUBSTR(CIRCUIT,1,10) LIKE '%OC12%' THEN 'OCN'
            WHEN SUBSTR(CIRCUIT,1,10) LIKE '%OC48%' THEN 'OCN'
            WHEN SUBSTR(CIRCUIT,1,10) LIKE '%OC192%' THEN 'OCN'
			WHEN SUBSTR(CIRCUIT,3,2) IN ('OB','OD','OF','OG') THEN 'OCN'
			WHEN SUBSTR(CIRCUIT,3,1) IN ('K','V') THEN 'Ethernet'
			WHEN RATE_CODE IN ('OC3','OC12','OC48','OC192') THEN 'OCN'
			ELSE ' ' END PRODUCT,
	   CREATE_DATE, 
	   CASE WHEN CLEARED_DT IS NOT NULL THEN CLEARED_DT
            ELSE CLOSED_DT END CLEARED_DT, 
	   CASE WHEN CLOSED_DT IS NOT NULL THEN CLOSED_DT
            ELSE CLEARED_DT END CLOSED_DT,
       TOTAL_DURATION, 
	   TTR,
	   B.TRBL_FOUND_NUMBER, B.TRBL_FOUND_DESC, B.DISP, C.TRBL_FOUND_NUMBER TRBL_FOUND_NUMBER2, C.TRBL_FOUND_DESC TRBL_FOUND_DESC2, C.DISP DISP2, D.DISP DISP3,
	   SITE_ID, A.REPAIR_CODE, SERVICE_TYPE_CODE, CAUSE_CD, FAULT, PLANT, TROUBLE_DESC
FROM (
SELECT A.FLD_REQUESTID TICKET_ID, 
       MAX(SUBSTR(A.FLD_SITEID,5,2)) KEEP (DENSE_RANK LAST ORDER BY A.FLD_MODIFIEDDATE) SITE_STATE, 
	   MAX(UPPER(D.EC_COMPANY_CODE)) KEEP (DENSE_RANK LAST ORDER BY D.LAST_MODIFIED_DATE) ICSC, 
       MAX(SUBSTR(D.PRIMARY_LOCATION,5,2)) KEEP (DENSE_RANK LAST ORDER BY D.LAST_MODIFIED_DATE) PRILOC, 
	   MAX(A.FLD_SITEID) KEEP (DENSE_RANK LAST ORDER BY A.FLD_MODIFIEDDATE) SITE_ID,
	   A.EXCHANGE_CARRIER_CIRCUIT_ID CKT_ID, 
	   REPLACE(REPLACE(A.EXCHANGE_CARRIER_CIRCUIT_ID,' '),'/') CIRCUIT,
	   MAX(A.ACNA) KEEP (DENSE_RANK LAST ORDER BY A.FLD_MODIFIEDDATE) ACNA, 
	   MAX(D.CCNA) KEEP (DENSE_RANK LAST ORDER BY D.LAST_MODIFIED_DATE) CCNA1, 
	   MAX(D.CCNA) KEEP (DENSE_RANK FIRST ORDER BY D.CCNA) CCNA2,
       MAX(TRIM(D2.CLEC_ID)) KEEP (DENSE_RANK FIRST ORDER BY D2.LAST_MODIFIED_DATE) ACNA3,
	   MAX(A.FLD_REQUESTTYPE) KEEP (DENSE_RANK LAST ORDER BY A.FLD_MODIFIEDDATE) REQUEST_TYPE, 
	   MAX(A.FLD_STARTDATE) KEEP (DENSE_RANK LAST ORDER BY A.FLD_MODIFIEDDATE) CREATE_DATE,
	   MAX(A.FLD_EVENT_END_TIME) KEEP (DENSE_RANK LAST ORDER BY A.FLD_MODIFIEDDATE) CLEARED_DT, 
       MAX(A.DTE_CLOSEDDATETIME) KEEP (DENSE_RANK LAST ORDER BY A.FLD_MODIFIEDDATE) CLOSED_DT,
	   MAX(ROUND(A.FLD_MTTREPAIR/3600,2)) KEEP (DENSE_RANK LAST ORDER BY A.FLD_MODIFIEDDATE) TTR,
	   MAX(ROUND(A.H_FLD_TOTALOPENTIME_SECS_/3600,2)) KEEP (DENSE_RANK LAST ORDER BY A.FLD_MODIFIEDDATE) TOTAL_DURATION,
	   MAX(FLD_COMPLETE_REPAIRCODE) KEEP (DENSE_RANK LAST ORDER BY A.FLD_MODIFIEDDATE) REPAIR_CODE,
	   MAX(FLD_TROUBLEFOUNDINT) KEEP (DENSE_RANK LAST ORDER BY A.FLD_MODIFIEDDATE) TRBL_FOUND_CD,
       MAX(FLD_COMPLETE_CAUSECODE) KEEP (DENSE_RANK LAST ORDER BY A.FLD_MODIFIEDDATE) CAUSE_CD,
       MAX(E.TYPE) KEEP (DENSE_RANK LAST ORDER BY E.LAST_MODIFIED_DATE) TYPE,
	   MAX(E.SERVICE_TYPE_CODE) KEEP (DENSE_RANK LAST ORDER BY E.LAST_MODIFIED_DATE) SERVICE_TYPE_CODE, 
	   MAX(E.RATE_CODE) KEEP (DENSE_RANK LAST ORDER BY E.LAST_MODIFIED_DATE) RATE_CODE,
	   MAX(A.FLD_REQUESTSTATUS) KEEP (DENSE_RANK LAST ORDER BY A.FLD_MODIFIEDDATE) REQSTAT,
       MAX(WO.FLD_REQUESTID) KEEP (DENSE_RANK FIRST ORDER BY WO.FLD_AUDITMODIFIEDDATE) WO_ID,
       MAX(VNET.FAULT_FAULT) KEEP (DENSE_RANK FIRST ORDER BY VNET.DW_LOAD_DATE_TIME) FAULT,
       MAX(VNET.FAULT_PLANT_ITEM) KEEP (DENSE_RANK FIRST ORDER BY VNET.DW_LOAD_DATE_TIME) PLANT,
       REPLACE(REPLACE(A.FLD_DESCRIPTIONOFSYMPTON,CHR(10),''),CHR(13),'') TROUBLE_DESC
FROM CASDW.TROUBLE_TICKET_R A,  
     CASDW.WORK_ORDER_R WO,
     CASDW.DESIGN_LAYOUT_REPORT D,
     RVV827.DESIGN_LAYOUT_REPORT_TEMP D2,
     CASDW.CIRCUIT E,
     CASDW.VNET_DAILY VNET
WHERE A.FLD_TROUBLEREPORTSTATE = 'closed'
 AND A.FLD_ASSIGNMENTPROFILE IN ('CNOC')
 AND A.FLD_REQUESTID = WO.FLD_TICKETID (+)
 AND A.EXCHANGE_CARRIER_CIRCUIT_ID = D.ECCKT(+)
 AND A.EXCHANGE_CARRIER_CIRCUIT_ID = D2.ECCKT(+)
 AND A.EXCHANGE_CARRIER_CIRCUIT_ID = E.EXCHANGE_CARRIER_CIRCUIT_ID(+)
 AND SUBSTR(WO.FLD_REQUESTID,9,7) = SUBSTR(VNET.HOST_ID (+),10,7)
 AND (E.TYPE <> 'T' OR TYPE IS NULL) 
 AND (TO_CHAR(DTE_CLOSEDDATETIME,'yyyymm') IN ('202006','202007')    --NEED TO CHANGE THIS EACH MONTH TO INCLUDE BOTH CURRENT AND PREVIOUS MONTHS 
    OR (DTE_CLOSEDDATETIME IS NULL AND TO_CHAR(FLD_EVENT_END_TIME,'yyyymm') IN ('202006','202007')))   --NEED TO CHANGE THIS EACH MONTH TO INCLUDE BOTH CURRENT AND PREVIOUS MONTHS 
 AND E.STATUS (+) not in ('8','A')
 AND (A.ACNA IN ('ATX','AAV','SBB','SBZ','SUV','TPM','AAX','ACF','ACH','ADM','AEC','AGS','AGZ','AHA','AHD','AHM','AHO',
	   		    'AIL','AIN','AIS','AKZ','ALY','AMH','AMP','AWL','AWN','AZE','BAC','BAK','BAO','BCU','BFL','BGH','BPN',
				'BSM','CBL','CCB','CDA','CEO','CEU','CFN','CIV','CIW','CKQ','CLQ','COW','CQW','CRF','CRJ','CSG','CSO',
			    'CSU','CSX','CTJ','CUO','CUY','CZB','DNC','ETP','EST','ETX','FLA','FSC','FSI','FSV','GEE','GLV','GSL',
				'HGN','HLU','HNC','HTN','IMP','IND','ISZ','IUW','JCT','LAA','LAC','LBH','LNZ','LSZ','MBN','MBQ','MCA',
			    'MCC','MCE','MCQ','MCV','MCW','MCZ','MFN','MIB','MIR','MLA','MLZ','MMV','MOB','MOE','MTX','MUI','MWB',
				'MWZ','NBC','NWW','OAK','OCL','ORV','OSU','OCK','PFM','PIG','RAD','RMC','RMF','RRC','SBG','SBM','SBN',
				'SCU','SHI','SLL','SMC','SNP','STH','SUF','SWM','SWP','SWT','SWV','SYC','SZM','TGH','TQU','UMT','VGD',
				'VRA','WBT','WGL','WLG','WLZ','WVO','WWC','NHO','LOA','AVA','AYA')
 OR D.CCNA IN ('ATX','AAV','SBB','SBZ','SUV','TPM','AAX','ACF','ACH','ADM','AEC','AGS','AGZ','AHA','AHD','AHM','AHO',
	   		    'AIL','AIN','AIS','AKZ','ALY','AMH','AMP','AWL','AWN','AZE','BAC','BAK','BAO','BCU','BFL','BGH','BPN',
				'BSM','CBL','CCB','CDA','CEO','CEU','CFN','CIV','CIW','CKQ','CLQ','COW','CQW','CRF','CRJ','CSG','CSO',
			    'CSU','CSX','CTJ','CUO','CUY','CZB','DNC','ETP','EST','ETX','FLA','FSC','FSI','FSV','GEE','GLV','GSL',
				'HGN','HLU','HNC','HTN','IMP','IND','ISZ','IUW','JCT','LAA','LAC','LBH','LNZ','LSZ','MBN','MBQ','MCA',
			    'MCC','MCE','MCQ','MCV','MCW','MCZ','MFN','MIB','MIR','MLA','MLZ','MMV','MOB','MOE','MTX','MUI','MWB',
				'MWZ','NBC','NWW','OAK','OCL','ORV','OSU','OCK','PFM','PIG','RAD','RMC','RMF','RRC','SBG','SBM','SBN',
				'SCU','SHI','SLL','SMC','SNP','STH','SUF','SWM','SWP','SWT','SWV','SYC','SZM','TGH','TQU','UMT','VGD',
				'VRA','WBT','WGL','WLG','WLZ','WVO','WWC','NHO','LOA','AVA','AYA'))
GROUP BY A.FLD_REQUESTID, A.EXCHANGE_CARRIER_CIRCUIT_ID, A.FLD_DESCRIPTIONOFSYMPTON
) A, RVV827.TRBL_FOUND_REMEDY B, RVV827.REPAIR_CODE C, RVV827.TRBL_FOUND_REMEDY D
WHERE A.TRBL_FOUND_CD = B.TRBL_FOUND_NUMBER (+)
AND A.REPAIR_CODE = C.REPAIR_CODE (+)
AND A.REPAIR_CODE = D.TRBL_FOUND_DESC (+) 
AND SUBSTR(CIRCUIT,6,1) <> 'U'   
AND REQUEST_TYPE IN ('Agent','Alarm','Customer','Maintenance')
AND SUBSTR(CKT_ID,4,2) NOT IN ('VM','EM','IP','IB','FX','YB','YG','UG','UH','RT','PL','LA','LU','XA','LA','LO','LN','LU','FD','US','CS')   
AND REQSTAT = 'Closed' 
)			  	 
)DATA, RVV827.CARRIER_LIST CL
WHERE CLEC_ID = CL.ACNA(+)
AND PRODUCT IN ('DS1','DS3','OCN','Ethernet')
)	
WHERE STATE IN ('WA','OR','ID','MT')
AND PROD2 IN ('ABS DS1','ABS DS3','ABS OCN','ABS Ethernet','MOB 1G','MOB 10G')				 
ORDER BY 4,3,1;





--MTTR    
SELECT * FROM ATTMR
WHERE MON = '07'   --NEED TO CHANGE THIS EACH MONTH TO SHOW CURRENT MONTH 
AND DISP IN ('CO','FAC','CC','NTF')
;


DROP TABLE ATTREPEAT
/

CREATE TABLE ATTREPEAT NOLOGGING NOCACHE AS
SELECT * 
FROM ATTMR
WHERE MON = '07'   --NEED TO CHANGE THIS EACH MONTH TO SHOW CURRENT MONTH 
AND DISP IN ('CO','FAC','NTF','CC');


--PULLS THE SUMMARY RFR TO PUT ON THE RFR TAB   
SELECT COMPANY, PRODUCT, BDW, COUNT(*) CNT
FROM (
SELECT TICKET_ID, STATE, CLEC_ID, COMPANY, PRODUCT, BDW,
       CKT_ID, CREATE_DATE, CLEARED_DT, CLOSED_DT, DISP, PREV_TICKET_ID, PREV_CREATE_DT, PREV_CLEAR_DT,
       PREV_DISP, ROUND(CREATE_DATE-PREV_CLEAR_DT,0) DAYS, TO_CHAR(CLOSED_DT,'MM') MON 
FROM (
SELECT R.TICKET_ID, R.STATE, R.CLEC_ID, R.COMPANY, 
       R.PRODUCT, R.CKT_ID, R.CREATE_DATE, R.CLEARED_DT, R.CLOSED_DT, R.DISP, R.BDW,
       MAX(T.TICKET_ID) PREV_TICKET_ID, 
       MAX(T.CREATE_DATE) PREV_CREATE_DT, 
       MAX(T.CLEARED_DT) PREV_CLEAR_DT,
       MAX(T.DISP) PREV_DISP 
FROM ATTREPEAT R, ATTMR T 
WHERE R.CKT_ID = T.CKT_ID
AND R.CREATE_DATE > T.CLEARED_DT
AND R.TICKET_ID <> T.TICKET_ID
AND T.DISP IN ('CO','FAC','NTF','CC')
GROUP BY R.TICKET_ID, R.STATE, R.CLEC_ID, R.COMPANY, 
         R.PRODUCT, R.CKT_ID, R.CREATE_DATE, R.CLEARED_DT, R.CLOSED_DT, R.DISP, R.BDW
)
WHERE CREATE_DATE-PREV_CLEAR_DT <=30
)
GROUP BY COMPANY, PRODUCT, BDW
ORDER BY 1,2,3,4;






--PULLS THE DETAIL FOR THE REPEAT AND THE ASSOCIATED TROUBLES  
DROP TABLE ATTRPT
/
;

CREATE TABLE ATTRPT NOLOGGING NOCACHE AS
SELECT CKT_ID, TICKET_ID, ROUND(CREATE_DATE-PREV_CLEAR_DT,0) DAYS, 1 RPT 
FROM (
SELECT R.TICKET_ID, R.STATE, R.CLEC_ID, R.COMPANY, 
       R.PRODUCT, R.CKT_ID, R.CREATE_DATE, R.CLEARED_DT, R.CLOSED_DT, R.DISP, 
       MAX(T.TICKET_ID) PREV_TICKET_ID, 
       MAX(T.CREATE_DATE) PREV_CREATE_DT, 
       MAX(T.CLEARED_DT) PREV_CLEAR_DT,
       MAX(T.DISP) PREV_DISP 
FROM ATTREPEAT R, ATTMR T 
WHERE R.CKT_ID = T.CKT_ID
AND R.CREATE_DATE > T.CLEARED_DT
AND R.TICKET_ID <> T.TICKET_ID
AND T.DISP IN ('CO','FAC','NTF','CC')
GROUP BY R.TICKET_ID, R.STATE, R.CLEC_ID, R.COMPANY, 
         R.PRODUCT, R.CKT_ID, R.CREATE_DATE, R.CLEARED_DT, R.CLOSED_DT, R.DISP
)
WHERE CREATE_DATE-PREV_CLEAR_DT <=30
;



SELECT STATE, COMPANY, PRODUCT, T2.CKT_ID, T2.TICKET_ID, DISP, FOUND, CREATE_DATE, CLEARED_DT, CLOSED_DT, DAYS, RPT  
FROM ATTMR T2, ATTRPT R2
WHERE T2.TICKET_ID = R2.TICKET_ID (+) 
AND T2.CKT_ID IN (SELECT CKT_ID FROM ATTRPT)
AND DISP IN ('CO','FAC','NTF','CC')
ORDER BY 4,8;


