--FOR NCFR DETAIL - NUMERATOR   

SELECT DOCUMENT_NUMBER, PON, ACT_IND, COMP_DT, DD_TASK_COMP, NPANXX, ICSC, ACNA, CUSTOMER,
 STATE, PRODUCT, CKT, 
 MIN(TICKET_ID) TICKET_ID, 
 MIN(ASSIGNMENTPROFILE) KEEP (DENSE_RANK FIRST ORDER BY TICKET_ID) ASSIGNMENTPROFILE,
 MIN(REPAIR_CODE) KEEP (DENSE_RANK FIRST ORDER BY TICKET_ID) REPAIR_CODE, 
 MIN(DISP) KEEP (DENSE_RANK FIRST ORDER BY TICKET_ID) DISP,
 MIN(TRBL_CREATE_DATE) KEEP (DENSE_RANK FIRST ORDER BY TICKET_ID) TRBL_CREATE_DATE,
 MIN(TRBL_CLEARED_DT) KEEP (DENSE_RANK FIRST ORDER BY TICKET_ID) TRBL_CLEARED_DT,
 MIN(TRBL_CLOSED_DT) KEEP (DENSE_RANK FIRST ORDER BY TICKET_ID) TRBL_CLOSED_DT,
 CASE WHEN MON = 12 THEN 1 ELSE MON+1 END MON                                               --USE PLUS 1 TO ACCOMODATE THE SPREADSHEET WITH THIS ONE MONTH IN ARREARS              
 FROM (
    SELECT DISTINCT DOCUMENT_NUMBER, PON, ACT_IND, COMP_DT, DD_TASK_COMP, NPANXX, ICSC, ACNA, CUSTOMER,
    STATE, PRODUCT, CKT, TICKET_ID, ASSIGNMENTPROFILE, REPAIR_CODE, TFR.DISP, TO_CHAR(DD_TASK_COMP,'MM') MON,  
    TRBL_CREATE_DATE, TRBL_CLEARED_DT, 
    CASE WHEN CLOSED_DT IS NOT NULL THEN CLOSED_DT
         ELSE TRBL_CLEARED_DT END TRBL_CLOSED_DT
    FROM (
        SELECT DISTINCT DOCUMENT_NUMBER, PON, ACT_IND, COMP_DT, DD_TASK_COMP, NPANXX, ICSC, A.ACNA, CUSTOMER,
        STATE, PRODUCT, CKT,
        TT.FLD_REQUESTID TICKET_ID,
        MAX(TT.FLD_COMPLETE_REPAIRCODE) KEEP (DENSE_RANK LAST ORDER BY TT.FLD_MODIFIEDDATE) REPAIR_CODE,
        MAX(TRIM(TT.FLD_ASSIGNMENTPROFILE)) KEEP (DENSE_RANK FIRST ORDER BY TT.FLD_MODIFIEDDATE) ASSIGNMENTPROFILE, 
        MAX(TT.FLD_REQUESTSTATUS) KEEP (DENSE_RANK LAST ORDER BY TT.FLD_MODIFIEDDATE) REQSTAT,
        MAX(TT.FLD_REQUESTTYPE) KEEP (DENSE_RANK LAST ORDER BY TT.FLD_MODIFIEDDATE) REQUEST_TYPE,
        MAX(TT.FLD_STARTDATE) KEEP (DENSE_RANK LAST ORDER BY TT.FLD_MODIFIEDDATE) TRBL_CREATE_DATE,
        MAX(TT.FLD_EVENT_END_TIME) KEEP (DENSE_RANK LAST ORDER BY TT.FLD_MODIFIEDDATE) TRBL_CLEARED_DT, 
        MAX(TT.DTE_CLOSEDDATETIME) KEEP (DENSE_RANK LAST ORDER BY TT.FLD_MODIFIEDDATE) CLOSED_DT,
        MAX(TT.FLD_MODIFIEDDATE) MOD_DATE
        FROM ( 
            SELECT DOCUMENT_NUMBER, PON, ACT_IND, DREC, DD, DDD, COMP_DT, DD_TASK_COMP, 
            NCFR.NPANXX, ICSC, NCFR.ACNA, CUSTOMER, CKT, STATE,
            CASE WHEN PRODUCT = 'DS1' AND SUBSTR(PON,3,1) = 'S' AND SUBSTR(PON,4,1) = '0' THEN 'ATX DS1'
            WHEN ACNA = 'TPM' AND PRODUCT = 'DS1' AND SUBSTR(PON,4,1) IN ('P','Y') THEN 'ATX DS1'
            WHEN ACNA IN ('SBB','SBZ','AAV','SUV') AND PRODUCT = 'DS1' THEN 'ATX DS1'
            WHEN PRODUCT = 'DS1' AND SUBSTR(PON,3,1) = 'S' AND SUBSTR(PON,4,1) = 'X' THEN 'ATX ESO DS1'
            WHEN PRODUCT = 'DS3' AND SUBSTR(PON,3,1) = 'S' AND SUBSTR(PON,4,1) = '0' THEN 'ATX DS3'
            WHEN ACNA = 'TPM' AND PRODUCT = 'DS3' AND SUBSTR(PON,4,1) IN ('P','Y') THEN 'ATX DS3'
            WHEN ACNA IN ('SBB','SBZ','AAV','SUV') AND PRODUCT = 'DS3' THEN 'ATX DS3'
            WHEN PRODUCT = 'DS3' AND SUBSTR(PON,3,1) = 'S' AND SUBSTR(PON,4,1) = 'X' THEN 'ATX ESO DS3'
            WHEN PRODUCT LIKE 'OC%' AND SUBSTR(PON,3,1) = 'S' AND SUBSTR(PON,4,1) = '0' THEN 'ATX'||' '||PRODUCT
            WHEN PRODUCT LIKE 'OC%' AND SUBSTR(PON,3,1) = 'S' AND SUBSTR(PON,4,1) = 'X' THEN 'ATX ESO'||' '||PRODUCT
            WHEN PRODUCT ='DS0' AND SUBSTR(PON,3,1) = 'S' AND SUBSTR(PON,4,1) = 'X' THEN 'ATX ESO DS0' 
            WHEN PRODUCT = 'ETHERNET-UNI' AND REQ_TYPE = 'E' AND SEI = 'Y' THEN 'ATX Ethernet'
            WHEN PRODUCT = 'ETHERNET-UNI' AND REQ_TYPE = 'S' AND SEI = 'Y' THEN 'EXCLUDE'
            WHEN PRODUCT = 'ETHERNET-UNI' AND REQ_TYPE = 'S' AND SEI IS NULL THEN 'ATX Ethernet'    
            WHEN PRODUCT = 'ETHERNET-UNI' AND SUBSTR(PON,4,1) = 'C' THEN 'ATX Ethernet' 
            ELSE 'EXCLUDE' END PRODUCT
            FROM NCFRORDERS NCFR 
            WHERE ACT_IND = 'N'
            AND TO_CHAR(DD_TASK_COMP,'YYYYMM') = '202009' --ONE MONTH IN ARREARS FROM REPORTING MONTH - MAKE SURE TO CHANGE EVERY MONTH   
            AND NCFR.STATE IN ('WA','OR','ID','MT') 
            AND ACNA IN ('ATX','AAV','SBB','SBZ','SUV','TPM','LOA','AVA','AYA')
        )A, CASDW.TROUBLE_TICKET_R TT
     WHERE A.CKT = TT.EXCHANGE_CARRIER_CIRCUIT_ID
     AND TT.FLD_TROUBLEREPORTSTATE = 'closed'
     AND TT.FLD_ASSIGNMENTPROFILE IN ('CNOC','Commercial-CTF')
     AND TO_CHAR(FLD_STARTDATE,'yyyymm') IN ('202009','202010')  --MUST CHANGE THESE DATES EACH MONTH TO SHOW PREVIOUS AND CURRENT MONTH  
     AND TO_CHAR(TT.FLD_STARTDATE,'YYYYMMDD') >= TO_CHAR(A.COMP_DT,'YYYYMMDD') 
     GROUP BY DOCUMENT_NUMBER, PON, ACT_IND, COMP_DT, DD_TASK_COMP, NPANXX, ICSC, A.ACNA, CUSTOMER, 
              STATE, PRODUCT, CKT, TT.FLD_REQUESTID
   )B, RVV827.TRBL_FOUND_REMEDY TFR           
   WHERE B.REPAIR_CODE = TFR.TRBL_FOUND_DESC (+)  
   AND REQUEST_TYPE IN ('Agent','Alarm','Customer','Maintenance')
   AND TFR.DISP IN ('CO','FAC')           
)
WHERE TRBL_CREATE_DATE - COMP_DT <31
AND TO_CHAR(TRBL_CREATE_DATE,'YYYYMMDD') >= TO_CHAR(COMP_DT,'YYYYMMDD')
GROUP BY DOCUMENT_NUMBER, PON, ACT_IND, COMP_DT, DD_TASK_COMP, NPANXX, ICSC, ACNA, CUSTOMER, 
         STATE, PRODUCT, CKT, MON
ORDER BY 11;
         
    
 
 
--FOR NCFR DENOMINATOR  
          
SELECT *
FROM (           
            SELECT DISTINCT DOCUMENT_NUMBER,    
            TO_CHAR(DD_TASK_COMP,'mm') MON,
            TO_CHAR(DD_TASK_COMP,'yyyymm') DD_TASK,
            CASE WHEN PRODUCT = 'DS1' AND SUBSTR(PON,3,1) = 'S' AND SUBSTR(PON,4,1) = '0' THEN 'ATX DS1'
            WHEN ACNA = 'TPM' AND PRODUCT = 'DS1' AND SUBSTR(PON,4,1) IN ('P','Y') THEN 'ATX DS1'
            WHEN ACNA IN ('SBB','SBZ','AAV','SUV') AND PRODUCT = 'DS1' THEN 'ATX DS1'
            WHEN PRODUCT = 'DS1' AND SUBSTR(PON,3,1) = 'S' AND SUBSTR(PON,4,1) = 'X' THEN 'ATX ESO DS1'
            WHEN PRODUCT = 'DS3' AND SUBSTR(PON,3,1) = 'S' AND SUBSTR(PON,4,1) = '0' THEN 'ATX DS3'
            WHEN ACNA = 'TPM' AND PRODUCT = 'DS3' AND SUBSTR(PON,4,1) IN ('P','Y') THEN 'ATX DS3'
            WHEN ACNA IN ('SBB','SBZ','AAV','SUV') AND PRODUCT = 'DS3' THEN 'ATX DS3'
            WHEN PRODUCT = 'DS3' AND SUBSTR(PON,3,1) = 'S' AND SUBSTR(PON,4,1) = 'X' THEN 'ATX ESO DS3'
            WHEN PRODUCT LIKE 'OC%' AND SUBSTR(PON,3,1) = 'S' AND SUBSTR(PON,4,1) = '0' THEN 'ATX'||' '||PRODUCT
            WHEN PRODUCT LIKE 'OC%' AND SUBSTR(PON,3,1) = 'S' AND SUBSTR(PON,4,1) = 'X' THEN 'ATX ESO'||' '||PRODUCT
            WHEN PRODUCT ='DS0' AND SUBSTR(PON,3,1) = 'S' AND SUBSTR(PON,4,1) = 'X' THEN 'ATX ESO DS0' 
            WHEN PRODUCT = 'ETHERNET-UNI' AND REQ_TYPE = 'E' AND SEI = 'Y' THEN 'ATX Ethernet'
            WHEN PRODUCT = 'ETHERNET-UNI' AND REQ_TYPE = 'S' AND SEI = 'Y' THEN 'EXCLUDE'  -- ETHERNET POP TO SWITCH  
            WHEN PRODUCT = 'ETHERNET-UNI' AND REQ_TYPE = 'S' AND SEI IS NULL THEN 'ATX Ethernet'    
            WHEN PRODUCT = 'ETHERNET-UNI' AND SUBSTR(PON,4,1) = 'C' THEN 'ATX Ethernet' 
            ELSE 'EXCLUDE' END PRODUCT
            FROM NCFRORDERS NCFR 
            WHERE ACNA IN ('ATX','AAV','SBB','SBZ','SUV','TPM','LOA','AVA','AYA')
            AND ACT_IND = 'N'
  ) WHERE DD_TASK = '202009'                     --CHANGE THIS EACH MONTH  - SHOULD SHOW PREVIOUS REPORTING MONTH
    AND (PRODUCT NOT LIKE '%ESO%'
     AND PRODUCT <> 'EXCLUDE')     
; 
  
  
