
CREATE PROCEDURE LZ.usp_TBL_LZ_HBE_ROADMAP_UPLOAD as

truncate table LZ.TBL_LZ_HBE_ROADMAP_UPLOAD --Cannot truncate system versioned table

insert INTO LZ.TBL_LZ_HBE_ROADMAP_UPLOAD 
SELECT * 
FROM OPENROWSET('Microsoft.ACE.OLEDB.12.0', 
   'Excel 12.0;Database=D:\LZ\HBE_ROADMAP\UPLOAD.XLSX;HDR=YES', 
   'SELECT * FROM [Sheet1$]')

INSERT INTO dbo.TBL_HBE_ROADMAP 
SELECT A.*
,GETDATE() AS INSERT_TS

FROM LZ.TBL_LZ_HBE_ROADMAP_UPLOAD A