commit;

drop table carrier_list;

create table carrier_list
(
acna   		 	 VARCHAR2(255 BYTE),
customer 		 VARCHAR2(255 BYTE),
cust_descr   	 VARCHAR2(255 BYTE),
type		 	 VARCHAR2(255 BYTE)
);


update carrier_list
set customer = 'COMCAST'
where acna = 'MYX'
;





INSERT ALL
into carrier_list values ('UEE','UNIVERSAL TELECOM','UNDEFINED ACNAS','LL')
into carrier_list values ('UEL','VERIZON BUSINESSMCI','VERIZON BUSINESS-MCI','LL')
into carrier_list values ('UEM','UNITED TELECOM ','UNDEFINED ACNAS','LL')
into carrier_list values ('UEX','BENDTEL','UNDEFINED ACNAS','LL')
into carrier_list values ('UFB','US FIBERCOM NETWORK','UNDEFINED ACNAS','LL')
into carrier_list values ('UHC','PAETEC COMMUNICATIONS','PAETEC COMMUNICATIONS','LL')
into carrier_list values ('UHD','U.S. TELEFONE','UNDEFINED ACNAS','LL')
into carrier_list values ('UID','LIGHTYEAR COMMUNICATIONS','UNDEFINED ACNAS','LL')
into carrier_list values ('UIO','UNICOM COMMUNICATIONS','UNDEFINED ACNAS','LL')
into carrier_list values ('UJB','URJET BACKBONE NETWORK','UNDEFINED ACNAS','LL')
into carrier_list values ('ULA','DAYSTAR COMMUNICATIONS','UNDEFINED ACNAS','LL')
into carrier_list values ('ULD','US BILLING','UNDEFINED ACNAS','LL')
into carrier_list values ('ULG','SPRINT','SPRINT','LL')
into carrier_list values ('ULL','UTELCALL','OTHER WIRELESS','WL')
into carrier_list values ('ULM','ATHENA INTERNATIONAL LLC','UNDEFINED ACNAS','LL')
into carrier_list values ('ULN','VERIZON WIRELESS','VERIZON WIRELESS','WL')
into carrier_list values ('ULT','ULTRATELCOM INC','OTHER WIRELESS','WL')
into carrier_list values ('UMB','ARCH WIRELESS','ARCH WIRELESS','WL')
into carrier_list values ('UMC','CUMMINGS TELECOMMUNICATION SERVICES ','UNDEFINED ACNAS','LL')
into carrier_list values ('UMG','URBAN MEDIA LONG DISTANCE','UNDEFINED ACNAS','LL')
into carrier_list values ('UML','ARCH WIRELESS','ARCH WIRELESS','WL')
into carrier_list values ('UMN','UNITED MOBILE NETWORK','OTHER WIRELESS','WL')
into carrier_list values ('UMT','ATT MOBILITY','ATT MOBILITY','WL')
into carrier_list values ('UMW','TSUNAMI NETWORKS','UNDEFINED ACNAS','LL')
into carrier_list values ('UNC','UNIVERSITY COMMUNICATIONS','UNDEFINED ACNAS','LL')
into carrier_list values ('UNE','UNITEL','UNDEFINED ACNAS','LL')
into carrier_list values ('UNF','VERIZON BUSINESSMCI','VERIZON BUSINESS-MCI','LL')
into carrier_list values ('UNI','UNITEL','UNDEFINED ACNAS','LL')
into carrier_list values ('UNK','US ADVANCED NETWORK INC','UNDEFINED ACNAS','LL')
into carrier_list values ('UNL','LEVEL 3','LEVEL 3','LL')
into carrier_list values ('UNM','UNION COMMUNICATIONS','OTHER WIRELESS','WL')
into carrier_list values ('UNS','UNITED NETWORK','UNDEFINED ACNAS','LL')
into carrier_list values ('UNT','UNITEL','UNDEFINED ACNAS','LL')
into carrier_list values ('UNU','UNIVERSAL TELECOM ','UNDEFINED ACNAS','LL')
into carrier_list values ('UNV','VERIZON WIRELESS','VERIZON WIRELESS','WL')
into carrier_list values ('UNY','RCC WIRELESS','RCC WIRELESS','WL')
into carrier_list values ('UNZ','UNI COMMUNICATIONS INC','OTHER WIRELESS','WL')
into carrier_list values ('UOI','USCOM TELEPHONE ','UNDEFINED ACNAS','LL')
into carrier_list values ('UOM','US ONE COMMUNICATIONS','UNDEFINED ACNAS','LL')
into carrier_list values ('UOP','UNIVERSITY OF PITTSBURGH','UNDEFINED ACNAS','LL')
into carrier_list values ('UPG','USA PAGING','OTHER WIRELESS','WL')
into carrier_list values ('UPS','UPSTATE PAGING','OTHER WIRELESS','WL')
into carrier_list values ('URC','EXCEL TELECOMMUNICATIONS','EXCEL TELECOMMUNICATIONS','LL')
into carrier_list values ('URT','UNITED RADIOTELEPHONE','OTHER WIRELESS','WL')
into carrier_list values ('USA','UNITED SERVICES ADMINISTRATION','UNDEFINED ACNAS','LL')
into carrier_list values ('USB','U S BANCORP','UNDEFINED ACNAS','LL')
into carrier_list values ('USC','US CELLULAR','US CELLULAR','WL')
into carrier_list values ('USD','US DIAL','UNDEFINED ACNAS','LL')
into carrier_list values ('USE','US ELECTRODYNAMICS INC','UNDEFINED ACNAS','LL')
into carrier_list values ('USG','USA LONG DISTANCE','UNDEFINED ACNAS','LL')
into carrier_list values ('USH','XO COMMUNICATIONS','XO COMMUNICATIONS','LL')
into carrier_list values ('USI','CIERA NETWORK SYSTEMS','UNDEFINED ACNAS','LL')
into carrier_list values ('USJ','US CONNECT CORP','UNDEFINED ACNAS','LL')
into carrier_list values ('USL','USLINK LONG DISTANCE','UNDEFINED ACNAS','LL')
into carrier_list values ('USM','ARCH WIRELESS','ARCH WIRELESS','WL')
into carrier_list values ('USP','SPRINT','SPRINT','LL')
into carrier_list values ('USQ','US TELECOMM INC','UNDEFINED ACNAS','LL')
into carrier_list values ('USS','USASATCO CO','UNDEFINED ACNAS','LL')
into carrier_list values ('UST','VERIZON BUSINESSMCI','VERIZON BUSINESS-MCI','LL')
into carrier_list values ('USW','QWEST','QWEST','LL')
into carrier_list values ('USX','USTEL/ARCADA','UNDEFINED ACNAS','LL')
into carrier_list values ('USY','EXCEL TELECOMMUNICATIONS','EXCEL TELECOMMUNICATIONS','LL')
into carrier_list values ('UTC','SPRINT','SPRINT','LL')
into carrier_list values ('UTE','UTE COMMUNICATIONS','OTHER WIRELESS','WL')
into carrier_list values ('UTI','VERIZON WIRELESS','VERIZON WIRELESS','WL')
into carrier_list values ('UTK','USN COMMUNICATIONS','UNDEFINED ACNAS','LL')
into carrier_list values ('UTL','SPRINT','SPRINT','LL')
into carrier_list values ('UTQ','1ST UNITED TELCOM','UNDEFINED ACNAS','LL')
into carrier_list values ('UTR','CELLULAR ONE','OTHER WIRELESS','WL')
into carrier_list values ('UTS','VERIZON WIRELESS','VERIZON WIRELESS','WL')
into carrier_list values ('UTV','UNIVERSITY TELEPHONE SERVICES','UNDEFINED ACNAS','LL')
into carrier_list values ('UTX','UTC LONG DISTANCE','UNDEFINED ACNAS','LL')
into carrier_list values ('UUN','VERIZON BUSINESSMCI','VERIZON BUSINESS-MCI','LL')
into carrier_list values ('UVA','UNIVERSAL ACCESS','UNDEFINED ACNAS','LL')
into carrier_list values ('UVC','UV CORP','OTHER WIRELESS','WL')
into carrier_list values ('UVN','UNIVERSALCOM INC','UNDEFINED ACNAS','LL')
into carrier_list values ('UVR','VERIZON BUSINESSMCI','VERIZON BUSINESS-MCI','LL')
into carrier_list values ('UWB','QWEST','QWEST','LL')
into carrier_list values ('UWC','QWEST','QWEST','LL')
into carrier_list values ('UWI','QWEST','QWEST','LL')
into carrier_list values ('UWP','ARCH WIRELESS','ARCH WIRELESS','WL')
into carrier_list values ('UWT','CAPSULE COMMUNICATIONS','UNDEFINED ACNAS','LL')
into carrier_list values ('UWW','U S WEST WIRELESS','OTHER WIRELESS','WL')
into carrier_list values ('UXC','OMNIPLEX COMMUNICATIONS GROUP','UNDEFINED ACNAS','LL')
into carrier_list values ('UXT','US IN TOUCH','UNDEFINED ACNAS','LL')
into carrier_list values ('UXW','ONE COMMUNICATIONS','ONE COMMUNICATIONS','LL')
into carrier_list values ('UYA','UNITED SYSTEMS ACCESS TELECOM','UNDEFINED ACNAS','LL')
into carrier_list values ('UYM','UNITYCOMM','UNDEFINED ACNAS','LL')
into carrier_list values ('UYT','UTILITY TELEPHONE ','UNDEFINED ACNAS','LL')
into carrier_list values ('VAC','VALUE ADDED COMMUNICATIONS','OTHER WIRELESS','WL')
into carrier_list values ('VAD','VERIZON','VERIZON','LL')
into carrier_list values ('VAF','AMERICAN FIBER NETWORK OF VIRGINIA ','UNDEFINED ACNAS','LL')
into carrier_list values ('VAR','VALSTAR INC','UNDEFINED ACNAS','LL')
into carrier_list values ('VAS','VALLEY ANSWERING SERVICE','OTHER WIRELESS','WL')
into carrier_list values ('VAT','VIATEL','UNDEFINED ACNAS','LL')
into carrier_list values ('VAU','WINDSTREAM SOUTHWEST LONG DISTANCE','UNDEFINED ACNAS','LL')
into carrier_list values ('VBT','VBI 2000 LLC','UNDEFINED ACNAS','LL')
into carrier_list values ('VCC','VOICE TELECOMM','UNDEFINED ACNAS','LL')
into carrier_list values ('VCF','VOLO COMMUNICATIONS','UNDEFINED ACNAS','LL')
into carrier_list values ('VCI','VINCENT COMMUNICATIONS','UNDEFINED ACNAS','LL')
into carrier_list values ('VCM','VALCOM INC','OTHER WIRELESS','WL')
into carrier_list values ('VCS','DEDICATED COMMUNICATIONS CORP','UNDEFINED ACNAS','LL')
into carrier_list values ('VCT','VICKI COWAN DBA TELAVOICE','OTHER WIRELESS','WL')
into carrier_list values ('VCV','VERNON COMMUNICATION','UNDEFINED ACNAS','LL')
into carrier_list values ('VCY','VCI COMPANY','UNDEFINED ACNAS','LL')
into carrier_list values ('VDC','NATIONWIDE LONG DISTANCE','UNDEFINED ACNAS','LL')
into carrier_list values ('VDG','VERIZON','VERIZON','LL')
into carrier_list values ('VDI','CLEVELAND COMMUNICATIONS PAGING','OTHER WIRELESS','WL')
into carrier_list values ('VDT','WORLDXCHANGE CORP','UNDEFINED ACNAS','LL')
into carrier_list values ('VDV','VONAGE','UNDEFINED ACNAS','LL')
into carrier_list values ('VEN','VERIZON','VERIZON','LL')
into carrier_list values ('VER','VERIO INC','UNDEFINED ACNAS','LL')
into carrier_list values ('VES','VERIZON BUSINESSGNI','VERIZON BUSINESS-GNI','LL')
into carrier_list values ('VEY','VALLEY TELECOMMUNICATIONS CO','OTHER WIRELESS','WL')
into carrier_list values ('VGD','ATT MOBILITY','ATT MOBILITY','WL')
into carrier_list values ('VGL','V3 GLOBAL ','UNDEFINED ACNAS','LL')
into carrier_list values ('VGM','VERIZON BUSINESSMCI','VERIZON BUSINESS-MCI','LL')
into carrier_list values ('VGS','VERIZON BUSINESSGNI','VERIZON BUSINESS-GNI','LL')
into carrier_list values ('VHC','VIRTUAL HIPSTER CORPORATION','UNDEFINED ACNAS','LL')
into carrier_list values ('VIA','VITAL COMMUNICATION','OTHER WIRELESS','WL')
into carrier_list values ('VIC','VICOM INC','UNDEFINED ACNAS','LL')
into carrier_list values ('VIM','SAVVIS ','UNDEFINED ACNAS','LL')
into carrier_list values ('VIN','VERIZON BUSINESSMCI','VERIZON BUSINESS-MCI','LL')
into carrier_list values ('VIP','VALLEY INSTANT PAGE','OTHER WIRELESS','WL')
into carrier_list values ('VIS','VITTS CORPORATION','UNDEFINED ACNAS','LL')
into carrier_list values ('VIX','VIXXI SOLUTIONS INC','UNDEFINED ACNAS','LL')
into carrier_list values ('VLA','VALUE LINE','UNDEFINED ACNAS','LL')
into carrier_list values ('VLB','VALUE LINE','OTHER WIRELESS','WL')
into carrier_list values ('VLD','VERA LONG DISTANCE','UNDEFINED ACNAS','LL')
into carrier_list values ('VLE','VALLEY COMMUNICATIONS','OTHER WIRELESS','WL')
into carrier_list values ('VLH','VALTECH COMMUNICATIONS ','UNDEFINED ACNAS','LL')
into carrier_list values ('VLK','BIRCH TELECOM','UNDEFINED ACNAS','LL')
into carrier_list values ('VLL','VALUE LINE','UNDEFINED ACNAS','LL')
into carrier_list values ('VLR','CAVALIER TELEPHONE','UNDEFINED ACNAS','LL')
into carrier_list values ('VLW','IONEX TELECOMMUNICATIONS','UNDEFINED ACNAS','LL')
into carrier_list values ('VLX','VALUELINX COMMUNICATIONS CORPORATION','OTHER WIRELESS','WL')
into carrier_list values ('VLY','VALLEY PAGING','OTHER WIRELESS','WL')
into carrier_list values ('VMC','VALLEY MOBILE COMMUNICATIONS INC','OTHER WIRELESS','WL')
into carrier_list values ('VMS','SBC TELECOMOTHER','UNDEFINED ACNAS','LL')
into carrier_list values ('VMT','VINELAND MOBILE TELCO','OTHER WIRELESS','WL')
into carrier_list values ('VNC','VENTURE COMMUNICATIONS CORP','UNDEFINED ACNAS','LL')
into carrier_list values ('VNE','VIRGINIA NETWORK INCORPORATED','UNDEFINED ACNAS','LL')
into carrier_list values ('VNH','TIME WARNER CABLE','UNDEFINED ACNAS','LL')
into carrier_list values ('VNL','LEVEL 3','LEVEL 3','LL')
into carrier_list values ('VNR','VNUS NETWORK ','UNDEFINED ACNAS','LL')
into carrier_list values ('VNS','QWEST','QWEST','LL')
into carrier_list values ('VOA','TCA LONG DISTANCE','UNDEFINED ACNAS','LL')
into carrier_list values ('VOC','VOICE TEL','OTHER WIRELESS','WL')
into carrier_list values ('VOL','VALUE LINE','UNDEFINED ACNAS','LL')
into carrier_list values ('VOU','VELOCITY.NET COMMUNICATIONS, INC.','UNDEFINED ACNAS','LL')
into carrier_list values ('VOY','GLOBAL CROSSING','GLOBAL CROSSING','LL')
into carrier_list values ('VPC','VIP CONNECTIONS','UNDEFINED ACNAS','LL')
into carrier_list values ('VPG','VALLEY PAGING','OTHER WIRELESS','WL')
into carrier_list values ('VPM','VPS COMMUNICATIONS','UNDEFINED ACNAS','LL')
into carrier_list values ('VPP','VIP ENTERPRISES INC','OTHER WIRELESS','WL')
into carrier_list values ('VRA','ATT MOBILITY','ATT MOBILITY','WL')
into carrier_list values ('VRN','VERNON TELEPHONE COMPANY','UNDEFINED ACNAS','LL')
into carrier_list values ('VRO','VERIZON','VERIZON','LL')
into carrier_list values ('VRT','EXCEL TELECOMMUNICATIONS','EXCEL TELECOMMUNICATIONS','LL')
into carrier_list values ('VRZ','VERIZON WIRELESS','VERIZON WIRELESS','WL')
into carrier_list values ('VSJ','COMMUNIGROUP INC','UNDEFINED ACNAS','LL')
into carrier_list values ('VSP','VISTA PCS','OTHER WIRELESS','WL')
into carrier_list values ('VST','VALLEY STAR TEL','UNDEFINED ACNAS','LL')
into carrier_list values ('VTA','VINCENNES TELEPHONE ANSWERING SERVICE','OTHER WIRELESS','WL')
into carrier_list values ('VTD','GRANDE RIVER COMMUNICATIONS','UNDEFINED ACNAS','LL')
into carrier_list values ('VTI','VT OF LONG ISLAND ','UNDEFINED ACNAS','LL')
into carrier_list values ('VTR','VICTORIA CELLULAR CORP','OTHER WIRELESS','WL')
into carrier_list values ('VTS','VENTURES IN PAGING','OTHER WIRELESS','WL')
into carrier_list values ('VTT','VASTTEL COMMUNICATIONS INC','UNDEFINED ACNAS','LL')
into carrier_list values ('VTY','VERMONT TELEPHONE COMPANY','UNDEFINED ACNAS','LL')
into carrier_list values ('VTZ','VEROXITY TECHNOLOGY PARTNERS','UNDEFINED ACNAS','LL')
into carrier_list values ('VUN','VECTRIS TELECOM','UNDEFINED ACNAS','LL')
into carrier_list values ('VUS','VERIZON BUSINESSMCI','VERIZON BUSINESS-MCI','LL')
into carrier_list values ('VVS','SAVVIS ','UNDEFINED ACNAS','LL')
into carrier_list values ('VWF','VALUE LINE','UNDEFINED ACNAS','LL')
into carrier_list values ('VYN','VALLEYNET','UNDEFINED ACNAS','LL')
into carrier_list values ('VZN','VERIZON','VERIZON','LL')
into carrier_list values ('WAC','WACO COMMUNICATIONS INC','OTHER WIRELESS','WL')
into carrier_list values ('WAD','WADENA LONG DISTANCE','OTHER WIRELESS','WL')
into carrier_list values ('WAL','WEST ALABAMA COMMUNICATIONS','OTHER WIRELESS','WL')
into carrier_list values ('WAN','WIRELESS ALLIANCE','OTHER WIRELESS','WL')
into carrier_list values ('WAU','WTI ADVANTAGE PRODUCTS ','UNDEFINED ACNAS','LL')
into carrier_list values ('WBC','WALLER BROADCASTING','OTHER WIRELESS','WL')
into carrier_list values ('WBG','TRENTON TELEPHONE','UNDEFINED ACNAS','LL')
into carrier_list values ('WBI','SBC TELECOMOTHER','UNDEFINED ACNAS','LL')
into carrier_list values ('WBS','WEBSTER RADIO','OTHER WIRELESS','WL')
into carrier_list values ('WBT','ATT MOBILITY','ATT MOBILITY','WL')
into carrier_list values ('WBY','SNET','SNET','LL')
into carrier_list values ('WCA','LEVEL 3','LEVEL 3','LL')
into carrier_list values ('WCC','WEST COAST COMMUNICATIONS INC','UNDEFINED ACNAS','LL')
into carrier_list values ('WCF','WHOLESALE CARRIER SERVICES','UNDEFINED ACNAS','LL')
into carrier_list values ('WCG','TMOBILE','T-MOBILE','WL')
into carrier_list values ('WCJ','WASHINGTON COUNTY JOINT VENTURE','OTHER WIRELESS','WL')
into carrier_list values ('WCL','WEST CENTRAL CELLULAR','OTHER WIRELESS','WL')
into carrier_list values ('WCM','W C COMMUNICATIONS','OTHER WIRELESS','WL')
into carrier_list values ('WCN','WEST CENTRAL CELLULAR','OTHER WIRELESS','WL')
into carrier_list values ('WCO','WESTCOM','UNDEFINED ACNAS','LL')
into carrier_list values ('WCP','WEST CENTRAL PAGERS','OTHER WIRELESS','WL')
into carrier_list values ('WCR','WORCESTER COMMUNICATIONS','UNDEFINED ACNAS','LL')
into carrier_list values ('WCT','US CELLULAR','US CELLULAR','WL')
into carrier_list values ('WCU','GLOBAL CROSSING','GLOBAL CROSSING','LL')
into carrier_list values ('WCV','WITTENBERG CABLE TV COMPANY INC','UNDEFINED ACNAS','LL')
into carrier_list values ('WCX','ATT MOBILITY','ATT MOBILITY','WL')
into carrier_list values ('WCY','CENTRAL WISCONSIN COMMUNICATIONS','UNDEFINED ACNAS','LL')
into carrier_list values ('WDC','VERIZON BUSINESSMCI','VERIZON BUSINESS-MCI','LL')
into carrier_list values ('WDM','VERIZON BUSINESSMCI','VERIZON BUSINESS-MCI','LL')
into carrier_list values ('WEC','WEST FLORIDA COMMUNICATION','UNDEFINED ACNAS','LL')
into carrier_list values ('WEL','SPRINT PCS','SPRINT PCS','WL')
into carrier_list values ('WES','WESTEL','UNDEFINED ACNAS','LL')
into carrier_list values ('WET','WESTERN TELECOMMUNICATIONS','OTHER WIRELESS','WL')
into carrier_list values ('WEU','WE CONNECT COMMUNICATIONS','UNDEFINED ACNAS','LL')
into carrier_list values ('WFA','WELLS FARGO ALARM SERVICES ','UNDEFINED ACNAS','LL')
into carrier_list values ('WFB','WELLS FARGO BANK','UNDEFINED ACNAS','LL')
into carrier_list values ('WFC','WICHITA FALLS CELLULAR TELEPHONE CO','OTHER WIRELESS','WL')
into carrier_list values ('WGK','WGK RADIO','OTHER WIRELESS','WL')
into carrier_list values ('WGL','ATT MOBILITY','ATT MOBILITY','WL')
into carrier_list values ('WGO','WCTA LONG DISTANCE ','UNDEFINED ACNAS','LL')
into carrier_list values ('WGP','WEST GEORGIA PAGING','OTHER WIRELESS','WL')
into carrier_list values ('WGR','WIREGRASS TELCOM ','UNDEFINED ACNAS','LL')
into carrier_list values ('WGT','WESTGATE COMMUNICATIONS','UNDEFINED ACNAS','LL')
into carrier_list values ('WHA','WHOLESALE AIRTIME','UNDEFINED ACNAS','LL')
into carrier_list values ('WHC','WICHITA CHEAP TALK','UNDEFINED ACNAS','LL')
into carrier_list values ('WHG','WINSTARGVC','WINSTAR-GVC','LL')
into carrier_list values ('WHI','WABASH INDEPENDENT NETWORKS ','UNDEFINED ACNAS','LL')
into carrier_list values ('WHL','WHEELER COMMUNICATIONS','OTHER WIRELESS','WL')
into carrier_list values ('WHM','WHATCOM TELECOMM','UNDEFINED ACNAS','LL')
into carrier_list values ('WHS','WHISLER COMMUNICATIONS','OTHER WIRELESS','WL')
into carrier_list values ('WIL','WILEY COMMUNICATIONS INC','UNDEFINED ACNAS','LL')
into carrier_list values ('WIN','RSL COM USA','RSL COM USA','LL')
into carrier_list values ('WIP','WINSOME PAGING','OTHER WIRELESS','WL')
into carrier_list values ('WIR','WIRELESS TWO ','OTHER WIRELESS','WL')
into carrier_list values ('WIS','WESTERN TELECOMMUNICATIONS','UNDEFINED ACNAS','LL')
into carrier_list values ('WIX','WPTI TELECOM ','UNDEFINED ACNAS','LL')
into carrier_list values ('WIY','WINN TELECOM','UNDEFINED ACNAS','LL')
into carrier_list values ('WIZ','LEVEL 3','LEVEL 3','LL')
into carrier_list values ('WJG','WJG TELEPHONE CO','OTHER WIRELESS','WL')
into carrier_list values ('WKC','SE INDIANA CELLULAR TELCO','OTHER WIRELESS','WL')
into carrier_list values ('WKT','WEST KENTUCKY TWOWAY RADIO INC','OTHER WIRELESS','WL')
into carrier_list values ('WLA','WESTERN LONG DISTANCE','UNDEFINED ACNAS','LL')
into carrier_list values ('WLE','WORLDNET COMMUNICATIONS','UNDEFINED ACNAS','LL')
into carrier_list values ('WLG','ATT MOBILITY','ATT MOBILITY','WL')
into carrier_list values ('WLH','NORTHSTAR','OTHER WIRELESS','WL')
into carrier_list values ('WLK','WLKI FM 100','OTHER WIRELESS','WL')
into carrier_list values ('WLM','WHOLESALE TELECOM CORPORATION','UNDEFINED ACNAS','LL')
into carrier_list values ('WLO','WEST CAROLINA COMMUNICATIONS LLC','UNDEFINED ACNAS','LL')
into carrier_list values ('WLT','LEVEL 3','LEVEL 3','LL')
into carrier_list values ('WLZ','ATT MOBILITY','ATT MOBILITY','WL')
into carrier_list values ('WMA','ANEW TELECOMMUNICATIONS','UNDEFINED ACNAS','LL')
into carrier_list values ('WMC','WILLIAMS METRO COMMUNICATIONS','OTHER WIRELESS','WL')
into carrier_list values ('WMF','WESTCHESTER MOBILE FONE SYSTEMS INC','OTHER WIRELESS','WL')
into carrier_list values ('WMG','WILMINGTON CELLULAR TELEPHONE CO','OTHER WIRELESS','WL')
into carrier_list values ('WMM','WEST MOUNTAIN MOBILE','OTHER WIRELESS','WL')
into carrier_list values ('WMP','WARK MOBILE PHONE AND PAGE','OTHER WIRELESS','WL')
into carrier_list values ('WMT','WILLIAMSPORT MOBILE TELE CO','OTHER WIRELESS','WL')
into carrier_list values ('WMU','WABASH MUTUAL TELEPHONE','UNDEFINED ACNAS','LL')
into carrier_list values ('WNA','WIN NET TELECOMMUNICATIONS ','UNDEFINED ACNAS','LL')
into carrier_list values ('WNC','WESTERN COMMUNICATIONS','OTHER WIRELESS','WL')
into carrier_list values ('WNH','WALNUT HILL CELLULAR INC','OTHER WIRELESS','WL')
into carrier_list values ('WNI','NEW EDGE NETWORK','UNDEFINED ACNAS','LL')
into carrier_list values ('WNK','WISCONSIN INDEPENDENT NETWORK','UNDEFINED ACNAS','LL')
into carrier_list values ('WNL','WANTEL INC','UNDEFINED ACNAS','LL')
into carrier_list values ('WNO','WINCO ','UNDEFINED ACNAS','LL')
into carrier_list values ('WNR','WINSTARGVC','WINSTAR-GVC','LL')
into carrier_list values ('WNT','WATS NETWORK OF TEXAS','UNDEFINED ACNAS','LL')
into carrier_list values ('WNW','WESTEL','UNDEFINED ACNAS','LL')
into carrier_list values ('WOL','WORLD COMMUNICATIONS INC','UNDEFINED ACNAS','LL')
into carrier_list values ('WON','WIRELESS ONE NETWORK','OTHER WIRELESS','WL')
into carrier_list values ('WOR','WORTHEIM','UNDEFINED ACNAS','LL')
into carrier_list values ('WOW','SPRINT PCS','SPRINT PCS','WL')
into carrier_list values ('WPH','WESTPHALIA BROADBAND','UNDEFINED ACNAS','LL')
into carrier_list values ('WPI','WIRELESS PLUS','OTHER WIRELESS','WL')
into carrier_list values ('WPM','WYOMING PINE MTN COMMUNICATIONS','OTHER WIRELESS','WL')
into carrier_list values ('WPT','WESTERN PACIFIC TELECOM INC','UNDEFINED ACNAS','LL')
into carrier_list values ('WRC','WESTERN RADIO COMMUNICATIONS','OTHER WIRELESS','WL')
into carrier_list values ('WRF','CELLCOM','OTHER WIRELESS','WL')
into carrier_list values ('WRG','WR GRACE AND COMPANY','UNDEFINED ACNAS','LL')
into carrier_list values ('WRI','WORLDLINK SOLUTIONS ','OTHER WIRELESS','WL')
into carrier_list values ('WRK','WORKING ASSETS','UNDEFINED ACNAS','LL')
into carrier_list values ('WRN','CELLCOM','OTHER WIRELESS','WL')
into carrier_list values ('WRO','CELLCOM','OTHER WIRELESS','WL')
into carrier_list values ('WRP','WESTCOL','OTHER WIRELESS','WL')
into carrier_list values ('WRS','WESTERN RADIO SERVICES CO INC','OTHER WIRELESS','WL')
into carrier_list values ('WRT','CELLCOM','OTHER WIRELESS','WL')
into carrier_list values ('WSB','WYMOBIG SKY BEEPER','OTHER WIRELESS','WL')
into carrier_list values ('WSC','WITHERS COMMUNICATIONS','OTHER WIRELESS','WL')
into carrier_list values ('WSG','WORLD SAVINGS AND LOAN','UNDEFINED ACNAS','LL')
into carrier_list values ('WSH','WIRLESS SYSTEMS TECHNOLOGY','OTHER WIRELESS','WL')
into carrier_list values ('WSJ','WINDSTREAM COMMUNICATIONS','UNDEFINED ACNAS','LL')
into carrier_list values ('WSL','WESTCOL','OTHER WIRELESS','WL')
into carrier_list values ('WSM','WESTCOM','UNDEFINED ACNAS','LL')
into carrier_list values ('WSN','BROADWING','BROADWING','LL')
into carrier_list values ('WSO','SPRINT PCS','SPRINT PCS','WL')
into carrier_list values ('WSQ','WINSTARGVC','WINSTAR-GVC','LL')
into carrier_list values ('WSS','CELLCOM','OTHER WIRELESS','WL')
into carrier_list values ('WST','WESTERN TELENET','UNDEFINED ACNAS','LL')
into carrier_list values ('WSU','WILSON COMMUNICATION COMPANY ','UNDEFINED ACNAS','LL')
into carrier_list values ('WSV','WORLAND SERVICES','OTHER WIRELESS','WL')
into carrier_list values ('WSX','CELLCOM','OTHER WIRELESS','WL')
into carrier_list values ('WTC','WESTERN TELECOMMUNICATIONS','UNDEFINED ACNAS','LL')
into carrier_list values ('WTG','RSL COM USA','RSL COM USA','LL')
into carrier_list values ('WTK','WESTERN TELECOM INC','UNDEFINED ACNAS','LL')
into carrier_list values ('WTL','VERIZON BUSINESSMCI','VERIZON BUSINESS-MCI','LL')
into carrier_list values ('WTM','WEST TEXAS MICROWAVE','UNDEFINED ACNAS','LL')
into carrier_list values ('WTP','WESTERN TELEPAGE','OTHER WIRELESS','WL')
into carrier_list values ('WTR','CELLCOM','OTHER WIRELESS','WL')
into carrier_list values ('WTS','WESTERN TELEPHONE SERVICE INC','UNDEFINED ACNAS','LL')
into carrier_list values ('WTT','WASHINGTON TELEPHONE CO','OTHER WIRELESS','WL')
into carrier_list values ('WTV','WESTERN TELEPHONE AND TELEVISION','UNDEFINED ACNAS','LL')
into carrier_list values ('WTX','WESTEX CELLULAR','OTHER WIRELESS','WL')
into carrier_list values ('WTZ','WATS/800 INCORPORATED','UNDEFINED ACNAS','LL')
into carrier_list values ('WUA','VERIZON BUSINESSMCI','VERIZON BUSINESS-MCI','LL')
into carrier_list values ('WUI','VERIZON BUSINESSMCI','VERIZON BUSINESS-MCI','LL')
into carrier_list values ('WUS','360NETWORKS','UNDEFINED ACNAS','LL')
into carrier_list values ('WUT','ATT COMMUNICATIONSOTHER','ATT COMMUNICATIONS-OTHER','LL')
into carrier_list values ('WVA','TWIN VALLEY TELEPHONE','UNDEFINED ACNAS','LL')
into carrier_list values ('WVC','WEST VIRGINIA CELLTELL CO','OTHER WIRELESS','WL')
into carrier_list values ('WVD','WEST RIVER LONG DISTANCE','UNDEFINED ACNAS','LL')
into carrier_list values ('WVI','WIDE VOICE, LLC','UNDEFINED ACNAS','LL')
into carrier_list values ('WVL','WARWICK VALLEY LONG DISTANCE','UNDEFINED ACNAS','LL')
into carrier_list values ('WVM','WAVECOMM','UNDEFINED ACNAS','LL')
into carrier_list values ('WVO','ATT MOBILITY','ATT MOBILITY','WL')
into carrier_list values ('WVP','WEST VIRGINIA PCS ALLIANCE','UNDEFINED ACNAS','LL')
into carrier_list values ('WVR','WIRELESS VENTURES','OTHER WIRELESS','WL')
into carrier_list values ('WVS','WAVESENT','OTHER WIRELESS','WL')
into carrier_list values ('WWC','ATT MOBILITY','ATT MOBILITY','WL')
into carrier_list values ('WWE','WORLD WIDE DEVELOPMENT ','UNDEFINED ACNAS','LL')
into carrier_list values ('WWS','CELLCOM','OTHER WIRELESS','WL')
into carrier_list values ('WWV','WINDWAVE COMMUNICATIONS','UNDEFINED ACNAS','LL')
into carrier_list values ('WXC','WILCOX COMMUNICATIONS','OTHER WIRELESS','WL')
into carrier_list values ('WXL','WORLDXCHANGE CORP','UNDEFINED ACNAS','LL')
into carrier_list values ('WYM','WYOMING MOBILEPHONE','OTHER WIRELESS','WL')
into carrier_list values ('WYN','WAYNE PAGING','OTHER WIRELESS','WL')
into carrier_list values ('WZT','WIZTRONICS','OTHER WIRELESS','WL')
into carrier_list values ('XAT','XATEL','UNDEFINED ACNAS','LL')
into carrier_list values ('XBC','CBX ONESTOP ','UNDEFINED ACNAS','LL')
into carrier_list values ('XCA','CAPITOL INFRASTRUCTURE','UNDEFINED ACNAS','LL')
into carrier_list values ('XCC','CCG COMMUNICATIONS','UNDEFINED ACNAS','LL')
into carrier_list values ('XCH','XCHANGE TELECOM CORP','UNDEFINED ACNAS','LL')
into carrier_list values ('XCL','XCELL CELLULAR INC','OTHER WIRELESS','WL')
into carrier_list values ('XCT','XCOM TECHNOLOGIES','UNDEFINED ACNAS','LL')
into carrier_list values ('XCW','CRICKET COMMUNICATIONS','CRICKET COMMUNICATIONS','WL')
into carrier_list values ('XIC','XIT COMMUNICATIONS','UNDEFINED ACNAS','LL')
into carrier_list values ('XIT','XIT TELECOM AND TECHNOLOGY','OTHER WIRELESS','WL')
into carrier_list values ('XMC','TW TELECOM','TW TELECOM','LL')
into carrier_list values ('XMI','NATIONSLINE','UNDEFINED ACNAS','LL')
into carrier_list values ('XPM','XPM INC','OTHER WIRELESS','WL')
into carrier_list values ('XPS','XPEDITE SYSTEMS ','UNDEFINED ACNAS','LL')
into carrier_list values ('XRX','XEROX CORP','UNDEFINED ACNAS','LL')
into carrier_list values ('XTI','AX TELECOMMUNICATIONS ORPORATED','UNDEFINED ACNAS','LL')
into carrier_list values ('XTL','XTEL COMMUNICATIONS','UNDEFINED ACNAS','LL')
into carrier_list values ('XTN','FREEDOM COMM USA','UNDEFINED ACNAS','LL')
into carrier_list values ('XTR','XTRACOM INC','UNDEFINED ACNAS','LL')
into carrier_list values ('XTS','TEXAS 10, LLC','UNDEFINED ACNAS','LL')
into carrier_list values ('XWL','CRICKET COMMUNICATIONS','CRICKET COMMUNICATIONS','WL')
into carrier_list values ('XXX','BROADVIEW NETWORKS','BROADVIEW NETWORKS','LL')
into carrier_list values ('XYZ','INTERNATIONAL MARKETING AND ADVERTISING','UNDEFINED ACNAS','LL')
into carrier_list values ('XZP','ZERO PLUS','UNDEFINED ACNAS','LL')
into carrier_list values ('YAC','YAZOO ANSWER CALL','OTHER WIRELESS','WL')
into carrier_list values ('YBG','ATT MOBILITY','ATT MOBILITY','WL')
into carrier_list values ('YCA','BRIGHTHOUSE NETWORKS','UNDEFINED ACNAS','LL')
into carrier_list values ('YCC','YAKIMA COUNTY COMMUNICATIONS','OTHER WIRELESS','WL')
into carrier_list values ('YCN','POCKET COMMUNICATIONS INC','UNDEFINED ACNAS','LL')
into carrier_list values ('YDE','NATIONSLINE DELAWARE','UNDEFINED ACNAS','LL')
into carrier_list values ('YEL','YUMA ELECTRONICS INC','OTHER WIRELESS','WL')
into carrier_list values ('YMI','BRIGHTHOUSE NETWORKS','UNDEFINED ACNAS','LL')
into carrier_list values ('YMN','GLOBAL TELECOM SOLUTIONS','UNDEFINED ACNAS','LL')
into carrier_list values ('YMX','YMAX COMMUNICATIONS','UNDEFINED ACNAS','LL')
into carrier_list values ('YNC','NATIONSLINE','UNDEFINED ACNAS','LL')
into carrier_list values ('YNK','YANKEE MICROWAVE INC','OTHER WIRELESS','WL')
into carrier_list values ('YNY','CITYNET','UNDEFINED ACNAS','LL')
into carrier_list values ('YOH','CINERGY COMMUNICATIONS','UNDEFINED ACNAS','LL')
into carrier_list values ('YOR','YORKVILLE TELEPHONE COOPERATIVE','UNDEFINED ACNAS','LL')
into carrier_list values ('YOY','CYPRESS COMMUNICATIONS OPERATING COMPANY','UNDEFINED ACNAS','LL')
into carrier_list values ('YPA','CITYNET PENNSYLVANIA','UNDEFINED ACNAS','LL')
into carrier_list values ('YPC','YELLOW PAGER COMMUNICATIONS SYSTEMS','OTHER WIRELESS','WL')
into carrier_list values ('YPS','YIPES ENTERPRISE SERVICES','UNDEFINED ACNAS','LL')
into carrier_list values ('YRT','YUMA RADIO TELEPHONE SVC','OTHER WIRELESS','WL')
into carrier_list values ('YRW','SYRINGA NETWORKS','UNDEFINED ACNAS','LL')
into carrier_list values ('YTA','YAKIMA TAS','OTHER WIRELESS','WL')
into carrier_list values ('YVA','KENTUCKY DATA LINK ','UNDEFINED ACNAS','LL')
into carrier_list values ('YYX','YOUGHIOGHENY COMM','OTHER WIRELESS','WL')
into carrier_list values ('YYY','RESERVED FOR RT  OBFCLEC','UNDEFINED ACNAS','LL')
into carrier_list values ('ZAX','VERIZON BUSINESSGNI','VERIZON BUSINESS-GNI','LL')
into carrier_list values ('ZCL','ZIPCALL INC','OTHER WIRELESS','WL')
into carrier_list values ('ZDE','KPMG TESTING IN VIRGINIA','UNDEFINED ACNAS','LL')
into carrier_list values ('ZIP','VERIZON BUSINESSOTHER','VERIZON BUSINESS-OTHER','LL')
into carrier_list values ('ZPC','ZIPCOM','OTHER WIRELESS','WL')
into carrier_list values ('ZRP','ZANESVILLE RADIO PHONE','OTHER WIRELESS','WL')
into carrier_list values ('ZVD','VERIZON','VERIZON','LL')
into carrier_list values ('LLJ','MEDIACOM TELEPHONY OF ILLINOIS','UNDEFINED ACNAS','LL')
into carrier_list values ('WIJ','ALLIED WIRELESS COMMUNICATIONS','UNDEFINED ACNAS','WL')
select * from dual;

