--UNE P MTTR BY DAC:
SELECT	* --distinct DM_CCNA_LONG_NAME, DM_CCNA_CD, DM_CCNA_STATE_CD
FROM	DM_WST_APP.NMPW_DM_CCNA_LU
where TO_CHAR(DM_CCNA_START_DT,'YYYYMMDD')=20120201
--and DM_CCNA_LONG_NAME like 'Astro%'
and DM_CCNA_CD = 'MVX' 
order by 2,1,3
