SELECT DISTINCT DOCNO, PON, CKT, ACT, DREC, DD, DDD, COMP_DT, DD_TASK_COMP, PROD, PROJECT, ICSC, DATA3.ACNA, CL.CUSTOMER, 
       EXPEDITE, WHY_MISS, WHY_MISS_DESC, STATE, REGION, TERRITORY, DIRECTOR, NPANXX,
       CLLI6, ORIG_DD_STATUS, ORIG_DDD_STATUS, TL.TASK_LABEL_10
 FROM (      
SELECT DISTINCT DOCUMENT_NUMBER DOCNO, PON, CKT, DREC, DD, DDD, COMP_DT, DD_COMP DD_TASK_COMP,  
       PROD, PROJECT, ACT,
       ICSC, ACNA, 
       CASE WHEN WMRCA IS NOT NULL THEN WMRCA ELSE WHY_MISS END WHY_MISS,
       CASE WHEN WMRCA IS NOT NULL THEN RCA_WHY_MISS_DESC ELSE WHY_MISS_DESC END WHY_MISS_DESC,
       CASE WHEN NSTATE IS NOT NULL THEN NSTATE
            WHEN CSTATE IS NOT NULL THEN CSTATE
            ELSE NPA.STATE END STATE,
       CASE WHEN NAREA IS NOT NULL THEN NAREA
            WHEN CAREA IS NOT NULL THEN CAREA 
            ELSE NULL END REGION,
       CASE WHEN NTER IS NOT NULL THEN NTER
            WHEN CTER IS NOT NULL THEN CTER
            ELSE NULL END TERRITORY,
       CASE WHEN NDIR IS NOT NULL THEN NDIR
            WHEN CDIR IS NOT NULL THEN CDIR 
            ELSE NULL END DIRECTOR,                         
       ORD_NPANXX NPANXX, EXPEDITE,        
       CASE WHEN (COMP_DT <= DD OR DD IS NULL) THEN 'Met'
            WHEN (COMP_DT > DD AND WMRCA IN ('CU01','CU02','CU03','CU04','CU05','DS02','CA22','EX01','CU51','CU52','CU53','CU54','DS52')) THEN 'Met'
            WHEN (COMP_DT > DD AND WMRCA IS NULL AND WHY_MISS IN ('CU01','CU02','CU03','CU04','CU05','DS02','CA22','EX01','CU51','CU52','CU53','CU54','DS52')) THEN 'Met'
            ELSE 'Miss' END ORIG_DD_STATUS,
       CASE WHEN (COMP_DT <= DDD OR DDD IS NULL) THEN 'Met'
            WHEN (COMP_DT > DDD AND WMRCA IN ('CU01','CU02','CU03','CU04','CU05','DS02','CA22','EX01','CU51','CU52','CU53','CU54','DS52')) THEN 'Met'
            WHEN (COMP_DT > DDD AND WMRCA IS NULL AND WHY_MISS IN ('CU01','CU02','CU03','CU04','CU05','DS02','CA22','EX01','CU51','CU52','CU53','CU54','DS52')) THEN 'Met'
            ELSE 'Miss' END ORIG_DDD_STATUS,
        CLLIZ CLLI6    
FROM (
SELECT DISTINCT DOCUMENT_NUMBER, TRUNC(DREC) DREC, DD, DDD, DD_COMP, ACCEPT_DT, 
       CASE WHEN DD_COMP IS NULL AND ACCEPT_DT > DREC THEN ACCEPT_DT
            WHEN ACCEPT_DT IS NULL THEN DD_COMP
            WHEN ACCEPT_DT <= DD_COMP AND ACCEPT_DT > DREC THEN ACCEPT_DT 
            ELSE DD_COMP END COMP_DT, 
       CASE WHEN NC = 'HC' THEN 'DS1'
            WHEN NC = 'HF' THEN 'DS3'
            when substr(ckt,4,2) = 'LX' and substr(PNUM,1,3) = 'DKF' then 'Dark Fiber'
            WHEN SUBSTR(NC,1,1) IN ('L','X') THEN 'DS0'
            WHEN NC IN ('OB','OD','OF','OG') THEN 'OCN'
            WHEN EVC_IND = 'A' THEN 'Ethernet-EVC'
            WHEN EVC_IND = 'B' THEN 'Ethernet-Combo'
            WHEN SUBSTR(NC,1,1) IN ('K') THEN 'Ethernet-UNI'
            WHEN SUBSTR(NC,1,1) IN ('V') THEN 'Ethernet-EVC'
            WHEN SUBSTR(NC,1,2) IN ('SN') THEN 'Ethernet-NNI'
            WHEN SUBSTR(CKT,4,1) IN ('K') THEN 'Ethernet-UNI'
            WHEN SUBSTR(CKT,4,1) IN ('V') THEN 'Ethernet-EVC'
            WHEN SUBSTR(CKT,4,2) IN ('SX') THEN 'Ethernet-NNI'
            ELSE ' ' END PROD,        
        PON, ICSC, ACNA, PROJECT, WHY_MISS, JT.DESCRIPT WHY_MISS_DESC, WMRCA, JTRCA.DESCRIPT RCA_WHY_MISS_DESC, 
        SUPP, CKT, EXPEDITE, ACT, NC, EVC_IND, 
        CLLIZ, NPA||NXX ORD_NPANXX,
        DIRN.NPANXX NNPA, DIRN.AREA NAREA, DIRN.TERRITORY NTER, DIRN.DIRECTOR NDIR, DIRN.STATE NSTATE,
        DIRC.CLLI CNPA, DIRC.AREA CAREA, DIRC.TERRITORY CTER, DIRC.DIRECTOR CDIR, DIRC.STATE CSTATE
FROM (
SELECT SR.DOCUMENT_NUMBER, 
       ASR.REQUEST_TYPE, 
       MAX(ASR.PROJECT_IDENTIFICATION) KEEP (DENSE_RANK LAST ORDER BY ASR.LAST_MODIFIED_DATE) PROJECT, 
       MAX(ASR.DATE_TIME_SENT) KEEP (DENSE_RANK LAST ORDER BY ASR.LAST_MODIFIED_DATE) DREC, 
       MAX(ASR.DESIRED_DUE_DATE) KEEP (DENSE_RANK LAST ORDER BY ASR.LAST_MODIFIED_DATE) DD, 
       MAX(AUD.CRDD) KEEP (DENSE_RANK LAST ORDER BY AUD.LAST_MODIFIED_DATE) DDD, 
       MIN(ACCEPTANCE_DATE) KEEP (DENSE_RANK LAST ORDER BY AUD.LAST_MODIFIED_DATE) ACCEPT_DT, 
       MAX(ASR.NETWORK_CHANNEL_SERVICE_CODE) KEEP (DENSE_RANK LAST ORDER BY ASR.LAST_MODIFIED_DATE) NC, 
       MAX(ASR.PON) KEEP (DENSE_RANK LAST ORDER BY ASR.LAST_MODIFIED_DATE) PON,  
       MAX(ACCESS_PROVIDER_SERV_CTR_CODE) ICSC, 
       MAX(SR.ACNA) ACNA,  
       MAX(ASR.ACTIVITY_INDICATOR) KEEP (DENSE_RANK LAST ORDER BY ASR.LAST_MODIFIED_DATE) ACT, 
       MAX(JW.JEOPARDY_REASON_CODE) KEEP (DENSE_RANK LAST ORDER BY JW.LAST_MODIFIED_DATE) WHY_MISS,
       MAX(JWRCA.JEOPARDY_REASON_CODE) KEEP (DENSE_RANK LAST ORDER BY JWRCA.LAST_MODIFIED_DATE) WMRCA,
       MAX(SUBSTR(NL1.CLLI_CODE,1,6)) KEEP (DENSE_RANK LAST ORDER BY NL1.LAST_MODIFIED_DATE) CLLIZ, 
       TRUNC(T.ACTUAL_COMPLETION_DATE) DD_COMP,
       MAX(SR.SUPPLEMENT_TYPE) KEEP (DENSE_RANK LAST ORDER BY SR.LAST_MODIFIED_DATE) SUPP,
       MAX(SR.FIRST_ECCKT_ID) KEEP (DENSE_RANK LAST ORDER BY SR.LAST_MODIFIED_DATE) CKT,
       MAX(EXPEDITE_INDICATOR) KEEP (DENSE_RANK LAST ORDER BY ASR.LAST_MODIFIED_DATE) EXPEDITE,
       MAX(ASR.EVC_IND) KEEP (DENSE_RANK LAST ORDER BY ASR.LAST_MODIFIED_DATE) EVC_IND,
       MAX(ASR.UNBUNDLED_NETWORK_ELEMENT) KEEP (DENSE_RANK LAST ORDER BY ASR.LAST_MODIFIED_DATE) UNE,
       MAX(ASR.promotion_nbr) KEEP (DENSE_RANK LAST ORDER BY ASR.LAST_MODIFIED_DATE) PNUM,
       MAX(ASR.NPA) KEEP (DENSE_RANK LAST ORDER BY ASR.LAST_MODIFIED_DATE) NPA,
       MAX(ASR.NXX) KEEP (DENSE_RANK LAST ORDER BY ASR.LAST_MODIFIED_DATE) NXX
FROM CASDW.ASR_USER_DATA AUD, 
     CASDW.ACCESS_SERVICE_REQUEST ASR,
     CASDW.SERV_REQ SR,
     CASDW.NETWORK_LOCATION NL1,
     CASDW.TASK_JEOPARDY_WHYMISS JW,
     CASDW.TASK_JEOPARDY_WHYMISS JWRCA,
     CASDW.TASK T,
     CASDW.TASK TRCA,
     CASDW.CIRCUIT C
WHERE SR.DOCUMENT_NUMBER = ASR.DOCUMENT_NUMBER
  AND SR.DOCUMENT_NUMBER = AUD.DOCUMENT_NUMBER(+)
  AND SR.FIRST_ECCKT_ID = C.EXCHANGE_CARRIER_CIRCUIT_ID (+)
  AND C.LOCATION_ID_2 = NL1.LOCATION_ID(+)
  AND SR.DOCUMENT_NUMBER = T.DOCUMENT_NUMBER
  AND SR.DOCUMENT_NUMBER = TRCA.DOCUMENT_NUMBER (+)
  AND T.TASK_NUMBER = JW.TASK_NUMBER(+)
  AND TRCA.TASK_NUMBER = JWRCA.TASK_NUMBER(+)
  AND TO_CHAR(T.ACTUAL_COMPLETION_DATE,'yyyymm') = '202106'   --CHANGE EACH MONTH - CURRENT REPORTING MONTH  
  AND ASR.REQUEST_TYPE IN ('S','E')
  AND ASR.ACTIVITY_INDICATOR IN ('N','C')
  AND ASR.ORDER_TYPE = 'ASR'
  AND JW.JEOPARDY_TYPE_CD(+) = 'W' 
  AND T.TASK_TYPE = 'DD'
  AND TRCA.TASK_TYPE (+) = 'RCA'
  AND SR.DOCUMENT_NUMBER > '1000000'
  GROUP BY SR.DOCUMENT_NUMBER, ASR.REQUEST_TYPE, T.ACTUAL_COMPLETION_DATE
) DATA, 
  rvv827.DIRECTOR_NPANXX_4 DIRN,
  rvv827.DIRECTOR_CLLI_4 DIRC,
  rvv827.JEOPARDY_TYPE JT,
  rvv827.JEOPARDY_TYPE JTRCA
  WHERE DATA.NPA||DATA.NXX = DIRN.NPANXX (+)
  AND CLLIZ = DIRC.CLLI (+) 
  AND WHY_MISS = JT.CODE(+) 
  AND WMRCA = JTRCA.CODE(+) 
  AND (NC NOT IN ('TD','TR') OR NC IS NULL)
  AND (UNE = 'N' OR UNE IS NULL)
) DATA2,
  rvv827.NPANXX NPA
WHERE DATA2.ORD_NPANXX = NPA.NPANXX (+) 
 AND (SUPP <> 1 OR SUPP IS NULL)  
 AND (ACNA NOT IN ('FLR','ZTK','BLI','BNK','CMW','COY','CQV','CUS','CZE','CZJ','CZN','CZX','EPX','ERR','EXC','FBA','FCA','FIS',
                   'FLX','GOP','GTO','GVN','IZH','NNR','OGD','RGD','ROU','T05','VAC','VZN','WDK','ZAP','ZWV','ZZZ','XYY','NFZ') OR ACNA IS NULL)
) DATA3, rvv827.CARRIER_LIST CL, LAA122.TASK_LABEL10 TL
WHERE DATA3.ACNA = CL.ACNA(+)
AND DATA3.DOCNO = TL.DOCUMENT_NUMBER (+)
AND STATE NOT IN ('WA','OR','ID','MT')                  
ORDER BY 1
;
