select DOCNO, PON, ACNA, ICSC, STATE, D_REC, APP_COMP_DT, DD, DDD, Accept_dt, DD_COMP_DT, NC, SPEC, request_type, ACT, expedite, task_at_ready, work_queue_id
FROM (
SELECT PON, DOCUMENT_NUMBER DOCNO, ACNA, ACT, CKT, D_REC, DD, DDD, accept_dt, dd_comp_dt, 	
	   ICSC, 
       CASE WHEN STATE IN ('NY','PA','CT','WA','OR','WI','ID','TN','IL','MN','OH','WV','NC','SC','IN','MI','NE','CA','AZ','NV','NM','UT','MT','AL','FL','GA','MS','KY','IA','MO','MD','VA','TX') THEN STATE
			WHEN CFASTATE IN ('NY','PA','CT','WA','OR','WI','ID','TN','IL','MN','OH','WV','NC','SC','IN','MI','NE','CA','AZ','NV','NM','UT','MT','AL','FL','GA','MS','KY','IA','MO','MD','VA','TX') THEN CFASTATE
	        WHEN POT IN ('NY','PA','CT','WA','OR','WI','ID','TN','IL','MN','OH','WV','NC','SC','IN','MI','NE','CA','AZ','NV','NM','UT','MT','AL','FL','GA','MS','KY','IA','MO','MD','VA','TX') THEN POT
	        WHEN ICSC = 'FV01' THEN 'WV'
			WHEN ICSC = 'SN01' THEN 'CT'
			WHEN SUBSTR(ICSC,1,2) = 'FV' AND SUBSTR(CKT,1,2) = '30' THEN 'IL'
			WHEN SUBSTR(ICSC,1,2) = 'FV' AND SUBSTR(CKT,1,2) = '31' THEN 'IN'
			WHEN SUBSTR(ICSC,1,2) = 'FV' AND SUBSTR(CKT,1,2) = '33' THEN 'MI'
			WHEN SUBSTR(ICSC,1,2) = 'FV' AND SUBSTR(CKT,1,2) = '36' THEN 'OH'
			WHEN SUBSTR(ICSC,1,2) = 'FV' AND SUBSTR(CKT,1,2) = '39' THEN 'WI'
			WHEN SUBSTR(ICSC,1,2) = 'FV' AND SUBSTR(CKT,1,2) = '43' THEN 'OR'
			WHEN SUBSTR(ICSC,1,2) = 'FV' AND SUBSTR(CKT,1,2) = '61' THEN 'NC'
			WHEN SUBSTR(ICSC,1,2) = 'FV' AND SUBSTR(CKT,1,2) = '62' THEN 'SC'
			WHEN SUBSTR(ICSC,1,2) = 'FV' AND SUBSTR(CKT,1,2) = '83' THEN 'ID'
			WHEN SUBSTR(ICSC,1,2) = 'FV' AND SUBSTR(CKT,1,2) = '85' THEN 'OR'
			WHEN SUBSTR(ICSC,1,2) = 'FV' AND SUBSTR(CKT,1,2) = '86' THEN 'WA'
			WHEN SUBSTR(ICSC,1,2) <> 'FV' AND SUBSTR(CKT,1,2) = '61' THEN 'PA'
			WHEN SUBSTR(CKT,1,2) = '23' THEN 'MN'
			WHEN SUBSTR(CKT,1,2) = '50' THEN 'WV'
			WHEN SUBSTR(CKT,1,2) = '11' THEN 'AZ'
			WHEN SUBSTR(CKT,1,2) = '97' THEN 'NY'
			WHEN ICSC = 'RT01' THEN 'NY'
			WHEN ICSC in ('IB94') THEN 'IL'
			ELSE null END STATE,
	   NC, spec, request_type, expedite, app_comp_dt, task_at_ready, work_queue_id
FROM
(
SELECT distinct SR.ACNA,
       SR.PON,
       SR.DOCUMENT_NUMBER,
	   ASR.ACCESS_PROVIDER_SERV_CTR_CODE ICSC, 
       ASR.REQUEST_TYPE,  
       ASR.DATE_RECEIVED D_REC, 
	   ASR.DESIRED_DUE_DATE DD, 
	   AUD.CRDD DDD, 
	   ACCEPTANCE_DATE ACCEPT_DT,
	   TRUNC(T2.ACTUAL_COMPLETION_DATE-5/24) DD_COMP_DT,
	   ASR.NETWORK_CHANNEL_SERVICE_CODE NC, 
	   ASR.SERVICE_AND_PRODUCT_ENHANC_COD SPEC,  
	   ASR.ACTIVITY_INDICATOR ACT,
	   asr.NPA,
	   asr.NXX,
	   TRUNC(T1.ACTUAL_COMPLETION_DATE-5/24) APP_COMP_DT,
	   ASR.SUPPLEMENT_TYPE SUPP,
	   SR.FIRST_ECCKT_ID CKT,
	   EXPEDITE_INDICATOR EXPEDITE,
	   substr(npa.exchange_area_clli,5,2) state,
	   SUBSTR(ASR.ADDITIONAL_POINT_OF_TERM,5,2) POT,
	   SUBSTR(ASR.CONNECTING_FACILITY_ASSIGNMENT,24,2) CFASTATE,  
	   t3.task_type task_at_ready, 
	   t3.work_queue_id 
--
FROM SERV_REQ SR, 
     ACCESS_SERVICE_REQUEST ASR,
	 ASR_USER_DATA AUD,
	 TASK T1,
	 TASK T2,
	 TASK T3,
	 NPA_NXX NPA
--
WHERE SR.DOCUMENT_NUMBER = ASR.DOCUMENT_NUMBER(+)
AND SR.DOCUMENT_NUMBER = T1.DOCUMENT_NUMBER (+)
AND SR.DOCUMENT_NUMBER = T2.DOCUMENT_NUMBER (+)
AND SR.DOCUMENT_NUMBER = T3.DOCUMENT_NUMBER (+)
AND SR.DOCUMENT_NUMBER = AUD.DOCUMENT_NUMBER (+)
AND asr.NPA = NPA.NPA (+)
and asr.nxx = npa.nxx (+)
AND SR.TYPE_OF_SR in ('ASR')
and asr.activity_indicator not in ('D','R')
AND T1.TASK_TYPE = 'APP'
AND T2.TASK_TYPE = 'DD'
and t3.task_status = 'Ready'
and EXPEDITE_INDICATOR = 'Y'
and T2.ACTUAL_COMPLETION_DATE is null
--
)
where (SUPP <> '1' OR SUPP IS NULL)
and (acna not in ('ZTK','ZZZ','ZWV') or acna is null)
)
order by 8		 