--created table in the schema browser   
--must run commit after insert or delete   
  
commit;  

delete from TEMP_HIER; 
  
select count(*) from temp_hier

INSERT ALL
into temp_hier values ('ABVLSC','Southeast','South Carolina')
into temp_hier values ('ACLKIL','Central','Illinois')
into temp_hier values ('ACMEWA','West','Washington')
into temp_hier values ('ADENOH','Central','Ohio')
into temp_hier values ('ADMSWI','Central','Wisconsin')
into temp_hier values ('ADRNMI','Midwest','Central District')
into temp_hier values ('ADSNMI','Midwest','Central District')
into temp_hier values ('ADVLMI','Midwest','Central District')
into temp_hier values ('AGSTIL','Central','Illinois')
into temp_hier values ('AHVLNC','Southeast','North Carolina')
into temp_hier values ('AHVLOH','Central','Ohio')
into temp_hier values ('AKRNIN','Midwest','South District')
into temp_hier values ('ALBMNC','Southeast','North Carolina')
into temp_hier values ('ALBNIL','Central','Illinois')
into temp_hier values ('ALBNIN','Midwest','Central District')
into temp_hier values ('ALBRIL','Central','Illinois')
into temp_hier values ('ALBYOH','Central','Ohio')
into temp_hier values ('ALDLIL','Central','Illinois')
into temp_hier values ('ALDNMI','Midwest','North District')
into temp_hier values ('ALFDWA','West','Washington')
into temp_hier values ('ALGRMI','Midwest','North District')
into temp_hier values ('ALGRWA','West','Washington')
into temp_hier values ('ALLGMI','Midwest','Central District')
into temp_hier values ('ALMAMI','Midwest','North District')
into temp_hier values ('ALMTMI','Midwest','North District')
into temp_hier values ('ALNTWI','Central','Wisconsin')
into temp_hier values ('ALOHOR','West','Oregon')
into temp_hier values ('ALPEMI','Midwest','North District')
into temp_hier values ('ALTNNC','Southeast','North Carolina')
into temp_hier values ('ALVNIL','Central','Illinois')
into temp_hier values ('ALXNIL','Central','Illinois')
into temp_hier values ('AMBYIL','Central','Illinois')
into temp_hier values ('AMDAOH','Central','Ohio')
into temp_hier values ('AMHROH','Central','Ohio')
into temp_hier values ('AMSTOH','Central','Ohio')
into temp_hier values ('AMTYOR','West','Oregon')
into temp_hier values ('AMVLOH','Central','Ohio')
into temp_hier values ('AMVLOR','West','Oregon')
into temp_hier values ('ANCRWA','West','Washington')
into temp_hier values ('ANDRNC','Southeast','North Carolina')
into temp_hier values ('ANDRSC','Southeast','South Carolina')
into temp_hier values ('ANGLIN','Midwest','Central District')
into temp_hier values ('ANNAIL','Central','Illinois')
into temp_hier values ('ANNPIL','Central','Illinois')
into temp_hier values ('ANTGWI','Central','Wisconsin')
into temp_hier values ('APPLWI','Central','Wisconsin')
into temp_hier values ('APRVIL','Central','Illinois')
into temp_hier values ('ARCHOH','Central','Ohio')
into temp_hier values ('ARENWI','Central','Wisconsin')
into temp_hier values ('ARGTIL','Central','Illinois')
into temp_hier values ('ARMSIL','Central','Illinois')
into temp_hier values ('ARRWIL','Central','Illinois')
into temp_hier values ('ARTNIN','Midwest','South District')
into temp_hier values ('ARTNOH','Central','Ohio')
into temp_hier values ('ARTNWA','West','Washington')
into temp_hier values ('ASHKIL','Central','Illinois')
into temp_hier values ('ASHYIN','Midwest','Central District')
into temp_hier values ('ASHYMI','Midwest','North District')
into temp_hier values ('ASHYOH','Central','Ohio')
into temp_hier values ('ASLDOH','Central','Ohio')
into temp_hier values ('ASTNIL','Central','Illinois')
into temp_hier values ('ASTRIL','Central','Illinois')
into temp_hier values ('ATHNOH','Central','Ohio')
into temp_hier values ('ATHNWI','Central','Wisconsin')
into temp_hier values ('ATHOID','West','Southwest/Mountain')
into temp_hier values ('ATLNIL','Central','Illinois')
into temp_hier values ('ATLNMI','Midwest','North District')
into temp_hier values ('ATTCIN','Midwest','South District')
into temp_hier values ('ATTCOH','Central','Ohio')
into temp_hier values ('ATWDIN','Midwest','South District')
into temp_hier values ('ATWPOH','Central','Ohio')
into temp_hier values ('AUBNIL','Central','Illinois')
into temp_hier values ('AUBNIN','Midwest','South District')
into temp_hier values ('AUSTIN','Midwest','South District')
into temp_hier values ('AVA IL','Central','Illinois')
into temp_hier values ('AVLLIN','Midwest','Central District')
into temp_hier values ('AVOCMI','Midwest','North District')
into temp_hier values ('AVONIL','Central','Illinois')
into temp_hier values ('BARYIL','Central','Illinois')
into temp_hier values ('BATHMI','Midwest','North District')
into temp_hier values ('BAVLNC','Southeast','North Carolina')
into temp_hier values ('BCKLIL','Central','Illinois')
into temp_hier values ('BCKNIN','Midwest','South District')
into temp_hier values ('BCYROH','Central','Ohio')
into temp_hier values ('BDTWIL','Central','Illinois')
into temp_hier values ('BDVLIL','Central','Illinois')
into temp_hier values ('BEMTIL','Central','Illinois')
into temp_hier values ('BERNIN','Midwest','South District')
into temp_hier values ('BESNIL','Central','Illinois')
into temp_hier values ('BEVROH','Central','Ohio')
into temp_hier values ('BFTNIN','Midwest','South District')
into temp_hier values ('BGLKWA','West','Washington')
into temp_hier values ('BGRPMI','Midwest','North District')
into temp_hier values ('BGRVCA','West','Southwest/Mountain')
into temp_hier values ('BKNGOR','West','Oregon')
into temp_hier values ('BKPTIL','Central','Illinois')
into temp_hier values ('BKTNIN','Midwest','South District')
into temp_hier values ('BKVLIN','Midwest','South District')
into temp_hier values ('BKVLOH','Central','Ohio')
into temp_hier values ('BLANWA','West','Washington')
into temp_hier values ('BLCHOH','Central','Ohio')
into temp_hier values ('BLCYWI','Central','Wisconsin')
into temp_hier values ('BLDLMI','Midwest','North District')
into temp_hier values ('BLDWIL','Central','Illinois')
into temp_hier values ('BLFDMI','Midwest','Central District')
into temp_hier values ('BLFLIL','Central','Illinois')
into temp_hier values ('BLFSIL','Central','Illinois')
into temp_hier values ('BLGMWI','Central','Wisconsin')
into temp_hier values ('BLHMWA','West','Washington')
into temp_hier values ('BLHNOH','Central','Ohio')
into temp_hier values ('BLHRWI','Central','Wisconsin')
into temp_hier values ('BLLFOH','Central','Ohio')
into temp_hier values ('BLLNWI','Central','Wisconsin')
into temp_hier values ('BLLRMI','Midwest','North District')
into temp_hier values ('BLLVOH','Central','Ohio')
into temp_hier values ('BLLVWA','West','Washington')
into temp_hier values ('BLNCMI','Midwest','North District')
into temp_hier values ('BLNVIL','Central','Illinois')
into temp_hier values ('BLTCOH','Central','Ohio')
into temp_hier values ('BLTMOH','Central','Ohio')
into temp_hier values ('BLTNIL','Central','Illinois')
into temp_hier values ('BLVDIL','Central','Illinois')
into temp_hier values ('BLVLWI','Central','Wisconsin')
into temp_hier values ('BLVROH','Central','Ohio')
into temp_hier values ('BLYTCA','West','Southwest/Mountain')
into temp_hier values ('BMFDIL','Central','Illinois')
into temp_hier values ('BMNTIL','Central','Illinois')
into temp_hier values ('BMVLOH','Central','Ohio')
into temp_hier values ('BNCRMI','Midwest','North District')
into temp_hier values ('BNCYWA','West','Washington')
into temp_hier values ('BNDNOR','West','Oregon')
into temp_hier values ('BNFYID','West','Southwest/Mountain')
into temp_hier values ('BNGRMI','Midwest','Central District')
into temp_hier values ('BNISWA','West','Washington')
into temp_hier values ('BNKSOR','West','Oregon')
into temp_hier values ('BNSNIL','Central','Illinois')
into temp_hier values ('BNTNIL','Central','Illinois')
into temp_hier values ('BOTHWA','West','Washington')
into temp_hier values ('BOUSAZ','West','Southwest/Mountain')
into temp_hier values ('BOVLID','West','Southwest/Mountain')
into temp_hier values ('BPPSIN','Midwest','South District')
into temp_hier values ('BRBAWA','West','Washington')
into temp_hier values ('BRBNIN','Midwest','South District')
into temp_hier values ('BRBNOH','Central','Ohio')
into temp_hier values ('BRCYNC','Southeast','North Carolina')
into temp_hier values ('BRDAMI','Midwest','Central District')
into temp_hier values ('BRDGMI','Midwest','Central District')
into temp_hier values ('BRDSIL','Central','Illinois')
into temp_hier values ('BRDSIN','Midwest','South District')
into temp_hier values ('BRFRIL','Central','Illinois')
into temp_hier values ('BRGHOH','Central','Ohio')
into temp_hier values ('BRGVWI','Central','Wisconsin')
into temp_hier values ('BRHDWI','Central','Wisconsin')
into temp_hier values ('BRHMOH','Central','Ohio')
into temp_hier values ('BRILOH','Central','Ohio')
into temp_hier values ('BRKLWI','Central','Wisconsin')
into temp_hier values ('BRKTIN','Midwest','South District')
into temp_hier values ('BRLDIL','Central','Illinois')
into temp_hier values ('BRLNOH','Central','Ohio')
into temp_hier values ('BRLWOH','Central','Ohio')
into temp_hier values ('BRLWOH','Central','Ohio')
into temp_hier values ('BRMNOH','Central','Ohio')
into temp_hier values ('BROKMI','Midwest','Central District')
into temp_hier values ('BRPRIL','Central','Illinois')
into temp_hier values ('BRPTIL','Central','Illinois')
into temp_hier values ('BRPTWA','West','Washington')
into temp_hier values ('BRRGMI','Midwest','North District')
into temp_hier values ('BRSNMI','Midwest','Central District')
into temp_hier values ('BRSTIN','Midwest','Central District')
into temp_hier values ('BRSTWI','Central','Wisconsin')
into temp_hier values ('BRTNIL','Central','Illinois')
into temp_hier values ('BRTNMI','Midwest','Central District')
into temp_hier values ('BRTWIN','Midwest','South District')
into temp_hier values ('BRVLNC','Southeast','North Carolina')
into temp_hier values ('BRWDWI','Central','Wisconsin')
into temp_hier values ('BRWKOH','Central','Ohio')
into temp_hier values ('BRWSOH','Central','Ohio')
into temp_hier values ('BRWSWA','West','Washington')
into temp_hier values ('BRYNIN','Midwest','South District')
into temp_hier values ('BRYNOH','Central','Ohio')
into temp_hier values ('BRYTMI','Midwest','North District')
into temp_hier values ('BRZLIN','Midwest','South District')
into temp_hier values ('BSHNIL','Central','Illinois')
into temp_hier values ('BSMRIL','Central','Illinois')
into temp_hier values ('BSVLOH','Central','Ohio')
into temp_hier values ('BSVLSC','Southeast','South Carolina')
into temp_hier values ('BTCKMI','Midwest','North District')
into temp_hier values ('BTHNIL','Central','Illinois')
into temp_hier values ('BTLGIN','Midwest','South District')
into temp_hier values ('BTLRIN','Midwest','Central District')
into temp_hier values ('BTVIIN','Midwest','South District')
into temp_hier values ('BTVLIN','Midwest','South District')
into temp_hier values ('BUDAIL','Central','Illinois')
into temp_hier values ('BUREIL','Central','Illinois')
into temp_hier values ('BURLMI','Midwest','Central District')
into temp_hier values ('BURLOH','Central','Ohio')
into temp_hier values ('BURLWA','West','Washington')
into temp_hier values ('BUVLIN','Midwest','South District')
into temp_hier values ('BVRLOH','Central','Ohio')
into temp_hier values ('BVTNOR','West','Oregon')
into temp_hier values ('BVVLIL','Central','Illinois')
into temp_hier values ('BWCYMI','Midwest','North District')
into temp_hier values ('BWLGOH','Central','Ohio')
into temp_hier values ('BWMNSC','Southeast','South Carolina')
into temp_hier values ('BWTNOH','Central','Ohio')
into temp_hier values ('BYCYMI','Midwest','North District')
into temp_hier values ('BYLSIL','Central','Illinois')
into temp_hier values ('BYRNIL','Central','Illinois')
into temp_hier values ('BYVLOH','Central','Ohio')
into temp_hier values ('BYVWID','West','Southwest/Mountain')
into temp_hier values ('CADZOH','Central','Ohio')
into temp_hier values ('CAIRIL','Central','Illinois')
into temp_hier values ('CAMSWA','West','Oregon')
into temp_hier values ('CANNIN','Midwest','South District')
into temp_hier values ('CARMIL','Central','Illinois')
into temp_hier values ('CARVIL','Central','Illinois')
into temp_hier values ('CARYNC','Southeast','North Carolina')
into temp_hier values ('CARYOH','Central','Ohio')
into temp_hier values ('CASYIL','Central','Illinois')
into temp_hier values ('CBCYIN','Midwest','Central District')
into temp_hier values ('CBDNIL','Central','Illinois')
into temp_hier values ('CBRYIL','Central','Illinois')
into temp_hier values ('CBVLMI','Midwest','North District')
into temp_hier values ('CDGVWI','Central','Wisconsin')
into temp_hier values ('CDPNIL','Central','Illinois')
into temp_hier values ('CDVLIL','Central','Illinois')
into temp_hier values ('CDWLMI','Midwest','Central District')
into temp_hier values ('CDWRMI','Midwest','Central District')
into temp_hier values ('CDWROH','Central','Ohio')
into temp_hier values ('CELNOH','Central','Ohio')
into temp_hier values ('CENTIN','Midwest','South District')
into temp_hier values ('CETNIL','Central','Illinois')
into temp_hier values ('CETNOH','Central','Ohio')
into temp_hier values ('CEVLCA','West','Southwest/Mountain')
into temp_hier values ('CFTNIL','Central','Illinois')
into temp_hier values ('CGVIIN','Midwest','South District')
into temp_hier values ('CGVLIL','Central','Illinois')
into temp_hier values ('CHAPIL','Central','Illinois')
into temp_hier values ('CHBNIL','Central','Illinois')
into temp_hier values ('CHENIL','Central','Illinois')
into temp_hier values ('CHESIL','Central','Illinois')
into temp_hier values ('CHESOH','Central','Ohio')
into temp_hier values ('CHHMIL','Central','Illinois')
into temp_hier values ('CHHMOH','Central','Ohio')
into temp_hier values ('CHLCIL','Central','Illinois')
into temp_hier values ('CHLCOH','Central','Ohio')
into temp_hier values ('CHLNWA','West','Washington')
into temp_hier values ('CHMPIL','Central','Illinois')
into temp_hier values ('CHNCIL','Central','Illinois')
into temp_hier values ('CHRBIN','Midwest','Central District')
into temp_hier values ('CHRKNC','Southeast','North Carolina')
into temp_hier values ('CHRLNC','Southeast','North Carolina')
into temp_hier values ('CHRSIL','Central','Illinois')
into temp_hier values ('CHRTIL','Central','Illinois')
into temp_hier values ('CHSDOH','Central','Ohio')
into temp_hier values ('CHSKOH','Central','Ohio')
into temp_hier values ('CHSNSC','Southeast','South Carolina')
into temp_hier values ('CHTNIN','Midwest','Central District')
into temp_hier values ('CHVYIL','Central','Illinois')
into temp_hier values ('CHWOIL','Central','Illinois')
into temp_hier values ('CICRIN','Midwest','South District')
into temp_hier values ('CISCIL','Central','Illinois')
into temp_hier values ('CITNWI','Central','Wisconsin')
into temp_hier values ('CIVLWI','Central','Wisconsin')
into temp_hier values ('CLARMI','Midwest','North District')
into temp_hier values ('CLBYWA','West','Washington')
into temp_hier values ('CLBYWI','Central','Wisconsin')
into temp_hier values ('CLCHIL','Central','Illinois')
into temp_hier values ('CLCKSC','Southeast','South Carolina')
into temp_hier values ('CLDMWA','West','Washington')
into temp_hier values ('CLDNOH','Central','Ohio')
into temp_hier values ('CLFKID','West','Southwest/Mountain')
into temp_hier values ('CLFLSC','Southeast','South Carolina')
into temp_hier values ('CLFRMI','Midwest','North District')
into temp_hier values ('CLFXIL','Central','Illinois')
into temp_hier values ('CLHLIN','Midwest','South District')
into temp_hier values ('CLHNIL','Central','Illinois')
into temp_hier values ('CLMASC','Southeast','South Carolina')
into temp_hier values ('CLMAWA','West','Washington')
into temp_hier values ('CLMTIL','Central','Illinois')
into temp_hier values ('CLPLIN','Midwest','South District')
into temp_hier values ('CLRVMI','Midwest','North District')
into temp_hier values ('CLSNIL','Central','Illinois')
into temp_hier values ('CLSPIL','Central','Illinois')
into temp_hier values ('CLSPIN','Midwest','South District')
into temp_hier values ('CLTNIL','Central','Illinois')
into temp_hier values ('CLTNMI','Midwest','Central District')
into temp_hier values ('CLTNWI','Central','Wisconsin')
into temp_hier values ('CLTSOR','West','Oregon')
into temp_hier values ('CLVLOH','Central','Ohio')
into temp_hier values ('CLVWWA','West','Washington')
into temp_hier values ('CLWHNC','Southeast','North Carolina')
into temp_hier values ('CLWLOH','Central','Ohio')
into temp_hier values ('CLYDOH','Central','Ohio')
into temp_hier values ('CLYMWI','Central','Wisconsin')
into temp_hier values ('CMBGIN','Midwest','South District')
into temp_hier values ('CMBROH','Central','Ohio')
into temp_hier values ('CMBRWI','Central','Wisconsin')
into temp_hier values ('CMCYIN','Midwest','South District')
into temp_hier values ('CMDNIN','Midwest','South District')
into temp_hier values ('CMGVIL','Central','Illinois')
into temp_hier values ('CMISWA','West','Washington')
into temp_hier values ('CMLDOH','Central','Ohio')
into temp_hier values ('CMPNIL','Central','Illinois')
into temp_hier values ('CMPSIL','Central','Illinois')
into temp_hier values ('CMPTWI','Central','Wisconsin')
into temp_hier values ('CMTNIL','Central','Illinois')
into temp_hier values ('CNBYOR','West','Oregon')
into temp_hier values ('CNCRWA','West','Washington')
into temp_hier values ('CNGROH','Central','Ohio')
into temp_hier values ('CNKLMI','Midwest','North District')
into temp_hier values ('CNLKMI','Midwest','North District')
into temp_hier values ('CNNLWA','West','Washington')
into temp_hier values ('CNSTMI','Midwest','Central District')
into temp_hier values ('CNVIMI','Midwest','Central District')
into temp_hier values ('CNVLIN','Midwest','South District')
into temp_hier values ('CNVYOH','Central','Ohio')
into temp_hier values ('CNWYSC','Southeast','South Carolina')
into temp_hier values ('CNWYWA','West','Washington')
into temp_hier values ('COBBWI','Central','Wisconsin')
into temp_hier values ('CODLIN','Midwest','South District')
into temp_hier values ('COLNMI','Midwest','Central District')
into temp_hier values ('COOLOH','Central','Ohio')
into temp_hier values ('CORYIN','Midwest','South District')
into temp_hier values ('COVEOR','West','Washington')
into temp_hier values ('COVLIN','Midwest','South District')
into temp_hier values ('CPACMI','Midwest','North District')
into temp_hier values ('CPDLOH','Central','Ohio')
into temp_hier values ('CPHLNC','Southeast','North Carolina')
into temp_hier values ('CPRNIL','Central','Illinois')
into temp_hier values ('CPVLMI','Midwest','North District')
into temp_hier values ('CPVLWA','West','Washington')
into temp_hier values ('CQLLOR','West','Oregon')
into temp_hier values ('CRALID','West','Southwest/Mountain')
into temp_hier values ('CRANIN','Midwest','South District')
into temp_hier values ('CRBTOR','West','Oregon')
into temp_hier values ('CRCYCA','West','Oregon')
into temp_hier values ('CRCYMI','Midwest','North District')
into temp_hier values ('CRCYNV','West','Southwest/Mountain')
into temp_hier values ('CRDLIL','Central','Illinois')
into temp_hier values ('CRDMNC','Southeast','North Carolina')
into temp_hier values ('CRGRIL','Central','Illinois')
into temp_hier values ('CRLCIL','Central','Illinois')
into temp_hier values ('CRLNOH','Central','Ohio')
into temp_hier values ('CRLSIN','Midwest','South District')
into temp_hier values ('CRLWWA','West','Washington')
into temp_hier values ('CRMLIL','Central','Illinois')
into temp_hier values ('CRNDIN','Midwest','South District')
into temp_hier values ('CRNLOR','West','Oregon')
into temp_hier values ('CRNNMI','Midwest','North District')
into temp_hier values ('CRPSIL','Central','Illinois')
into temp_hier values ('CRTCOH','Central','Ohio')
into temp_hier values ('CRTHIL','Central','Illinois')
into temp_hier values ('CRTHIN','Midwest','South District')
into temp_hier values ('CRTNIL','Central','Illinois')
into temp_hier values ('CRTNOH','Central','Ohio')
into temp_hier values ('CRVLOH','Central','Ohio')
into temp_hier values ('CSBYOR','West','Oregon')
into temp_hier values ('CSCDWI','Central','Wisconsin')
into temp_hier values ('CSCYMI','Midwest','North District')
into temp_hier values ('CSHRNC','Southeast','North Carolina')
into temp_hier values ('CSHRWA','West','Washington')
into temp_hier values ('CSLCOR','West','Oregon')
into temp_hier values ('CSPKIL','Central','Illinois')
into temp_hier values ('CSPLMI','Midwest','Central District')
into temp_hier values ('CSTNIL','Central','Illinois')
into temp_hier values ('CSTRWA','West','Washington')
into temp_hier values ('CSVIMI','Midwest','North District')
into temp_hier values ('CSVLIL','Central','Illinois')
into temp_hier values ('CSVLIN','Midwest','South District')
into temp_hier values ('CSVLMI','Midwest','North District')
into temp_hier values ('CTBGIL','Central','Illinois')
into temp_hier values ('CTGVWI','Central','Wisconsin')
into temp_hier values ('CTISOH','Central','Ohio')
into temp_hier values ('CTLRIN','Midwest','South District')
into temp_hier values ('CTPNIN','Midwest','South District')
into temp_hier values ('CTPOMI','Midwest','North District')
into temp_hier values ('CTVLIL','Central','Illinois')
into temp_hier values ('CTWBOH','Central','Ohio')
into temp_hier values ('CUBAIL','Central','Illinois')
into temp_hier values ('CUSKWA','West','Washington')
into temp_hier values ('CVRTMI','Midwest','Central District')
into temp_hier values ('CVTNOH','Central','Ohio')
into temp_hier values ('CVTPOH','Central','Ohio')
into temp_hier values ('CYCYIL','Central','Illinois')
into temp_hier values ('CYCYIN','Midwest','South District')
into temp_hier values ('CYDNIN','Midwest','South District')
into temp_hier values ('CYNTIN','Midwest','South District')
into temp_hier values ('CYPRIL','Central','Illinois')
into temp_hier values ('CYTNIL','Central','Illinois')
into temp_hier values ('CYTNMI','Midwest','Central District')
into temp_hier values ('CYVLIL','Central','Illinois')
into temp_hier values ('DAKTIL','Central','Illinois')
into temp_hier values ('DARNWI','Central','Wisconsin')
into temp_hier values ('DAVSIL','Central','Illinois')
into temp_hier values ('DCKRIN','Midwest','South District')
into temp_hier values ('DCTRIN','Midwest','Central District')
into temp_hier values ('DCTRMI','Midwest','Central District')
into temp_hier values ('DCTROH','Central','Ohio')
into temp_hier values ('DCVLMI','Midwest','North District')
into temp_hier values ('DCVLWI','Central','Wisconsin')
into temp_hier values ('DELDIL','Central','Illinois')
into temp_hier values ('DERYID','West','Southwest/Mountain')
into temp_hier values ('DESTIL','Central','Illinois')
into temp_hier values ('DFNCOH','Central','Ohio')
into temp_hier values ('DGVLWI','Central','Wisconsin')
into temp_hier values ('DHLGIL','Central','Illinois')
into temp_hier values ('DIXNIL','Central','Illinois')
into temp_hier values ('DKLBIL','Central','Illinois')
into temp_hier values ('DLPHIN','Midwest','South District')
into temp_hier values ('DLRYOH','Central','Ohio')
into temp_hier values ('DLVLOH','Central','Ohio')
into temp_hier values ('DLWROH','Central','Ohio')
into temp_hier values ('DMNGWA','West','Washington')
into temp_hier values ('DNDSIL','Central','Illinois')
into temp_hier values ('DNFTIL','Central','Illinois')
into temp_hier values ('DNKRIN','Midwest','South District')
into temp_hier values ('DNLPIL','Central','Illinois')
into temp_hier values ('DNLPIN','Midwest','Central District')
into temp_hier values ('DNVNIL','Central','Illinois')
into temp_hier values ('DONGIL','Central','Illinois')
into temp_hier values ('DOVRIL','Central','Illinois')
into temp_hier values ('DOVROH','Central','Ohio')
into temp_hier values ('DRCHWI','Central','Wisconsin')
into temp_hier values ('DRCKIL','Central','Illinois')
into temp_hier values ('DRFDWI','Central','Wisconsin')
into temp_hier values ('DRHMNC','Southeast','North Carolina')
into temp_hier values ('DRNDIL','Central','Illinois')
into temp_hier values ('DRNDMI','Midwest','North District')
into temp_hier values ('DRTNWA','West','Washington')
into temp_hier values ('DRTNWI','Central','Wisconsin')
into temp_hier values ('DRYDMI','Midwest','North District')
into temp_hier values ('DTCYIL','Central','Illinois')
into temp_hier values ('DTRTOR','West','Oregon')
into temp_hier values ('DUBSIN','Midwest','South District')
into temp_hier values ('DUNDMI','Midwest','Central District')
into temp_hier values ('DUQNIL','Central','Illinois')
into temp_hier values ('DVLLWA','West','Washington')
into temp_hier values ('DVRNIL','Central','Illinois')
into temp_hier values ('DVSNMI','Midwest','North District')
into temp_hier values ('DWGCMI','Midwest','Central District')
into temp_hier values ('DWNSIL','Central','Illinois')
into temp_hier values ('DWTTMI','Midwest','North District')
into temp_hier values ('DXCYOH','Central','Ohio')
into temp_hier values ('DYTNOH','Central','Ohio')
into temp_hier values ('DYTNOR','West','Oregon')
into temp_hier values ('EARPCA','West','Southwest/Mountain')
into temp_hier values ('EDENWI','Central','Wisconsin')
into temp_hier values ('EDGRWI','Central','Wisconsin')
into temp_hier values ('EDLSIL','Central','Illinois')
into temp_hier values ('EDMNWA','West','Washington')
select * from dual;



INSERT ALL
into temp_hier values ('EDMRMI','Midwest','North District')
into temp_hier values ('EDONOH','Central','Ohio')
into temp_hier values ('EDSNWA','West','Washington')
into temp_hier values ('EDWRMI','Midwest','Central District')
into temp_hier values ('EGHRWI','Central','Wisconsin')
into temp_hier values ('EGRVWI','Central','Wisconsin')
into temp_hier values ('EGTNOH','Central','Ohio')
into temp_hier values ('EGTNWI','Central','Wisconsin')
into temp_hier values ('EHRHSC','Southeast','South Carolina')
into temp_hier values ('EHRNAZ','West','Southwest/Mountain')
into temp_hier values ('EKHTIL','Central','Illinois')
into temp_hier values ('EKHTIN','Midwest','Central District')
into temp_hier values ('EKTNMI','Midwest','North District')
into temp_hier values ('EKVLIL','Central','Illinois')
into temp_hier values ('ELBRIN','Midwest','South District')
into temp_hier values ('ELDDIL','Central','Illinois')
into temp_hier values ('ELGNOR','West','Washington')
into temp_hier values ('ELLGIL','Central','Illinois')
into temp_hier values ('ELLKWI','Central','Wisconsin')
into temp_hier values ('ELLRSC','Southeast','South Carolina')
into temp_hier values ('ELLTIL','Central','Illinois')
into temp_hier values ('ELMROH','Central','Ohio')
into temp_hier values ('ELPSIL','Central','Illinois')
into temp_hier values ('ELRDIL','Central','Illinois')
into temp_hier values ('ELSCWA','West','Washington')
into temp_hier values ('ELSIMI','Midwest','North District')
into temp_hier values ('ELWNIL','Central','Illinois')
into temp_hier values ('ELWOIL','Central','Illinois')
into temp_hier values ('ELWOMI','Midwest','North District')
into temp_hier values ('ELYNIL','Central','Illinois')
into temp_hier values ('ELYROH','Central','Ohio')
into temp_hier values ('ELZBIL','Central','Illinois')
into temp_hier values ('ELZBIN','Midwest','South District')
into temp_hier values ('EMDNIL','Central','Illinois')
into temp_hier values ('EMIRIL','Central','Illinois')
into temp_hier values ('EMMTMI','Midwest','North District')
into temp_hier values ('EMPROR','West','Oregon')
into temp_hier values ('EMTNIL','Central','Illinois')
into temp_hier values ('EMWDIL','Central','Illinois')
into temp_hier values ('ENFDIL','Central','Illinois')
into temp_hier values ('ENGLIN','Midwest','South District')
into temp_hier values ('ENTROR','West','Washington')
into temp_hier values ('ENTTWA','West','Washington')
into temp_hier values ('ENWDOH','Central','Ohio')
into temp_hier values ('EQLTIL','Central','Illinois')
into temp_hier values ('ERCHOH','Central','Ohio')
into temp_hier values ('ERIEMI','Midwest','Central District')
into temp_hier values ('ERVLIL','Central','Illinois')
into temp_hier values ('ESCDOR','West','Oregon')
into temp_hier values ('ESNDWA','West','Washington')
into temp_hier values ('ESPTMI','Midwest','North District')
into temp_hier values ('EURKIL','Central','Illinois')
into temp_hier values ('EVPTOH','Central','Ohio')
into temp_hier values ('EVRTWA','West','Washington')
into temp_hier values ('EVSNWA','West','Washington')
into temp_hier values ('EVVLIL','Central','Illinois')
into temp_hier values ('EVVLIN','Midwest','South District')
into temp_hier values ('EWNCWA','West','Washington')
into temp_hier values ('EWNGIL','Central','Illinois')
into temp_hier values ('FDNDIN','Midwest','South District')
into temp_hier values ('FDULWI','Central','Wisconsin')
into temp_hier values ('FKLNIL','Central','Illinois')
into temp_hier values ('FKLNNC','Southeast','North Carolina')
into temp_hier values ('FLCYOH','Central','Ohio')
into temp_hier values ('FLCYWA','West','Washington')
into temp_hier values ('FLORIL','Central','Illinois')
into temp_hier values ('FLRKIL','Central','Illinois')
into temp_hier values ('FLRNOR','West','Oregon')
into temp_hier values ('FLRNSC','Southeast','South Carolina')
into temp_hier values ('FLSHOH','Central','Ohio')
into temp_hier values ('FLTNIL','Central','Illinois')
into temp_hier values ('FLTNIN','Midwest','South District')
into temp_hier values ('FLVLIL','Central','Illinois')
into temp_hier values ('FMBGIN','Midwest','South District')
into temp_hier values ('FMCYIL','Central','Illinois')
into temp_hier values ('FMLDIN','Midwest','South District')
into temp_hier values ('FNCYIN','Midwest','South District')
into temp_hier values ('FNDLWA','West','Washington')
into temp_hier values ('FNDYOH','Central','Ohio')
into temp_hier values ('FNGVIL','Central','Illinois')
into temp_hier values ('FNVLIN','Midwest','South District')
into temp_hier values ('FNVLMI','Midwest','Central District')
into temp_hier values ('FNVLNC','Southeast','North Carolina')
into temp_hier values ('FNWKMI','Midwest','North District')
into temp_hier values ('FORSOH','Central','Ohio')
into temp_hier values ('FRBGIN','Midwest','South District')
into temp_hier values ('FRBNIN','Midwest','South District')
into temp_hier values ('FRBRIL','Central','Illinois')
into temp_hier values ('FRFDIL','Central','Illinois')
into temp_hier values ('FRFDWA','West','Southwest/Mountain')
into temp_hier values ('FRFTOH','Central','Ohio')
into temp_hier values ('FRFXSC','Southeast','South Carolina')
into temp_hier values ('FRGVOR','West','Oregon')
into temp_hier values ('FRHRWA','West','Washington')
into temp_hier values ('FRKSWA','West','Washington')
into temp_hier values ('FRMTIN','Midwest','Central District')
into temp_hier values ('FRMTMI','Midwest','North District')
into temp_hier values ('FRNCIN','Midwest','South District')
into temp_hier values ('FRPRMI','Midwest','North District')
into temp_hier values ('FRPTIL','Central','Illinois')
into temp_hier values ('FRPTOH','Central','Ohio')
into temp_hier values ('FRTNIN','Midwest','South District')
into temp_hier values ('FRTNWA','West','Southwest/Mountain')
into temp_hier values ('FRTWIN','Midwest','South District')
into temp_hier values ('FRVLOH','Central','Ohio')
into temp_hier values ('FRVWMI','Midwest','North District')
into temp_hier values ('FRWLMI','Midwest','North District')
into temp_hier values ('FSHRIL','Central','Illinois')
into temp_hier values ('FSLDIL','Central','Illinois')
into temp_hier values ('FSTAOH','Central','Ohio')
into temp_hier values ('FSTNIL','Central','Illinois')
into temp_hier values ('FTBGMI','Midwest','Central District')
into temp_hier values ('FTBRIN','Midwest','South District')
into temp_hier values ('FTRCOH','Central','Ohio')
into temp_hier values ('FTTNIN','Midwest','South District')
into temp_hier values ('FTWYIN','Midwest','South District')
into temp_hier values ('FWLRIN','Midwest','South District')
into temp_hier values ('FWLRMI','Midwest','North District')
into temp_hier values ('FYTTOH','Central','Ohio')
into temp_hier values ('FYVLIL','Central','Illinois')
into temp_hier values ('GAINMI','Midwest','North District')
into temp_hier values ('GALVIL','Central','Illinois')
into temp_hier values ('GBBGOH','Central','Ohio')
into temp_hier values ('GBLSMI','Midwest','Central District')
into temp_hier values ('GDFDIL','Central','Illinois')
into temp_hier values ('GDISOR','West','Oregon')
into temp_hier values ('GDJTMI','Midwest','Central District')
into temp_hier values ('GDLSMI','Midwest','North District')
into temp_hier values ('GDRGIL','Central','Illinois')
into temp_hier values ('GDRPOH','Central','Ohio')
into temp_hier values ('GENOIL','Central','Illinois')
into temp_hier values ('GENOOH','Central','Ohio')
into temp_hier values ('GENSID','West','Southwest/Mountain')
into temp_hier values ('GERGWA','West','Washington')
into temp_hier values ('GFFRIL','Central','Illinois')
into temp_hier values ('GFTNOH','Central','Ohio')
into temp_hier values ('GGHRWA','West','Washington')
into temp_hier values ('GGVLIL','Central','Illinois')
into temp_hier values ('GLADOH','Central','Ohio')
into temp_hier values ('GLBGIL','Central','Illinois')
into temp_hier values ('GLBHOR','West','Oregon')
into temp_hier values ('GLBKNV','West','Southwest/Mountain')
into temp_hier values ('GLCNIL','Central','Illinois')
into temp_hier values ('GLDLWA','West','Washington')
into temp_hier values ('GLDNIL','Central','Illinois')
into temp_hier values ('GLINOH','Central','Ohio')
into temp_hier values ('GLNNMI','Midwest','Central District')
into temp_hier values ('GLPTIL','Central','Illinois')
into temp_hier values ('GLSTOH','Central','Ohio')
into temp_hier values ('GLTNIN','Midwest','South District')
into temp_hier values ('GLWDIN','Midwest','South District')
into temp_hier values ('GNBGIN','Midwest','South District')
into temp_hier values ('GNBNWA','West','Washington')
into temp_hier values ('GNBSWI','Central','Wisconsin')
into temp_hier values ('GNBYWI','Central','Wisconsin')
into temp_hier values ('GNCSIN','Midwest','South District')
into temp_hier values ('GNFDIL','Central','Illinois')
into temp_hier values ('GNFDOH','Central','Ohio')
into temp_hier values ('GNGSMI','Midwest','Central District')
into temp_hier values ('GNTRIL','Central','Illinois')
into temp_hier values ('GNUPIL','Central','Illinois')
into temp_hier values ('GNVLOH','Central','Ohio')
into temp_hier values ('GNWCOH','Central','Ohio')
into temp_hier values ('GNWDWI','Central','Wisconsin')
into temp_hier values ('GRCMOH','Central','Ohio')
into temp_hier values ('GRCYNC','Southeast','North Carolina')
into temp_hier values ('GRDLIL','Central','Illinois')
into temp_hier values ('GRDVNV','West','Southwest/Mountain')
into temp_hier values ('GRFDWA','West','Southwest/Mountain')
into temp_hier values ('GRFKIN','Midwest','South District')
into temp_hier values ('GRFLWA','West','Washington')
into temp_hier values ('GRGRMI','Midwest','Central District')
into temp_hier values ('GRHMOR','West','Oregon')
into temp_hier values ('GRHRMI','Midwest','North District')
into temp_hier values ('GRLDMI','Midwest','North District')
into temp_hier values ('GRLDWA','West','Washington')
into temp_hier values ('GRLKMI','Midwest','Central District')
into temp_hier values ('GRPRIL','Central','Illinois')
into temp_hier values ('GRRDIL','Central','Illinois')
into temp_hier values ('GRRTIN','Midwest','Central District')
into temp_hier values ('GRSPOH','Central','Ohio')
into temp_hier values ('GRTSOH','Central','Ohio')
into temp_hier values ('GRTWIN','Midwest','South District')
into temp_hier values ('GRTWOH','Central','Ohio')
into temp_hier values ('GRTWSC','Southeast','South Carolina')
into temp_hier values ('GRVIIL','Central','Illinois')
into temp_hier values ('GRVLIL','Central','Illinois')
into temp_hier values ('GRVLOH','Central','Ohio')
into temp_hier values ('GRVYIL','Central','Illinois')
into temp_hier values ('GRYLMI','Midwest','North District')
into temp_hier values ('GSCKNC','Southeast','North Carolina')
into temp_hier values ('GSHNIN','Midwest','Central District')
into temp_hier values ('GSQTCA','West','Oregon')
into temp_hier values ('GSTNOR','West','Oregon')
into temp_hier values ('GTTWNC','Southeast','North Carolina')
into temp_hier values ('GUVLOH','Central','Ohio')
into temp_hier values ('GVLDIL','Central','Illinois')
into temp_hier values ('GVRSNV','West','Southwest/Mountain')
into temp_hier values ('GWPRNC','Southeast','North Carolina')
into temp_hier values ('GYLRMI','Midwest','North District')
into temp_hier values ('GYVLIL','Central','Illinois')
into temp_hier values ('GYVLIN','Midwest','South District')
into temp_hier values ('HANNIN','Midwest','Central District')
into temp_hier values ('HARTMI','Midwest','North District')
into temp_hier values ('HAVLIL','Central','Illinois')
into temp_hier values ('HBLKMI','Midwest','North District')
into temp_hier values ('HBRNIL','Central','Illinois')
into temp_hier values ('HBRTIN','Midwest','Central District')
into temp_hier values ('HBTNMI','Midwest','North District')
into temp_hier values ('HCKRIL','Central','Illinois')
into temp_hier values ('HCVLOH','Central','Ohio')
into temp_hier values ('HDLDOR','West','Oregon')
into temp_hier values ('HDRVOR','West','Oregon')
into temp_hier values ('HDSNIL','Central','Illinois')
into temp_hier values ('HDSNMI','Midwest','Central District')
into temp_hier values ('HEVLIN','Midwest','South District')
into temp_hier values ('HGBGIN','Midwest','South District')
into temp_hier values ('HGLDIL','Central','Illinois')
into temp_hier values ('HGLKMI','Midwest','North District')
into temp_hier values ('HGLNNC','Southeast','North Carolina')
into temp_hier values ('HGPTMI','Midwest','North District')
into temp_hier values ('HGPTOH','Central','Ohio')
into temp_hier values ('HGTWIN','Midwest','South District')
into temp_hier values ('HHLKMI','Midwest','North District')
into temp_hier values ('HICHCA','West','Oregon')
into temp_hier values ('HLBONC','Southeast','North Carolina')
into temp_hier values ('HLBOOR','West','Oregon')
into temp_hier values ('HLBRWI','Central','Wisconsin')
into temp_hier values ('HLLDIN','Midwest','South District')
into temp_hier values ('HLLKWA','West','Washington')
into temp_hier values ('HLMNMI','Midwest','North District')
into temp_hier values ('HLNAOH','Central','Ohio')
into temp_hier values ('HLTNMI','Midwest','North District')
into temp_hier values ('HLVWIL','Central','Illinois')
into temp_hier values ('HLWDSC','Southeast','South Carolina')
into temp_hier values ('HMBRNC','Southeast','North Carolina')
into temp_hier values ('HMLCMI','Midwest','North District')
into temp_hier values ('HMNDIL','Central','Illinois')
into temp_hier values ('HMNGSC','Southeast','South Carolina')
into temp_hier values ('HMTNIL','Central','Illinois')
into temp_hier values ('HMTNIN','Midwest','Central District')
into temp_hier values ('HMTNMI','Midwest','Central District')
into temp_hier values ('HMTNWA','West','Washington')
into temp_hier values ('HMVIOH','Central','Ohio')
into temp_hier values ('HNCKIL','Central','Illinois')
into temp_hier values ('HNNGIL','Central','Illinois')
into temp_hier values ('HNPNIL','Central','Illinois')
into temp_hier values ('HNRYIL','Central','Illinois')
into temp_hier values ('HNTNIN','Midwest','Central District')
into temp_hier values ('HNTWIN','Midwest','South District')
into temp_hier values ('HNVRIL','Central','Illinois')
into temp_hier values ('HNVRIN','Midwest','South District')
into temp_hier values ('HODLWI','Central','Wisconsin')
into temp_hier values ('HOMRIL','Central','Illinois')
into temp_hier values ('HOMRMI','Midwest','Central District')
into temp_hier values ('HOPEID','West','Southwest/Mountain')
into temp_hier values ('HPDLIL','Central','Illinois')
into temp_hier values ('HPNROR','West','Oregon')
into temp_hier values ('HPTNIL','Central','Illinois')
into temp_hier values ('HRBGIL','Central','Illinois')
into temp_hier values ('HRBHMI','Midwest','North District')
into temp_hier values ('HRFRMI','Midwest','Central District')
into temp_hier values ('HRLNIN','Midwest','Central District')
into temp_hier values ('HRPSOH','Central','Ohio')
into temp_hier values ('HRRNIL','Central','Illinois')
into temp_hier values ('HRSNID','West','Southwest/Mountain')
into temp_hier values ('HRSNMI','Midwest','North District')
into temp_hier values ('HRSPOH','Central','Ohio')
into temp_hier values ('HRSTIL','Central','Illinois')
into temp_hier values ('HRVLMI','Midwest','North District')
into temp_hier values ('HSFDWI','Central','Wisconsin')
into temp_hier values ('HSKNOH','Central','Ohio')
into temp_hier values ('HSPRMI','Midwest','North District')
into temp_hier values ('HSVLOH','Central','Ohio')
into temp_hier values ('HTBGIL','Central','Illinois')
into temp_hier values ('HTLYWI','Central','Wisconsin')
into temp_hier values ('HTSPNC','Southeast','North Carolina')
into temp_hier values ('HTSVIL','Central','Illinois')
into temp_hier values ('HULLIL','Central','Illinois')
into temp_hier values ('HURNOH','Central','Ohio')
into temp_hier values ('HVSUCA','West','Southwest/Mountain')
into temp_hier values ('HVTNOH','Central','Ohio')
into temp_hier values ('HWCYMI','Midwest','North District')
into temp_hier values ('HYLKID','West','Southwest/Mountain')
into temp_hier values ('HYMRIN','Midwest','South District')
into temp_hier values ('HYVLIN','Midwest','South District')
into temp_hier values ('HYVLNC','Southeast','North Carolina')
into temp_hier values ('HYVLOH','Central','Ohio')
into temp_hier values ('HYWOIL','Central','Illinois')
into temp_hier values ('HZTNIN','Midwest','South District')
into temp_hier values ('IDA MI','Midwest','Central District')
into temp_hier values ('IDAHOH','Central','Ohio')
into temp_hier values ('IDVLIN','Midwest','South District')
into temp_hier values ('ILPLIL','Central','Illinois')
into temp_hier values ('IMBLOR','West','Washington')
into temp_hier values ('IMCYMI','Midwest','North District')
into temp_hier values ('IMNHOR','West','Washington')
into temp_hier values ('IONEWA','West','Washington')
into temp_hier values ('IRTNOH','Central','Ohio')
into temp_hier values ('ITHCMI','Midwest','North District')
into temp_hier values ('ITHCWI','Central','Wisconsin')
into temp_hier values ('IVDLIL','Central','Illinois')
into temp_hier values ('JCPTWI','Central','Wisconsin')
into temp_hier values ('JCSNOH','Central','Ohio')
into temp_hier values ('JCSNSC','Southeast','South Carolina')
into temp_hier values ('JCVLIL','Central','Illinois')
into temp_hier values ('JDDOMI','Midwest','North District')
into temp_hier values ('JENROH','Central','Ohio')
into temp_hier values ('JHBGWI','Central','Wisconsin')
into temp_hier values ('JHCYIL','Central','Illinois')
into temp_hier values ('JHDYOR','West','Oregon')
into temp_hier values ('JKVYNV','West','Southwest/Mountain')
into temp_hier values ('JOPPIL','Central','Illinois')
into temp_hier values ('JSPHOR','West','Washington')
into temp_hier values ('JSPRIN','Midwest','South District')
into temp_hier values ('JSVLSC','Southeast','South Carolina')
into temp_hier values ('JUNTWA','West','Washington')
into temp_hier values ('JWTTOH','Central','Ohio')
into temp_hier values ('KDVLIN','Midwest','South District')
into temp_hier values ('KENTOH','Central','Ohio')
into temp_hier values ('KEWNIL','Central','Illinois')
into temp_hier values ('KGTNMI','Midwest','North District')
into temp_hier values ('KGTNWA','West','Washington')
into temp_hier values ('KGTRSC','Southeast','South Carolina')
into temp_hier values ('KIELWI','Central','Wisconsin')
into temp_hier values ('KLBROH','Central','Ohio')
into temp_hier values ('KLFLOR','West','Oregon')
into temp_hier values ('KLISOH','Central','Ohio')
into temp_hier values ('KLLGID','West','Southwest/Mountain')
into temp_hier values ('KLMTCA','West','Oregon')
into temp_hier values ('KMMLIN','Midwest','Central District')
into temp_hier values ('KNLDIN','Midwest','South District')
into temp_hier values ('KNNYIL','Central','Illinois')
into temp_hier values ('KNSSIL','Central','Illinois')
into temp_hier values ('KNVLOH','Central','Ohio')
into temp_hier values ('KNWCWA','West','Washington')
into temp_hier values ('KOTSIN','Midwest','Central District')
into temp_hier values ('KRLDIL','Central','Illinois')
into temp_hier values ('KRLDWA','West','Washington')
into temp_hier values ('KRNKIL','Central','Illinois')
into temp_hier values ('KSHNWI','Central','Wisconsin')
into temp_hier values ('KWSKWI','Central','Wisconsin')
into temp_hier values ('LACNIN','Midwest','South District')
into temp_hier values ('LACNWA','West','Washington')
into temp_hier values ('LACRIN','Midwest','Central District')
into temp_hier values ('LADDIL','Central','Illinois')
into temp_hier values ('LAGRIN','Midwest','South District')
into temp_hier values ('LAGROR','West','Washington')
into temp_hier values ('LAMLIL','Central','Illinois')
into temp_hier values ('LAMRSC','Southeast','South Carolina')
into temp_hier values ('LAPLIL','Central','Illinois')
into temp_hier values ('LAPTIN','Midwest','Central District')
into temp_hier values ('LARLIN','Midwest','South District')
into temp_hier values ('LARLWA','West','Washington')
into temp_hier values ('LARSIL','Central','Illinois')
into temp_hier values ('LARUOH','Central','Ohio')
into temp_hier values ('LATHWA','West','Southwest/Mountain')
into temp_hier values ('LAUROH','Central','Ohio')
into temp_hier values ('LAVLOH','Central','Ohio')
into temp_hier values ('LBNNWI','Central','Wisconsin')
into temp_hier values ('LBRTIN','Midwest','South District')
into temp_hier values ('LBRTOH','Central','Ohio')
into temp_hier values ('LCHNMI','Midwest','North District')
into temp_hier values ('LCRNIN','Midwest','South District')
into temp_hier values ('LCRSWI','Central','Wisconsin')
into temp_hier values ('LCTAMI','Midwest','Central District')
into temp_hier values ('LDLWIL','Central','Illinois')
into temp_hier values ('LDNGMI','Midwest','North District')
into temp_hier values ('LDRYOH','Central','Ohio')
into temp_hier values ('LDUFWI','Central','Wisconsin')
into temp_hier values ('LDVLOH','Central','Ohio')
into temp_hier values ('LELDIL','Central','Illinois')
into temp_hier values ('LENAIL','Central','Illinois')
into temp_hier values ('LENRIL','Central','Illinois')
into temp_hier values ('LEO IN','Midwest','Central District')
into temp_hier values ('LEWSIN','Midwest','South District')
into temp_hier values ('LFYTIN','Midwest','South District')
into temp_hier values ('LGNRIN','Midwest','Central District')
into temp_hier values ('LGPNIL','Central','Illinois')
into temp_hier values ('LGPTIN','Midwest','South District')
into temp_hier values ('LGRNIN','Midwest','Central District')
into temp_hier values ('LGVLWI','Central','Wisconsin')
into temp_hier values ('LHRPIL','Central','Illinois')
into temp_hier values ('LIMAOH','Central','Ohio')
into temp_hier values ('LKCYSC','Southeast','South Carolina')
into temp_hier values ('LKGWWA','West','Washington')
into temp_hier values ('LKMLWI','Central','Wisconsin')
into temp_hier values ('LKOSOR','West','Oregon')
into temp_hier values ('LKSDOR','West','Oregon')
into temp_hier values ('LKSTIN','Midwest','Central District')
into temp_hier values ('LKSTWA','West','Washington')
into temp_hier values ('LKTMWI','Central','Wisconsin')
into temp_hier values ('LKVLOH','Central','Ohio')
into temp_hier values ('LKVWMI','Midwest','North District')
into temp_hier values ('LKWDSC','Southeast','South Carolina')
into temp_hier values ('LKWDWI','Central','Wisconsin')
into temp_hier values ('LKWNWA','West','Washington')
into temp_hier values ('LLALMI','Midwest','North District')
into temp_hier values ('LLVLNC','Southeast','North Carolina')
into temp_hier values ('LMRGWI','Central','Wisconsin')
into temp_hier values ('LMVLMI','Central','Ohio')
into temp_hier values ('LNBGMI','Midwest','North District')
into temp_hier values ('LNBHCA','West','Southwest/Mountain')
into temp_hier values ('LNCLIL','Central','Illinois')
into temp_hier values ('LNCLMI','Midwest','North District')
into temp_hier values ('LNCSOH','Central','Ohio')
into temp_hier values ('LNDNMI','Midwest','North District')
into temp_hier values ('LNDSWI','Central','Wisconsin')
into temp_hier values ('LNGLOR','West','Oregon')
into temp_hier values ('LNLKWI','Central','Wisconsin')
into temp_hier values ('LNRKIL','Central','Illinois')
into temp_hier values ('LNRKWI','Central','Wisconsin')
into temp_hier values ('LNVLIN','Midwest','South District')
into temp_hier values ('LOAMIL','Central','Illinois')
into temp_hier values ('LODAIL','Central','Illinois')
into temp_hier values ('LODIOH','Central','Ohio')
into temp_hier values ('LODIWI','Central','Wisconsin')
into temp_hier values ('LOGNOH','Central','Ohio')
into temp_hier values ('LOGTIN','Midwest','South District')
into temp_hier values ('LOMRWI','Central','Wisconsin')
into temp_hier values ('LOMSWA','West','Washington')
into temp_hier values ('LOPZWA','West','Washington')
into temp_hier values ('LORISC','Southeast','South Carolina')
into temp_hier values ('LORNOH','Central','Ohio')
into temp_hier values ('LOSTOR','West','Washington')
into temp_hier values ('LOYLWI','Central','Wisconsin')
into temp_hier values ('LPSCOH','Central','Ohio')
into temp_hier values ('LPTNMI','Midwest','North District')
into temp_hier values ('LRNSSC','Southeast','South Carolina')
into temp_hier values ('LROYIL','Central','Illinois')
into temp_hier values ('LRVLIL','Central','Illinois')
into temp_hier values ('LSBGOH','Central','Ohio')
into temp_hier values ('LSLKCA','West','Southwest/Mountain')
into temp_hier values ('LSPNMI','Midwest','Central District')
into temp_hier values ('LSTNIL','Central','Illinois')
into temp_hier values ('LSTNMI','Midwest','North District')
into temp_hier values ('LSVLIL','Central','Illinois')
into temp_hier values ('LTFLOH','Central','Ohio')
into temp_hier values ('LTRBIL','Central','Illinois')
into temp_hier values ('LUVLOH','Central','Ohio')
into temp_hier values ('LVWOIN','Midwest','South District')
into temp_hier values ('LVWOWA','West','Washington')
into temp_hier values ('LWBGOH','Central','Ohio')
into temp_hier values ('LWLLOH','Central','Ohio')
into temp_hier values ('LWRNMI','Midwest','Central District')
into temp_hier values ('LWSLOH','Central','Ohio')
select * from dual;


INSERT ALL
into temp_hier values ('LWTNMI','Midwest','Central District')
into temp_hier values ('LXTNIL','Central','Illinois')
into temp_hier values ('LXTNIN','Midwest','South District')
into temp_hier values ('LYBGOH','Central','Ohio')
into temp_hier values ('LYNDWA','West','Washington')
into temp_hier values ('LYNNIN','Midwest','South District')
into temp_hier values ('LYSTWI','Central','Wisconsin')
into temp_hier values ('LYVLIN','Midwest','South District')
into temp_hier values ('MACNIL','Central','Illinois')
into temp_hier values ('MACYIN','Midwest','South District')
into temp_hier values ('MALTIL','Central','Illinois')
into temp_hier values ('MAPKIL','Central','Illinois')
into temp_hier values ('MARNIL','Central','Illinois')
into temp_hier values ('MARNNC','Southeast','North Carolina')
into temp_hier values ('MARNOH','Central','Ohio')
into temp_hier values ('MAROIL','Central','Illinois')
into temp_hier values ('MAUNIL','Central','Illinois')
into temp_hier values ('MAYSIN','Midwest','South District')
into temp_hier values ('MCAROH','Central','Ohio')
into temp_hier values ('MCBBIN','Midwest','South District')
into temp_hier values ('MCBGOH','Central','Ohio')
into temp_hier values ('MCBHIN','Midwest','South District')
into temp_hier values ('MCBOIL','Central','Illinois')
into temp_hier values ('MCBRMI','Midwest','North District')
into temp_hier values ('MCCMOH','Central','Ohio')
into temp_hier values ('MCCNIL','Central','Illinois')
into temp_hier values ('MCCRSC','Southeast','South Carolina')
into temp_hier values ('MCCYIN','Midwest','Central District')
into temp_hier values ('MCFAWI','Central','Wisconsin')
into temp_hier values ('MCKNIL','Central','Illinois')
into temp_hier values ('MCKYIN','Midwest','South District')
into temp_hier values ('MCLNIL','Central','Illinois')
into temp_hier values ('MCMBIL','Central','Illinois')
into temp_hier values ('MCTWOH','Central','Ohio')
into temp_hier values ('MDFDWI','Central','Wisconsin')
into temp_hier values ('MDLBIN','Midwest','Central District')
into temp_hier values ('MDSNIN','Midwest','South District')
into temp_hier values ('MDSNWI','Central','Wisconsin')
into temp_hier values ('MDTNMI','Midwest','North District')
into temp_hier values ('MEDNOH','Central','Ohio')
into temp_hier values ('MEDRIN','Midwest','South District')
into temp_hier values ('MERMIN','Midwest','South District')
into temp_hier values ('MGNLIL','Central','Illinois')
into temp_hier values ('MHMTIL','Central','Illinois')
into temp_hier values ('MHVLNC','Southeast','North Carolina')
into temp_hier values ('MILNIN','Midwest','South District')
into temp_hier values ('MILNOH','Central','Ohio')
into temp_hier values ('MILWWI','Central','Wisconsin')
into temp_hier values ('MINRIL','Central','Illinois')
into temp_hier values ('MIO MI','Midwest','North District')
into temp_hier values ('MIVLNC','Southeast','North Carolina')
into temp_hier values ('MKLTWA','West','Washington')
into temp_hier values ('MLBYIN','Midwest','South District')
into temp_hier values ('MLCYOR','West','Oregon')
into temp_hier values ('MLDNWA','West','Southwest/Mountain')
into temp_hier values ('MLFRIL','Central','Illinois')
into temp_hier values ('MLFRMI','Midwest','North District')
into temp_hier values ('MLLLOR','West','Oregon')
into temp_hier values ('MLLNID','West','Southwest/Mountain')
into temp_hier values ('MLPTOH','Central','Ohio')
into temp_hier values ('MLRYIN','Midwest','South District')
into temp_hier values ('MLSNWA','West','Washington')
into temp_hier values ('MLSTIL','Central','Illinois')
into temp_hier values ('MLTNIL','Central','Illinois')
into temp_hier values ('MLTWIN','Midwest','South District')
into temp_hier values ('MLVNIL','Central','Illinois')
into temp_hier values ('MLVROH','Central','Ohio')
into temp_hier values ('MLWDIN','Midwest','South District')
into temp_hier values ('MLWKOR','West','Oregon')
into temp_hier values ('MMPHMI','Midwest','North District')
into temp_hier values ('MMVLOR','West','Oregon')
into temp_hier values ('MNCAOH','Central','Ohio')
into temp_hier values ('MNCHIL','Central','Illinois')
into temp_hier values ('MNCQWI','Central','Wisconsin')
into temp_hier values ('MNCTIL','Central','Illinois')
into temp_hier values ('MNCTWI','Central','Wisconsin')
into temp_hier values ('MNCYIN','Midwest','South District')
into temp_hier values ('MNCYMI','Midwest','North District')
into temp_hier values ('MNCYOH','Central','Ohio')
into temp_hier values ('MNDNIL','Central','Illinois')
into temp_hier values ('MNDNMI','Midwest','Central District')
into temp_hier values ('MNDNOH','Central','Ohio')
into temp_hier values ('MNDTIL','Central','Illinois')
into temp_hier values ('MNFDIL','Central','Illinois')
into temp_hier values ('MNFDOH','Central','Ohio')
into temp_hier values ('MNFDWA','West','Washington')
into temp_hier values ('MNFROH','Central','Ohio')
into temp_hier values ('MNLSIL','Central','Illinois')
into temp_hier values ('MNMOIL','Central','Illinois')
into temp_hier values ('MNNGSC','Southeast','South Carolina')
into temp_hier values ('MNNKIL','Central','Illinois')
into temp_hier values ('MNPLMI','Midwest','North District')
into temp_hier values ('MNPTWI','Central','Wisconsin')
into temp_hier values ('MNRLIL','Central','Illinois')
into temp_hier values ('MNRVOH','Central','Ohio')
into temp_hier values ('MNSNWA','West','Washington')
into temp_hier values ('MNSTOH','Central','Ohio')
into temp_hier values ('MNTCCA','West','Southwest/Mountain')
into temp_hier values ('MNTHMI','Midwest','Central District')
into temp_hier values ('MNTIIL','Central','Illinois')
into temp_hier values ('MNTNIN','Midwest','South District')
into temp_hier values ('MNTWWI','Central','Wisconsin')
into temp_hier values ('MODCIN','Midwest','South District')
into temp_hier values ('MONRIN','Midwest','South District')
into temp_hier values ('MONRNC','Southeast','North Carolina')
into temp_hier values ('MONRWA','West','Washington')
into temp_hier values ('MOSNWI','Central','Wisconsin')
into temp_hier values ('MOVLIN','Midwest','South District')
into temp_hier values ('MOVLOH','Central','Ohio')
into temp_hier values ('MPFLWA','West','Washington')
into temp_hier values ('MPRPMI','Midwest','North District')
into temp_hier values ('MPTNWI','Central','Wisconsin')
into temp_hier values ('MRBLOH','Central','Ohio')
into temp_hier values ('MRBLWA','West','Washington')
into temp_hier values ('MRBOIL','Central','Illinois')
into temp_hier values ('MRCLMI','Midwest','Central District')
into temp_hier values ('MRDSIL','Central','Illinois')
into temp_hier values ('MRFDWI','Central','Wisconsin')
into temp_hier values ('MRHLNC','Southeast','North Carolina')
into temp_hier values ('MRINSC','Southeast','South Carolina')
into temp_hier values ('MRKLIN','Midwest','South District')
into temp_hier values ('MRLDIN','Midwest','South District')
into temp_hier values ('MRMCWI','Central','Wisconsin')
into temp_hier values ('MRNCMI','Midwest','Central District')
into temp_hier values ('MRNGIN','Midwest','South District')
into temp_hier values ('MRNSOH','Central','Ohio')
into temp_hier values ('MRPHNC','Southeast','North Carolina')
into temp_hier values ('MRPHOR','West','Oregon')
into temp_hier values ('MRRLMI','Midwest','North District')
into temp_hier values ('MRRLOH','Central','Ohio')
into temp_hier values ('MRRLWI','Central','Wisconsin')
into temp_hier values ('MRSHIL','Central','Illinois')
into temp_hier values ('MRSHNC','Southeast','North Carolina')
into temp_hier values ('MRSHWI','Central','Wisconsin')
into temp_hier values ('MRSSIL','Central','Illinois')
into temp_hier values ('MRSTOH','Central','Ohio')
into temp_hier values ('MRTHWI','Central','Wisconsin')
into temp_hier values ('MRTNIL','Central','Illinois')
into temp_hier values ('MRTNIN','Midwest','South District')
into temp_hier values ('MRTWIN','Midwest','South District')
into temp_hier values ('MRTWOH','Central','Ohio')
into temp_hier values ('MRWYWA','West','Washington')
into temp_hier values ('MSBCIL','Central','Illinois')
into temp_hier values ('MSCTIL','Central','Illinois')
into temp_hier values ('MSCWID','West','Southwest/Mountain')
into temp_hier values ('MSHCWI','Central','Wisconsin')
into temp_hier values ('MSKGMI','Midwest','North District')
into temp_hier values ('MSKHMI','Midwest','North District')
into temp_hier values ('MSLKWA','West','Washington')
into temp_hier values ('MSTNWI','Central','Wisconsin')
into temp_hier values ('MSVLIL','Central','Illinois')
into temp_hier values ('MTANOR','West','Oregon')
into temp_hier values ('MTBLOH','Central','Ohio')
into temp_hier values ('MTCAIL','Central','Illinois')
into temp_hier values ('MTCFIL','Central','Illinois')
into temp_hier values ('MTCHIN','Midwest','South District')
into temp_hier values ('MTCLWI','Central','Wisconsin')
into temp_hier values ('MTCRIL','Central','Illinois')
into temp_hier values ('MTFLWA','West','Washington')
into temp_hier values ('MTHWNC','Southeast','North Carolina')
into temp_hier values ('MTLLWI','Central','Wisconsin')
into temp_hier values ('MTMOMI','Midwest','North District')
into temp_hier values ('MTMRIL','Central','Illinois')
into temp_hier values ('MTONWI','Central','Wisconsin')
into temp_hier values ('MTOROH','Central','Ohio')
into temp_hier values ('MTPLOH','Central','Ohio')
into temp_hier values ('MTRPIL','Central','Illinois')
into temp_hier values ('MTRSOH','Central','Ohio')
into temp_hier values ('MTSTIL','Central','Illinois')
into temp_hier values ('MTTNIL','Central','Illinois')
into temp_hier values ('MTVIIL','Central','Illinois')
into temp_hier values ('MTVIOH','Central','Ohio')
into temp_hier values ('MTVROH','Central','Ohio')
into temp_hier values ('MTVRWA','West','Washington')
into temp_hier values ('MTWNMI','Midwest','Central District')
into temp_hier values ('MTZNIL','Central','Illinois')
into temp_hier values ('MUIRMI','Midwest','North District')
into temp_hier values ('MUVLIL','Central','Illinois')
into temp_hier values ('MWTWOH','Central','Ohio')
into temp_hier values ('MYBEMI','Midwest','Central District')
into temp_hier values ('MYBHSC','Southeast','South Carolina')
into temp_hier values ('MYPNOR','West','Oregon')
into temp_hier values ('MYVIOH','Central','Ohio')
into temp_hier values ('MYVIWA','West','Washington')
into temp_hier values ('NAUVIL','Central','Illinois')
into temp_hier values ('NBLNOH','Central','Ohio')
into temp_hier values ('NBLTOH','Central','Ohio')
into temp_hier values ('NBNDOR','West','Oregon')
into temp_hier values ('NBNDWA','West','Washington')
into temp_hier values ('NBRNMI','Midwest','North District')
into temp_hier values ('NBTNOH','Central','Ohio')
into temp_hier values ('NBVLIN','Midwest','South District')
into temp_hier values ('NCHSWA','West','Washington')
into temp_hier values ('NCTNIL','Central','Illinois')
into temp_hier values ('NEOGIL','Central','Illinois')
into temp_hier values ('NESHWI','Central','Wisconsin')
into temp_hier values ('NETNOH','Central','Ohio')
into temp_hier values ('NEVDOH','Central','Ohio')
into temp_hier values ('NEY OH','Central','Ohio')
into temp_hier values ('NFFDOH','Central','Ohio')
into temp_hier values ('NGTWOH','Central','Ohio')
into temp_hier values ('NHLDIL','Central','Illinois')
into temp_hier values ('NILEWA','West','Washington')
into temp_hier values ('NINTIL','Central','Illinois')
into temp_hier values ('NJSNIN','Midwest','Central District')
into temp_hier values ('NLVLOH','Central','Ohio')
into temp_hier values ('NMCHIN','Midwest','South District')
into temp_hier values ('NMFRIL','Central','Illinois')
into temp_hier values ('NOBLIL','Central','Illinois')
into temp_hier values ('NPLNOH','Central','Ohio')
into temp_hier values ('NPLNOR','West','Oregon')
into temp_hier values ('NPNSIL','Central','Illinois')
into temp_hier values ('NRCYIL','Central','Illinois')
into temp_hier values ('NRMLIL','Central','Illinois')
into temp_hier values ('NRSHMI','Midwest','North District')
into temp_hier values ('NRWLOH','Central','Ohio')
into temp_hier values ('NSMTSC','Southeast','South Carolina')
into temp_hier values ('NSPLWA','West','Washington')
into temp_hier values ('NSTROH','Central','Ohio')
into temp_hier values ('NVRNIN','Midwest','South District')
into temp_hier values ('NWALIN','Midwest','South District')
into temp_hier values ('NWBDIL','Central','Illinois')
into temp_hier values ('NWBLIL','Central','Illinois')
into temp_hier values ('NWBMOH','Central','Ohio')
into temp_hier values ('NWBROR','West','Oregon')
into temp_hier values ('NWCNOH','Central','Ohio')
into temp_hier values ('NWHLWI','Central','Wisconsin')
into temp_hier values ('NWHNIL','Central','Illinois')
into temp_hier values ('NWHNIN','Midwest','South District')
into temp_hier values ('NWKNOH','Central','Ohio')
into temp_hier values ('NWLBOH','Central','Ohio')
into temp_hier values ('NWLNOH','Central','Ohio')
into temp_hier values ('NWMLIN','Midwest','South District')
into temp_hier values ('NWMNIL','Central','Illinois')
into temp_hier values ('NWMROH','Central','Ohio')
into temp_hier values ('NWPHOH','Central','Ohio')
into temp_hier values ('NWPRIN','Midwest','Central District')
into temp_hier values ('NWPTWA','West','Southwest/Mountain')
into temp_hier values ('NWTNIL','Central','Illinois')
into temp_hier values ('NWTNOH','Central','Ohio')
into temp_hier values ('NWVNOH','Central','Ohio')
into temp_hier values ('OBLNIL','Central','Illinois')
into temp_hier values ('OBRLOH','Central','Ohio')
into temp_hier values ('ODBHSC','Southeast','South Carolina')
into temp_hier values ('ODLLIL','Central','Illinois')
into temp_hier values ('ODONIN','Midwest','South District')
into temp_hier values ('OGDNIL','Central','Illinois')
into temp_hier values ('OGVLIL','Central','Illinois')
into temp_hier values ('OHCYOH','Central','Ohio')
into temp_hier values ('OHIOIL','Central','Illinois')
into temp_hier values ('OKCYIN','Midwest','South District')
into temp_hier values ('OKDLWA','West','Southwest/Mountain')
into temp_hier values ('OKFDWI','Central','Wisconsin')
into temp_hier values ('OKHLOH','Central','Ohio')
into temp_hier values ('OKHROH','Central','Ohio')
into temp_hier values ('OKHRWA','West','Washington')
into temp_hier values ('OKTWIN','Midwest','South District')
into temp_hier values ('OKVLIL','Central','Illinois')
into temp_hier values ('OLARSC','Southeast','South Carolina')
into temp_hier values ('OLFTNC','Southeast','North Carolina')
into temp_hier values ('OLNTSC','Southeast','South Carolina')
into temp_hier values ('OLNYIL','Central','Illinois')
into temp_hier values ('OLWSOH','Central','Ohio')
into temp_hier values ('OMAHIL','Central','Illinois')
into temp_hier values ('OMAKWA','West','Washington')
into temp_hier values ('ONDGMI','Midwest','Central District')
into temp_hier values ('ONSTMI','Midwest','Central District')
into temp_hier values ('ONTRCA','West','Southwest/Mountain')
into temp_hier values ('ONWYMI','Midwest','North District')
into temp_hier values ('ORCHWA','West','Washington')
into temp_hier values ('ORENIL','Central','Illinois')
into temp_hier values ('ORFNID','West','Southwest/Mountain')
into temp_hier values ('ORGNIL','Central','Illinois')
into temp_hier values ('ORGNWI','Central','Wisconsin')
into temp_hier values ('ORICCA','West','Oregon')
into temp_hier values ('ORLDIN','Midwest','Central District')
into temp_hier values ('ORLNIN','Midwest','South District')
into temp_hier values ('ORNTOR','West','Oregon')
into temp_hier values ('ORVLMI','Midwest','North District')
into temp_hier values ('ORVLWA','West','Washington')
into temp_hier values ('ORVLWI','Central','Wisconsin')
into temp_hier values ('OSBGWI','Central','Wisconsin')
into temp_hier values ('OSCLIN','Midwest','Central District')
into temp_hier values ('OSNKMI','Midwest','North District')
into temp_hier values ('OSSIIN','Midwest','South District')
into temp_hier values ('OSTROH','Central','Ohio')
into temp_hier values ('OTVLMI','Midwest','North District')
into temp_hier values ('OTWYOH','Central','Ohio')
into temp_hier values ('OVIDMI','Midwest','North District')
into temp_hier values ('OWENWI','Central','Wisconsin')
into temp_hier values ('OWSOMI','Midwest','North District')
into temp_hier values ('OWVLIN','Midwest','South District')
into temp_hier values ('OXFROH','Central','Ohio')
into temp_hier values ('PALOMI','Midwest','North District')
into temp_hier values ('PALSWA','West','Southwest/Mountain')
into temp_hier values ('PAOLIN','Midwest','South District')
into temp_hier values ('PARMMI','Midwest','Central District')
into temp_hier values ('PARSIL','Central','Illinois')
into temp_hier values ('PARSOH','Central','Ohio')
into temp_hier values ('PASCWA','West','Washington')
into temp_hier values ('PASNIL','Central','Illinois')
into temp_hier values ('PATKIN','Midwest','South District')
into temp_hier values ('PAWNIL','Central','Illinois')
into temp_hier values ('PAYNOH','Central','Ohio')
into temp_hier values ('PBLSOH','Central','Ohio')
into temp_hier values ('PCCYOR','West','Oregon')
into temp_hier values ('PCKRWI','Central','Wisconsin')
into temp_hier values ('PCTNIL','Central','Illinois')
into temp_hier values ('PCTNOH','Central','Ohio')
into temp_hier values ('PDUCWI','Central','Wisconsin')
into temp_hier values ('PDVLMI','Midwest','North District')
into temp_hier values ('PDVLWI','Central','Wisconsin')
into temp_hier values ('PECKID','West','Southwest/Mountain')
into temp_hier values ('PEORIL','Central','Illinois')
into temp_hier values ('PERCIL','Central','Illinois')
into temp_hier values ('PERLIL','Central','Illinois')
into temp_hier values ('PGLDSC','Southeast','South Carolina')
into temp_hier values ('PHBGOH','Central','Ohio')
into temp_hier values ('PHILIL','Central','Illinois')
into temp_hier values ('PHLSWI','Central','Wisconsin')
into temp_hier values ('PINROH','Central','Ohio')
into temp_hier values ('PIRCID','West','Southwest/Mountain')
into temp_hier values ('PKGNIN','Midwest','Central District')
into temp_hier values ('PKTNOH','Central','Ohio')
into temp_hier values ('PKVLIN','Midwest','South District')
into temp_hier values ('PLANIL','Central','Illinois')
into temp_hier values ('PLANWI','Central','Wisconsin')
into temp_hier values ('PLCYIL','Central','Illinois')
into temp_hier values ('PLHLIL','Central','Illinois')
into temp_hier values ('PLLKIN','Midwest','Central District')
into temp_hier values ('PLMNMI','Midwest','Central District')
into temp_hier values ('PLMNWA','West','Southwest/Mountain')
into temp_hier values ('PLMOIN','Midwest','Central District')
into temp_hier values ('PLMOOH','Central','Ohio')
into temp_hier values ('PLMOWI','Central','Wisconsin')
into temp_hier values ('PLMRID','West','Southwest/Mountain')
into temp_hier values ('PLMYIL','Central','Illinois')
into temp_hier values ('PLMYIN','Midwest','South District')
into temp_hier values ('PLPLIL','Central','Illinois')
into temp_hier values ('PLSBWA','West','Washington')
into temp_hier values ('PLSTIL','Central','Illinois')
into temp_hier values ('PLTNIL','Central','Illinois')
into temp_hier values ('PLVRCA','West','Southwest/Mountain')
into temp_hier values ('PLWDOH','Central','Ohio')
into temp_hier values ('PMPLSC','Southeast','South Carolina')
into temp_hier values ('PMRYOH','Central','Ohio')
into temp_hier values ('PMVLOH','Central','Ohio')
into temp_hier values ('PNCYOH','Central','Ohio')
into temp_hier values ('PNFDIL','Central','Illinois')
into temp_hier values ('PNHRID','West','Southwest/Mountain')
into temp_hier values ('PNRBWA','West','Washington')
into temp_hier values ('PNTCIL','Central','Illinois')
into temp_hier values ('PNTNIN','Midwest','South District')
into temp_hier values ('PNTWMI','Midwest','North District')
into temp_hier values ('POCLSC','Southeast','South Carolina')
into temp_hier values ('POE IN','Midwest','South District')
into temp_hier values ('POLDIN','Midwest','South District')
into temp_hier values ('POLKOH','Central','Ohio')
into temp_hier values ('POMPMI','Midwest','North District')
into temp_hier values ('POSNMI','Midwest','North District')
into temp_hier values ('PPCYIL','Central','Illinois')
into temp_hier values ('PPGVIL','Central','Illinois')
into temp_hier values ('PRBGIL','Central','Illinois')
into temp_hier values ('PRCKIN','Midwest','South District')
into temp_hier values ('PRCYIL','Central','Illinois')
into temp_hier values ('PRDMAZ','West','Southwest/Mountain')
into temp_hier values ('PRDMCA','West','Southwest/Mountain')
into temp_hier values ('PRKRAZ','West','Southwest/Mountain')
into temp_hier values ('PRLKID','West','Southwest/Mountain')
into temp_hier values ('PRNVIL','Central','Illinois')
into temp_hier values ('PRRVID','West','Southwest/Mountain')
into temp_hier values ('PRRYIL','Central','Illinois')
into temp_hier values ('PRSCMI','Midwest','North District')
into temp_hier values ('PRSPOH','Central','Ohio')
into temp_hier values ('PRTGIN','Midwest','Central District')
into temp_hier values ('PRTGOH','Central','Ohio')
into temp_hier values ('PRTGWI','Central','Wisconsin')
into temp_hier values ('PRTNIL','Central','Illinois')
into temp_hier values ('PRTNIN','Midwest','South District')
into temp_hier values ('PRVLOH','Central','Ohio')
into temp_hier values ('PRVTOR','West','Oregon')
into temp_hier values ('PSFLID','West','Southwest/Mountain')
into temp_hier values ('PSTMIL','Central','Illinois')
into temp_hier values ('PSTNAZ','West','Southwest/Mountain')
into temp_hier values ('PSVLOH','Central','Ohio')
into temp_hier values ('PTANWA','West','Washington')
into temp_hier values ('PTBGIN','Midwest','South District')
into temp_hier values ('PTBGMI','Midwest','Central District')
into temp_hier values ('PTBYOH','Central','Ohio')
into temp_hier values ('PTFDIL','Central','Illinois')
into temp_hier values ('PTLDIN','Midwest','Central District')
into temp_hier values ('PTLDOH','Central','Ohio')
into temp_hier values ('PTLDOR','West','Oregon')
into temp_hier values ('PTLTID','West','Southwest/Mountain')
into temp_hier values ('PTMCIL','Central','Illinois')
into temp_hier values ('PTMOOH','Central','Ohio')
into temp_hier values ('PTNMIL','Central','Illinois')
into temp_hier values ('PTOROR','West','Oregon')
into temp_hier values ('PTRSWA','West','Washington')
into temp_hier values ('PTRVOH','Central','Ohio')
into temp_hier values ('PTTWWA','West','Washington')
into temp_hier values ('PTVLWI','Central','Wisconsin')
into temp_hier values ('PTWLOH','Central','Ohio')
into temp_hier values ('PWISSC','Southeast','South Carolina')
into temp_hier values ('PWPWIL','Central','Illinois')
into temp_hier values ('PWPWMI','Midwest','Central District')
into temp_hier values ('PWRSOR','West','Oregon')
into temp_hier values ('PXTNIL','Central','Illinois')
into temp_hier values ('PYVLIL','Central','Illinois')
into temp_hier values ('PYVLOH','Central','Ohio')
into temp_hier values ('QKCYOH','Central','Ohio')
into temp_hier values ('QNCYIL','Central','Illinois')
into temp_hier values ('QNCYMI','Midwest','Central District')
into temp_hier values ('QNCYWA','West','Washington')
into temp_hier values ('QRTZAZ','West','Southwest/Mountain')
into temp_hier values ('RACNOH','Central','Ohio')
into temp_hier values ('RBLKWI','Central','Wisconsin')
into temp_hier values ('RBRTIL','Central','Illinois')
into temp_hier values ('RBSNIL','Central','Illinois')
into temp_hier values ('RCBHWA','West','Washington')
into temp_hier values ('RCCTWI','Central','Wisconsin')
into temp_hier values ('RCFRIL','Central','Illinois')
into temp_hier values ('RCFRWA','West','Southwest/Mountain')
into temp_hier values ('RCHEIL','Central','Illinois')
into temp_hier values ('RCKTIL','Central','Illinois')
into temp_hier values ('RCLDWA','West','Washington')
into temp_hier values ('RCMDIL','Central','Illinois')
into temp_hier values ('RCMDIN','Midwest','South District')
into temp_hier values ('RCMDMI','Midwest','North District')
into temp_hier values ('RCMDOH','Central','Ohio')
into temp_hier values ('RCPTIL','Central','Illinois')
into temp_hier values ('RCTNIL','Central','Illinois')
into temp_hier values ('RCWDOH','Central','Ohio')
into temp_hier values ('RDBGWI','Central','Wisconsin')
into temp_hier values ('RDDCIL','Central','Illinois')
into temp_hier values ('RDGCCA','West','Southwest/Mountain')
into temp_hier values ('RDHSIL','Central','Illinois')
into temp_hier values ('RDHWOH','Central','Ohio')
into temp_hier values ('RDKYIN','Midwest','South District')
into temp_hier values ('RDMDWA','West','Washington')
select * from dual;



INSERT ALL
into temp_hier values ('RDMNIL','Central','Illinois')
into temp_hier values ('RDNGMI','Midwest','Central District')
into temp_hier values ('RDNROH','Central','Ohio')
into temp_hier values ('RDPTOR','West','Oregon')
into temp_hier values ('RDTNIN','Midwest','South District')
into temp_hier values ('RDVLWI','Central','Wisconsin')
into temp_hier values ('RDWYWI','Central','Wisconsin')
into temp_hier values ('RGCYMI','Midwest','North District')
into temp_hier values ('RGVLIN','Midwest','South District')
into temp_hier values ('RGWYIL','Central','Illinois')
into temp_hier values ('RHNLWI','Central','Wisconsin')
into temp_hier values ('RIGROH','Central','Ohio')
into temp_hier values ('RILYIN','Midwest','South District')
into temp_hier values ('RLGHIL','Central','Illinois')
into temp_hier values ('RLGHNC','Southeast','North Carolina')
into temp_hier values ('RLPRIN','Midwest','Central District')
into temp_hier values ('RLVLOH','Central','Ohio')
into temp_hier values ('RMSYIN','Midwest','South District')
into temp_hier values ('RMTNIN','Midwest','Central District')
into temp_hier values ('RMUSMI','Midwest','North District')
into temp_hier values ('RNKNIL','Central','Illinois')
into temp_hier values ('RNKNMI','Midwest','North District')
into temp_hier values ('RNLKWI','Central','Wisconsin')
into temp_hier values ('RNSLIN','Midwest','Central District')
into temp_hier values ('RNTLIL','Central','Illinois')
into temp_hier values ('RNTNWA','West','Washington')
into temp_hier values ('ROCHMI','Midwest','Central District')
into temp_hier values ('RONKIL','Central','Illinois')
into temp_hier values ('RONKIN','Midwest','South District')
into temp_hier values ('ROSCIL','Central','Illinois')
into temp_hier values ('ROSLWA','West','Southwest/Mountain')
into temp_hier values ('ROVLIL','Central','Illinois')
into temp_hier values ('ROVLNC','Southeast','North Carolina')
into temp_hier values ('ROYLIL','Central','Illinois')
into temp_hier values ('RPBLOH','Central','Ohio')
into temp_hier values ('RPBLWA','West','Washington')
into temp_hier values ('RSBGOR','West','Oregon')
into temp_hier values ('RSCMMI','Midwest','North District')
into temp_hier values ('RSCYMI','Midwest','North District')
into temp_hier values ('RSHLIL','Central','Illinois')
into temp_hier values ('RSLNWA','West','Washington')
into temp_hier values ('RSVRIN','Midwest','South District')
into temp_hier values ('RTHBOH','Central','Ohio')
into temp_hier values ('RTHDID','West','Southwest/Mountain')
into temp_hier values ('RTLDIL','Central','Illinois')
into temp_hier values ('RTLDOH','Central','Ohio')
into temp_hier values ('RUVLIL','Central','Illinois')
into temp_hier values ('RUVLIN','Midwest','South District')
into temp_hier values ('RVDLMI','Midwest','North District')
into temp_hier values ('RVJTMI','Midwest','Central District')
into temp_hier values ('RVNNMI','Midwest','North District')
into temp_hier values ('RWSNOH','Central','Ohio')
into temp_hier values ('RYCTIN','Midwest','South District')
into temp_hier values ('RYTNIL','Central','Illinois')
into temp_hier values ('SABNOH','Central','Ohio')
into temp_hier values ('SALMAZ','West','Southwest/Mountain')
into temp_hier values ('SALMIN','Midwest','South District')
into temp_hier values ('SALMOR','West','Oregon')
into temp_hier values ('SALMWI','Central','Wisconsin')
into temp_hier values ('SALNMI','Midwest','Central District')
into temp_hier values ('SANTSC','Southeast','South Carolina')
into temp_hier values ('SBLTIL','Central','Illinois')
into temp_hier values ('SBLYIL','Central','Illinois')
into temp_hier values ('SBNDIN','Midwest','Central District')
into temp_hier values ('SBVIOH','Central','Ohio')
into temp_hier values ('SCBGIN','Midwest','South District')
into temp_hier values ('SCHLMI','Midwest','Central District')
into temp_hier values ('SCHLOR','West','Oregon')
into temp_hier values ('SCIOOH','Central','Ohio')
into temp_hier values ('SCIPIN','Midwest','South District')
into temp_hier values ('SCMNIL','Central','Illinois')
into temp_hier values ('SCPPOR','West','Oregon')
into temp_hier values ('SCTTOH','Central','Ohio')
into temp_hier values ('SCTVOH','Central','Ohio')
into temp_hier values ('SDLLIL','Central','Illinois')
into temp_hier values ('SDNYIL','Central','Illinois')
into temp_hier values ('SDNYIN','Midwest','South District')
into temp_hier values ('SDNYMI','Midwest','North District')
into temp_hier values ('SDRSIL','Central','Illinois')
into temp_hier values ('SECRIL','Central','Illinois')
into temp_hier values ('SEMNOH','Central','Ohio')
into temp_hier values ('SEQMWA','West','Washington')
into temp_hier values ('SEVLOH','Central','Ohio')
into temp_hier values ('SEVRNC','Southeast','North Carolina')
into temp_hier values ('SFVLIL','Central','Illinois')
into temp_hier values ('SGNWMI','Midwest','North District')
into temp_hier values ('SGRCOH','Central','Ohio')
into temp_hier values ('SGTCMI','Midwest','Central District')
into temp_hier values ('SHBNIL','Central','Illinois')
into temp_hier values ('SHCTOH','Central','Ohio')
into temp_hier values ('SHFDIL','Central','Illinois')
into temp_hier values ('SHHGSC','Southeast','South Carolina')
into temp_hier values ('SHLBIN','Midwest','South District')
into temp_hier values ('SHLBMI','Midwest','North District')
into temp_hier values ('SHLBOH','Central','Ohio')
into temp_hier values ('SHLDIL','Central','Illinois')
into temp_hier values ('SHLNIL','Central','Illinois')
into temp_hier values ('SHLSIN','Midwest','South District')
into temp_hier values ('SHMNIL','Central','Illinois')
into temp_hier values ('SHPHMI','Midwest','North District')
into temp_hier values ('SHPSIN','Midwest','Central District')
into temp_hier values ('SHRDIL','Central','Illinois')
into temp_hier values ('SHRDMI','Midwest','North District')
into temp_hier values ('SHRDOR','West','Oregon')
into temp_hier values ('SHRLIN','Midwest','South District')
into temp_hier values ('SHRYIN','Midwest','South District')
into temp_hier values ('SHTWIL','Central','Illinois')
into temp_hier values ('SHWDOR','West','Oregon')
into temp_hier values ('SKCYWI','Central','Wisconsin')
into temp_hier values ('SKTNIL','Central','Illinois')
into temp_hier values ('SKYKWA','West','Washington')
into temp_hier values ('SLLKIN','Midwest','South District')
into temp_hier values ('SLLKWA','West','Washington')
into temp_hier values ('SLLKWI','Central','Wisconsin')
into temp_hier values ('SLLVIL','Central','Illinois')
into temp_hier values ('SLLVIN','Midwest','South District')
into temp_hier values ('SLNGWI','Central','Wisconsin')
into temp_hier values ('SLSPIL','Central','Illinois')
into temp_hier values ('SLTNOR','West','Oregon')
into temp_hier values ('SMCKMI','Midwest','North District')
into temp_hier values ('SMFDOH','Central','Ohio')
into temp_hier values ('SMNKIL','Central','Illinois')
into temp_hier values ('SMNRIL','Central','Illinois')
into temp_hier values ('SMRVCA','West','Oregon')
into temp_hier values ('SMRWOR','West','Oregon')
into temp_hier values ('SMSHWA','West','Washington')
into temp_hier values ('SMTHNV','West','Southwest/Mountain')
into temp_hier values ('SMTNSC','Southeast','South Carolina')
into temp_hier values ('SMTRSC','Southeast','South Carolina')
into temp_hier values ('SNBRCA','West','Southwest/Mountain')
into temp_hier values ('SNBYOH','Central','Ohio')
into temp_hier values ('SNCKMI','Midwest','Central District')
into temp_hier values ('SNDSOH','Central','Ohio')
into temp_hier values ('SNDWIL','Central','Illinois')
into temp_hier values ('SNDYOR','West','Oregon')
into temp_hier values ('SNFRNC','Southeast','North Carolina')
into temp_hier values ('SNGRCA','West','Southwest/Mountain')
into temp_hier values ('SNHSWA','West','Washington')
into temp_hier values ('SNLDIL','Central','Illinois')
into temp_hier values ('SNMNCA','West','Southwest/Mountain')
into temp_hier values ('SNMNIN','Midwest','South District')
into temp_hier values ('SNPNID','West','Southwest/Mountain')
into temp_hier values ('SNPRWI','Central','Wisconsin')
into temp_hier values ('SNSDOR','West','Oregon')
into temp_hier values ('SNSPOH','Central','Ohio')
into temp_hier values ('SNTCIN','Midwest','South District')
into temp_hier values ('SNTNMI','Midwest','North District')
into temp_hier values ('SNVLIN','Midwest','Central District')
into temp_hier values ('SNVLOH','Central','Ohio')
into temp_hier values ('SOHNMI','Midwest','Central District')
into temp_hier values ('SOLKWA','West','Washington')
into temp_hier values ('SPGRWI','Central','Wisconsin')
into temp_hier values ('SPGVIL','Central','Illinois')
into temp_hier values ('SPLDIL','Central','Illinois')
into temp_hier values ('SPLDIN','Midwest','South District')
into temp_hier values ('SPLKID','West','Southwest/Mountain')
into temp_hier values ('SPNCOH','Central','Ohio')
into temp_hier values ('SPNCWI','Central','Wisconsin')
into temp_hier values ('SPPTIN','Midwest','South District')
into temp_hier values ('SPRGIN','Midwest','South District')
into temp_hier values ('SPRTIL','Central','Illinois')
into temp_hier values ('SPVYIL','Central','Illinois')
into temp_hier values ('SRDNOH','Central','Ohio')
into temp_hier values ('SRFDIL','Central','Illinois')
into temp_hier values ('SRFDOH','Central','Ohio')
into temp_hier values ('SRFRWI','Central','Wisconsin')
into temp_hier values ('SRLKMI','Midwest','Central District')
into temp_hier values ('SSBYWI','Central','Wisconsin')
into temp_hier values ('SSSRIL','Central','Illinois')
into temp_hier values ('SSVLSC','Southeast','South Carolina')
into temp_hier values ('STATIN','Midwest','South District')
into temp_hier values ('STBGOH','Central','Ohio')
into temp_hier values ('STBRMI','Midwest','Central District')
into temp_hier values ('STCDWI','Central','Wisconsin')
into temp_hier values ('STFRIL','Central','Illinois')
into temp_hier values ('STFROR','West','Oregon')
into temp_hier values ('STFTIL','Central','Illinois')
into temp_hier values ('STJHMI','Midwest','North District')
into temp_hier values ('STJOIN','Midwest','Central District')
into temp_hier values ('STLDIL','Central','Illinois')
into temp_hier values ('STLNNV','West','Southwest/Mountain')
into temp_hier values ('STLSMI','Midwest','North District')
into temp_hier values ('STLVIL','Central','Illinois')
into temp_hier values ('STMRID','West','Southwest/Mountain')
into temp_hier values ('STMYOH','Central','Ohio')
into temp_hier values ('STNGIL','Central','Illinois')
into temp_hier values ('STNGMI','Midwest','North District')
into temp_hier values ('STPSWA','West','Washington')
into temp_hier values ('STRGMI','Midwest','Central District')
into temp_hier values ('STRTIL','Central','Illinois')
into temp_hier values ('STRWIL','Central','Illinois')
into temp_hier values ('STSNWA','West','Washington')
into temp_hier values ('STTLWA','West','Washington')
into temp_hier values ('STTNOR','West','Oregon')
into temp_hier values ('STVYIL','Central','Illinois')
into temp_hier values ('STWDMI','Midwest','North District')
into temp_hier values ('STWDWA','West','Washington')
into temp_hier values ('STWRIL','Central','Illinois')
into temp_hier values ('SUITNC','Southeast','North Carolina')
into temp_hier values ('SULTWA','West','Washington')
into temp_hier values ('SUMSWA','West','Washington')
into temp_hier values ('SVNHOH','Central','Ohio')
into temp_hier values ('SVNNIL','Central','Illinois')
into temp_hier values ('SWBSOH','Central','Ohio')
into temp_hier values ('SWCRMI','Midwest','North District')
into temp_hier values ('SWHDWA','West','Washington')
into temp_hier values ('SWLYWA','West','Washington')
into temp_hier values ('SWRDIL','Central','Illinois')
into temp_hier values ('SWTNOH','Central','Ohio')
into temp_hier values ('SWYRMI','Midwest','Central District')
into temp_hier values ('SXLKMI','Midwest','North District')
into temp_hier values ('SYBKIL','Central','Illinois')
into temp_hier values ('SYCMIL','Central','Illinois')
into temp_hier values ('SYLVNC','Southeast','North Carolina')
into temp_hier values ('SYMRIL','Central','Illinois')
into temp_hier values ('SYMRIN','Midwest','South District')
into temp_hier values ('SYNRWI','Central','Wisconsin')
into temp_hier values ('SYRCIN','Midwest','Central District')
into temp_hier values ('SYVNOH','Central','Ohio')
into temp_hier values ('TACMWA','West','Washington')
into temp_hier values ('TCMSMI','Midwest','Central District')
into temp_hier values ('TEKOWA','West','Southwest/Mountain')
into temp_hier values ('TGRDOR','West','Oregon')
into temp_hier values ('THBOIL','Central','Illinois')
into temp_hier values ('THLKWI','Central','Wisconsin')
into temp_hier values ('THPLOH','Central','Ohio')
into temp_hier values ('THRRMI','Midwest','Central District')
into temp_hier values ('THRSWI','Central','Wisconsin')
into temp_hier values ('THSNIL','Central','Illinois')
into temp_hier values ('THTNWA','West','Southwest/Mountain')
into temp_hier values ('TKNSMI','Midwest','Central District')
into temp_hier values ('TLCYIN','Midwest','South District')
into temp_hier values ('TLDNIL','Central','Illinois')
into temp_hier values ('TLONIL','Central','Illinois')
into temp_hier values ('TLVLOH','Central','Ohio')
into temp_hier values ('TMHKWI','Central','Wisconsin')
into temp_hier values ('TMPRMI','Midwest','Central District')
into temp_hier values ('TNLKMI','Midwest','North District')
into temp_hier values ('TNSKWA','West','Washington')
into temp_hier values ('TNSNIN','Midwest','South District')
into temp_hier values ('TOLCIL','Central','Illinois')
into temp_hier values ('TOLDIL','Central','Illinois')
into temp_hier values ('TOLNIL','Central','Illinois')
into temp_hier values ('TPCNIN','Midwest','South District')
into temp_hier values ('TPCYOH','Central','Ohio')
into temp_hier values ('TPKAIN','Midwest','Central District')
into temp_hier values ('TPLKNV','West','Southwest/Mountain')
into temp_hier values ('TPTNMI','Midwest','Central District')
into temp_hier values ('TPVLIL','Central','Illinois')
into temp_hier values ('TRMTIL','Central','Illinois')
into temp_hier values ('TRNROR','West','Oregon')
into temp_hier values ('TROYOH','Central','Ohio')
into temp_hier values ('TRRHIN','Midwest','South District')
into temp_hier values ('TRRVMI','Midwest','North District')
into temp_hier values ('TRVRWI','Central','Wisconsin')
into temp_hier values ('TRWDOH','Central','Ohio')
into temp_hier values ('TRYNNC','Southeast','North Carolina')
into temp_hier values ('TSCLIL','Central','Illinois')
into temp_hier values ('TSKLIL','Central','Illinois')
into temp_hier values ('TULTOR','West','Oregon')
into temp_hier values ('TWISWA','West','Washington')
into temp_hier values ('TWLKWI','Central','Wisconsin')
into temp_hier values ('TWNDIL','Central','Illinois')
into temp_hier values ('TWRVWI','Central','Wisconsin')
into temp_hier values ('TWVLIL','Central','Illinois')
into temp_hier values ('ULLNIL','Central','Illinois')
into temp_hier values ('UNCYIN','Midwest','North District')
into temp_hier values ('UNCYMI','Midwest','Central District')
into temp_hier values ('UNDLIN','Midwest','South District')
into temp_hier values ('UNINMI','Midwest','Central District')
into temp_hier values ('UNINOR','West','Washington')
into temp_hier values ('UNMLIN','Midwest','Central District')
into temp_hier values ('URSAIL','Central','Illinois')
into temp_hier values ('VANCWA','West','Washington')
into temp_hier values ('VANDMI','Midwest','Central District')
into temp_hier values ('VARNIL','Central','Illinois')
into temp_hier values ('VINNIL','Central','Illinois')
into temp_hier values ('VIRQWI','Central','Wisconsin')
into temp_hier values ('VLCYOH','Central','Ohio')
into temp_hier values ('VLGVIL','Central','Illinois')
into temp_hier values ('VLPRIN','Midwest','Central District')
into temp_hier values ('VLRGIL','Central','Illinois')
into temp_hier values ('VNBROH','Central','Ohio')
into temp_hier values ('VNDRMI','Midwest','North District')
into temp_hier values ('VRDNIL','Central','Illinois')
into temp_hier values ('VRMLIL','Central','Illinois')
into temp_hier values ('VRMTIL','Central','Illinois')
into temp_hier values ('VRNNOR','West','Oregon')
into temp_hier values ('VRSLIL','Central','Illinois')
into temp_hier values ('VRSLIN','Midwest','South District')
into temp_hier values ('VTBGMI','Midwest','North District')
into temp_hier values ('VTVLCA','West','Southwest/Mountain')
into temp_hier values ('VYVWOR','West','Oregon')
into temp_hier values ('WAISWI','Central','Wisconsin')
into temp_hier values ('WALDOH','Central','Ohio')
into temp_hier values ('WALXOH','Central','Ohio')
into temp_hier values ('WAMPSC','Southeast','South Carolina')
into temp_hier values ('WASHIL','Central','Illinois')
into temp_hier values ('WAUSWI','Central','Wisconsin')
into temp_hier values ('WAWKIN','Midwest','Central District')
into temp_hier values ('WAYNOH','Central','Ohio')
into temp_hier values ('WBKAWI','Central','Wisconsin')
into temp_hier values ('WBRKIL','Central','Illinois')
into temp_hier values ('WBSHIN','Midwest','South District')
into temp_hier values ('WBVLMI','Midwest','Central District')
into temp_hier values ('WCCRIN','Midwest','South District')
into temp_hier values ('WCSTMI','Midwest','North District')
into temp_hier values ('WDBNIN','Midwest','South District')
into temp_hier values ('WDBNOR','West','Oregon')
into temp_hier values ('WDBONC','Southeast','North Carolina')
into temp_hier values ('WDFRCA','West','Southwest/Mountain')
into temp_hier values ('WDLDIL','Central','Illinois')
into temp_hier values ('WDLDMI','Midwest','North District')
into temp_hier values ('WDLDWA','West','Oregon')
into temp_hier values ('WDMNMI','Midwest','North District')
into temp_hier values ('WDRFSC','Southeast','South Carolina')
into temp_hier values ('WDSNIL','Central','Illinois')
into temp_hier values ('WDSTOH','Central','Ohio')
into temp_hier values ('WDVLWA','West','Washington')
into temp_hier values ('WENNIL','Central','Illinois')
into temp_hier values ('WEPPID','West','Southwest/Mountain')
into temp_hier values ('WFFTIL','Central','Illinois')
into temp_hier values ('WGTNIL','Central','Illinois')
into temp_hier values ('WGTNOH','Central','Ohio')
into temp_hier values ('WHBGOH','Central','Ohio')
into temp_hier values ('WHCYOR','West','Oregon')
into temp_hier values ('WHHAIL','Central','Illinois')
into temp_hier values ('WHLKMI','Midwest','North District')
into temp_hier values ('WHLKWI','Central','Wisconsin')
into temp_hier values ('WHLRIN','Midwest','Central District')
into temp_hier values ('WHLWWI','Central','Wisconsin')
into temp_hier values ('WHPGMI','Midwest','Central District')
into temp_hier values ('WHPGOH','Central','Ohio')
into temp_hier values ('WHTHMI','Midwest','North District')
into temp_hier values ('WHTNOH','Central','Ohio')
into temp_hier values ('WIDLWI','Central','Wisconsin')
into temp_hier values ('WINOOH','Central','Ohio')
into temp_hier values ('WIVLOR','West','Oregon')
into temp_hier values ('WKMNOH','Central','Ohio')
into temp_hier values ('WKRSIN','Midwest','Central District')
into temp_hier values ('WKVLOH','Central','Ohio')
into temp_hier values ('WLBOSC','Southeast','South Carolina')
into temp_hier values ('WLDNIL','Central','Illinois')
into temp_hier values ('WLDROH','Central','Ohio')
into temp_hier values ('WLFYIN','Midwest','South District')
into temp_hier values ('WLKMMI','Midwest','North District')
into temp_hier values ('WLLCID','West','Southwest/Mountain')
into temp_hier values ('WLLWOR','West','Washington')
into temp_hier values ('WLMGOH','Central','Ohio')
into temp_hier values ('WLNTIL','Central','Illinois')
into temp_hier values ('WLPTOH','Central','Ohio')
into temp_hier values ('WLRDOH','Central','Ohio')
into temp_hier values ('WLSHOH','Central','Ohio')
into temp_hier values ('WLTNIN','Midwest','South District')
into temp_hier values ('WLTNOH','Central','Ohio')
into temp_hier values ('WLWLWA','West','Washington')
into temp_hier values ('WLWOWI','Central','Wisconsin')
into temp_hier values ('WMBHSC','Southeast','South Carolina')
into temp_hier values ('WMTNMI','Midwest','Central District')
into temp_hier values ('WMTNOH','Central','Ohio')
into temp_hier values ('WNBOSC','Southeast','South Carolina')
into temp_hier values ('WNCHIL','Central','Illinois')
into temp_hier values ('WNCHIN','Midwest','South District')
into temp_hier values ('WNDNIL','Central','Illinois')
into temp_hier values ('WNFLIN','Midwest','South District')
into temp_hier values ('WNGTNC','Southeast','North Carolina')
into temp_hier values ('WNHLSC','Southeast','South Carolina')
into temp_hier values ('WNLKIL','Central','Illinois')
into temp_hier values ('WNNBIL','Central','Illinois')
into temp_hier values ('WNSLIL','Central','Illinois')
into temp_hier values ('WNTCWA','West','Washington')
into temp_hier values ('WNTHIN','Midwest','Central District')
into temp_hier values ('WNTHWA','West','Washington')
into temp_hier values ('WOTNIN','Midwest','South District')
into temp_hier values ('WPHLMI','Midwest','North District')
into temp_hier values ('WPKNOH','Central','Ohio')
into temp_hier values ('WPMOOH','Central','Ohio')
into temp_hier values ('WRBGIL','Central','Illinois')
into temp_hier values ('WRDNWA','West','Washington')
into temp_hier values ('WRLDWA','West','Washington')
into temp_hier values ('WRRNIL','Central','Illinois')
into temp_hier values ('WRRNIN','Midwest','South District')
into temp_hier values ('WRSWIN','Midwest','Central District')
into temp_hier values ('WRSWOH','Central','Ohio')
into temp_hier values ('WSBNIL','Central','Illinois')
into temp_hier values ('WSBYWI','Central','Wisconsin')
into temp_hier values ('WSFDIL','Central','Illinois')
into temp_hier values ('WSFDIN','Midwest','South District')
into temp_hier values ('WSFDWI','Central','Wisconsin')
into temp_hier values ('WSHGWA','West','Oregon')
into temp_hier values ('WSLMIL','Central','Illinois')
into temp_hier values ('WSLMOH','Central','Ohio')
into temp_hier values ('WSPNIN','Midwest','South District')
into temp_hier values ('WSPTIL','Central','Illinois')
into temp_hier values ('WSPTIN','Midwest','South District')
into temp_hier values ('WSPTWA','West','Washington')
into temp_hier values ('WSRVWA','West','Oregon')
into temp_hier values ('WSTNOH','Central','Ohio')
into temp_hier values ('WSTROH','Central','Ohio')
into temp_hier values ('WSTVIN','Midwest','Central District')
into temp_hier values ('WSVLIL','Central','Illinois')
into temp_hier values ('WSVWIL','Central','Illinois')
into temp_hier values ('WSWOOH','Central','Ohio')
into temp_hier values ('WTLDIN','Midwest','South District')
into temp_hier values ('WTMNIL','Central','Illinois')
into temp_hier values ('WTNBWI','Central','Wisconsin')
into temp_hier values ('WTRLIN','Midwest','Central District')
into temp_hier values ('WTRLWI','Central','Wisconsin')
into temp_hier values ('WTVLWA','West','Washington')
into temp_hier values ('WTWNWI','Central','Wisconsin')
into temp_hier values ('WUNNIL','Central','Illinois')
into temp_hier values ('WUNNOH','Central','Ohio')
into temp_hier values ('WUNTOH','Central','Ohio')
into temp_hier values ('WVRLIL','Central','Illinois')
into temp_hier values ('WVRLOH','Central','Ohio')
into temp_hier values ('WVVLNC','Southeast','North Carolina')
into temp_hier values ('WWHLIL','Central','Illinois')
into temp_hier values ('WXHWNC','Southeast','North Carolina')
into temp_hier values ('WYCYIL','Central','Illinois')
into temp_hier values ('WYNGIL','Central','Illinois')
into temp_hier values ('WYNGMI','Midwest','North District')
into temp_hier values ('WYNTIL','Central','Illinois')
into temp_hier values ('WYTTIN','Midwest','Central District')
into temp_hier values ('WYVLIL','Central','Illinois')
into temp_hier values ('XENIOH','Central','Ohio')
into temp_hier values ('XXXXAZ','West','Southwest/Mountain')
into temp_hier values ('XXXXCA','West','Southwest/Mountain')
into temp_hier values ('XXXXID','West','Southwest/Mountain')
into temp_hier values ('XXXXIL','Central','Illinois')
into temp_hier values ('XXXXIN','Midwest','South District')
into temp_hier values ('XXXXMI','Midwest','North District')
into temp_hier values ('XXXXNC','Southeast','North Carolina')
into temp_hier values ('XXXXNV','West','Southwest/Mountain')
into temp_hier values ('XXXXOH','Central','Ohio')
into temp_hier values ('XXXXOR','West','Oregon')
into temp_hier values ('XXXXSC','Southeast','South Carolina')
into temp_hier values ('XXXXWA','West','Washington')
into temp_hier values ('XXXXWI','Central','Wisconsin')
into temp_hier values ('YAKMWA','West','Washington')
into temp_hier values ('YALEMI','Midwest','North District')
into temp_hier values ('YMHLOR','West','Oregon')
into temp_hier values ('YMSSSC','Southeast','South Carolina')
into temp_hier values ('YRKSOH','Central','Ohio')
into temp_hier values ('YRTNNV','West','Southwest/Mountain')
into temp_hier values ('ZGLRIL','Central','Illinois')
into temp_hier values ('ZNVLIN','Midwest','South District')
select * from dual;

