select	/*+ ORDERED */ a11.DM_LSR_ASR_ID  LSR_ASR_ID,
	a11.DM_LSR_ASR_RECORD_TYPE_CD  Record_Type,
	a11.DM_LSR_ASR_AORD_NO  ASR_Order_Number,
	a11.DM_LSR_ASR_LORD_NO  LSR_Order_Number,
	a14.DM_SUB_MSRMNT_CD  Sub_Measurement_Code,
	a11.DM_LSR_ASR_STATE_CD  STATE,
	a11.DM_LSR_ASR_CLEC_NAME  CLEC_Name,
	a11.DM_LSR_ASR_CCNA_CD  CCNA,
	a11.DM_LSR_ASR_PROD_CLASS  Class,
	a11.DM_LSR_ASR_BILL_TN  BILLING_TELEPHONE_NO,
	a11.DM_LSR_ASR_CKT_TN  Circuit_TN,
	a11.DM_LSR_ASR_DUE_DAY_MISS_FLAG  Due_Date_Missed_Flag,
	a11.dm_lsr_asr_DUE_SCHEDULE_DT,
	a11.DM_LSR_ASR_CMP_DT,
	a11.DM_LSR_ASR_ORD_CREATE_DT,
	a11.DM_LSR_ASR_REQ_DUE_DT,
	a11.DM_LSR_ASR_DISPATCH_FLAG  dispatch_flag,
	a11.DM_LSR_ASR_DAYS_TO_INSTALL  Days_Install,
	a11.DM_LSR_ASR_TRBL7_FLAG  Trouble_7_Flag,
	a11.DM_LSR_ASR_TRBL30_FLAG  Trouble_30_Flag,
	a12.DM_AGG_RPTG_MONTH  Reporting_Month,
	count(a11.DM_LSR_ASR_ORD_ID)  WJXBFS1
from	(SELECT/*+ INDEX(LSR NMPW_DM_PR_LSR_PROD_RPTG_MONTH) */
	LSR.DM_LSR_ID DM_LSR_ASR_ID,
	LSR.DM_LSR_ORD_NO DM_LSR_ASR_LORD_NO,
	NULL DM_LSR_ASR_AORD_NO,
	LSR.DM_LSR_REGION_CD DM_LSR_ASR_REGION_CD,
	LSR.DM_LSR_ORD_ID DM_LSR_ASR_ORD_ID,
	LSR.DM_LSR_AUDIT_RC_CD DM_LSR_ASR_AUDIT_RC_CD,
	LSR.DM_LSR_CCNA_CD DM_LSR_ASR_CCNA_CD,
	LSR.DM_LSR_DISPATCH_FLAG DM_LSR_ASR_DISPATCH_FLAG,
	LSR.DM_LSR_BILL_TYPE_CD DM_LSR_ASR_BILL_TYPE_CD,
	LSR.DM_LSR_CMP_LTERM DM_LSR_ASR_CMP_LTERM,
	LSR.DM_LSR_CREATE_LTERM DM_LSR_ASR_CREATE_LTERM,
	LSR.DM_LSR_DUE_DT DM_LSR_ASR_DUE_SCHEDULE_DT,
	LSR.DM_LSR_EXPANDED_SVC_CLASS_CD DM_LSR_ASR_EXPNDD_SVC_CLASS_CD,
	LSR.DM_LSR_SVC_TYPE_CD DM_LSR_ASR_SVC_TYPE_CD,
	LSR.DM_LSR_STATE_CD DM_LSR_ASR_STATE_CD,
	LSR.DM_LSR_SUBCLASS_CD1 DM_LSR_ASR_SUBCLASS_CD1,
	LSR.DM_LSR_SUBCLASS_CD2 DM_LSR_ASR_SUBCLASS_CD2,
	LSR.DM_LSR_SUBCLASS_CD3 DM_LSR_ASR_SUBCLASS_CD3,
	LSR.DM_LSR_SUBCLASS_CD4 DM_LSR_ASR_SUBCLASS_CD4,
	LSR.DM_LSR_SUBCLASS_CD5 DM_LSR_ASR_SUBCLASS_CD5,
	LSR.DM_LSR_SUBCLASS_CD6 DM_LSR_ASR_SUBCLASS_CD6,
	LSR.DM_LSR_BILL_EFCTV_DT DM_LSR_ASR_CMP_DT,
	LSR.DM_LSR_CUST_REQ_CD DM_LSR_ASR_CUST_REQ_CD,
	LSR.DM_LSR_DAYS_TO_INSTALL DM_LSR_ASR_DAYS_TO_INSTALL,
	LSR.DM_LSR_AVG_INSTALL_FLAG DM_LSR_ASR_AVG_INSTALL_FLAG,
	LSR.DM_LSR_DELAY_DAYS DM_LSR_ASR_DELAY_DAYS,
	LSR.DM_LSR_ORD_STATUS_CD DM_LSR_ASR_ORD_STATUS_CD,
	LSR.DM_LSR_BIZ_DT DM_LSR_ASR_BIZ_DT,
	LSR.DM_LSR_C2C_FCC_CD DM_LSR_ASR_C2C_FCC_CD,
	LSR.DM_LSR_SUFFIX_C12_HF_FLAG DM_LSR_ASR_SUFFIX_C12_HF_FLAG,
	LSR.DM_LSR_SUFFIX_C12_CW_FLAG DM_LSR_ASR_SUFFIX_C12_CW_FLAG,
	LSR.DM_LSR_SUFFIX_C12_NA_FLAG DM_LSR_ASR_SUFFIX_C12_NA_FLAG,
	LSR.DM_LSR_SUFFIX_C12_CR_FLAG DM_LSR_ASR_SUFFIX_C12_CR_FLAG,
	LSR.DM_LSR_SUFFIX_C12_CD_FLAG DM_LSR_ASR_SUFFIX_C12_CD_FLAG,
	LSR.DM_LSR_SUFFIX_CDDD_FLAG DM_LSR_ASR_SUFFIX_CDDD_FLAG,
	LSR.DM_LSR_SUFFIX_BFR_FLAG DM_LSR_ASR_SUFFIX_BFR_FLAG,
	LSR.DM_LSR_SUFFIX_LOA_FLAG DM_LSR_ASR_SUFFIX_LOA_FLAG,
	LSR.DM_LSR_SUFFIX_VCDDD_FLAG DM_LSR_ASR_SUFFIX_VCDDD_FLAG,
	LSR.DM_LSR_SUFFIX_SID_FLAG DM_LSR_ASR_SUFFIX_SID_FLAG,
	LSR.DM_LSR_SUFFIX_FIX_FLAG DM_LSR_ASR_SUFFIX_FIX_FLAG,
	LSR.DM_LSR_SUFFIX_FRLAY_FLAG DM_LSR_ASR_SUFFIX_FRLAY_FLAG,
	LSR.DM_LSR_SUFFIX_FRLAYS_FLAG DM_LSR_ASR_SUFFIX_FRLAYS_FLAG,
	LSR.DM_LSR_SUFFIX_FRLAYH_FLAG DM_LSR_ASR_SUFFIX_FRLAYH_FLAG,
	LSR.DM_LSR_SUFFIX_DSCMP_FLAG DM_LSR_ASR_SUFFIX_DSCMP_FLAG,
	LSR.DM_LSR_SUFFIX_C15_BLOCK_FLAG DM_LSR_ASR_SUFFIX_C15_BLK_FLAG,
	LSR.DM_LSR_SUFFIX_C14_RCDS_FLAG DM_LSR_ASR_SFX_C14_RCDS_FLAG,
	LSR.DM_LSR_SUFFIX_C12_DR_FLAG DM_LSR_ASR_SUFFIX_C12_DR_FLAG,
	LSR.DM_LSR_SUFFIX_DROSP_FLAG DM_LSR_ASR_SUFFIX_DROSP_FLAG,
	LSR.DM_LSR_SUFFIX_DRCOE_FLAG DM_LSR_ASR_SUFFIX_DRCOE_FLAG,
	LSR.DM_LSR_SUFFIX_DREQ_FLAG DM_LSR_ASR_SUFFIX_DREQ_FLAG,
	LSR.DM_LSR_ORD_CMP_CANCEL_FLAG DM_LSR_ASR_ORD_CMP_CNCL_FLAG,
	LSR.DM_LSR_CONV_TYPE_IND DM_LSR_ASR_CONV_TYPE_IND,
	LSR.DM_LSR_CONV_MET_FLAG DM_LSR_ASR_CONV_MET_FLAG,
	LSR.DM_LSR_CLEC_CAUSED_FLAG DM_LSR_ASR_CLEC_CAUSED_FLAG,
	LSR.DM_LSR_PLANNED_CMP_DT DM_LSR_ASR_PLANNED_CMP_DT,
	LSR.DM_LSR_ACTUAL_CMP_DT DM_LSR_ASR_ACTUAL_CMP_DT,
	LSR.DM_LSR_RPTG_MONTH DM_LSR_ASR_RPTG_MONTH,
	LSR.DM_LSR_EXCL_CCNA_FLAG DM_LSR_ASR_EXCL_CCNA_FLAG,
	LSR.DM_LSR_VERSION DM_LSR_ASR_VERSION,
	LSR.DM_LSR_ORD_CREATE_DT DM_LSR_ASR_ORD_CREATE_DT,
	LSR.DM_LSR_PURCHASE_ORD_NO DM_LSR_ASR_PURCHASE_ORD_NO,
	LSR.DM_LSR_ORD_DTL_COEFFICIENT DM_LSR_ASR_ORD_DTL_COEFFICIENT,
	LSR.DM_LSR_OMT_TYPE DM_LSR_ASR_OMT_TYPE,
	LSR.DM_LSR_BILL_EFCTV_DT DM_LSR_ASR_BILL_EFCTV_DT,
	LSR.DM_LSR_BILL_TN DM_LSR_ASR_BILL_TN,
	LSR.DM_LSR_CKT_TN DM_LSR_ASR_CKT_TN,
	LSR.DM_LSR_RECORD_TYPE_CD DM_LSR_ASR_RECORD_TYPE_CD,
	LSR.DM_LSR_PROD_CLASS DM_LSR_ASR_PROD_CLASS,
	LSR.DM_LSR_ORIG_CLASS_NAME DM_LSR_ASR_ORIG_CLASS_NAME,
	LSR.DM_LSR_PRIMARY_CLASS_FLAG DM_LSR_ASR_PRIMARY_CLASS_FLAG,
	LSR.DM_LSR_INTERVAL_NO DM_LSR_ASR_INTERVAL_NO,
	LSR.DM_LSR_ITEM_NO DM_LSR_ASR_ITEM_NO,
	LSR.DM_LSR_REQ_DUE_DT DM_LSR_ASR_REQ_DUE_DT,
	LSR.DM_LSR_COIN_TYPE_CD DM_LSR_ASR_COIN_TYPE_CD,
	LSR.DM_LSR_COMPANY_CD DM_LSR_ASR_COMPANY_CD,
	LSR.DM_LSR_CBSS_CUST_ACCT_NO DM_LSR_ASR_CBSS_CUST_ACCT_NO,
	LSR.DM_LSR_SVC_CLASS_CD DM_LSR_ASR_SVC_CLASS_CD,
	LSR.DM_LSR_CUST_SVC_DT DM_LSR_ASR_CUST_SVC_DT,
	LSR.DM_LSR_CUST_REF_STATUS_CD DM_LSR_ASR_CUST_REF_STATUS_CD,
	LSR.DM_LSR_CUST_REF DM_LSR_ASR_CUST_REF,
	LSR.DM_LSR_SELECT_SVC_TYPE_CD DM_LSR_ASR_SELECT_SVC_TYPE_CD,
	LSR.DM_LSR_BILL_POSITION_NO DM_LSR_ASR_BILL_POSITION_NO,
	LSR.DM_LSR_UID DM_LSR_ASR_UID,
	NULL DM_LSR_ASR_INVALID_IND,
	NULL DM_LSR_ASR_SVC_CD,
	NULL DM_LSR_ASR_WHYMISS_REASON_CD,
	NULL DM_LSR_ASR_Z_ACTION_CD,
	NULL DM_LSR_ASR_NC_CD,
	LSR.DM_LSR_ASSGN_JEOP_FLAG DM_LSR_ASR_ASSGN_JEOP_FLAG,
	LSR.DM_LSR_DELAY_ORD_JEOP_FLAG DM_LSR_ASR_DELAY_ORD_JEOP_FLAG,
	NULL DM_LSR_ASR_INV_DPT_WHYMISS_FLG,
	LSR.DM_LSR_ASSGN_MIN_JEOP_SENT_DT DM_LSR_ASR_ASGMN_JEOP_SENT_DT,
	LSR.DM_LSR_ASSGN_JEOP_NI DM_LSR_ASR_ASSGN_JEOP_NI,
	LSR.DM_LSR_INSTL_JEOP_FLAG DM_LSR_ASR_INSTL_JEOP_FLAG,
	LSR.DM_LSR_INSTALL_JEOP_SENT_DT DM_LSR_ASR_INSTL_JEOP_SENT_DT,
	LSR.DM_LSR_INSTALL_JEOP_NI DM_LSR_ASR_INSTL_JEOP_NI,
	LSR.DM_LSR_MSCMT_JEOP_FLAG DM_LSR_ASR_MSCMT_JEOP_FLG,
	LSR.DM_LSR_MISS_COMMIT_JEOP_DT DM_LSR_ASR_MSCMT_JEOP_DT,
	NULL DM_LSR_ASR_LATEST_RECORD_FLAG,
	LSR.DM_LSR_MISS_COMMIT_JEOP_NI DM_LSR_ASR_MISS_COMMIT_JEOP_NI,
	NULL DM_LSR_ASR_TABULATE_OFFICE_CD,
	NULL DM_LSR_ASR_BILL_ACCT_NO,
	NULL DM_LSR_ASR_TRUNK_GROUP_CD,
	NULL DM_LSR_ASR_RSN_IND,
	LSR.DM_LSR_APP_DT DM_LSR_ASR_APP_DT,
	NULL DM_LSR_ASR_EX_COMPANY_CKT_ID,
	NULL DM_LSR_ASR_CLASS_SVC,
	LSR.DM_LSR_DUE_CMP_DT DM_LSR_ASR_DUE_CMP_DT,
	NULL DM_LSR_ASR_CLLI_A_CD,
	NULL DM_LSR_ASR_CK_REF_NO,
	NULL DM_LSR_ASR_TRUNK_GROUP_ID,
	NULL DM_LSR_ASR_NCI,
	LSR.DM_LSR_TXN_EFCTV_COMMIT_DT DM_LSR_ASR_TXN_EFCTV_COMMIT_DT,
	LSR.DM_LSR_TXN_DSRD_DT DM_LSR_ASR_TXN_DSRD_DT,
	LSR.DM_LSR_TXN_EFCTV_BILL_DT DM_LSR_ASR_TXN_EFCTV_BILL_DT,
	LSR.DM_LSR_ORD_TYPE_CD DM_LSR_ASR_ORD_TYPE_CD,
--PR Performance Fixes Start
-- Reverted columns from Trbl Fact to LSR Fact
	LSR.DM_LSR_REPAIR_HOURS DM_LSR_ASR_REPAIR_HOURS,
	LSR.DM_LSR_COMMITMENT_MET DM_LSR_ASR_COMMITMENT_MET,
	LSR.DM_LSR_OOS_FLAG DM_LSR_ASR_OOS_FLAG,
	LSR.DM_LSR_REPEAT_30_FLAG DM_LSR_ASR_REPEAT_30_FLAG,
	LSR.DM_LSR_DSP_CD DM_LSR_ASR_DSP_CD,
	LSR.DM_LSR_DSP_SUB_CD DM_LSR_ASR_DSP_SUB_CD,
	LSR.DM_LSR_SVC_OFFICE DM_LSR_ASR_SVC_OFFICE,
	LSR.DM_LSR_CLEARING_EMP DM_LSR_ASR_CLEARING_EMP,
	LSR.DM_LSR_CUST_NAME DM_LSR_ASR_CUST_NAME,
--PR Performance Fixes End
	LSR.DM_LSR_CLEC_NAME DM_LSR_ASR_CLEC_NAME,
--PR Performance Fixes Start
-- Reverted columns from Trbl Fact to LSR Fact
	LSR.DM_LSR_TRBL7_FLAG DM_LSR_ASR_TRBL7_FLAG,
	LSR.DM_LSR_TRBL30_FLAG DM_LSR_ASR_TRBL30_FLAG,
--PR Performance Fixes End
	LSR.DM_LSR_DUE_DAY_MISS_FLAG DM_LSR_ASR_DUE_DAY_MISS_FLAG,
	LSR.DM_LSR_USER_NAME DM_LSR_ASR_USER_NAME,
	NULL DM_LSR_ASR_ASSGN_JEOP_CODES,
	NULL DM_LSR_ASR_DELAY_JEOP_CODES,
	NULL DM_LSR_ASR_FAC_JEOP_CODES,
	NULL DM_LSR_ASR_INSTALL_JEOP_CODES,
	NULL DM_LSR_ASR_MSCMT_JEOP_CODES,
--PR Performance Fixes Start
-- Reverted columns from Trbl Fact to LSR Fact
	LSR.DM_LSR_TRBL_COMMIT_DATE DM_LSR_ASR_TRBL_COMMIT_DATE,
	LSR.DM_LSR_TRBL_APPT_DATE DM_LSR_ASR_TRBL_APPT_DATE,
	LSR.DM_LSR_TRBL_CLEAR_DATE DM_LSR_ASR_TRBL_CLEAR_DATE,
	LSR.DM_LSR_TRBL_CREATE_DATE DM_LSR_ASR_TRBL_CREATE_DATE,
	LSR.DM_LSR_TRBL_DISPATCH_FLAG DM_LSR_ASR_TRBL_DISPATCH_FLAG,
	LSR.DM_LSR_TRBL_CNTR_OFF_CD DM_LSR_ASR_TRBL_CNTR_OFF_CD,
--PR Performance Fixes End
	NULL DM_LSR_ASR_LTST_REC_MISS_FLG,
	LSR.DM_LSR_REP_MONTH_CD DM_LSR_ASR_REP_MONTH_CD,
	LSR.DM_LSR_SFX_DR_ALL_MNTHS_FLAG DM_LSR_ASR_SFX_DR_MNTHS_FLAG,
	LSR.DM_LSR_ORD_CMP_FLAG DM_LSR_ASR_ORD_CMP_FLAG,
	LSR.DM_LSR_PARTITION_MNTH DM_LSR_ASR_PRTN_MTH,
	LSR.DM_LSR_FEATURES_FLAG DM_LSR_ASR_FEATURES_FLAG,
	NULL DM_LSR_ASR_PROJ_IND,
	LSR.DM_LSR_DELAY_JEOP_DT DM_LSR_ASR_DELAY_JEOP_DT,
	LSR.DM_LSR_ASSGN_JEOP_MET_STDS DM_LSR_ASR_ASSGN_JEOP_MET_STDS,
	LSR.DM_LSR_ASSGN_JEOP_CNT DM_LSR_ASR_ASSGN_JEOP_CNT,
	LSR.DM_LSR_INSTL_JEOP_MET_STDS DM_LSR_ASR_INSTL_JEOP_MET_STDS,
	LSR.DM_LSR_INSTL_JEOP_CNT DM_LSR_ASR_INSTL_JEOP_CNT,
	LSR.DM_LSR_MSCMT_JEOP_MET_STDS DM_LSR_ASR_MSCMT_JEOP_MET_STDS,
	LSR.DM_LSR_MSCMT_JEOP_CNT DM_LSR_ASR_MSCMT_JEOP_CNT,
	LSR.DM_LSR_CMNT_STAT_CD_FLAG DM_LSR_ASR_CMNT_STAT_CD_FLAG,
	-- CCR 10153 START
	LSR.DM_LSR_LAT_FLAG DM_LSR_ASR_LAT_FLAG,
	LSR.DM_LSR_LAT_MISS_FLAG DM_LSR_ASR_LAT_MISS_FLAG
	-- CCR 10153 END
FROM
	DM_WST_APP.NMPW_DM_PR_LSR_PRODUCT LSR
WHERE
  LSR.DM_LSR_RPTG_MONTH = '201109'
UNION ALL
-- All ASR Orders
SELECT /*+ INDEX(ASR NMPW_DM_PR_ASR_PRODUCT_IE01)*/
	ASR.DM_ASR_ID DM_LSR_ASR_ID,
	ASR.DM_ASR_LSR_ORD_NO DM_LSR_ASR_LORD_NO,
	ASR.DM_ASR_ORD_NO DM_LSR_ASR_AORD_NO,
	NULL DM_LSR_ASR_REGION_CD,
	ASR.DM_ASR_ORD_ID DM_LSR_ASR_ORD_ID,
	NULL DM_LSR_ASR_AUDIT_RC_CD,
	ASR.DM_ASR_CCNA_CD DM_LSR_ASR_CCNA_CD,
	ASR.DM_ASR_DISPATCH_FLAG DM_LSR_ASR_DISPATCH_FLAG,
	NULL DM_LSR_ASR_BILL_TYPE_CD,
	NULL DM_LSR_ASR_CMP_LTERM,
	NULL DM_LSR_ASR_CREATE_LTERM,
	ASR.DM_ASR_DUE_SCHEDULE_DT DM_LSR_ASR_DUE_SCHEDULE_DT,
	NULL DM_LSR_ASR_EXPNDD_SVC_CLASS_CD,
	NULL DM_LSR_ASR_SVC_TYPE_CD,
	ASR.DM_ASR_STATE_CD DM_LSR_ASR_STATE_CD,
	ASR.DM_ASR_SUBCLASS_CD1 DM_LSR_ASR_SUBCLASS_CD1,
	ASR.DM_ASR_SUBCLASS_CD2 DM_LSR_ASR_SUBCLASS_CD2,
	ASR.DM_ASR_SUBCLASS_CD3 DM_LSR_ASR_SUBCLASS_CD3,
	ASR.DM_ASR_SUBCLASS_CD4 DM_LSR_ASR_SUBCLASS_CD4,
	ASR.DM_ASR_SUBCLASS_CD5 DM_LSR_ASR_SUBCLASS_CD5,
	ASR.DM_ASR_SUBCLASS_CD6 DM_LSR_ASR_SUBCLASS_CD6,
	ASR.DM_ASR_EFCTV_CMP_DT DM_LSR_ASR_CMP_DT,
	NULL DM_LSR_ASR_CUST_REQ_CD,
	ASR.DM_ASR_DAYS_TO_INSTALL DM_LSR_ASR_DAYS_TO_INSTALL,
	ASR.DM_ASR_AVG_INSTALL_FLAG DM_LSR_ASR_AVG_INSTALL_FLAG,
	ASR.DM_ASR_DELAY_DAY_COUNT DM_LSR_ASR_DELAY_DAYS,
	ASR.DM_ASR_ORD_STATUS_CD DM_LSR_ASR_ORD_STATUS_CD,
	ASR.DM_ASR_BIZ_DT DM_LSR_ASR_BIZ_DT,
	ASR.DM_ASR_C2C_FCC_CD DM_LSR_ASR_C2C_FCC_CD,
	NULL DM_LSR_ASR_SUFFIX_C12_HF_FLAG,
	NULL DM_LSR_ASR_SUFFIX_C12_CW_FLAG,
	NULL DM_LSR_ASR_SUFFIX_C12_NA_FLAG,
	NULL DM_LSR_ASR_SUFFIX_C12_CR_FLAG,
	NULL DM_LSR_ASR_SUFFIX_C12_CD_FLAG,
	NULL DM_LSR_ASR_SUFFIX_CDDD_FLAG,
	NULL DM_LSR_ASR_SUFFIX_BFR_FLAG,
	NULL DM_LSR_ASR_SUFFIX_LOA_FLAG,
	NULL DM_LSR_ASR_SUFFIX_VCDDD_FLAG,
	NULL DM_LSR_ASR_SUFFIX_SID_FLAG,
	NULL DM_LSR_ASR_SUFFIX_FIX_FLAG,
	NULL DM_LSR_ASR_SUFFIX_FRLAY_FLAG,
	NULL DM_LSR_ASR_SUFFIX_FRLAYS_FLAG,
	NULL DM_LSR_ASR_SUFFIX_FRLAYH_FLAG,
	NULL DM_LSR_ASR_SUFFIX_DSCMP_FLAG,
	NULL DM_LSR_ASR_SUFFIX_C15_BLK_FLAG,
	NULL DM_LSR_ASR_SFX_C14_RCDS_FLAG,
	NULL DM_LSR_ASR_SUFFIX_C12_DR_FLAG,
	NULL DM_LSR_ASR_SUFFIX_DROSP_FLAG,
	NULL DM_LSR_ASR_SUFFIX_DRCOE_FLAG,
	NULL DM_LSR_ASR_SUFFIX_DREQ_FLAG,
	NULL DM_LSR_ASR_ORD_CMP_CNCL_FLAG,
	NULL DM_LSR_ASR_CONV_TYPE_IND,
	NULL DM_LSR_ASR_CONV_MET_FLAG,
	NULL DM_LSR_ASR_CLEC_CAUSED_FLAG,
	ASR.DM_ASR_PLANNED_CMP_DT DM_LSR_ASR_PLANNED_CMP_DT,
	ASR.DM_ASR_ACTUAL_CMP_DT DM_LSR_ASR_ACTUAL_CMP_DT,
	ASR.DM_ASR_RPTG_MONTH DM_LSR_ASR_RPTG_MONTH,
	ASR.DM_ASR_EXCL_CCNA_FLAG DM_LSR_ASR_EXCL_CCNA_FLAG,
	ASR.DM_ASR_VERSION DM_LSR_ASR_VERSION,
	ASR.DM_ASR_ORD_CREATE_DT DM_LSR_ASR_ORD_CREATE_DT,
	ASR.DM_ASR_PURCHASE_ORD_NO DM_LSR_ASR_PURCHASE_ORD_NO,
	ASR.DM_ASR_ORD_DTL_COEFFICIENT DM_LSR_ASR_ORD_DTL_COEFFICIENT,
	NULL DM_LSR_ASR_OMT_TYPE,
	ASR.DM_ASR_BILL_EFCTV_DT DM_LSR_ASR_BILL_EFCTV_DT,
	NULL DM_LSR_ASR_BILL_TN,
	ASR.DM_ASR_CKT_TN DM_LSR_ASR_CKT_TN,
	ASR.DM_ASR_RECORD_TYPE_CD DM_LSR_ASR_RECORD_TYPE_CD,
	ASR.DM_ASR_PROD_CLASS DM_LSR_ASR_PROD_CLASS,
	ASR.DM_ASR_ORIG_CLASS_NAME DM_LSR_ASR_ORIG_CLASS_NAME,
	ASR.DM_ASR_PRIMARY_CLASS_FLAG DM_LSR_ASR_PRIMARY_CLASS_FLAG,
	ASR.DM_ASR_INTERVAL_NO DM_LSR_ASR_INTERVAL_NO,
	ASR.DM_ASR_ITEM_NO DM_LSR_ASR_ITEM_NO,
	ASR.DM_ASR_REQ_DUE_DT DM_LSR_ASR_REQ_DUE_DT,
	NULL DM_LSR_ASR_COIN_TYPE_CD,
	NULL DM_LSR_ASR_COMPANY_CD,
	NULL DM_LSR_ASR_CBSS_CUST_ACCT_NO,
	NULL DM_LSR_ASR_SVC_CLASS_CD,
	ASR.DM_ASR_CUST_SVC_DT DM_LSR_ASR_CUST_SVC_DT,
	NULL DM_LSR_ASR_CUST_REF_STATUS_CD,
	NULL DM_LSR_ASR_CUST_REF,
	ASR.DM_ASR_SELECT_SVC_TYPE_CD DM_LSR_ASR_SELECT_SVC_TYPE_CD,
	NULL DM_LSR_ASR_BILL_POSITION_NO,
	ASR.DM_ASR_UID DM_LSR_ASR_UID,
	ASR.DM_ASR_INVALID_IND DM_LSR_ASR_INVALID_IND,
	ASR.DM_ASR_SVC_CD DM_LSR_ASR_SVC_CD,
	ASR.DM_ASR_WHY_MISS_REASON_CD DM_LSR_ASR_WHYMISS_REASON_CD,
	ASR.DM_ASR_Z_ACTION_CD DM_LSR_ASR_Z_ACTION_CD,
	ASR.DM_ASR_NC_CD DM_LSR_ASR_NC_CD,
	ASR.DM_ASR_ASSGN_JEOP_FLAG DM_LSR_ASR_ASSGN_JEOP_FLAG,
	ASR.DM_ASR_DELAY_ORD_JEOP_FLAG DM_LSR_ASR_DELAY_ORD_JEOP_FLAG,
	ASR.DM_ASR_INV_DEPT_WHY_MISS_FLAG DM_LSR_ASR_INV_DPT_WHYMISS_FLG,
	ASR.DM_ASR_ASSGN_MIN_JEOP_SENT_DT DM_LSR_ASR_ASGMN_JEOP_SENT_DT,
	ASR.DM_ASR_ASSGN_JEOP_NI DM_LSR_ASR_ASSGN_JEOP_NI,
	ASR.DM_ASR_INSTALL_JEOP_FLAG DM_LSR_ASR_INSTL_JEOP_FLAG,
	ASR.DM_ASR_INSTALL_JEOP_SENT_DT DM_LSR_ASR_INSTL_JEOP_SENT_DT,
	ASR.DM_ASR_INSTALL_JEOP_NI DM_LSR_ASR_INSTL_JEOP_NI,
	ASR.DM_ASR_MISS_COMMIT_JEOP_FLAG DM_LSR_ASR_MSCMT_JEOP_FLG,
	ASR.DM_ASR_MISS_COMMIT_JEOP_DT DM_LSR_ASR_MSCMT_JEOP_DT,
	ASR.DM_ASR_LATEST_RECORD_FLAG DM_LSR_ASR_LATEST_RECORD_FLAG,
	ASR.DM_ASR_MISS_COMMIT_JEOP_NI DM_LSR_ASR_MISS_COMMIT_JEOP_NI,
	ASR.DM_ASR_TABULATE_OFFICE_CD DM_LSR_ASR_TABULATE_OFFICE_CD,
	ASR.DM_ASR_BILL_ACCT_NO DM_LSR_ASR_BILL_ACCT_NO,
	ASR.DM_ASR_TRUNK_GROUP_CD DM_LSR_ASR_TRUNK_GROUP_CD,
	ASR.DM_ASR_RSN_IND DM_LSR_ASR_RSN_IND,
	ASR.DM_ASR_APP_DT DM_LSR_ASR_APP_DT,
	ASR.DM_ASR_EX_COMPANY_CKT_ID DM_LSR_ASR_EX_COMPANY_CKT_ID,
	ASR.DM_ASR_CLASS_SVC DM_LSR_ASR_CLASS_SVC,
	ASR.DM_ASR_DUE_CMP_DT DM_LSR_ASR_DUE_CMP_DT,
	ASR.DM_ASR_CLLI_A_CD DM_LSR_ASR_CLLI_A_CD,
	ASR.DM_ASR_CK_REF_NO DM_LSR_ASR_CK_REF_NO,
	ASR.DM_ASR_TRUNK_GROUP_ID DM_LSR_ASR_TRUNK_GROUP_ID,
	ASR.DM_ASR_NCI DM_LSR_ASR_NCI,
	ASR.DM_ASR_TXN_EFCTV_COMMIT_DT DM_LSR_ASR_TXN_EFCTV_COMMIT_DT,
	ASR.DM_ASR_TXN_DSRD_DT DM_LSR_ASR_TXN_DSRD_DT,
	ASR.DM_ASR_TXN_EFCTV_BILL_DT DM_LSR_ASR_TXN_EFCTV_BILL_DT,
	NULL DM_LSR_ASR_ORD_TYPE_CD,
	ASR.DM_ASR_REPAIR_HOURS DM_LSR_ASR_REPAIR_HOURS,
	ASR.DM_ASR_COMMITMENT_MET DM_LSR_ASR_COMMITMENT_MET,
	ASR.DM_ASR_OOS_FLAG DM_LSR_ASR_OOS_FLAG,
	ASR.DM_ASR_REPEAT_30_FLAG DM_LSR_ASR_REPEAT_30_FLAG,
	ASR.DM_ASR_DSP_CD DM_LSR_ASR_DSP_CD,
	ASR.DM_ASR_DSP_SUB_CD DM_LSR_ASR_DSP_SUB_CD,
	ASR.DM_ASR_SVC_OFFICE DM_LSR_ASR_SVC_OFFICE,
	ASR.DM_ASR_CLEARING_EMP DM_LSR_ASR_CLEARING_EMP,
	ASR.DM_ASR_CUST_NAME DM_LSR_ASR_CUST_NAME,
	ASR.DM_ASR_CLEC_NAME DM_LSR_ASR_CLEC_NAME,
	ASR.DM_ASR_TRBL7_FLAG DM_LSR_ASR_TRBL7_FLAG,
	ASR.DM_ASR_TRBL30_FLAG DM_LSR_ASR_TRBL30_FLAG,
	ASR.DM_ASR_DUE_DAY_MISS_FLAG DM_LSR_ASR_DUE_DAY_MISS_FLAG,
	ASR.DM_ASR_USER_NAME DM_LSR_ASR_USER_NAME,
	ASR.DM_ASR_ASSGN_JEOP_CODES DM_LSR_ASR_ASSGN_JEOP_CODES,
	ASR.DM_ASR_DELAY_JEOP_CODES DM_LSR_ASR_DELAY_JEOP_CODES,
	ASR.DM_ASR_FACILITIES_JEOP_CODES DM_LSR_ASR_FAC_JEOP_CODES,
	ASR.DM_ASR_INSTALL_JEOP_CODES DM_LSR_ASR_INSTALL_JEOP_CODES,
	ASR.DM_ASR_MSCMT_JEOP_CODES DM_LSR_ASR_MSCMT_JEOP_CODES,
	ASR.DM_ASR_TRBL_COMMIT_DATE DM_LSR_ASR_TRBL_COMMIT_DATE,
	ASR.DM_ASR_TRBL_APPT_DATE DM_LSR_ASR_TRBL_APPT_DATE,
	ASR.DM_ASR_TRBL_CLEAR_DATE DM_LSR_ASR_TRBL_CLEAR_DATE,
	ASR.DM_ASR_TRBL_CREATE_DATE DM_LSR_ASR_TRBL_CREATE_DATE,
	ASR.DM_ASR_TRBL_DISPATCH_FLAG DM_LSR_ASR_TRBL_DISPATCH_FLAG,
	ASR.DM_ASR_TRBL_CNTR_OFF_CD DM_LSR_ASR_TRBL_CNTR_OFF_CD,
	ASR.DM_ASR_LATEST_REC_WHY_MISS_FLG DM_LSR_ASR_LTST_REC_MISS_FLG,
	ASR.DM_ASR_REP_MONTH_CD DM_LSR_ASR_REP_MONTH_CD,
	NULL DM_LSR_ASR_SFX_DR_MNTHS_FLAG,
	NULL DM_LSR_ASR_ORD_CMP_FLAG,
	MOD((TO_NUMBER(SUBSTR(ASR.DM_ASR_RPTG_MONTH,1,4))*12) + TO_NUMBER(SUBSTR(ASR.DM_ASR_RPTG_MONTH,5,2)),14) DM_LSR_ASR_PRTN_MTH,
	NULL DM_LSR_ASR_FEATURES_FLAG,
	ASR.DM_ASR_PROJ_IND DM_LSR_ASR_PROJ_IND,
	TO_DATE(NULL) DM_LSR_ASR_DELAY_JEOP_DT,
	ASR.DM_ASR_ASSGN_JEOP_MET_STDS DM_LSR_ASR_ASSGN_JEOP_MET_STDS,
	ASR.DM_ASR_ASSGN_JEOP_CNT DM_LSR_ASR_ASSGN_JEOP_CNT,
	ASR.DM_ASR_INSTL_JEOP_MET_STDS DM_LSR_ASR_INSTL_JEOP_MET_STDS,
	ASR.DM_ASR_INSTL_JEOP_CNT DM_LSR_ASR_INSTL_JEOP_CNT,
	ASR.DM_ASR_MSCMT_JEOP_MET_STDS DM_LSR_ASR_MSCMT_JEOP_MET_STDS,
	ASR.DM_ASR_MSCMT_JEOP_CNT DM_LSR_ASR_MSCMT_JEOP_CNT,
	NULL DM_LSR_ASR_CMNT_STAT_CD_FLAG,
	-- CCR 10153 START
	NULL DM_LSR_ASR_LAT_FLAG,
	NULL	DM_LSR_ASR_LAT_MISS_FLAG
	-- CCR 10153 END
FROM
	DM_WST_APP.NMPW_DM_PR_ASR_PRODUCT ASR
WHERE
  ASR.DM_ASR_RPTG_MONTH = '201109')	a11, 
	DM_WST_APP.NMPW_DM_AGGREGATE_DT	a12, 
	DM_WST_APP.NMPW_DM_SUBCLASS_LU	a13, 
	DM_WST_APP.NMPW_DM_MSRMNT_SUBCLASS_LU	a14
where	a11.DM_LSR_ASR_VERSION = a12.DM_AGG_RPTG_VERSION and 
	a11.DM_LSR_ASR_SUBCLASS_CD1 = a13.DM_SUBCLASS_CD1 and 
	a11.DM_LSR_ASR_SUBCLASS_CD2 = a13.DM_SUBCLASS_CD2 and 
	a11.DM_LSR_ASR_SUBCLASS_CD3 = a13.DM_SUBCLASS_CD3 and 
	a13.DM_SUBCLASS_ID = a14.DM_SUBCLASS_ID
 and	(a11.DM_LSR_ASR_CCNA_CD <> '#GT'
 and a11.DM_LSR_ASR_CCNA_CD <> 'BNK'
 and a11.DM_LSR_ASR_CCNA_CD <> 'VEN'
 and a11.DM_LSR_ASR_CCNA_CD <> '#NU'
 and a11.dm_lsr_asr_state_cd = 'MI'
 --and a11.DM_LSR_ASR_DUE_DAY_MISS_FLAG = 'Y'
 and a14.DM_MSRMNT_CD = 'FCCPRV0405'
 and a12.DM_AGG_RPTG_START_DT < a14.DM_MSRMNT_SUBCLASS_RETIRE_DT
 and a14.DM_MSRMNT_SUBCLASS_START_DT < a12.DM_AGG_RPTG_END_DT
 and (((a11.DM_LSR_ASR_ORD_TYPE_CD = 'I'
 or a11.DM_LSR_ASR_ORD_TYPE_CD = 'M'
 or a11.DM_LSR_ASR_ORD_TYPE_CD = 'C'
 or (a11.DM_LSR_ASR_ORD_TYPE_CD = 'O'
 and a11.DM_LSR_ASR_OMT_TYPE = 'PB'))
 and (SUBSTR(a11.DM_LSR_ASR_EXPNDD_SVC_CLASS_CD,1,1) = 'B'
 or SUBSTR(a11.DM_LSR_ASR_EXPNDD_SVC_CLASS_CD,1,1) = 'G'
 or SUBSTR(a11.DM_LSR_ASR_EXPNDD_SVC_CLASS_CD,1,1) = 'R'
 or (SUBSTR(a11.DM_LSR_ASR_EXPNDD_SVC_CLASS_CD,1,1) is null
 and a11.DM_LSR_ASR_ORD_TYPE_CD = 'O'
 and a11.DM_LSR_ASR_OMT_TYPE = 'PB'))
 and a11.DM_LSR_ASR_ORD_STATUS_CD = 5
 and a11.DM_LSR_ASR_DAYS_TO_INSTALL is not null
 and (a11.DM_LSR_ASR_CREATE_LTERM <> a11.DM_LSR_ASR_CMP_LTERM
 or (a11.DM_LSR_ASR_CMP_LTERM is null
 and a11.DM_LSR_ASR_CREATE_LTERM is not null)
 or (a11.DM_LSR_ASR_CMP_LTERM is not null
 and a11.DM_LSR_ASR_CREATE_LTERM is null))
 and a11.DM_LSR_ASR_DUE_SCHEDULE_DT <> To_Date('1900-01-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS')
 and (a11.DM_LSR_ASR_BILL_TYPE_CD <> 'G'
 or a11.DM_LSR_ASR_BILL_TYPE_CD is null)
 and a11.DM_LSR_ASR_CMP_DT >=  a11.DM_LSR_ASR_ORD_CREATE_DT
 and a11.DM_LSR_ASR_SFX_C14_RCDS_FLAG = 'N'
 and a11.DM_LSR_ASR_RECORD_TYPE_CD = 'LSR'
 and (a11.DM_LSR_ASR_FEATURES_FLAG <> 'Y'
 or (a11.DM_LSR_ASR_SUBCLASS_CD1 <> 'UNE'
 and a11.DM_LSR_ASR_SUBCLASS_CD1 <> 'SUB')
 or a11.DM_LSR_ASR_SUBCLASS_CD2 <> 'LOP'
 or a11.DM_LSR_ASR_CCNA_CD <> '#GT')
 and ((a11.DM_LSR_ASR_SUBCLASS_CD1 <> 'LNP'
 and a11.DM_LSR_ASR_ORD_TYPE_CD <> 'O')
 or a11.DM_LSR_ASR_SUBCLASS_CD1 = 'LNP')
 and (SUBSTR(a11.DM_LSR_ASR_EXPNDD_SVC_CLASS_CD,1,1) <> 'T'
 or SUBSTR(a11.DM_LSR_ASR_EXPNDD_SVC_CLASS_CD,1,1) is null))
 or (((a11.DM_LSR_ASR_Z_ACTION_CD <> 'D'
 and a11.DM_LSR_ASR_Z_ACTION_CD <> 'K'
 and a11.DM_LSR_ASR_Z_ACTION_CD <> 'O'
 and a11.DM_LSR_ASR_Z_ACTION_CD <> 'R')
 or a11.DM_LSR_ASR_Z_ACTION_CD is null)
 and a11.DM_LSR_ASR_INV_DPT_WHYMISS_FLG = 'N'
 and (a11.DM_LSR_ASR_INVALID_IND <> 'I'
 or a11.DM_LSR_ASR_INVALID_IND is null)
 and a11.DM_LSR_ASR_RECORD_TYPE_CD = 'ASR'
 and a11.DM_LSR_ASR_LATEST_RECORD_FLAG = 'Y'
 and a11.DM_LSR_ASR_CMP_DT >=  a11.DM_LSR_ASR_APP_DT))
 and a11.DM_LSR_ASR_C2C_FCC_CD = 'FCC'
 and ((a11.DM_LSR_ASR_CCNA_CD = '#GT'
 and a11.DM_LSR_ASR_SUBCLASS_CD1 = 'UNE'
 and a11.DM_LSR_ASR_SUBCLASS_CD2 = 'LOP'
 and a11.DM_LSR_ASR_SUBCLASS_CD4 = 'DSP'
 and (a11.DM_LSR_ASR_SUBCLASS_CD3 = 'NDS'
 or a11.DM_LSR_ASR_SUBCLASS_CD3 = 'DES'))
 or a13.DM_SUBCLASS_CD4 = a11.DM_LSR_ASR_SUBCLASS_CD4)
 and a11.DM_LSR_ASR_EXCL_CCNA_FLAG = 'N'
 and a11.DM_LSR_ASR_BIZ_DT between a12.DM_AGG_RPTG_START_DT and a12.DM_AGG_RPTG_END_DT
 and a12.DM_AGG_RPTG_MONTH = a11.DM_LSR_ASR_RPTG_MONTH
 and a12.DM_AGG_RPTG_DOMAIN_CD = 'PR'
 and a11.DM_LSR_ASR_REP_MONTH_CD = '1'
 and a12.DM_AGG_RPTG_MONTH in ('201109')
 )
group by	a11.DM_LSR_ASR_ID,
	a11.DM_LSR_ASR_RECORD_TYPE_CD,
	a11.DM_LSR_ASR_AORD_NO,
	a11.DM_LSR_ASR_LORD_NO,
	a14.DM_SUB_MSRMNT_CD,
	a11.DM_LSR_ASR_STATE_CD,
	a11.DM_LSR_ASR_CLEC_NAME,
	a11.DM_LSR_ASR_CCNA_CD,
	a11.DM_LSR_ASR_PROD_CLASS,
	a11.DM_LSR_ASR_BILL_TN,
	a11.DM_LSR_ASR_CKT_TN,
	a11.DM_LSR_ASR_DUE_DAY_MISS_FLAG,
	a11.DM_LSR_ASR_DISPATCH_FLAG,
	a11.DM_LSR_ASR_DAYS_TO_INSTALL,
	a11.DM_LSR_ASR_TRBL7_FLAG,
	a11.DM_LSR_ASR_TRBL30_FLAG,
	a12.DM_AGG_RPTG_MONTH,
	a11.dm_lsr_asr_DUE_SCHEDULE_DT,
	a11.DM_LSR_ASR_CMP_DT,
	a11.DM_LSR_ASR_ORD_CREATE_DT,
	a11.DM_LSR_ASR_REQ_DUE_DT;