SELECT	/*+ ORDERED */ a11.DM_LSR_ASR_LORD_NO  Ord_No,
    a11.DM_LSR_ASR_ORD_ID ORD_ID,
	a11.DM_LSR_ASR_STATE_CD  STATE,
	a11.DM_LSR_ASR_CLEC_NAME  CLEC_Name,
	a11.DM_LSR_ASR_CCNA_CD  CCNA,
	a11.DM_LSR_ASR_PROD_CLASS  Class,
	a11.DM_LSR_ASR_SVC_CLASS_CD Svc_Class,
	a11.DM_LSR_ASR_DISPATCH_FLAG Ord_Disp,
	a11.DM_LSR_ASR_CKT_TN  Circuit_TN,
	a11.DM_LSR_ASR_BILL_TN  Billing_TN,
	a11.DM_LSR_ASR_CMP_DT  Completion_date,
	a11.DM_LSR_ASR_TRBL_CREATE_DATE  Trouble_Create_Date,
	a11.DM_LSR_ASR_TRBL_APPT_DATE  Trouble_Appt_Date,
	a11.DM_LSR_ASR_TRBL_COMMIT_DATE  Trouble_Commitment_Date,
	a11.DM_LSR_ASR_TRBL_CLEAR_DATE  Trouble_Clear_Date,
	a11.DM_LSR_ASR_REPAIR_HOURS  Repair_Hrs,
	a11.DM_LSR_ASR_TRBL_DISPATCH_FLAG  Trouble_Dispatch_Flag,
	a11.DM_LSR_ASR_DSP_CD  Disp_Code,
	a11.DM_LSR_ASR_DSP_SUB_CD  Disp_Sub_Code,
	a11.DM_LSR_ASR_CUST_NAME  Customer_Name
FROM	DM_WST_APP.NMPW_DM_PR_LSR_ASR_VIEW	a11, 
	DM_WST_APP.NMPW_DM_AGGREGATE_DT	a12, 
	DM_WST_APP.NMPW_DM_SUBCLASS_LU	a13, 
	DM_WST_APP.NMPW_DM_MSRMNT_SUBCLASS_LU	a14
WHERE	a11.DM_LSR_ASR_VERSION = a12.DM_AGG_RPTG_VERSION AND 
	a11.DM_LSR_ASR_SUBCLASS_CD1 = a13.DM_SUBCLASS_CD1 AND 
	a11.DM_LSR_ASR_SUBCLASS_CD2 = a13.DM_SUBCLASS_CD2 AND 
	a11.DM_LSR_ASR_SUBCLASS_CD3 = a13.DM_SUBCLASS_CD3 AND 
	a13.DM_SUBCLASS_ID = a14.DM_SUBCLASS_ID
 AND	(a11.DM_LSR_ASR_C2C_FCC_CD = 'FCC'
 AND a14.DM_MSRMNT_CD = 'FCCPRV0602'
 AND a12.DM_AGG_RPTG_START_DT < a14.DM_MSRMNT_SUBCLASS_RETIRE_DT
 AND a14.DM_MSRMNT_SUBCLASS_START_DT < a12.DM_AGG_RPTG_END_DT
 AND a11.DM_LSR_ASR_STATE_CD in ('IL','NC','OH','OR','SC')
 AND a11.DM_LSR_ASR_EXCL_CCNA_FLAG = 'N'
 AND a11.DM_LSR_ASR_TRBL7_FLAG = 'Y'
 AND a11.DM_LSR_ASR_CCNA_CD <> '#GT'
 AND a11.DM_LSR_ASR_CCNA_CD <> '#NU'
 AND a11.DM_LSR_ASR_CCNA_CD <> '#CL'
 AND a11.DM_LSR_ASR_CCNA_CD <> 'G01'
 AND (((a11.DM_LSR_ASR_ORD_TYPE_CD = 'I'
 OR a11.DM_LSR_ASR_ORD_TYPE_CD = 'M'
 OR a11.DM_LSR_ASR_ORD_TYPE_CD = 'C'
 OR (a11.DM_LSR_ASR_ORD_TYPE_CD = 'O'
 AND a11.DM_LSR_ASR_OMT_TYPE = 'PB'))
 AND (SUBSTR(a11.DM_LSR_ASR_EXPNDD_SVC_CLASS_CD,1,1) = 'B'
 OR SUBSTR(a11.DM_LSR_ASR_EXPNDD_SVC_CLASS_CD,1,1) = 'G'
 OR SUBSTR(a11.DM_LSR_ASR_EXPNDD_SVC_CLASS_CD,1,1) = 'R'
 OR (SUBSTR(a11.DM_LSR_ASR_EXPNDD_SVC_CLASS_CD,1,1) IS NULL
 AND a11.DM_LSR_ASR_ORD_TYPE_CD = 'O'
 AND a11.DM_LSR_ASR_OMT_TYPE = 'PB'))
 AND a11.DM_LSR_ASR_ORD_STATUS_CD = 5
 AND a11.DM_LSR_ASR_DAYS_TO_INSTALL IS NOT NULL
 AND (a11.DM_LSR_ASR_CREATE_LTERM <> a11.DM_LSR_ASR_CMP_LTERM
 OR (a11.DM_LSR_ASR_CMP_LTERM IS NULL
 AND a11.DM_LSR_ASR_CREATE_LTERM IS NOT NULL)
 OR (a11.DM_LSR_ASR_CMP_LTERM IS NOT NULL
 AND a11.DM_LSR_ASR_CREATE_LTERM IS NULL))
 AND a11.DM_LSR_ASR_DUE_SCHEDULE_DT <> TO_DATE('1900-01-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS')
 AND (a11.DM_LSR_ASR_BILL_TYPE_CD <> 'G'
 OR a11.DM_LSR_ASR_BILL_TYPE_CD IS NULL)
 AND a11.DM_LSR_ASR_CMP_DT >=  a11.DM_LSR_ASR_ORD_CREATE_DT
 AND a11.DM_LSR_ASR_SFX_C14_RCDS_FLAG = 'N'
 AND a11.DM_LSR_ASR_RECORD_TYPE_CD = 'LSR')
 OR (((a11.DM_LSR_ASR_Z_ACTION_CD <> 'D'
 AND a11.DM_LSR_ASR_Z_ACTION_CD <> 'K'
 AND a11.DM_LSR_ASR_Z_ACTION_CD <> 'O'
 AND a11.DM_LSR_ASR_Z_ACTION_CD <> 'R')
 OR a11.DM_LSR_ASR_Z_ACTION_CD IS NULL)
 AND a11.DM_LSR_ASR_INV_DPT_WHYMISS_FLG = 'N'
 AND (a11.DM_LSR_ASR_INVALID_IND <> 'I'
 OR a11.DM_LSR_ASR_INVALID_IND IS NULL)
 AND a11.DM_LSR_ASR_RECORD_TYPE_CD = 'ASR'
 AND a11.DM_LSR_ASR_LATEST_RECORD_FLAG = 'Y'
 AND a11.DM_LSR_ASR_CMP_DT >=  a11.DM_LSR_ASR_APP_DT))
 AND a11.DM_LSR_ASR_BIZ_DT BETWEEN a12.DM_AGG_RPTG_START_DT AND a12.DM_AGG_RPTG_END_DT
 AND a12.DM_AGG_RPTG_MONTH = a11.DM_LSR_ASR_RPTG_MONTH
 AND a12.DM_AGG_RPTG_DOMAIN_CD = 'PR'
 AND a11.DM_LSR_ASR_REP_MONTH_CD = '1'
 AND a12.DM_AGG_RPTG_MONTH IN ('201107'))
ORDER BY a11.DM_LSR_ASR_STATE_CD, a11.DM_LSR_ASR_PROD_CLASS, a11.DM_LSR_ASR_CCNA_CD;