--drop table company;

create table repair_code
(
repair_code  		 	 VARCHAR2(255 BYTE),
repair_code_desc     	 VARCHAR2(255 BYTE),
trbl_found_number        VARCHAR2(255 BYTE),
trbl_found_desc          VARCHAR2(255 BYTE),
disp                     VARCHAR2(255 BYTE)
);

select * from repair_code;

commit;

INSERT ALL
into repair_code values ('75','RECEIVER OFF HOOK','52','receiverOffHook','CPE')
into repair_code values ('102','ANCHOR','46','outsidePlantEquipment','FAC')
into repair_code values ('103','GUY','46','outsidePlantEquipment','FAC')
into repair_code values ('104','POLE','46','outsidePlantEquipment','FAC')
into repair_code values ('201','FIOS_SET_TOP_BOXES/REMOTES','54','cpeTelcoMaintained','CPE')
into repair_code values ('202','FIOS_INSIDE_PROBLEM','54','cpeTelcoMaintained','CPE')
into repair_code values ('203','FIOS_FTTP_NETWORK','47','outsidePlantFiberOptic','FAC')
into repair_code values ('204','FIOS_VIDEO_TRANSPORT_NETWORK','47','outsidePlantFiberOptic','FAC')
into repair_code values ('205','FIOS ONT/BBU/PSU','45','outsideTerminals','FAC')
into repair_code values ('302','CONNECTING BLOCK/TERMINAL','45','outsideTerminals','FAC')
into repair_code values ('305','HANDHOLES','46','outsidePlantEquipment','FAC')
into repair_code values ('306','BUILDOUT CAPACITOR','48','outsidePlantOther','FAC')
into repair_code values ('307','SPLICE CASE','45','outsidePlantEquipment','FAC')
into repair_code values ('308','PEDESTAL','45','outsidePlantEquipment','FAC')
into repair_code values ('310','LOAD COIL AND CASE','48','outsidePlantOther','FAC')
into repair_code values ('311','SHIELD BOND / HARNESS','44','outsidePlantEquipment','FAC')
into repair_code values ('312','CONDUCTOR','44','outsidePlantEquipment','FAC')
into repair_code values ('313','SPLICING CONNECTOR','44','outsidePlantEquipment','FAC')
into repair_code values ('314','SPLICE ENCAPSULATION','44','outsidePlantEquipment','FAC')
into repair_code values ('318','SHEATH / SHIELD','44','outsidePlantEquipment','FAC')
into repair_code values ('327','INDUCTION NEUTRAL TRANSFO','48','outsidePlantOther','FAC')
into repair_code values ('339','OTHER','48','outsidePlantOther','FAC')
into repair_code values ('341','FIBER SPLICE CASE','47','outsidePlantFiberOptic','FAC')
into repair_code values ('342','FIBER MECHANICAL SPLICE','47','outsidePlantFiberOptic','FAC')
into repair_code values ('343','FIBER FUSION SPLICE','47','outsidePlantFiberOptic','FAC')
into repair_code values ('344','FIBER CONDUCTOR','47','outsidePlantFiberOptic','FAC')
into repair_code values ('352','XCONNECT WIRING','44','outsideWire','FAC')
into repair_code values ('353','XCONNECT HOUSING','46','outsidePlantEquipment','FAC')
into repair_code values ('502','ALARMS','2','centralOffice','CO')
into repair_code values ('506','BATTERY','2','centralOffice','CO')
into repair_code values ('511','911 EQUIPMENT CITIZENS','2','centralOffice','CO')
into repair_code values ('514','FILTER','2','centralOffice','CO')
into repair_code values ('516','BREAKER','2','centralOffice','CO')
into repair_code values ('517','FUSE','2','centralOffice','CO')
into repair_code values ('518','GAS TUBE PROTECTION','2','centralOffice','CO')
into repair_code values ('520','GENERATOR RINGER','2','centralOffice','CO')
into repair_code values ('526','POWER BOARD','2','centralOffice','CO')
into repair_code values ('527','POWER SUPPLY','2','centralOffice','CO')
into repair_code values ('529','RECORDER/INTERCEPT EQUIP','2','centralOffice','CO')
into repair_code values ('530','RECTIFIER/CHARGERS','2','centralOffice','CO')
into repair_code values ('532','TRANSFER SWITCH','2','centralOffice','CO')
into repair_code values ('534','LOOP TREATMENT','2','centralOffice','CO')
into repair_code values ('540','TERMINAL BLOCK','2','centralOffice','CO')
into repair_code values ('541','TEST CIRCUIT','2','centralOffice','CO')
into repair_code values ('546','WIRING CENT OFC','2','centralOffice','CO')
into repair_code values ('547','PROGRAMMING (INCL PIC)','57','assigningProvisioning','FAC')
into repair_code values ('550','COMMON EQUIPMENT (PCBC)','2','centralOffice','CO')
into repair_code values ('561','TAPE DISC DRIVES','2','centralOffice','CO')
into repair_code values ('562','COOLING UNIT','2','centralOffice','CO')
into repair_code values ('563','TRANSLATIONS','2','centralOffice','CO')
into repair_code values ('564','LINE CARD (PCB)','2','centralOffice','CO')
into repair_code values ('565','TRUNK CIRCUIT (PCB)','2','centralOffice','CO')
into repair_code values ('566','CENTREX','2','centralOffice','CO')
into repair_code values ('567','BMC EQUIPMENT','2','centralOffice','CO')
into repair_code values ('570','INVERTER','2','centralOffice','CO')
into repair_code values ('571','SS7 EQUIPMENT','2','centralOffice','CO')
into repair_code values ('572','BITS CLOCK','2','centralOffice','CO')
into repair_code values ('575','VOICE MAIL EQUIPMENT','2','centralOffice','CO')
into repair_code values ('577','MICROWAVE EQUIPMENT','2','centralOffice','CO')
into repair_code values ('578','DACS EQUIPMENT','2','centralOffice','CO')
into repair_code values ('579','SPECIAL EQUIPMENT','2','centralOffice','CO')
into repair_code values ('580','FIBER TERMINAL EQUIPMENT','2','centralOffice','CO')
into repair_code values ('581','CIRCUIT EQUIPMENT','2','centralOffice','CO')
into repair_code values ('582','DSL EQUIPMENT CO','2','centralOffice','CO')
into repair_code values ('583','ENET SWITCH','2','centralOffice','CO')
into repair_code values ('585','ANALOG SUBCRIBER CARRIER','51','coConcentrator','CO')
into repair_code values ('590','DIGITAL CARRIER<24 CHANNE','51','coConcentrator','CO')
into repair_code values ('591','LINE REPEATER','2','centralOffice','CO')
into repair_code values ('592','ATM/FRAME RELAY EQUIPMENT','2','centralOffice','CO')
into repair_code values ('602','ALARM EQUIPMENT -REMOTE','2','centralOffice','CO')
into repair_code values ('606','BATTERY - REMOTE','2','centralOffice','CO')
into repair_code values ('614','FILTER-REMOTE','2','centralOffice','CO')
into repair_code values ('616','BREAKER - REMOTE','2','centralOffice','CO')
into repair_code values ('617','FUSE-REMOTE','2','centralOffice','CO')
into repair_code values ('618','GAS TUBE PROTECTION-REMOT','2','centralOffice','CO')
into repair_code values ('620','GENERATOR RINGER-REMOTE','2','centralOffice','CO')
into repair_code values ('626','POWER BOARD-REMOTE','2','centralOffice','CO')
into repair_code values ('627','POWER SUPPLY-REMOTE','2','centralOffice','CO')
into repair_code values ('630','RECTIFIER/CHARGERS-REMOTE','2','centralOffice','CO')
into repair_code values ('632','TRANSFER SWITCH-REMOTE','2','centralOffice','CO')
into repair_code values ('640','TERMINAL BLOCK-REMOTE','2','centralOffice','CO')
into repair_code values ('641','TEST CIRCUIT-REMOTE','2','centralOffice','CO')
into repair_code values ('646','WIRING-REMOTE','2','centralOffice','CO')
into repair_code values ('647','PROGRAMMING-REMOTE','57','assigningProvisioning','FAC')
into repair_code values ('650','COMMON EQUIP(PCBC)-REMOTE','2','centralOffice','CO')
into repair_code values ('662','COOLING UNIT-REMOTE','2','centralOffice','CO')
into repair_code values ('664','LINE CARDS (PCB)-REMOTE','2','centralOffice','CO')
into repair_code values ('665','HOST REMOTE LINKS','2','centralOffice','CO')
into repair_code values ('679','SPECIAL EQUIPMENT-REMOTE','2','centralOffice','CO')
into repair_code values ('680','FIBER TERML EQUIP-REMOTE','2','centralOffice','CO')
into repair_code values ('682','DSL EQUIPMENT-REMOTE','2','centralOffice','CO')
into repair_code values ('683','ENET SWITCH REMOTE','2','centralOffice','CO')
into repair_code values ('684','WIFI GATEWAY','2','centralOffice','CO')
into repair_code values ('685','MANAGED ROUTER','2','centralOffice','CO')
into repair_code values ('686','WIFI ACCESS POINT','2','centralOffice','CO')
into repair_code values ('690','DIGITAL CXR<24 CH-REMOTE','2','centralOffice','CO')
into repair_code values ('692','ATM/FRAME RELAY EQUIPMENT','2','centralOffice','CO')
into repair_code values ('702','CUST EQUIP/WIRE(RENT,LOAN)','54','cpeTelcoMaintained','CPE')
into repair_code values ('703','CUST EQ/WIRE W/O MAINT','31','cpeCustomerResponsibility','CPE')
into repair_code values ('704','CUST EQ/WIRE W/MAINT','54','cpeTelcoMaintained','CPE')
into repair_code values ('705','CUST EQ/WIRE UNDER WARRANTY','54','cpeTelcoMaintained','CPE')
into repair_code values ('706','CALLER ID COMP PROVIDED','54','cpeTelcoMaintained','CPE')
into repair_code values ('707','CALLER ID CUSTOMER OWNED','4','customerProvidedEquipment','CPE')
into repair_code values ('708','PAYSTATION AND EQUIP COMP','24','publicServicesCoinSet','EXC')
into repair_code values ('709','PAYSTATION  COCOT','24','publicServicesCoinSet','EXC')
into repair_code values ('721','CONNECT COMPANY EQUIP','59','referredOut','REF')
into repair_code values ('722','MOBILE EQUIPMENT','49','coEquipmentOther','CO')
into repair_code values ('723','CITIZEN LONG DISTANCE','60','network','FAC')
into repair_code values ('724','TRAFFIC RECORDING EQUIP','49','coEquipmentOther','CO')
into repair_code values ('725','COMPANY OWNED DATA EQUIP','36','data','CO')
into repair_code values ('726','FRONTIER TOLL FREE','60','network','FAC')
into repair_code values ('727','CITIZEN INTERNET','36','data','CO')
into repair_code values ('728','911 EQUIP CONNECTING COMP','59','referredOut','REF')
into repair_code values ('729','CUSTOMER EDUCATION','25','customerOperatingInstructions','CPE')
into repair_code values ('730','PIC VERICATION','57','assigningProvisioning','FAC')
into repair_code values ('731','ISP CONNECTION FAILURE','36','data','CO')
into repair_code values ('732','FIRE CALL EQUIPMENT','49','coEquipmentOther','CO')
into repair_code values ('733','FRONTIER DSL LOOP','36','outsidePlantEquipment','CO')
into repair_code values ('734','DSL MODEM','54','cpeTelcoMaintained','CPE')
into repair_code values ('735','DSL COMPUTER','31','cpeCustomerResponsibility','CPE')
into repair_code values ('736','CUSTOMER NETWORK EQUIP','31','cpeCustomerResponsibility','CPE')
into repair_code values ('751','SATELLITE DISH','46','outsidePlantEquipment','FAC')
into repair_code values ('752','SATELLITE RADIO','46','outsidePlantEquipment','FAC')
into repair_code values ('753','SATELLITE MODEM','54','cpeTelcoMaintained','CPE')
into repair_code values ('754','COAXIAL CABLE','44','outsideWire','FAC')
into repair_code values ('802','AERIAL DROP','44','outsideWire','FAC')
into repair_code values ('803','BURIED DROP','44','outsideWire','FAC')
into repair_code values ('804','DISTRIBUTION WIRE  (RDW)','44','outsideWire','FAC')
into repair_code values ('805','PROTECTOR','45','outsideTerminals','FAC')
into repair_code values ('806','NID / DEMARC','45','outsideTerminals','FAC')
into repair_code values ('812','DSL SPLITTER/FILTER','45','cpeTelcoMaintained','FAC')
into repair_code values ('916','STANDBY GENERATORS','46','outsidePlantEquipment','FAC')
into repair_code values ('923','AIR PRESSURE EQUIPMENT','46','outsidePlantEquipment','FAC')
into repair_code values ('988','NO TROUBLE FOUND','13','noTroubleFound','NTF')
into repair_code values ('990','TEST OK','23','testOK','NTF')
select * from dual;

