-- Step 1 - check the measures table to see where the data is coming from, and which column we are using
SEL * FROM C2C_CPODS.C2C_RUL_SUB_MTRC_MEAS
WHERE SUB_MTRC_NO = 'MR-2-01-3563'
AND DW_ST_CD = 'CA';

-- C2C_FCT_MR_ACCSLN_PRD, Count Distinct LN_ID

-- Raw data
SEL * FROM C2C_CPODS_VWMC.C2C_FCT_MR_ACCSLN_SUB_MTRC
WHERE YR_MTH_NO = 201607
AND DW_ST_CD = 'FL'
AND SUB_MTRC_NO in ('MR-2-01-3561')
AND CLEC_GRP_CD = '229'
AND DNMNTR_INCLD_IND = 1
AND ROW_INCLD_IND = 1
;
-- 68598 rows

-- Aggregated Result
SEL COUNT(DISTINCT LN_ID)
FROM C2C_CPODS_VWMC.C2C_FCT_MR_ACCSLN_SUB_MTRC
WHERE YR_MTH_NO = 201604
AND DW_ST_CD = 'CA'
AND SUB_MTRC_NO = 'MR-2-01-3563'
AND CLEC_CD = '100'
AND DNMNTR_INCLD_IND = 1
AND ROW_INCLD_IND = 1



--- PR-4-01-2111 - CLEC

SEL * FROM C2C_CPODS.C2C_RUL_SUB_MTRC_MEAS
WHERE SUB_MTRC_NO = 'PR-4-01-2111'
AND DW_ST_CD = 'CA';


-- Raw data
SEL * FROM C2C_CPODS_VWMC.C2C_FCT_PR_SVCORD_SUB_MTRC
WHERE YR_MTH_NO = 201604
AND DW_ST_CD = 'CA'
AND SUB_MTRC_NO = 'PR-4-01-2111'
AND CLEC_CD = 'BUL'
AND DNMNTR_INCLD_IND = 1
AND ROW_INCLD_IND = 1
;
-- 3 rows

-- Aggregated Result
SEL COUNT(DISTINCT PON)
FROM C2C_CPODS_VWMC.C2C_FCT_PR_SVCORD_SUB_MTRC
WHERE YR_MTH_NO = 201604
AND DW_ST_CD = 'CA'
AND SUB_MTRC_NO = 'PR-4-01-2111'
AND CLEC_CD = 'BUL'
AND DNMNTR_INCLD_IND = 1
AND ROW_INCLD_IND = 1
;
-- 2

-- Report fact data
SEL * FROM C2C_CPODS_VWMC.C2C_RPT_FCT_SUB_MTRC
WHERE YR_MTH_NO = 202212
AND DW_ST_CD = 'IN'
AND SUB_MTRC_NO = 'MR-2-01-2110'
ORDER BY CLEC_CD;


select *
from C2C_CPODS_VWMC.C2C_FCT_MR_TRBLT
where dw_st_cd = 'FL'
and YR_MTH_NO = '201607'
and (cust_asset_no like '%DHSU%'
or cust_asset_no like '%TYNU%');
