--drop table company;

create table trbl_found_remedy
(
trbl_found_number  		 VARCHAR2(255 BYTE),
trbl_found_desc     	 VARCHAR2(255 BYTE),
disp                     VARCHAR2(255 BYTE)
);

select * from trbl_found_remedy;

commit;

INSERT ALL
into trbl_found_remedy values ('104','lCfacility','FAC')
into trbl_found_remedy values ('103','coEquiptmentFrames','CO')
into trbl_found_remedy values ('101','outsidePlantEquiptment','FAC')
into trbl_found_remedy values ('102','coEquiptmentOther','CO')
into trbl_found_remedy values ('1','cameClear','CC')
into trbl_found_remedy values ('2','centralOffice','CO')
into trbl_found_remedy values ('3','switchTrouble','CO')
into trbl_found_remedy values ('4','customerProvidedEquipment','CPE')
into trbl_found_remedy values ('5','facility','FAC')
into trbl_found_remedy values ('6','centralOfficeFacility','FAC')
into trbl_found_remedy values ('7','ICfacility','FAC')
into trbl_found_remedy values ('8','interexchangeCarrier','REF')
into trbl_found_remedy values ('9','information','EXC')
into trbl_found_remedy values ('10','nonplanClassified','EXC')
into trbl_found_remedy values ('11','nonplanClassifiedIC','EXC')
into trbl_found_remedy values ('12','nonplanClassifiedEA','EXC')
into trbl_found_remedy values ('13','noTroubleFound','NTF')
into trbl_found_remedy values ('14','station','FAC')
into trbl_found_remedy values ('15','stationProductData','FAC')
into trbl_found_remedy values ('16','stationProductTerminal','FAC')
into trbl_found_remedy values ('17','stationProductVideo','FAC')
into trbl_found_remedy values ('18','stationProductVoice','FAC')
into trbl_found_remedy values ('19','stationWiring','FAC')
into trbl_found_remedy values ('20','otherStationEquipment','FAC')
into trbl_found_remedy values ('21','foundOKStation','NTF')
into trbl_found_remedy values ('22','servingBureau','EXC')
into trbl_found_remedy values ('23','testOK','NTF')
into trbl_found_remedy values ('24','publicServicesCoinSet','EXC')
into trbl_found_remedy values ('25','customerOperatingInstructions','CPE')
into trbl_found_remedy values ('26','testedOKVerifiedOK','NTF')
into trbl_found_remedy values ('27','coFacilityTestedFoundOK','NTF')
into trbl_found_remedy values ('28','outsideFacilityTestedFoundOK','NTF')
into trbl_found_remedy values ('29','referredOutToOtherDept','REF')
into trbl_found_remedy values ('30','protectiveConnectingArrang','CPE')
into trbl_found_remedy values ('31','cpeCustomerResponsibility','CPE')
into trbl_found_remedy values ('32','preService','EXC')
into trbl_found_remedy values ('33','preServiceIC','EXC')
into trbl_found_remedy values ('34','preServiceEA','EXC')
into trbl_found_remedy values ('35','serviceNode','EXC')
into trbl_found_remedy values ('36','data','CO')
into trbl_found_remedy values ('37','customerReferredToVendor','REF')
into trbl_found_remedy values ('38','exchangeAccess','EXC')
into trbl_found_remedy values ('39','international','EXC')
into trbl_found_remedy values ('40','otherProvidedAccess','REF')
into trbl_found_remedy values ('41','existingReport','EXC')
into trbl_found_remedy values ('42','cancelExclude','EXC')
into trbl_found_remedy values ('43','paBX','EXC')
into trbl_found_remedy values ('44','outsideWire','FAC')
into trbl_found_remedy values ('45','outsideTerminals','FAC')
into trbl_found_remedy values ('46','outsidePlantEquipment','FAC')
into trbl_found_remedy values ('47','outsidePlantFiberOptic','FAC')
into trbl_found_remedy values ('48','outsidePlantOther','FAC')
into trbl_found_remedy values ('49','coEquipmentOther','CO')
into trbl_found_remedy values ('50','coEquipmentFrames','CO')
into trbl_found_remedy values ('51','coConcentrator','CO')
into trbl_found_remedy values ('52','receiverOffHook','CPE')
into trbl_found_remedy values ('53','cpeAuthorized','CPE')
into trbl_found_remedy values ('54','cpeTelcoMaintained','CPE')
into trbl_found_remedy values ('55','independentCompany','REF')
into trbl_found_remedy values ('56','cpeCalledNumber','CPE')
into trbl_found_remedy values ('57','assigningProvisioning','FAC')
into trbl_found_remedy values ('58','interServiceCenter','EXC')
into trbl_found_remedy values ('59','referredOut','REF')
into trbl_found_remedy values ('60','network','FAC')
into trbl_found_remedy values ('0','pending','EXC')
select * from dual;

