SELECT DISTINCT REGION, STATE, DOCNO, FTR_TKT, PRODUCT, CREATE_DATE, CLEARED_DT, CLOSE_DT, TT_TYPE, CURRENT_STATE,
       CIRCUIT, OFFICE_CLLI_CD, ICSC, SERV_ITEM_TYPE_CD, CUSTOMER_TICKET_ID, CLEC_ID, 
	   case when clec_id in ('ATX','AAV','SBB','SBZ','SUV','TPM') then 'ATX' else 'MOB' end company,
	   SERV_CODE, TROUBLE_FOUND_CD, TRBL_FOUND_ID, DISPOSITION, FOUND, TTR, TOTAL_DURATION,
	   CASE WHEN TTR <= 4 THEN 1 ELSE 0 END TTR4,
	   CASE WHEN TTR <= 8 THEN 1 ELSE 0 END TTR8	
FROM (
SELECT 
 CASE WHEN STATE IN ('IN','KY','MI','IL','MO','MN','NE','IA','ND') THEN 'Central'
       		WHEN STATE IN ('NY','PA','OH','WV','MD','VA') THEN 'East'
	  		WHEN STATE IN ('CA','OR','WA','ID','MT') THEN 'West'
	  		WHEN STATE IN ('AL','AZ','FL','GA','MS','NM','NV','TN','UT','WI','SC','NC') THEN 'National'
	  ELSE 'Unknown' END REGION, 
      STATE, 
       CASE WHEN SUBSTR(SERV_CODE,1,1) IN ('K','V') THEN 'Ethernet'
			WHEN SERV_CODE = 'OB' THEN 'OC3'
			WHEN SERV_CODE = 'OD' THEN 'OC12'
			WHEN SERV_CODE = 'OF' THEN 'OC48'
			WHEN SERV_CODE = 'OG' THEN 'OC192'
			WHEN SUBSTR(SERV_CODE,1,1) IN ('L','X') THEN 'DS0'
			WHEN SERV_CODE = 'HC' THEN 'DS1'
			WHEN SUBSTR(SERV_CODE,1,2) = 'T1' THEN 'DS1'
			WHEN SERV_CODE = 'HF' THEN 'DS3'
			WHEN SUBSTR(SERV_CODE,1,2) = 'T3' THEN 'DS3'
			ELSE PRODUCT_LEVEL END PRODUCT,
	   DOCUMENT_NUMBER DOCNO, CREATE_DATE, CLEARED_DT, CLOSE_DT, TT_TYPE, CURRENT_STATE, FTR_TKT,
       CIRCUIT, OFFICE_CLLI_CD, ICSC, SERV_ITEM_TYPE_CD, CUSTOMER_TICKET_ID, 
       CASE WHEN ACNA IS NOT NULL THEN ACNA
	        WHEN CCNA IS NOT NULL THEN CCNA
			ELSE USER_DATA_ACNA END CLEC_ID, 
	   SERV_CODE, TROUBLE_FOUND_CD, TRBL_FOUND_ID, DISPOSITION, 
	   CASE WHEN DISPOSITION IN ('CO','FAC','CC') THEN 'F'
	        WHEN DISPOSITION = 'NTF' THEN 'NF'
			ELSE 'EXC' END FOUND,
	   TTR, TOTAL_DURATION
FROM (
SELECT MAX(C.RATE_CODE) KEEP (DENSE_RANK LAST ORDER BY C.LAST_MODIFIED_DATE) AS PRODUCT_LEVEL,
 CASE WHEN NL1.CLLI_CODE IS NOT NULL THEN SUBSTR(NL1.CLLI_CODE,5,2)
      WHEN NL2.CLLI_CODE IS NOT NULL THEN SUBSTR(NL2.CLLI_CODE,5,2)
	  WHEN TT.OFFICE_CLLI_CD IS NOT NULL THEN SUBSTR(TT.OFFICE_CLLI_CD,5,2)
	  ELSE NULL END STATE,
 TT.DOCUMENT_NUMBER, 
 TT.CREATE_DATE,
 ASAP.PKG_GMT.SF_GMT_AS_PASSED_TIMEZONE(TT.CLEARED_DT, '1222') AS CLEARED_DT, -- GMT CONVERTED  
 ASAP.PKG_GMT.SF_GMT_AS_PASSED_TIMEZONE(TT.CLOSE_DT, '1222') AS CLOSE_DT, --GMT CONVERTED  
 TT.TT_TYPE_CD AS TT_TYPE,
 TT.CURRENT_STATE AS CURRENT_STATE,
 TO_CHAR(TT.TICKET_ID) FTR_TKT,
 TT.SERV_ITEM_DESC CIRCUIT,
 REPLACE(REPLACE(TT.SERV_ITEM_DESC,' '),'/') CKT, 
 TT.OFFICE_CLLI_CD,
 TT.SERV_ITEM_TYPE_CD, 
 TT.CUSTOMER_TICKET_ID,
 D.ACNA USER_DATA_ACNA,
 MAX(DLR.ACNA) KEEP (DENSE_RANK LAST ORDER BY DLR.LAST_MODIFIED_DATE) ACNA,
 MAX(DLR.CCNA) KEEP (DENSE_RANK LAST ORDER BY DLR.LAST_MODIFIED_DATE) CCNA,
 MAX(C.SERVICE_TYPE_CODE) KEEP (DENSE_RANK LAST ORDER BY C.LAST_MODIFIED_DATE) SERV_CODE,
 MAX(UPPER(DLR.EC_COMPANY_CODE)) KEEP (DENSE_RANK LAST ORDER BY D.LAST_MODIFIED_DATE) ICSC,
 TFT.TROUBLE_FOUND_CD,
 TT.TRBL_FOUND_ID,
 CASE WHEN TT.TRBL_FOUND_ID IN ('253','261','263','266','267','268') THEN 'NTF'  
      WHEN TT.TRBL_FOUND_ID IN ('241') THEN 'CC'  
	  WHEN TT.TRBL_FOUND_ID IN ('242','243','276','289','290','291') THEN 'CO'  
	  WHEN TT.TRBL_FOUND_ID IN ('245','246','247','254','255','256','257','258','259','260',
	                            '284','285','286','287','288','297','300') THEN 'FAC' 
	  ELSE 'EXC' END DISPOSITION,
 ROUND((TTR/3600),2) TTR,
 ROUND((TOT_DUR/3600),2) TOTAL_DURATION
 --
 FROM TROUBLE_USER_DATA D,
 CIRCUIT C,
 DESIGN_LAYOUT_REPORT DLR,
 NETWORK_LOCATION NL1,
 NETWORK_LOCATION NL2,
 TROUBLE_FOUND_TYPE TFT,
 TROUBLE_TICKET TT
 WHERE TT.DOCUMENT_NUMBER = D.DOCUMENT_NUMBER(+)
 AND TT.SERV_ITEM_DESC = C.EXCHANGE_CARRIER_CIRCUIT_ID(+)
 AND C.CIRCUIT_DESIGN_ID = DLR.CIRCUIT_DESIGN_ID
 AND C.LOCATION_ID = NL1.LOCATION_ID(+)
 AND C.LOCATION_ID_2 = NL2.LOCATION_ID(+)
 AND TT.TRBL_FOUND_ID = TFT.TRBL_FOUND_ID (+)
 AND TT.CURRENT_STATE = 'closed'
 AND TO_CHAR(ASAP.PKG_GMT.SF_GMT_AS_PASSED_TIMEZONE(TT.CLOSE_DT,'1222'),'yyyymm') in ('201312')
 AND RESP_ORG_PARTY_ID IN ('518336','540992','541368')
 AND TT.SERV_ITEM_TYPE_CD = 'CIRCUIT'
 AND SUBSTR(TT.SERV_ITEM_DESC,7,1) <> 'U'
 AND TT.TT_TYPE_CD = 'CUSTOMER'
 AND DLR.ISSUE_STATUS = '2'
 AND (C.TYPE <> 'T' OR TYPE IS NULL)
 AND TT.TRBL_FOUND_ID IN ('242','243','276','289','290','291','245','246','247','254','255','256','257','258','259','260',
	                      '284','285','286','287','288','297','300','253','261','263','266','267','268','241')
 and (ccna in ('ATX','AAV','SBB','SBZ','SUV','TPM','AAX','ACF','ACH','ADM','AEC','AGS','AGZ','AHA','AHD','AHM','AHO',
	   		      'AIL','AIN','AIS','AKZ','ALY','AMH','AMP','AWL','AWN','AZE','BAC','BAK','BAO','BCU','BFL','BGH','BPN',
				  'BSM','CBL','CCB','CDA','CEO','CEU','CFN','CIV','CIW','CKQ','CLQ','COW','CQW','CRF','CRJ','CSG','CSO',
			      'CSU','CSX','CTJ','CUO','CUY','CZB','DNC','ETP','EST','ETX','FLA','FSC','FSI','FSV','GEE','GLV','GSL',
				  'HGN','HLU','HNC','HTN','IMP','IND','ISZ','IUW','JCT','LAA','LAC','LBH','LNZ','LSZ','MBN','MBQ','MCA',
			      'MCC','MCE','MCQ','MCV','MCW','MCZ','MFN','MIB','MIR','MLA','MLZ','MMV','MOB','MOE','MTX','MUI','MWB',
				  'MWZ','NBC','NWW','OAK','OCL','ORV','OSU','OCK','PFM','PIG','RAD','RMC','RMF','RRC','SBG','SBM','SBN',
				  'SCU','SHI','SLL','SMC','SNP','STH','SUF','SWM','SWP','SWT','SWV','SYC','SZM','TGH','TQU','UMT','VGD',
				  'VRA','WBT','WGL','WLG','WLZ','WVO','WWC')
 and (dlr.acna in ('ATX','AAV','SBB','SBZ','SUV','TPM','AAX','ACF','ACH','ADM','AEC','AGS','AGZ','AHA','AHD','AHM','AHO',
	   		      'AIL','AIN','AIS','AKZ','ALY','AMH','AMP','AWL','AWN','AZE','BAC','BAK','BAO','BCU','BFL','BGH','BPN',
				  'BSM','CBL','CCB','CDA','CEO','CEU','CFN','CIV','CIW','CKQ','CLQ','COW','CQW','CRF','CRJ','CSG','CSO',
			      'CSU','CSX','CTJ','CUO','CUY','CZB','DNC','ETP','EST','ETX','FLA','FSC','FSI','FSV','GEE','GLV','GSL',
				  'HGN','HLU','HNC','HTN','IMP','IND','ISZ','IUW','JCT','LAA','LAC','LBH','LNZ','LSZ','MBN','MBQ','MCA',
			      'MCC','MCE','MCQ','MCV','MCW','MCZ','MFN','MIB','MIR','MLA','MLZ','MMV','MOB','MOE','MTX','MUI','MWB',
				  'MWZ','NBC','NWW','OAK','OCL','ORV','OSU','OCK','PFM','PIG','RAD','RMC','RMF','RRC','SBG','SBM','SBN',
				  'SCU','SHI','SLL','SMC','SNP','STH','SUF','SWM','SWP','SWT','SWV','SYC','SZM','TGH','TQU','UMT','VGD',
				  'VRA','WBT','WGL','WLG','WLZ','WVO','WWC','BNK') or dlr.acna is null))	
 AND (SUBSTR(C.SERVICE_TYPE_CODE,1,2) IN ('HC','HF','T1','T3')
   OR SUBSTR(C.SERVICE_TYPE_CODE,1,1) IN ('L','X','K','V','O'))				  			  				  
 --
 GROUP BY NL1.CLLI_CODE, NL2.CLLI_CODE, TT.DOCUMENT_NUMBER, TT.CREATE_DATE, TT.CLEARED_DT, TT.CLOSE_DT,   
 TT.TT_TYPE_CD, TT.CURRENT_STATE, TT.TICKET_ID, TT.SERV_ITEM_DESC, TT.OFFICE_CLLI_CD, TT.SERV_ITEM_TYPE_CD, 
 TT.CUSTOMER_TICKET_ID, D.ACNA, TFT.TROUBLE_FOUND_CD, TT.TRBL_FOUND_ID, TTR, TOT_DUR
 )) 
  ORDER BY REGION, STATE, TTR DESC



