CREATE TABLE [forecast].[Summary] (
    [SummaryDate]              DATETIME       NOT NULL,
    [ProjectNumber]            INT            NOT NULL,
    [SubprojectNumber]         SMALLINT       NOT NULL,
    [ProjectSubNumber]         INT            NULL,
    [BudgetLineNumber]         INT            NULL,
    [BudgetLineName]           VARCHAR (100)  NULL,
    [ClassOfPlant]             CHAR (2)       NULL,
    [LinkCode]                 VARCHAR (25)   NULL,
    [JustificationCode]        TINYINT        NULL,
    [BudgetCategory]           VARCHAR (50)   NULL,
    [FunctionalGroup]          CHAR (1)       NULL,
    [ProjectDescription]       VARCHAR (200)  NULL,
    [Billable]                 CHAR (1)       NULL,
    [ProjectStatusCode]        CHAR (2)       NULL,
    [ApprovalCode]             CHAR (2)       NULL,
    [ProjectType]              CHAR (1)       NULL,
    [Company]                  SMALLINT       NULL,
    [Exchange]                 VARCHAR (50)   NULL,
    [OperatingArea]            SMALLINT       NULL,
    [State]                    CHAR (2)       NULL,
    [Engineer]                 VARCHAR (50)   NULL,
    [ProjectOwner]             VARCHAR (50)   NULL,
    [ApprovalDate]             DATE           NULL,
    [EstimatedStartDate]       DATE           NULL,
    [EstimatedCompleteDate]    DATE           NULL,
    [ActualStartDate]          DATE           NULL,
    [ReadyForServiceDate]      DATE           NULL,
    [TentativeCloseDate]       DATE           NULL,
    [CloseDate]                DATE           NULL,
    [AuthorizedDirect]         MONEY          NULL,
    [AuthorizedIndirect]       MONEY          NULL,
    [AuthorizedTotal]          MONEY          NULL,
    [PriorYearsSpend]          MONEY          NULL,
    [ProjectVariance]          FLOAT (53)     NULL,
    [PercentOverUnder]         FLOAT (53)     NULL,
    [SpendingForecast]         MONEY          NULL,
    [JanuaryDirect]            MONEY          NULL,
    [JanuaryIndirect]          MONEY          NULL,
    [FebruaryDirect]           MONEY          NULL,
    [FebruaryIndirect]         MONEY          NULL,
    [MarchDirect]              MONEY          NULL,
    [MarchIndirect]            MONEY          NULL,
    [AprilDirect]              MONEY          NULL,
    [AprilIndirect]            MONEY          NULL,
    [MayDirect]                MONEY          NULL,
    [MayIndirect]              MONEY          NULL,
    [JuneDirect]               MONEY          NULL,
    [JuneIndirect]             MONEY          NULL,
    [JulyDirect]               MONEY          NULL,
    [JulyIndirect]             MONEY          NULL,
    [AugustDirect]             MONEY          NULL,
    [AugustIndirect]           MONEY          NULL,
    [SeptemberDirect]          MONEY          NULL,
    [SeptemberIndirect]        MONEY          NULL,
    [OctoberDirect]            MONEY          NULL,
    [OctoberIndirect]          MONEY          NULL,
    [NovemberDirect]           MONEY          NULL,
    [NovemberIndirect]         MONEY          NULL,
    [DecemberDirect]           MONEY          NULL,
    [DecemberIndirect]         MONEY          NULL,
    [GrossAddsDirect]          MONEY          NULL,
    [GrossAddsIndirect]        MONEY          NULL,
    [GrossAddsTotal]           MONEY          NULL,
    [CIACBudget]               MONEY          NULL,
    [CIACSpend]                MONEY          NULL,
    [FutureYearsSpendInfinium] MONEY          NULL,
    [FutureYearsSpend]         MONEY          NULL,
    [SpendingNotNeeded]        MONEY          NULL,
    [RemainderToSpend]         MONEY          NULL,
    [AdditionalDollarsNeeded]  MONEY          NULL,
    [Q1Direct]                 MONEY          NULL,
    [Q1Indirect]               MONEY          NULL,
    [Q2Direct]                 MONEY          NULL,
    [Q2Indirect]               MONEY          NULL,
    [Q3Direct]                 MONEY          NULL,
    [Q3Indirect]               MONEY          NULL,
    [Q4Direct]                 MONEY          NULL,
    [Q4Indirect]               MONEY          NULL,
    [QuarterlyDirect]          MONEY          NULL,
    [QuarterlyIndirect]        MONEY          NULL,
    [QuarterlyTotal]           MONEY          NULL,
    [Notes]                    VARCHAR (4000) NULL,
    [SubprojectStatus]         VARCHAR (50)   NULL,
    [CarryIn]                  BIT            NULL,
    [SentToClosing]            VARCHAR (25)   NULL,
    CONSTRAINT [PK_Summary] PRIMARY KEY CLUSTERED ([SummaryDate] ASC, [ProjectNumber] ASC, [SubprojectNumber] ASC)
);

