select region, sum(met), count(*), sum(met)/count(*)*100 res, avg(days_install)
from (
SELECT/*+ INDEX(LSR NMPW_DM_PR_LSR_PROD_RPTG_MONTH) */
	distinct DM_LSR_ORD_NO ORD_NO,
	LSR.DM_LSR_ORD_ID ORD_ID,
	LSR.DM_LSR_CCNA_CD CCNA,
	LSR.DM_LSR_STATE_CD STATE,
	LSR.DM_LSR_PROD_CLASS PROD,
	LSR.DM_LSR_ORD_CREATE_DT CREATE_DT,
	LSR.DM_LSR_ORIG_DUE_DT ORIG_DUE_DT, 
	LSR.DM_LSR_DUE_DT DUE_DT,
	LSR.DM_LSR_REQ_DUE_DT REQ_DUE_DT,
	LSR.DM_LSR_BILL_EFCTV_DT Completion_Dt,
	LSR.DM_LSR_DAYS_TO_INSTALL DAYS_INSTALL,
	LSR.DM_LSR_CUST_REQ_CD CUST_REQ,
	LSR.DM_LSR_CLEC_CAUSED_FLAG CLEC_CAUSED,
	LSR.DM_LSR_BILL_TN BILL_TN,
	LSR.DM_LSR_CKT_TN CKT_TN,
	LSR.DM_LSR_ORD_TYPE_CD ACT, 
    LSR.DM_LSR_DUE_DAY_MISS_FLAG DUE_DAY_MISS,
	case when LSR.DM_LSR_STATE_CD in ('WA','CA','OR') then 'West'
	     when LSR.DM_LSR_STATE_CD in ('IL','OH') then 'Central'
		 else 'National' end region,
	case when LSR.DM_LSR_DUE_DAY_MISS_FLAG = 'N' then 1
	     else 0 end met
FROM
	DM_WST_APP.NMPW_DM_PR_LSR_PRODUCT LSR, 
	DM_WST_APP.NMPW_DM_AGGREGATE_DT	a12, 
	DM_WST_APP.NMPW_DM_SUBCLASS_LU	a13, 
	DM_WST_APP.NMPW_DM_MSRMNT_SUBCLASS_LU	a14
where	LSR.DM_LSR_VERSION = a12.DM_AGG_RPTG_VERSION and 
	LSR.DM_LSR_SUBCLASS_CD1 = a13.DM_SUBCLASS_CD1 and 
	LSR.DM_LSR_SUBCLASS_CD2 = a13.DM_SUBCLASS_CD2 and 
	LSR.DM_LSR_SUBCLASS_CD3 = a13.DM_SUBCLASS_CD3 and 
	a13.DM_SUBCLASS_ID = a14.DM_SUBCLASS_ID
 and LSR.DM_LSR_RPTG_MONTH = '201201'	
 and to_char(LSR.DM_LSR_BILL_EFCTV_DT,'yyyymmdd') between '20120129' and '20120131'
 and (LSR.DM_LSR_C2C_FCC_CD = 'FCC'
 and a14.DM_MSRMNT_CD in ('FCCPRV0404','FCCPRV0405')
 and a12.DM_AGG_RPTG_START_DT < a14.DM_MSRMNT_SUBCLASS_RETIRE_DT
 and a14.DM_MSRMNT_SUBCLASS_START_DT < a12.DM_AGG_RPTG_END_DT
 and LSR.DM_LSR_EXCL_CCNA_FLAG = 'N'
 and LSR.DM_LSR_CCNA_CD <> '#GT'
 and (((LSR.DM_LSR_ORD_TYPE_CD = 'I'
 or LSR.DM_LSR_ORD_TYPE_CD = 'M'
 or LSR.DM_LSR_ORD_TYPE_CD = 'C'
 or (LSR.DM_LSR_ORD_TYPE_CD = 'O'
 and LSR.DM_LSR_OMT_TYPE = 'PB'))
 and (SUBSTR(LSR.DM_LSR_EXPANDED_SVC_CLASS_CD,1,1) = 'B'
 or SUBSTR(LSR.DM_LSR_EXPANDED_SVC_CLASS_CD,1,1) = 'G'
 or SUBSTR(LSR.DM_LSR_EXPANDED_SVC_CLASS_CD,1,1) = 'R'
 or (SUBSTR(LSR.DM_LSR_EXPANDED_SVC_CLASS_CD,1,1) is null
 and LSR.DM_LSR_ORD_TYPE_CD = 'O'
 and LSR.DM_LSR_OMT_TYPE = 'PB'))
 and LSR.DM_LSR_ORD_STATUS_CD = 5
 and LSR.DM_LSR_DAYS_TO_INSTALL is not null
 and (LSR.DM_LSR_CREATE_LTERM <> LSR.DM_LSR_CMP_LTERM
 or (LSR.DM_LSR_CMP_LTERM is null
 and LSR.DM_LSR_CREATE_LTERM is not null)
 or (LSR.DM_LSR_CMP_LTERM is not null
 and LSR.DM_LSR_CREATE_LTERM is null))
 and LSR.DM_LSR_DUE_DT <> To_Date('1900-01-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS')
 and (LSR.DM_LSR_BILL_TYPE_CD <> 'G'
 or LSR.DM_LSR_BILL_TYPE_CD is null)
 and LSR.DM_LSR_CMP_DT >=  LSR.DM_LSR_ORD_CREATE_DT
 and LSR.DM_LSR_SUFFIX_C14_RCDS_FLAG = 'N'
 and LSR.DM_LSR_RECORD_TYPE_CD = 'LSR'
 and ((LSR.DM_LSR_SUBCLASS_CD1 <> 'LNP'
 and LSR.DM_LSR_ORD_TYPE_CD <> 'O')
 or LSR.DM_LSR_SUBCLASS_CD1 = 'LNP')
 and (SUBSTR(DM_LSR_EXPANDED_SVC_CLASS_CD,1,1) <> 'T'
 or SUBSTR(DM_LSR_EXPANDED_SVC_CLASS_CD,1,1) is null)
 and (LSR.DM_LSR_FEATURES_FLAG <> 'Y'
 or (LSR.DM_LSR_SUBCLASS_CD1 <> 'UNE'
 and LSR.DM_LSR_SUBCLASS_CD1 <> 'SUB')
 or LSR.DM_LSR_SUBCLASS_CD2 <> 'LOP'
 or LSR.DM_LSR_CCNA_CD <> '#GT')))
 and LSR.DM_LSR_BIZ_DT between a12.DM_AGG_RPTG_START_DT and a12.DM_AGG_RPTG_END_DT
 and a12.DM_AGG_RPTG_MONTH = LSR.DM_LSR_RPTG_MONTH
 and a12.DM_AGG_RPTG_DOMAIN_CD = 'PR'
 and LSR.DM_LSR_PROD_CLASS not in ('LNS','UPL','LNP')
 and LSR.DM_LSR_REP_MONTH_CD = '1'
 and a12.DM_AGG_RPTG_MONTH in ('201201'))
)
 group by region
 order by 1
 
 

	
	
	
,