
CREATE PROCEDURE [ProjApproval].[InputScreen_PreSale_Grants_Trim]
AS
	SET XACT_ABORT, NOCOUNT ON
BEGIN TRY
	BEGIN TRANSACTION
DROP TABLE IF EXISTS LOG.Tracker_Temp_ProjApproval__InputScreen_PreSale_Grants_Trim
INSERT INTO [LOG].[Tracker]
    ([EVENTNAME]
    ,[EVENTSTART]
    ,[EVENTTYPE]
    ,[EVENTDESCRIPTION])
VALUES
('[ProjApproval].[InputScreen_PreSale_Grants_Trim]'
    ,CAST(GETDATE() AS DATETIME)
    ,'STORE PROC'
    ,'')

SELECT MAX(EVENTID) AS LATESTID  INTO LOG.Tracker_Temp_ProjApproval__InputScreen_PreSale_Grants_Trim
FROM [LOG].[Tracker]

insert into projapproval.InputScreen_PreSale_Grants_Trimmed
([Opportunity ID]
      ,[Start time]
      ,[SubmitttedDtm]
      ,[SubmittedBy]
      ,[Name]
      ,[CRC Date]
      ,[Budget Category]
      ,[Build]
      ,[Project Number]
      ,[Project Description]
      ,[State]
      ,[Grants Name]
      ,[Exchange]
      ,[Household Opportunity]
      ,[Cost Per Household]
      ,[Household Forecast]
      ,[Take Rate]
      ,[Capital Request]
      ,[Capital Request Q1]
      ,[Capital Request Q2]
      ,[Capital Request Q3]
      ,[Capital Request Q4]
      ,[Capital Cost Future Years]
      ,[Cost To Connect]
      ,[Total ISP Capital]
      ,[Total OSP Capital]
      ,[Total Capital]
      ,[MRC]
      ,[NRC]
      ,[Monthly Expense]
      ,[CIAC]
      ,[NPV]
      ,[IRR]
      ,[Payback]
      ,[Video Enabled State]
      ,[Terms in Months]
      ,[Type of Deal]
      ,[Link Code]
      ,[Notes]
      ,[Additional Documents])
  
  select 
  'Grants_'+[ID]
      ,[Start time]
      ,[SubmitttedDtm]
      ,[SubmittedBy]
      ,[Name]
      ,[CRC Date]
      ,[Budget Category]
      ,[Build]
      ,[Project Number 1]
      ,[Project Description]
      ,[State]
      ,[Grants Name]
      ,[Exchange]
      ,[Household Opportunity]
      ,[Cost Per Household]
      ,[Household Forecast]
      ,[Take Rate]
      ,[Capital Request]
      ,[Capital Request Q1]
      ,[Capital Request Q2]
      ,[Capital Request Q3]
      ,[Capital Request Q4]
      ,[Capital Cost Future Years]
      ,[Cost To Connect]
      ,[Total ISP Capital]
      ,[Total OSP Capital]
      ,[Total Capital]
      ,[MRC]
      ,[NRC]
      ,[Monthly Expense]
      ,[CIAC]
      ,[NPV]
      ,[IRR]
      ,[Payback]
      ,[Video Enabled State]
      ,[Terms in Months]
      ,[Type of Deal]
      ,[Link Code]
      ,[Notes]
      ,[Additional Documents]
  FROM [ProjApproval].[InputScreen_PreSale_Grants]
--  where [Project Number 1] != ''
--and  [Project Number 1] != ' '
--and  [Project Number 1] is not null
--and [ProjApproval].[InputScreen_PreSale_Grants].[Project Number 1] NOT IN
--(select [Project Number]
--from [ProjApproval].[InputScreen_PreSale_Grants_Trimmed]
--)


insert into projapproval.InputScreen_PreSale_Grants_Trimmed
([Opportunity ID]
      ,[Start time]
      ,[SubmitttedDtm]
      ,[SubmittedBy]
      ,[Name]
      ,[CRC Date]
      ,[Budget Category]
      ,[Build]
      ,[Project Number]
      ,[Project Description]
      ,[State]
      ,[Grants Name]
      ,[Exchange]
      ,[Household Opportunity]
      ,[Cost Per Household]
      ,[Household Forecast]
      ,[Take Rate]
      ,[Capital Request]
      ,[Capital Request Q1]
      ,[Capital Request Q2]
      ,[Capital Request Q3]
      ,[Capital Request Q4]
      ,[Capital Cost Future Years]
      ,[Cost To Connect]
      ,[Total ISP Capital]
      ,[Total OSP Capital]
      ,[Total Capital]
      ,[MRC]
      ,[NRC]
      ,[Monthly Expense]
      ,[CIAC]
      ,[NPV]
      ,[IRR]
      ,[Payback]
      ,[Video Enabled State]
      ,[Terms in Months]
      ,[Type of Deal]
      ,[Link Code]
      ,[Notes]
      ,[Additional Documents])
  
  select 
  'Grants_'+[ID]
      ,[Start time]
      ,[SubmitttedDtm]
      ,[SubmittedBy]
      ,[Name]
      ,[CRC Date]
      ,[Budget Category]
      ,[Build]
      ,[Project Number 2]
      ,[Project Description]
      ,[State]
      ,[Grants Name]
      ,[Exchange]
      ,[Household Opportunity]
      ,[Cost Per Household]
      ,[Household Forecast]
      ,[Take Rate]
      ,[Capital Request]
      ,[Capital Request Q1]
      ,[Capital Request Q2]
      ,[Capital Request Q3]
      ,[Capital Request Q4]
      ,[Capital Cost Future Years]
      ,[Cost To Connect]
      ,[Total ISP Capital]
      ,[Total OSP Capital]
      ,[Total Capital]
      ,[MRC]
      ,[NRC]
      ,[Monthly Expense]
      ,[CIAC]
      ,[NPV]
      ,[IRR]
      ,[Payback]
      ,[Video Enabled State]
      ,[Terms in Months]
      ,[Type of Deal]
      ,[Link Code]
      ,[Notes]
      ,[Additional Documents]
  FROM [ProjApproval].[InputScreen_PreSale_Grants]
  where [Project Number 2] != ''
and  [Project Number 2] != ' '
and  [Project Number 2] is not null
and [ProjApproval].[InputScreen_PreSale_Grants].[Project Number 2] NOT IN
(select [Project Number]
from [ProjApproval].[InputScreen_PreSale_Grants_Trimmed]
)

insert into projapproval.InputScreen_PreSale_Grants_Trimmed
([Opportunity ID]
      ,[Start time]
      ,[SubmitttedDtm]
      ,[SubmittedBy]
      ,[Name]
      ,[CRC Date]
      ,[Budget Category]
      ,[Build]
      ,[Project Number]
      ,[Project Description]
      ,[State]
      ,[Grants Name]
      ,[Exchange]
      ,[Household Opportunity]
      ,[Cost Per Household]
      ,[Household Forecast]
      ,[Take Rate]
      ,[Capital Request]
      ,[Capital Request Q1]
      ,[Capital Request Q2]
      ,[Capital Request Q3]
      ,[Capital Request Q4]
      ,[Capital Cost Future Years]
      ,[Cost To Connect]
      ,[Total ISP Capital]
      ,[Total OSP Capital]
      ,[Total Capital]
      ,[MRC]
      ,[NRC]
      ,[Monthly Expense]
      ,[CIAC]
      ,[NPV]
      ,[IRR]
      ,[Payback]
      ,[Video Enabled State]
      ,[Terms in Months]
      ,[Type of Deal]
      ,[Link Code]
      ,[Notes]
      ,[Additional Documents])
  
  select 
  'Grants_'+[ID]
      ,[Start time]
      ,[SubmitttedDtm]
      ,[SubmittedBy]
      ,[Name]
      ,[CRC Date]
      ,[Budget Category]
      ,[Build]
      ,[Project Number 3]
      ,[Project Description]
      ,[State]
      ,[Grants Name]
      ,[Exchange]
      ,[Household Opportunity]
      ,[Cost Per Household]
      ,[Household Forecast]
      ,[Take Rate]
      ,[Capital Request]
      ,[Capital Request Q1]
      ,[Capital Request Q2]
      ,[Capital Request Q3]
      ,[Capital Request Q4]
      ,[Capital Cost Future Years]
      ,[Cost To Connect]
      ,[Total ISP Capital]
      ,[Total OSP Capital]
      ,[Total Capital]
      ,[MRC]
      ,[NRC]
      ,[Monthly Expense]
      ,[CIAC]
      ,[NPV]
      ,[IRR]
      ,[Payback]
      ,[Video Enabled State]
      ,[Terms in Months]
      ,[Type of Deal]
      ,[Link Code]
      ,[Notes]
      ,[Additional Documents]
  FROM [ProjApproval].[InputScreen_PreSale_Grants]
  where [Project Number 3] != ''
and  [Project Number 3] != ' '
and  [Project Number 3] is not null
and [ProjApproval].[InputScreen_PreSale_Grants].[Project Number 3] NOT IN
(select [Project Number]
from [ProjApproval].[InputScreen_PreSale_Grants_Trimmed]
)

insert into projapproval.InputScreen_PreSale_Grants_Trimmed
([Opportunity ID]
      ,[Start time]
      ,[SubmitttedDtm]
      ,[SubmittedBy]
      ,[Name]
      ,[CRC Date]
      ,[Budget Category]
      ,[Build]
      ,[Project Number]
      ,[Project Description]
      ,[State]
      ,[Grants Name]
      ,[Exchange]
      ,[Household Opportunity]
      ,[Cost Per Household]
      ,[Household Forecast]
      ,[Take Rate]
      ,[Capital Request]
      ,[Capital Request Q1]
      ,[Capital Request Q2]
      ,[Capital Request Q3]
      ,[Capital Request Q4]
      ,[Capital Cost Future Years]
      ,[Cost To Connect]
      ,[Total ISP Capital]
      ,[Total OSP Capital]
      ,[Total Capital]
      ,[MRC]
      ,[NRC]
      ,[Monthly Expense]
      ,[CIAC]
      ,[NPV]
      ,[IRR]
      ,[Payback]
      ,[Video Enabled State]
      ,[Terms in Months]
      ,[Type of Deal]
      ,[Link Code]
      ,[Notes]
      ,[Additional Documents])
  
  select 
  'Grants_'+[ID]
      ,[Start time]
      ,[SubmitttedDtm]
      ,[SubmittedBy]
      ,[Name]
      ,[CRC Date]
      ,[Budget Category]
      ,[Build]
      ,[Project Number 4]
      ,[Project Description]
      ,[State]
      ,[Grants Name]
      ,[Exchange]
      ,[Household Opportunity]
      ,[Cost Per Household]
      ,[Household Forecast]
      ,[Take Rate]
      ,[Capital Request]
      ,[Capital Request Q1]
      ,[Capital Request Q2]
      ,[Capital Request Q3]
      ,[Capital Request Q4]
      ,[Capital Cost Future Years]
      ,[Cost To Connect]
      ,[Total ISP Capital]
      ,[Total OSP Capital]
      ,[Total Capital]
      ,[MRC]
      ,[NRC]
      ,[Monthly Expense]
      ,[CIAC]
      ,[NPV]
      ,[IRR]
      ,[Payback]
      ,[Video Enabled State]
      ,[Terms in Months]
      ,[Type of Deal]
      ,[Link Code]
      ,[Notes]
      ,[Additional Documents]
  FROM [ProjApproval].[InputScreen_PreSale_Grants]
  where [Project Number 4] != ''
and  [Project Number 4] != ' '
and  [Project Number 4] is not null
and [ProjApproval].[InputScreen_PreSale_Grants].[Project Number 4] NOT IN
(select [Project Number]
from [ProjApproval].[InputScreen_PreSale_Grants_Trimmed]
)

insert into projapproval.InputScreen_PreSale_Grants_Trimmed
([Opportunity ID]
      ,[Start time]
      ,[SubmitttedDtm]
      ,[SubmittedBy]
      ,[Name]
      ,[CRC Date]
      ,[Budget Category]
      ,[Build]
      ,[Project Number]
      ,[Project Description]
      ,[State]
      ,[Grants Name]
      ,[Exchange]
      ,[Household Opportunity]
      ,[Cost Per Household]
      ,[Household Forecast]
      ,[Take Rate]
      ,[Capital Request]
      ,[Capital Request Q1]
      ,[Capital Request Q2]
      ,[Capital Request Q3]
      ,[Capital Request Q4]
      ,[Capital Cost Future Years]
      ,[Cost To Connect]
      ,[Total ISP Capital]
      ,[Total OSP Capital]
      ,[Total Capital]
      ,[MRC]
      ,[NRC]
      ,[Monthly Expense]
      ,[CIAC]
      ,[NPV]
      ,[IRR]
      ,[Payback]
      ,[Video Enabled State]
      ,[Terms in Months]
      ,[Type of Deal]
      ,[Link Code]
      ,[Notes]
      ,[Additional Documents])
  
  select 
  'Grants_'+[ID]
      ,[Start time]
      ,[SubmitttedDtm]
      ,[SubmittedBy]
      ,[Name]
      ,[CRC Date]
      ,[Budget Category]
      ,[Build]
      ,[Project Number 5]
      ,[Project Description]
      ,[State]
      ,[Grants Name]
      ,[Exchange]
      ,[Household Opportunity]
      ,[Cost Per Household]
      ,[Household Forecast]
      ,[Take Rate]
      ,[Capital Request]
      ,[Capital Request Q1]
      ,[Capital Request Q2]
      ,[Capital Request Q3]
      ,[Capital Request Q4]
      ,[Capital Cost Future Years]
      ,[Cost To Connect]
      ,[Total ISP Capital]
      ,[Total OSP Capital]
      ,[Total Capital]
      ,[MRC]
      ,[NRC]
      ,[Monthly Expense]
      ,[CIAC]
      ,[NPV]
      ,[IRR]
      ,[Payback]
      ,[Video Enabled State]
      ,[Terms in Months]
      ,[Type of Deal]
      ,[Link Code]
      ,[Notes]
      ,[Additional Documents]
  FROM [ProjApproval].[InputScreen_PreSale_Grants]
  where [Project Number 5] != ''
and  [Project Number 5] != ' '
and  [Project Number 5] is not null
and [ProjApproval].[InputScreen_PreSale_Grants].[Project Number 5] NOT IN
(select [Project Number]
from [ProjApproval].[InputScreen_PreSale_Grants_Trimmed]
)


insert into projapproval.InputScreen_PreSale_Grants_Trimmed
([Opportunity ID]
      ,[Start time]
      ,[SubmitttedDtm]
      ,[SubmittedBy]
      ,[Name]
      ,[CRC Date]
      ,[Budget Category]
      ,[Build]
      ,[Project Number]
      ,[Project Description]
      ,[State]
      ,[Grants Name]
      ,[Exchange]
      ,[Household Opportunity]
      ,[Cost Per Household]
      ,[Household Forecast]
      ,[Take Rate]
      ,[Capital Request]
      ,[Capital Request Q1]
      ,[Capital Request Q2]
      ,[Capital Request Q3]
      ,[Capital Request Q4]
      ,[Capital Cost Future Years]
      ,[Cost To Connect]
      ,[Total ISP Capital]
      ,[Total OSP Capital]
      ,[Total Capital]
      ,[MRC]
      ,[NRC]
      ,[Monthly Expense]
      ,[CIAC]
      ,[NPV]
      ,[IRR]
      ,[Payback]
      ,[Video Enabled State]
      ,[Terms in Months]
      ,[Type of Deal]
      ,[Link Code]
      ,[Notes]
      ,[Additional Documents])
  
  select 
  'Grants_'+[ID]
      ,[Start time]
      ,[SubmitttedDtm]
      ,[SubmittedBy]
      ,[Name]
      ,[CRC Date]
      ,[Budget Category]
      ,[Build]
      ,[Project Number 6]
      ,[Project Description]
      ,[State]
      ,[Grants Name]
      ,[Exchange]
      ,[Household Opportunity]
      ,[Cost Per Household]
      ,[Household Forecast]
      ,[Take Rate]
      ,[Capital Request]
      ,[Capital Request Q1]
      ,[Capital Request Q2]
      ,[Capital Request Q3]
      ,[Capital Request Q4]
      ,[Capital Cost Future Years]
      ,[Cost To Connect]
      ,[Total ISP Capital]
      ,[Total OSP Capital]
      ,[Total Capital]
      ,[MRC]
      ,[NRC]
      ,[Monthly Expense]
      ,[CIAC]
      ,[NPV]
      ,[IRR]
      ,[Payback]
      ,[Video Enabled State]
      ,[Terms in Months]
      ,[Type of Deal]
      ,[Link Code]
      ,[Notes]
      ,[Additional Documents]
  FROM [ProjApproval].[InputScreen_PreSale_Grants]
  where [Project Number 6] != ''
and  [Project Number 6] != ' '
and  [Project Number 6] is not null
and [ProjApproval].[InputScreen_PreSale_Grants].[Project Number 6] NOT IN
(select [Project Number]
from [ProjApproval].[InputScreen_PreSale_Grants_Trimmed]
)


insert into projapproval.InputScreen_PreSale_Grants_Trimmed
([Opportunity ID]
      ,[Start time]
      ,[SubmitttedDtm]
      ,[SubmittedBy]
      ,[Name]
      ,[CRC Date]
      ,[Budget Category]
      ,[Build]
      ,[Project Number]
      ,[Project Description]
      ,[State]
      ,[Grants Name]
      ,[Exchange]
      ,[Household Opportunity]
      ,[Cost Per Household]
      ,[Household Forecast]
      ,[Take Rate]
      ,[Capital Request]
      ,[Capital Request Q1]
      ,[Capital Request Q2]
      ,[Capital Request Q3]
      ,[Capital Request Q4]
      ,[Capital Cost Future Years]
      ,[Cost To Connect]
      ,[Total ISP Capital]
      ,[Total OSP Capital]
      ,[Total Capital]
      ,[MRC]
      ,[NRC]
      ,[Monthly Expense]
      ,[CIAC]
      ,[NPV]
      ,[IRR]
      ,[Payback]
      ,[Video Enabled State]
      ,[Terms in Months]
      ,[Type of Deal]
      ,[Link Code]
      ,[Notes]
      ,[Additional Documents])
  
  select 
  'Grants_'+[ID]
      ,[Start time]
      ,[SubmitttedDtm]
      ,[SubmittedBy]
      ,[Name]
      ,[CRC Date]
      ,[Budget Category]
      ,[Build]
      ,[Project Number 7]
      ,[Project Description]
      ,[State]
      ,[Grants Name]
      ,[Exchange]
      ,[Household Opportunity]
      ,[Cost Per Household]
      ,[Household Forecast]
      ,[Take Rate]
      ,[Capital Request]
      ,[Capital Request Q1]
      ,[Capital Request Q2]
      ,[Capital Request Q3]
      ,[Capital Request Q4]
      ,[Capital Cost Future Years]
      ,[Cost To Connect]
      ,[Total ISP Capital]
      ,[Total OSP Capital]
      ,[Total Capital]
      ,[MRC]
      ,[NRC]
      ,[Monthly Expense]
      ,[CIAC]
      ,[NPV]
      ,[IRR]
      ,[Payback]
      ,[Video Enabled State]
      ,[Terms in Months]
      ,[Type of Deal]
      ,[Link Code]
      ,[Notes]
      ,[Additional Documents]
  FROM [ProjApproval].[InputScreen_PreSale_Grants]
  where [Project Number 7] != ''
and  [Project Number 7] != ' '
and  [Project Number 7] is not null
and [ProjApproval].[InputScreen_PreSale_Grants].[Project Number 7] NOT IN
(select [Project Number]
from [ProjApproval].[InputScreen_PreSale_Grants_Trimmed]
)
insert into projapproval.InputScreen_PreSale_Grants_Trimmed
([Opportunity ID]
      ,[Start time]
      ,[SubmitttedDtm]
      ,[SubmittedBy]
      ,[Name]
      ,[CRC Date]
      ,[Budget Category]
      ,[Build]
      ,[Project Number]
      ,[Project Description]
      ,[State]
      ,[Grants Name]
      ,[Exchange]
      ,[Household Opportunity]
      ,[Cost Per Household]
      ,[Household Forecast]
      ,[Take Rate]
      ,[Capital Request]
      ,[Capital Request Q1]
      ,[Capital Request Q2]
      ,[Capital Request Q3]
      ,[Capital Request Q4]
      ,[Capital Cost Future Years]
      ,[Cost To Connect]
      ,[Total ISP Capital]
      ,[Total OSP Capital]
      ,[Total Capital]
      ,[MRC]
      ,[NRC]
      ,[Monthly Expense]
      ,[CIAC]
      ,[NPV]
      ,[IRR]
      ,[Payback]
      ,[Video Enabled State]
      ,[Terms in Months]
      ,[Type of Deal]
      ,[Link Code]
      ,[Notes]
      ,[Additional Documents])
  
  select 
  'Grants_'+[ID]
      ,[Start time]
      ,[SubmitttedDtm]
      ,[SubmittedBy]
      ,[Name]
      ,[CRC Date]
      ,[Budget Category]
      ,[Build]
      ,[Project Number 8]
      ,[Project Description]
      ,[State]
      ,[Grants Name]
      ,[Exchange]
      ,[Household Opportunity]
      ,[Cost Per Household]
      ,[Household Forecast]
      ,[Take Rate]
      ,[Capital Request]
      ,[Capital Request Q1]
      ,[Capital Request Q2]
      ,[Capital Request Q3]
      ,[Capital Request Q4]
      ,[Capital Cost Future Years]
      ,[Cost To Connect]
      ,[Total ISP Capital]
      ,[Total OSP Capital]
      ,[Total Capital]
      ,[MRC]
      ,[NRC]
      ,[Monthly Expense]
      ,[CIAC]
      ,[NPV]
      ,[IRR]
      ,[Payback]
      ,[Video Enabled State]
      ,[Terms in Months]
      ,[Type of Deal]
      ,[Link Code]
      ,[Notes]
      ,[Additional Documents]
  FROM [ProjApproval].[InputScreen_PreSale_Grants]
  where [Project Number 8] != ''
and  [Project Number 8] != ' '
and  [Project Number 8] is not null
and [ProjApproval].[InputScreen_PreSale_Grants].[Project Number 8] NOT IN
(select [Project Number]
from [ProjApproval].[InputScreen_PreSale_Grants_Trimmed]
)
insert into projapproval.InputScreen_PreSale_Grants_Trimmed
([Opportunity ID]
      ,[Start time]
      ,[SubmitttedDtm]
      ,[SubmittedBy]
      ,[Name]
      ,[CRC Date]
      ,[Budget Category]
      ,[Build]
      ,[Project Number]
      ,[Project Description]
      ,[State]
      ,[Grants Name]
      ,[Exchange]
      ,[Household Opportunity]
      ,[Cost Per Household]
      ,[Household Forecast]
      ,[Take Rate]
      ,[Capital Request]
      ,[Capital Request Q1]
      ,[Capital Request Q2]
      ,[Capital Request Q3]
      ,[Capital Request Q4]
      ,[Capital Cost Future Years]
      ,[Cost To Connect]
      ,[Total ISP Capital]
      ,[Total OSP Capital]
      ,[Total Capital]
      ,[MRC]
      ,[NRC]
      ,[Monthly Expense]
      ,[CIAC]
      ,[NPV]
      ,[IRR]
      ,[Payback]
      ,[Video Enabled State]
      ,[Terms in Months]
      ,[Type of Deal]
      ,[Link Code]
      ,[Notes]
      ,[Additional Documents])
  
  select 
  'Grants_'+[ID]
      ,[Start time]
      ,[SubmitttedDtm]
      ,[SubmittedBy]
      ,[Name]
      ,[CRC Date]
      ,[Budget Category]
      ,[Build]
      ,[Project Number 9]
      ,[Project Description]
      ,[State]
      ,[Grants Name]
      ,[Exchange]
      ,[Household Opportunity]
      ,[Cost Per Household]
      ,[Household Forecast]
      ,[Take Rate]
      ,[Capital Request]
      ,[Capital Request Q1]
      ,[Capital Request Q2]
      ,[Capital Request Q3]
      ,[Capital Request Q4]
      ,[Capital Cost Future Years]
      ,[Cost To Connect]
      ,[Total ISP Capital]
      ,[Total OSP Capital]
      ,[Total Capital]
      ,[MRC]
      ,[NRC]
      ,[Monthly Expense]
      ,[CIAC]
      ,[NPV]
      ,[IRR]
      ,[Payback]
      ,[Video Enabled State]
      ,[Terms in Months]
      ,[Type of Deal]
      ,[Link Code]
      ,[Notes]
      ,[Additional Documents]
  FROM [ProjApproval].[InputScreen_PreSale_Grants]
  where [Project Number 9] != ''
and  [Project Number 9] != ' '
and  [Project Number 9] is not null
and [ProjApproval].[InputScreen_PreSale_Grants].[Project Number 9] NOT IN
(select [Project Number]
from [ProjApproval].[InputScreen_PreSale_Grants_Trimmed]
)
insert into projapproval.InputScreen_PreSale_Grants_Trimmed
([Opportunity ID]
      ,[Start time]
      ,[SubmitttedDtm]
      ,[SubmittedBy]
      ,[Name]
      ,[CRC Date]
      ,[Budget Category]
      ,[Build]
      ,[Project Number]
      ,[Project Description]
      ,[State]
      ,[Grants Name]
      ,[Exchange]
      ,[Household Opportunity]
      ,[Cost Per Household]
      ,[Household Forecast]
      ,[Take Rate]
      ,[Capital Request]
      ,[Capital Request Q1]
      ,[Capital Request Q2]
      ,[Capital Request Q3]
      ,[Capital Request Q4]
      ,[Capital Cost Future Years]
      ,[Cost To Connect]
      ,[Total ISP Capital]
      ,[Total OSP Capital]
      ,[Total Capital]
      ,[MRC]
      ,[NRC]
      ,[Monthly Expense]
      ,[CIAC]
      ,[NPV]
      ,[IRR]
      ,[Payback]
      ,[Video Enabled State]
      ,[Terms in Months]
      ,[Type of Deal]
      ,[Link Code]
      ,[Notes]
      ,[Additional Documents])
  
  select 
  'Grants_'+[ID]
      ,[Start time]
      ,[SubmitttedDtm]
      ,[SubmittedBy]
      ,[Name]
      ,[CRC Date]
      ,[Budget Category]
      ,[Build]
      ,[Project Number 10]
      ,[Project Description]
      ,[State]
      ,[Grants Name]
      ,[Exchange]
      ,[Household Opportunity]
      ,[Cost Per Household]
      ,[Household Forecast]
      ,[Take Rate]
      ,[Capital Request]
      ,[Capital Request Q1]
      ,[Capital Request Q2]
      ,[Capital Request Q3]
      ,[Capital Request Q4]
      ,[Capital Cost Future Years]
      ,[Cost To Connect]
      ,[Total ISP Capital]
      ,[Total OSP Capital]
      ,[Total Capital]
      ,[MRC]
      ,[NRC]
      ,[Monthly Expense]
      ,[CIAC]
      ,[NPV]
      ,[IRR]
      ,[Payback]
      ,[Video Enabled State]
      ,[Terms in Months]
      ,[Type of Deal]
      ,[Link Code]
      ,[Notes]
      ,[Additional Documents]
  FROM [ProjApproval].[InputScreen_PreSale_Grants]
  where [Project Number 10] != ''
and  [Project Number 10] != ' '
and  [Project Number 10] is not null
and [ProjApproval].[InputScreen_PreSale_Grants].[Project Number 10] NOT IN
(select [Project Number]
from [ProjApproval].[InputScreen_PreSale_Grants_Trimmed]
)

Update ProjApproval.InputScreen_PreSale_Grants_Trimmed
set build = replace(build, '["', '')
Update ProjApproval.InputScreen_PreSale_Grants_Trimmed
set build = replace(build, '"]', '')

Update ProjApproval.InputScreen_PreSale_Grants_Trimmed
set [type of deal] = replace([type of deal], '["', '')
Update ProjApproval.InputScreen_PreSale_Grants_Trimmed
set [type of deal] = replace([type of deal], '"]', '')


insert into ProjApproval.PreSale_Compiled
(
[Opportunity ID]
      ,[SubmitttedDtm]
      ,[SubmittedBy]
      ,[CRC Date]
      ,[Budget Category]
      ,[Build]
      ,[Project Number]
      ,[Project Description]
      ,[State]
      ,[Grants Name]
      ,[Exchange]
      ,[Cost Per Household]
      ,[Household Forecast]
      ,[Take Rate]
      ,[Capital Request]
      ,[Capital Request Q1]
      ,[Capital Request Q2]
      ,[Capital Request Q3]
      ,[Capital Request Q4]
      ,[Capital Cost Future Years]
      ,[Cost To Connect]
      ,[Total ISP Capital - Fully Loaded]
      ,[Total OSP Capital - Fully Loaded]
      ,[Total Capital - Fully Loaded]
      ,[MRC - Fully Loaded]
      ,[NRC]
      ,[Monthly Expense]
      ,[CIAC - Fully Loaded]
      ,[NPV - Fully Loaded]
      ,[IRR - Fully Loaded]
      ,[Payback - Fully Loaded]
      ,[Video Enabled State]
      ,[Term in Months]
      ,[Type of Deal]
      ,[Link Code]
      ,[Notes]
      ,[Additional Documents]
)
SELECT [Opportunity ID]
      ,[SubmitttedDtm]
      ,[SubmittedBy]
      ,[CRC Date]
      ,[Budget Category]
      ,[Build]
      ,[Project Number]
      ,[Project Description]
      ,[State]
      ,[Grants Name]
      ,[Exchange]
      ,[Cost Per Household]
      ,[Household Forecast]
      ,[Take Rate]
      ,[Capital Request]
      ,[Capital Request Q1]
      ,[Capital Request Q2]
      ,[Capital Request Q3]
      ,[Capital Request Q4]
      ,[Capital Cost Future Years]
      ,[Cost To Connect]
      ,[Total ISP Capital]
      ,[Total OSP Capital]
      ,[Total Capital]
      ,[MRC]
      ,[NRC]
      ,[Monthly Expense]
      ,[CIAC]
      ,[NPV]
      ,[IRR]
      ,[Payback]
      ,[Video Enabled State]
      ,[Terms in Months]
      ,[Type of Deal]
      ,[Link Code]
      ,[Notes]
      ,[Additional Documents]
  FROM [ProjApproval].[InputScreen_PreSale_Grants_Trimmed]
where ProjApproval.[InputScreen_PreSale_Grants_Trimmed].[Opportunity ID]
NOT IN (
select [Opportunity ID] from ProjApproval.PreSale_Compiled
)

delete from ProjApproval.PreSale_Compiled
FROM     ProjApproval.PreSale_Compiled INNER JOIN
                  ProjApproval.InputScreen_Projects_ExistingOpportunity_Trimmed ON ProjApproval.PreSale_Compiled.[Opportunity ID] = ProjApproval.InputScreen_Projects_ExistingOpportunity_Trimmed.OpportunityID
where ProjApproval.PreSale_Compiled.[Project Number] like 'TBD'


Update ProjApproval.PreSale_Compiled
set build = replace(build, '["', '')
Update ProjApproval.PreSale_Compiled
set build = replace(build, '"]', '')

Update ProjApproval.PreSale_Compiled
set [Type of Deal] = replace([Type of Deal], '["', '')
Update ProjApproval.PreSale_Compiled
set [Type of Deal] = replace([Type of Deal], '"]', '')

Update ProjApproval.PreSale_Compiled
set [Brownfield/Greenfield] = replace([Brownfield/Greenfield], '["', '')
Update ProjApproval.PreSale_Compiled
set [Brownfield/Greenfield] = replace([Brownfield/Greenfield], '"]', '')




delete from ProjApproval.InputScreen_PreSale_Grants
delete from ProjApproval.InputScreen_PreSale_Grants_Trimmed
UPDATE T
SET T.EVENTEND=CAST(GETDATE() AS DATETIME)
FROM LOG.Tracker T
INNER JOIN LOG.Tracker_Temp_ProjApproval__InputScreen_PreSale_Grants_Trim P
ON T.EVENTID = P.LATESTID
DROP TABLE IF EXISTS LOG.Tracker_Temp_ProjApproval__InputScreen_PreSale_Grants_Trim

	COMMIT TRANSACTION
END TRY
BEGIN CATCH
	IF @@trancount > 0 ROLLBACK TRANSACTION
	EXEC usp_error_handler
	RETURN 55555
END CATCH
