
CREATE PROCEDURE [ProjApproval].[InputScreen_PreSale_MDUSubdivision_Trim]
AS
	SET XACT_ABORT, NOCOUNT ON
BEGIN TRY
	BEGIN TRANSACTION
DROP TABLE IF EXISTS LOG.Tracker_Temp_ProjApproval__InputScreen_PreSale_MDUSubdivision_Trim
INSERT INTO [LOG].[Tracker]
    ([EVENTNAME]
    ,[EVENTSTART]
    ,[EVENTTYPE]
    ,[EVENTDESCRIPTION])
VALUES
('[ProjApproval].[InputScreen_PreSale_MDUSubdivision_Trim]'
    ,CAST(GETDATE() AS DATETIME)
    ,'STORE PROC'
    ,'')

SELECT MAX(EVENTID) AS LATESTID  INTO LOG.Tracker_Temp_ProjApproval__InputScreen_PreSale_MDUSubdivision_Trim
FROM [LOG].[Tracker]

INSERT INTO [ProjApproval].[InputScreen_PreSale_MDUSubdivision_Trimmed]
           ([Opportunity ID]
      ,[Start time]
      ,[SubmitttedDtm]
      ,[SubmittedBy]
      ,[Name]
      ,[CRC Date]
      ,[Budget Category]
      ,[Build]
      ,[Project Description]
      ,[State]
      ,[Exchange]
      ,[BDT#]
      ,[Project Number]
      ,[Unit Opportunity - Number of Units]
      ,[Cost Per Unit]
      ,[Unit Forecast]
      ,[Take Rate - Engineering/Proforma]
      ,[ROI Take Rate]
      ,[Average Take Rate]
      ,[Capital Request]
      ,[Capital Request Q1]
      ,[Capital Request Q2]
      ,[Capital Request Q3]
      ,[Capital Request Q4]
      ,[Capital Cost Future Years]
      ,[Cost To Connect]
      ,[Total ISP Capital]
      ,[Total OSP Capital]
      ,[Total Capital]
	  ,[Total Revenue]
      ,[Monthly Expense]
      ,[CIAC]
      ,[NPV]
      ,[IRR]
      ,[Payback]
      ,[Competitor]
      ,[Video Enabled State]
      ,[Terms in Months]
      ,[Type of Deal]
      ,[Brownfield/Greenfield]
      ,[Link Code]
      ,[Notes]
      ,[Additional Documents])

SELECT 'MDUSFU_'+[ID]
      ,[Start time]
      ,[SubmitttedDtm]
      ,[SubmittedBy]
      ,[Name]
      ,[CRC Date]
      ,[Budget Category]
      ,[Build]
      ,[Project Description]
      ,[State]
      ,[Exchange]
      ,[BDT#]
      ,[Project Number 1]
      ,[Unit Opportunity - Number of Units]
      ,[Cost Per Unit]
      ,[Unit Forecast]
      ,[Take Rate - Engineering/Proforma]
      ,[ROI Take Rate]
      ,[Average Take Rate]
      ,[Capital Request]
      ,[Capital Request Q1]
      ,[Capital Request Q2]
      ,[Capital Request Q3]
      ,[Capital Request Q4]
      ,[Capital Cost Future Years]
      ,[Cost To Connect]
      ,[Total ISP Capital]
      ,[Total OSP Capital]
      ,[Total Capital]
	  ,[Total Revenue]
      ,[Monthly Expense]
      ,[CIAC]
      ,[NPV]
      ,[IRR]
      ,[Payback]
      ,[Competitor]
      ,[Video Enabled State]
      ,[Terms in Months]
      ,[Type of Deal]
      ,[Brownfield/Greenfield]
      ,[Link Code]
      ,[Notes]
      ,[Additional Documents]
  FROM [ProjApproval].[InputScreen_PreSale_MDUSubdivision]
--where [Project Number 1] != ''
--and  [Project Number 1] != ' '
--and  [Project Number 1] is not null
--and [ProjApproval].[InputScreen_PreSale_MDUSubdivision].[Project Number 1] NOT IN
--(select [Project Number]
--from [ProjApproval].[InputScreen_PreSale_MDUSubdivision_Trimmed]
--)


INSERT INTO [ProjApproval].[InputScreen_PreSale_MDUSubdivision_Trimmed]
           ([Opportunity ID]
      ,[Start time]
      ,[SubmitttedDtm]
      ,[SubmittedBy]
      ,[Name]
      ,[CRC Date]
      ,[Budget Category]
      ,[Build]
      ,[Project Description]
      ,[State]
      ,[Exchange]
      ,[BDT#]
      ,[Project Number]
      ,[Unit Opportunity - Number of Units]
      ,[Cost Per Unit]
      ,[Unit Forecast]
      ,[Take Rate - Engineering/Proforma]
      ,[ROI Take Rate]
      ,[Average Take Rate]
      ,[Capital Request]
      ,[Capital Request Q1]
      ,[Capital Request Q2]
      ,[Capital Request Q3]
      ,[Capital Request Q4]
      ,[Capital Cost Future Years]
      ,[Cost To Connect]
      ,[Total ISP Capital]
      ,[Total OSP Capital]
      ,[Total Capital]
      ,[Total Revenue]
      ,[Monthly Expense]
      ,[CIAC]
      ,[NPV]
      ,[IRR]
      ,[Payback]
      ,[Competitor]
      ,[Video Enabled State]
      ,[Terms in Months]
      ,[Type of Deal]
      ,[Brownfield/Greenfield]
      ,[Link Code]
      ,[Notes]
      ,[Additional Documents])

SELECT 'MDUSFU_'+[ID]
      ,[Start time]
      ,[SubmitttedDtm]
      ,[SubmittedBy]
      ,[Name]
      ,[CRC Date]
      ,[Budget Category]
      ,[Build]
      ,[Project Description]
      ,[State]
      ,[Exchange]
      ,[BDT#]
      ,[Project Number 2]
      ,[Unit Opportunity - Number of Units]
      ,[Cost Per Unit]
      ,[Unit Forecast]
      ,[Take Rate - Engineering/Proforma]
      ,[ROI Take Rate]
      ,[Average Take Rate]
      ,[Capital Request]
      ,[Capital Request Q1]
      ,[Capital Request Q2]
      ,[Capital Request Q3]
      ,[Capital Request Q4]
      ,[Capital Cost Future Years]
      ,[Cost To Connect]
      ,[Total ISP Capital]
      ,[Total OSP Capital]
      ,[Total Capital]
      ,[Total Revenue]
      
      ,[Monthly Expense]
      ,[CIAC]
      ,[NPV]
      ,[IRR]
      ,[Payback]
      ,[Competitor]
      ,[Video Enabled State]
      ,[Terms in Months]
      ,[Type of Deal]
      ,[Brownfield/Greenfield]
      ,[Link Code]
      ,[Notes]
      ,[Additional Documents]
  FROM [ProjApproval].[InputScreen_PreSale_MDUSubdivision]
where [Project Number 2] != ''
and  [Project Number 2] != ' '
and  [Project Number 2] is not null
and [ProjApproval].[InputScreen_PreSale_MDUSubdivision].[Project Number 2] NOT IN
(select [Project Number]
from [ProjApproval].[InputScreen_PreSale_MDUSubdivision_Trimmed]
)


INSERT INTO [ProjApproval].[InputScreen_PreSale_MDUSubdivision_Trimmed]
           ([Opportunity ID]
      ,[Start time]
      ,[SubmitttedDtm]
      ,[SubmittedBy]
      ,[Name]
      ,[CRC Date]
      ,[Budget Category]
      ,[Build]
      ,[Project Description]
      ,[State]
      ,[Exchange]
      ,[BDT#]
      ,[Project Number]
      ,[Unit Opportunity - Number of Units]
      ,[Cost Per Unit]
      ,[Unit Forecast]
      ,[Take Rate - Engineering/Proforma]
      ,[ROI Take Rate]
      ,[Average Take Rate]
      ,[Capital Request]
      ,[Capital Request Q1]
      ,[Capital Request Q2]
      ,[Capital Request Q3]
      ,[Capital Request Q4]
      ,[Capital Cost Future Years]
      ,[Cost To Connect]
      ,[Total ISP Capital]
      ,[Total OSP Capital]
      ,[Total Capital]
      ,[Total Revenue]
      
      ,[Monthly Expense]
      ,[CIAC]
      ,[NPV]
      ,[IRR]
      ,[Payback]
      ,[Competitor]
      ,[Video Enabled State]
      ,[Terms in Months]
      ,[Type of Deal]
      ,[Brownfield/Greenfield]
      ,[Link Code]
      ,[Notes]
      ,[Additional Documents])

SELECT 'MDUSFU_'+[ID]
      ,[Start time]
      ,[SubmitttedDtm]
      ,[SubmittedBy]
      ,[Name]
      ,[CRC Date]
      ,[Budget Category]
      ,[Build]
      ,[Project Description]
      ,[State]
      ,[Exchange]
      ,[BDT#]
      ,[Project Number 3]
      ,[Unit Opportunity - Number of Units]
      ,[Cost Per Unit]
      ,[Unit Forecast]
      ,[Take Rate - Engineering/Proforma]
      ,[ROI Take Rate]
      ,[Average Take Rate]
      ,[Capital Request]
      ,[Capital Request Q1]
      ,[Capital Request Q2]
      ,[Capital Request Q3]
      ,[Capital Request Q4]
      ,[Capital Cost Future Years]
      ,[Cost To Connect]
      ,[Total ISP Capital]
      ,[Total OSP Capital]
      ,[Total Capital]
      ,[Total Revenue]
      
      ,[Monthly Expense]
      ,[CIAC]
      ,[NPV]
      ,[IRR]
      ,[Payback]
      ,[Competitor]
      ,[Video Enabled State]
      ,[Terms in Months]
      ,[Type of Deal]
      ,[Brownfield/Greenfield]
      ,[Link Code]
      ,[Notes]
      ,[Additional Documents]
  FROM [ProjApproval].[InputScreen_PreSale_MDUSubdivision]
where [Project Number 3] != ''
and  [Project Number 3] != ' '
and  [Project Number 3] is not null
and [ProjApproval].[InputScreen_PreSale_MDUSubdivision].[Project Number 3] NOT IN
(select [Project Number]
from [ProjApproval].[InputScreen_PreSale_MDUSubdivision_Trimmed]
)



INSERT INTO [ProjApproval].[InputScreen_PreSale_MDUSubdivision_Trimmed]
           ([Opportunity ID]
      ,[Start time]
      ,[SubmitttedDtm]
      ,[SubmittedBy]
      ,[Name]
      ,[CRC Date]
      ,[Budget Category]
      ,[Build]
      ,[Project Description]
      ,[State]
      ,[Exchange]
      ,[BDT#]
      ,[Project Number]
      ,[Unit Opportunity - Number of Units]
      ,[Cost Per Unit]
      ,[Unit Forecast]
      ,[Take Rate - Engineering/Proforma]
      ,[ROI Take Rate]
      ,[Average Take Rate]
      ,[Capital Request]
      ,[Capital Request Q1]
      ,[Capital Request Q2]
      ,[Capital Request Q3]
      ,[Capital Request Q4]
      ,[Capital Cost Future Years]
      ,[Cost To Connect]
      ,[Total ISP Capital]
      ,[Total OSP Capital]
      ,[Total Capital]
      
      ,[Total Revenue]
      ,[Monthly Expense]
      ,[CIAC]
      ,[NPV]
      ,[IRR]
      ,[Payback]
      ,[Competitor]
      ,[Video Enabled State]
      ,[Terms in Months]
      ,[Type of Deal]
      ,[Brownfield/Greenfield]
      ,[Link Code]
      ,[Notes]
      ,[Additional Documents])

SELECT 'MDUSFU_'+[ID]
      ,[Start time]
      ,[SubmitttedDtm]
      ,[SubmittedBy]
      ,[Name]
      ,[CRC Date]
      ,[Budget Category]
      ,[Build]
      ,[Project Description]
      ,[State]
      ,[Exchange]
      ,[BDT#]
      ,[Project Number 4]
      ,[Unit Opportunity - Number of Units]
      ,[Cost Per Unit]
      ,[Unit Forecast]
      ,[Take Rate - Engineering/Proforma]
      ,[ROI Take Rate]
      ,[Average Take Rate]
      ,[Capital Request]
      ,[Capital Request Q1]
      ,[Capital Request Q2]
      ,[Capital Request Q3]
      ,[Capital Request Q4]
      ,[Capital Cost Future Years]
      ,[Cost To Connect]
      ,[Total ISP Capital]
      ,[Total OSP Capital]
      ,[Total Capital]
      
      ,[Total Revenue]
      ,[Monthly Expense]
      ,[CIAC]
      ,[NPV]
      ,[IRR]
      ,[Payback]
      ,[Competitor]
      ,[Video Enabled State]
      ,[Terms in Months]
      ,[Type of Deal]
      ,[Brownfield/Greenfield]
      ,[Link Code]
      ,[Notes]
      ,[Additional Documents]
  FROM [ProjApproval].[InputScreen_PreSale_MDUSubdivision]
where [Project Number 4] != ''
and  [Project Number 4] != ' '
and  [Project Number 4] is not null
and [ProjApproval].[InputScreen_PreSale_MDUSubdivision].[Project Number 4] NOT IN
(select [Project Number]
from [ProjApproval].[InputScreen_PreSale_MDUSubdivision_Trimmed]
)



INSERT INTO [ProjApproval].[InputScreen_PreSale_MDUSubdivision_Trimmed]
           ([Opportunity ID]
      ,[Start time]
      ,[SubmitttedDtm]
      ,[SubmittedBy]
      ,[Name]
      ,[CRC Date]
      ,[Budget Category]
      ,[Build]
      ,[Project Description]
      ,[State]
      ,[Exchange]
      ,[BDT#]
      ,[Project Number]
      ,[Unit Opportunity - Number of Units]
      ,[Cost Per Unit]
      ,[Unit Forecast]
      ,[Take Rate - Engineering/Proforma]
      ,[ROI Take Rate]
      ,[Average Take Rate]
      ,[Capital Request]
      ,[Capital Request Q1]
      ,[Capital Request Q2]
      ,[Capital Request Q3]
      ,[Capital Request Q4]
      ,[Capital Cost Future Years]
      ,[Cost To Connect]
      ,[Total ISP Capital]
      ,[Total OSP Capital]
      ,[Total Capital]
      ,[Total Revenue]
      
      ,[Monthly Expense]
      ,[CIAC]
      ,[NPV]
      ,[IRR]
      ,[Payback]
      ,[Competitor]
      ,[Video Enabled State]
      ,[Terms in Months]
      ,[Type of Deal]
      ,[Brownfield/Greenfield]
      ,[Link Code]
      ,[Notes]
      ,[Additional Documents])

SELECT 'MDUSFU_'+[ID]
      ,[Start time]
      ,[SubmitttedDtm]
      ,[SubmittedBy]
      ,[Name]
      ,[CRC Date]
      ,[Budget Category]
      ,[Build]
      ,[Project Description]
      ,[State]
      ,[Exchange]
      ,[BDT#]
      ,[Project Number 5]
      ,[Unit Opportunity - Number of Units]
      ,[Cost Per Unit]
      ,[Unit Forecast]
      ,[Take Rate - Engineering/Proforma]
      ,[ROI Take Rate]
      ,[Average Take Rate]
      ,[Capital Request]
      ,[Capital Request Q1]
      ,[Capital Request Q2]
      ,[Capital Request Q3]
      ,[Capital Request Q4]
      ,[Capital Cost Future Years]
      ,[Cost To Connect]
      ,[Total ISP Capital]
      ,[Total OSP Capital]
      ,[Total Capital]
      ,[Total Revenue]
      
      ,[Monthly Expense]
      ,[CIAC]
      ,[NPV]
      ,[IRR]
      ,[Payback]
      ,[Competitor]
      ,[Video Enabled State]
      ,[Terms in Months]
      ,[Type of Deal]
      ,[Brownfield/Greenfield]
      ,[Link Code]
      ,[Notes]
      ,[Additional Documents]
  FROM [ProjApproval].[InputScreen_PreSale_MDUSubdivision]
where [Project Number 5] != ''
and  [Project Number 5] != ' '
and  [Project Number 5] is not null
and [ProjApproval].[InputScreen_PreSale_MDUSubdivision].[Project Number 5] NOT IN
(select [Project Number]
from [ProjApproval].[InputScreen_PreSale_MDUSubdivision_Trimmed]
)



INSERT INTO [ProjApproval].[InputScreen_PreSale_MDUSubdivision_Trimmed]
           ([Opportunity ID]
      ,[Start time]
      ,[SubmitttedDtm]
      ,[SubmittedBy]
      ,[Name]
      ,[CRC Date]
      ,[Budget Category]
      ,[Build]
      ,[Project Description]
      ,[State]
      ,[Exchange]
      ,[BDT#]
      ,[Project Number]
      ,[Unit Opportunity - Number of Units]
      ,[Cost Per Unit]
      ,[Unit Forecast]
      ,[Take Rate - Engineering/Proforma]
      ,[ROI Take Rate]
      ,[Average Take Rate]
      ,[Capital Request]
      ,[Capital Request Q1]
      ,[Capital Request Q2]
      ,[Capital Request Q3]
      ,[Capital Request Q4]
      ,[Capital Cost Future Years]
      ,[Cost To Connect]
      ,[Total ISP Capital]
      ,[Total OSP Capital]
      ,[Total Capital]
      
      ,[Total Revenue]
      ,[Monthly Expense]
      ,[CIAC]
      ,[NPV]
      ,[IRR]
      ,[Payback]
      ,[Competitor]
      ,[Video Enabled State]
      ,[Terms in Months]
      ,[Type of Deal]
      ,[Brownfield/Greenfield]
      ,[Link Code]
      ,[Notes]
      ,[Additional Documents])

SELECT 'MDUSFU_'+[ID]
      ,[Start time]
      ,[SubmitttedDtm]
      ,[SubmittedBy]
      ,[Name]
      ,[CRC Date]
      ,[Budget Category]
      ,[Build]
      ,[Project Description]
      ,[State]
      ,[Exchange]
      ,[BDT#]
      ,[Project Number 6]
      ,[Unit Opportunity - Number of Units]
      ,[Cost Per Unit]
      ,[Unit Forecast]
      ,[Take Rate - Engineering/Proforma]
      ,[ROI Take Rate]
      ,[Average Take Rate]
      ,[Capital Request]
      ,[Capital Request Q1]
      ,[Capital Request Q2]
      ,[Capital Request Q3]
      ,[Capital Request Q4]
      ,[Capital Cost Future Years]
      ,[Cost To Connect]
      ,[Total ISP Capital]
      ,[Total OSP Capital]
      ,[Total Capital]
      ,[Total Revenue]
      
      ,[Monthly Expense]
      ,[CIAC]
      ,[NPV]
      ,[IRR]
      ,[Payback]
      ,[Competitor]
      ,[Video Enabled State]
      ,[Terms in Months]
      ,[Type of Deal]
      ,[Brownfield/Greenfield]
      ,[Link Code]
      ,[Notes]
      ,[Additional Documents]
  FROM [ProjApproval].[InputScreen_PreSale_MDUSubdivision]
where [Project Number 6] != ''
and  [Project Number 6] != ' '
and  [Project Number 6] is not null
and [ProjApproval].[InputScreen_PreSale_MDUSubdivision].[Project Number 6] NOT IN
(select [Project Number]
from [ProjApproval].[InputScreen_PreSale_MDUSubdivision_Trimmed]
)



INSERT INTO [ProjApproval].[InputScreen_PreSale_MDUSubdivision_Trimmed]
           ([Opportunity ID]
      ,[Start time]
      ,[SubmitttedDtm]
      ,[SubmittedBy]
      ,[Name]
      ,[CRC Date]
      ,[Budget Category]
      ,[Build]
      ,[Project Description]
      ,[State]
      ,[Exchange]
      ,[BDT#]
      ,[Project Number]
      ,[Unit Opportunity - Number of Units]
      ,[Cost Per Unit]
      ,[Unit Forecast]
      ,[Take Rate - Engineering/Proforma]
      ,[ROI Take Rate]
      ,[Average Take Rate]
      ,[Capital Request]
      ,[Capital Request Q1]
      ,[Capital Request Q2]
      ,[Capital Request Q3]
      ,[Capital Request Q4]
      ,[Capital Cost Future Years]
      ,[Cost To Connect]
      ,[Total ISP Capital]
      ,[Total OSP Capital]
      ,[Total Capital]
      
      ,[Total Revenue]
      ,[Monthly Expense]
      ,[CIAC]
      ,[NPV]
      ,[IRR]
      ,[Payback]
      ,[Competitor]
      ,[Video Enabled State]
      ,[Terms in Months]
      ,[Type of Deal]
      ,[Brownfield/Greenfield]
      ,[Link Code]
      ,[Notes]
      ,[Additional Documents])

SELECT 'MDUSFU_'+[ID]
      ,[Start time]
      ,[SubmitttedDtm]
      ,[SubmittedBy]
      ,[Name]
      ,[CRC Date]
      ,[Budget Category]
      ,[Build]
      ,[Project Description]
      ,[State]
      ,[Exchange]
      ,[BDT#]
      ,[Project Number 7]
      ,[Unit Opportunity - Number of Units]
      ,[Cost Per Unit]
      ,[Unit Forecast]
      ,[Take Rate - Engineering/Proforma]
      ,[ROI Take Rate]
      ,[Average Take Rate]
      ,[Capital Request]
      ,[Capital Request Q1]
      ,[Capital Request Q2]
      ,[Capital Request Q3]
      ,[Capital Request Q4]
      ,[Capital Cost Future Years]
      ,[Cost To Connect]
      ,[Total ISP Capital]
      ,[Total OSP Capital]
      ,[Total Capital]
      ,[Total Revenue]
      
      ,[Monthly Expense]
      ,[CIAC]
      ,[NPV]
      ,[IRR]
      ,[Payback]
      ,[Competitor]
      ,[Video Enabled State]
      ,[Terms in Months]
      ,[Type of Deal]
      ,[Brownfield/Greenfield]
      ,[Link Code]
      ,[Notes]
      ,[Additional Documents]
  FROM [ProjApproval].[InputScreen_PreSale_MDUSubdivision]
where [Project Number 7] != ''
and  [Project Number 7] != ' '
and  [Project Number 7] is not null
and [ProjApproval].[InputScreen_PreSale_MDUSubdivision].[Project Number 7] NOT IN
(select [Project Number]
from [ProjApproval].[InputScreen_PreSale_MDUSubdivision_Trimmed]
)



INSERT INTO [ProjApproval].[InputScreen_PreSale_MDUSubdivision_Trimmed]
           ([Opportunity ID]
      ,[Start time]
      ,[SubmitttedDtm]
      ,[SubmittedBy]
      ,[Name]
      ,[CRC Date]
      ,[Budget Category]
      ,[Build]
      ,[Project Description]
      ,[State]
      ,[Exchange]
      ,[BDT#]
      ,[Project Number]
      ,[Unit Opportunity - Number of Units]
      ,[Cost Per Unit]
      ,[Unit Forecast]
      ,[Take Rate - Engineering/Proforma]
      ,[ROI Take Rate]
      ,[Average Take Rate]
      ,[Capital Request]
      ,[Capital Request Q1]
      ,[Capital Request Q2]
      ,[Capital Request Q3]
      ,[Capital Request Q4]
      ,[Capital Cost Future Years]
      ,[Cost To Connect]
      ,[Total ISP Capital]
      ,[Total OSP Capital]
      ,[Total Capital]
      
      ,[Total Revenue]
      ,[Monthly Expense]
      ,[CIAC]
      ,[NPV]
      ,[IRR]
      ,[Payback]
      ,[Competitor]
      ,[Video Enabled State]
      ,[Terms in Months]
      ,[Type of Deal]
      ,[Brownfield/Greenfield]
      ,[Link Code]
      ,[Notes]
      ,[Additional Documents])

SELECT 'MDUSFU_'+[ID]
      ,[Start time]
      ,[SubmitttedDtm]
      ,[SubmittedBy]
      ,[Name]
      ,[CRC Date]
      ,[Budget Category]
      ,[Build]
      ,[Project Description]
      ,[State]
      ,[Exchange]
      ,[BDT#]
      ,[Project Number 8]
      ,[Unit Opportunity - Number of Units]
      ,[Cost Per Unit]
      ,[Unit Forecast]
      ,[Take Rate - Engineering/Proforma]
      ,[ROI Take Rate]
      ,[Average Take Rate]
      ,[Capital Request]
      ,[Capital Request Q1]
      ,[Capital Request Q2]
      ,[Capital Request Q3]
      ,[Capital Request Q4]
      ,[Capital Cost Future Years]
      ,[Cost To Connect]
      ,[Total ISP Capital]
      ,[Total OSP Capital]
      ,[Total Capital]
      
      ,[Total Revenue]
      ,[Monthly Expense]
      ,[CIAC]
      ,[NPV]
      ,[IRR]
      ,[Payback]
      ,[Competitor]
      ,[Video Enabled State]
      ,[Terms in Months]
      ,[Type of Deal]
      ,[Brownfield/Greenfield]
      ,[Link Code]
      ,[Notes]
      ,[Additional Documents]
  FROM [ProjApproval].[InputScreen_PreSale_MDUSubdivision]
where [Project Number 8] != ''
and  [Project Number 8] != ' '
and  [Project Number 8] is not null
and [ProjApproval].[InputScreen_PreSale_MDUSubdivision].[Project Number 8] NOT IN
(select [Project Number]
from [ProjApproval].[InputScreen_PreSale_MDUSubdivision_Trimmed]
)



INSERT INTO [ProjApproval].[InputScreen_PreSale_MDUSubdivision_Trimmed]
           ([Opportunity ID]
      ,[Start time]
      ,[SubmitttedDtm]
      ,[SubmittedBy]
      ,[Name]
      ,[CRC Date]
      ,[Budget Category]
      ,[Build]
      ,[Project Description]
      ,[State]
      ,[Exchange]
      ,[BDT#]
      ,[Project Number]
      ,[Unit Opportunity - Number of Units]
      ,[Cost Per Unit]
      ,[Unit Forecast]
      ,[Take Rate - Engineering/Proforma]
      ,[ROI Take Rate]
      ,[Average Take Rate]
      ,[Capital Request]
      ,[Capital Request Q1]
      ,[Capital Request Q2]
      ,[Capital Request Q3]
      ,[Capital Request Q4]
      ,[Capital Cost Future Years]
      ,[Cost To Connect]
      ,[Total ISP Capital]
      ,[Total OSP Capital]
      ,[Total Capital]
      ,[Total Revenue]
      
      ,[Monthly Expense]
      ,[CIAC]
      ,[NPV]
      ,[IRR]
      ,[Payback]
      ,[Competitor]
      ,[Video Enabled State]
      ,[Terms in Months]
      ,[Type of Deal]
      ,[Brownfield/Greenfield]
      ,[Link Code]
      ,[Notes]
      ,[Additional Documents])

SELECT 'MDUSFU_'+[ID]
      ,[Start time]
      ,[SubmitttedDtm]
      ,[SubmittedBy]
      ,[Name]
      ,[CRC Date]
      ,[Budget Category]
      ,[Build]
      ,[Project Description]
      ,[State]
      ,[Exchange]
      ,[BDT#]
      ,[Project Number 9]
      ,[Unit Opportunity - Number of Units]
      ,[Cost Per Unit]
      ,[Unit Forecast]
      ,[Take Rate - Engineering/Proforma]
      ,[ROI Take Rate]
      ,[Average Take Rate]
      ,[Capital Request]
      ,[Capital Request Q1]
      ,[Capital Request Q2]
      ,[Capital Request Q3]
      ,[Capital Request Q4]
      ,[Capital Cost Future Years]
      ,[Cost To Connect]
      ,[Total ISP Capital]
      ,[Total OSP Capital]
      ,[Total Capital]
      ,[Total Revenue]
      
      ,[Monthly Expense]
      ,[CIAC]
      ,[NPV]
      ,[IRR]
      ,[Payback]
      ,[Competitor]
      ,[Video Enabled State]
      ,[Terms in Months]
      ,[Type of Deal]
      ,[Brownfield/Greenfield]
      ,[Link Code]
      ,[Notes]
      ,[Additional Documents]
  FROM [ProjApproval].[InputScreen_PreSale_MDUSubdivision]
where [Project Number 9] != ''
and  [Project Number 9] != ' '
and  [Project Number 9] is not null
and [ProjApproval].[InputScreen_PreSale_MDUSubdivision].[Project Number 9] NOT IN
(select [Project Number]
from [ProjApproval].[InputScreen_PreSale_MDUSubdivision_Trimmed]
)



INSERT INTO [ProjApproval].[InputScreen_PreSale_MDUSubdivision_Trimmed]
           ([Opportunity ID]
      ,[Start time]
      ,[SubmitttedDtm]
      ,[SubmittedBy]
      ,[Name]
      ,[CRC Date]
      ,[Budget Category]
      ,[Build]
      ,[Project Description]
      ,[State]
      ,[Exchange]
      ,[BDT#]
      ,[Project Number]
      ,[Unit Opportunity - Number of Units]
      ,[Cost Per Unit]
      ,[Unit Forecast]
      ,[Take Rate - Engineering/Proforma]
      ,[ROI Take Rate]
      ,[Average Take Rate]
      ,[Capital Request]
      ,[Capital Request Q1]
      ,[Capital Request Q2]
      ,[Capital Request Q3]
      ,[Capital Request Q4]
      ,[Capital Cost Future Years]
      ,[Cost To Connect]
      ,[Total ISP Capital]
      ,[Total OSP Capital]
      ,[Total Capital]
      ,[Total Revenue]
      
      ,[Monthly Expense]
      ,[CIAC]
      ,[NPV]
      ,[IRR]
      ,[Payback]
      ,[Competitor]
      ,[Video Enabled State]
      ,[Terms in Months]
      ,[Type of Deal]
      ,[Brownfield/Greenfield]
      ,[Link Code]
      ,[Notes]
      ,[Additional Documents])

SELECT 'MDUSFU_'+[ID]
      ,[Start time]
      ,[SubmitttedDtm]
      ,[SubmittedBy]
      ,[Name]
      ,[CRC Date]
      ,[Budget Category]
      ,[Build]
      ,[Project Description]
      ,[State]
      ,[Exchange]
      ,[BDT#]
      ,[Project Number 10]
      ,[Unit Opportunity - Number of Units]
      ,[Cost Per Unit]
      ,[Unit Forecast]
      ,[Take Rate - Engineering/Proforma]
      ,[ROI Take Rate]
      ,[Average Take Rate]
      ,[Capital Request]
      ,[Capital Request Q1]
      ,[Capital Request Q2]
      ,[Capital Request Q3]
      ,[Capital Request Q4]
      ,[Capital Cost Future Years]
      ,[Cost To Connect]
      ,[Total ISP Capital]
      ,[Total OSP Capital]
      ,[Total Capital]
      
      ,[Total Revenue]
      ,[Monthly Expense]
      ,[CIAC]
      ,[NPV]
      ,[IRR]
      ,[Payback]
      ,[Competitor]
      ,[Video Enabled State]
      ,[Terms in Months]
      ,[Type of Deal]
      ,[Brownfield/Greenfield]
      ,[Link Code]
      ,[Notes]
      ,[Additional Documents]
  FROM [ProjApproval].[InputScreen_PreSale_MDUSubdivision]
where [Project Number 10] != ''
and  [Project Number 10] != ' '
and  [Project Number 10] is not null
and [ProjApproval].[InputScreen_PreSale_MDUSubdivision].[Project Number 10] NOT IN
(select [Project Number]
from [ProjApproval].[InputScreen_PreSale_MDUSubdivision_Trimmed]
)



Update ProjApproval.InputScreen_PreSale_MDUSubdivision_Trimmed
set build = replace(build, '["', '')
Update ProjApproval.InputScreen_PreSale_MDUSubdivision_Trimmed
set build = replace(build, '"]', '')

Update ProjApproval.InputScreen_PreSale_MDUSubdivision_Trimmed
set [Type of Deal] = replace([Type of Deal], '["', '')
Update ProjApproval.InputScreen_PreSale_MDUSubdivision_Trimmed
set [Type of Deal] = replace([Type of Deal], '"]', '')

Update ProjApproval.InputScreen_PreSale_MDUSubdivision_Trimmed
set [Brownfield/Greenfield] = replace([Brownfield/Greenfield], '["', '')
Update ProjApproval.InputScreen_PreSale_MDUSubdivision_Trimmed
set [Brownfield/Greenfield] = replace([Brownfield/Greenfield], '"]', '')


insert into ProjApproval.PreSale_Compiled
(
[Opportunity ID]
      ,[SubmitttedDtm]
      ,[SubmittedBy]
      ,[CRC Date]
      ,[Budget Category]
      ,[Build]
      ,[Project Description]
      ,[State]
      ,[Exchange]
      ,[BDT#]
      ,[Project Number]
      ,[Unit Opportunity]
      ,[Cost Per Unit]
      ,[Unit Forecast]
      ,[Take Rate - Engineering/Proforma]
      ,[ROI Take Rate]
      ,[Average Take Rate]
      ,[Capital Request]
      ,[Capital Request Q1]
      ,[Capital Request Q2]
      ,[Capital Request Q3]
      ,[Capital Request Q4]
      ,[Capital Cost Future Years]
      ,[Cost To Connect]
      ,[Total ISP Capital - Fully Loaded]
      ,[Total OSP Capital - Fully Loaded]
      ,[Total Capital - Fully Loaded]
      ,[Total Revenue]
      ,[Monthly Expense]
      ,[CIAC - Fully Loaded]
      ,[NPV - Fully Loaded]
      ,[IRR - Fully Loaded]
      ,[Payback - Fully Loaded]
      ,[Competitor]
      ,[Video Enabled State]
      ,[Term in Months]
      ,[Type of Deal]
      ,[Brownfield/Greenfield]
      ,[Link Code]
      ,[Notes]
      ,[Additional Documents]
)
SELECT [Opportunity ID]
      ,[SubmitttedDtm]
      ,[SubmittedBy]
      ,[CRC Date]
      ,[Budget Category]
      ,[Build]
      ,[Project Description]
      ,[State]
      ,[Exchange]
      ,[BDT#]
      ,[Project Number]
      ,[Unit Opportunity - Number of Units]
      ,[Cost Per Unit]
      ,[Unit Forecast]
      ,[Take Rate - Engineering/Proforma]
      ,[ROI Take Rate]
      ,[Average Take Rate]
      ,[Capital Request]
      ,[Capital Request Q1]
      ,[Capital Request Q2]
      ,[Capital Request Q3]
      ,[Capital Request Q4]
      ,[Capital Cost Future Years]
      ,[Cost To Connect]
      ,[Total ISP Capital]
      ,[Total OSP Capital]
      ,[Total Capital]
      ,[Total Revenue]
      ,[Monthly Expense]
      ,[CIAC]
      ,[NPV]
      ,[IRR]
      ,[Payback]
      ,[Competitor]
      ,[Video Enabled State]
      ,[Terms in Months]
      ,[Type of Deal]
      ,[Brownfield/Greenfield]
      ,[Link Code]
      ,[Notes]
      ,[Additional Documents]
  FROM [ProjApproval].[InputScreen_PreSale_MDUSubdivision_Trimmed]
where ProjApproval.[InputScreen_PreSale_MDUSubdivision_Trimmed].[Opportunity ID]
NOT IN (
select [Opportunity ID] from ProjApproval.PreSale_Compiled
)


delete from ProjApproval.PreSale_Compiled
FROM     ProjApproval.PreSale_Compiled INNER JOIN
                  ProjApproval.InputScreen_Projects_ExistingOpportunity_Trimmed ON ProjApproval.PreSale_Compiled.[Opportunity ID] = ProjApproval.InputScreen_Projects_ExistingOpportunity_Trimmed.OpportunityID
where ProjApproval.PreSale_Compiled.[Project Number] like 'TBD'


Update ProjApproval.PreSale_Compiled
set build = replace(build, '["', '')
Update ProjApproval.PreSale_Compiled
set build = replace(build, '"]', '')

Update ProjApproval.PreSale_Compiled
set [Type of Deal] = replace([Type of Deal], '["', '')
Update ProjApproval.PreSale_Compiled
set [Type of Deal] = replace([Type of Deal], '"]', '')

Update ProjApproval.PreSale_Compiled
set [Brownfield/Greenfield] = replace([Brownfield/Greenfield], '["', '')
Update ProjApproval.PreSale_Compiled
set [Brownfield/Greenfield] = replace([Brownfield/Greenfield], '"]', '')


Update ProjApproval.PreSale_Compiled
set [Project Number] = replace([Project Number], '.', '')

--Bring the data to MDUSFU PreSale history table
INSERT INTO [ProjApproval].[PreSale_MDUSFU_History]
           ([Opportunity ID]
           ,[Start time]
           ,[SubmitttedDtm]
           ,[SubmittedBy]
           ,[Name]
           ,[CRC Date]
           ,[Budget Category]
           ,[Build]
           ,[Project Description]
           ,[State]
           ,[Exchange]
           ,[BDT#]
           ,[Project Number]
           ,[Unit Opportunity - Number of Units]
           ,[Cost Per Unit]
           ,[Unit Forecast]
           ,[Take Rate - Engineering/Proforma]
           ,[ROI Take Rate]
           ,[Average Take Rate]
           ,[Capital Request]
           ,[Capital Request Q1]
           ,[Capital Request Q2]
           ,[Capital Request Q3]
           ,[Capital Request Q4]
           ,[Capital Cost Future Years]
           ,[Cost To Connect]
           ,[Total ISP Capital]
           ,[Total OSP Capital]
           ,[Total Capital]
           ,[Total Revenue]
           ,[Monthly Expense]
           ,[CIAC]
           ,[NPV]
           ,[IRR]
           ,[Payback]
           ,[Competitor]
           ,[Video Enabled State]
           ,[Terms in Months]
           ,[Type of Deal]
           ,[Brownfield/Greenfield]
           ,[Link Code]
           ,[Notes]
           ,[Additional Documents])
select 
[Opportunity ID]
           ,[SubmitttedDtm]
           ,[SubmitttedDtm]
           ,[SubmittedBy]
           ,[SubmittedBy]
           ,[CRC Date]
           ,[Budget Category]
           ,[Build]
           ,[Project Description]
           ,[State]
           ,[Exchange]
           ,[BDT#]
           ,[Project Number]
           ,[Unit Opportunity]
           ,[Cost Per Unit]
           ,[Unit Forecast]
           ,[Take Rate - Engineering/Proforma]
           ,[ROI Take Rate]
           ,[Average Take Rate]
           ,[Capital Request]
           ,[Capital Request Q1]
           ,[Capital Request Q2]
           ,[Capital Request Q3]
           ,[Capital Request Q4]
           ,[Capital Cost Future Years]
           ,[Cost To Connect]
           ,[Total ISP Capital - Fully Loaded]
           ,[Total OSP Capital - Fully Loaded]
           ,[Total Capital - Fully Loaded]
           ,[Total Revenue]
           ,[Monthly Expense]
           ,[CIAC - Fully Loaded]
           ,[NPV - Fully Loaded]
           ,[IRR - Fully Loaded]
           ,[Payback - Fully Loaded]
           ,[Competitor]
           ,[Video Enabled State]
           ,[Term in Months]
           ,[Type of Deal]
           ,[Brownfield/Greenfield]
           ,[Link Code]
           ,[Notes]
           ,[Additional Documents]
from ProjApproval.PreSale_Compiled
WHERE [Opportunity ID] LIKE '%MDUSFU%'
AND ProjApproval.PreSale_Compiled.[Opportunity ID] NOT IN
(SELECT [Opportunity ID] FROM [ProjApproval].[PreSale_MDUSFU_History])


delete from ProjApproval.InputScreen_PreSale_MDUSubdivision
delete from ProjApproval.InputScreen_PreSale_MDUSubdivision_Trimmed
UPDATE T
SET T.EVENTEND=CAST(GETDATE() AS DATETIME)
FROM LOG.Tracker T
INNER JOIN LOG.Tracker_Temp_ProjApproval__InputScreen_PreSale_MDUSubdivision_Trim P
ON T.EVENTID = P.LATESTID
DROP TABLE IF EXISTS LOG.Tracker_Temp_ProjApproval__InputScreen_PreSale_MDUSubdivision_Trim

	COMMIT TRANSACTION
END TRY
BEGIN CATCH
	IF @@trancount > 0 ROLLBACK TRANSACTION
	EXEC usp_error_handler
	RETURN 55555
END CATCH
