CREATE MULTISET TABLE USER_WORK.CM_WABB
(
DATA_MONTH        DATE FORMAT 'YYYY-MM-DD', 
CARRIER           VARCHAR(75),
CCNA              VARCHAR(3),
STATE             VARCHAR(2),
TARIFF_CD         VARCHAR(5),
PRODUCT           VARCHAR(10),
WTN               VARCHAR(10),
BTN               VARCHAR(10),
STN               VARCHAR(10),
GL_MATRIX_CLASS   VARCHAR(15),
PRD_SVC_CD        VARCHAR(10),
PRD_SVC_CD_DS     VARCHAR(50),
TOTAL_MRC         DECIMAL(10,2),
CUSTNAME          VARCHAR(50))
PRIMARY INDEX (DATA_MONTH, WTN);





