CREATE MULTISET TABLE USER_WORK.CM_WSA_RESALE
(
DATA_MONTH        DATE FORMAT 'YYYY-MM-DD', 
CARRIER           VARCHAR(75),
CCNA              VARCHAR(3),
STATE             VARCHAR(2),
TARIFF_CD         VARCHAR(5),
SVC_TYPE          VARCHAR(5),
SVC_TYPE_DESC     VARCHAR(50),
PRODUCT           VARCHAR(10),
WTN               VARCHAR(10),
BTN               VARCHAR(10),
STN               VARCHAR(10),
GL_MATRIX_CLASS   VARCHAR(10),
VOICE_MRC         DECIMAL(10,2),
VOICE_ADJUST      DECIMAL(10,2),
VOICE_PRO_RATED   DECIMAL(10,2),
VOICE_TOTAL       DECIMAL(10,2),
VOICE_SURCHARGE   DECIMAL(10,2))
PRIMARY INDEX (DATA_MONTH, WTN);







