CREATE MULTISET TABLE USER_WORK.CM_WSA_SUMMARY ,FALLBACK ,
     NO BEFORE JOURNAL,
     NO AFTER JOURNAL,
     CHECKSUM = DEFAULT,
     DEFAULT MERGEBLOCKRATIO,
     MAP = TD_MAP1
     (
      DATA_MONTH DATE FORMAT 'YYYY-MM-DD',
      CARRIER VARCHAR(75) CHARACTER SET LATIN NOT CASESPECIFIC,
      STATE VARCHAR(2) CHARACTER SET LATIN NOT CASESPECIFIC,
      VOICE_MRC DECIMAL(10,2),
      AVG_MRC DECIMAL(10,2),
      VOICE_SURCHARGE DECIMAL(10,2),
      AVG_SURCHARGE DECIMAL(10,2),
      LINES NUMERIC(10,0),
      GAINS NUMBER(10,0),
      LOSSES NUMBER(10,0))
PRIMARY INDEX ( DATA_MONTH ,CARRIER ,STATE);







