CREATE MULTISET TABLE USER_WORK.CM_WABB_LOOP_CODES
( 
LOOP_SE           VARCHAR(10),
LOOP_DESC         VARCHAR(50),
LOOP_PLAN         VARCHAR(25),
PRODUCT           VARCHAR(20),
SPEED             VARCHAR(15),
SPEED2            INT,
SPEED_CAT         VARCHAR(15),
SPEED_CAT2        VARCHAR(15),
SPEED_GROUP       INT,
SPEED_GROUP2      INT,
STAND_SHARE       VARCHAR(15),
COP_FIB           VARCHAR(10))
PRIMARY INDEX (LOOP_SE);





SELECT * FROM USER_WORK.CM_WABB_LOOP_CODES

DROP TABLE USER_WORK.CM_WABB_LOOP_CODES