select SVC_ACCS_METHD_NO, WRK_ORD_TYPE_CD, COMPLETION_DTTM, SVC_ORD_TYPE_CD, SVC_ORD_TYPE_DS, 
       SVC_ORD_RESULT_TYPE_CD, ADDR, CITY, STATE,
       CASE WHEN CUST_NM IS NOT NULL THEN CUST_NM ELSE ORG_NM END ORG_NM
  FROM (     
select distinct SO.SVC_ACCS_METHD_NO, SO.WRK_ORD_TYPE_CD, trunc(SO.COMPLETION_DTTM) COMPLETION_DTTM, SO.SVC_ORD_TYPE_CD, SO.SVC_ORD_TYPE_DS, 
       SO.SVC_ORD_RESULT_TYPE_CD, CUST.ADDR_LINE_1_TXT ADDR, CUST.CITY_NM CITY, CUST.STATE,      
       max(CUST.ORG_NM) cust_nm, max(ADDR.ORG_NM) org_nm
from EDW_VWMC.SERVICE_ORDERS_V SO 
       LEFT OUTER JOIN EDW_VWMC.LINE_NAME_ADDR_CURR_V CUST ON (SO.SVC_ACCS_METHD_NO  = CUST.SVC_ACCS_METHD_NO)
       LEFT OUTER JOIN EDW_VWMC.ACCT_NAME_ADDR_CURR_V ADDR ON (SO.ACCT_JOIN_KEY = ADDR.ACCT_JOIN_KEY)
-- WHERE svc_ord_type_cd in ('CO','PO','WT','ND','HI')
where to_char(SO.COMPLETION_DTTM,'yyyymm') IN ('202303','202304','202305')
and SO.svc_accs_methd_no in (
'9419576426',
'4087769578',
'9038939547'
)
group by SO.SVC_ACCS_METHD_NO, SO.WRK_ORD_TYPE_CD, SO.COMPLETION_DTTM, SO.SVC_ORD_TYPE_CD, SO.SVC_ORD_TYPE_DS, 
       SO.SVC_ORD_RESULT_TYPE_CD, CUST.ADDR_LINE_1_TXT, CUST.CITY_NM, CUST.STATE
) SUBQ      
order by 1,3 desc
;
