SELECT DISTINCT BILL_MONTH_DATE, CARRIER, CCNA, ADDRESS, CITY, STATE, ZIPCODE, SERVICE_TYPE, TARIFF_CD, PRODUCT,  
       WTN, BTN, STN, GL_MATRIX_CLASS, PRD_SVC_CD, PRD_SVC_CD_DS, TOTAL_MRC, CUSTNAME
FROM (
-- 8
SELECT DISTINCT CARRIER, CCNA, ADDRESS, CITY, STATE, ZIPCODE, TARIFF_CD, PRODUCT, BILL_MONTH_DATE, WTN, BTN, STN, 
       GL_MATRIX_CLASS, PRD_SVC_CD, PRD_SVC_CD_DS, VOICE_MRC USOC_MRC, TOT_CHRGE_AMT TOTAL_MRC, CUSTNAME, SERVICE_TYPE,
       ROW_NUMBER() OVER (PARTITION BY WTN ORDER BY VOICE_MRC DESC) R
    FROM (
-- 7    
SELECT 
   (SELECT SUM((CHRGE_AMT)-(PRORATED_CHARGE_AMT)) FROM EDW_VWMC.EUBS_BILL_REV_ACCT_DETAIL_V AS EUBS 
        WHERE SQ6.WTN = EUBS.SVC_ACCS_METHD_NO AND SQ6.BILL_MONTH_DATE = EUBS.BILL_MONTH_DATE
        AND BILL_AMT_TYPE_DS <> 'ADJUSTMENTS'
        AND GL_MATRIX_NO IN (SELECT GL_MATRIX_NO FROM USER_WORK.CM_GL_MATRIX WHERE GL_MATRIX_CLASS = 'DATA SERVICES'
                             AND PRD_SVC_CD NOT IN ('WMBF','WMDSL') AND SUBSTR(PRD_SVC_CD,1,3) NOT IN ('FZZ'))) AS TOT_CHRGE_AMT,
        SQ6.*
       FROM ( 
-- 6
SELECT DISTINCT CARRIER, CCNA, 
       STATE, TARIFF_CD, 'WABB' PRODUCT, BILL_MONTH_DATE, SQ5.WTN, SQ5.BTN, SQ5.STN, 
       GL_MATRIX_CLASS, PRD_SVC_CD, PRD_SVC_CD_DS, ADDRESS, CITY, ZIPCODE, SERVICE_TYPE,
   COALESCE(SUM(CASE WHEN GL_MATRIX_CLASS ='DATA SERVICES' AND BILL_AMT_TYPE_DS <> 'ADJUSTMENTS' THEN ((CHRGE_AMT)-(PRORATED_CHARGE_AMT)) END), 0) AS VOICE_MRC,
   COALESCE(SUM(CASE WHEN GL_MATRIX_CLASS ='DATA SERVICES' AND BILL_AMT_TYPE_DS = 'ADJUSTMENTS' THEN CHRGE_AMT END), 0) AS VOICE_ADJ,
   COALESCE(SUM(CASE WHEN GL_MATRIX_CLASS ='DATA SERVICES' AND PRORATED_CHARGE_AMT <> 0 THEN PRORATED_CHARGE_AMT END), 0) AS VOICE_PRO_RATED,
   COALESCE(SUM(CASE WHEN GL_MATRIX_CLASS ='DATA SERVICES' THEN CHRGE_AMT END), 0) AS VOICE_TOTAL,
   COALESCE(SUM(CASE WHEN GL_MATRIX_CLASS ='DATA SERVICES' AND BILL_AMT_TYPE_DS <> 'ADJUSTMENTS' AND SUBSTR(PRD_SVC_CD,4,1) = 'P' 
                 AND (PRD_SVC_CD_DS LIKE '%SCH%' OR PRD_SVC_CD_DS LIKE '%SCHG%' OR PRD_SVC_CD_DS LIKE '%SRCH%' OR PRD_SVC_CD_DS LIKE '%SRCHG%' OR
                      PRD_SVC_CD_DS LIKE '%SURCHARGE%' OR PRD_SVC_CD_DS LIKE '%SURCHG%' OR PRD_SVC_CD_DS LIKE '%SURCHRG%' OR PRD_SVC_CD_DS LIKE '%ZONE%') 
   THEN ((CHRGE_AMT)-(PRORATED_CHARGE_AMT)) END), 0) AS SURCHARGE_MRC,
   CUSTNAME, LOOP_CNT
   
 FROM (
-- 5 
SELECT DISTINCT CARRIER, CCNA, 
       STATE, TARIFF_CD, PRODUCT, WTN, BTN, STN, CUSTNAME, SERVICE_TYPE,
       ADDRESS, CITY, ZIPCODE, BILL_MONTH_DATE,
       CASE WHEN PRD_SVC_CD IN ('WHALP','WHAPB') THEN 'VOICE' ELSE GL_MATRIX_CLASS END GL_MATRIX_CLASS,
       BILL_AMT_TYPE_DS, CHRGE_AMT, PRORATED_CHARGE_AMT, PRD_SVC_CD, PRD_SVC_CD_DS,
       CASE WHEN PRD_SVC_CD IN (
       'CF15L','CF25L','CF30L','CF50L','CF75L','CFL0L','CFL1L','CFL2L','CFL3L','CFL50','CFL5L','CFL7L','FL634','HLC01','HLC02',
       'HLC04','HLC05','HLC07','HLC08','HLC09','HLMXL','L01WD','L02WD','L03WD','L04WD','L05WD','L06WD','L07WD','L08WD','L09FD',
       'L09WD','L10WD','L11WD','L13FD','L14FD','L14WD','L15FD','L15WD','L16FD','L16WD','L17FD','L17WD','L18FD','L18WD','L19WD',
       'L20WD','L21WD','L22FS','L22WD','L23WD','L24WD','L27WS','L28WS','L29WS','L30WS','L31FS','L31WS','L32FS','L32WS','L33FS',
       'L33WS','L34FS','L34WS','L35FS','L35WS','L36FS','L36WS','L39WS','L40WS','L41WS','L42WS','L43WS','L44WS','L45VD','L45WS',
       'L46WS','L47WS','L48WS','L49VD','L50VD','L51VD','L52VD','L53VD','L54VD','L63VS','L67VS','L68VS','L69VS','L70VS','L71VS',
       'L72VS','PTD1B','PTD1R','PTD3B','PTD3R','PTD3S','PTD7D','PTD7S','WBDLL','WBDML','WBMDL','WBSLL','WBSML','WBSRL','WBSTL',
       'WDPLB','WDPLS','WDTLB','WDTLS','WDWLS','WLSLS','WMLUB','WMLUS','WRBLL','WRBXL','WRUTL','WSBLL','WSBML','WSDLL','WSDML',
       'WSDPL','WSDRL','WSDTL','WSDWL','WSDXL','WSI1G','WSI2G','WSI30','WSI50','WSI70','WSLSL','WSMLD','WSMLU','WSMPL','WSMSL',
       'WSMTL','WSMXL','WSRML','WSSLL','WSSML','WSSPL','WSSRL','WSSTL','WSSXL','WURLL'
       ) THEN 1 ELSE 0 END LOOP_CNT
FROM (
-- 4
SELECT CARRIER, SERVICE_TYPE, CCNA, STATE, TARIFF_CD, PRODUCT, WTN, BTN, STN, CUSTNAME, ADDRESS, CITY, ZIPCODE,
       BILL_AMT_TYPE_DS, GL_MATRIX_NO, CHRGE_AMT, PRORATED_CHARGE_AMT, PRD_SVC_CD, PRD_SVC_CD_DS, BILL_CYCLE_DT, BILL_MONTH_DATE
FROM USER_WORK.CM_RVT_TEMP RVT
    LEFT OUTER JOIN EDW_VWMC.EUBS_BILL_REV_ACCT_DETAIL_V AS EUBS ON EUBS.SVC_ACCS_METHD_NO = RVT.WTN
    WHERE EUBS.BILL_MONTH_DATE ='2023-12-01'
   AND GL_MATRIX_NO <> '000' --excludes Non-Rev  
   AND GL_MATRIX_NO <> '124' --excludes Inside Wiring Non-Recurring
   AND PRD_SVC_CD NOT IN ('WMBF','WMDSL') AND SUBSTR(PRD_SVC_CD,1,3) NOT IN ('FZZ') -- MODEM & EARLY TERM CHARGES - NRC
     -- AND RVT.WTN = '8136543536'
-- 4 
)SQ4
 LEFT OUTER JOIN USER_WORK.CM_GL_MATRIX AS GLM ON GLM.GL_MATRIX_NO = SQ4.GL_MATRIX_NO
-- 5 
)SQ5
 WHERE GL_MATRIX_CLASS = 'DATA SERVICES'
  AND PRODUCT = 'WSA'
  AND WTN <> STN
  -- AND SUBHIST.SEQ = '0'
 GROUP BY CARRIER, CCNA, STATE, TARIFF_CD, BILL_MONTH_DATE, ADDRESS, CITY, ZIPCODE, SERVICE_TYPE,
         CUSTNAME, WTN, BTN, STN, GL_MATRIX_CLASS, CUSTNAME, PRD_SVC_CD, PRD_SVC_CD_DS, LOOP_CNT 
 -- 6        
 )SQ6
 -- 7
 )SQ7
  WHERE LOOP_CNT > 0 
 )SQ8
 WHERE R = 1
 ORDER BY 2,6,11;       