SELECT WTN, BTN, ENV, ORDNO, ORD_TYPE, ACT, PON, CARRIER_NAME, CCNA, SERV_TYPE, POST_DT, SUM(MRC) TOTAL_MRC
 FROM
(
SELECT DISTINCT ENV, ORDNO, ORD_TYPE, WTN, BTN, POST_DT, 
       E.XSOPON PON, F.PONACT ACT, E.XSODEC CCNA, G.CARRIER_NAME,
       CASE WHEN SV2STP IN ('WR','DL','LR') THEN 'RES' ELSE 'BUS' END SERV_TYPE, 
       H.SV7RTE AS MRC, H.SV7ITM AS SE_CODE   
 FROM       
( 
SELECT DISTINCT A.BILL_SUB_SYS ENV, MSOSO# AS ORDNO, MSOTOS ORD_TYPE, MSOPH# AS WTN, MSOMB# AS BTN, 
       CASE WHEN MSOPST > 0 THEN CAST(TO_CHAR(MSOPST) AS DATE FORMAT 'YYYYMMDD') ELSE NULL END POST_DT
FROM STG_DPI_VW.SVORD_LOAD A
INNER JOIN STG_DPI_VW.SV07_LOAD B
 ON A.MSOSO# = B.SV7SO# AND A.BILL_SUB_SYS = B.BILL_SUB_SYS
WHERE SV7ITM IN (
       'CF15L','CF25L','CF30L','CF50L','CF75L','CFL0L','CFL1L','CFL2L','CFL3L','CFL50','CFL5L','CFL7L','FL634','HLC01','HLC02',
       'HLC04','HLC05','HLC07','HLC08','HLC09','HLMXL','L01WD','L02WD','L03WD','L04WD','L05WD','L06WD','L07WD','L08WD','L09FD',
       'L09WD','L10WD','L11WD','L13FD','L14FD','L14WD','L15FD','L15WD','L16FD','L16WD','L17FD','L17WD','L18FD','L18WD','L19WD',
       'L20WD','L21WD','L22FS','L22WD','L23WD','L24WD','L27WS','L28WS','L29WS','L30WS','L31FS','L31WS','L32FS','L32WS','L33FS',
       'L33WS','L34FS','L34WS','L35FS','L35WS','L36FS','L36WS','L39WS','L40WS','L41WS','L42WS','L43WS','L44WS','L45VD','L45WS',
       'L46WS','L47WS','L48WS','L49VD','L50VD','L51VD','L52VD','L53VD','L54VD','L63VS','L67VS','L68VS','L69VS','L70VS','L71VS',
       'L72VS','PTD1B','PTD1R','PTD3B','PTD3R','PTD3S','PTD7D','PTD7S','WBDLL','WBDML','WBMDL','WBSLL','WBSML','WBSRL','WBSTL',
       'WDPLB','WDPLS','WDTLB','WDTLS','WDWLS','WLSLS','WMLUB','WMLUS','WRBLL','WRBXL','WRUTL','WSBLL','WSBML','WSDLL','WSDML',
       'WSDPL','WSDRL','WSDTL','WSDWL','WSDXL','WSI1G','WSI2G','WSI30','WSI50','WSI70','WSLSL','WSMLD','WSMLU','WSMPL','WSMSL',
       'WSMTL','WSMXL','WSRML','WSSLL','WSSML','WSSPL','WSSRL','WSSTL','WSSXL','WURLL') 
 AND MSOTOS IN ('CI')
 AND SV7STS <> 'D' 
 AND MSOPST between 20230901 and 20230930 -- *********************CHANGE HERE************************* 
) SQ1 
  FULL JOIN STG_DPI_VW.SV02_LOAD C
   ON SQ1.ORDNO = C.SV2SO# AND SQ1.ENV = C.BILL_SUB_SYS
  FULL JOIN STG_DPI_VW.SVORDX_LOAD E
   ON SQ1.ORDNO = E.XSOSO# AND SQ1.ENV = E.BILL_SUB_SYS
  LEFT OUTER JOIN STG_DPI_VW.LSPPON F
   ON E.XSOPON = F.PONPON# AND E.XSODEC = F.PONCCDE AND E.BILL_SUB_SYS = F.PONENV
  LEFT OUTER JOIN USER_WORK.CM_CARRIER_LIST G
   ON E.XSODEC = G.CCNA
  INNER JOIN STG_DPI_VW.SV07_LOAD H
   ON SQ1.ORDNO = H.SV7SO# AND SQ1.ENV = H.BILL_SUB_SYS 
   WHERE SV7ITM NOT IN ('WMBF','WMDSL','TAXCODE','WCBAF','FTTNR') AND SUBSTR(SV7ITM,1,3) NOT IN ('FZZ') 
    AND SV7STS <> 'D'
) SQ2
 GROUP BY WTN, BTN, ENV, ORDNO, ORD_TYPE, ACT, PON, CARRIER_NAME, CCNA, SERV_TYPE, POST_DT
 ORDER BY 8,1;  
 
 

