SELECT DISTINCT CARRIER, BILL_MONTH_DATE, WTN, PRD_SVC_CD, PRD_SVC_CD_DS, VOICE_MRC USOC_MRC, TOT_CHRGE_AMT TOTAL_MRC
    FROM (
-- 7    
SELECT 
   (SELECT SUM((CHRGE_AMT)-(PRORATED_CHARGE_AMT)) FROM EDW_VWMC.EUBS_BILL_REV_ACCT_DETAIL_V AS EUBS 
        WHERE SQ6.WTN = EUBS.SVC_ACCS_METHD_NO AND SQ6.BILL_MONTH_DATE = EUBS.BILL_MONTH_DATE
        AND BILL_AMT_TYPE_DS <> 'ADJUSTMENTS'
        AND GL_MATRIX_NO IN (SELECT GL_MATRIX_NO FROM USER_WORK.CM_GL_MATRIX WHERE GL_MATRIX_CLASS = 'DATA SERVICES'
                             AND PRD_SVC_CD NOT IN ('WMBF','WMDSL') AND SUBSTR(PRD_SVC_CD,1,3) NOT IN ('FZZ'))) AS TOT_CHRGE_AMT,
        SQ6.*
       FROM ( 
-- 6
SELECT DISTINCT CARRIER, CCNA, 
       STATE, TARIFF_CD, 'WABB' PRODUCT, BILL_MONTH_DATE, SQ5.WTN, SQ5.BTN, MASTERACCOUNTNUMBER STN, 
       GL_MATRIX_CLASS, PRD_SVC_CD, PRD_SVC_CD_DS, ADDRESS, CITY, ZIPCODE, SITE_CLLI, SERVICE_TYPE,
   COALESCE(SUM(CASE WHEN GL_MATRIX_CLASS ='DATA SERVICES' AND BILL_AMT_TYPE_DS <> 'ADJUSTMENTS' THEN ((CHRGE_AMT)-(PRORATED_CHARGE_AMT)) END), 0) AS VOICE_MRC,
   COALESCE(SUM(CASE WHEN GL_MATRIX_CLASS ='DATA SERVICES' AND BILL_AMT_TYPE_DS = 'ADJUSTMENTS' THEN CHRGE_AMT END), 0) AS VOICE_ADJ,
   COALESCE(SUM(CASE WHEN GL_MATRIX_CLASS ='DATA SERVICES' AND PRORATED_CHARGE_AMT <> 0 THEN PRORATED_CHARGE_AMT END), 0) AS VOICE_PRO_RATED,
   COALESCE(SUM(CASE WHEN GL_MATRIX_CLASS ='DATA SERVICES' THEN CHRGE_AMT END), 0) AS VOICE_TOTAL,
   COALESCE(SUM(CASE WHEN GL_MATRIX_CLASS ='DATA SERVICES' AND BILL_AMT_TYPE_DS <> 'ADJUSTMENTS' AND SUBSTR(PRD_SVC_CD,4,1) = 'P' 
                 AND (PRD_SVC_CD_DS LIKE '%SCH%' OR PRD_SVC_CD_DS LIKE '%SCHG%' OR PRD_SVC_CD_DS LIKE '%SRCH%' OR PRD_SVC_CD_DS LIKE '%SRCHG%' OR
                      PRD_SVC_CD_DS LIKE '%SURCHARGE%' OR PRD_SVC_CD_DS LIKE '%SURCHG%' OR PRD_SVC_CD_DS LIKE '%SURCHRG%' OR PRD_SVC_CD_DS LIKE '%ZONE%') 
   THEN ((CHRGE_AMT)-(PRORATED_CHARGE_AMT)) END), 0) AS SURCHARGE_MRC,
   CUSTNAME, LOOP_CNT
   
 FROM (
-- 5 
SELECT DISTINCT CARRIER, CCNA, 
       STATE, TARIFF_CD, BAN_TYPE, WTN, BTN, MASTERACCOUNTNUMBER, CUSTNAME, SERVICE_TYPE,
       ADDRESS, CITY, ZIPCODE, SITE_CLLI, BILL_MONTH_DATE,
       CASE WHEN PRD_SVC_CD IN ('WHALP','WHAPB') THEN 'VOICE' ELSE GL_MATRIX_CLASS END GL_MATRIX_CLASS,
       BILL_AMT_TYPE_DS, CHRGE_AMT, PRORATED_CHARGE_AMT, PRD_SVC_CD, PRD_SVC_CD_DS,
       CASE WHEN PRD_SVC_CD IN (
       'BDISM','CF15L','CF25L','CF30L','CF50L','CF75L','CFL0L','CFL1L','CFL2L','CFL3L','CFL50','CFL5L','CFL7L','DL564','DL7B1',
       'DLCUL','F15LS','FL409','FL633','FL634','FL640','FOXVL','H455L','HDULL','HL264','HL619','HL7KC','HLC01','HLC02','HLC04',
       'HLC05','HLC07','HLC08','HLC09','HLC10','HLC11','HLC13','HLC17','HLC28','HLMXC','HLMXL','HLULB','ICBL7','ICBLP',
       'ICBPL','IX14F','L01WD','L02WD','L03WD','L04WD','L05WD','L06WD','L07WD','L08WD','L09FD','L09WD','L10WD','L11WD','L13FD',
       'L14FD','L14WD','L15FD','L15WD','L16FD','L16WD','L17FD','L17WD','L18FD','L18WD','L19WD','L20WD','L21WD','L22FS','L22WD',
       'L23WD','L24WD','L27WS','L28WS','L29WS','L30WS','L31FS','L31WS','L32FS','L32WS','L33FS','L33WS','L34FS','L34WS','L35FS',
       'L35WS','L36FS','L36WS','L39WS','L40WS','L41WS','L42WS','L43WS','L44WS','L45VD','L45WS','L46WS','L47WS','L48WS','L49VD',
       'L50VD','L51VD','L52VD','L53VD','L54VD','L63VS','L67VS','L68VS','L69VS','L70VS','L71VS','L72VS','LCLTC','PT3DR','PTD1B',
       'PTD1R','PTD3B','PTD3R','PTD3S','PTD4S','PTD7B','PTD7D','PTD7S','RFL0L','RFL1L','RFL2L','RFL3L','RFL5L','RFL7L','SLS25',
       'SLS75','SSMLP','SULCL','W303L','W305L','W30L5','W30XL','W50BL','W50XL','WB15L','WB35L','WBDLL','WBDML','WBDPL','WBDRL',
       'WBDTL','WBDWL','WBDXL','WBLSL','WBLTL','WBMDL','WBMLU','WBMSL','WBPPL','WBSLL','WBSML','WBSPL','WBSRL','WBSTL','WBSXL',
       'WBTTL','WDPLB','WDPLS','WDTLB','WDTLS','WDWLB','WDWLS','WF15L','WF30L','WF35L','WFXVL','WL15B','WL15F','WL35B','WL35F',
       'WLRUL','WLSLS','WLTBL','WM15L','WM30L','WM4SL','WM4XL','WMBTL','WMLPL','WMLUB','WMLUS','WMPRL','WMU5L','WMXRL','WO15L',
       'WO35L','WOL15','WOL35','WPOWL','WRBLL','WRBXL','WRMXL','WRPRL','WRUTL','WS15L','WS35L','WS50L','WS55L','WSBIL','WSBLL',
       'WSBML','WSDLL','WSDML','WSDPL','WSDRL','WSDTL','WSDWL','WSDXL','WSI1G','WSI2G','WSI30','WSI50','WSI70','WSL15','WSL35',
       'WSLLD','WSLSL','WSM4L','WSMBL','WSMLD','WSMLU','WSMPL','WSMSL','WSMTL','WSMXL','WSPRL','WSRML','WSRPL','WSSLL','WSSML',
       'WSSPL','WSSRL','WSSTL','WSSXL','WSTML','WSXVL','WTR8L','WULRL','WURLL','WUTRL','WXDLS'
       ) THEN 1 ELSE 0 END LOOP_CNT
FROM (
-- 4
SELECT CASE WHEN CARRIER_NAME IS NOT NULL THEN CARRIER_NAME ELSE CARRIER END CARRIER, SERVICE_TYPE,
       CCNA, STATE, TARIFF_CD, BAN_TYPE, WTN, BTN, MASTERACCOUNTNUMBER, CUSTNAME, ADDRESS, CITY, ZIPCODE, SITE_CLLI,
       BILL_AMT_TYPE_DS, GL_MATRIX_NO, CHRGE_AMT, PRORATED_CHARGE_AMT, PRD_SVC_CD, PRD_SVC_CD_DS, BILL_CYCLE_DT, BILL_MONTH_DATE
FROM (
-- 3
SELECT MCL.PRIMARY_CARRIER_NAME CARRIER, CARLIS.CARRIER_NAME, SQ2.CCNA, BAN_STATE STATE, TARIFF_CD, CUSTNAME,
       CASE WHEN LCTD LIKE '%BUS%' THEN 'BUS'
            WHEN LCTD LIKE '%RES%' THEN 'RES'
            WHEN LCTD LIKE 'CLEC B%' THEN 'BUS'
            WHEN LCTD LIKE 'CLEC R%' THEN 'RES'
            WHEN LCTD LIKE 'CL B%' THEN 'BUS'
            WHEN LCTD LIKE 'CL R%' THEN 'RES'
            WHEN LCTD LIKE 'B %' THEN 'BUS'
            WHEN LCTD LIKE 'R %' THEN 'RES'
            WHEN LCTD LIKE '%CENTREX%' THEN 'BUS'
            ELSE NULL END SERVICE_TYPE,
       BAN_TYPE, WTN, BTN, MASTERACCOUNTNUMBER, ADDRESS, CITY, ZIPCODE, SITE_CLLI
FROM (
-- 2
SELECT LSPBAN.BANCARCD CCNA, SQ1.WTN, SQ1.BTN, SQ1.MASTERACCOUNTNUMBER, CUSTNAME, LCTD,
       SQ1.STATE, LSPBAN.BANSTACD BAN_STATE, LSPBAN.BANTRFCD TARIFF_CD, ADDRESS, CITY, ZIPCODE, SITE_CLLI,
       CASE WHEN LSPBAN.BANSUMTYP IN ('D','B','C','E','F','G','H','I','J','K') THEN 'DIRECTORY'
            WHEN LSPBAN.BANSUMTYP IN ('P','W','X','Y','Z') THEN 'WSA'
            WHEN LSPBAN.BANSUMTYP IN ('L','M','N','O','A','Q') THEN 'LOOP'
            WHEN LSPBAN.BANSUMTYP IN ('R','S','T','U','V') THEN 'RESALE'
            WHEN LSPBAN.BANSUMTYP IN ('I') THEN 'ISP'
            ELSE NULL END BAN_TYPE
FROM (
-- 1
SELECT DISTINCT SUBSTR(TRIM(TELEPHONENUMBER),1,10) WTN, 
       SUBSTR(TRIM(BILLINGTELEPHONE),1,10) BTN, 
       SUBSTR(TRIM(C2F.MASTERACCOUNTNUMBER),1,10) MASTERACCOUNTNUMBER, 
       C2F.ADDRESS,
       C2F.CITY,
       C2F.STATE,
       C2F.ZIPCODE,
       C2F.SUBSCRIPTIONUSERNAME CUSTNAME,
       C2F.LINE_CARD_TYPE_DESC LCTD,
       C2F.OFFICE_CLLI8_SITE_ID SITE_CLLI
FROM EDW_VWMC.C2F_EXCHANGE_SUBSCRIBERS C2F
WHERE MASTERACCOUNTNUMBER IS NOT NULL
      -- AND C2F.TELEPHONENUMBER in ('8135712586')
-- 1
)SQ1,
 USER_WORK.CM_LSPBANM LSPBAN
 WHERE SQ1.MASTERACCOUNTNUMBER = LSPBAN.STN
  -- AND SUBSTR(LSPBAN.BANCARCD,1,1) = 'Z'
-- 2 
)SQ2
 LEFT OUTER JOIN USER_WORK.CM_CARRIER_ACNA_MCL_202201 AS MCL ON MCL.SECONDARY_ID = SQ2.CCNA
 LEFT OUTER JOIN USER_WORK.CM_CARRIER_LIST AS CARLIS ON CARLIS.CCNA = SQ2.CCNA
-- 3
)SQ3 
 LEFT OUTER JOIN EDW_VWMC.EUBS_BILL_REV_ACCT_DETAIL_V AS EUBS ON EUBS.SVC_ACCS_METHD_NO = SQ3.WTN
    WHERE EUBS.BILL_MONTH_DATE ='2023-06-01'
   AND GL_MATRIX_NO <> '000' --excludes Non-Rev  
   AND GL_MATRIX_NO <> '124' --excludes Inside Wiring Non-Recurring
   AND PRD_SVC_CD NOT IN ('WMBF','WMDSL') AND SUBSTR(PRD_SVC_CD,1,3) NOT IN ('FZZ') -- MODEM & EARLY TERM CHARGES - NRC
   -- AND BILL_AMT_TYPE_DS <> 'ADJUSTMENTS'
-- 4 
)SQ4
 LEFT OUTER JOIN USER_WORK.CM_GL_MATRIX AS GLM ON GLM.GL_MATRIX_NO = SQ4.GL_MATRIX_NO
-- 5 
)SQ5
 WHERE GL_MATRIX_CLASS = 'DATA SERVICES'
  AND BAN_TYPE = 'WSA'
  AND WTN <> STN
  -- AND SUBHIST.SEQ = '0'
 GROUP BY CARRIER, CCNA, STATE, TARIFF_CD, BAN_TYPE, BILL_MONTH_DATE, ADDRESS, CITY, ZIPCODE, SITE_CLLI, SERVICE_TYPE,
         CUSTNAME, WTN, BTN, MASTERACCOUNTNUMBER, GL_MATRIX_CLASS, CUSTNAME, PRD_SVC_CD, PRD_SVC_CD_DS, LOOP_CNT 
 -- 6        
 )SQ6
 -- 7
 )SQ7
 order by 1,3;     