SELECT ORDNO, ENV, PON, ACT, ORD_TYPE, SERV_TYPE, WTN, BTN, SE_CODE, LC.COP_FIB NETWORK, SQ.CCNA, 
       CL.CARRIER_NAME CARRIER, POST_DT, 
       OREPLACE(ADDRESS,'.','') ADDRESS, CITY, STATE, 
       EUBS.GL_MATRIX_NO, EUBS.CHRGE_AMT-EUBS.PRORATED_CHARGE_AMT MRC, EUBS.PRD_SVC_CD, EUBS.PRD_SVC_CD_DS, EUBS.BILL_MONTH_DATE,
       EUBS2.GL_MATRIX_NO GL2, EUBS2.CHRGE_AMT-EUBS2.PRORATED_CHARGE_AMT MRC2, EUBS2.PRD_SVC_CD PRD2, EUBS2.PRD_SVC_CD_DS PRD_DES2, EUBS2.BILL_MONTH_DATE BILL2
   FROM (         
SELECT DISTINCT A.BILL_SUB_SYS ENV, MSOSO# AS ORDNO, E.XSOPON PON, F.PONACT ACT, MSOTOS ORD_TYPE,
       CASE WHEN SV2STP IN ('WR','DL','LR') THEN 'RES' ELSE 'BUS' END SERV_TYPE, 
       MSOPH# AS WTN, MSOMB# AS BTN, SV7ITM AS SE_CODE, E.XSODEC CCNA, G.CARRIER_NAME, 
       CASE WHEN MSOPST > 0 THEN CAST(TO_CHAR(MSOPST) AS DATE FORMAT 'YYYYMMDD') ELSE NULL END POST_DT,
       TRIM(MSOST#)||' '||TRIM(MSOSTR)||' '||TRIM(MSOSST) AS ADDRESS, CTYDES AS CITY, MSOSTA AS STATE
FROM STG_DPI_VW.SVORD_LOAD A
INNER JOIN STG_DPI_VW.SV07_LOAD B
 ON A.MSOSO# = B.SV7SO# AND A.BILL_SUB_SYS = B.BILL_SUB_SYS
FULL JOIN STG_DPI_VW.SV02_LOAD C
 ON A.MSOSO# = C.SV2SO# AND A.BILL_SUB_SYS = C.BILL_SUB_SYS
FULL JOIN STG_DPI_VW.DBCTY D
 ON A.MSOCTY = D.CTYCAB AND A.BILL_SUB_SYS = D.BILL_SUB_SYS
FULL JOIN STG_DPI_VW.SVORDX_LOAD E
 ON A.MSOSO# = E.XSOSO# AND A.BILL_SUB_SYS = E.BILL_SUB_SYS
LEFT OUTER JOIN STG_DPI_VW.LSPPON F
 ON E.XSOPON = F.PONPON# AND E.XSODEC = F.PONCCDE AND E.BILL_SUB_SYS = F.PONENV
LEFT OUTER JOIN USER_WORK.CM_CARRIER_LIST G
 ON E.XSODEC = G.CCNA
 WHERE SV7ITM IN (
       'CF15L','CF25L','CF30L','CF50L','CF75L','CFL0L','CFL1L','CFL2L','CFL3L','CFL50','CFL5L','CFL7L','FL634','HLC01','HLC02',
       'HLC04','HLC05','HLC07','HLC08','HLC09','HLMXL','L01WD','L02WD','L03WD','L04WD','L05WD','L06WD','L07WD','L08WD','L09FD',
       'L09WD','L10WD','L11WD','L13FD','L14FD','L14WD','L15FD','L15WD','L16FD','L16WD','L17FD','L17WD','L18FD','L18WD','L19WD',
       'L20WD','L21WD','L22FS','L22WD','L23WD','L24WD','L27WS','L28WS','L29WS','L30WS','L31FS','L31WS','L32FS','L32WS','L33FS',
       'L33WS','L34FS','L34WS','L35FS','L35WS','L36FS','L36WS','L39WS','L40WS','L41WS','L42WS','L43WS','L44WS','L45VD','L45WS',
       'L46WS','L47WS','L48WS','L49VD','L50VD','L51VD','L52VD','L53VD','L54VD','L63VS','L67VS','L68VS','L69VS','L70VS','L71VS',
       'L72VS','PTD1B','PTD1R','PTD3B','PTD3R','PTD3S','PTD7D','PTD7S','WBDLL','WBDML','WBMDL','WBSLL','WBSML','WBSRL','WBSTL',
       'WDPLB','WDPLS','WDTLB','WDTLS','WDWLS','WLSLS','WMLUB','WMLUS','WRBLL','WRBXL','WRUTL','WSBLL','WSBML','WSDLL','WSDML',
       'WSDPL','WSDRL','WSDTL','WSDWL','WSDXL','WSI1G','WSI2G','WSI30','WSI50','WSI70','WSLSL','WSMLD','WSMLU','WSMPL','WSMSL',
       'WSMTL','WSMXL','WSRML','WSSLL','WSSML','WSSPL','WSSRL','WSSTL','WSSXL','WURLL')
 AND MSOTOS IN ('CI')
 and MSOPH# in ('9723175284','8054855488','3049656515')
 AND SV7STS <> 'D' 
 AND MSOPST between 20230801 and 20230831 -- *********************CHANGE HERE*************************
 ) SQ
 LEFT OUTER JOIN USER_WORK.CM_CARRIER_LIST CL 
  ON SQ.CCNA = CL.CCNA
 LEFT OUTER JOIN USER_WORK.CM_WABB_LOOP_CODES LC 
  ON SQ.SE_CODE = LC.LOOP_SE
 LEFT OUTER JOIN EDW_VWMC.EUBS_BILL_REV_ACCT_DETAIL_V EUBS 
  ON to_CHAR(SQ.WTN) = EUBS.SVC_ACCS_METHD_NO 
 LEFT OUTER JOIN EDW_VWMC.EUBS_BILL_REV_ACCT_DETAIL_V EUBS2 
  ON to_CHAR(SQ.WTN) = EUBS2.SVC_ACCS_METHD_NO  
  WHERE EUBS.BILL_MONTH_DATE IN ('2023-08-01')  -- ****************CHANGE HERE TO CURRENT MONTH********************
   AND EUBS2.BILL_MONTH_DATE IN ('2023-09-01')  -- ***************CHANGE HERE TO 1 MONTH AFTER POST MONTH***************
   AND EUBS.GL_MATRIX_NO <> '000' --excludes Non-Rev  
   AND EUBS.GL_MATRIX_NO <> '124' --excludes Inside Wiring Non-Recurring
   AND EUBS.PRD_SVC_CD NOT IN ('WMBF','WMDSL','TAXCODE','WCBAF') AND SUBSTR(EUBS.PRD_SVC_CD,1,3) NOT IN ('FZZ')
   AND EUBS2.GL_MATRIX_NO <> '000' --excludes Non-Rev  
   AND EUBS2.GL_MATRIX_NO <> '124' --excludes Inside Wiring Non-Recurring
   AND EUBS2.PRD_SVC_CD NOT IN ('WMBF','WMDSL','TAXCODE','WCBAF') AND SUBSTR(EUBS2.PRD_SVC_CD,1,3) NOT IN ('FZZ')  
   



