SELECT ORDNO, ENV, PON, ACT, ORD_TYPE, SERV_TYPE, STATUS, WTN, BTN, SE_CODE, CCNA, CUSTNM, 
       SO_CREATE_DT, SO_EFF_COMP_DT, SO_ACT_COMP_DT, POST_DT, AGING,
       CASE WHEN AGING BETWEEN 0 AND 10 THEN '0-10'  
            WHEN AGING BETWEEN 11 AND 20 THEN '11-20'
            WHEN AGING BETWEEN 21 AND 30 THEN '21-30'
            WHEN AGING BETWEEN 31 AND 60 THEN '31-60'
            WHEN AGING BETWEEN 61 AND 90 THEN '61-90'
            WHEN AGING IS NULL THEN NULL
            ELSE '90+' END AGING_GRP,
       ADDRESS, CITY, STATE     
   FROM (         
SELECT DISTINCT 'CP1FT' AS ENV, MSOSO# AS ORDNO, E.XSOPON PON, F.PONACT ACT, 
       CASE WHEN MSOTOS = 'CI' THEN 'NEW(CI)' WHEN MSOTOS = 'CO' THEN 'DISC(CO)' END ORD_TYPE,
       CASE WHEN SV2STP IN ('WR','DL','LR') THEN 'RES' ELSE 'BUS' END SERV_TYPE,
       CASE WHEN MSOPST > 0 THEN 'COMPLETE' ELSE 'PENDING' END STATUS,
       MSOPH# AS WTN, MSOMB# AS BTN, SV7ITM AS SE_CODE, E.XSODEC CCNA, MSOLSN||MSOFRN AS CUSTNM,  
       CAST(SUBSTR(MSOSDT,5,2)||'/'||SUBSTR(MSOSDT,7,2)||'/'||SUBSTR(MSOSDT,1,4) AS DATE) SO_CREATE_DT,
       CASE WHEN MSOEDT > 0 THEN CAST(SUBSTR(MSOEDT,5,2)||'/'||SUBSTR(MSOEDT,7,2)||'/'||SUBSTR(MSOEDT,1,4) AS DATE) ELSE NULL END SO_EFF_COMP_DT, 
       CASE WHEN MSOCPD > 0 THEN CAST(SUBSTR(MSOCPD,5,2)||'/'||SUBSTR(MSOCPD,7,2)||'/'||SUBSTR(MSOCPD,1,4) AS DATE) ELSE NULL END SO_ACT_COMP_DT,
       CASE WHEN MSOPST > 0 THEN CAST(SUBSTR(MSOPST,5,2)||'/'||SUBSTR(MSOPST,7,2)||'/'||SUBSTR(MSOPST,1,4) AS DATE) ELSE NULL END POST_DT,
       CASE WHEN MSOPST > 0 THEN NULL 
            ELSE DAYS(CURRENT_DATE)-DAYS(CAST(SUBSTR(MSOSDT,5,2)||'/'||SUBSTR(MSOSDT,7,2)||'/'||SUBSTR(MSOSDT,1,4) AS DATE)) END AGING,
       TRIM(MSOST#)||' '||TRIM(MSOSTR)||' '||TRIM(MSOSST) AS ADDRESS, CTYDES AS CITY, MSOSTA AS STATE
FROM CP1FT.SVORD A
INNER JOIN CP1FT.SV07 B
 ON A.MSOSO# = B.SV7SO#
FULL JOIN CP1FT.SV02 C
 ON A.MSOSO# = C.SV2SO#
FULL JOIN CP1FT.DBCTY D
 ON A.MSOCTY = D.CTYCAB
FULL JOIN CP1FT.SVORDX E
 ON A.MSOSO# = E.XSOSO#
LEFT OUTER JOIN CP1##.LSPPON F
 ON E.XSOPON = F.PONPON# AND E.XSODEC = F.PONCCDE
 WHERE SV7ITM IN (
       'CF15L','CF25L','CF30L','CF50L','CF75L','CFL0L','CFL1L','CFL2L','CFL3L','CFL50','CFL5L','CFL7L','FL634','HLC01','HLC02',
       'HLC04','HLC05','HLC07','HLC08','HLC09','HLMXL','L01WD','L02WD','L03WD','L04WD','L05WD','L06WD','L07WD','L08WD','L09FD',
       'L09WD','L10WD','L11WD','L13FD','L14FD','L14WD','L15FD','L15WD','L16FD','L16WD','L17FD','L17WD','L18FD','L18WD','L19WD',
       'L20WD','L21WD','L22FS','L22WD','L23WD','L24WD','L27WS','L28WS','L29WS','L30WS','L31FS','L31WS','L32FS','L32WS','L33FS',
       'L33WS','L34FS','L34WS','L35FS','L35WS','L36FS','L36WS','L39WS','L40WS','L41WS','L42WS','L43WS','L44WS','L45VD','L45WS',
       'L46WS','L47WS','L48WS','L49VD','L50VD','L51VD','L52VD','L53VD','L54VD','L63VS','L67VS','L68VS','L69VS','L70VS','L71VS',
       'L72VS','PTD1B','PTD1R','PTD3B','PTD3R','PTD3S','PTD7D','PTD7S','WBDLL','WBDML','WBMDL','WBSLL','WBSML','WBSRL','WBSTL',
       'WDPLB','WDPLS','WDTLB','WDTLS','WDWLS','WLSLS','WMLUB','WMLUS','WRBLL','WRBXL','WRUTL','WSBLL','WSBML','WSDLL','WSDML',
       'WSDPL','WSDRL','WSDTL','WSDWL','WSDXL','WSI1G','WSI2G','WSI30','WSI50','WSI70','WSLSL','WSMLD','WSMLU','WSMPL','WSMSL',
       'WSMTL','WSMXL','WSRML','WSSLL','WSSML','WSSPL','WSSRL','WSSTL','WSSXL','WURLL')
 AND MSOTOS IN ('CI','CO')
 AND MSOSTS <> 'D' 
 AND SV7STS <> 'D' 
 AND (MSOPST >= 20230101 OR MSOPST = 0)
   -- AND MSOSO# IN ('082955761','083440426')

 UNION ALL
 
select distinct 'CP1CZ' as ENV, MSOSO# AS ORDNO, E.XSOPON PON, F.PONACT ACT, 
       CASE WHEN MSOTOS = 'CI' THEN 'NEW(CI)' WHEN MSOTOS = 'CO' THEN 'DISC(CO)' END ORD_TYPE,
       CASE WHEN SV2STP IN ('WR','DL','LR') THEN 'RES' ELSE 'BUS' END SERV_TYPE,
       CASE WHEN MSOPST > 0 THEN 'COMPLETE' ELSE 'PENDING' END STATUS,
       MSOPH# AS WTN, MSOMB# AS BTN, SV7ITM AS SE_CODE, E.XSODEC CCNA, MSOLSN||MSOFRN AS CUSTNM,  
       CAST(SUBSTR(MSOSDT,5,2)||'/'||SUBSTR(MSOSDT,7,2)||'/'||SUBSTR(MSOSDT,1,4) AS DATE) SO_CREATE_DT,
       CASE WHEN MSOEDT > 0 THEN CAST(SUBSTR(MSOEDT,5,2)||'/'||SUBSTR(MSOEDT,7,2)||'/'||SUBSTR(MSOEDT,1,4) AS DATE) ELSE NULL END SO_EFF_COMP_DT, 
       CASE WHEN MSOCPD > 0 THEN CAST(SUBSTR(MSOCPD,5,2)||'/'||SUBSTR(MSOCPD,7,2)||'/'||SUBSTR(MSOCPD,1,4) AS DATE) ELSE NULL END SO_ACT_COMP_DT,
       CASE WHEN MSOPST > 0 THEN CAST(SUBSTR(MSOPST,5,2)||'/'||SUBSTR(MSOPST,7,2)||'/'||SUBSTR(MSOPST,1,4) AS DATE) ELSE NULL END POST_DT,
       CASE WHEN MSOPST > 0 THEN NULL 
            ELSE DAYS(CURRENT_DATE)-DAYS(CAST(SUBSTR(MSOSDT,5,2)||'/'||SUBSTR(MSOSDT,7,2)||'/'||SUBSTR(MSOSDT,1,4) AS DATE)) END AGING,
       TRIM(MSOST#)||' '||TRIM(MSOSTR)||' '||TRIM(MSOSST) AS ADDRESS, CTYDES AS CITY, MSOSTA AS STATE
FROM CP1CZ.SVORD A
INNER JOIN CP1CZ.SV07 B
 ON A.MSOSO# = B.SV7SO#
FULL JOIN CP1CZ.SV02 C
 ON A.MSOSO# = C.SV2SO#
FULL JOIN CP1CZ.DBCTY D
 ON A.MSOCTY = D.CTYCAB
FULL JOIN CP1CZ.SVORDX E
 ON A.MSOSO# = E.XSOSO#
LEFT OUTER JOIN CP1##.LSPPON F
 ON E.XSOPON = F.PONPON# AND E.XSODEC = F.PONCCDE 
 WHERE SV7ITM IN (
       'CF15L','CF25L','CF30L','CF50L','CF75L','CFL0L','CFL1L','CFL2L','CFL3L','CFL50','CFL5L','CFL7L','FL634','HLC01','HLC02',
       'HLC04','HLC05','HLC07','HLC08','HLC09','HLMXL','L01WD','L02WD','L03WD','L04WD','L05WD','L06WD','L07WD','L08WD','L09FD',
       'L09WD','L10WD','L11WD','L13FD','L14FD','L14WD','L15FD','L15WD','L16FD','L16WD','L17FD','L17WD','L18FD','L18WD','L19WD',
       'L20WD','L21WD','L22FS','L22WD','L23WD','L24WD','L27WS','L28WS','L29WS','L30WS','L31FS','L31WS','L32FS','L32WS','L33FS',
       'L33WS','L34FS','L34WS','L35FS','L35WS','L36FS','L36WS','L39WS','L40WS','L41WS','L42WS','L43WS','L44WS','L45VD','L45WS',
       'L46WS','L47WS','L48WS','L49VD','L50VD','L51VD','L52VD','L53VD','L54VD','L63VS','L67VS','L68VS','L69VS','L70VS','L71VS',
       'L72VS','PTD1B','PTD1R','PTD3B','PTD3R','PTD3S','PTD7D','PTD7S','WBDLL','WBDML','WBMDL','WBSLL','WBSML','WBSRL','WBSTL',
       'WDPLB','WDPLS','WDTLB','WDTLS','WDWLS','WLSLS','WMLUB','WMLUS','WRBLL','WRBXL','WRUTL','WSBLL','WSBML','WSDLL','WSDML',
       'WSDPL','WSDRL','WSDTL','WSDWL','WSDXL','WSI1G','WSI2G','WSI30','WSI50','WSI70','WSLSL','WSMLD','WSMLU','WSMPL','WSMSL',
       'WSMTL','WSMXL','WSRML','WSSLL','WSSML','WSSPL','WSSRL','WSSTL','WSSXL','WURLL')
 AND MSOTOS IN ('CI','CO')
 AND MSOSTS <> 'D' 
 AND SV7STS <> 'D' 
 AND (MSOPST >= 20230101 OR MSOPST = 0)
 
 UNION ALL
 
select distinct 'CP1MS' as ENV, MSOSO# AS ORDNO, E.XSOPON PON, F.PONACT ACT, 
       CASE WHEN MSOTOS = 'CI' THEN 'NEW(CI)' WHEN MSOTOS = 'CO' THEN 'DISC(CO)' END ORD_TYPE,
       CASE WHEN SV2STP IN ('WR','DL','LR') THEN 'RES' ELSE 'BUS' END SERV_TYPE,
       CASE WHEN MSOPST > 0 THEN 'COMPLETE' ELSE 'PENDING' END STATUS,
       MSOPH# AS WTN, MSOMB# AS BTN, SV7ITM AS SE_CODE, E.XSODEC CCNA, MSOLSN||MSOFRN AS CUSTNM,  
       CAST(SUBSTR(MSOSDT,5,2)||'/'||SUBSTR(MSOSDT,7,2)||'/'||SUBSTR(MSOSDT,1,4) AS DATE) SO_CREATE_DT,
       CASE WHEN MSOEDT > 0 THEN CAST(SUBSTR(MSOEDT,5,2)||'/'||SUBSTR(MSOEDT,7,2)||'/'||SUBSTR(MSOEDT,1,4) AS DATE) ELSE NULL END SO_EFF_COMP_DT, 
       CASE WHEN MSOCPD > 0 THEN CAST(SUBSTR(MSOCPD,5,2)||'/'||SUBSTR(MSOCPD,7,2)||'/'||SUBSTR(MSOCPD,1,4) AS DATE) ELSE NULL END SO_ACT_COMP_DT,
       CASE WHEN MSOPST > 0 THEN CAST(SUBSTR(MSOPST,5,2)||'/'||SUBSTR(MSOPST,7,2)||'/'||SUBSTR(MSOPST,1,4) AS DATE) ELSE NULL END POST_DT,
       CASE WHEN MSOPST > 0 THEN NULL 
            ELSE DAYS(CURRENT_DATE)-DAYS(CAST(SUBSTR(MSOSDT,5,2)||'/'||SUBSTR(MSOSDT,7,2)||'/'||SUBSTR(MSOSDT,1,4) AS DATE)) END AGING,
       TRIM(MSOST#)||' '||TRIM(MSOSTR)||' '||TRIM(MSOSST) AS ADDRESS, CTYDES AS CITY, MSOSTA AS STATE
FROM CP1MS.SVORD A
INNER JOIN CP1MS.SV07 B
 ON A.MSOSO# = B.SV7SO#
FULL JOIN CP1MS.SV02 C
 ON A.MSOSO# = C.SV2SO#
FULL JOIN CP1MS.DBCTY D
 ON A.MSOCTY = D.CTYCAB
FULL JOIN CP1MS.SVORDX E
 ON A.MSOSO# = E.XSOSO#
LEFT OUTER JOIN CP1##.LSPPON F
 ON E.XSOPON = F.PONPON# AND E.XSODEC = F.PONCCDE 
 WHERE SV7ITM IN (
       'CF15L','CF25L','CF30L','CF50L','CF75L','CFL0L','CFL1L','CFL2L','CFL3L','CFL50','CFL5L','CFL7L','FL634','HLC01','HLC02',
       'HLC04','HLC05','HLC07','HLC08','HLC09','HLMXL','L01WD','L02WD','L03WD','L04WD','L05WD','L06WD','L07WD','L08WD','L09FD',
       'L09WD','L10WD','L11WD','L13FD','L14FD','L14WD','L15FD','L15WD','L16FD','L16WD','L17FD','L17WD','L18FD','L18WD','L19WD',
       'L20WD','L21WD','L22FS','L22WD','L23WD','L24WD','L27WS','L28WS','L29WS','L30WS','L31FS','L31WS','L32FS','L32WS','L33FS',
       'L33WS','L34FS','L34WS','L35FS','L35WS','L36FS','L36WS','L39WS','L40WS','L41WS','L42WS','L43WS','L44WS','L45VD','L45WS',
       'L46WS','L47WS','L48WS','L49VD','L50VD','L51VD','L52VD','L53VD','L54VD','L63VS','L67VS','L68VS','L69VS','L70VS','L71VS',
       'L72VS','PTD1B','PTD1R','PTD3B','PTD3R','PTD3S','PTD7D','PTD7S','WBDLL','WBDML','WBMDL','WBSLL','WBSML','WBSRL','WBSTL',
       'WDPLB','WDPLS','WDTLB','WDTLS','WDWLS','WLSLS','WMLUB','WMLUS','WRBLL','WRBXL','WRUTL','WSBLL','WSBML','WSDLL','WSDML',
       'WSDPL','WSDRL','WSDTL','WSDWL','WSDXL','WSI1G','WSI2G','WSI30','WSI50','WSI70','WSLSL','WSMLD','WSMLU','WSMPL','WSMSL',
       'WSMTL','WSMXL','WSRML','WSSLL','WSSML','WSSPL','WSSRL','WSSTL','WSSXL','WURLL')
 AND MSOTOS IN ('CI','CO')
 AND MSOSTS <> 'D' 
 AND SV7STS <> 'D' 
 AND (MSOPST >= 20230101 OR MSOPST = 0)
 
 UNION ALL
 
select distinct 'CP1EA' as ENV, MSOSO# AS ORDNO, E.XSOPON PON, F.PONACT ACT, 
       CASE WHEN MSOTOS = 'CI' THEN 'NEW(CI)' WHEN MSOTOS = 'CO' THEN 'DISC(CO)' END ORD_TYPE,
       CASE WHEN SV2STP IN ('WR','DL','LR') THEN 'RES' ELSE 'BUS' END SERV_TYPE,
       CASE WHEN MSOPST > 0 THEN 'COMPLETE' ELSE 'PENDING' END STATUS,
       MSOPH# AS WTN, MSOMB# AS BTN, SV7ITM AS SE_CODE, E.XSODEC CCNA, MSOLSN||MSOFRN AS CUSTNM,  
       CAST(SUBSTR(MSOSDT,5,2)||'/'||SUBSTR(MSOSDT,7,2)||'/'||SUBSTR(MSOSDT,1,4) AS DATE) SO_CREATE_DT,
       CASE WHEN MSOEDT > 0 THEN CAST(SUBSTR(MSOEDT,5,2)||'/'||SUBSTR(MSOEDT,7,2)||'/'||SUBSTR(MSOEDT,1,4) AS DATE) ELSE NULL END SO_EFF_COMP_DT, 
       CASE WHEN MSOCPD > 0 THEN CAST(SUBSTR(MSOCPD,5,2)||'/'||SUBSTR(MSOCPD,7,2)||'/'||SUBSTR(MSOCPD,1,4) AS DATE) ELSE NULL END SO_ACT_COMP_DT,
       CASE WHEN MSOPST > 0 THEN CAST(SUBSTR(MSOPST,5,2)||'/'||SUBSTR(MSOPST,7,2)||'/'||SUBSTR(MSOPST,1,4) AS DATE) ELSE NULL END POST_DT,
       CASE WHEN MSOPST > 0 THEN NULL 
            ELSE DAYS(CURRENT_DATE)-DAYS(CAST(SUBSTR(MSOSDT,5,2)||'/'||SUBSTR(MSOSDT,7,2)||'/'||SUBSTR(MSOSDT,1,4) AS DATE)) END AGING,
       TRIM(MSOST#)||' '||TRIM(MSOSTR)||' '||TRIM(MSOSST) AS ADDRESS, CTYDES AS CITY, MSOSTA AS STATE
FROM CP1EA.SVORD A
INNER JOIN CP1EA.SV07 B
 ON A.MSOSO# = B.SV7SO#
FULL JOIN CP1EA.SV02 C
 ON A.MSOSO# = C.SV2SO#
FULL JOIN CP1EA.DBCTY D
 ON A.MSOCTY = D.CTYCAB
FULL JOIN CP1EA.SVORDX E
 ON A.MSOSO# = E.XSOSO#
LEFT OUTER JOIN CP1##.LSPPON F
 ON E.XSOPON = F.PONPON# AND E.XSODEC = F.PONCCDE 
 WHERE SV7ITM IN (
       'CF15L','CF25L','CF30L','CF50L','CF75L','CFL0L','CFL1L','CFL2L','CFL3L','CFL50','CFL5L','CFL7L','FL634','HLC01','HLC02',
       'HLC04','HLC05','HLC07','HLC08','HLC09','HLMXL','L01WD','L02WD','L03WD','L04WD','L05WD','L06WD','L07WD','L08WD','L09FD',
       'L09WD','L10WD','L11WD','L13FD','L14FD','L14WD','L15FD','L15WD','L16FD','L16WD','L17FD','L17WD','L18FD','L18WD','L19WD',
       'L20WD','L21WD','L22FS','L22WD','L23WD','L24WD','L27WS','L28WS','L29WS','L30WS','L31FS','L31WS','L32FS','L32WS','L33FS',
       'L33WS','L34FS','L34WS','L35FS','L35WS','L36FS','L36WS','L39WS','L40WS','L41WS','L42WS','L43WS','L44WS','L45VD','L45WS',
       'L46WS','L47WS','L48WS','L49VD','L50VD','L51VD','L52VD','L53VD','L54VD','L63VS','L67VS','L68VS','L69VS','L70VS','L71VS',
       'L72VS','PTD1B','PTD1R','PTD3B','PTD3R','PTD3S','PTD7D','PTD7S','WBDLL','WBDML','WBMDL','WBSLL','WBSML','WBSRL','WBSTL',
       'WDPLB','WDPLS','WDTLB','WDTLS','WDWLS','WLSLS','WMLUB','WMLUS','WRBLL','WRBXL','WRUTL','WSBLL','WSBML','WSDLL','WSDML',
       'WSDPL','WSDRL','WSDTL','WSDWL','WSDXL','WSI1G','WSI2G','WSI30','WSI50','WSI70','WSLSL','WSMLD','WSMLU','WSMPL','WSMSL',
       'WSMTL','WSMXL','WSRML','WSSLL','WSSML','WSSPL','WSSRL','WSSTL','WSSXL','WURLL')
 AND MSOTOS IN ('CI','CO')
 AND MSOSTS <> 'D' 
 AND SV7STS <> 'D' 
 AND (MSOPST >= 20230101 OR MSOPST = 0)
 
 UNION ALL
 
select distinct 'CP1LF' as ENV, MSOSO# AS ORDNO, E.XSOPON PON, F.PONACT ACT, 
       CASE WHEN MSOTOS = 'CI' THEN 'NEW(CI)' WHEN MSOTOS = 'CO' THEN 'DISC(CO)' END ORD_TYPE,
       CASE WHEN SV2STP IN ('WR','DL','LR') THEN 'RES' ELSE 'BUS' END SERV_TYPE,
       CASE WHEN MSOPST > 0 THEN 'COMPLETE' ELSE 'PENDING' END STATUS,
       MSOPH# AS WTN, MSOMB# AS BTN, SV7ITM AS SE_CODE, E.XSODEC CCNA, MSOLSN||MSOFRN AS CUSTNM,  
       CAST(SUBSTR(MSOSDT,5,2)||'/'||SUBSTR(MSOSDT,7,2)||'/'||SUBSTR(MSOSDT,1,4) AS DATE) SO_CREATE_DT,
       CASE WHEN MSOEDT > 0 THEN CAST(SUBSTR(MSOEDT,5,2)||'/'||SUBSTR(MSOEDT,7,2)||'/'||SUBSTR(MSOEDT,1,4) AS DATE) ELSE NULL END SO_EFF_COMP_DT, 
       CASE WHEN MSOCPD > 0 THEN CAST(SUBSTR(MSOCPD,5,2)||'/'||SUBSTR(MSOCPD,7,2)||'/'||SUBSTR(MSOCPD,1,4) AS DATE) ELSE NULL END SO_ACT_COMP_DT,
       CASE WHEN MSOPST > 0 THEN CAST(SUBSTR(MSOPST,5,2)||'/'||SUBSTR(MSOPST,7,2)||'/'||SUBSTR(MSOPST,1,4) AS DATE) ELSE NULL END POST_DT,
       CASE WHEN MSOPST > 0 THEN NULL 
            ELSE DAYS(CURRENT_DATE)-DAYS(CAST(SUBSTR(MSOSDT,5,2)||'/'||SUBSTR(MSOSDT,7,2)||'/'||SUBSTR(MSOSDT,1,4) AS DATE)) END AGING,
       TRIM(MSOST#)||' '||TRIM(MSOSTR)||' '||TRIM(MSOSST) AS ADDRESS, CTYDES AS CITY, MSOSTA AS STATE
FROM CP1LF.SVORD A
INNER JOIN CP1LF.SV07 B
 ON A.MSOSO# = B.SV7SO#
FULL JOIN CP1LF.SV02 C
 ON A.MSOSO# = C.SV2SO#
FULL JOIN CP1LF.DBCTY D
 ON A.MSOCTY = D.CTYCAB
FULL JOIN CP1LF.SVORDX E
 ON A.MSOSO# = E.XSOSO#
LEFT OUTER JOIN CP1##.LSPPON F
 ON E.XSOPON = F.PONPON# AND E.XSODEC = F.PONCCDE 
 WHERE SV7ITM IN (
       'CF15L','CF25L','CF30L','CF50L','CF75L','CFL0L','CFL1L','CFL2L','CFL3L','CFL50','CFL5L','CFL7L','FL634','HLC01','HLC02',
       'HLC04','HLC05','HLC07','HLC08','HLC09','HLMXL','L01WD','L02WD','L03WD','L04WD','L05WD','L06WD','L07WD','L08WD','L09FD',
       'L09WD','L10WD','L11WD','L13FD','L14FD','L14WD','L15FD','L15WD','L16FD','L16WD','L17FD','L17WD','L18FD','L18WD','L19WD',
       'L20WD','L21WD','L22FS','L22WD','L23WD','L24WD','L27WS','L28WS','L29WS','L30WS','L31FS','L31WS','L32FS','L32WS','L33FS',
       'L33WS','L34FS','L34WS','L35FS','L35WS','L36FS','L36WS','L39WS','L40WS','L41WS','L42WS','L43WS','L44WS','L45VD','L45WS',
       'L46WS','L47WS','L48WS','L49VD','L50VD','L51VD','L52VD','L53VD','L54VD','L63VS','L67VS','L68VS','L69VS','L70VS','L71VS',
       'L72VS','PTD1B','PTD1R','PTD3B','PTD3R','PTD3S','PTD7D','PTD7S','WBDLL','WBDML','WBMDL','WBSLL','WBSML','WBSRL','WBSTL',
       'WDPLB','WDPLS','WDTLB','WDTLS','WDWLS','WLSLS','WMLUB','WMLUS','WRBLL','WRBXL','WRUTL','WSBLL','WSBML','WSDLL','WSDML',
       'WSDPL','WSDRL','WSDTL','WSDWL','WSDXL','WSI1G','WSI2G','WSI30','WSI50','WSI70','WSLSL','WSMLD','WSMLU','WSMPL','WSMSL',
       'WSMTL','WSMXL','WSRML','WSSLL','WSSML','WSSPL','WSSRL','WSSTL','WSSXL','WURLL')
 AND MSOTOS IN ('CI','CO')
 AND MSOSTS <> 'D' 
 AND SV7STS <> 'D' 
 AND (MSOPST >= 20230101 OR MSOPST = 0)
 
 UNION ALL
 
select distinct 'CP1CW' as ENV, MSOSO# AS ORDNO, E.XSOPON PON, F.PONACT ACT, 
       CASE WHEN MSOTOS = 'CI' THEN 'NEW(CI)' WHEN MSOTOS = 'CO' THEN 'DISC(CO)' END ORD_TYPE,
       CASE WHEN SV2STP IN ('WR','DL','LR') THEN 'RES' ELSE 'BUS' END SERV_TYPE,
       CASE WHEN MSOPST > 0 THEN 'COMPLETE' ELSE 'PENDING' END STATUS,
       MSOPH# AS WTN, MSOMB# AS BTN, SV7ITM AS SE_CODE, E.XSODEC CCNA, MSOLSN||MSOFRN AS CUSTNM,  
       CAST(SUBSTR(MSOSDT,5,2)||'/'||SUBSTR(MSOSDT,7,2)||'/'||SUBSTR(MSOSDT,1,4) AS DATE) SO_CREATE_DT,
       CASE WHEN MSOEDT > 0 THEN CAST(SUBSTR(MSOEDT,5,2)||'/'||SUBSTR(MSOEDT,7,2)||'/'||SUBSTR(MSOEDT,1,4) AS DATE) ELSE NULL END SO_EFF_COMP_DT, 
       CASE WHEN MSOCPD > 0 THEN CAST(SUBSTR(MSOCPD,5,2)||'/'||SUBSTR(MSOCPD,7,2)||'/'||SUBSTR(MSOCPD,1,4) AS DATE) ELSE NULL END SO_ACT_COMP_DT,
       CASE WHEN MSOPST > 0 THEN CAST(SUBSTR(MSOPST,5,2)||'/'||SUBSTR(MSOPST,7,2)||'/'||SUBSTR(MSOPST,1,4) AS DATE) ELSE NULL END POST_DT,
       CASE WHEN MSOPST > 0 THEN NULL 
            ELSE DAYS(CURRENT_DATE)-DAYS(CAST(SUBSTR(MSOSDT,5,2)||'/'||SUBSTR(MSOSDT,7,2)||'/'||SUBSTR(MSOSDT,1,4) AS DATE)) END AGING,
       TRIM(MSOST#)||' '||TRIM(MSOSTR)||' '||TRIM(MSOSST) AS ADDRESS, CTYDES AS CITY, MSOSTA AS STATE
FROM CP1CW.SVORD A
INNER JOIN CP1CW.SV07 B
 ON A.MSOSO# = B.SV7SO#
FULL JOIN CP1CW.SV02 C
 ON A.MSOSO# = C.SV2SO#
FULL JOIN CP1CW.DBCTY D
 ON A.MSOCTY = D.CTYCAB
FULL JOIN CP1CW.SVORDX E
 ON A.MSOSO# = E.XSOSO#
LEFT OUTER JOIN CP1##.LSPPON F
 ON E.XSOPON = F.PONPON# AND E.XSODEC = F.PONCCDE 
 WHERE SV7ITM IN (
       'CF15L','CF25L','CF30L','CF50L','CF75L','CFL0L','CFL1L','CFL2L','CFL3L','CFL50','CFL5L','CFL7L','FL634','HLC01','HLC02',
       'HLC04','HLC05','HLC07','HLC08','HLC09','HLMXL','L01WD','L02WD','L03WD','L04WD','L05WD','L06WD','L07WD','L08WD','L09FD',
       'L09WD','L10WD','L11WD','L13FD','L14FD','L14WD','L15FD','L15WD','L16FD','L16WD','L17FD','L17WD','L18FD','L18WD','L19WD',
       'L20WD','L21WD','L22FS','L22WD','L23WD','L24WD','L27WS','L28WS','L29WS','L30WS','L31FS','L31WS','L32FS','L32WS','L33FS',
       'L33WS','L34FS','L34WS','L35FS','L35WS','L36FS','L36WS','L39WS','L40WS','L41WS','L42WS','L43WS','L44WS','L45VD','L45WS',
       'L46WS','L47WS','L48WS','L49VD','L50VD','L51VD','L52VD','L53VD','L54VD','L63VS','L67VS','L68VS','L69VS','L70VS','L71VS',
       'L72VS','PTD1B','PTD1R','PTD3B','PTD3R','PTD3S','PTD7D','PTD7S','WBDLL','WBDML','WBMDL','WBSLL','WBSML','WBSRL','WBSTL',
       'WDPLB','WDPLS','WDTLB','WDTLS','WDWLS','WLSLS','WMLUB','WMLUS','WRBLL','WRBXL','WRUTL','WSBLL','WSBML','WSDLL','WSDML',
       'WSDPL','WSDRL','WSDTL','WSDWL','WSDXL','WSI1G','WSI2G','WSI30','WSI50','WSI70','WSLSL','WSMLD','WSMLU','WSMPL','WSMSL',
       'WSMTL','WSMXL','WSRML','WSSLL','WSSML','WSSPL','WSSRL','WSSTL','WSSXL','WURLL')
 AND MSOTOS IN ('CI','CO')
 AND MSOSTS <> 'D' 
 AND SV7STS <> 'D' 
 AND (MSOPST >= 20230101 OR MSOPST = 0)
 
 UNION ALL
 
select distinct 'CP1CA' as ENV, MSOSO# AS ORDNO, E.XSOPON PON, F.PONACT ACT, 
       CASE WHEN MSOTOS = 'CI' THEN 'NEW(CI)' WHEN MSOTOS = 'CO' THEN 'DISC(CO)' END ORD_TYPE,
       CASE WHEN SV2STP IN ('WR','DL','LR') THEN 'RES' ELSE 'BUS' END SERV_TYPE,
       CASE WHEN MSOPST > 0 THEN 'COMPLETE' ELSE 'PENDING' END STATUS,
       MSOPH# AS WTN, MSOMB# AS BTN, SV7ITM AS SE_CODE, E.XSODEC CCNA, MSOLSN||MSOFRN AS CUSTNM,  
       CAST(SUBSTR(MSOSDT,5,2)||'/'||SUBSTR(MSOSDT,7,2)||'/'||SUBSTR(MSOSDT,1,4) AS DATE) SO_CREATE_DT,
       CASE WHEN MSOEDT > 0 THEN CAST(SUBSTR(MSOEDT,5,2)||'/'||SUBSTR(MSOEDT,7,2)||'/'||SUBSTR(MSOEDT,1,4) AS DATE) ELSE NULL END SO_EFF_COMP_DT, 
       CASE WHEN MSOCPD > 0 THEN CAST(SUBSTR(MSOCPD,5,2)||'/'||SUBSTR(MSOCPD,7,2)||'/'||SUBSTR(MSOCPD,1,4) AS DATE) ELSE NULL END SO_ACT_COMP_DT,
       CASE WHEN MSOPST > 0 THEN CAST(SUBSTR(MSOPST,5,2)||'/'||SUBSTR(MSOPST,7,2)||'/'||SUBSTR(MSOPST,1,4) AS DATE) ELSE NULL END POST_DT,
       CASE WHEN MSOPST > 0 THEN NULL 
            ELSE DAYS(CURRENT_DATE)-DAYS(CAST(SUBSTR(MSOSDT,5,2)||'/'||SUBSTR(MSOSDT,7,2)||'/'||SUBSTR(MSOSDT,1,4) AS DATE)) END AGING,
       TRIM(MSOST#)||' '||TRIM(MSOSTR)||' '||TRIM(MSOSST) AS ADDRESS, CTYDES AS CITY, MSOSTA AS STATE
FROM CP1CA.SVORD A
INNER JOIN CP1CA.SV07 B
 ON A.MSOSO# = B.SV7SO#
FULL JOIN CP1CA.SV02 C
 ON A.MSOSO# = C.SV2SO#
FULL JOIN CP1CA.DBCTY D
 ON A.MSOCTY = D.CTYCAB
FULL JOIN CP1CA.SVORDX E
 ON A.MSOSO# = E.XSOSO#
LEFT OUTER JOIN CP1##.LSPPON F
 ON E.XSOPON = F.PONPON# AND E.XSODEC = F.PONCCDE
 WHERE SV7ITM IN (
       'CF15L','CF25L','CF30L','CF50L','CF75L','CFL0L','CFL1L','CFL2L','CFL3L','CFL50','CFL5L','CFL7L','FL634','HLC01','HLC02',
       'HLC04','HLC05','HLC07','HLC08','HLC09','HLMXL','L01WD','L02WD','L03WD','L04WD','L05WD','L06WD','L07WD','L08WD','L09FD',
       'L09WD','L10WD','L11WD','L13FD','L14FD','L14WD','L15FD','L15WD','L16FD','L16WD','L17FD','L17WD','L18FD','L18WD','L19WD',
       'L20WD','L21WD','L22FS','L22WD','L23WD','L24WD','L27WS','L28WS','L29WS','L30WS','L31FS','L31WS','L32FS','L32WS','L33FS',
       'L33WS','L34FS','L34WS','L35FS','L35WS','L36FS','L36WS','L39WS','L40WS','L41WS','L42WS','L43WS','L44WS','L45VD','L45WS',
       'L46WS','L47WS','L48WS','L49VD','L50VD','L51VD','L52VD','L53VD','L54VD','L63VS','L67VS','L68VS','L69VS','L70VS','L71VS',
       'L72VS','PTD1B','PTD1R','PTD3B','PTD3R','PTD3S','PTD7D','PTD7S','WBDLL','WBDML','WBMDL','WBSLL','WBSML','WBSRL','WBSTL',
       'WDPLB','WDPLS','WDTLB','WDTLS','WDWLS','WLSLS','WMLUB','WMLUS','WRBLL','WRBXL','WRUTL','WSBLL','WSBML','WSDLL','WSDML',
       'WSDPL','WSDRL','WSDTL','WSDWL','WSDXL','WSI1G','WSI2G','WSI30','WSI50','WSI70','WSLSL','WSMLD','WSMLU','WSMPL','WSMSL',
       'WSMTL','WSMXL','WSRML','WSSLL','WSSML','WSSPL','WSSRL','WSSTL','WSSXL','WURLL')
 AND MSOTOS IN ('CI','CO')
 AND MSOSTS <> 'D' 
 AND SV7STS <> 'D' 
 AND (MSOPST >= 20230101 OR MSOPST = 0)
 
 UNION ALL
 
select distinct 'CP1CT' as ENV, MSOSO# AS ORDNO, E.XSOPON PON, F.PONACT ACT, 
       CASE WHEN MSOTOS = 'CI' THEN 'NEW(CI)' WHEN MSOTOS = 'CO' THEN 'DISC(CO)' END ORD_TYPE,
       CASE WHEN SV2STP IN ('WR','DL','LR') THEN 'RES' ELSE 'BUS' END SERV_TYPE,
       CASE WHEN MSOPST > 0 THEN 'COMPLETE' ELSE 'PENDING' END STATUS,
       MSOPH# AS WTN, MSOMB# AS BTN, SV7ITM AS SE_CODE, E.XSODEC CCNA, MSOLSN||MSOFRN AS CUSTNM,  
       CAST(SUBSTR(MSOSDT,5,2)||'/'||SUBSTR(MSOSDT,7,2)||'/'||SUBSTR(MSOSDT,1,4) AS DATE) SO_CREATE_DT,
       CASE WHEN MSOEDT > 0 THEN CAST(SUBSTR(MSOEDT,5,2)||'/'||SUBSTR(MSOEDT,7,2)||'/'||SUBSTR(MSOEDT,1,4) AS DATE) ELSE NULL END SO_EFF_COMP_DT, 
       CASE WHEN MSOCPD > 0 THEN CAST(SUBSTR(MSOCPD,5,2)||'/'||SUBSTR(MSOCPD,7,2)||'/'||SUBSTR(MSOCPD,1,4) AS DATE) ELSE NULL END SO_ACT_COMP_DT,
       CASE WHEN MSOPST > 0 THEN CAST(SUBSTR(MSOPST,5,2)||'/'||SUBSTR(MSOPST,7,2)||'/'||SUBSTR(MSOPST,1,4) AS DATE) ELSE NULL END POST_DT,
       CASE WHEN MSOPST > 0 THEN NULL 
            ELSE DAYS(CURRENT_DATE)-DAYS(CAST(SUBSTR(MSOSDT,5,2)||'/'||SUBSTR(MSOSDT,7,2)||'/'||SUBSTR(MSOSDT,1,4) AS DATE)) END AGING,
       TRIM(MSOST#)||' '||TRIM(MSOSTR)||' '||TRIM(MSOSST) AS ADDRESS, CTYDES AS CITY, MSOSTA AS STATE
FROM CP1CT.SVORD A
INNER JOIN CP1CT.SV07 B
 ON A.MSOSO# = B.SV7SO#
FULL JOIN CP1CT.SV02 C
 ON A.MSOSO# = C.SV2SO#
FULL JOIN CP1CT.DBCTY D
 ON A.MSOCTY = D.CTYCAB
FULL JOIN CP1CT.SVORDX E
 ON A.MSOSO# = E.XSOSO#
LEFT OUTER JOIN CP1##.LSPPON F
 ON E.XSOPON = F.PONPON# AND E.XSODEC = F.PONCCDE 
 WHERE SV7ITM IN (
       'CF15L','CF25L','CF30L','CF50L','CF75L','CFL0L','CFL1L','CFL2L','CFL3L','CFL50','CFL5L','CFL7L','FL634','HLC01','HLC02',
       'HLC04','HLC05','HLC07','HLC08','HLC09','HLMXL','L01WD','L02WD','L03WD','L04WD','L05WD','L06WD','L07WD','L08WD','L09FD',
       'L09WD','L10WD','L11WD','L13FD','L14FD','L14WD','L15FD','L15WD','L16FD','L16WD','L17FD','L17WD','L18FD','L18WD','L19WD',
       'L20WD','L21WD','L22FS','L22WD','L23WD','L24WD','L27WS','L28WS','L29WS','L30WS','L31FS','L31WS','L32FS','L32WS','L33FS',
       'L33WS','L34FS','L34WS','L35FS','L35WS','L36FS','L36WS','L39WS','L40WS','L41WS','L42WS','L43WS','L44WS','L45VD','L45WS',
       'L46WS','L47WS','L48WS','L49VD','L50VD','L51VD','L52VD','L53VD','L54VD','L63VS','L67VS','L68VS','L69VS','L70VS','L71VS',
       'L72VS','PTD1B','PTD1R','PTD3B','PTD3R','PTD3S','PTD7D','PTD7S','WBDLL','WBDML','WBMDL','WBSLL','WBSML','WBSRL','WBSTL',
       'WDPLB','WDPLS','WDTLB','WDTLS','WDWLS','WLSLS','WMLUB','WMLUS','WRBLL','WRBXL','WRUTL','WSBLL','WSBML','WSDLL','WSDML',
       'WSDPL','WSDRL','WSDTL','WSDWL','WSDXL','WSI1G','WSI2G','WSI30','WSI50','WSI70','WSLSL','WSMLD','WSMLU','WSMPL','WSMSL',
       'WSMTL','WSMXL','WSRML','WSSLL','WSSML','WSSPL','WSSRL','WSSTL','WSSXL','WURLL')
 AND MSOTOS IN ('CI','CO')
 AND MSOSTS <> 'D' 
 AND SV7STS <> 'D' 
 AND (MSOPST >= 20230101 OR MSOPST = 0)
 
 UNION ALL
 
select distinct 'CP1AZ' as ENV, MSOSO# AS ORDNO, E.XSOPON PON, F.PONACT ACT, 
       CASE WHEN MSOTOS = 'CI' THEN 'NEW(CI)' WHEN MSOTOS = 'CO' THEN 'DISC(CO)' END ORD_TYPE,
       CASE WHEN SV2STP IN ('WR','DL','LR') THEN 'RES' ELSE 'BUS' END SERV_TYPE,
       CASE WHEN MSOPST > 0 THEN 'COMPLETE' ELSE 'PENDING' END STATUS,
       MSOPH# AS WTN, MSOMB# AS BTN, SV7ITM AS SE_CODE, E.XSODEC CCNA, MSOLSN||MSOFRN AS CUSTNM,  
       CAST(SUBSTR(MSOSDT,5,2)||'/'||SUBSTR(MSOSDT,7,2)||'/'||SUBSTR(MSOSDT,1,4) AS DATE) SO_CREATE_DT,
       CASE WHEN MSOEDT > 0 THEN CAST(SUBSTR(MSOEDT,5,2)||'/'||SUBSTR(MSOEDT,7,2)||'/'||SUBSTR(MSOEDT,1,4) AS DATE) ELSE NULL END SO_EFF_COMP_DT, 
       CASE WHEN MSOCPD > 0 THEN CAST(SUBSTR(MSOCPD,5,2)||'/'||SUBSTR(MSOCPD,7,2)||'/'||SUBSTR(MSOCPD,1,4) AS DATE) ELSE NULL END SO_ACT_COMP_DT,
       CASE WHEN MSOPST > 0 THEN CAST(SUBSTR(MSOPST,5,2)||'/'||SUBSTR(MSOPST,7,2)||'/'||SUBSTR(MSOPST,1,4) AS DATE) ELSE NULL END POST_DT,
       CASE WHEN MSOPST > 0 THEN NULL 
            ELSE DAYS(CURRENT_DATE)-DAYS(CAST(SUBSTR(MSOSDT,5,2)||'/'||SUBSTR(MSOSDT,7,2)||'/'||SUBSTR(MSOSDT,1,4) AS DATE)) END AGING,
       TRIM(MSOST#)||' '||TRIM(MSOSTR)||' '||TRIM(MSOSST) AS ADDRESS, CTYDES AS CITY, MSOSTA AS STATE
FROM CP1AZ.SVORD A
INNER JOIN CP1AZ.SV07 B
 ON A.MSOSO# = B.SV7SO#
FULL JOIN CP1AZ.SV02 C
 ON A.MSOSO# = C.SV2SO#
FULL JOIN CP1AZ.DBCTY D
 ON A.MSOCTY = D.CTYCAB
FULL JOIN CP1AZ.SVORDX E
 ON A.MSOSO# = E.XSOSO#
LEFT OUTER JOIN CP1##.LSPPON F
 ON E.XSOPON = F.PONPON# AND E.XSODEC = F.PONCCDE 
 WHERE SV7ITM IN (
       'CF15L','CF25L','CF30L','CF50L','CF75L','CFL0L','CFL1L','CFL2L','CFL3L','CFL50','CFL5L','CFL7L','FL634','HLC01','HLC02',
       'HLC04','HLC05','HLC07','HLC08','HLC09','HLMXL','L01WD','L02WD','L03WD','L04WD','L05WD','L06WD','L07WD','L08WD','L09FD',
       'L09WD','L10WD','L11WD','L13FD','L14FD','L14WD','L15FD','L15WD','L16FD','L16WD','L17FD','L17WD','L18FD','L18WD','L19WD',
       'L20WD','L21WD','L22FS','L22WD','L23WD','L24WD','L27WS','L28WS','L29WS','L30WS','L31FS','L31WS','L32FS','L32WS','L33FS',
       'L33WS','L34FS','L34WS','L35FS','L35WS','L36FS','L36WS','L39WS','L40WS','L41WS','L42WS','L43WS','L44WS','L45VD','L45WS',
       'L46WS','L47WS','L48WS','L49VD','L50VD','L51VD','L52VD','L53VD','L54VD','L63VS','L67VS','L68VS','L69VS','L70VS','L71VS',
       'L72VS','PTD1B','PTD1R','PTD3B','PTD3R','PTD3S','PTD7D','PTD7S','WBDLL','WBDML','WBMDL','WBSLL','WBSML','WBSRL','WBSTL',
       'WDPLB','WDPLS','WDTLB','WDTLS','WDWLS','WLSLS','WMLUB','WMLUS','WRBLL','WRBXL','WRUTL','WSBLL','WSBML','WSDLL','WSDML',
       'WSDPL','WSDRL','WSDTL','WSDWL','WSDXL','WSI1G','WSI2G','WSI30','WSI50','WSI70','WSLSL','WSMLD','WSMLU','WSMPL','WSMSL',
       'WSMTL','WSMXL','WSRML','WSSLL','WSSML','WSSPL','WSSRL','WSSTL','WSSXL','WURLL')
 AND MSOTOS IN ('CI','CO')
 AND MSOSTS <> 'D' 
 AND SV7STS <> 'D' 
 AND (MSOPST >= 20230101 OR MSOPST = 0)
 
 UNION ALL
 
select distinct 'CP1LR' as ENV, MSOSO# AS ORDNO, E.XSOPON PON, F.PONACT ACT, 
       CASE WHEN MSOTOS = 'CI' THEN 'NEW(CI)' WHEN MSOTOS = 'CO' THEN 'DISC(CO)' END ORD_TYPE,
       CASE WHEN SV2STP IN ('WR','DL','LR') THEN 'RES' ELSE 'BUS' END SERV_TYPE,
       CASE WHEN MSOPST > 0 THEN 'COMPLETE' ELSE 'PENDING' END STATUS,
       MSOPH# AS WTN, MSOMB# AS BTN, SV7ITM AS SE_CODE, E.XSODEC CCNA, MSOLSN||MSOFRN AS CUSTNM,  
       CAST(SUBSTR(MSOSDT,5,2)||'/'||SUBSTR(MSOSDT,7,2)||'/'||SUBSTR(MSOSDT,1,4) AS DATE) SO_CREATE_DT,
       CASE WHEN MSOEDT > 0 THEN CAST(SUBSTR(MSOEDT,5,2)||'/'||SUBSTR(MSOEDT,7,2)||'/'||SUBSTR(MSOEDT,1,4) AS DATE) ELSE NULL END SO_EFF_COMP_DT, 
       CASE WHEN MSOCPD > 0 THEN CAST(SUBSTR(MSOCPD,5,2)||'/'||SUBSTR(MSOCPD,7,2)||'/'||SUBSTR(MSOCPD,1,4) AS DATE) ELSE NULL END SO_ACT_COMP_DT,
       CASE WHEN MSOPST > 0 THEN CAST(SUBSTR(MSOPST,5,2)||'/'||SUBSTR(MSOPST,7,2)||'/'||SUBSTR(MSOPST,1,4) AS DATE) ELSE NULL END POST_DT,
       CASE WHEN MSOPST > 0 THEN NULL 
            ELSE DAYS(CURRENT_DATE)-DAYS(CAST(SUBSTR(MSOSDT,5,2)||'/'||SUBSTR(MSOSDT,7,2)||'/'||SUBSTR(MSOSDT,1,4) AS DATE)) END AGING,
       TRIM(MSOST#)||' '||TRIM(MSOSTR)||' '||TRIM(MSOSST) AS ADDRESS, CTYDES AS CITY, MSOSTA AS STATE
FROM CP1LR.SVORD A
INNER JOIN CP1LR.SV07 B
 ON A.MSOSO# = B.SV7SO#
FULL JOIN CP1LR.SV02 C
 ON A.MSOSO# = C.SV2SO#
FULL JOIN CP1LR.DBCTY D
 ON A.MSOCTY = D.CTYCAB
FULL JOIN CP1LR.SVORDX E
 ON A.MSOSO# = E.XSOSO#
LEFT OUTER JOIN CP1##.LSPPON F
 ON E.XSOPON = F.PONPON# AND E.XSODEC = F.PONCCDE 
 WHERE SV7ITM IN (
       'CF15L','CF25L','CF30L','CF50L','CF75L','CFL0L','CFL1L','CFL2L','CFL3L','CFL50','CFL5L','CFL7L','FL634','HLC01','HLC02',
       'HLC04','HLC05','HLC07','HLC08','HLC09','HLMXL','L01WD','L02WD','L03WD','L04WD','L05WD','L06WD','L07WD','L08WD','L09FD',
       'L09WD','L10WD','L11WD','L13FD','L14FD','L14WD','L15FD','L15WD','L16FD','L16WD','L17FD','L17WD','L18FD','L18WD','L19WD',
       'L20WD','L21WD','L22FS','L22WD','L23WD','L24WD','L27WS','L28WS','L29WS','L30WS','L31FS','L31WS','L32FS','L32WS','L33FS',
       'L33WS','L34FS','L34WS','L35FS','L35WS','L36FS','L36WS','L39WS','L40WS','L41WS','L42WS','L43WS','L44WS','L45VD','L45WS',
       'L46WS','L47WS','L48WS','L49VD','L50VD','L51VD','L52VD','L53VD','L54VD','L63VS','L67VS','L68VS','L69VS','L70VS','L71VS',
       'L72VS','PTD1B','PTD1R','PTD3B','PTD3R','PTD3S','PTD7D','PTD7S','WBDLL','WBDML','WBMDL','WBSLL','WBSML','WBSRL','WBSTL',
       'WDPLB','WDPLS','WDTLB','WDTLS','WDWLS','WLSLS','WMLUB','WMLUS','WRBLL','WRBXL','WRUTL','WSBLL','WSBML','WSDLL','WSDML',
       'WSDPL','WSDRL','WSDTL','WSDWL','WSDXL','WSI1G','WSI2G','WSI30','WSI50','WSI70','WSLSL','WSMLD','WSMLU','WSMPL','WSMSL',
       'WSMTL','WSMXL','WSRML','WSSLL','WSSML','WSSPL','WSSRL','WSSTL','WSSXL','WURLL')
 AND MSOTOS IN ('CI','CO')
 AND MSOSTS <> 'D' 
 AND SV7STS <> 'D' 
 AND (MSOPST >= 20230101 OR MSOPST = 0)
 
 UNION ALL
 
select distinct 'CP1NW' as ENV, MSOSO# AS ORDNO, E.XSOPON PON, F.PONACT ACT, 
       CASE WHEN MSOTOS = 'CI' THEN 'NEW(CI)' WHEN MSOTOS = 'CO' THEN 'DISC(CO)' END ORD_TYPE,
       CASE WHEN SV2STP IN ('WR','DL','LR') THEN 'RES' ELSE 'BUS' END SERV_TYPE,
       CASE WHEN MSOPST > 0 THEN 'COMPLETE' ELSE 'PENDING' END STATUS,
       MSOPH# AS WTN, MSOMB# AS BTN, SV7ITM AS SE_CODE, E.XSODEC CCNA, MSOLSN||MSOFRN AS CUSTNM,  
       CAST(SUBSTR(MSOSDT,5,2)||'/'||SUBSTR(MSOSDT,7,2)||'/'||SUBSTR(MSOSDT,1,4) AS DATE) SO_CREATE_DT,
       CASE WHEN MSOEDT > 0 THEN CAST(SUBSTR(MSOEDT,5,2)||'/'||SUBSTR(MSOEDT,7,2)||'/'||SUBSTR(MSOEDT,1,4) AS DATE) ELSE NULL END SO_EFF_COMP_DT, 
       CASE WHEN MSOCPD > 0 THEN CAST(SUBSTR(MSOCPD,5,2)||'/'||SUBSTR(MSOCPD,7,2)||'/'||SUBSTR(MSOCPD,1,4) AS DATE) ELSE NULL END SO_ACT_COMP_DT,
       CASE WHEN MSOPST > 0 THEN CAST(SUBSTR(MSOPST,5,2)||'/'||SUBSTR(MSOPST,7,2)||'/'||SUBSTR(MSOPST,1,4) AS DATE) ELSE NULL END POST_DT,
       CASE WHEN MSOPST > 0 THEN NULL 
            ELSE DAYS(CURRENT_DATE)-DAYS(CAST(SUBSTR(MSOSDT,5,2)||'/'||SUBSTR(MSOSDT,7,2)||'/'||SUBSTR(MSOSDT,1,4) AS DATE)) END AGING,
       TRIM(MSOST#)||' '||TRIM(MSOSTR)||' '||TRIM(MSOSST) AS ADDRESS, CTYDES AS CITY, MSOSTA AS STATE
FROM CP1NW.SVORD A
INNER JOIN CP1NW.SV07 B
 ON A.MSOSO# = B.SV7SO#
FULL JOIN CP1NW.SV02 C
 ON A.MSOSO# = C.SV2SO#
FULL JOIN CP1NW.DBCTY D
 ON A.MSOCTY = D.CTYCAB
FULL JOIN CP1NW.SVORDX E
 ON A.MSOSO# = E.XSOSO#
LEFT OUTER JOIN CP1##.LSPPON F
 ON E.XSOPON = F.PONPON# AND E.XSODEC = F.PONCCDE 
 WHERE SV7ITM IN (
       'CF15L','CF25L','CF30L','CF50L','CF75L','CFL0L','CFL1L','CFL2L','CFL3L','CFL50','CFL5L','CFL7L','FL634','HLC01','HLC02',
       'HLC04','HLC05','HLC07','HLC08','HLC09','HLMXL','L01WD','L02WD','L03WD','L04WD','L05WD','L06WD','L07WD','L08WD','L09FD',
       'L09WD','L10WD','L11WD','L13FD','L14FD','L14WD','L15FD','L15WD','L16FD','L16WD','L17FD','L17WD','L18FD','L18WD','L19WD',
       'L20WD','L21WD','L22FS','L22WD','L23WD','L24WD','L27WS','L28WS','L29WS','L30WS','L31FS','L31WS','L32FS','L32WS','L33FS',
       'L33WS','L34FS','L34WS','L35FS','L35WS','L36FS','L36WS','L39WS','L40WS','L41WS','L42WS','L43WS','L44WS','L45VD','L45WS',
       'L46WS','L47WS','L48WS','L49VD','L50VD','L51VD','L52VD','L53VD','L54VD','L63VS','L67VS','L68VS','L69VS','L70VS','L71VS',
       'L72VS','PTD1B','PTD1R','PTD3B','PTD3R','PTD3S','PTD7D','PTD7S','WBDLL','WBDML','WBMDL','WBSLL','WBSML','WBSRL','WBSTL',
       'WDPLB','WDPLS','WDTLB','WDTLS','WDWLS','WLSLS','WMLUB','WMLUS','WRBLL','WRBXL','WRUTL','WSBLL','WSBML','WSDLL','WSDML',
       'WSDPL','WSDRL','WSDTL','WSDWL','WSDXL','WSI1G','WSI2G','WSI30','WSI50','WSI70','WSLSL','WSMLD','WSMLU','WSMPL','WSMSL',
       'WSMTL','WSMXL','WSRML','WSSLL','WSSML','WSSPL','WSSRL','WSSTL','WSSXL','WURLL')
 AND MSOTOS IN ('CI','CO')
 AND MSOSTS <> 'D' 
 AND SV7STS <> 'D' 
 AND (MSOPST >= 20230101 OR MSOPST = 0)
 
 UNION ALL
 
select distinct 'CP1PA' as ENV, MSOSO# AS ORDNO, E.XSOPON PON, F.PONACT ACT, 
       CASE WHEN MSOTOS = 'CI' THEN 'NEW(CI)' WHEN MSOTOS = 'CO' THEN 'DISC(CO)' END ORD_TYPE,
       CASE WHEN SV2STP IN ('WR','DL','LR') THEN 'RES' ELSE 'BUS' END SERV_TYPE,
       CASE WHEN MSOPST > 0 THEN 'COMPLETE' ELSE 'PENDING' END STATUS,
       MSOPH# AS WTN, MSOMB# AS BTN, SV7ITM AS SE_CODE, E.XSODEC CCNA, MSOLSN||MSOFRN AS CUSTNM,  
       CAST(SUBSTR(MSOSDT,5,2)||'/'||SUBSTR(MSOSDT,7,2)||'/'||SUBSTR(MSOSDT,1,4) AS DATE) SO_CREATE_DT,
       CASE WHEN MSOEDT > 0 THEN CAST(SUBSTR(MSOEDT,5,2)||'/'||SUBSTR(MSOEDT,7,2)||'/'||SUBSTR(MSOEDT,1,4) AS DATE) ELSE NULL END SO_EFF_COMP_DT, 
       CASE WHEN MSOCPD > 0 THEN CAST(SUBSTR(MSOCPD,5,2)||'/'||SUBSTR(MSOCPD,7,2)||'/'||SUBSTR(MSOCPD,1,4) AS DATE) ELSE NULL END SO_ACT_COMP_DT,
       CASE WHEN MSOPST > 0 THEN CAST(SUBSTR(MSOPST,5,2)||'/'||SUBSTR(MSOPST,7,2)||'/'||SUBSTR(MSOPST,1,4) AS DATE) ELSE NULL END POST_DT,
       CASE WHEN MSOPST > 0 THEN NULL 
            ELSE DAYS(CURRENT_DATE)-DAYS(CAST(SUBSTR(MSOSDT,5,2)||'/'||SUBSTR(MSOSDT,7,2)||'/'||SUBSTR(MSOSDT,1,4) AS DATE)) END AGING,
       TRIM(MSOST#)||' '||TRIM(MSOSTR)||' '||TRIM(MSOSST) AS ADDRESS, CTYDES AS CITY, MSOSTA AS STATE
FROM CP1PA.SVORD A
INNER JOIN CP1PA.SV07 B
 ON A.MSOSO# = B.SV7SO#
FULL JOIN CP1PA.SV02 C
 ON A.MSOSO# = C.SV2SO#
FULL JOIN CP1PA.DBCTY D
 ON A.MSOCTY = D.CTYCAB
FULL JOIN CP1PA.SVORDX E
 ON A.MSOSO# = E.XSOSO#
LEFT OUTER JOIN CP1##.LSPPON F
 ON E.XSOPON = F.PONPON# AND E.XSODEC = F.PONCCDE 
 WHERE SV7ITM IN (
       'CF15L','CF25L','CF30L','CF50L','CF75L','CFL0L','CFL1L','CFL2L','CFL3L','CFL50','CFL5L','CFL7L','FL634','HLC01','HLC02',
       'HLC04','HLC05','HLC07','HLC08','HLC09','HLMXL','L01WD','L02WD','L03WD','L04WD','L05WD','L06WD','L07WD','L08WD','L09FD',
       'L09WD','L10WD','L11WD','L13FD','L14FD','L14WD','L15FD','L15WD','L16FD','L16WD','L17FD','L17WD','L18FD','L18WD','L19WD',
       'L20WD','L21WD','L22FS','L22WD','L23WD','L24WD','L27WS','L28WS','L29WS','L30WS','L31FS','L31WS','L32FS','L32WS','L33FS',
       'L33WS','L34FS','L34WS','L35FS','L35WS','L36FS','L36WS','L39WS','L40WS','L41WS','L42WS','L43WS','L44WS','L45VD','L45WS',
       'L46WS','L47WS','L48WS','L49VD','L50VD','L51VD','L52VD','L53VD','L54VD','L63VS','L67VS','L68VS','L69VS','L70VS','L71VS',
       'L72VS','PTD1B','PTD1R','PTD3B','PTD3R','PTD3S','PTD7D','PTD7S','WBDLL','WBDML','WBMDL','WBSLL','WBSML','WBSRL','WBSTL',
       'WDPLB','WDPLS','WDTLB','WDTLS','WDWLS','WLSLS','WMLUB','WMLUS','WRBLL','WRBXL','WRUTL','WSBLL','WSBML','WSDLL','WSDML',
       'WSDPL','WSDRL','WSDTL','WSDWL','WSDXL','WSI1G','WSI2G','WSI30','WSI50','WSI70','WSLSL','WSMLD','WSMLU','WSMPL','WSMSL',
       'WSMTL','WSMXL','WSRML','WSSLL','WSSML','WSSPL','WSSRL','WSSTL','WSSXL','WURLL')
 AND MSOTOS IN ('CI','CO')
 AND MSOSTS <> 'D' 
 AND SV7STS <> 'D' 
 AND (MSOPST >= 20230101 OR MSOPST = 0)
 
 UNION ALL
 
select distinct 'CP1US' as ENV, MSOSO# AS ORDNO, E.XSOPON PON, F.PONACT ACT, 
       CASE WHEN MSOTOS = 'CI' THEN 'NEW(CI)' WHEN MSOTOS = 'CO' THEN 'DISC(CO)' END ORD_TYPE,
       CASE WHEN SV2STP IN ('WR','DL','LR') THEN 'RES' ELSE 'BUS' END SERV_TYPE,
       CASE WHEN MSOPST > 0 THEN 'COMPLETE' ELSE 'PENDING' END STATUS,
       MSOPH# AS WTN, MSOMB# AS BTN, SV7ITM AS SE_CODE, E.XSODEC CCNA, MSOLSN||MSOFRN AS CUSTNM,  
       CAST(SUBSTR(MSOSDT,5,2)||'/'||SUBSTR(MSOSDT,7,2)||'/'||SUBSTR(MSOSDT,1,4) AS DATE) SO_CREATE_DT,
       CASE WHEN MSOEDT > 0 THEN CAST(SUBSTR(MSOEDT,5,2)||'/'||SUBSTR(MSOEDT,7,2)||'/'||SUBSTR(MSOEDT,1,4) AS DATE) ELSE NULL END SO_EFF_COMP_DT, 
       CASE WHEN MSOCPD > 0 THEN CAST(SUBSTR(MSOCPD,5,2)||'/'||SUBSTR(MSOCPD,7,2)||'/'||SUBSTR(MSOCPD,1,4) AS DATE) ELSE NULL END SO_ACT_COMP_DT,
       CASE WHEN MSOPST > 0 THEN CAST(SUBSTR(MSOPST,5,2)||'/'||SUBSTR(MSOPST,7,2)||'/'||SUBSTR(MSOPST,1,4) AS DATE) ELSE NULL END POST_DT,
       CASE WHEN MSOPST > 0 THEN NULL 
            ELSE DAYS(CURRENT_DATE)-DAYS(CAST(SUBSTR(MSOSDT,5,2)||'/'||SUBSTR(MSOSDT,7,2)||'/'||SUBSTR(MSOSDT,1,4) AS DATE)) END AGING,
       TRIM(MSOST#)||' '||TRIM(MSOSTR)||' '||TRIM(MSOSST) AS ADDRESS, CTYDES AS CITY, MSOSTA AS STATE
FROM CP1US.SVORD A
INNER JOIN CP1US.SV07 B
 ON A.MSOSO# = B.SV7SO#
FULL JOIN CP1US.SV02 C
 ON A.MSOSO# = C.SV2SO#
FULL JOIN CP1US.DBCTY D
 ON A.MSOCTY = D.CTYCAB
FULL JOIN CP1US.SVORDX E
 ON A.MSOSO# = E.XSOSO#
LEFT OUTER JOIN CP1##.LSPPON F
 ON E.XSOPON = F.PONPON# AND E.XSODEC = F.PONCCDE 
 WHERE SV7ITM IN (
       'CF15L','CF25L','CF30L','CF50L','CF75L','CFL0L','CFL1L','CFL2L','CFL3L','CFL50','CFL5L','CFL7L','FL634','HLC01','HLC02',
       'HLC04','HLC05','HLC07','HLC08','HLC09','HLMXL','L01WD','L02WD','L03WD','L04WD','L05WD','L06WD','L07WD','L08WD','L09FD',
       'L09WD','L10WD','L11WD','L13FD','L14FD','L14WD','L15FD','L15WD','L16FD','L16WD','L17FD','L17WD','L18FD','L18WD','L19WD',
       'L20WD','L21WD','L22FS','L22WD','L23WD','L24WD','L27WS','L28WS','L29WS','L30WS','L31FS','L31WS','L32FS','L32WS','L33FS',
       'L33WS','L34FS','L34WS','L35FS','L35WS','L36FS','L36WS','L39WS','L40WS','L41WS','L42WS','L43WS','L44WS','L45VD','L45WS',
       'L46WS','L47WS','L48WS','L49VD','L50VD','L51VD','L52VD','L53VD','L54VD','L63VS','L67VS','L68VS','L69VS','L70VS','L71VS',
       'L72VS','PTD1B','PTD1R','PTD3B','PTD3R','PTD3S','PTD7D','PTD7S','WBDLL','WBDML','WBMDL','WBSLL','WBSML','WBSRL','WBSTL',
       'WDPLB','WDPLS','WDTLB','WDTLS','WDWLS','WLSLS','WMLUB','WMLUS','WRBLL','WRBXL','WRUTL','WSBLL','WSBML','WSDLL','WSDML',
       'WSDPL','WSDRL','WSDTL','WSDWL','WSDXL','WSI1G','WSI2G','WSI30','WSI50','WSI70','WSLSL','WSMLD','WSMLU','WSMPL','WSMSL',
       'WSMTL','WSMXL','WSRML','WSSLL','WSSML','WSSPL','WSSRL','WSSTL','WSSXL','WURLL')
 AND MSOTOS IN ('CI','CO')
 AND MSOSTS <> 'D' 
 AND SV7STS <> 'D' 
 AND (MSOPST >= 20230101 OR MSOPST = 0)
 )
 ORDER BY SO_CREATE_DT
