SELECT DATA_MONTH, CARRIER, STATE, ACTIVITY, COUNT(*)
FROM (
SELECT DATA_MONTH, CARRIER, STATE,  
  CASE WHEN SVC_ORD_TYPE_CD IN ('CO','PO') THEN 'DISCONNECT'
       WHEN SVC_ORD_TYPE_CD = 'WT' THEN 'MOVED TO RETAIL'
       WHEN SVC_ORD_TYPE_CD = 'CI' THEN 'NEW INSTALL'
       WHEN SVC_ORD_TYPE_CD = 'MT' THEN 'MOVED FROM RETAIL'
       WHEN SVC_ORD_TYPE_CD IS NULL AND MOVEMENT = 'LOS' THEN 'OTHER LOSS'
       WHEN SVC_ORD_TYPE_CD IS NULL AND MOVEMENT = 'ADD' THEN 'OTHER GAIN'
       ELSE NULL END ACTIVITY
FROM (
SELECT DISTINCT SQ1.*, TRUNC(SO.COMPLETION_DTTM) COMP_DT, SO.SVC_ORD_TYPE_CD, SO.SVC_ORD_TYPE_DS
FROM (
--
SELECT DATA_MONTH, WTN, CARRIER, STATE, CUSTNAME, 'ADD' MOVEMENT
FROM USER_WORK.CM_WSA_RESALE
WHERE DATA_MONTH = '2023-05-01'    -- CURRENT MONTH 
AND PRODUCT = 'WSA'
AND WTN NOT IN (
SELECT WTN FROM USER_WORK.CM_WSA_RESALE
WHERE DATA_MONTH = '2023-04-01'    -- PREVIOUS MONTH
)
)SQ1
LEFT OUTER JOIN 
(SELECT SVC_ACCS_METHD_NO, COMPLETION_DTTM, SVC_ORD_TYPE_CD, SVC_ORD_TYPE_DS FROM 
(SELECT SVC_ACCS_METHD_NO, COMPLETION_DTTM, SVC_ORD_TYPE_CD, SVC_ORD_TYPE_DS,
ROW_NUMBER() OVER (PARTITION BY SVC_ACCS_METHD_NO ORDER BY COMPLETION_DTTM) R
FROM EDW_VWMC.SERVICE_ORDERS_V
WHERE TO_CHAR(COMPLETION_DTTM,'YYYYMMDD') BETWEEN '20230430' AND '20230602'
AND SVC_ORD_TYPE_CD IN ('CI','MT'))SQ12
WHERE R = 1) AS SO ON SO.SVC_ACCS_METHD_NO = SQ1.WTN
--
UNION ALL
--
SELECT DISTINCT SQ2.*, SO2.COMPLETION_DTTM, SO2.SVC_ORD_TYPE_CD, SO2.SVC_ORD_TYPE_DS
FROM (
--
SELECT ADD_MONTHS(DATA_MONTH,1) DATA_MONTH, WTN, CARRIER, STATE, CUSTNAME, 'LOSS' MOVEMENT
FROM USER_WORK.CM_WSA_RESALE
WHERE DATA_MONTH = '2023-04-01'      -- PREVIOUS MONTH
AND PRODUCT = 'WSA'
AND WTN NOT IN (
SELECT WTN FROM USER_WORK.CM_WSA_RESALE
WHERE DATA_MONTH = '2023-05-01'      -- CURRENT MONTH
) 
)SQ2
LEFT OUTER JOIN
(SELECT SVC_ACCS_METHD_NO, COMPLETION_DTTM, SVC_ORD_TYPE_CD, SVC_ORD_TYPE_DS FROM 
(SELECT SVC_ACCS_METHD_NO, COMPLETION_DTTM, SVC_ORD_TYPE_CD, SVC_ORD_TYPE_DS,
ROW_NUMBER() OVER (PARTITION BY SVC_ACCS_METHD_NO ORDER BY COMPLETION_DTTM) R
FROM EDW_VWMC.SERVICE_ORDERS_V
WHERE TO_CHAR(COMPLETION_DTTM,'YYYYMMDD') BETWEEN '20230430' AND '20230602'
AND SVC_ORD_TYPE_CD IN ('CO','PO','WT')) SQ22
WHERE R = 1) AS SO2 ON SO2.SVC_ACCS_METHD_NO = SQ2.WTN
-- ORDER BY 3,2
)SQ3
)SQ4
GROUP BY DATA_MONTH, CARRIER, STATE, ACTIVITY
ORDER BY 1,2,3,4
