select carrier, data_month, count(wtn) wtn, sum(voice_mrc) vm
from user_work.cm_wsa_resale
where product = 'WSA'
and carrier in (
'GRANITE TELECOMMUNICATIONS',
'METTEL',
'CLEAR RATE COMMUNICATIONS INC',
'BIRCH TELECOM',
'WHOLESALE AIRTIME dba SOUTHERN CALIFORNIA TELEPHONE COMPANY',
'BULLSEYE TELECOM INC',
'SPECTROTEL',
'AT&T',
'TPX COMMUNICATIONS',
'VERIZON',
'NEW HORIZON COMMUNICATIONS GROUP',
'BCN TELECOM',
'AMERICAN BROADBAND TELECOM',
'GTT COMMUNICATIONS',
'BLUE CASA TELEPHONE LLC'
)
group by carrier, data_month
order by carrier, data_month
