SELECT DISTINCT SQ1.*, TRUNC(SO.COMPLETION_DTTM) COMP_DT, SO.SVC_ORD_TYPE_CD, SO.SVC_ORD_TYPE_DS
FROM (
--
SELECT DATA_MONTH, WTN, CARRIER, STATE, CUSTNAME, 'ADD' MOVEMENT
FROM USER_WORK.CM_WSA_RESALE
WHERE DATA_MONTH = '2023-05-01'    -- CURRENT MONTH 
AND PRODUCT = 'WSA'
AND WTN NOT IN (
SELECT WTN FROM USER_WORK.CM_WSA_RESALE
WHERE DATA_MONTH = '2023-04-01'    -- PREVIOUS MONTH
)
)SQ1
LEFT OUTER JOIN 
(SELECT SVC_ACCS_METHD_NO, COMPLETION_DTTM, SVC_ORD_TYPE_CD, SVC_ORD_TYPE_DS FROM 
(SELECT SVC_ACCS_METHD_NO, COMPLETION_DTTM, SVC_ORD_TYPE_CD, SVC_ORD_TYPE_DS,
ROW_NUMBER() OVER (PARTITION BY SVC_ACCS_METHD_NO ORDER BY COMPLETION_DTTM) R
FROM EDW_VWMC.SERVICE_ORDERS_V
WHERE TO_CHAR(COMPLETION_DTTM,'YYYYMMDD') BETWEEN '20230430' AND '20230602'
AND SVC_ORD_TYPE_CD IN ('CI','MT'))SQ12
WHERE R = 1) AS SO ON SO.SVC_ACCS_METHD_NO = SQ1.WTN
--
UNION ALL
--
SELECT DISTINCT SQ2.*, SO2.COMPLETION_DTTM, SO2.SVC_ORD_TYPE_CD, SO2.SVC_ORD_TYPE_DS
FROM (
--
SELECT ADD_MONTHS(DATA_MONTH,1) DATA_MONTH, WTN, CARRIER, STATE, CUSTNAME, 'LOSS' MOVEMENT
FROM USER_WORK.CM_WSA_RESALE
WHERE DATA_MONTH = '2023-04-01'      -- PREVIOUS MONTH
AND PRODUCT = 'WSA'
AND WTN NOT IN (
SELECT WTN FROM USER_WORK.CM_WSA_RESALE
WHERE DATA_MONTH = '2023-05-01'      -- CURRENT MONTH
) 
)SQ2
LEFT OUTER JOIN
(SELECT SVC_ACCS_METHD_NO, COMPLETION_DTTM, SVC_ORD_TYPE_CD, SVC_ORD_TYPE_DS FROM 
(SELECT SVC_ACCS_METHD_NO, COMPLETION_DTTM, SVC_ORD_TYPE_CD, SVC_ORD_TYPE_DS,
ROW_NUMBER() OVER (PARTITION BY SVC_ACCS_METHD_NO ORDER BY COMPLETION_DTTM) R
FROM EDW_VWMC.SERVICE_ORDERS_V
WHERE TO_CHAR(COMPLETION_DTTM,'YYYYMMDD') BETWEEN '20230430' AND '20230602'
AND SVC_ORD_TYPE_CD IN ('CO','PO','WT')) SQ22
WHERE R = 1) AS SO2 ON SO2.SVC_ACCS_METHD_NO = SQ2.WTN
ORDER BY 3,2
