REPLACE VIEW MY_PARAMS AS
SELECT DATE '2023-02-01' AS START_DATE;

SELECT DATA_MONTH, CARRIER, STATE, VOICE_MRC, VOICE_MRC/LINES AVG_MRC, VOICE_SURCHARGE, VOICE_SURCHARGE/LINES AVG_SURCHARGE, LINES,
       GAINS, LOSSES
FROM (
SELECT DATA_MONTH, CARRIER, STATE, SUM(VOICE_MRC) VOICE_MRC, SUM(VOICE_SURCHARGE) VOICE_SURCHARGE, SUM(LINES) LINES,
       SUM(ADDS) GAINS, SUM(REMOVALS) LOSSES
FROM (
SELECT TRUNC(DATA_MONTH) DATA_MONTH, CARRIER, STATE, SUM(VOICE_MRC) VOICE_MRC, SUM(VOICE_SURCHARGE) VOICE_SURCHARGE, COUNT(*) LINES, 
       NULL ADDS, NULL REMOVALS
FROM USER_WORK.CM_WSA_RESALE
WHERE PRODUCT = 'WSA'
AND DATA_MONTH = MY_PARAMS.START_DATE
GROUP BY DATA_MONTH, CARRIER, STATE
--
UNION ALL
--
SELECT DATA_MONTH, CARRIER, STATE, NULL VOICE_MRC, NULL VOICE_SURCHARGE, NULL LINES, COUNT(*) ADDS, NULL REMOVALS
FROM USER_WORK.CM_WSA_RESALE
WHERE DATA_MONTH = MY_PARAMS.START_DATE
AND PRODUCT = 'WSA'
AND WTN NOT IN (
SELECT WTN FROM USER_WORK.CM_WSA_RESALE
WHERE DATA_MONTH = ADD_MONTHS(MY_PARAMS.START_DATE,-1)
)
GROUP BY DATA_MONTH, CARRIER, STATE
--
UNION ALL
--
SELECT ADD_MONTHS(DATA_MONTH,1) DATA_MONTH, CARRIER, STATE, NULL VOICE_MRC, NULL VOICE_SURCHARGE, NULL LINES, NULL ADDS, COUNT(*) REMOVALS
FROM USER_WORK.CM_WSA_RESALE
WHERE DATA_MONTH = ADD_MONTHS(MY_PARAMS.START_DATE,-1)
AND PRODUCT = 'WSA'
AND WTN NOT IN (
SELECT WTN FROM USER_WORK.CM_WSA_RESALE
WHERE DATA_MONTH = MY_PARAMS.START_DATE
)
GROUP BY DATA_MONTH, CARRIER, STATE
) SUBQ
GROUP BY DATA_MONTH, CARRIER, STATE
) SUBQ2
ORDER BY 1,2,3;
