REPLACE VIEW USER_WORK.CM_MY_PARAMS AS
SELECT DATE '2023-12-01' AS START_DATE;

SELECT DATA_MONTH, CARRIER, STATE, VOICE_MRC, VOICE_MRC/LINES AVG_MRC, VOICE_SURCHARGE, VOICE_SURCHARGE/LINES AVG_SURCHARGE, LINES,
       GAINS, LOSSES, RES_TO_WSA, WSA_TO_RES, PORT_OUT, PORT_IN
FROM (
SELECT DATA_MONTH, CARRIER, STATE, SUM(VOICE_MRC) VOICE_MRC, SUM(VOICE_SURCHARGE) VOICE_SURCHARGE, SUM(LINES) LINES,
       SUM(ADDS) GAINS, SUM(REMOVALS) LOSSES, SUM(RES_TO_WSA) RES_TO_WSA, 
       SUM(WSA_TO_RES) WSA_TO_RES, SUM(PORT_OUT) PORT_OUT, SUM(PORT_IN) PORT_IN
FROM (
-- MRC & LINES
SELECT TRUNC(DATA_MONTH) DATA_MONTH, CARRIER, STATE, SUM(VOICE_MRC) VOICE_MRC, SUM(VOICE_SURCHARGE) VOICE_SURCHARGE, COUNT(*) LINES, 
       NULL ADDS, NULL REMOVALS, NULL RES_TO_WSA, NULL WSA_TO_RES, NULL PORT_OUT, NULL PORT_IN
FROM USER_WORK.CM_WSA_RESALE
WHERE PRODUCT = 'WSA'
AND DATA_MONTH = USER_WORK.CM_MY_PARAMS.START_DATE
GROUP BY DATA_MONTH, CARRIER, STATE
--
UNION ALL
-- ADDS
SELECT DATA_MONTH, CARRIER, STATE, NULL VOICE_MRC, NULL VOICE_SURCHARGE, NULL LINES, COUNT(*) ADDS, NULL REMOVALS, 
       NULL RES_TO_WSA, NULL WSA_TO_RES, NULL PORT_OUT, NULL PORT_IN
FROM USER_WORK.CM_WSA_RESALE
WHERE DATA_MONTH = USER_WORK.CM_MY_PARAMS.START_DATE
AND PRODUCT = 'WSA'
AND WTN NOT IN (
SELECT WTN FROM USER_WORK.CM_WSA_RESALE
WHERE DATA_MONTH = ADD_MONTHS(USER_WORK.CM_MY_PARAMS.START_DATE,-1)
)
GROUP BY DATA_MONTH, CARRIER, STATE
--
UNION ALL
-- LOSSES
SELECT ADD_MONTHS(DATA_MONTH,1) DATA_MONTH, CARRIER, STATE, NULL VOICE_MRC, NULL VOICE_SURCHARGE, NULL LINES, NULL ADDS, COUNT(*) REMOVALS,
       NULL RES_TO_WSA, NULL WSA_TO_RES, NULL PORT_OUT, NULL PORT_IN
FROM USER_WORK.CM_WSA_RESALE
WHERE DATA_MONTH = ADD_MONTHS(USER_WORK.CM_MY_PARAMS.START_DATE,-1)
AND PRODUCT = 'WSA'
AND WTN NOT IN (
SELECT WTN FROM USER_WORK.CM_WSA_RESALE
WHERE DATA_MONTH = USER_WORK.CM_MY_PARAMS.START_DATE
)
GROUP BY DATA_MONTH, CARRIER, STATE
--
UNION ALL
-- RES TO WSA
SELECT CURR_DATA_MONTH DATA_MONTH, CURR_CARRIER CARRIER, STATE, NULL VOICE_MRC, NULL VOICE_SURCHARGE, NULL LINES, NULL ADDS, NULL REMOVALS,
       COUNT(*) RES_TO_WSA, NULL WSA_TO_RES, NULL PORT_OUT, NULL PORT_IN
FROM (
SELECT WTN, STATE, PREV_PROD, PREV_DATA_MONTH, PREV_CARRIER, CURR_PROD, CURR_DATA_MONTH, CURR_CARRIER,
       CASE WHEN PREV_CARRIER = CURR_CARRIER THEN 'SAME' ELSE 'CHANGE' END CARRIER_MOVE
FROM (
SELECT WTN, STATE, 'RESALE' PREV_PROD, MAX(PREV_DATA_MONTH) PREV_DATA_MONTH, MAX(PREV_CARRIER) PREV_CARRIER,  
       'WSA' CURR_PROD, MAX(CURR_DATA_MONTH) CURR_DATA_MONTH, MAX(CURR_CARRIER) CURR_CARRIER
FROM (
SELECT WTN, STATE, 
       CASE WHEN R = 2 THEN CARRIER ELSE NULL END PREV_CARRIER,
       CASE WHEN R = 2 THEN DATA_MONTH ELSE NULL END PREV_DATA_MONTH,
       CASE WHEN R = 1 THEN CARRIER ELSE NULL END CURR_CARRIER,
       CASE WHEN R = 1 THEN DATA_MONTH ELSE NULL END CURR_DATA_MONTH
FROM (
SELECT WTN, STATE, DATA_MONTH, CARRIER, PRODUCT,
       ROW_NUMBER() OVER (PARTITION BY WTN ORDER BY DATA_MONTH DESC) R
FROM USER_WORK.CM_WSA_RESALE
WHERE DATA_MONTH in (USER_WORK.CM_MY_PARAMS.START_DATE, ADD_MONTHS(USER_WORK.CM_MY_PARAMS.START_DATE,-1))
AND WTN IN (
SELECT WTN
FROM USER_WORK.CM_WSA_RESALE
WHERE DATA_MONTH = USER_WORK.CM_MY_PARAMS.START_DATE
AND PRODUCT = 'WSA'
AND WTN IN (
SELECT WTN FROM USER_WORK.CM_WSA_RESALE
WHERE DATA_MONTH = ADD_MONTHS(USER_WORK.CM_MY_PARAMS.START_DATE,-1)
AND PRODUCT = 'RESALE'
)) 
) SUBQ1
) SUBQ2
GROUP BY WTN, STATE
) SUBQ3
) SUBQ4
WHERE CARRIER_MOVE = 'SAME'
GROUP BY CURR_DATA_MONTH, CURR_CARRIER, STATE
--
UNION ALL
-- WSA TO RES
SELECT CURR_DATA_MONTH DATA_MONTH, CURR_CARRIER CARRIER, STATE, NULL VOICE_MRC, NULL VOICE_SURCHARGE, NULL LINES, NULL ADDS, NULL REMOVALS,
       NULL RES_TO_WSA, COUNT(*) WSA_TO_RES, NULL PORT_OUT, NULL PORT_IN
FROM (
SELECT WTN, STATE, PREV_PROD, PREV_DATA_MONTH, PREV_CARRIER, CURR_PROD, CURR_DATA_MONTH, CURR_CARRIER,
       CASE WHEN PREV_CARRIER = CURR_CARRIER THEN 'SAME' ELSE 'CHANGE' END CARRIER_MOVE
FROM (
SELECT WTN, STATE, 'WSA' PREV_PROD, MAX(PREV_DATA_MONTH) PREV_DATA_MONTH, MAX(PREV_CARRIER) PREV_CARRIER,  
       'RESALE' CURR_PROD, MAX(CURR_DATA_MONTH) CURR_DATA_MONTH, MAX(CURR_CARRIER) CURR_CARRIER
FROM (
SELECT WTN, STATE, 
       CASE WHEN R = 2 THEN CARRIER ELSE NULL END PREV_CARRIER,
       CASE WHEN R = 2 THEN DATA_MONTH ELSE NULL END PREV_DATA_MONTH,
       CASE WHEN R = 1 THEN CARRIER ELSE NULL END CURR_CARRIER,
       CASE WHEN R = 1 THEN DATA_MONTH ELSE NULL END CURR_DATA_MONTH
FROM (
SELECT WTN, STATE, DATA_MONTH, CARRIER, PRODUCT,
       ROW_NUMBER() OVER (PARTITION BY WTN ORDER BY DATA_MONTH DESC) R
FROM USER_WORK.CM_WSA_RESALE
WHERE DATA_MONTH in (USER_WORK.CM_MY_PARAMS.START_DATE, ADD_MONTHS(USER_WORK.CM_MY_PARAMS.START_DATE,-1))
AND WTN IN (
SELECT WTN
FROM USER_WORK.CM_WSA_RESALE
WHERE DATA_MONTH = USER_WORK.CM_MY_PARAMS.START_DATE
AND PRODUCT = 'RESALE'
AND WTN IN (
SELECT WTN FROM USER_WORK.CM_WSA_RESALE
WHERE DATA_MONTH = ADD_MONTHS(USER_WORK.CM_MY_PARAMS.START_DATE,-1)
AND PRODUCT = 'WSA'
)) 
) SUBQ1
) SUBQ2
GROUP BY WTN, STATE
) SUBQ3
) SUBQ4
WHERE CARRIER_MOVE = 'SAME'
GROUP BY CURR_DATA_MONTH, CURR_CARRIER, STATE
--
UNION ALL
-- PORT OUT
SELECT CURR_DATA_MONTH DATA_MONTH, PREV_CARRIER CARRIER, STATE, NULL VOICE_MRC, NULL VOICE_SURCHARGE, NULL LINES, NULL ADDS, NULL REMOVALS,
       NULL RES_TO_WSA, NULL WSA_TO_RES, COUNT(*) PORT_OUT, NULL PORT_IN
FROM (
SELECT WTN, STATE, PREV_PROD, PREV_DATA_MONTH, PREV_CARRIER, CURR_PROD, CURR_DATA_MONTH, CURR_CARRIER,
       CASE WHEN PREV_CARRIER = CURR_CARRIER THEN 'SAME' ELSE 'CHANGE' END CARRIER_MOVE
FROM (
SELECT WTN, STATE, MAX(PREV_PROD) PREV_PROD, MAX(PREV_DATA_MONTH) PREV_DATA_MONTH, MAX(PREV_CARRIER) PREV_CARRIER,  
        MAX(CURR_PROD) CURR_PROD, MAX(CURR_DATA_MONTH) CURR_DATA_MONTH, MAX(CURR_CARRIER) CURR_CARRIER
FROM (
SELECT WTN, STATE, 
       CASE WHEN R = 2 THEN CARRIER ELSE NULL END PREV_CARRIER,
       CASE WHEN R = 2 THEN DATA_MONTH ELSE NULL END PREV_DATA_MONTH,
       CASE WHEN R = 2 THEN PRODUCT ELSE NULL END PREV_PROD,
       CASE WHEN R = 1 THEN CARRIER ELSE NULL END CURR_CARRIER,
       CASE WHEN R = 1 THEN DATA_MONTH ELSE NULL END CURR_DATA_MONTH,
       CASE WHEN R = 1 THEN PRODUCT ELSE NULL END CURR_PROD
FROM (
SELECT WTN, STATE, DATA_MONTH, CARRIER, PRODUCT,
       ROW_NUMBER() OVER (PARTITION BY WTN ORDER BY DATA_MONTH DESC) R
FROM USER_WORK.CM_WSA_RESALE
WHERE DATA_MONTH in (USER_WORK.CM_MY_PARAMS.START_DATE, ADD_MONTHS(USER_WORK.CM_MY_PARAMS.START_DATE,-1))
AND WTN IN (
SELECT WTN
FROM USER_WORK.CM_WSA_RESALE
WHERE DATA_MONTH = USER_WORK.CM_MY_PARAMS.START_DATE
AND WTN IN (
SELECT WTN FROM USER_WORK.CM_WSA_RESALE
WHERE DATA_MONTH = ADD_MONTHS(USER_WORK.CM_MY_PARAMS.START_DATE,-1)
AND PRODUCT = 'WSA'
)) 
) SUBQ1
) SUBQ2
GROUP BY WTN, STATE
) SUBQ3
) SUBQ4
WHERE CARRIER_MOVE = 'CHANGE'
GROUP BY CURR_DATA_MONTH, PREV_CARRIER, STATE
--
UNION ALL
-- PORT IN
SELECT CURR_DATA_MONTH DATA_MONTH, CURR_CARRIER CARRIER, STATE, NULL VOICE_MRC, NULL VOICE_SURCHARGE, NULL LINES, NULL ADDS, NULL REMOVALS,
       NULL RES_TO_WSA, NULL WSA_TO_RES, NULL PORT_OUT, COUNT(*) PORT_IN
FROM (
SELECT WTN, STATE, PREV_PROD, PREV_DATA_MONTH, PREV_CARRIER, CURR_PROD, CURR_DATA_MONTH, CURR_CARRIER,
       CASE WHEN PREV_CARRIER = CURR_CARRIER THEN 'SAME' ELSE 'CHANGE' END CARRIER_MOVE
FROM (
SELECT WTN, STATE, MAX(PREV_PROD) PREV_PROD, MAX(PREV_DATA_MONTH) PREV_DATA_MONTH, MAX(PREV_CARRIER) PREV_CARRIER,  
        MAX(CURR_PROD) CURR_PROD, MAX(CURR_DATA_MONTH) CURR_DATA_MONTH, MAX(CURR_CARRIER) CURR_CARRIER
FROM (
SELECT WTN, STATE, 
       CASE WHEN R = 2 THEN CARRIER ELSE NULL END PREV_CARRIER,
       CASE WHEN R = 2 THEN DATA_MONTH ELSE NULL END PREV_DATA_MONTH,
       CASE WHEN R = 2 THEN PRODUCT ELSE NULL END PREV_PROD,
       CASE WHEN R = 1 THEN CARRIER ELSE NULL END CURR_CARRIER,
       CASE WHEN R = 1 THEN DATA_MONTH ELSE NULL END CURR_DATA_MONTH,
       CASE WHEN R = 1 THEN PRODUCT ELSE NULL END CURR_PROD
FROM (
SELECT WTN, STATE, DATA_MONTH, CARRIER, PRODUCT,
       ROW_NUMBER() OVER (PARTITION BY WTN ORDER BY DATA_MONTH DESC) R
FROM USER_WORK.CM_WSA_RESALE
WHERE DATA_MONTH in (USER_WORK.CM_MY_PARAMS.START_DATE, ADD_MONTHS(USER_WORK.CM_MY_PARAMS.START_DATE,-1))
AND WTN IN (
SELECT WTN
FROM USER_WORK.CM_WSA_RESALE
WHERE DATA_MONTH = USER_WORK.CM_MY_PARAMS.START_DATE
AND PRODUCT = 'WSA'
AND WTN IN (
SELECT WTN FROM USER_WORK.CM_WSA_RESALE
WHERE DATA_MONTH = ADD_MONTHS(USER_WORK.CM_MY_PARAMS.START_DATE,-1)
)) 
) SUBQ1
) SUBQ2
GROUP BY WTN, STATE
) SUBQ3
) SUBQ4
WHERE CARRIER_MOVE = 'CHANGE'
GROUP BY CURR_DATA_MONTH, CURR_CARRIER, STATE
--
) SUBQ
GROUP BY DATA_MONTH, CARRIER, STATE
) SUBQ2
ORDER BY 1,2,3;
