SELECT DISTINCT CARRIER, CCNA, 
       STATE, TARIFF_CD, SUBSTP SVC_TYPE, STPDSC SVC_TYPE_DESC, PRODUCT, SQ5.WTN, SQ5.BTN, STN, 
       GL_MATRIX_CLASS, PRD_SVC_CD, PRD_SVC_CD_DS,
   COALESCE(SUM(CASE WHEN GL_MATRIX_CLASS ='VOICE' AND BILL_AMT_TYPE_DS <> 'ADJUSTMENTS' THEN ((CHRGE_AMT)-(PRORATED_CHARGE_AMT)) END), 0) AS VOICE_MRC,
   COALESCE(SUM(CASE WHEN GL_MATRIX_CLASS ='VOICE' AND BILL_AMT_TYPE_DS = 'ADJUSTMENTS' THEN CHRGE_AMT END), 0) AS VOICE_ADJ,
   COALESCE(SUM(CASE WHEN GL_MATRIX_CLASS ='VOICE' AND PRORATED_CHARGE_AMT <> 0 THEN PRORATED_CHARGE_AMT END), 0) AS VOICE_PRO_RATED,
   COALESCE(SUM(CASE WHEN GL_MATRIX_CLASS ='VOICE' THEN CHRGE_AMT END), 0) AS VOICE_TOTAL,
   COALESCE(SUM(CASE WHEN GL_MATRIX_CLASS ='VOICE' AND BILL_AMT_TYPE_DS <> 'ADJUSTMENTS' AND SUBSTR(PRD_SVC_CD,4,1) = 'P' 
                 AND (PRD_SVC_CD_DS LIKE '%SCH%' OR PRD_SVC_CD_DS LIKE '%SCHG%' OR PRD_SVC_CD_DS LIKE '%SRCH%' OR PRD_SVC_CD_DS LIKE '%SRCHG%' OR
                      PRD_SVC_CD_DS LIKE '%SURCHARGE%' OR PRD_SVC_CD_DS LIKE '%SURCHG%' OR PRD_SVC_CD_DS LIKE '%SURCHRG%' OR PRD_SVC_CD_DS LIKE '%ZONE%') 
   THEN ((CHRGE_AMT)-(PRORATED_CHARGE_AMT)) END), 0) AS SURCHARGE_MRC,
   CUSTNAME
 FROM (
SELECT DISTINCT CARRIER, CCNA, 
       STATE, TARIFF_CD, PRODUCT, WTN, BTN, STN, CUSTNAME,
       CASE WHEN PRD_SVC_CD IN ('WHALP','WHAPB') THEN 'VOICE' ELSE GL_MATRIX_CLASS END GL_MATRIX_CLASS,
       BILL_AMT_TYPE_DS, CHRGE_AMT, PRORATED_CHARGE_AMT, PRD_SVC_CD, PRD_SVC_CD_DS
FROM (
SELECT CARRIER, CCNA, STATE, TARIFF_CD, PRODUCT, WTN, BTN, STN, CUSTNAME,
       BILL_AMT_TYPE_DS, GL_MATRIX_NO, CHRGE_AMT, PRORATED_CHARGE_AMT, PRD_SVC_CD, PRD_SVC_CD_DS, BILL_CYCLE_DT
FROM USER_WORK.CM_RVT_TEMP RVT 
     LEFT OUTER JOIN EDW_VWMC.EUBS_BILL_REV_ACCT_DETAIL_V AS EUBS ON EUBS.SVC_ACCS_METHD_NO = RVT.WTN
     WHERE EUBS.BILL_MONTH_DATE ='2023-11-01'
     and carrier = 'TPX COMMUNICATIONS' and product = 'WSA'
   AND GL_MATRIX_NO <> '000' --excludes Non-Rev  
   AND GL_MATRIX_NO <> '124' --excludes Inside Wiring Non-Recurring
)SQ4
 LEFT OUTER JOIN USER_WORK.CM_GL_MATRIX AS GLM ON GLM.GL_MATRIX_NO = SQ4.GL_MATRIX_NO    
)SQ5
 LEFT OUTER JOIN 
 (SELECT DISTINCT MTN, SEQ, SUBSTP, STPDSC
        FROM (
            SELECT MTN, 
            SEQ, 
            SUBSTP,
            STPDSC,
            ROW_NUMBER() OVER (PARTITION BY MTN ORDER BY SEQ) R
         FROM USER_WORK.CM_SUB_HISTORY      
          )  ISQ1  
              WHERE R = 1 ) SUBHIST ON SUBHIST.MTN = SQ5.WTN
 WHERE GL_MATRIX_CLASS = 'VOICE'
  AND PRODUCT IN ('WSA','RESALE')
  -- AND SUBHIST.SEQ = '0'
 GROUP BY CARRIER, CCNA, STATE, TARIFF_CD, PRODUCT, SUBSTP, STPDSC,
          CUSTNAME, WTN, BTN, STN, GL_MATRIX_CLASS, CUSTNAME, PRD_SVC_CD, PRD_SVC_CD_DS
 ORDER BY 1,7,3,8;          