SELECT DISTINCT CARRIER, CCNA, 
       STATE, TARIFF_CD, SUBSTP SVC_TYPE, STPDSC SVC_TYPE_DESC, BAN_TYPE, SQ5.WTN, SQ5.BTN, MASTERACCOUNTNUMBER STN, 
       GL_MATRIX_CLASS, VOICE_MRC, VOICE_ADJ, VOICE_PRO_RATED, VOICE_TOTAL
 FROM (
SELECT DISTINCT CARRIER, CCNA, 
       STATE, TARIFF_CD, ACCOUNTACTIVATIONDATE, MRC, BAN_TYPE, WTN, BTN, MASTERACCOUNTNUMBER, 
       GL_MATRIX_CLASS, 
   COALESCE(SUM(CASE WHEN GL_MATRIX_CLASS ='VOICE' AND BILL_AMT_TYPE_DS <> 'ADJUSTMENTS' THEN ((CHRGE_AMT)-(PRORATED_CHARGE_AMT)) END), 0) AS VOICE_MRC,
   COALESCE(SUM(CASE WHEN GL_MATRIX_CLASS ='VOICE' AND BILL_AMT_TYPE_DS = 'ADJUSTMENTS' THEN CHRGE_AMT END), 0) AS VOICE_ADJ,
   COALESCE(SUM(CASE WHEN GL_MATRIX_CLASS ='VOICE' AND PRORATED_CHARGE_AMT <> 0 THEN PRORATED_CHARGE_AMT END), 0) AS VOICE_PRO_RATED,
   COALESCE(SUM(CASE WHEN GL_MATRIX_CLASS ='VOICE' THEN CHRGE_AMT END), 0) AS VOICE_TOTAL
FROM (
SELECT CASE WHEN CARRIER_NAME IS NOT NULL THEN CARRIER_NAME ELSE CARRIER END CARRIER, 
       CCNA, STATE, TARIFF_CD, ACCOUNTACTIVATIONDATE, MRC, BAN_TYPE, WTN, BTN, MASTERACCOUNTNUMBER, 
       BILL_AMT_TYPE_DS, GL_MATRIX_NO, CHRGE_AMT, PRORATED_CHARGE_AMT
FROM (

SELECT MCL.PRIMARY_CARRIER_NAME CARRIER, CARLIS.CARRIER_NAME, SQ2.CCNA, BAN_STATE STATE, TARIFF_CD,  
       TRUNC(ACCOUNTACTIVATIONDATE) ACCOUNTACTIVATIONDATE, MRC, BAN_TYPE, WTN, BTN, MASTERACCOUNTNUMBER
FROM (
--
SELECT LSPBAN.BANCARCD CCNA, SQ1.WTN, SQ1.BTN, SQ1.MASTERACCOUNTNUMBER,
       SQ1.STATE, LSPBAN.BANSTACD BAN_STATE, SQ1.ACCOUNTACTIVATIONDATE, SQ1.MRC, LSPBAN.BANTRFCD TARIFF_CD,
       CASE WHEN LSPBAN.BANSUMTYP IN ('D','B','C','E','F','G','H','I','J','K') THEN 'DIRECTORY'
            WHEN LSPBAN.BANSUMTYP IN ('P','W','X','Y','Z') THEN 'WSA'
            WHEN LSPBAN.BANSUMTYP IN ('L','M','N','O','A','Q') THEN 'LOOP'
            WHEN LSPBAN.BANSUMTYP IN ('R','S','T','U','V') THEN 'RESALE'
            WHEN LSPBAN.BANSUMTYP IN ('I') THEN 'ISP'
            ELSE NULL END BAN_TYPE
FROM (
--
SELECT DISTINCT SUBSTR(TRIM(TELEPHONENUMBER),1,10) WTN, 
       SUBSTR(TRIM(BILLINGTELEPHONE),1,10) BTN, 
       SUBSTR(TRIM(C2F.MASTERACCOUNTNUMBER),1,10) MASTERACCOUNTNUMBER, 
       C2F.STATE,
       C2F.ACCOUNTACTIVATIONDATE,
       SUM(C2F.MRC) MRC
FROM EDW_VWMC.C2F_EXCHANGE_SUBSCRIBERS C2F
WHERE MASTERACCOUNTNUMBER IS NOT NULL
  -- AND C2F.TELEPHONENUMBER in ('6086475513')
  GROUP BY TELEPHONENUMBER, BILLINGTELEPHONE, MASTERACCOUNTNUMBER, STATE, ACCOUNTACTIVATIONDATE
)SQ1,
 USER_WORK.CM_LSPBANM LSPBAN
 WHERE SQ1.MASTERACCOUNTNUMBER = LSPBAN.STN
 AND SUBSTR(LSPBAN.BANCARCD,1,1) <> 'Z'
)SQ2
 LEFT OUTER JOIN USER_WORK.CM_CARRIER_ACNA_MCL_202201 AS MCL ON MCL.SECONDARY_ID = SQ2.CCNA
 LEFT OUTER JOIN USER_WORK.CM_CARRIER_LIST AS CARLIS ON CARLIS.CCNA = SQ2.CCNA

)SQ3 
 LEFT OUTER JOIN EDW_VWMC.EUBS_BILL_REV_ACCT_DETAIL_V AS EUBS ON EUBS.SVC_ACCS_METHD_NO = SQ3.WTN
    WHERE EUBS.BILL_MONTH_DATE ='2022-10-01'
    -- WHERE EUBS.BILL_CYCLE_DT BETWEEN '2022-09-28' AND '2022-10-27'  -- check how far EUBS is loaded
   AND GL_MATRIX_NO <> '000' --excludes Non-Rev  
   AND GL_MATRIX_NO <> '124' --excludes Inside Wiring Non-Recurring
   -- AND BILL_AMT_TYPE_DS <> 'ADJUSTMENTS'
 
)SQ4
 LEFT OUTER JOIN USER_WORK.CM_GL_MATRIX AS GLM ON GLM.GL_MATRIX_NO = SQ4.GL_MATRIX_NO
 GROUP BY CARRIER, CCNA, STATE, TARIFF_CD, ACCOUNTACTIVATIONDATE, MRC, BAN_TYPE, 
          WTN, BTN, MASTERACCOUNTNUMBER, GL_MATRIX_CLASS        
)SQ5
 LEFT OUTER JOIN 
 (SELECT DISTINCT MTN, SEQ, SUBSTP, STPDSC
        FROM (
            SELECT MTN, 
            SEQ, 
            SUBSTP,
            STPDSC,
            ROW_NUMBER() OVER (PARTITION BY MTN ORDER BY SEQ) R
         FROM USER_WORK.CM_SUB_HISTORY      
          )  ISQ1  
              WHERE R = 1 ) SUBHIST ON SUBHIST.MTN = SQ5.WTN
 WHERE GL_MATRIX_CLASS = 'VOICE'
  AND BAN_TYPE IN ('WSA','RESALE')
  -- AND SUBHIST.SEQ = '0'
 ORDER BY 1,6,3,7;          