SELECT DISTINCT CASE WHEN CARRIER_NAME IS NOT NULL THEN CARRIER_NAME ELSE CARRIER END CARRIER,
       CCNA, STATE, TARIFF_CD, CUSTNAME, SERVICE_TYPE,
       BAN_TYPE, WTN, BTN, MASTERACCOUNTNUMBER, ADDRESS, CITY, ZIPCODE
FROM (
SELECT MCL.PRIMARY_CARRIER_NAME CARRIER, CARLIS.CARRIER_NAME, SQ2.CCNA, BAN_STATE STATE, TARIFF_CD, CUSTNAME,
       CASE WHEN LCTD LIKE '%BUS%' THEN 'BUS'
            WHEN LCTD LIKE '%RES%' THEN 'RES'
            WHEN LCTD LIKE 'CLEC B%' THEN 'BUS'
            WHEN LCTD LIKE 'CLEC R%' THEN 'RES'
            WHEN LCTD LIKE 'CL B%' THEN 'BUS'
            WHEN LCTD LIKE 'CL R%' THEN 'RES'
            WHEN LCTD LIKE 'B %' THEN 'BUS'
            WHEN LCTD LIKE 'R %' THEN 'RES'
            WHEN LCTD LIKE '%CENTREX%' THEN 'BUS'
            ELSE 'BUS' END SERVICE_TYPE,
       BAN_TYPE, WTN, BTN, MASTERACCOUNTNUMBER, ADDRESS, CITY, ZIPCODE
FROM (
-- 2
SELECT LSPBAN.BANCARCD CCNA, SQ1.WTN, SQ1.BTN, SQ1.MASTERACCOUNTNUMBER, CUSTNAME, LCTD,
       SQ1.STATE, LSPBAN.BANSTACD BAN_STATE, LSPBAN.BANTRFCD TARIFF_CD, ADDRESS, CITY, ZIPCODE, 
       CASE WHEN LSPBAN.BANSUMTYP IN ('D','B','C','E','F','G','H','I','J','K') THEN 'DIRECTORY'
            WHEN LSPBAN.BANSUMTYP IN ('P','W','X','Y','Z') THEN 'WSA'
            WHEN LSPBAN.BANSUMTYP IN ('L','M','N','O','A','Q') THEN 'LOOP'
            WHEN LSPBAN.BANSUMTYP IN ('R','S','T','U','V') THEN 'RESALE'
            WHEN LSPBAN.BANSUMTYP IN ('I') THEN 'ISP'
            ELSE NULL END BAN_TYPE   
FROM (
-- 1
SELECT DISTINCT SUBSTR(TRIM(TELEPHONENUMBER),1,10) WTN, 
       SUBSTR(TRIM(BILLINGTELEPHONE),1,10) BTN, 
       SUBSTR(TRIM(C2F.MASTERACCOUNTNUMBER),1,10) MASTERACCOUNTNUMBER, 
       C2F.ADDRESS,
       C2F.CITY,
       C2F.STATE,
       C2F.ZIPCODE,
       C2F.SUBSCRIPTIONUSERNAME CUSTNAME,
       C2F.LINE_CARD_TYPE_DESC LCTD,
       ROW_NUMBER() OVER (PARTITION BY WTN ORDER BY MRC DESC) R
FROM EDW_VWMC.C2F_EXCHANGE_SUBSCRIBERS C2F
WHERE MASTERACCOUNTNUMBER IS NOT NULL
       -- AND C2F.TELEPHONENUMBER in ('9797745612')
-- 1
)SQ1,
 USER_WORK.CM_LSPBANM LSPBAN
 WHERE SQ1.MASTERACCOUNTNUMBER = LSPBAN.STN
 AND R = 1
-- 2 
)SQ2
 LEFT OUTER JOIN USER_WORK.CM_CARRIER_ACNA_MCL AS MCL ON MCL.SECONDARY_ID = SQ2.CCNA
 LEFT OUTER JOIN USER_WORK.CM_CARRIER_LIST AS CARLIS ON CARLIS.CCNA = SQ2.CCNA
 WHERE BAN_TYPE IN ('WSA','RESALE')
 -- AND WTN <> MASTERACCOUNTNUMBER
 )SQ3