CREATE PROCEDURE [LZ].[usp_ROUTE_MILEAGE]
/*
	-- Add any parameters for the stored procedure here
	@var1 int,
	@var2 int
*/
AS
	SET XACT_ABORT, NOCOUNT ON;
BEGIN TRY
	BEGIN TRANSACTION
	DROP TABLE IF EXISTS #t
INSERT INTO [LOG].tbl_StoreProc
    ([EVENTNAME]
    ,[EVENTSTART]
    ,[EVENTTYPE]
    ,[EVENTDESCRIPTION])

--enter values below

VALUES
('LZ.ROUTE_MILEAGE'
    ,CAST(GETDATE() AS DATETIME)
    ,'STORE PROC'
    ,'SINGLE_INGESTION')



SELECT MAX(EVENTID) AS LATESTID  INTO #t
FROM [LOG].tbl_StoreProc


truncate table LZ.TBL_ROUTE_MILEAGE --Cannot truncate system versioned table

insert INTO LZ.TBL_ROUTE_MILEAGE
SELECT A.*

FROM OPENROWSET('Microsoft.ACE.OLEDB.12.0', 
   'Excel 12.0;Database=D:\LZ\WCF\ROUTE MILEAGE\Route and Sheath Summary.XLSX;HDR=YES', 
   'SELECT * FROM [Route and Sheath Summary$]')A


   --INSERT INTO HISTORICAL TRACKED TABLE
INSERT INTO WCF.TBL_ROUTE_MILEAGE
SELECT A.*,CAST(GETDATE() AS DATE) AS UPDATE_DT FROM LZ.TBL_ROUTE_MILEAGE A

	
	
UPDATE L
SET L.EVENTEND=CAST(GETDATE() AS DATETIME)
FROM LOG.tbl_StoreProc L
INNER JOIN #t
ON L.EVENTID = #t.LATESTID
DROP TABLE IF EXISTS #t


	
	COMMIT TRANSACTION
END TRY
BEGIN CATCH
	IF @@trancount > 0 ROLLBACK TRANSACTION
	EXEC usp_error_handler
	RETURN 55555
END CATCH
GO