/*
CREATE PROCEDURE [LZ].[USP_CABS_SHORTCUT]
AS
INSERT INTO LZ.TBL_CABS_SHORTCUT (CLEAN_ID, BILL_MONTH_DT, LAST_BILL_MONTH_DT, PRIMARY_CARRIER_NAME, PRODUCT, SVC_GROUP, TIER, TOTAL_MRC, UNI_MBPS, EVC_MBPS)
SELECT DISTINCT
    OREPLACE(OREPLACE(OREPLACE(SUBQ2.CIRCUIT_NO,'.',''),'-',''),' ','') AS CLEAN_ID,
    SUBQ2.BILL_MONTH_DT,
    SUBQ2.LAST_BILL_MONTH_DT,
    SUBQ2.PRIMARY_CARRIER_NAME,
    SUBQ2.PRODUCT,
    SUBQ2.SVC_GROUP,
    SUBQ2.TIER,
    SUBQ2.TOTAL_MRC,
    SUBQ2.UNI_MBPS,
    SUBQ2.EVC_MBPS

    -- etl pipeline wip (WAD 239 ticket #)
    -- btwn teradata, Miraz environment - no current integration
    -- won't work currently - comment everything out
FROM
(
    SELECT DISTINCT
        CABSSP.CMPY_NO,
        SUBQ1.*,
        ROW_NUMBER() OVER (PARTITION BY CABS.CIRCUIT_NO ORDER BY CMPY_NO) AS ROWNUM
    FROM
    (
        SELECT DISTINCT
            CABS0.CIRCUIT_NO,
            CABS0.CMPY_NO,
            CASE
                WHEN CABS0.STATE_CD IN ('AL','AZ','CA','CT','FL','GA','IA','ID','IL','IN','MI','MN','MS','MT','NC','NE','NM','NV','NY','OH','OR','PA','SC','TN','TX','UT','WA','WI','WV') THEN CABS0.STATE_CD
                WHEN SUBSTR(CABS0.EO_CLLI_CD,5,2) IN ('AL','AZ','CA','CT','FL','GA','IA','ID','IL','IN','MI','MN','MS','MT','NC','NE','NM','NV','NY','OH','OR','PA','SC','TN','TX','UT','WA','WI','WV') THEN SUBSTR(CABS0.EO_CLLI_CD,5,2)
                WHEN SUBSTR(CABS0.POP_CLLI_CD,5,2) IN ('AL','AZ','CA','CT','FL','GA','IA','ID','IL','IN','MI','MN','MS','MT','NC','NE','NM','NV','NY','OH','OR','PA','SC','TN','TX','UT','WA','WI','WV') THEN SUBSTR(CABS0.POP_CLLI_CD,5,2)
                WHEN SUBSTR(CABS0.CIRCUIT_NO,18,2) IN ('AL','AZ','CA','CT','FL','GA','IA','ID','IL','IN','MI','MN','MS','MT','NC','NE','NM','NV','NY','OH','OR','PA','SC','TN','TX','UT','WA','WI','WV') THEN SUBSTR(CABS0.CIRCUIT_NO,18,2)
                WHEN CABS0.STATE_CD IS NULL OR CABS0.EO_CLLI_CD IS NULL OR CABS0.POP_CLLI_CD IS NULL OR CABS0.CIRCUIT_NO IS NULL THEN 'OTHER'
                ELSE 'OTHER'
            END AS STATE,
            CABS0.BILL_MONTH_DT
        FROM
            edw_vwmc.CABS_SPCL_ACCS_BILL_REV_DTL_V CABS0
        WHERE
            CABS0.BILL_MONTH_DT > DATEADD(YEAR, -2, GETDATE()) -- Changed to select data from the past two years
            AND (CABS0.SW_SPL_IND = 'SP' OR SUBSTR(CABS0.NC_PRODUCT_CD,1,4) IN ('COLL','COLO'))
    ) SUBQ1
    JOIN edw_vwmc.CABS_SPCL_ACCS_BILL_REV_DTL_V CABS ON CABSSP.CIRCUIT_NO = CABS.CIRCUIT_NO AND CABSSP.CMPY_NO = CABS.CMPY_NO
) SUBQ2
WHERE
    ROWNUM = 1 -- Selecting only distinct rows
ORDER BY
    CLEAN_ID, BILL_MONTH_DT; */