CREATE PROCEDURE [LZ].[usp_TBL_MCL_UPLOAD]
/*
	-- Add any parameters for the stored procedure here
	@var1 int,
	@var2 int
*/
AS
	SET XACT_ABORT, NOCOUNT ON;
BEGIN TRY
	BEGIN TRANSACTION
	DROP TABLE IF EXISTS #t
INSERT INTO [LOG].tbl_StoreProc
    ([EVENTNAME]
    ,[EVENTSTART]
    ,[EVENTTYPE]
    ,[EVENTDESCRIPTION])

--enter values below

VALUES
('LZ.TBL_MCL_UPLOAD'
    ,CAST(GETDATE() AS DATETIME)
    ,'STORE PROC'
    ,'SINGLE_INGESTION')



SELECT MAX(EVENTID) AS LATESTID  INTO #t
FROM [LOG].tbl_StoreProc


truncate table LZ.TBL_MCL_UPLOAD --Cannot truncate system versioned table

insert INTO LZ.TBL_MCL_UPLOAD
SELECT A.*,CAST(GETDATE() as DATE) as UPDATE_DT, CURRENT_TIMESTAMP AS UPLOAD_TS


FROM OPENROWSET('Microsoft.ACE.OLEDB.12.0', 
   'Excel 12.0;Database=D:\LZ\MCL\UPLOAD.XLSX;HDR=YES', 
   'SELECT * FROM [FTR MCL$]')A

   --INSERT INTO HISTORICAL TRACKED TABLE
INSERT INTO dbo.TBL_MCL_HIST
SELECT * FROM LZ.TBL_MCL_UPLOAD


DELETE  EDW..USER_WORK.TBL_MCL;

INSERT INTO EDW..USER_WORK.TBL_MCL

SELECT 

[SECONDARY_ID_SOURCE]
      ,[PRIMARY_ID_SOURCE]
      ,[PRIMARY_ID]
      ,[PRIMARY_CARRIER_NM]
      ,[PRIMARY_FOCUS]
      ,[ID_TYPE]
      ,[SECONDARY_ID]
      ,[SECONDARY_CARRIER_NM]
      ,[VP]
      ,[Column1]
      ,[SLS_DIR]
      ,[AE_SR]
      ,[AE_2]
      ,[AE]
      ,[SLS_ENGR]
FROM WAD_PRD_02.dbo.TBL_MCL_HIST

where upload_ts = (select max(upload_ts) from dbo.TBL_MCL_HIST)

	
	
UPDATE L
SET L.EVENTEND=CAST(GETDATE() AS DATETIME)
FROM LOG.tbl_StoreProc L
INNER JOIN #t
ON L.EVENTID = #t.LATESTID
DROP TABLE IF EXISTS #t


	
	COMMIT TRANSACTION
END TRY
BEGIN CATCH
	IF @@trancount > 0 ROLLBACK TRANSACTION
	EXEC usp_error_handler
	RETURN 55555
END CATCH
GO