version: '3.8'
services:
  api:
    build: .
    volumes:
      - ./:/app
    ports:
      - "8000:8000"
    env_file: .env.dev
    depends_on:
      - elasticsearch
      - redis

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.9.0
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - "9200:9200"

