services:
  - type: web
    name: ConnectbaseAPI
    env: python
    plan: free
    repo: https://github.com/onlymiraz/boilerplate
    branch: master
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn backend.app:app --host 0.0.0.0 --port 8000
    envVars:
      - key: OPENAI_API_KEY
        fromDatabase: RENDER  
      - key: ELASTICSEARCH_URL
        value: http://elasticsearch:9200
      - key: REDIS_URL
        value: redis://redis:6379/0
