ALTER SERVER ROLE [sysadmin] ADD MEMBER [CORP\taw330];


GO
ALTER SERVER ROLE [sysadmin] ADD MEMBER [CORP\mmm722];


GO
ALTER SERVER ROLE [sysadmin] ADD MEMBER [CORP\bbb724];


GO
ALTER SERVER ROLE [sysadmin] ADD MEMBER [NT SERVICE\SQLWriter];


GO
ALTER SERVER ROLE [sysadmin] ADD MEMBER [NT SERVICE\Winmgmt];


GO
ALTER SERVER ROLE [sysadmin] ADD MEMBER [NT SERVICE\MSSQLSERVER];


GO
ALTER SERVER ROLE [sysadmin] ADD MEMBER [NT SERVICE\SQLSERVERAGENT];


GO
ALTER SERVER ROLE [sysadmin] ADD MEMBER [CORP\WAD_DevOps];


GO
ALTER SERVER ROLE [sysadmin] ADD MEMBER [CORP\s_prod_tfssvc];


GO
ALTER SERVER ROLE [sysadmin] ADD MEMBER [CORP\s_WAD];


GO
ALTER SERVER ROLE [sysadmin] ADD MEMBER [CORP\s_WAD0];


GO
ALTER SERVER ROLE [sysadmin] ADD MEMBER [CORP\s_WAD1];


GO
ALTER SERVER ROLE [sysadmin] ADD MEMBER [CORP\s_WAD2];


GO
ALTER SERVER ROLE [sysadmin] ADD MEMBER [CORP\s_WAD3];


GO
ALTER SERVER ROLE [sysadmin] ADD MEMBER [CORP\s_WAD4];


GO
ALTER SERVER ROLE [sysadmin] ADD MEMBER [CORP\sbb217];


GO
ALTER SERVER ROLE [securityadmin] ADD MEMBER [CORP\s_WAD];


GO
ALTER SERVER ROLE [serveradmin] ADD MEMBER [CORP\s_WAD];


GO
ALTER SERVER ROLE [setupadmin] ADD MEMBER [CORP\s_WAD];


GO
ALTER SERVER ROLE [processadmin] ADD MEMBER [CORP\s_WAD];


GO
ALTER SERVER ROLE [diskadmin] ADD MEMBER [CORP\s_WAD];


GO
ALTER SERVER ROLE [dbcreator] ADD MEMBER [CORP\s_WAD];


GO
ALTER SERVER ROLE [bulkadmin] ADD MEMBER [CORP\s_WAD];


GO
ALTER ROLE [db_owner] ADD MEMBER [CORP\WAD_DevOps];


GO
ALTER ROLE [db_owner] ADD MEMBER [CORP\s_prod_tfssvc];


GO
ALTER ROLE [db_owner] ADD MEMBER [CORP\s_WAD];


GO
ALTER ROLE [db_owner] ADD MEMBER [CORP\s_WAD0];


GO
ALTER ROLE [db_owner] ADD MEMBER [CORP\s_WAD1];


GO
ALTER ROLE [db_owner] ADD MEMBER [CORP\s_WAD2];


GO
ALTER ROLE [db_owner] ADD MEMBER [CORP\s_WAD3];


GO
ALTER ROLE [db_owner] ADD MEMBER [CORP\s_WAD4];

