ALTER SERVER ROLE [sysadmin] ADD MEMBER [CORP\taw330];


GO
ALTER SERVER ROLE [sysadmin] ADD MEMBER [CORP\WAD_DevOps];


GO
ALTER SERVER ROLE [sysadmin] ADD MEMBER [NT SERVICE\SQLWriter];


GO
ALTER SERVER ROLE [sysadmin] ADD MEMBER [NT SERVICE\Winmgmt];


GO
ALTER SERVER ROLE [sysadmin] ADD MEMBER [NT SERVICE\MSSQLSERVER];


GO
ALTER SERVER ROLE [sysadmin] ADD MEMBER [NT SERVICE\SQLSERVERAGENT];


GO
ALTER SERVER ROLE [sysadmin] ADD MEMBER [CORP\s_WAD];


GO
ALTER SERVER ROLE [sysadmin] ADD MEMBER [CORP\s_WAD0];


GO
ALTER SERVER ROLE [sysadmin] ADD MEMBER [CORP\s_WAD1];


GO
ALTER SERVER ROLE [sysadmin] ADD MEMBER [CORP\s_WAD2];


GO
ALTER SERVER ROLE [sysadmin] ADD MEMBER [CORP\s_WAD3];


GO
ALTER SERVER ROLE [sysadmin] ADD MEMBER [CORP\s_WAD4];


GO
ALTER SERVER ROLE [sysadmin] ADD MEMBER [CORP\s_prod_tfssvc];


GO
ALTER ROLE [db_owner] ADD MEMBER [CORP\s_WAD0];


GO
ALTER ROLE [db_owner] ADD MEMBER [CORP\s_WAD1];


GO
ALTER ROLE [db_owner] ADD MEMBER [CORP\s_WAD2];


GO
ALTER ROLE [db_owner] ADD MEMBER [CORP\s_WAD3];


GO
ALTER ROLE [db_owner] ADD MEMBER [CORP\s_WAD4];


GO
ALTER ROLE [db_owner] ADD MEMBER [CORP\s_prod_tfssvc];


GO
ALTER ROLE [db_owner] ADD MEMBER [CORP\WAD_DevOps];

