CREATE VIEW WCF.[REV_BY_PROD_V]
	AS 


SELECT
A.*
,SUM(A.VOICE_LINES) OVER(PARTITION BY RPT_MTH, WIRECENTER,WCF_PRD_TYPE) AS WC_VOICE_LINES
,SUM(A.MRC) OVER(PARTITION BY RPT_MTH, WIRECENTER,WCF_PRD_TYPE) AS WC_TOTAL_MRC
,CASE WHEN A.VOICE_LINES = 0 THEN NULL ELSE A.VOICE_LINES END *1.0000/SUM(A.TOTAL_LINES) OVER(PARTITION BY RPT_MTH, WIRECENTER) AS WC_VOICE_LINES_PCT
,CASE WHEN A.MRC = 0 THEN NULL ELSE A.MRC END*1.0000/SUM(A.MRC) OVER(PARTITION BY RPT_MTH, WIRECENTER) AS WC_MRC_PCT
,SUM(A.TOTAL_LINES) OVER(PARTITION BY RPT_MTH, STATE) AS ST_VOICE_LINES
,SUM(A.MRC) OVER(PARTITION BY RPT_MTH, STATE) AS ST_TOTAL_MRC
,CASE WHEN A.VOICE_LINES = 0 THEN NULL ELSE A.VOICE_LINES END *1.0000/SUM(A.VOICE_LINES) OVER(PARTITION BY RPT_MTH, STATE) AS ST_VOICE_LINES_PCT
,CASE WHEN A.DATA_LINES = 0 THEN NULL ELSE A.DATA_LINES END *1.0000/SUM(A.DATA_LINES) OVER(PARTITION BY RPT_MTH, STATE) AS ST_DATA_LINES_PCT
,CASE WHEN A.VOICE_LINES = 0 THEN NULL ELSE A.VOICE_LINES END *1.0000/SUM(A.VOICE_LINES) OVER(PARTITION BY RPT_MTH) AS NTL_VOICE_LINES_PCT
,CASE WHEN A.DATA_LINES = 0 THEN NULL ELSE A.DATA_LINES END *1.0000/SUM(A.DATA_LINES) OVER(PARTITION BY RPT_MTH) AS NTL_DATA_LINES_PCT



FROM(
select 
RPT_MTH
,WIRECENTER
,WCF_PRD_TYPE
,DSAT.STATE
,SUM(VOICE_LINES) AS VOICE_LINES
,SUM(DATA_LINES) AS DATA_LINES
,SUM(VOICE_LINES) +SUM(DATA_LINES) as TOTAL_LINES -- NEED CHRIS' SIGN OFF
,SUM(MRC) AS MRC


FROM WCF.TBL_REV_BY_PROD rev
INNER join dbo.DSAT_MATRIX_V dsat
on rev.WIRECENTER = dsat.WIRECENTERCLLi

WHERE WIRECENTER IS NOT NULL

GROUP BY RPT_MTH,WIRECENTER,WCF_PRD_TYPE,DSAT.STATE
)A
