CREATE TABLE [TOWERS_UNIVERSE].[TBL_DSAT_MATRIX] (
    [LOCATION_ID]             FLOAT (53)     NULL,
    [state]                   NVARCHAR (255) NULL,
    [lata]                    NVARCHAR (255) NULL,
    [localAreaMarket]         NVARCHAR (255) NULL,
    [wireCenterClli]          NVARCHAR (255) NULL,
    [wireCenterName]          NVARCHAR (255) NULL,
    [eia]                     NVARCHAR (255) NULL,
    [eReachPath]              NVARCHAR (255) NULL,
    [ipvpn]                   NVARCHAR (255) NULL,
    [voip]                    NVARCHAR (255) NULL,
    [metroE]                  NVARCHAR (255) NULL,
    [approvedAccessElement]   NVARCHAR (255) NULL,
    [jumboFrames]             NVARCHAR (255) NULL,
    [maximumSpeed]            NVARCHAR (255) NULL,
    [maximumQualityOfService] NVARCHAR (255) NULL,
    [carRouterClli]           NVARCHAR (255) NULL,
    [carLocation]             NVARCHAR (255) NULL,
    [perCarRouterCLLI]        NVARCHAR (255) NULL,
    [futureHbeWcSpeed]        NVARCHAR (255) NULL,
    [plannedHbeTimeframe]     NVARCHAR (255) NULL,
    [HBE_EIA]                 NVARCHAR (255) NULL,
    [HBE_Evpl]                NVARCHAR (255) NULL,
    [HBE_Inni_L2]             NVARCHAR (255) NULL,
    [HBE_Jumbo_Frames]        NVARCHAR (255) NULL,
    [HBE_Max_QoS]             NVARCHAR (255) NULL,
    [HBE_Max_Speed]           NVARCHAR (255) NULL,
    [INNI L2]                 NVARCHAR (255) NULL,
    [INNI L3]                 NVARCHAR (255) NULL,
    [Market]                  NVARCHAR (255) NULL,
    [Level]                   NVARCHAR (255) NULL,
    [Lit_Building]            NVARCHAR (255) NULL,
    [AddrLn1]                 NVARCHAR (255) NULL,
    [AddrLn2]                 NVARCHAR (255) NULL,
    [AddrLn3]                 NVARCHAR (255) NULL,
    [AddrLn4]                 NVARCHAR (255) NULL,
    [AddrLn5]                 NVARCHAR (255) NULL,
    [AddrLn6]                 NVARCHAR (255) NULL,
    [AddrLn7]                 NVARCHAR (255) NULL,
    [INSERT_TS]               DATETIME       NOT NULL
);

