CREATE TABLE QBR.[TBL_JEOPARDY_TYPE]
(
    [JEOPARDY_REASON_CODE] varchar(4),
    [JEOPARDY_REASON_DESCRIPTION] varchar(79),
    [LAST_MODIFIED_USERID] varchar(8),
    [LAST_MODIFIED_DATE] datetime,
    [TRANSACTION_ORIGIN] varchar(8),
    [JEOPARDY_TYPE_CD] varchar(1),
    [ACTIVE_IND] varchar(1)
)
