CREATE TABLE QBR.[TBL_VFO_PONS]
(
[DOCNO] [varchar](15) NOT NULL,
	[REQ] [varchar](1) NULL,
	[ACT] [varchar](1) NULL,
	[BUILD] [varchar](25) NULL,
	[BUILD_IOF] [varchar](255) NULL,
	[BUILD_OSP] [varchar](255) NULL,
	[INIT] [datetime] NULL,
	[CLEAN] [datetime] NULL,
	[DD] [datetime] NULL,
	[COMP_DT] [datetime] NULL,
	[DD_COMP] [datetime] NULL,
	[NC] [varchar](5) NULL,
	[PROD] [varchar](15) NULL,
	[PNUM] [varchar](20) NULL,
	[PON] [varchar](20) NULL,
	[CKT] [varchar](60) NULL,
	[ICSC] [varchar](5) NULL,
	[ACNA] [varchar](5) NULL,
	[WHY_MISS1] [varchar](5) NULL,
	[MISS_REASON1] [varchar](125) NULL,
	[PROJ] [varchar](20) NULL,
	[STATE] [varchar](2) NULL,
	[REGION] [varchar](7) NULL,
	[PRODUCT] [varchar](22) NULL,
	[PRODUCT2] [varchar](8) NULL,
	[SEI] [varchar](1) NULL,
	[BDW] [varchar](4) NULL,
	[DD_MET] [float] NULL,
	[DLR] [varchar](3) NULL,
	UPDATE_DT DATE
)
