CREATE TABLE QBR.[TBL_NCFR]
(
    [DOCUMENT_NUMBER] varchar(255),
    [PON] varchar(255),
    [ACT_IND] varchar(255),
    [COMP_DT] datetime,
    [DD_TASK_COMP] datetime,
    [NPANXX] varchar(255),
    [CLLI] varchar(255),
    [ICSC] varchar(255),
    [AREA] varchar(6),
    [ACNA] varchar(255),
    [CUSTOMER] varchar(255),
    [REGION] varchar(255),
    [TERRITORY] varchar(255),
    [LAM] varchar(255),
    [STATE] varchar(255),
    [PRODUCT] varchar(255),
    [CKT] varchar(255),
    [TICKET_ID] varchar(15),
    [ASSIGNMENTPROFILE] varchar(30),
    [REPAIR_CODE] varchar(255),
    [DISP] varchar(255),
    [TRBL_CREATE_DATE] datetime,
    [TRBL_CLEARED_DT] datetime,
    [TRBL_CLOSED_DT] datetime,
    [MON] float,
    UPDATE_DT DATETIME2
)
