CREATE TABLE [LZ].[TBL_MCL_UPLOAD] (
    [SECONDARY ID SOURCE]    NVARCHAR (255) NULL,
    [PRIMARY ID SOURCE]      NVARCHAR (255) NULL,
    [PRIMARY ID]             NVARCHAR (255) NULL,
    [PRIMARY CARRIER NAME]   NVARCHAR (255) NULL,
    [PRIMARY FOCUS]          NVARCHAR (255) NULL,
    [ID TYPE]                NVARCHAR (255) NULL,
    [SECONDARY ID]           NVARCHAR (255) NULL,
    [SECONDARY CARRIER NAME] NVARCHAR (255) NULL,
    [VP]                     NVARCHAR (255) NULL,
    [Column1]                NVARCHAR (255) NULL,
    [SALES DIRECTOR]         NVARCHAR (255) NULL,
    [ACCT EXECUTIVE SR]      NVARCHAR (255) NULL,
    [ACCT EXECUTIVE 2]       NVARCHAR (255) NULL,
    [ACCT EXECUTIVE]         NVARCHAR (255) NULL,
    [SALES ENGINEER]         NVARCHAR (255) NULL,
    [CHECK]                  NVARCHAR (255) NULL,
    [UPDATE_DT]              DATETIME       NULL,
    [UPLOAD_TS]              DATETIME       NOT NULL
);

