CREATE TABLE [LZ].[TBL_DELAY_ORDERS] (
    [DOCUMENT_NUMBER]  VARCHAR (25)   NOT NULL,
    [NOTES_ID]         VARCHAR (100)  NULL,
    [NOTE_TEXT]        VARCHAR (2500) NULL,
    [USER_ID]          VARCHAR (50)   NULL,
    [LAST_MODIFIED_DT] DATE           NULL,
    [ACNA]             VARCHAR (10)   NULL,
    [COMP_DT]          DATE           NULL,
    PRIMARY KEY CLUSTERED ([DOCUMENT_NUMBER] ASC)
);

