CREATE TABLE [LZ].[TBL_WHSL_ADV_HIST_VFO_ORDERHISTORYINFO_THIST] (
    [ORDERHISTORYINFOID]            FLOAT (53)    NULL,
    [CUSTOMERNAME]                  VARCHAR (50)  NULL,
    [ISCCODE]                       VARCHAR (50)  NULL,
    [ACTIVITY]                      VARCHAR (30)  NULL,
    [REQTYPE]                       VARCHAR (20)  NULL,
    [PON]                           VARCHAR (25)  NULL,
    [VERSION]                       VARCHAR (10)  NULL,
    [ORDERSTATUS]                   VARCHAR (100) NULL,
    [INITIATORNAME]                 VARCHAR (30)  NULL,
    [DUEDATE]                       VARCHAR (30)  NULL,
    [ESPID]                         FLOAT (53)    NULL,
    [WISORUSERID]                   VARCHAR (30)  NULL,
    [CREATIONDATETIME]              DATETIME      NULL,
    [UPDATEDATETIME]                DATETIME      NULL,
    [TN]                            VARCHAR (10)  NULL,
    [STATE]                         VARCHAR (2)   NULL,
    [SUPPTYPE]                      VARCHAR (2)   NULL,
    [ORDERXMLDATAID]                FLOAT (53)    NULL,
    [SERVICEREQUESTTYPE]            VARCHAR (30)  NULL,
    [SUBMITTEDDATETIME]             DATETIME      NULL,
    [SERVICETYPE]                   VARCHAR (100) NULL,
    [CCNA]                          VARCHAR (50)  NULL,
    [GUIDELINEVERSION]              VARCHAR (10)  NULL,
    [TRADINGPARTNERNAME]            VARCHAR (100) NULL,
    [TRANSMISSIONTYPE]              VARCHAR (30)  NULL,
    [DIRECTION]                     VARCHAR (10)  NULL,
    [MANAGINGESPID]                 FLOAT (53)    NULL,
    [INACTIVE_INDICATOR]            VARCHAR (10)  NULL,
    [CC]                            VARCHAR (20)  NULL,
    [REQUESTSTATE]                  VARCHAR (50)  NULL,
    [FOCFDD]                        VARCHAR (50)  NULL,
    [FOCDD]                         VARCHAR (50)  NULL,
    [FOCORD]                        VARCHAR (50)  NULL,
    [CDDATE]                        VARCHAR (50)  NULL,
    [PCNDATE]                       VARCHAR (50)  NULL,
    [BCNDATE]                       VARCHAR (50)  NULL,
    [PARTITIONKEYDATETIME]          DATETIME      NULL,
    [APPLICATIONID]                 VARCHAR (30)  NULL,
    [DATETIMESTAMP]                 DATETIME      NULL,
    [ORDERINITIATOR]                VARCHAR (30)  NULL,
    [ORDERLASTUPDATEDBY]            VARCHAR (30)  NULL,
    [INTERNALTRACKID]               VARCHAR (50)  NULL,
    [RESTRICTMANAGEDESP]            VARCHAR (50)  NULL,
    [SRC_CMMT_TS]                   DATETIME      NULL,
    [SRC_ACTN_CD]                   VARCHAR (1)   NULL,
    [DW_INSRT_TS]                   DATETIME      NULL,
    [SRC_COMMIT_SCN]                NUMERIC (38)  NULL,
    [SRC_LOGRBA]                    NUMERIC (38)  NULL,
    [SRC_LOGPOSITION]               NUMERIC (38)  NULL,
    [STG_IDENT]                     FLOAT (53)    NULL,
    [MESSAGEID]                     VARCHAR (25)  NULL,
    [POTYPE]                        VARCHAR (20)  NULL,
    [FORMSECTION]                   VARCHAR (250) NULL,
    [PREORDERINFOID]                FLOAT (53)    NULL,
    [TEMP_MIGRATED_ORDERHISTINFOID] FLOAT (53)    NULL,
    [LOCKORCLOCKSTATUS]             VARCHAR (25)  NULL,
    [TOS]                           VARCHAR (200) NULL,
    [STYC]                          VARCHAR (200) NULL,
    [RTY]                           VARCHAR (200) NULL,
    [NOTIFYRESPONSECODE]            VARCHAR (25)  NULL,
    [SLAFILTERCRITERIA]             VARCHAR (50)  NULL,
    [ACKNOWDLEDGEMENTTIMESTAMP]     DATETIME      NULL,
    [LOCKEDDATETIME]                DATETIME      NULL,
    [RESPONSERECEIVED]              VARCHAR (10)  NULL,
    [GG_READ_DATE]                  DATETIME      NULL,
    [SENSITIVEPON]                  VARCHAR (30)  NULL,
    [ASR_PROJECT]                   VARCHAR (25)  NULL,
    [ISORDERREADONLY]               VARCHAR (10)  NULL
);

