CREATE VIEW [dbo].[CABS_CIRCUIT_USOC_DETAIL_V]
	AS 
SELECT
CASE WHEN REPLACE(REPLACE(REPLACE(CABS.CIRCUIT_NO,'.',''),'-',''),' ','') IN ('81HCGS739897GTEW','603T3ZKLLRTXXASOLKTXESH31') THEN 'VERIZON' ELSE mcl.PRIMARY_CARRIER_NM END AS PRIMARY_CARRIER_NM  --THIS CLAUSE FOR THE 2 IDs added due to showing as ZZZ.
,CASE WHEN MCL.PRIMARY_FOCUS = 'WIRELESS' THEN 'WIRELESS' ELSE 'WIRELINE' END AS WIRE_TYPE_IND
,REPLACE(REPLACE(REPLACE(CABS.CIRCUIT_NO,'.',''),'-',''),' ','')AS CLEAN_ID --SSMS LOGIC
,CABS.*
,CASE
    WHEN SUBSTRING(NC_PRODUCT_CD,1,2) in ('KE','KF','KG','KJ','KQ','KP','KR','KS','KU','VL') AND SUBSTRING(NC_PRODUCT_CD,3,1) = 'L' THEN 'ETHERNET - DEDICATED'
 WHEN SUBSTRING(NC_PRODUCT_CD,1,2) in ('KE','KF','KG','KJ','KQ','KP','KR','KS','KU','VL') THEN 'ETHERNET' --WAD_940 FROM JW AND modified 2/3/25 that if 3rd spot is L that it is ETHERNET - DEDICATED
 WHEN SUBSTRING(cabs.NC_PRODUCT_CD,1,2) ='HF' AND SUBSTRING(cabs.NC_PRODUCT_CD,4,1) NOT IN ('-',' ') 
       AND LEN(cabs.NC_PRODUCT_CD)= 4 THEN 'TDM_DS3_mux'
     WHEN SUBSTRING(cabs.NC_PRODUCT_CD,1,2) ='HC' AND SUBSTRING(cabs.NC_PRODUCT_CD,4,1) NOT IN ('-',' ') 
       AND LEN(cabs.NC_PRODUCT_CD)= 4 THEN 'TDM_DS1_mux'
     WHEN SUBSTRING(cabs.NC_PRODUCT_CD,1,2) ='HF' AND LEN(CABS.CIRCUIT_NO) > 27 THEN 'TDM_DS3_noEU'
     WHEN SUBSTRING(cabs.NC_PRODUCT_CD,1,2) ='HC' AND LEN(CABS.CIRCUIT_NO) > 27 THEN 'TDM_DS1_noEU'
     WHEN SUBSTRING(cabs.NC_PRODUCT_CD,1,2) ='HF' THEN 'TDM_DS3'
     WHEN SUBSTRING(cabs.NC_PRODUCT_CD,1,2) ='HC' THEN 'TDM_DS1'
     
     WHEN SUBSTRING(CABS.NC_PRODUCT_CD,1,4) IN ('COLL','COLO') THEN 'COLO'
     WHEN SUBSTRING(CABS.PLAN_ID,1,3) = 'DKF' THEN 'DKF'
     ELSE SUBSTRING(CABS.CIRCUIT_NO, CHARINDEX('.', CABS.CIRCUIT_NO) + 1, 2)
     END AS PROD_TYPE
,XREF.SUMMARIZED_PRODUCT
,CASE WHEN CHARINDEX('-', CABS.PLAN_ID) > 0 THEN SUBSTRING(CABS.PLAN_ID, 1, CHARINDEX('-', CABS.PLAN_ID) - 1) 
  ELSE NULL 
  END as PLAN_ID_PNUM
,CASE WHEN (SUBSTRING(cabs.PLAN_ID,1,3) IN ('DKF','EDC','EDG','EOS','SEW')
        OR SUBSTRING(cabs.PLAN_ID,1,4) IN ('EIAV','EPAV','FOTW')
        OR SUBSTRING(cabs.PLAN_ID,1,5) IN ('FOTSV')
        OR SUBSTRING(cabs.PLAN_ID,1,6) IN ('FBATTM','FLATFB','PCFICB'))
     THEN 'NEW' ELSE 'OTHER' END AS PNUM_GRP
,SUM(CHRGE_AMT) OVER (PARTITION BY CIRCUIT_NO,SW_SPL_IND,NC_PRODUCT_CD,USOC_PRODUCT_CD,JURIS_CD,BILL_MONTH_DT ORDER BY BILL_MONTH_DT asc) AS CURR_BILL
--,LAG(CHRGE_AMT) OVER (PARTITION BY CIRCUIT_NO,SW_SPL_IND,NC_PRODUCT_CD,USOC_PRODUCT_CD,JURIS_CD ORDER BY BILL_MONTH_DT asc) AS PRIOR_BILL
--,CASE WHEN LAG(CHRGE_AMT) OVER (PARTITION BY CIRCUIT_NO,SW_SPL_IND,NC_PRODUCT_CD,USOC_PRODUCT_CD,JURIS_CD ORDER BY BILL_MONTH_DT asc) = 0 THEN NULL ELSE (SUM(CHRGE_AMT) OVER (PARTITION BY CIRCUIT_NO,SW_SPL_IND,NC_PRODUCT_CD,USOC_PRODUCT_CD,JURIS_CD,BILL_MONTH_DT ORDER BY BILL_MONTH_DT asc) *1.0000/LAG(CHRGE_AMT) OVER (PARTITION BY CIRCUIT_NO,SW_SPL_IND,NC_PRODUCT_CD,USOC_PRODUCT_CD,JURIS_CD ORDER BY BILL_MONTH_DT asc)) -1 END AS MOM  --logic to look into prior BDS POSSIBILITIES
,CASE WHEN BO.COMPANY IS NOT NULL THEN 'Y' ELSE 'N' END AS BACKOUT_IND

FROM EDW_VWMC.TBL_CABS_SPCL_ACCS_BILL_REV_DTL CABS

LEFT JOIN dbo.MCL_V AS MCL 
ON MCL.SECONDARY_ID = CABS.ACNA
AND ID_TYPE = 'ACNA'

left join dbo.TBL_BACKOUT_REPORT_HIST bo
on CABS.CMPY_NO = BO.Company
AND CABS.IXC_NO = BO.IXC
AND CABS.FEATR_GRP_CD = BO.FG
AND CABS.BILL_MONTH_DT = BO.RPT_MTH

LEFT JOIN DBO.DS0_DS1_XREF XREF
ON SUBSTRING(NC_PRODUCT_CD,1,2) = XREF.NC_POS_1_2
AND CABS.CLASS_OF_SERVICE = XREF.CABS_CLASS_OF_SERVICE

WHERE 1=1
--AND YEAR(CABS.BILL_MONTH_DT)>= 2024
--AND (CABS.SW_SPL_IND = 'SP' OR SUBSTRING(CABS.NC_PRODUCT_CD,1,4) IN ('COLL','COLO') OR SUBSTRING(CABS.PLAN_ID,1,3) = 'DKF')
AND (CABS.DISCONNECT_DT > CABS.BILL_CYCLE_DT OR CABS.DISCONNECT_DT IS NULL) 
AND CABS.CMPY_NO NOT IN ('0570','0572','0576','6102','6105','6106') -- EXCLUDE NWF COMPANY CODES
AND CASE WHEN REPLACE(REPLACE(REPLACE(CABS.CIRCUIT_NO,'.',''),'-',''),' ','') IN ('81HCGS739897GTEW','603T3ZKLLRTXXASOLKTXESH31') THEN 'VERIZON' ELSE mcl.PRIMARY_CARRIER_NM END IS NOT NULL --WOULD GENERALLY DUE INNER JOIN ON MCL, BUT CAN'T DUE TO ZZZ ACNA FOR SOME VZ



