CREATE VIEW [dbo].[CB_MS_XREF_V] AS
SELECT 
PRIMARY_CARRIER_NM
,COMBINED_ACNA
,CONCAT(REF_1,CASE WHEN REF_2 IS NOT NULL THEN CONCAT('|',REF_2) ELSE NULL END
	,CASE WHEN REF_3 IS NOT NULL THEN CONCAT('|',REF_3) ELSE NULL END
	,CASE WHEN REF_4 IS NOT NULL THEN CONCAT('|',REF_4) ELSE NULL END
	,CASE WHEN REF_5 IS NOT NULL THEN CONCAT('|',REF_5) ELSE NULL END)
	AS SEARCH_COMPANIES

FROM DBO.CB_MS_XREF