CREATE VIEW M6_CIRCUIT_INVENTORY_SITE_MAPPING_V
AS
SELECT 
    pvt.EXCHANGE_CARRIER_CIRCUIT_ID AS EXCHANGE_CARRIER_CIRCUIT_ID,
    pvt.CLEAN_ID AS CLEAN_ID,
    pvt.STATUS AS STATUS,
    pvt.SERVICE_TYPE_CODE AS SERVICE_TYPE_CODE,
    pvt.ACNA AS ACNA,
	--pvt.IN_SERVICE_DATE AS IN_SERVICE_DATE,
	--pvt.DD_COMPLETION_DATE AS DD_COMPLETION_DATE,
    pvt."1" AS CELL_SITE_1,
    pvt."2" AS CELL_SITE_2,
    pvt."3" AS CELL_SITE_3,
    pvt."4" AS CELL_SITE_4,
    pvt."5" AS CELL_SITE_5,
    pvt."6" AS CELL_SITE_6,
    pvt."7" AS CELL_SITE_7,
    pvt."8" AS CELL_SITE_8,
    pvt."9" AS CELL_SITE_9,
    pvt."10" AS CELL_SITE_10
FROM (
    SELECT 
        EXCHANGE_CARRIER_CIRCUIT_ID,
        CLEAN_ID,
        STATUS,
        SERVICE_TYPE_CODE,
        ACNA,
		--IN_SERVICE_DATE,
		--DD_COMPLETION_DATE,
        SITE_ID,
        ROW_NUMBER() OVER (PARTITION BY CLEAN_ID ORDER BY SITE_ID DESC) AS rn
    FROM dbo.M6_CIRCUIT_INVENTORY_SITE_MAPPING
    WHERE ACNA IS NOT NULL
) AS source
PIVOT (
    MIN(SITE_ID)
    FOR rn IN ("1", "2", "3", "4", "5", "6", "7", "8", "9", "10")
) AS pvt
