CREATE VIEW [dbo].[TBL_WIRELINE_SLS_DISCONNECTS_V] AS 
SELECT 
	A.*,
	B.MRC AS LAST_BILL_MRC,
	B.BILL_MONTH_DT AS LAST_BILL_MONTH
 
 from
 dbo.TBL_WIRELINE_SLS_DISCONNECTS A
LEFT JOIN(
SELECT
BILL_MONTH_DT,CLEAN_ID,SUM(CHRGE_AMT) AS MRC,
ROW_NUMBER() OVER(PARTITION BY CLEAN_ID ORDER BY BILL_MONTH_DT DESC) AS RN
 
FROM DBO.CABS_CIRCUIT_USOC_DETAIL_V GROUP BY BILL_MONTH_DT,CLEAN_ID)B
ON A.CLEAN_ID = B.CLEAN_ID
AND RN = 1
GO
