CREATE TABLE CB_MS.[TBL_CB_MS_COMBINED]
(
[ID] [nvarchar](15) NULL,
	LOGIN_ID [nvarchar](75) NULL,
	[ROUTE_NAME] [nvarchar](40) NULL,
	[REQUESTING_COMPANY] [nvarchar](75) NULL,
	[CLIENT_COMPANY] [nvarchar](75) NULL,
	[CCNA_X] [nvarchar](10) NULL,
	[ADDRESS] [nvarchar](255) NULL,
	[CITY] [nvarchar](80) NULL,
	[STATE] [nvarchar](255) NULL,
	[ZIP] [nvarchar](35) NULL,
	[COUNTY] [nvarchar](35) NULL,
	[COUNTRY] [nvarchar](50) NULL,
	[USER_COMPANY] [nvarchar](75) NULL,
	[TARGET_COMPANY_ID] [nvarchar](10) NULL,
	[TARGET_COMPANY] [nvarchar](75) NULL,
	[REQUEST_DATE] datetime2 NULL,
	[RESULT] [nvarchar](2) NULL,
	[SERVICENAME] [nvarchar](50) NULL,
	SERVICE_TYPE [nvarchar](75) NULL,
	[ERROR_MESSAGE] [nvarchar](255) NULL,
	[TERMS] [nvarchar](25) NULL,
	FILE_NAME [nvarchar](75) NULL,
	UPDATED_DT DATE
)
