CREATE TABLE [ExpenseForecast].[Raw_GLExpense] (
    [TXCO]     VARCHAR (10)  NULL,
    [CTACCT]   VARCHAR (50)  NULL,
    [PROJ]     VARCHAR (10)  NULL,
    [SUBPRJ]   VARCHAR (10)  NULL,
    [MAINTSK]  VARCHAR (10)  NULL,
    [SUBTSK]   VARCHAR (10)  NULL,
    [MATRIX]   VARCHAR (10)  NULL,
    [AMOUNT]   VARCHAR (25)  NULL,
    [YEAR]     VARCHAR (10)  NULL,
    [MONTH]    VARCHAR (10)  NULL,
    [OPERAREA] VARCHAR (10)  NULL,
    [JOURNAL]  VARCHAR (15)  NULL,
    [TXDESC]   VARCHAR (200) NULL,
    [CMTH]     VARCHAR (10)  NULL,
    [CYR]      VARCHAR (10)  NULL,
    [VEND#]    VARCHAR (50)  NULL,
    [VOUCHER#] VARCHAR (100) NULL,
    [INVOICE#] VARCHAR (100) NULL
);

