USE CapitalManagementStaging
GO

EXEC(
	'ALTER TABLE CapitalManagementProduction.forecast.GrossAddsDirect NOCHECK CONSTRAINT FK_GrossAddsDirect_Subproject
	ALTER TABLE CapitalManagementProduction.forecast.GrossAddsIndirect NOCHECK CONSTRAINT FK_GrossAddsIndirect_Project
	ALTER TABLE CapitalManagementProduction.forecast.GrossAddsIndirect NOCHECK CONSTRAINT FK_GrossAddsIndirect_Subproject
	ALTER TABLE CapitalManagementProduction.forecast.SubprojectAuthorized NOCHECK CONSTRAINT FK_SubprojectAuthorized_Subproject
	ALTER TABLE CapitalManagementProduction.forecast.SubprojectCIAC NOCHECK CONSTRAINT FK_SubprojectCIAC_Subproject
	ALTER TABLE CapitalManagementProduction.forecast.SubprojectFinancial NOCHECK CONSTRAINT FK_SubprojectFinancial_Subproject
	ALTER TABLE CapitalManagementProduction.forecast.SubprojectFutureYear NOCHECK CONSTRAINT FK_SubprojectFutureYear_Subproject
	ALTER TABLE CapitalManagementProduction.forecast.SubprojectPriorYear NOCHECK CONSTRAINT FK_SubprojectPriorYear_Subproject'
) AT [CAPINFWWAPV01]