SELECT SUBQ3.*,
ROW_NUMBER() OVER (PARTITION BY CIRCUIT_NO ORDER BY CMPY_NO) AS ROWNUM
FROM
( -- SUBQ3 -- 
SELECT DISTINCT
OREPLACE(OREPLACE(OREPLACE(SUBQ2.CIRCUIT_NO,'.',''),'-',''),' ','')AS CLEAN_ID,
SUBQ2.CMPY_NO, SUBQ2.CMPY_NO_COUNT, SUBQ2.STATE, SUBQ2.CIRCUIT_NO, SUBQ2.NC_PRODUCT_CD, SUBQ2.NCI, subq2.cfa,
SUBQ2.BILL_MONTH_DT, SUBQ2.ACNA, SUBQ2.JURIS_CD, SUBQ2.INSTALL_DT, SUBQ2.TERM_START_DT, SUBQ2.TERM_END_DT,-- SUBQ2.DISCONNECT_DT,
-- subq2.cabs_billing_no, subq2.ixc_no,
SUBQ2.TOTAL_MRC, SUBQ2.PRIMARY_CARRIER_NAME, SUBQ2.PLAN_ID, SUBQ2.PNUM, SUBQ2.WIRELESS, 
CASE WHEN (SUBQ2.STATE <> 'CT' AND SUBQ2.NNI = 'NNI') THEN 'ETH_NNI'
     WHEN (SUBQ2.STATE = 'CT' AND SUBSTR(SUBQ2.NC_PRODUCT_CD,1,2) IN ('KD','KE','KF','KG','KJ','KP','KQ','KR','KS','KU','SN')
       AND SUBSTR(SUBQ2.NC_PRODUCT_CD,4,1) IN ('0','-') 
       AND SUBQ2.ACTLCLLI <> 'UNKNOWN' 
       AND SUBQ2.ACTLCLLI <> 'ZZZZZZZZZZZ' 
       AND OREPLACE(SUBQ2.ACTLCLLI,' ','') <> ''
       AND SUBSTR(SUBQ2.ACTLCLLI,1,4) <> 'CUST' 
       AND SUBQ2.PRODUCT <> 'GIGA,DECA,WAVE') THEN 'ETH_NNI'
     -- WHEN SUBSTR(cabs.NC_PRODUCT_CD,1,1) = 'K' THEN 'UNI'
     -- WHEN SUBSTR(cabs.NC_PRODUCT_CD,1,2) = 'VL' THEN 'EVC'
     ELSE SUBQ2.SVC_GROUP END AS SVC_GROUP,
NVL(SUBQ2.PRODUCT, 
    CASE WHEN SUBSTR(SUBQ2.SVC_GROUP,1,3) IN ('TDM','OCN') THEN 'TDM/OCN'
         WHEN SUBSTR(SUBQ2.SVC_GROUP,1,5) = ('COLLO') THEN SUBQ2.SVC_GROUP
         WHEN SUBSTR(SUBQ2.PLAN_ID,1,3) = 'DKF' THEN 'DRK_FBR'
    ELSE 'UNKNOWN' END) AS PRODUCT, 
NVL(SUBQ2.ETHERNET_TYPE,'UNKNOWN') AS ETHERNET_TYPE, 
CASE WHEN SUBSTR(SUBQ2.CIRCUIT_NO,4,2) = 'KD' THEN 10
     WHEN SUBSTR(SUBQ2.CIRCUIT_NO,4,2) = 'KE' THEN 100
     WHEN SUBSTR(SUBQ2.CIRCUIT_NO,4,2) = 'KF' THEN 1000
     WHEN SUBSTR(SUBQ2.CIRCUIT_NO,4,2) = 'KG' THEN 10000
     WHEN SUBSTR(SUBQ2.CIRCUIT_NO,4,2) = 'KJ' THEN 100000
     WHEN SUBSTR(SUBQ2.CIRCUIT_NO,4,2) = 'KP' THEN 10
     WHEN SUBSTR(SUBQ2.CIRCUIT_NO,4,2) = 'KQ' THEN 100
     WHEN SUBSTR(SUBQ2.CIRCUIT_NO,4,2) = 'KR' THEN 1000
     WHEN SUBSTR(SUBQ2.CIRCUIT_NO,4,2) = 'KS' THEN 10000     
     WHEN SUBSTR(SUBQ2.CIRCUIT_NO,4,2) = 'KU' THEN 100000     
     -- WHEN SUBSTR(cabs.CIRCUIT_NO,4,2) = 'VL' THEN CIR.MBPS     
     ELSE NULL END AS UNI_MBPS,
CASE WHEN SUBSTR(SUBQ2.CIRCUIT_NO,4,2) IN ('KP','KQ','KR','KS','KU') THEN 'Adj' ELSE NULL END AS ADJ,
CASE WHEN SUBQ2.SVC_GROUP = 'ETH_EVC' THEN SUBQ2.EVC_MBPS ELSE NULL END AS EVC_MBPS, 
SUBQ2.NNI, 
SUBQ2.FIRST_BILL_MONTH_DT, SUBQ2.LAST_BILL_MONTH_DT, SUBQ2.MILEAGE_MRC,
-- ROW_NUMBER() OVER (PARTITION BY CIRCUIT_NO ORDER BY CMPY_NO) AS ROWNUM,
(select max(eo_clli_cd) from edw_vwmc.CABS_SPCL_ACCS_BILL_REV_DTL_V cabsc where 
  OREPLACE(OREPLACE(OREPLACE(SUBQ2.CIRCUIT_NO,'.',''),'-',''),' ','') = 
  OREPLACE(OREPLACE(OREPLACE(cabsc.CIRCUIT_NO,'.',''),'-',''),' ','')) as EO_CLLI,
CASE WHEN (SUBSTR(SUBQ2.PLAN_ID,1,3) IN ('DKF','EDC','EDG','EOS','SEW')
        OR SUBSTR(SUBQ2.PLAN_ID,1,4) IN ('EIAV','EPAV','FOTW')
        OR SUBSTR(SUBQ2.PLAN_ID,1,5) IN ('FOTSV')
        OR SUBSTR(SUBQ2.PLAN_ID,1,6) IN ('FBATTM','FLATFB','PCFICB'))
     THEN 'NEW' ELSE 'OTHER' END AS PNUM_GRP,
(SELECT MAX(CABST.TIER) from edw_vwmc.CABS_SPCL_ACCS_BILL_REV_DTL_V CABST  WHERE 
  OREPLACE(OREPLACE(OREPLACE(SUBQ2.CIRCUIT_NO,'.',''),'-',''),' ','') = 
  OREPLACE(OREPLACE(OREPLACE(CABST.CIRCUIT_NO,'.',''),'-',''),' ','') 
  AND CABST.BILL_MONTH_DT = SUBQ2.BILL_MONTH_DT) 
  AS TIER,
(SELECT MIN(CABSR.BILL_MONTH_DT) from edw_vwmc.CABS_SPCL_ACCS_BILL_REV_DTL_V CABSR  WHERE 
  OREPLACE(OREPLACE(OREPLACE(SUBQ2.CIRCUIT_NO,'.',''),'-',''),' ','') = 
  OREPLACE(OREPLACE(OREPLACE(CABSR.CIRCUIT_NO,'.',''),'-',''),' ','') 
  AND (SUBSTR(CABSR.PNUM,1,4) IN ('EPAV','EIAV') AND SUBSTR(CABSR.PNUM,17,2)='BK')) 
  as RETERM_BILL_MONTH
FROM
-------------------------------------------------------------------------------------------------------------------------
( -- SUBQ2 -- ADD INFO FROM OTHER FIELDS TO THE CIRCUITS DEFINED IN CABSSP
SELECT DISTINCT
CABSSP.CMPY_NO, 
(SELECT MAX(CABS3.PLAN_ID) FROM edw_vwmc.CABS_SPCL_ACCS_BILL_REV_DTL_V CABS3 WHERE CABS3.CIRCUIT_NO = CABSSP.CIRCUIT_NO 
 AND CABS3.BILL_MONTH_DT = CABS.BILL_MONTH_DT AND CABS3.CMPY_NO = CABSSP.CMPY_NO AND CABS3.SW_SPL_IND = 'SP'
) AS PLAN_ID, 
(SELECT MAX(CABS4.PNUM) FROM edw_vwmc.CABS_SPCL_ACCS_BILL_REV_DTL_V CABS4 WHERE CABS4.CIRCUIT_NO = CABSSP.CIRCUIT_NO 
 AND CABS4.BILL_MONTH_DT = CABS.BILL_MONTH_DT AND CABS4.CMPY_NO = CABSSP.CMPY_NO AND CABS4.SW_SPL_IND = 'SP'
) AS PNUM, 
-- CABS.EO_CLLI_CD, CABS.POP_CLLI_CD,
CABSSP.CMPY_NO_COUNT, CABSSP.STATE, CABS.ACTLCLLI, CABS.CIRCUIT_NO, CABS.NC_PRODUCT_CD, CABS.BILL_MONTH_DT, 
MIN(CABS.JURIS_CD) OVER (PARTITION BY CABS.CIRCUIT_NO, CABS.BILL_MONTH_DT) AS JURIS_CD,
MAX(CABS.ACNA) OVER (PARTITION BY CABS.CIRCUIT_NO, CABS.BILL_MONTH_DT) AS ACNA, 
CABS.NCI, 
MAX(CABS.CFA) OVER (PARTITION BY CABS.CIRCUIT_NO, CABS.BILL_MONTH_DT) AS CFA, 
MIN(CABS.INSTALL_DT) OVER (PARTITION BY CABS.CIRCUIT_NO, CABS.BILL_MONTH_DT) AS INSTALL_DT, 
-- CABS.TERM_START_DT, CABS.TERM_END_DT, -- cabs.cabs_billing_no, cabs.ixc_no,-- CABS.DISCONNECT_DT, --   -- CABS.SW_SPL_IND, CABS.ACNA, 
MAX(CABS.TERM_START_DT) OVER (PARTITION BY CABS.CIRCUIT_NO, CABS.BILL_MONTH_DT) AS TERM_START_DT,
MAX(CABS.TERM_END_DT) OVER (PARTITION BY CABS.CIRCUIT_NO, CABS.BILL_MONTH_DT) AS TERM_END_DT,
(SELECT SUM(CABSM.CHRGE_AMT) FROM edw_vwmc.CABS_SPCL_ACCS_BILL_REV_DTL_V CABSM
  WHERE CABS.CIRCUIT_NO = CABSM.CIRCUIT_NO AND CABS.BILL_MONTH_DT = CABSM.BILL_MONTH_DT AND CABS.CMPY_NO = CABSM.CMPY_NO
  AND (CABSM.DISCONNECT_DT > CABSM.BILL_CYCLE_DT OR CABSM.DISCONNECT_DT IS NULL)) AS TOTAL_MRC,
(SELECT SUM(CABSM2.CHRGE_AMT) FROM edw_vwmc.CABS_SPCL_ACCS_BILL_REV_DTL_V CABSM2
  INNER JOIN USER_WORK.CM_USOC_ETHERNET_TYPE4 USOC2 ON CABSM2.USOC_PRODUCT_CD = USOC2.USOC AND SUBSTR(USOC2.CHARGE_TYPE,1,7) = 'Mileage'
  WHERE CABS.CIRCUIT_NO = CABSM2.CIRCUIT_NO AND CABS.BILL_MONTH_DT = CABSM2.BILL_MONTH_DT AND CABS.CMPY_NO = CABSM2.CMPY_NO
  AND (CABSM2.DISCONNECT_DT > CABSM2.BILL_CYCLE_DT OR CABSM2.DISCONNECT_DT IS NULL)) AS MILEAGE_MRC,

NVL(MCL.PRIMARY_CARRIER_NAME,'UNKNOWN') AS PRIMARY_CARRIER_NAME,
CASE WHEN MCL.PRIMARY_FOCUS = 'WIRELESS' THEN 'WIRELESS' ELSE 'WIRELINE' END AS WIRELESS,
-- NVL(WA.PRIMARY_FOCUS,'WIRELINE') AS WIRELESS,
-- 'ALL' AS WIRELESS,
CASE WHEN MAX(USOC3.CHARGE_TYPE) OVER (PARTITION BY CABS.CIRCUIT_NO, CABS.BILL_MONTH_DT) = 'NNI' THEN 'ETH_NNI'
     WHEN SUBSTR(cabs.NC_PRODUCT_CD,1,1) ='K' THEN 'ETH_UNI'
     WHEN SUBSTR(cabs.NC_PRODUCT_CD,1,2) ='SN' THEN 'ETH_NNI'
     WHEN SUBSTR(cabs.NC_PRODUCT_CD,1,2) ='
     WHEN SUBSTR(cabs.NC_PRODUCT_CD,1,2) ='VL' THEN 'ETH_EVC'
     WHEN SUBSTR(cabs.NC_PRODUCT_CD,1,1) ='O' THEN 'OCN'
     WHEN SUBSTR(cabs.NC_PRODUCT_CD,1,2) ='HF' AND SUBSTR(cabs.NC_PRODUCT_CD,4,1) NOT IN ('-',' ') 
       AND LENGTH(cabs.NC_PRODUCT_CD)= 4 THEN 'TDM_DS3_mux'
     WHEN SUBSTR(cabs.NC_PRODUCT_CD,1,2) ='HC' AND SUBSTR(cabs.NC_PRODUCT_CD,4,1) NOT IN ('-',' ') 
       AND LENGTH(cabs.NC_PRODUCT_CD)= 4 THEN 'TDM_DS1_mux'
     WHEN SUBSTR(cabs.NC_PRODUCT_CD,1,2) ='HF' AND LENGTH(CABS.CIRCUIT_NO) > 27 THEN 'TDM_DS3_noEU'
     WHEN SUBSTR(cabs.NC_PRODUCT_CD,1,2) ='HC' AND LENGTH(CABS.CIRCUIT_NO) > 27 THEN 'TDM_DS1_noEU'
     WHEN SUBSTR(cabs.NC_PRODUCT_CD,1,2) ='HF' THEN 'TDM_DS3'
     WHEN SUBSTR(cabs.NC_PRODUCT_CD,1,2) ='HC' THEN 'TDM_DS1'
     WHEN SUBSTR(cabs.NC_PRODUCT_CD,1,4) ='COLL' THEN 'COLLO_REG'
     WHEN SUBSTR(cabs.NC_PRODUCT_CD,1,4) ='COLO' THEN 'COLLO_NONREG'     
     WHEN SUBSTR(cabs.PLAN_ID,1,3) = 'DKF' THEN 'DRK_FBR'
     ELSE 'OTHER' END AS SVC_GROUP,
CASE WHEN SUBSTR(cabs.NC_PRODUCT_CD,1,1) IN ('K','O') OR SUBSTR(cabs.NC_PRODUCT_CD,1,2) IN ('VL','SN') 
      THEN MAX(USOC.PRODUCT) OVER (PARTITION BY CABS.CIRCUIT_NO, CABS.BILL_MONTH_DT) ELSE NULL END AS PRODUCT, 
 CASE WHEN SUBSTR(cabs.NC_PRODUCT_CD,1,1) IN ('K','O') OR SUBSTR(cabs.NC_PRODUCT_CD,1,2) IN ('VL','SN') 
      THEN MAX(USOC.ETHERNET_TYPE) OVER (PARTITION BY CABS.CIRCUIT_NO, CABS.BILL_MONTH_DT) ELSE NULL END AS ETHERNET_TYPE, 
 MAX(USOC2.MBPS) OVER (PARTITION BY CABS.CIRCUIT_NO, CABS.BILL_MONTH_DT) AS EVC_MBPS, 
 MAX(USOC3.CHARGE_TYPE) OVER (PARTITION BY CABS.CIRCUIT_NO, CABS.BILL_MONTH_DT) AS NNI,    
CASE WHEN(SELECT MIN(CABS1.BILL_MONTH_DT) FROM edw_vwmc.CABS_SPCL_ACCS_BILL_REV_DTL_V CABS1 
   WHERE CABS1.CIRCUIT_NO = CABS.CIRCUIT_NO AND CABS1.BILL_MONTH_DT >= ADD_MONTHS(CABS.BILL_MONTH_DT,-1) 
   AND CABS1.SW_SPL_IND = 'SP' AND (CABS1.DISCONNECT_DT > CABS1.BILL_CYCLE_DT OR CABS1.DISCONNECT_DT IS NULL)) = CABS.BILL_MONTH_DT THEN CABS.BILL_MONTH_DT ELSE NULL END 
   AS FIRST_BILL_MONTH_DT, -- CHECKS IF BILLED IN PRIOR MONTH TO IDENTIFY ADDS
CASE WHEN (SELECT MAX(CABS2.BILL_MONTH_DT) FROM edw_vwmc.CABS_SPCL_ACCS_BILL_REV_DTL_V CABS2
   WHERE CABS2.CIRCUIT_NO = CABS.CIRCUIT_NO AND CABS2.BILL_MONTH_DT <= ADD_MONTHS(CABS.BILL_MONTH_DT,1) 
   AND CABS2.SW_SPL_IND = 'SP' AND (CABS2.DISCONNECT_DT > CABS2.BILL_CYCLE_DT OR CABS2.DISCONNECT_DT IS NULL)) = CABS.BILL_MONTH_DT THEN CABS.BILL_MONTH_DT ELSE NULL END 
   AS LAST_BILL_MONTH_DT -- CHECKS IF BILLED IN FOLLOWING MONTH TO IDENTIFY REMOVES        
FROM 
-------------------------------------------------------------------------------------------------------------------------
(-- CABSSP SUBQUERY -- IDENTIFY ONLY CIRCUITS WITH "SP" INDICATOR AND EXCLUDE NW4 OPERATING COMPANIES
SELECT DISTINCT 
SUBQ1.*,
CAST(1.00/(COUNT(CMPY_NO) OVER (PARTITION BY CIRCUIT_NO, BILL_MONTH_DT)) AS FORMAT '9.99') AS CMPY_NO_COUNT
FROM
-------------------------------------------------------------------------------------------------------------------------
( -- SUBQ1 SUBQUERY -- INITIAL SUBQUERY TO FIND UNIQUE CIRCUIT NUMBER/STATE CODE COMBINTATIONS FOR BILL MONTHS SPECIFIED 
SELECT DISTINCT 
  CABS0.CIRCUIT_NO, CABS0.CMPY_NO, -- CABS0.ACTLCLLI, --CABS.PLAN_ID, 
  CASE WHEN CABS0.STATE_CD IN ('AL','AZ','CA','CT','FL','GA','IA','ID','IL','IN','MI','MN',
         'MS','MT','NC','NE','NM','NV','NY','OH','OR','PA','SC','TN','TX','UT','WA','WI','WV')
         THEN CABS0.STATE_CD
       WHEN SUBSTR(CABS0.EO_CLLI_CD,5,2) IN ('AL','AZ','CA','CT','FL','GA','IA','ID','IL','IN','MI','MN',
         'MS','MT','NC','NE','NM','NV','NY','OH','OR','PA','SC','TN','TX','UT','WA','WI','WV')
         THEN SUBSTR(CABS0.EO_CLLI_CD,5,2) 
       WHEN SUBSTR(CABS0.POP_CLLI_CD,5,2) IN ('AL','AZ','CA','CT','FL','GA','IA','ID','IL','IN','MI','MN',
         'MS','MT','NC','NE','NM','NV','NY','OH','OR','PA','SC','TN','TX','UT','WA','WI','WV')
         THEN SUBSTR(CABS0.POP_CLLI_CD,5,2)   
       WHEN SUBSTR(CABS0.CIRCUIT_NO,18,2) IN ('AL','AZ','CA','CT','FL','GA','IA','ID','IL','IN','MI','MN',
         'MS','MT','NC','NE','NM','NV','NY','OH','OR','PA','SC','TN','TX','UT','WA','WI','WV')  
         THEN SUBSTR(CABS0.CIRCUIT_NO,18,2)   
       WHEN CABS0.STATE_CD IS NULL OR CABS0.EO_CLLI_CD IS NULL OR CABS0.POP_CLLI_CD IS NULL OR CABS0.CIRCUIT_NO IS NULL  
         THEN 'OTHER'     
       ELSE 'OTHER' END AS STATE, -- CHECK SERVERAL FIELDS TO DERIVE STATE SINCE NOT ALWAYS POPULATED
  CABS0.BILL_MONTH_DT
FROM edw_vwmc.CABS_SPCL_ACCS_BILL_REV_DTL_V CABS0 
--WHERE CABS0.BILL_MONTH_DT = ADD_MONTHS(CURRENT_DATE - EXTRACT(DAY FROM CURRENT_DATE)+1, -1)
WHERE CABS0.BILL_MONTH_DT BETWEEN '2023-01-01' AND '2024-05-01' -- >= '2019-12-01') 
  AND (CABS0.SW_SPL_IND = 'SP' OR SUBSTR(CABS0.NC_PRODUCT_CD,1,4) IN ('COLL','COLO') OR SUBSTR(PLAN_ID,1,3) = 'DKF')
  AND (CABS0.DISCONNECT_DT > CABS0.BILL_CYCLE_DT OR CABS0.DISCONNECT_DT IS NULL) 
  -- AND SUBSTR(EO_CLLI_CD,1,8) = 'ALFAFLXA'
  -- AND CABS0.ACNA IN ('AF1','CXN','EXC','FBA','T05','WWW','ZTK') -- ONE TIME RUN
  -- AND CABS0.CIRCUIT_NO = 'FA.KRGN.483603.   .SN  .' -- TEST CIRCUIT
) SUBQ1 
-------------------------------------------------------------------------------------------------------------------------
   WHERE CMPY_NO NOT IN ('0570','0572','0576','6102','6105','6106') -- EXCLUDE NWF COMPANY CODES
   -- WHERE STATE NOT IN ('WA','OR','MT','ID')  -- CHANGE TO RUN ON FTR SERVER
   -- WHERE STATE IN ('WA','OR','MT','ID')  -- CHANGE TO RUN ON NWF SERVER
   

   ) CABSSP
-----------------------------------------------------------------------------------------------------------------
INNER JOIN edw_vwmc.CABS_SPCL_ACCS_BILL_REV_DTL_V CABS ON CABSSP.CIRCUIT_NO = CABS.CIRCUIT_NO AND CABSSP.CMPY_NO = CABS.CMPY_NO
LEFT OUTER JOIN USER_WORK.CM_USOC_ETHERNET_TYPE4 USOC ON CABS.USOC_PRODUCT_CD = USOC.USOC 
   AND SUBSTR(USOC.CHARGE_TYPE,1,9) <> 'Mileage -'
LEFT OUTER JOIN USER_WORK.CM_USOC_ETHERNET_TYPE4 USOC2 ON CABS.USOC_PRODUCT_CD = USOC2.USOC 
   AND SUBSTR(USOC2.CHARGE_TYPE,1,9) <> 'Mileage -'
LEFT OUTER JOIN USER_WORK.CM_USOC_ETHERNET_TYPE4 USOC3 ON CABS.USOC_PRODUCT_CD = USOC3.USOC 
   AND USOC3.CHARGE_TYPE = 'NNI'
-- LEFT OUTER JOIN USER_WORK.CM_WIRELESS_ACNAS WA ON CABS.ACNA = WA.SECONDARY_ID
LEFT OUTER JOIN USER_WORK.CM_CARRIER_ACNA_MCL MCL ON CABS.ACNA = MCL.SECONDARY_ID
--WHERE CABS.BILL_MONTH_DT = ADD_MONTHS(CURRENT_DATE - EXTRACT(DAY FROM CURRENT_DATE)+1, -1)
WHERE CABS.BILL_MONTH_DT BETWEEN '2023-01-01' AND '2024-05-01'  -- SPECIFY BILL MONTH RANGE TO RETRIEVE
-- AND SUBSTR(CABS.NC_PRODUCT_CD,1,2) IN ('HF','HC')
-- AND CABS.CLASS_OF_SERVICE IN ('XDH1X','XDH3X')
AND (SUBSTR(CABS.NC_PRODUCT_CD,1,1) IN ('K','O') OR SUBSTR(CABS.NC_PRODUCT_CD,1,2) IN ('HF','HC','VL','SN','LX')
  OR SUBSTR(CABS.NC_PRODUCT_CD,1,4) IN ('COLL','COLO') OR SUBSTR(PLAN_ID,1,3) = 'DKF')
-- AND SUBSTR(CABS.SOURCE_GL_ACCT_CD,20,3) IN ('106','107')
-- AND CABS.ACNA IN ('AF1','CXN','EXC','FBA','T05','WWW','ZTK') -- ONE TIME RUN
AND CABS.ACNA NOT IN ('BLI','CQV','CZJ','CZX','EPX','FLR','FLX','FTR','GOV','SUV','ZWV','ZZZ',
                      'FIS','W05','ANV','FCA','GVN','ZAP','GSW','WBY','CUS','VZN',
                      'AF1','CXN','EXC','FBA','T05','WWW','ZTK') -- EXCLUDE RETAIL/AFFILIATE ACNAs
AND NOT(CABS.ACNA = 'BNK' AND CABS.CMPY_NO ='5050')
AND NOT(CABS.ACNA = 'ALN' AND CABS.CMPY_NO ='0223')
) SUBQ2
WHERE NOT (SUBSTR(SUBQ2.NC_PRODUCT_CD,1,2) = 'LX' AND SUBQ2.SVC_GROUP <> 'DRK_FBR')
-- WHERE SUBQ2.PLAN_ID LIKE ('%ICB%')
-- WHERE SUBQ2.PRIMARY_CARRIER_NAME LIKE '%VERIZON%'
-- AND SUBQ2.PRIMARY_CARRIER_NAME IN ('AT'||chr(38)||'T','AT'||chr(38)||'T MOBILITY') 
) SUBQ3
ORDER BY SUBQ3.CIRCUIT_NO, SUBQ3.CMPY_NO
