CREATE TABLE [dbo].[TBL_MCL_HIST](
	[SECONDARY_ID_SOURCE] [nvarchar](255) NULL,
	[PRIMARY_ID_SOURCE] [nvarchar](255) NULL,
	[PRIMARY_ID] [nvarchar](255) NULL,
	[PRIMARY_CARRIER_NM] [nvarchar](255) NULL,
	[PRIMARY_FOCUS] [nvarchar](255) NULL,
	[ID_TYPE] [nvarchar](255) NULL,
	[SECONDARY_ID] [nvarchar](255) NULL,
	[SECONDARY_CARRIER_NM] [nvarchar](255) NULL,
	[VP] [nvarchar](255) NULL,
	[Column1] [nvarchar](255) NULL,
	[SLS_DIR] [nvarchar](255) NULL,
	[AE_SR] [nvarchar](255) NULL,
	[AE_2] [nvarchar](255) NULL,
	[AE] [nvarchar](255) NULL,
	[SLS_ENGR] [nvarchar](255) NULL,
	[CHECK] [nvarchar](255) NULL,
	[UPDATE_DT] [datetime] NULL,
	[UPLOAD_TS] [datetime] NOT NULL
)