CREATE TABLE [TOWERS_UNIVERSE].[TBL_DSAT_MATRIX]
(
	[LOCATION_ID] [float] NULL,
	[state] [nvarchar](255) NULL,
	[lata] [nvarchar](255) NULL,
	[localAreaMarket] [nvarchar](255) NULL,
	[wireCenterClli] [nvarchar](255) NULL,
	[wireCenterName] [nvarchar](255) NULL,
	[eia] [nvarchar](255) NULL,
	[eReachPath] [nvarchar](255) NULL,
	[ipvpn] [nvarchar](255) NULL,
	[voip] [nvarchar](255) NULL,
	[metroE] [nvarchar](255) NULL,
	[approvedAccessElement] [nvarchar](255) NULL,
	[jumboFrames] [nvarchar](255) NULL,
	[maximumSpeed] [nvarchar](255) NULL,
	[maximumQualityOfService] [nvarchar](255) NULL,
	[carRouterClli] [nvarchar](255) NULL,
	[carLocation] [nvarchar](255) NULL,
	[perCarRouterCLLI] [nvarchar](255) NULL,
	[futureHbeWcSpeed] [nvarchar](255) NULL,
	[plannedHbeTimeframe] [nvarchar](255) NULL,
	[HBE_EIA] [nvarchar](255) NULL,
	[HBE_Evpl] [nvarchar](255) NULL,
	[HBE_Inni_L2] [nvarchar](255) NULL,
	[HBE_Jumbo_Frames] [nvarchar](255) NULL,
	[HBE_Max_QoS] [nvarchar](255) NULL,
	[HBE_Max_Speed] [nvarchar](255) NULL,
	[INNI L2] [nvarchar](255) NULL,
	[INNI L3] [nvarchar](255) NULL,
	[Market] [nvarchar](255) NULL,
	[Level] [nvarchar](255) NULL,
	[Lit_Building] [nvarchar](255) NULL,
	[AddrLn1] [nvarchar](255) NULL,
	[AddrLn2] [nvarchar](255) NULL,
	[AddrLn3] [nvarchar](255) NULL,
	[AddrLn4] [nvarchar](255) NULL,
	[AddrLn5] [nvarchar](255) NULL,
	[AddrLn6] [nvarchar](255) NULL,
	[AddrLn7] [nvarchar](255) NULL,
	[INSERT_TS] [datetime] NOT NULL
)
