
CREATE PROCEDURE STG_DPI_VW.usp_ACOCUFL
/*
	-- Add any parameters for the stored procedure here
	@var1 int,
	@var2 int
*/
AS
	SET XACT_ABORT, NOCOUNT ON;
BEGIN TRY
	BEGIN TRANSACTION
	DROP TABLE IF EXISTS #t
INSERT INTO [LOG].tbl_StoreProc
    ([EVENTNAME]
    ,[EVENTSTART]
    ,[EVENTTYPE]
    ,[EVENTDESCRIPTION])

--enter values below

VALUES
('STG_DPI_VW.ACOCUFL'
    ,CAST(GETDATE() AS DATETIME)
    ,'STORE PROC'
    ,'SINGLE_INGESTION')



SELECT MAX(EVENTID) AS LATESTID  INTO #t
FROM [LOG].tbl_StoreProc

TRUNCATE TABLE STG_DPI_VW.ACOCUFL;

INSERT INTO STG_DPI_VW.ACOCUFL
select
CO
,IXC
,ACCTTYPE
,FACTYPE
,OCCDATE
,SO
,CIRCUIT
,LEG
,AZIND
,OCN
,SWSPL
,OCCTYPE
,USOC
,JURIS
,CAST(CAST(FROMDATE AS CHAR(8)) AS DATE) AS FROMDATE
,CAST(CAST(THRUDATE AS CHAR(8)) AS DATE) AS THRUDATE
,OCUIND
,CAST(CAST(BILLDATE AS CHAR(8)) AS DATE) AS BILLDATE
,BEENAPPL
,STATE
,PHRASECODE
,BIP
,BIP2
,PERMONTH
,AMOUNT
,SURCHARGE
,TAX
,OCCDAYS
,USOCDESIG
,LEC
,QTY
,TETQTYL
,TETREVL
,FLEXBAND
,MILERDT
,GEOCODE
,TAXCAT
,TAXSER
,SPLITPCT
,SPLITGEO
,PLANLVL
,USORATE
,USOCOS
,USOCOMP
,USOTIER
,USOSEQ
,USOFAC
,USOMON
,FILLER1
,UPDFUNC
,CAST(CAST(CASE WHEN UPDDATE = 0 THEN NULL ELSE UPDDATE END AS CHAR(8)) AS DATE) AS UPDDATE
,UPDTIME
,UPDOPID
,DW_USER
,CAST(DW_LOAD_TIMESTAMP AS DATETIME2) AS DW_LOAD_TIMESTAMP
,BILL_SUBSYS_CD

from LZ.TBL_STG_DPI_VW_ACOCUFL



	
	
UPDATE L
SET L.EVENTEND=CAST(GETDATE() AS DATETIME)
FROM LOG.tbl_StoreProc L
INNER JOIN #t
ON L.EVENTID = #t.LATESTID
DROP TABLE IF EXISTS #t


	
	COMMIT TRANSACTION
END TRY
BEGIN CATCH
	IF @@trancount > 0 ROLLBACK TRANSACTION
	EXEC usp_error_handler
	RETURN 55555
END CATCH