CREATE TABLE [REPORTING_BLITZ].[TBL_CRT_BDT_CAPITAL](
	[CRT_NBR] [varchar](14) NULL,
	[CREATED_DATE] [datetime] NULL,
	[CRT_ID] [int] NULL,
	[CAPITAL_AMOUNT] [numeric](14, 2) NULL,
	[EXPENSE_AMOUNT] [numeric](14, 2) NULL,
	[CASH_AMOUNT] [numeric](14, 2) NULL,
	[OSP_CAPITAL_AMOUNT] [numeric](14, 2) NULL,
	[EQUIPMENT_CAPITAL_AMOUNT] [numeric](14, 2) NULL
)
