CREATE TABLE [REPORTING_BLITZ].[TBL_OVERTOLERANCE_THRESHOLD_XREF] (
    THRESHOLD_ID INT IDENTITY(1,1) PRIMARY KEY,
    BW_LOWER NUMERIC(18,2),
    BW_UPPER NUMERIC(18,2),
    TIER1_DSAT_THRSHLD NUMERIC(18,2),
    TIER1_MAX_CAPITAL NUMERIC(18,2),
    TIER2_DSAT_THRSHLD NUMERIC(18,2),
    TIER2_MAX_CAPITAL NUMERIC(18,2),
    BW_RANGE VARCHAR(50),
    EFFECTIVE_DATE DATETIME,
    EXPIRATION_DATE DATETIME
);

