CREATE VIEW QBR.[NCFR_V] AS

SELECT DOCUMENT_NUMBER, PON, ACT_IND, COMP_DT, DD_TASK_COMP, NPANXX, CLLI, ICSC, 
 CASE WHEN ICSC IN ('GT10','GT11') and state = 'CA' THEN 'CA' ELSE 'LEGACY' END AREA,
 ACNA, CUSTOMER,
 --CASE WHEN ACNA IN ('HOC','UXW','CPO','NVA','LTP','DLT','BTI','NGE') THEN 'EARTHLINK'
   --   ELSE CUSTOMER END CUSTOMER,
 REGION, TERRITORY, LAM, STATE,  
 CASE WHEN PRODUCT LIKE 'ETHERNET%' THEN 'Ethernet' ELSE PRODUCT END PRODUCT,
 CKT, 
    MIN(TICKET_ID) OVER (PARTITION BY DOCUMENT_NUMBER, PON, ACT_IND, COMP_DT, DD_TASK_COMP, NPANXX, CLLI, ICSC, ACNA, CUSTOMER, 
         REGION, TERRITORY, LAM, STATE, PRODUCT, CKT, MON) AS TICKET_ID, 
    MIN(ASSIGNMENTPROFILE) OVER (PARTITION BY TICKET_ID ORDER BY TICKET_ID) AS ASSIGNMENTPROFILE,
    MIN(REPAIR_CODE) OVER (PARTITION BY TICKET_ID ORDER BY TICKET_ID) AS REPAIR_CODE, 
    MIN(DISP) OVER (PARTITION BY TICKET_ID ORDER BY TICKET_ID) AS DISP,
    MIN(TRBL_CREATE_DATE) OVER (PARTITION BY TICKET_ID ORDER BY TICKET_ID) AS TRBL_CREATE_DATE,
    MIN(TRBL_CLEARED_DT) OVER (PARTITION BY TICKET_ID ORDER BY TICKET_ID) AS TRBL_CLEARED_DT,
    MIN(TRBL_CLOSED_DT) OVER (PARTITION BY TICKET_ID ORDER BY TICKET_ID) AS TRBL_CLOSED_DT,
    CASE WHEN MON = 12 THEN 1 ELSE MON + 1 END AS MON                                              --USE PLUS 1 TO ACCOMODATE THE SPREADSHEET WITH THIS ONE MONTH IN ARREARS              
 FROM (
    SELECT DISTINCT DOCUMENT_NUMBER, PON, ACT_IND, COMP_DT, DD_TASK_COMP, NPANXX, CLLI, ICSC, ACNA, CUSTOMER,
    REGION, TERRITORY, LAM, STATE, PRODUCT, CKT, TICKET_ID, ASSIGNMENTPROFILE, REPAIR_CODE, TFR.DISP, DATEPART(MONTH, DD_TASK_COMP) AS MON,  
    CREATE_DATE TRBL_CREATE_DATE, 
    CASE WHEN CLEARED_DT IS NOT NULL THEN CLEARED_DT
            ELSE CLOSED_DT END TRBL_CLEARED_DT, 
    CASE WHEN CLOSED_DT IS NOT NULL THEN CLOSED_DT
            ELSE CLEARED_DT END TRBL_CLOSED_DT
    FROM (
        SELECT DISTINCT DOCUMENT_NUMBER, PON, ACT_IND, COMP_DT, DD_TASK_COMP, NPANXX, CLLI, ICSC, A.ACNA, CUSTOMER,
        REGION, TERRITORY, LAM, STATE, PRODUCT, CKT,
        TT.TICKET_ID TICKET_ID,
            MAX(TT.FLD_COMPLETE_REPAIRCODE) OVER (PARTITION BY TT.TICKET_ID ORDER BY TT.FLD_MODIFIEDDATE DESC) AS REPAIR_CODE,
            MAX(LTRIM(RTRIM(TT.FLD_ASSIGNMENTPROFILE))) OVER (PARTITION BY TT.TICKET_ID ORDER BY TT.FLD_MODIFIEDDATE) AS ASSIGNMENTPROFILE, 
            MAX(TT.FLD_REQUESTSTATUS) OVER (PARTITION BY TT.TICKET_ID ORDER BY TT.FLD_MODIFIEDDATE DESC) AS REQSTAT,
            MAX(TT.FLD_REQUESTTYPE) OVER (PARTITION BY TT.TICKET_ID ORDER BY TT.FLD_MODIFIEDDATE DESC) AS REQUEST_TYPE,
            MAX(TT.FLD_STARTDATE) OVER (PARTITION BY TT.TICKET_ID ORDER BY TT.FLD_MODIFIEDDATE DESC) AS CREATE_DATE,
            MAX(TT.FLD_EVENT_END_TIME) OVER (PARTITION BY TT.TICKET_ID ORDER BY TT.FLD_MODIFIEDDATE DESC) AS CLEARED_DT, 
            MAX(TT.DTE_CLOSEDDATETIME) OVER (PARTITION BY TT.TICKET_ID ORDER BY TT.FLD_MODIFIEDDATE DESC) AS CLOSED_DT,
            MAX(TT.FLD_MODIFIEDDATE)OVER (PARTITION BY TT.TICKET_ID) AS MOD_DATE
        FROM (  
            SELECT DOCUMENT_NUMBER, PON, ACT_IND, DREC, DD, DDD, COMP_DT, DD_TASK_COMP, 
            NCFR.NPANXX, CLLI, ICSC, NCFR.ACNA, CUSTOMER, PRODUCT, CKT, 
            CASE WHEN LAMN.REGION IS NOT NULL THEN LAMN.REGION ELSE NULL END REGION,
            CASE WHEN LAMN.TERRITORY IS NOT NULL THEN LAMN.TERRITORY ELSE NULL END TERRITORY,
            CASE WHEN LAMN.LOCAL_MKT IS NOT NULL THEN LAMN.LOCAL_MKT ELSE NULL END LAM,
            CASE WHEN LAMN.STATE IS NOT NULL THEN LAMN.STATE
            ELSE NCFR.STATE END STATE
            FROM QBR.TBL_NCFR_WEEKLY NCFR, 
                 QBR.TBL_LAM_NPANXX LAMN
            WHERE NCFR.NPANXX = LAMN.NPANXX 
            AND YEAR(DD_TASK_COMP) >= 2023                  --CHANGE THIS EACH MONTH   SHOULD SHOW PREVIOUS MONTH   
        )A, QBR.TBL_CASDW_TROUBLE_TICKET_R TT
     WHERE A.CKT = TT.EXCHANGE_CARRIER_CIRCUIT_ID
     AND TT.FLD_TROUBLEREPORTSTATE = 'closed'
     AND TT.FLD_ASSIGNMENTPROFILE IN ('CNOC','Commercial-CTF','FTW TSC','CTF TSC')
     AND YEAR(FLD_STARTDATE) >=2023  --MUST CHANGE THESE DATES EACH MONTH TO SHOW CURRENT AND PREVIOUS MONTH  
     AND CONVERT(VARCHAR(8), TT.FLD_STARTDATE, 112) >= CONVERT(VARCHAR(8), A.COMP_DT, 112) 

   )B, QBR.TBL_TRBL_FOUND_REMEDY TFR           
   WHERE B.REPAIR_CODE = TFR.TRBL_FOUND_DESC   
   AND (REQUEST_TYPE IN ('Agent','Alarm','Customer','Maintenance')
   OR ASSIGNMENTPROFILE IN ('FTW TSC','CTF TSC'))
   AND TFR.DISP IN ('CO','FAC')           
)C
WHERE 1=1
and DATEDIFF(DAY, TRBL_CREATE_DATE, COMP_DT)<31
AND CONVERT(VARCHAR(8), TRBL_CREATE_DATE, 112) >= CONVERT(VARCHAR(8), COMP_DT, 112)
AND CUSTOMER IS NOT NULL
AND STATE NOT IN ('WA','OR','ID','MT')


