-- ONLY FOR UNI ALL 

select NTS.DOCUMENT_NUMBER, NOTES_ID, REGEXP_REPLACE (SUBSTR(NOTE_TEXT, 1,INSTR(NOTE_TEXT,'DESC')-1),'[[:cntrl:]]*') NOTE_TEXT, NTS.USER_ID, NTS.LAST_MODIFIED_DATE    
from NOTES NTS    
where (NTS.NOTE_TEXT LIKE ('%IN JEOPARDY CODE 1C%')    
OR NTS.NOTE_TEXT LIKE ('%IN JEOPARDY CODE CA02%')    
OR NTS.NOTE_TEXT LIKE ('%IN JEOPARDY CODE CA07%')    
OR NTS.NOTE_TEXT LIKE ('%IN JEOPARDY CODE CA14%')    
OR NTS.NOTE_TEXT LIKE ('%IN JEOPARDY CODE CA50%')    
OR NTS.NOTE_TEXT LIKE ('%IN JEOPARDY CODE CA51%')    
OR NTS.NOTE_TEXT LIKE ('%IN JEOPARDY CODE CA52%')    
OR NTS.NOTE_TEXT LIKE ('%IN JEOPARDY CODE SW01%')    
OR NTS.NOTE_TEXT LIKE ('%IN JEOPARDY CODE SW02%')    
OR NTS.NOTE_TEXT LIKE ('%IN JEOPARDY CODE SW03%')    
OR NTS.NOTE_TEXT LIKE ('%IN JEOPARDY CODE SW04%')    
OR NTS.NOTE_TEXT LIKE ('%IN JEOPARDY CODE SW05%')     
OR NTS.NOTE_TEXT LIKE ('%JEOPARDY CODE 1C CLOSED%')    
OR NTS.NOTE_TEXT LIKE ('%JEOPARDY CODE CA02 CLOSED%')    
OR NTS.NOTE_TEXT LIKE ('%JEOPARDY CODE CA07 CLOSED%')    
OR NTS.NOTE_TEXT LIKE ('%JEOPARDY CODE CA14 CLOSED%')    
OR NTS.NOTE_TEXT LIKE ('%JEOPARDY CODE CA50 CLOSED%')    
OR NTS.NOTE_TEXT LIKE ('%JEOPARDY CODE CA51 CLOSED%')    
OR NTS.NOTE_TEXT LIKE ('%JEOPARDY CODE CA52 CLOSED%')    
OR NTS.NOTE_TEXT LIKE ('%JEOPARDY CODE SW01 CLOSED%')    
OR NTS.NOTE_TEXT LIKE ('%JEOPARDY CODE SW02 CLOSED%')    
OR NTS.NOTE_TEXT LIKE ('%JEOPARDY CODE SW03 CLOSED%')    
OR NTS.NOTE_TEXT LIKE ('%JEOPARDY CODE SW04 CLOSED%')    
OR NTS.NOTE_TEXT LIKE ('%JEOPARDY CODE SW05 CLOSED%'))    
AND NTS.NOTE_TEXT NOT LIKE 'ASGNPLAN%'    
AND NTS.DOCUMENT_NUMBER IN (    
'3775956'    
)    
ORDER BY DOCUMENT_NUMBER, NOTES_ID    
