SELECT DISTINCT CKT, CLEC_ID, SERVICE_TYPE_CATEGORY,
       CASE WHEN STATE1 IS NOT NULL AND STATE1 <> 'EF' THEN STATE1
            WHEN STATE2 IS NOT NULL AND STATE2 <> 'EF' THEN STATE2
            WHEN ICSC = 'SN01' THEN 'CT'
            WHEN ICSC = 'RT01' THEN 'NY'
            ELSE STATE3 END STATE, 
       SVC_CD,
       CASE WHEN CLEC_ID IN ('ATX','TPM','AAV','SBB','SBZ','SUV') THEN 'ABS' ELSE 'MOB' END COMPANY,
       CASE WHEN UNI_OR_NNI = 'NNI' THEN 'Ethernet-NNI'
            WHEN UNI_OR_NNI = 'UNI' THEN 'Ethernet-UNI'
            WHEN PRODUCT IN ('DS1','DS3','OC3','OC12','OC48','OC192') THEN 'TDM'
            ELSE PRODUCT END PRODUCT,    
       BDW, STATUS, SI_STATUS                
FROM (
SELECT CKT, ICSC, RATE, TYPE, ECCKT_TYPE, SERVICE_TYPE_CATEGORY,
       CASE WHEN CCNAD1 IS NOT NULL THEN CCNAD1
            WHEN ACNAD1 IS NOT NULL THEN ACNAD1
            WHEN CCNAD2 IS NOT NULL THEN CCNAD2
            WHEN ACNAD2 IS NOT NULL THEN ACNAD2
            WHEN CCNA1 IS NOT NULL THEN CCNA1
            WHEN ACNA1 IS NOT NULL THEN ACNA1
            WHEN CCNA2 IS NOT NULL THEN CCNA2
            ELSE ACNA2 END CLEC_ID,
       STATE1, STATE2, STATE3, OCN, SVC_CD, STATUS, SI_STATUS, 
       CASE WHEN SUBSTR(SVC_CD,1,2) IN ('HC','HX','T1') THEN 'DS1'
            WHEN SUBSTR(SVC_CD,1,2) IN ('HF','T3') THEN 'DS3'
            WHEN SUBSTR(SVC_CD,1,2) IN ('SX','KG','KS','KJ') THEN 'Ethernet-NNI'
            WHEN SUBSTR(SVC_CD,1,1) IN ('K') THEN 'Ethernet-UNI'
            WHEN SUBSTR(SVC_CD,1,2) IN ('XL') THEN 'DS3'
            WHEN SVC_CD IN ('OB','OC3','OC03','OC03P','OC03N') THEN 'OC3'
            WHEN SVC_CD IN ('OD','OC12','OC12N','OC12P','OC12C','O12P') THEN 'OC12'
            WHEN SVC_CD IN ('OF','OC48','OC48P') THEN 'OC48'
            WHEN SVC_CD IN ('OG','OC192') THEN 'OC192'
            ELSE NULL END PRODUCT,
       CASE WHEN SVC_CD IN ('KD','KP') THEN '10M'  
            WHEN SVC_CD IN ('KE','KQ') THEN '100M'                
            WHEN SVC_CD IN ('KF','KR') THEN '1G'
            WHEN SVC_CD IN ('KG','KS') THEN '10G'
            WHEN SVC_CD IN ('KJ') THEN '100G'
            ELSE '' END BDW, 
       CASE WHEN UNI_OR_NNI = '436' THEN 'NNI'
            WHEN UNI_OR_NNI = '435' THEN 'UNI'
            ELSE '' END UNI_OR_NNI        
FROM (
SELECT EXCHANGE_CARRIER_CIRCUIT_ID CKT,
       MAX(D.EC_COMPANY_CODE) KEEP (DENSE_RANK FIRST ORDER BY D.LAST_MODIFIED_DATE) ICSC, 
       MAX(RATE_CODE) KEEP (DENSE_RANK LAST ORDER BY C.LAST_MODIFIED_DATE) RATE, 
       MAX(C.TYPE) KEEP (DENSE_RANK LAST ORDER BY C.LAST_MODIFIED_DATE) TYPE, 
       MAX(D.CCNA) KEEP (DENSE_RANK LAST ORDER BY D.LAST_MODIFIED_DATE) CCNA1, 
       MAX(D.CCNA) KEEP (DENSE_RANK FIRST ORDER BY D.CCNA) CCNA2, 
       MAX(D.ACNA) KEEP (DENSE_RANK LAST ORDER BY D.LAST_MODIFIED_DATE) ACNA1, 
       MAX(D.ACNA) KEEP (DENSE_RANK FIRST ORDER BY D.CCNA) ACNA2,
       MAX(D2.CCNA) KEEP (DENSE_RANK LAST ORDER BY D.LAST_MODIFIED_DATE) CCNAD1, 
       MAX(D2.CCNA) KEEP (DENSE_RANK FIRST ORDER BY D.CCNA) CCNAD2, 
       MAX(D2.ACNA) KEEP (DENSE_RANK LAST ORDER BY D.LAST_MODIFIED_DATE) ACNAD1, 
       MAX(D2.ACNA) KEEP (DENSE_RANK FIRST ORDER BY D.CCNA) ACNAD2,
       MAX(SUBSTR(NL1.CLLI_CODE,5,2)) KEEP (DENSE_RANK LAST ORDER BY NL1.LAST_MODIFIED_DATE) STATE1,
       MAX(SUBSTR(NL2.CLLI_CODE,5,2)) KEEP (DENSE_RANK LAST ORDER BY NL2.LAST_MODIFIED_DATE) STATE2,
       NULL STATE3, 
       MAX(NL1.OPERATING_COMPANY_NUMBER) KEEP (DENSE_RANK LAST ORDER BY NL1.LAST_MODIFIED_DATE) OCN,
       MAX(C.SERVICE_TYPE_CODE) KEEP (DENSE_RANK LAST ORDER BY C.LAST_MODIFIED_DATE) SVC_CD,
       MAX(C.STATUS) KEEP (DENSE_RANK LAST ORDER BY C.LAST_MODIFIED_DATE) STATUS,
       MAX(C.ECCKT_TYPE) KEEP (DENSE_RANK LAST ORDER BY C.LAST_MODIFIED_DATE) ECCKT_TYPE,
       MAX(C.SERVICE_TYPE_CATEGORY) KEEP (DENSE_RANK LAST ORDER BY C.LAST_MODIFIED_DATE) SERVICE_TYPE_CATEGORY,
       CUD.UNI_OR_NNI,
       SI.STATUS SI_STATUS
FROM CIRCUIT C, DESIGN_LAYOUT_REPORT D, NETWORK_LOCATION NL1, NETWORK_LOCATION NL2, 
     CIRCUIT_USER_DATA CUD, SERV_ITEM SI, DESIGN_LAYOUT_REPORT D2
WHERE C.EXCHANGE_CARRIER_CIRCUIT_ID = D.ECCKT (+)
AND C.CIRCUIT_DESIGN_ID = D2.CIRCUIT_DESIGN_ID (+)
AND C.CIRCUIT_DESIGN_ID = SI.CIRCUIT_DESIGN_ID (+)
AND C.LOCATION_ID = NL1.LOCATION_ID(+)
AND C.LOCATION_ID_2 = NL2.LOCATION_ID(+)
AND C.CIRCUIT_DESIGN_ID = CUD.CIRCUIT_DESIGN_ID (+)
AND C.TYPE <> 'T'
AND (SUBSTR(SERVICE_TYPE_CODE,1,2) IN ('HC','HF','HX','KP','KD','KE','KF','KG','KQ','KR','KS','KJ','T1','T3','SX')
    OR SUBSTR(SERVICE_TYPE_CODE,1,1) IN ('X','O'))
AND SERVICE_TYPE_CODE <> 'OS'
AND (D.CCNA IN ('AAV','AVA','ATX','LOA','SBB','SBZ','SUV','TPM',
               'AAX','ACF','ACH','ADM','AEC','AGS','AGZ','AHA','AHD','AHM','AHO','AIL','AIN','AIS','AKZ','ALY','AMH',
               'AMP','AWL','AWN','AWS','AZE','BAC','BAK','BAO','BCU','BFL','BGH','BMI','BPN','BSM','BWI','CBL','CCB',
               'CDA','CEL','CEO','CEU','CFN','CGL','CIV','CIW','CKQ','CLQ','COW','CPF','CQW','CRF','CRJ','CSG','CSO',
               'CSU','CSX','CTJ','CUO','CUY','CZB','DNC','EKC','EST','ETP','ETX','FLA','FSC','FSI','FSV','GEE','GLV',
               'GMB','GSL','HGN','HLU','HNC','HTN','HWC','IAS','IFP','IMP','IND','ISZ','IUW','JCR','JCT','LAA','LAC',
               'LBH','LNZ','LSZ','MBN','MBQ','MCA','MCC','MCE','MCQ','MCV','MCW','MCZ','MFN','MIR','MLA','MLZ','MMV',
               'MOB','MOE','MTX','MUI','MWB','MWZ','NBC','NHL','NHO','NSI','NWW','OAK','OCL','ORV','OSU','PCK','PFM',
               'PIG','RAD','RMC','RMF','RRC','SBG','SBJ','SBM','SBN','SBT','SCU','SHI','SLL','SMC','SNP','SSL','STH',
               'SUF','SWC','SWM','SWP','SWT','SWV','SYC','SZM','TGH','TQU','TZV','UMT','VGB','VGD','VRA','WBT','WGL',
               'WLG','WLZ','WVO','WWC','ZAQ','ZAW','ZBM','ZCI','ZWO')
OR D.ACNA IN ('AAV','AVA','ATX','LOA','SBB','SBZ','SUV','TPM',
               'AAX','ACF','ACH','ADM','AEC','AGS','AGZ','AHA','AHD','AHM','AHO','AIL','AIN','AIS','AKZ','ALY','AMH',
               'AMP','AWL','AWN','AWS','AZE','BAC','BAK','BAO','BCU','BFL','BGH','BMI','BPN','BSM','BWI','CBL','CCB',
               'CDA','CEL','CEO','CEU','CFN','CGL','CIV','CIW','CKQ','CLQ','COW','CPF','CQW','CRF','CRJ','CSG','CSO',
               'CSU','CSX','CTJ','CUO','CUY','CZB','DNC','EKC','EST','ETP','ETX','FLA','FSC','FSI','FSV','GEE','GLV',
               'GMB','GSL','HGN','HLU','HNC','HTN','HWC','IAS','IFP','IMP','IND','ISZ','IUW','JCR','JCT','LAA','LAC',
               'LBH','LNZ','LSZ','MBN','MBQ','MCA','MCC','MCE','MCQ','MCV','MCW','MCZ','MFN','MIR','MLA','MLZ','MMV',
               'MOB','MOE','MTX','MUI','MWB','MWZ','NBC','NHL','NHO','NSI','NWW','OAK','OCL','ORV','OSU','PCK','PFM',
               'PIG','RAD','RMC','RMF','RRC','SBG','SBJ','SBM','SBN','SBT','SCU','SHI','SLL','SMC','SNP','SSL','STH',
               'SUF','SWC','SWM','SWP','SWT','SWV','SYC','SZM','TGH','TQU','TZV','UMT','VGB','VGD','VRA','WBT','WGL',
               'WLG','WLZ','WVO','WWC','ZAQ','ZAW','ZBM','ZCI','ZWO')
OR D2.ACNA IN ('AAV','AVA','ATX','LOA','SBB','SBZ','SUV','TPM',
               'AAX','ACF','ACH','ADM','AEC','AGS','AGZ','AHA','AHD','AHM','AHO','AIL','AIN','AIS','AKZ','ALY','AMH',
               'AMP','AWL','AWN','AWS','AZE','BAC','BAK','BAO','BCU','BFL','BGH','BMI','BPN','BSM','BWI','CBL','CCB',
               'CDA','CEL','CEO','CEU','CFN','CGL','CIV','CIW','CKQ','CLQ','COW','CPF','CQW','CRF','CRJ','CSG','CSO',
               'CSU','CSX','CTJ','CUO','CUY','CZB','DNC','EKC','EST','ETP','ETX','FLA','FSC','FSI','FSV','GEE','GLV',
               'GMB','GSL','HGN','HLU','HNC','HTN','HWC','IAS','IFP','IMP','IND','ISZ','IUW','JCR','JCT','LAA','LAC',
               'LBH','LNZ','LSZ','MBN','MBQ','MCA','MCC','MCE','MCQ','MCV','MCW','MCZ','MFN','MIR','MLA','MLZ','MMV',
               'MOB','MOE','MTX','MUI','MWB','MWZ','NBC','NHL','NHO','NSI','NWW','OAK','OCL','ORV','OSU','PCK','PFM',
               'PIG','RAD','RMC','RMF','RRC','SBG','SBJ','SBM','SBN','SBT','SCU','SHI','SLL','SMC','SNP','SSL','STH',
               'SUF','SWC','SWM','SWP','SWT','SWV','SYC','SZM','TGH','TQU','TZV','UMT','VGB','VGD','VRA','WBT','WGL',
               'WLG','WLZ','WVO','WWC','ZAQ','ZAW','ZBM','ZCI','ZWO')
OR D2.CCNA IN ('AAV','AVA','ATX','LOA','SBB','SBZ','SUV','TPM',
               'AAX','ACF','ACH','ADM','AEC','AGS','AGZ','AHA','AHD','AHM','AHO','AIL','AIN','AIS','AKZ','ALY','AMH',
               'AMP','AWL','AWN','AWS','AZE','BAC','BAK','BAO','BCU','BFL','BGH','BMI','BPN','BSM','BWI','CBL','CCB',
               'CDA','CEL','CEO','CEU','CFN','CGL','CIV','CIW','CKQ','CLQ','COW','CPF','CQW','CRF','CRJ','CSG','CSO',
               'CSU','CSX','CTJ','CUO','CUY','CZB','DNC','EKC','EST','ETP','ETX','FLA','FSC','FSI','FSV','GEE','GLV',
               'GMB','GSL','HGN','HLU','HNC','HTN','HWC','IAS','IFP','IMP','IND','ISZ','IUW','JCR','JCT','LAA','LAC',
               'LBH','LNZ','LSZ','MBN','MBQ','MCA','MCC','MCE','MCQ','MCV','MCW','MCZ','MFN','MIR','MLA','MLZ','MMV',
               'MOB','MOE','MTX','MUI','MWB','MWZ','NBC','NHL','NHO','NSI','NWW','OAK','OCL','ORV','OSU','PCK','PFM',
               'PIG','RAD','RMC','RMF','RRC','SBG','SBJ','SBM','SBN','SBT','SCU','SHI','SLL','SMC','SNP','SSL','STH',
               'SUF','SWC','SWM','SWP','SWT','SWV','SYC','SZM','TGH','TQU','TZV','UMT','VGB','VGD','VRA','WBT','WGL',
               'WLG','WLZ','WVO','WWC','ZAQ','ZAW','ZBM','ZCI','ZWO'))
GROUP BY EXCHANGE_CARRIER_CIRCUIT_ID, CUD.UNI_OR_NNI, SI.STATUS
))
WHERE SUBSTR(CKT,7,1) <> 'U'
AND SI_STATUS = '6' AND STATUS <> '8'
AND PRODUCT IS NOT NULL
AND SUBSTR(SERVICE_TYPE_CATEGORY,1,7) = 'CLCI-SS'
AND ECCKT_TYPE = 'CLS'
ORDER BY 1;
