CREATE TYPE [dbo].[project_fields_tbltype] AS TABLE (
    [ProjectNumber]         INT           NOT NULL,
    [SubprojectNumber]      SMALLINT      NULL,
    [BudgetLineNumber]      INT           NULL,
    [ClassOfPlant]          CHAR (2)      NULL,
    [LinkCode]              VARCHAR (25)  NULL,
    [JustificationCode]     TINYINT       NULL,
    [FunctionalGroup]       CHAR (1)      NULL,
    [ProjectDescription]    VARCHAR (200) NULL,
    [ProjectStatusCode]     CHAR (2)      NULL,
    [ApprovalCode]          CHAR (2)      NULL,
    [ProjectType]           CHAR (1)      NULL,
    [Billable]              CHAR (1)      NULL,
    [Company]               SMALLINT      NULL,
    [ExchangeName]          VARCHAR (50)  NULL,
    [State]                 CHAR (2)      NULL,
    [OperatingArea]         SMALLINT      NULL,
    [Engineer]              VARCHAR (50)  NULL,
    [ProjectOwner]          VARCHAR (50)  NULL,
    [ApprovalDate]          DATE          NULL,
    [EstimatedStartDate]    DATE          NULL,
    [EstimatedCompleteDate] DATE          NULL,
    [ActualStartDate]       DATE          NULL,
    [ReadyForServiceDate]   DATE          NULL,
    [TentativeCloseDate]    DATE          NULL,
    [CloseDate]             DATE          NULL);

