CREATE TABLE [WCF].[CONSOLIDATED_DATA_TABLE] (
    [wireCenterClli]                                 NVARCHAR (255) NULL,
    [STATE]                                          NVARCHAR (255) NULL,
    [Copper troubles]                                FLOAT (53)     NULL,
    [Fiber troubles]                                 FLOAT (53)     NULL,
    [Copper new adds]                                FLOAT (53)     NULL,
    [Fiber new adds]                                 FLOAT (53)     NULL,
    [Cost per fiber trouble]                         FLOAT (53)     NULL,
    [Cost per copper trouble ticket]                 FLOAT (53)     NULL,
    [Cost per copper new add]                        FLOAT (53)     NULL,
    [Cost per fiber new add]                         FLOAT (53)     NULL,
    [Copper Trouble OOP Labor]                       FLOAT (53)     NULL,
    [Fiber trouble OOP Labor]                        FLOAT (53)     NULL,
    [Fiber new add labor]                            FLOAT (53)     NULL,
    [Copper new add OOP labor]                       FLOAT (53)     NULL,
    [Copper Labor]                                   FLOAT (53)     NULL,
    [Fiber Labor]                                    FLOAT (53)     NULL,
    [TSO Calls]                                      FLOAT (53)     NULL,
    [Cost per call]                                  FLOAT (53)     NULL,
    [TSO Costs]                                      FLOAT (53)     NULL,
    [Network Operations]                             FLOAT (53)     NULL,
    [Network Distribution]                           FLOAT (53)     NULL,
    [Assignment]                                     FLOAT (53)     NULL,
    [Network Core]                                   FLOAT (53)     NULL,
    [Circuits COGS]                                  FLOAT (53)     NULL,
    [Network Ops Support]                            FLOAT (53)     NULL,
    [Voice COGS]                                     FLOAT (53)     NULL,
    [SS7 Circuit]                                    FLOAT (53)     NULL,
    [Cable Locates]                                  FLOAT (53)     NULL,
    [Plant Maintenance]                              FLOAT (53)     NULL,
    [Poles]                                          FLOAT (53)     NULL,
    [Jointly Owned Poles]                            FLOAT (53)     NULL,
    [Plant Maintenance and Constructions]            FLOAT (53)     NULL,
    [Network Access]                                 FLOAT (53)     NULL,
    [Total]                                          FLOAT (53)     NULL,
    [ABU > 81% of Customers]                         FLOAT (53)     NULL,
    [ABU 61-80% of Customers]                        FLOAT (53)     NULL,
    [ABU 41-60% of Customers]                        FLOAT (53)     NULL,
    [ABU 21-40% of Customers]                        FLOAT (53)     NULL,
    [ABU 1-20% of Customers]                         FLOAT (53)     NULL,
    [ABU 0% of Customers]                            FLOAT (53)     NULL,
    [BEAD > 81% of Customers]                        FLOAT (53)     NULL,
    [BEAD 61-80% of Customers]                       FLOAT (53)     NULL,
    [BEAD 41-60% of Customers]                       FLOAT (53)     NULL,
    [BEAD 21-40% of Customers]                       FLOAT (53)     NULL,
    [BEAD 1-20% of Customers]                        FLOAT (53)     NULL,
    [BEAD 0% of Customers]                           FLOAT (53)     NULL,
    [Hyperion]                                       FLOAT (53)     NULL,
    [Regulatory Guidance - Green]                    FLOAT (53)     NULL,
    [Regulatory Guidance - Yellow]                   FLOAT (53)     NULL,
    [Regulatory Guidance - Red]                      FLOAT (53)     NULL,
    [Tarriff Restrictions - Green]                   FLOAT (53)     NULL,
    [Tarriff Restrictions - Yellow]                  FLOAT (53)     NULL,
    [Tarriff Restrictions - Red]                     FLOAT (53)     NULL,
    [2023 New Copper Installs]                       FLOAT (53)     NULL,
    [Applied SAC per install]                        FLOAT (53)     NULL,
    [SAC]                                            FLOAT (53)     NULL,
    [Extractable Copper Power Expense]               FLOAT (53)     NULL,
    [Consumer - Total Fiber Customers]               FLOAT (53)     NULL,
    [Consumer - Fiber Voice Only Customers]          FLOAT (53)     NULL,
    [Consumer - Fiber Broadband Only Customers]      FLOAT (53)     NULL,
    [Consumer - Fiber Video Only Customers]          FLOAT (53)     NULL,
    [Consumer - Fiber Voice & Broadband Customers]   FLOAT (53)     NULL,
    [Consumer - Fiber Broadband & Video Customers]   FLOAT (53)     NULL,
    [Consumer - Fiber Voice & Video]                 FLOAT (53)     NULL,
    [Consumer - Fiber No Core Products Customers]    FLOAT (53)     NULL,
    [Consumer - Total Copper Customers]              FLOAT (53)     NULL,
    [Consumer - Copper Voice Only Customers]         FLOAT (53)     NULL,
    [Consumer - Copper Broadband Only Customers]     FLOAT (53)     NULL,
    [Consumer - Copper Video Only Customers]         FLOAT (53)     NULL,
    [Consumer - Copper Voice & Broadband Customers]  FLOAT (53)     NULL,
    [Consumer - Copper Broadband & Video Customers]  FLOAT (53)     NULL,
    [Consumer - Copper Voice & Video]                FLOAT (53)     NULL,
    [Consumer - Copper Broadband & Voice & Video]    FLOAT (53)     NULL,
    [Consumer - Copper No Core Products Customers]   FLOAT (53)     NULL,
    [SMB - Fiber Customers]                          FLOAT (53)     NULL,
    [SMB- Fiber Voice Only Customers]                FLOAT (53)     NULL,
    [SMB - Fiber Broadband Only Customers]           FLOAT (53)     NULL,
    [SMB - Fiber Video Only Customers]               FLOAT (53)     NULL,
    [SMB - Fiber Voice & Broadband Customers]        FLOAT (53)     NULL,
    [SMB - Fiber Broadband & Video Customers]        FLOAT (53)     NULL,
    [SMB - Fiber Voice & Video]                      FLOAT (53)     NULL,
    [SMB - Fiber No Core Products Customers]         FLOAT (53)     NULL,
    [SMB - Total Copper Customers]                   FLOAT (53)     NULL,
    [SMB - Copper Voice Only Customers]              FLOAT (53)     NULL,
    [SMB - Copper Broadband Only Customers]          FLOAT (53)     NULL,
    [SMB - Copper Video Only Customers]              FLOAT (53)     NULL,
    [SMB - Copper Voice & Broadband Customers]       FLOAT (53)     NULL,
    [SMB - Copper Broadband & Video Customers]       FLOAT (53)     NULL,
    [SMB - Copper Voice & Video]                     FLOAT (53)     NULL,
    [SMB - Copper Broadband & Voice & Video]         FLOAT (53)     NULL,
    [SMB - Copper No Core Products Customers]        FLOAT (53)     NULL,
    [ENT - Total Fiber Customers]                    FLOAT (53)     NULL,
    [ENT - Fiber Voice Only Customers]               FLOAT (53)     NULL,
    [ENT - Fiber Broadband Only Customers]           FLOAT (53)     NULL,
    [ENT - Fiber Video Only Customers]               FLOAT (53)     NULL,
    [ENT - Fiber Voice & Broadband Customers]        FLOAT (53)     NULL,
    [ENT - Fiber Broadband & Video Customers]        FLOAT (53)     NULL,
    [ENT - Fiber Voice & Video]                      FLOAT (53)     NULL,
    [ENT - Fiber No Core Products Customers]         FLOAT (53)     NULL,
    [ENT - Total Copper Customers]                   FLOAT (53)     NULL,
    [ENT - Copper Voice Only Customers]              FLOAT (53)     NULL,
    [ENT - Copper Broadband Only Customers]          FLOAT (53)     NULL,
    [ENT - Copper Video Only Customers]              FLOAT (53)     NULL,
    [ENT - Copper Voice & Broadband Customers]       FLOAT (53)     NULL,
    [ENT - Copper Broadband & Video Customers]       FLOAT (53)     NULL,
    [ENT - Copper Voice & Video]                     FLOAT (53)     NULL,
    [ENT - Copper Broadband & Voice & Video]         FLOAT (53)     NULL,
    [ENT - Copper No Core Products Customers]        FLOAT (53)     NULL,
    [ENT - Circuits]                                 FLOAT (53)     NULL,
    [Paystation -  Total Customers (Voice)]          FLOAT (53)     NULL,
    [Wholesale - Total Fiber Customers]              FLOAT (53)     NULL,
    [Wholesale - Fiber Voice Only Customers]         FLOAT (53)     NULL,
    [Wholesale - Fiber Broadband Only Customers]     FLOAT (53)     NULL,
    [Wholesale - Fiber Video Only Customers]         FLOAT (53)     NULL,
    [Wholesale - Fiber Voice & Broadband Customers]  FLOAT (53)     NULL,
    [Wholesale - Fiber Broadband & Video Customers]  FLOAT (53)     NULL,
    [Wholesale - Fiber Voice & Video]                FLOAT (53)     NULL,
    [Wholesale - Fiber No Core Products Customers]   FLOAT (53)     NULL,
    [Wholesale - Total Copper Customers]             FLOAT (53)     NULL,
    [Wholesale - Copper Voice Only Customers]        FLOAT (53)     NULL,
    [Wholesale - Copper Broadband Only Customers]    FLOAT (53)     NULL,
    [Wholesale - Copper Video Only Customers]        FLOAT (53)     NULL,
    [Wholesale - Copper Voice & Broadband Customers] FLOAT (53)     NULL,
    [Wholesale - Copper Broadband & Video Customers] FLOAT (53)     NULL,
    [Wholesale - Copper Voice & Video]               FLOAT (53)     NULL,
    [Wholesale - Copper Broadband & Voice & Video]   FLOAT (53)     NULL,
    [Wholesale - Copper No Core Products Customers]  FLOAT (53)     NULL,
    [Wholesale - Circuits]                           FLOAT (53)     NULL
);

