
CREATE PROCEDURE EDW_VWMC.usp_TBL_CABS_SPCL_ACCS_BILL_REV_DTL
/*
	-- Add any parameters for the stored procedure here
	@var1 int,
	@var2 int
*/
AS
	SET XACT_ABORT, NOCOUNT ON;
BEGIN TRY

	DECLARE @EVENTID INT;

	INSERT INTO [LOG].tbl_StoreProc
	(
		[EVENTNAME],
		[EVENTSTART],
		[EVENTTYPE],
		[EVENTDESCRIPTION]
	)
	VALUES
	(
		'EDW_VWMC.TBL_CABS_SPCL_ACCS_BILL_REV_DTL',
		CAST(GETDATE() AS DATETIME),
		'STORE PROC',
		'SINGLE_INGESTION'
	)

	SET @EVENTID = SCOPE_IDENTITY();

	BEGIN TRANSACTION

	DELETE FROM EDW_VWMC.TBL_CABS_SPCL_ACCS_BILL_REV_DTL  WHERE BILL_MONTH_DT>=DATEADD(month, DATEDIFF(MONTH, -1, GETDATE()) - 2, 0)

	INSERT INTO EDW_VWMC.TBL_CABS_SPCL_ACCS_BILL_REV_DTL
	SELECT * FROM LZ.EDW_VWMC_CABS_SPCL_ACCS_BILL_REV_DTL_V
	
	COMMIT TRANSACTION

	UPDATE L
    SET L.EVENTEND = CAST(GETDATE() AS DATETIME)
    FROM LOG.tbl_StoreProc L
    WHERE L.EVENTID = @EventID;

END TRY
BEGIN CATCH
	IF @@trancount > 0 ROLLBACK TRANSACTION
	EXEC usp_error_handler
	RETURN 55555
END CATCH