
CREATE PROCEDURE EDW_VWMC.usp_TROUBLE_TICKETS
/*
	-- Add any parameters for the stored procedure here
	@var1 int,
	@var2 int
*/
AS
	SET XACT_ABORT, NOCOUNT ON;
BEGIN TRY

    DECLARE @EVENTID INT;

    INSERT INTO [LOG].tbl_StoreProc
    (
        [EVENTNAME],
        [EVENTSTART],
        [EVENTTYPE],
        [EVENTDESCRIPTION]
    )
    VALUES
    (
        'EDW_VWMC.TBL_TROUBLE_TICKETS',
        CAST(GETDATE() AS DATETIME),
        'STORE PROC',
        'SINGLE_INGESTION'
    )

    SET @EVENTID = SCOPE_IDENTITY();

	BEGIN TRANSACTION

    MERGE INTO EDW_VWMC.[TBL_TROUBLE_TICKETS] AS target

    USING (SELECT * FROM LZ.TBL_EDW_VWMC_TROUBLE_TICKETS) AS source
    ON target.WRK_ORD_JOIN_KEY = source.WRK_ORD_JOIN_KEY
    AND target.ACCT_JOIN_KEY = source.ACCT_JOIN_KEY

    -- When records match, update the record in the target table
    WHEN MATCHED THEN
        UPDATE SET
    target.[WRK_ORD_JOIN_KEY]	= source.[WRK_ORD_JOIN_KEY]
          ,target.[ACCT_JOIN_KEY] = source.[ACCT_JOIN_KEY]
          ,target.[ACCT_CUST_TYPE] = source.[ACCT_CUST_TYPE]
          ,target.[VIRTUAL_WIRE_CTR_JOIN_KEY] = source.[VIRTUAL_WIRE_CTR_JOIN_KEY]
          ,target.[SVC_ACCS_METHD_JOIN_KEY] = source.[SVC_ACCS_METHD_JOIN_KEY]
          ,target.[BILL_SUBSYS_CD] = source.[BILL_SUBSYS_CD]
          ,target.[WRK_ORD_NO] = source.[WRK_ORD_NO]
          ,target.[WRK_ORD_TYPE_CD] = source.[WRK_ORD_TYPE_CD]
          ,target.[WRK_ORD_STATUS_TYPE_CD] = source.[WRK_ORD_STATUS_TYPE_CD]
          ,target.[CONTACT_TELEPHONE_NO] = source.[CONTACT_TELEPHONE_NO]
          ,target.[SVC_ACCS_METHD_NO] = source.[SVC_ACCS_METHD_NO]
          ,target.[SOURCE_NPANXX] = source.[SOURCE_NPANXX]
          ,target.[SOURCE_LINE_NUMBER] = source.[SOURCE_LINE_NUMBER]
          ,target.[WIRE_CTR_NM] = source.[WIRE_CTR_NM]
          ,target.[TERR_CD] = source.[TERR_CD]
          ,target.[CUST_NEGOTIATED_IND] = source.[CUST_NEGOTIATED_IND]
          ,target.[REPORT_DTTM] = source.[REPORT_DTTM]
          ,target.[COMPLETION_DTTM] = source.[COMPLETION_DTTM]
          ,target.[COMMITMENT_DTTM] = source.[COMMITMENT_DTTM]
          ,target.[DISPATCH_START_DTTM] = source.[DISPATCH_START_DTTM]
          ,target.[POST_DTTM] = source.[POST_DTTM]
          ,target.[TAKEN_BY_CRIS_ID] = source.[TAKEN_BY_CRIS_ID]
          ,target.[CLOSED_BY_CRIS_ID] = source.[CLOSED_BY_CRIS_ID]
          ,target.[COMMENT_TEXT] = source.[COMMENT_TEXT]
          ,target.[APPT_MET_IND] = source.[APPT_MET_IND]
          ,target.[LFA_ID] = source.[LFA_ID]
          ,target.[ONT_SERIAL_NO] = source.[ONT_SERIAL_NO]
          ,target.[VIDEO_IND] = source.[VIDEO_IND]
          ,target.[UNIQUE_APPT_IND] = source.[UNIQUE_APPT_IND]
          ,target.[TRBL_TICKET_TYPE_CD] = source.[TRBL_TICKET_TYPE_CD]
          ,target.[TRBL_TICKET_TYPE_DS] = source.[TRBL_TICKET_TYPE_DS]
          ,target.[SUBSEQUENT_TICKET_IND] = source.[SUBSEQUENT_TICKET_IND]
          ,target.[REPEAT_PARENT_WRK_ORD_NO] = source.[REPEAT_PARENT_WRK_ORD_NO]
          ,target.[REPEAT_PARENT_WRK_ORD_TYPE_CD] = source.[REPEAT_PARENT_WRK_ORD_TYPE_CD]
          ,target.[REPORTABLE_IND] = source.[REPORTABLE_IND]
          ,target.[OUT_OF_SERVICE_IND] = source.[OUT_OF_SERVICE_IND]
          ,target.[SPECIAL_CIRCUIT_NO] = source.[SPECIAL_CIRCUIT_NO]
          ,target.[PREV_WORK_COMIT_IND] = source.[PREV_WORK_COMIT_IND]
          ,target.[TRBL_TICKET_SCHED_CD] = source.[TRBL_TICKET_SCHED_CD]
          ,target.[SCHED_PERIOD_MTH] = source.[SCHED_PERIOD_MTH]
          ,target.[SCHED_UNIT_NO] = source.[SCHED_UNIT_NO]
          ,target.[LINE_CARD_LAST_NM] = source.[LINE_CARD_LAST_NM]
          ,target.[LINE_CARD_FIRST_NM] = source.[LINE_CARD_FIRST_NM]
          ,target.[BILLING_LAST_NM] = source.[BILLING_LAST_NM]
          ,target.[BILLING_FIRST_NM] = source.[BILLING_FIRST_NM]
          ,target.[CITY_CD] = source.[CITY_CD]
          ,target.[SUBDIVISION_CD] = source.[SUBDIVISION_CD]
          ,target.[MAP_NO] = source.[MAP_NO]
          ,target.[TAX_DISTRICT_CD] = source.[TAX_DISTRICT_CD]
          ,target.[BUILDING_NM] = source.[BUILDING_NM]
          ,target.[zipcode] = source.[zipcode]
          ,target.[SAM_SEQUENCE_NO] = source.[SAM_SEQUENCE_NO]
          ,target.[CLEARING_DTTM] = source.[CLEARING_DTTM]
          ,target.[DISPATCH_TO_DTTM] = source.[DISPATCH_TO_DTTM]
          ,target.[SERVICE_CLASS_CD] = source.[SERVICE_CLASS_CD]
          ,target.[TRBL_TICKET_MISSED_APPT_CD] = source.[TRBL_TICKET_MISSED_APPT_CD]
          ,target.[FAULT_TYPE_CD] = source.[FAULT_TYPE_CD]
          ,target.[FAULT_TYPE_DS] = source.[FAULT_TYPE_DS]
          ,target.[CAUSE_TYPE_CD] = source.[CAUSE_TYPE_CD]
          ,target.[CAUSE_TYPE_DS] = source.[CAUSE_TYPE_DS]
          ,target.[ACTION_TYPE_CD] = source.[ACTION_TYPE_CD]
          ,target.[ACTION_TYPE_DS] = source.[ACTION_TYPE_DS]
          ,target.[SOURCE_TYPE_CD] = source.[SOURCE_TYPE_CD]
          ,target.[SOURCE_TYPE_DS] = source.[SOURCE_TYPE_DS]
          ,target.[REPORT_CD] = source.[REPORT_CD]
          ,target.[REPORT_CD_DS] = source.[REPORT_CD_DS]
          ,target.[PLANT_ITEM_TYPE_CD] = source.[PLANT_ITEM_TYPE_CD]
          ,target.[PLANT_ITEM_TYPE_DS] = source.[PLANT_ITEM_TYPE_DS]
          ,target.[SERVICE_TYPE_CD] = source.[SERVICE_TYPE_CD]
          ,target.[TRBL_TICKET_APPT_TYPE_CD] = source.[TRBL_TICKET_APPT_TYPE_CD]
          ,target.[PLANT_USE_TYPE_CD] = source.[PLANT_USE_TYPE_CD]
          ,target.[TSR_TYPE_CD] = source.[TSR_TYPE_CD]
          ,target.[TSR_DTTM] = source.[TSR_DTTM]
          ,target.[TESTING_DTTM] = source.[TESTING_DTTM]
          ,target.[TESTING_HRS_WRKD_QTY] = source.[TESTING_HRS_WRKD_QTY]
          ,target.[TESTING_RSLT_TYPE_CD] = source.[TESTING_RSLT_TYPE_CD]
          ,target.[TESTING_WRK_ORD_NO] = source.[TESTING_WRK_ORD_NO]
          ,target.[TESTING_CRIS_ID] = source.[TESTING_CRIS_ID]
          ,target.[CMP_STATUS_TYPE_CD] = source.[CMP_STATUS_TYPE_CD]
          ,target.[COMPLETION_TYPE_CD] = source.[COMPLETION_TYPE_CD]
          ,target.[WEATHER_TYPE_CD] = source.[WEATHER_TYPE_CD]
          ,target.[COMM_CAUSE_LEAD_TICKET_NO] = source.[COMM_CAUSE_LEAD_TICKET_NO]
          ,target.[COMM_CAUSE_TICKET_XCHNG_NO] = source.[COMM_CAUSE_TICKET_XCHNG_NO]
          ,target.[COMM_CAUSE_LINE_NO] = source.[COMM_CAUSE_LINE_NO]
          ,target.[CREDIT_REQUEST_IND] = source.[CREDIT_REQUEST_IND]
          ,target.[CREDIT_QUAL_IND] = source.[CREDIT_QUAL_IND]
          ,target.[CREDIT_IN_DTTM] = source.[CREDIT_IN_DTTM]
          ,target.[CREDIT_OUT_DTTM] = source.[CREDIT_OUT_DTTM]
          ,target.[ADVISED_OF_CHARGES_IND] = source.[ADVISED_OF_CHARGES_IND]
          ,target.[HOURS_WORKED_QTY] = source.[HOURS_WORKED_QTY]
          ,target.[MILES_DRIVEN_QTY] = source.[MILES_DRIVEN_QTY]
          ,target.[ELAPSED_HRS_QTY] = source.[ELAPSED_HRS_QTY]
          ,target.[Elpsd_hrs_excl_Sun_holy] = source.[Elpsd_hrs_excl_Sun_holy]
          ,target.[ELAPSED_BUS_WORK_HRS_QTY] = source.[ELAPSED_BUS_WORK_HRS_QTY]
          ,target.[CLEARING_HRS_QTY] = source.[CLEARING_HRS_QTY]
          ,target.[TO_DTTM_IND] = source.[TO_DTTM_IND]
          ,target.[COMMIT_MET_IND] = source.[COMMIT_MET_IND]
          ,target.[REPORT_DATE] = source.[REPORT_DATE]
          ,target.[COMMITMENT_DATE] = source.[COMMITMENT_DATE]
          ,target.[COMPLETION_DATE] = source.[COMPLETION_DATE]
          ,target.[CT_Miss] = source.[CT_Miss]
          ,target.[Next_Day] = source.[Next_Day]
          ,target.[LATEST_UPD_DTTM] = source.[LATEST_UPD_DTTM]


    -- When there is no match in the target table, insert the record into the target table
    WHEN NOT MATCHED BY TARGET THEN
        INSERT ([WRK_ORD_JOIN_KEY]
          ,[ACCT_JOIN_KEY]
          ,[ACCT_CUST_TYPE]
          ,[VIRTUAL_WIRE_CTR_JOIN_KEY]
          ,[SVC_ACCS_METHD_JOIN_KEY]
          ,[BILL_SUBSYS_CD]
          ,[WRK_ORD_NO]
          ,[WRK_ORD_TYPE_CD]
          ,[WRK_ORD_STATUS_TYPE_CD]
          ,[CONTACT_TELEPHONE_NO]
          ,[SVC_ACCS_METHD_NO]
          ,[SOURCE_NPANXX]
          ,[SOURCE_LINE_NUMBER]
          ,[WIRE_CTR_NM]
          ,[TERR_CD]
          ,[CUST_NEGOTIATED_IND]
          ,[REPORT_DTTM]
          ,[COMPLETION_DTTM]
          ,[COMMITMENT_DTTM]
          ,[DISPATCH_START_DTTM]
          ,[POST_DTTM]
          ,[TAKEN_BY_CRIS_ID]
          ,[CLOSED_BY_CRIS_ID]
          ,[COMMENT_TEXT]
          ,[APPT_MET_IND]
          ,[LFA_ID]
          ,[ONT_SERIAL_NO]
          ,[VIDEO_IND]
          ,[UNIQUE_APPT_IND]
          ,[TRBL_TICKET_TYPE_CD]
          ,[TRBL_TICKET_TYPE_DS]
          ,[SUBSEQUENT_TICKET_IND]
          ,[REPEAT_PARENT_WRK_ORD_NO]
          ,[REPEAT_PARENT_WRK_ORD_TYPE_CD]
          ,[REPORTABLE_IND]
          ,[OUT_OF_SERVICE_IND]
          ,[SPECIAL_CIRCUIT_NO]
          ,[PREV_WORK_COMIT_IND]
          ,[TRBL_TICKET_SCHED_CD]
          ,[SCHED_PERIOD_MTH]
          ,[SCHED_UNIT_NO]
          ,[LINE_CARD_LAST_NM]
          ,[LINE_CARD_FIRST_NM]
          ,[BILLING_LAST_NM]
          ,[BILLING_FIRST_NM]
          ,[CITY_CD]
          ,[SUBDIVISION_CD]
          ,[MAP_NO]
          ,[TAX_DISTRICT_CD]
          ,[BUILDING_NM]
          ,[zipcode]
          ,[SAM_SEQUENCE_NO]
          ,[CLEARING_DTTM]
          ,[DISPATCH_TO_DTTM]
          ,[SERVICE_CLASS_CD]
          ,[TRBL_TICKET_MISSED_APPT_CD]
          ,[FAULT_TYPE_CD]
          ,[FAULT_TYPE_DS]
          ,[CAUSE_TYPE_CD]
          ,[CAUSE_TYPE_DS]
          ,[ACTION_TYPE_CD]
          ,[ACTION_TYPE_DS]
          ,[SOURCE_TYPE_CD]
          ,[SOURCE_TYPE_DS]
          ,[REPORT_CD]
          ,[REPORT_CD_DS]
          ,[PLANT_ITEM_TYPE_CD]
          ,[PLANT_ITEM_TYPE_DS]
          ,[SERVICE_TYPE_CD]
          ,[TRBL_TICKET_APPT_TYPE_CD]
          ,[PLANT_USE_TYPE_CD]
          ,[TSR_TYPE_CD]
          ,[TSR_DTTM]
          ,[TESTING_DTTM]
          ,[TESTING_HRS_WRKD_QTY]
          ,[TESTING_RSLT_TYPE_CD]
          ,[TESTING_WRK_ORD_NO]
          ,[TESTING_CRIS_ID]
          ,[CMP_STATUS_TYPE_CD]
          ,[COMPLETION_TYPE_CD]
          ,[WEATHER_TYPE_CD]
          ,[COMM_CAUSE_LEAD_TICKET_NO]
          ,[COMM_CAUSE_TICKET_XCHNG_NO]
          ,[COMM_CAUSE_LINE_NO]
          ,[CREDIT_REQUEST_IND]
          ,[CREDIT_QUAL_IND]
          ,[CREDIT_IN_DTTM]
          ,[CREDIT_OUT_DTTM]
          ,[ADVISED_OF_CHARGES_IND]
          ,[HOURS_WORKED_QTY]
          ,[MILES_DRIVEN_QTY]
          ,[ELAPSED_HRS_QTY]
          ,[Elpsd_hrs_excl_Sun_holy]
          ,[ELAPSED_BUS_WORK_HRS_QTY]
          ,[CLEARING_HRS_QTY]
          ,[TO_DTTM_IND]
          ,[COMMIT_MET_IND]
          ,[REPORT_DATE]
          ,[COMMITMENT_DATE]
          ,[COMPLETION_DATE]
          ,[CT_Miss]
          ,[Next_Day]
          ,[LATEST_UPD_DTTM])
        VALUES (source.[WRK_ORD_JOIN_KEY]
          ,source.[ACCT_JOIN_KEY]
          ,source.[ACCT_CUST_TYPE]
          ,source.[VIRTUAL_WIRE_CTR_JOIN_KEY]
          ,source.[SVC_ACCS_METHD_JOIN_KEY]
          ,source.[BILL_SUBSYS_CD]
          ,source.[WRK_ORD_NO]
          ,source.[WRK_ORD_TYPE_CD]
          ,source.[WRK_ORD_STATUS_TYPE_CD]
          ,source.[CONTACT_TELEPHONE_NO]
          ,source.[SVC_ACCS_METHD_NO]
          ,source.[SOURCE_NPANXX]
          ,source.[SOURCE_LINE_NUMBER]
          ,source.[WIRE_CTR_NM]
          ,source.[TERR_CD]
          ,source.[CUST_NEGOTIATED_IND]
          ,source.[REPORT_DTTM]
          ,source.[COMPLETION_DTTM]
          ,source.[COMMITMENT_DTTM]
          ,source.[DISPATCH_START_DTTM]
          ,source.[POST_DTTM]
          ,source.[TAKEN_BY_CRIS_ID]
          ,source.[CLOSED_BY_CRIS_ID]
          ,source.[COMMENT_TEXT]
          ,source.[APPT_MET_IND]
          ,source.[LFA_ID]
          ,source.[ONT_SERIAL_NO]
          ,source.[VIDEO_IND]
          ,source.[UNIQUE_APPT_IND]
          ,source.[TRBL_TICKET_TYPE_CD]
          ,source.[TRBL_TICKET_TYPE_DS]
          ,source.[SUBSEQUENT_TICKET_IND]
          ,source.[REPEAT_PARENT_WRK_ORD_NO]
          ,source.[REPEAT_PARENT_WRK_ORD_TYPE_CD]
          ,source.[REPORTABLE_IND]
          ,source.[OUT_OF_SERVICE_IND]
          ,source.[SPECIAL_CIRCUIT_NO]
          ,source.[PREV_WORK_COMIT_IND]
          ,source.[TRBL_TICKET_SCHED_CD]
          ,source.[SCHED_PERIOD_MTH]
          ,source.[SCHED_UNIT_NO]
          ,source.[LINE_CARD_LAST_NM]
          ,source.[LINE_CARD_FIRST_NM]
          ,source.[BILLING_LAST_NM]
          ,source.[BILLING_FIRST_NM]
          ,source.[CITY_CD]
          ,source.[SUBDIVISION_CD]
          ,source.[MAP_NO]
          ,source.[TAX_DISTRICT_CD]
          ,source.[BUILDING_NM]
          ,source.[zipcode]
          ,source.[SAM_SEQUENCE_NO]
          ,source.[CLEARING_DTTM]
          ,source.[DISPATCH_TO_DTTM]
          ,source.[SERVICE_CLASS_CD]
          ,source.[TRBL_TICKET_MISSED_APPT_CD]
          ,source.[FAULT_TYPE_CD]
          ,source.[FAULT_TYPE_DS]
          ,source.[CAUSE_TYPE_CD]
          ,source.[CAUSE_TYPE_DS]
          ,source.[ACTION_TYPE_CD]
          ,source.[ACTION_TYPE_DS]
          ,source.[SOURCE_TYPE_CD]
          ,source.[SOURCE_TYPE_DS]
          ,source.[REPORT_CD]
          ,source.[REPORT_CD_DS]
          ,source.[PLANT_ITEM_TYPE_CD]
          ,source.[PLANT_ITEM_TYPE_DS]
          ,source.[SERVICE_TYPE_CD]
          ,source.[TRBL_TICKET_APPT_TYPE_CD]
          ,source.[PLANT_USE_TYPE_CD]
          ,source.[TSR_TYPE_CD]
          ,source.[TSR_DTTM]
          ,source.[TESTING_DTTM]
          ,source.[TESTING_HRS_WRKD_QTY]
          ,source.[TESTING_RSLT_TYPE_CD]
          ,source.[TESTING_WRK_ORD_NO]
          ,source.[TESTING_CRIS_ID]
          ,source.[CMP_STATUS_TYPE_CD]
          ,source.[COMPLETION_TYPE_CD]
          ,source.[WEATHER_TYPE_CD]
          ,source.[COMM_CAUSE_LEAD_TICKET_NO]
          ,source.[COMM_CAUSE_TICKET_XCHNG_NO]
          ,source.[COMM_CAUSE_LINE_NO]
          ,source.[CREDIT_REQUEST_IND]
          ,source.[CREDIT_QUAL_IND]
          ,source.[CREDIT_IN_DTTM]
          ,source.[CREDIT_OUT_DTTM]
          ,source.[ADVISED_OF_CHARGES_IND]
          ,source.[HOURS_WORKED_QTY]
          ,source.[MILES_DRIVEN_QTY]
          ,source.[ELAPSED_HRS_QTY]
          ,source.[Elpsd_hrs_excl_Sun_holy]
          ,source.[ELAPSED_BUS_WORK_HRS_QTY]
          ,source.[CLEARING_HRS_QTY]
          ,source.[TO_DTTM_IND]
          ,source.[COMMIT_MET_IND]
          ,source.[REPORT_DATE]
          ,source.[COMMITMENT_DATE]
          ,source.[COMPLETION_DATE]
          ,source.[CT_Miss]
          ,source.[Next_Day]
          ,source.[LATEST_UPD_DTTM])
    ;
	
	COMMIT TRANSACTION

    UPDATE L
    SET L.EVENTEND = CAST(GETDATE() AS DATETIME)
    FROM LOG.tbl_StoreProc L
    WHERE L.EVENTID = @EventID;

END TRY
BEGIN CATCH
	IF @@trancount > 0 ROLLBACK TRANSACTION
	EXEC usp_error_handler
	RETURN 55555
END CATCH