CREATE PROCEDURE EDW_VWMC.usp_TBL_C2F_EXCHANGE_SUBSCRIBERS
/*
	-- Add any parameters for the stored procedure here
	@var1 int,
	@var2 int
*/
AS
	SET XACT_ABORT, NOCOUNT ON;
BEGIN TRY

	DECLARE @EVENTID INT;

	INSERT INTO [LOG].tbl_StoreProc
	(
		[EVENTNAME],
		[EVENTSTART],
		[EVENTTYPE],
		[EVENTDESCRIPTION]
	)
	VALUES
	(
		'EDW_VWMC.TBL_C2F_EXCHANGE_SUBSCRIBERS',
		CAST(GETDATE() AS DATETIME),
		'STORE PROC',
		'SINGLE_INGESTION'
	)

	SET @EVENTID = SCOPE_IDENTITY();

	BEGIN TRANSACTION

	insert INTO EDW_VWMC.TBL_C2F_EXCHANGE_SUBSCRIBERS
	SELECT 
	A.* 
	,CAST(GETDATE() AS DATE) AS UPDATED_DT
	FROM LZ.TBL_EDW_VWMC_C2F_EXCHANGE_SUBSCRIBERS A
	
	COMMIT TRANSACTION

	UPDATE L
    SET L.EVENTEND = CAST(GETDATE() AS DATETIME)
    FROM LOG.tbl_StoreProc L
    WHERE L.EVENTID = @EventID;

END TRY
BEGIN CATCH
	IF @@trancount > 0 ROLLBACK TRANSACTION
	EXEC usp_error_handler
	RETURN 55555
END CATCH