CREATE TABLE [PushPull].[Binh_Closed] (
    [CompanyNumber]      NVARCHAR (10)  NULL,
    [Exch#]              NVARCHAR (10)  NULL,
    [ProjectMasterNumbr] NVARCHAR (10)  NULL,
    [LineSubProject#]    NVARCHAR (10)  NULL,
    [ProjJustificatCode] NVARCHAR (10)  NULL,
    [LineSuffixNumber]   NVARCHAR (10)  NULL,
    [SerialNumber]       NVARCHAR (10)  NULL,
    [PartItemNumber]     NVARCHAR (10)  NULL,
    [LineDescription]    NVARCHAR (MAX) NULL,
    [Extra30CharField]   NVARCHAR (50)  NULL,
    [TransSourcheCode1]  NVARCHAR (10)  NULL,
    [MajorTaskNumber]    NVARCHAR (10)  NULL,
    [SubTaskNumber1]     NVARCHAR (10)  NULL,
    [CostCode]           NVARCHAR (10)  NULL,
    [TransactionDate]    DATE           NULL,
    [LineQuantity]       NVARCHAR (10)  NULL,
    [EstimatedLineHours] NVARCHAR (10)  NULL,
    [LineRegularHours]   NVARCHAR (10)  NULL,
    [UnitCost]           MONEY          NULL,
    [LineClosedDate]     DATE           NULL,
    [PurchOrderLine#]    NVARCHAR (10)  NULL,
    [LineCommittedAmt]   MONEY          NULL,
    [ExtraNumbericField] NVARCHAR (10)  NULL,
    [LineInvoiceAmt]     MONEY          NULL,
    [LineBudgetAmount]   MONEY          NULL,
    [LineSpntTodateAmt]  MONEY          NULL,
    [CIPWIPAccount]      NVARCHAR (50)  NULL,
    [ProjectDescription] NVARCHAR (MAX) NULL,
    [LineAdministrator]  NVARCHAR (10)  NULL,
    [ProjectOwner]       NVARCHAR (10)  NULL,
    [ProjectStatusCode]  NVARCHAR (10)  NULL,
    [ProjectTypeCode]    NVARCHAR (10)  NULL,
    [LineStateAbbrv]     NVARCHAR (10)  NULL,
    [ApprovalCode]       NVARCHAR (10)  NULL,
    [AccountingYear]     NVARCHAR (10)  NULL,
    [AccountingPeriod]   NVARCHAR (10)  NULL,
    [ProjectCloseDate]   DATE           NULL,
    [OrigBudgetAmount]   MONEY          NULL
);

