--USE CASDW
DROP TABLE JPSAPR                        
/                                                                                                                                                                                                                                        
                                                                                
CREATE TABLE JPSAPR NOLOGGING NOCACHE AS   
select DISTINCT ORDER_NUMBER, PON, CKT, SERVICE, CREATE_DT, DD, COMP_DT, DD_COMP, VNET_COMP, 
       ACNA, STATE, ICSC, PROJ, JEOP JEOP_CD,
       CASE WHEN (COMP_DT <= DD OR DD IS NULL) THEN 'Met'
            WHEN (COMP_DT > DD AND JEOP IN ('CU01','CU02','CU03','CU04','CU05','DS02','EX01','CU51','CU52','CU53','DS52')) then 'Met' 
            ELSE 'Miss' END DD_STATUS, 
       CASE WHEN vnet_comp IS NOT NULL and substr(vnet_comp,1,4) >= '2020' THEN 'YES' ELSE 'NO' END DISPATCH,
       (TRUNC(COMP_DT) - TRUNC(CREATE_DT) ) +1 - 
       ((((TRUNC(COMP_DT,'D'))-(TRUNC(CREATE_DT,'D')))/7)*2) -
       (CASE WHEN TO_CHAR(CREATE_DT,'DY','nls_date_language=english')='SUN' THEN 1 ELSE 0 END) -
       (CASE WHEN TO_CHAR(COMP_DT,'DY','nls_date_language=english')='SAT' THEN 1 ELSE 0 END) as BusinessDays,
       CASE WHEN SERVICE = 'EELS DS1 NEW' AND VNET_COMP IS NOT NULL THEN '3568'
            WHEN SERVICE = 'EELS DS1 NEW' AND VNET_COMP IS NULL THEN '3569'
            WHEN SERVICE = 'EELS DS1 CONV' AND VNET_COMP IS NOT NULL THEN '3574'
            WHEN SERVICE = 'EELS DS1 CONV' AND VNET_COMP IS NULL THEN '3575'
            WHEN SERVICE = 'EELS DS3 NEW' AND VNET_COMP IS NOT NULL THEN '3576'
            WHEN SERVICE = 'EELS DS3 NEW' AND VNET_COMP IS NULL THEN '3577'            
            WHEN SERVICE = 'TRANSPORT DS1 NEW' AND VNET_COMP IS NOT NULL THEN '3607'
            WHEN SERVICE = 'TRANSPORT DS1 NEW' AND VNET_COMP IS NULL THEN '3608'
            WHEN SERVICE = 'TRANSPORT DS3 NEW' AND VNET_COMP IS NOT NULL THEN '3609'
            WHEN SERVICE = 'TRANSPORT DS3 NEW' AND VNET_COMP IS NULL THEN '3610'
            ELSE NULL END PRODUCT
FROM (
SELECT PON, DOCUMENT_NUMBER ORDER_NUMBER, ACT_IND, SUPP_TYPE, TRUNC(CLEANASR) CREATE_DT, DD, ACCEPT_DT, DD_COMP, 
         CASE WHEN DD_COMP IS NULL AND ACCEPT_DT > CLEANASR THEN ACCEPT_DT
            WHEN ACCEPT_DT IS NULL THEN DD_COMP
            WHEN ACCEPT_DT <= DD_COMP AND ACCEPT_DT > CLEANASR THEN ACCEPT_DT 
            ELSE DD_COMP END COMP_DT, ICSC, ACNA,  
         CASE WHEN PROJ IS NOT NULL THEN 'YES' ELSE 'NO' END PROJ,   
         CASE WHEN SUBSTR(CKT,4,4) = 'HCFU' AND SPEC = 'UNB1OT' AND PROJ LIKE '%SPUNE%' THEN 'EELS DS1 CONV'
              WHEN SUBSTR(CKT,4,4) = 'HCFU' AND SPEC = 'UNB1OT' THEN 'EELS DS1 NEW'
              WHEN SUBSTR(CKT,4,4) = 'HCFU' AND SPEC = 'UNBALL' AND PROJ LIKE '%SPUNE%' THEN 'TRANSPORT DS1 CONV'
              WHEN SUBSTR(CKT,4,4) = 'HCFU' AND SPEC = 'UNBALL' THEN 'TRANSPORT DS1 NEW'
              WHEN SUBSTR(CKT,4,4) = 'HFFU' AND SPEC = 'UNB1OT' AND PROJ LIKE '%SPUNE%' THEN 'EELS DS3 CONV'
              WHEN SUBSTR(CKT,4,4) = 'HFFU' AND SPEC = 'UNB1OT' THEN 'EELS DS3 NEW'
              WHEN SUBSTR(CKT,4,4) = 'HFFU' AND SPEC = 'UNBALL' AND PROJ LIKE '%SPUNE%' THEN 'TRANSPORT DS3 CONV'
              WHEN SUBSTR(CKT,4,4) = 'HFFU' AND SPEC = 'UNBALL' THEN 'TRANSPORT DS3 NEW'
              ELSE NULL END SERVICE,
         NC, JEOP, CKT, NPA.STATE, max(vnet.complete_date) vnet_comp
FROM
(
SELECT SR.PON,
  SR.DOCUMENT_NUMBER,
  MAX(SR.ACTIVITY_IND) keep (dense_rank last order by sr.last_modified_date) ACT_IND,
  MAX(SR.SUPPLEMENT_TYPE) keep (dense_rank last order by sr.last_modified_date) SUPP_TYPE,
  MAX(ASR2.DATE_TIME_SENT) KEEP (DENSE_RANK LAST ORDER BY ASR2.LAST_MODIFIED_DATE) CLEANASR, 
  MAX(ASR.DESIRED_DUE_DATE) KEEP (DENSE_RANK LAST ORDER BY ASR.LAST_MODIFIED_DATE) DD, 
  MIN(ACCEPTANCE_DATE) KEEP (DENSE_RANK LAST ORDER BY AUD.LAST_MODIFIED_DATE) ACCEPT_DT, 
  MAX(TRUNC(T.ACTUAL_COMPLETION_DATE)) keep (dense_rank last order by T.last_modified_date) DD_COMP,
  MAX(ASR.ACCESS_PROVIDER_SERV_CTR_CODE) keep (dense_rank last order by asr.last_modified_date) ICSC,
  MAX(SR.PROJECT_IDENTIFICATION) keep (dense_rank last order by sr.last_modified_date) PROJ,
  MAX(SR.ACNA) keep (dense_rank last order by sr.last_modified_date) ACNA,
  MAX(ASR.NETWORK_CHANNEL_SERVICE_CODE) keep (dense_rank last order by asr.last_modified_date) NC,
  max(asr.service_and_product_enhanc_cod) keep (dense_rank last order by asr.last_modified_date) SPEC,
  MAX(JEOPARDY_REASON_CODE) KEEP (DENSE_RANK LAST ORDER BY JEOP.LAST_MODIFIED_DATE) JEOP,
  CIR.EXCHANGE_CARRIER_CIRCUIT_ID CKT,
  max(asr.npa) keep (dense_rank last order by asr.last_modified_date) npa,
  max(asr.nxx) keep (dense_rank last order by asr.last_modified_date) nxx     
--
FROM casdw.SERV_REQ SR, 
     casdw.ACCESS_SERVICE_REQUEST ASR,
     casdw.ACCESS_SERVICE_REQUEST ASR2,
     casdw.ASR_USER_DATA AUD,
     casdw.CIRCUIT CIR, 
     casdw.TASK T,
     casdw.TASK_JEOPARDY_WHYMISS JEOP,
     HIERARCHY NPA
--
WHERE SR.DOCUMENT_NUMBER = ASR.DOCUMENT_NUMBER(+)
AND SR.DOCUMENT_NUMBER = ASR2.DOCUMENT_NUMBER(+)
AND SR.DOCUMENT_NUMBER = AUD.DOCUMENT_NUMBER (+)
AND SR.FIRST_ECCKT_ID = CIR.EXCHANGE_CARRIER_CIRCUIT_ID (+)
AND SR.DOCUMENT_NUMBER = T.DOCUMENT_NUMBER (+)
AND T.TASK_NUMBER = JEOP.TASK_NUMBER(+)
AND ASR.NPA||ASR.NXX = NPA.NPANXX (+)
AND T.TASK_TYPE = 'DD'    
AND ASR.REQUEST_TYPE IN ('S','E')
AND ASR.ACTIVITY_INDICATOR IN ('N','C')
AND JEOP.JEOPARDY_TYPE_CD(+) = 'W' 
AND SUBSTR(CIR.EXCHANGE_CARRIER_CIRCUIT_ID,7,1) = 'U'
AND ASR.ACCESS_PROVIDER_SERV_CTR_CODE in ('GT10','GT11')
AND asr.service_and_product_enhanc_cod IN ('UNBALL','UNB1OT')
--and asr.document_number = '3544219'
AND TO_CHAR(T.ACTUAL_COMPLETION_DATE,'YYYYMM') = '202312' 
--
GROUP BY SR.DOCUMENT_NUMBER, SR.PON, CIR.EXCHANGE_CARRIER_CIRCUIT_ID
) A, HIERARCHY NPA, CASDW.VNET_DAILY VNET
--
WHERE A.NPA||A.NXX = NPA.NPANXX (+)
 and to_char(A.DOCUMENT_NUMBER) =  SUBSTR(VNET.cust_tckt_number(+),5,7)
AND (SUPP_TYPE <> '1' OR SUPP_TYPE IS NULL)
GROUP BY PON, DOCUMENT_NUMBER, ACT_IND, SUPP_TYPE, CLEANASR, DD, ACCEPT_DT, DD_COMP,
         ICSC, PROJ, ACNA, NC, JEOP, CKT, NPA.STATE, SPEC, PROJ 
 )
WHERE STATE IN ('CA','FL')
ORDER BY 10, 9, 4, 14;




--select * from jpsapr;


--TO PULL CLEC AGG SUMMARY FOR PR  
SELECT STATE, MNTH, 'PR-2-09-'||PRODUCT METRIC, SUM(NUM) NUM, COUNT(*) DEN
FROM        
(
--
SELECT STATE, TO_CHAR(DD_COMP,'MM')||'/01/'||TO_CHAR(DD_COMP,'YYYY') MNTH, 
       SERVICE, DISPATCH, PROJ, PRODUCT, DD_STATUS, BUSINESSDAYS NUM 
FROM JPSAPR
--
)WHERE PROJ = 'NO'
GROUP BY STATE, MNTH, PRODUCT
--
UNION ALL
--
SELECT STATE, MNTH, 'PR-4-01-'||PRODUCT METRIC, SUM(MET) NUM, COUNT(*) DEN
FROM        
(
--
SELECT STATE, TO_CHAR(DD_COMP,'MM')||'/01/'||TO_CHAR(DD_COMP,'YYYY') MNTH, 
       SERVICE, DISPATCH, PRODUCT, DD_STATUS, 
       CASE WHEN DD_STATUS = 'Met' THEN 0 ELSE 1 END MET 
FROM JPSAPR
--
)
GROUP BY STATE, MNTH, PRODUCT
--
UNION ALL
--
SELECT STATE, MNTH, 'PR-5-01-'||PRODUCT METRIC, 0 NUM, COUNT(*) DEN
FROM        
(
--
SELECT STATE, TO_CHAR(DD_COMP,'MM')||'/01/'||TO_CHAR(DD_COMP,'YYYY') MNTH, 
       SERVICE, DISPATCH, PRODUCT, DD_STATUS 
FROM JPSAPR
--
)
GROUP BY STATE, MNTH, PRODUCT
ORDER BY 1,2,3;


--TO PULL CLEC SPECIFIC SUMMARY FOR PR  
SELECT STATE, ACNA, MNTH, 'PR-2-09-'||PRODUCT METRIC, SUM(NUM) NUM, COUNT(*) DEN
FROM        
(
--
SELECT STATE, ACNA, TO_CHAR(DD_COMP,'MM')||'/01/'||TO_CHAR(DD_COMP,'YYYY') MNTH, 
       SERVICE, DISPATCH, PROJ, PRODUCT, DD_STATUS, BUSINESSDAYS NUM 
FROM JPSAPR
ORDER BY 1,2,3,4,5
--
)WHERE PROJ = 'NO'
GROUP BY STATE, ACNA, MNTH, PRODUCT
--
UNION ALL
--
SELECT STATE, ACNA, MNTH, 'PR-4-01-'||PRODUCT METRIC, SUM(MET) NUM, COUNT(*) DEN
FROM        
(
--
SELECT STATE, ACNA, TO_CHAR(DD_COMP,'MM')||'/01/'||TO_CHAR(DD_COMP,'YYYY') MNTH, 
       SERVICE, DISPATCH, PRODUCT, DD_STATUS, 
       CASE WHEN DD_STATUS = 'Met' THEN 0 ELSE 1 END MET 
FROM JPSAPR
ORDER BY 1,2,3,4,5
--
)
GROUP BY STATE, ACNA, MNTH, PRODUCT
--
UNION ALL
--
SELECT STATE, ACNA, MNTH, 'PR-5-01-'||PRODUCT METRIC, 0 NUM, COUNT(*) DEN
FROM        
(
--
SELECT STATE, ACNA, TO_CHAR(DD_COMP,'MM')||'/01/'||TO_CHAR(DD_COMP,'YYYY') MNTH, 
       SERVICE, DISPATCH, PRODUCT, DD_STATUS 
FROM JPSAPR
ORDER BY 1,2,3,4,5
--
)
GROUP BY STATE, ACNA, MNTH, PRODUCT
ORDER BY 1,2,4;




select * from CASDW.VNET_DAILY VNET
where SUBSTR(VNET.cust_tckt_number(+),5,7) in (
'3447770',
'3432098',
'3436124')

;

select * from jpsapr
