CREATE TABLE [WCF].[TBL_REV_BY_LOB_AND_PRODUCT] (
    [Wirecenter]                                     NVARCHAR (255) NULL,
    [Consumer - Total Fiber Customers]               FLOAT (53)     NULL,
    [Consumer - Fiber Voice Only Customers]          FLOAT (53)     NULL,
    [Consumer - Fiber Broadband Only Customers]      FLOAT (53)     NULL,
    [Consumer - Fiber Video Only Customers]          FLOAT (53)     NULL,
    [Consumer - Fiber Voice & Broadband Customers]   FLOAT (53)     NULL,
    [Consumer - Fiber Broadband & Video Customers]   FLOAT (53)     NULL,
    [Consumer - Fiber Voice & Video]                 FLOAT (53)     NULL,
    [Consumer - Fiber No Core Products Customers]    FLOAT (53)     NULL,
    [Consumer - Total Copper Customers]              FLOAT (53)     NULL,
    [Consumer - Copper Voice Only Customers]         FLOAT (53)     NULL,
    [Consumer - Copper Broadband Only Customers]     FLOAT (53)     NULL,
    [Consumer - Copper Video Only Customers]         FLOAT (53)     NULL,
    [Consumer - Copper Voice & Broadband Customers]  FLOAT (53)     NULL,
    [Consumer - Copper Broadband & Video Customers]  FLOAT (53)     NULL,
    [Consumer - Copper Voice & Video]                FLOAT (53)     NULL,
    [Consumer - Copper Broadband & Voice & Video]    FLOAT (53)     NULL,
    [Consumer - Copper No Core Products Customers]   FLOAT (53)     NULL,
    [SMB - Fiber Customers]                          FLOAT (53)     NULL,
    [SMB- Fiber Voice Only Customers]                FLOAT (53)     NULL,
    [SMB - Fiber Broadband Only Customers]           FLOAT (53)     NULL,
    [SMB - Fiber Video Only Customers]               FLOAT (53)     NULL,
    [SMB - Fiber Voice & Broadband Customers]        FLOAT (53)     NULL,
    [SMB - Fiber Broadband & Video Customers]        FLOAT (53)     NULL,
    [SMB - Fiber Voice & Video]                      FLOAT (53)     NULL,
    [SMB - Fiber No Core Products Customers]         FLOAT (53)     NULL,
    [SMB - Total Copper Customers]                   FLOAT (53)     NULL,
    [SMB - Copper Voice Only Customers]              FLOAT (53)     NULL,
    [SMB - Copper Broadband Only Customers]          FLOAT (53)     NULL,
    [SMB - Copper Video Only Customers]              FLOAT (53)     NULL,
    [SMB - Copper Voice & Broadband Customers]       FLOAT (53)     NULL,
    [SMB - Copper Broadband & Video Customers]       FLOAT (53)     NULL,
    [SMB - Copper Voice & Video]                     FLOAT (53)     NULL,
    [SMB - Copper Broadband & Voice & Video]         FLOAT (53)     NULL,
    [SMB - Copper No Core Products Customers]        FLOAT (53)     NULL,
    [ENT - Total Fiber Customers]                    FLOAT (53)     NULL,
    [ENT - Fiber Voice Only Customers]               FLOAT (53)     NULL,
    [ENT - Fiber Broadband Only Customers]           FLOAT (53)     NULL,
    [ENT - Fiber Video Only Customers]               FLOAT (53)     NULL,
    [ENT - Fiber Voice & Broadband Customers]        FLOAT (53)     NULL,
    [ENT - Fiber Broadband & Video Customers]        FLOAT (53)     NULL,
    [ENT - Fiber Voice & Video]                      FLOAT (53)     NULL,
    [ENT - Fiber No Core Products Customers]         FLOAT (53)     NULL,
    [ENT - Total Copper Customers]                   FLOAT (53)     NULL,
    [ENT - Copper Voice Only Customers]              FLOAT (53)     NULL,
    [ENT - Copper Broadband Only Customers]          FLOAT (53)     NULL,
    [ENT - Copper Video Only Customers]              FLOAT (53)     NULL,
    [ENT - Copper Voice & Broadband Customers]       FLOAT (53)     NULL,
    [ENT - Copper Broadband & Video Customers]       FLOAT (53)     NULL,
    [ENT - Copper Voice & Video]                     FLOAT (53)     NULL,
    [ENT - Copper Broadband & Voice & Video]         FLOAT (53)     NULL,
    [ENT - Copper No Core Products Customers]        FLOAT (53)     NULL,
    [ENT - Circuits]                                 FLOAT (53)     NULL,
    [Paystation -  Total Customers (Voice)]          FLOAT (53)     NULL,
    [Wholesale - Total Fiber Customers]              FLOAT (53)     NULL,
    [Wholesale - Fiber Voice Only Customers]         FLOAT (53)     NULL,
    [Wholesale - Fiber Broadband Only Customers]     FLOAT (53)     NULL,
    [Wholesale - Fiber Video Only Customers]         FLOAT (53)     NULL,
    [Wholesale - Fiber Voice & Broadband Customers]  FLOAT (53)     NULL,
    [Wholesale - Fiber Broadband & Video Customers]  FLOAT (53)     NULL,
    [Wholesale - Fiber Voice & Video]                FLOAT (53)     NULL,
    [Wholesale - Fiber No Core Products Customers]   FLOAT (53)     NULL,
    [Wholesale - Total Copper Customers]             FLOAT (53)     NULL,
    [Wholesale - Copper Voice Only Customers]        FLOAT (53)     NULL,
    [Wholesale - Copper Broadband Only Customers]    FLOAT (53)     NULL,
    [Wholesale - Copper Video Only Customers]        FLOAT (53)     NULL,
    [Wholesale - Copper Voice & Broadband Customers] FLOAT (53)     NULL,
    [Wholesale - Copper Broadband & Video Customers] FLOAT (53)     NULL,
    [Wholesale - Copper Voice & Video]               FLOAT (53)     NULL,
    [Wholesale - Copper Broadband & Voice & Video]   FLOAT (53)     NULL,
    [Wholesale - Copper No Core Products Customers]  FLOAT (53)     NULL,
    [Wholesale - Circuits]                           FLOAT (53)     NULL
);

