CREATE TABLE [LZ].[TBL_VFO_PONS] (
    [DOCNO]        VARCHAR (15)  NOT NULL,
    [REQ]          VARCHAR (1)   NULL,
    [ACT]          VARCHAR (1)   NULL,
    [BUILD]        VARCHAR (25)  NULL,
    [BUILD_IOF]    VARCHAR (255) NULL,
    [BUILD_OSP]    VARCHAR (255) NULL,
    [INIT]         DATETIME      NULL,
    [CLEAN]        DATETIME      NULL,
    [DD]           DATETIME      NULL,
    [COMP_DT]      DATETIME      NULL,
    [DD_COMP]      DATETIME      NULL,
    [NC]           VARCHAR (5)   NULL,
    [PROD]         VARCHAR (15)  NULL,
    [PNUM]         VARCHAR (20)  NULL,
    [PON]          VARCHAR (20)  NULL,
    [CKT]          VARCHAR (60)  NULL,
    [ICSC]         VARCHAR (5)   NULL,
    [ACNA]         VARCHAR (5)   NULL,
    [WHY_MISS1]    VARCHAR (5)   NULL,
    [MISS_REASON1] VARCHAR (125) NULL,
    [PROJ]         VARCHAR (20)  NULL,
    [STATE]        VARCHAR (2)   NULL,
    [REGION]       VARCHAR (7)   NULL,
    [PRODUCT]      VARCHAR (22)  NULL,
    [PRODUCT2]     VARCHAR (8)   NULL,
    [SEI]          VARCHAR (1)   NULL,
    [BDW]          VARCHAR (4)   NULL,
    [DD_MET]       FLOAT (53)    NULL,
    [DLR]          VARCHAR (3)   NULL
);

