CREATE TABLE [LZ].[TBL_WABB_SERVICE_ORDERS] (
    [ORDNO]          VARCHAR (9)     NULL,
    [ENV]            VARCHAR (2)     NULL,
    [PON]            VARCHAR (20)    NULL,
    [ACT]            VARCHAR (1)     NULL,
    [ORD_TYPE]       VARCHAR (8)     NULL,
    [SERV_TYPE]      VARCHAR (3)     NULL,
    [STATUS]         VARCHAR (8)     NULL,
    [WTN]            NUMERIC (10)    NULL,
    [BTN]            NUMERIC (10)    NULL,
    [SE_CODE]        VARCHAR (5)     NULL,
    [NETWORK]        VARCHAR (10)    NULL,
    [CCNA]           VARCHAR (4)     NULL,
    [CARRIER]        VARCHAR (100)   NULL,
    [CUSTNM]         VARCHAR (30)    NULL,
    [SO_CREATE_DT]   DATE            NULL,
    [SO_EFF_COMP_DT] DATE            NULL,
    [SO_ACT_COMP_DT] DATE            NULL,
    [POST_DT]        DATE            NULL,
    [AGING]          INT             NULL,
    [AGING_GRP]      VARCHAR (5)     NULL,
    [ADDRESS]        VARCHAR (4000)  NULL,
    [CITY]           VARCHAR (20)    NULL,
    [STATE]          VARCHAR (2)     NULL,
    [ZIP]            VARCHAR (5)     NULL,
    [MRC]            NUMERIC (15, 2) NULL,
    [TERM_CODE]      VARCHAR (5)     NULL,
    [TERM2]          VARCHAR (13)    NULL,
    [TERM_DESC]      VARCHAR (10)    NULL
);

