CREATE PROCEDURE WCF.[usp_UPDATE_TBL_NETWORK_EXPENSE_BY_STATE] AS

--MANUALLY UPDATE THE FILE NAME WHEN RUNNING USP
INSERT INTO WCF.TBL_NETWORK_EXPENSE_BY_STATE
SELECT *
FROM OPENROWSET('Microsoft.ACE.OLEDB.12.0', 
   'Excel 12.0;Database=D:\LZ\WCF\NETWORK\Network Expense by State Expanded JUNE 24.XLSX;HDR=YES', 
   'SELECT * FROM [UPLOAD$]')A
;
GO

--EXECUTE [WCF].[usp_UPDATE_TBL_NETWORK_EXPENSE_BY_STATE]
--SELECT * FROM WCF.TBL_NETWORK_EXPENSE_BY_STATE
--SELECT MAX(RPT_MTH) FROM WCF.TBL_NETWORK_EXPENSE_BY_STATE
--DELETE FROM WCF.TBL_NETWORK_EXPENSE_BY_STATE WHERE RPT_MTH = (SELECT MAX(RPT_MTH) FROM [WCF].TBL_NETWORK_EXPENSE_BY_STATE)