
CREATE PROCEDURE QBR.usp_TBL_SR_EMBEDDED_BASE
/*
	-- Add any parameters for the stored procedure here
	@var1 int,
	@var2 int
*/
AS
	SET XACT_ABORT, NOCOUNT ON;
BEGIN TRY
	BEGIN TRANSACTION
	DROP TABLE IF EXISTS #t
INSERT INTO [LOG].tbl_storeproc
    ([EVENTNAME]
    ,[EVENTSTART]
    ,[EVENTTYPE]
    ,[EVENTDESCRIPTION])

--enter values below

VALUES
('QBR.TBL_SR_EMBEDDED_BASE'
    ,CAST(GETDATE() AS DATETIME)
    ,'STORE PROC'
    ,'SINGLE_INGESTION')



SELECT MAX(EVENTID) AS LATESTID  INTO #t
FROM [LOG].tbl_storeproc


 --Cannot truncate system versioned table

INSERT INTO QBR.TBL_SR_EMBEDDED_BASE
SELECT CAST(DATEADD(month, DATEDIFF(month, 0, GETDATE()), 0) AS DATE) AS RPT_MTH
,A.CKT_ID
,A.CLEC_ID
,A.SERVICE_TYPE_CAT
,A.STATE_CD
,A.SVC_CD
,A.PRODUCT
,A.BDW
,A.STATUS
,A.SI_STATUS
FROM LZ.TBL_SR_EMBEDDED_BASE A

	
	
UPDATE L
SET L.EVENTEND=CAST(GETDATE() AS DATETIME)
FROM LOG.tbl_storeproc L
INNER JOIN #t
ON L.EVENTID = #t.LATESTID
DROP TABLE IF EXISTS #t


	
	COMMIT TRANSACTION
END TRY
BEGIN CATCH
	IF @@trancount > 0 ROLLBACK TRANSACTION
	EXEC usp_error_handler
	RETURN 55555
END CATCH