
CREATE PROCEDURE dbo.usp_TBL_CB_DE
/*
	-- Add any parameters for the stored procedure here
	@var1 int,
	@var2 int
*/
AS
	SET XACT_ABORT, NOCOUNT ON;
BEGIN TRY
	BEGIN TRANSACTION
	DROP TABLE IF EXISTS #t
INSERT INTO [LOG].tbl_storeproc
    ([EVENTNAME]
    ,[EVENTSTART]
    ,[EVENTTYPE]
    ,[EVENTDESCRIPTION])

--enter values below

VALUES
('dbo.TBL_CB_DE'
    ,CAST(GETDATE() AS DATETIME)
    ,'STORE PROC'
    ,'SINGLE_INGESTION')



SELECT MAX(EVENTID) AS LATESTID  INTO #t
FROM [LOG].tbl_storeproc


MERGE INTO dbo.TBL_CB_DE AS target
USING LZ.SFTP_CB_DE_750 AS source
ON target.ID =source.ID
WHEN NOT MATCHED BY TARGET THEN
INSERT (ID,LOGIN_ID,ROUTE_NAME,REQUESTING_COMPANY,ADDRESS,CITY,STATE,ZIP,COUNTY,COUNTRY,USER_COMPANY,TARGET_COMPANY_ID,TARGET_COMPANY,REQUEST_DATE,RESULT,SERVICENAME,ERROR_MESSAGE,Filename)
VALUES(source.ID,source.LOGIN_ID,source.ROUTE_NAME,source.REQUESTING_COMPANY,source.ADDRESS,source.CITY,source.STATE,source.ZIP,source.COUNTY,source.COUNTRY,source.USER_COMPANY,source.TARGET_COMPANY_ID,source.TARGET_COMPANY,source.REQUEST_DATE,source.RESULT,source.SERVICENAME,source.ERROR_MESSAGE,source.Filename)
;
MERGE INTO dbo.TBL_CB_DE AS target
USING LZ.SFTP_CB_DE_819 AS source
ON target.ID =source.ID
WHEN NOT MATCHED BY TARGET THEN
INSERT (ID,LOGIN_ID,ROUTE_NAME,REQUESTING_COMPANY,ADDRESS,CITY,STATE,ZIP,COUNTY,COUNTRY,USER_COMPANY,TARGET_COMPANY_ID,TARGET_COMPANY,REQUEST_DATE,RESULT,SERVICENAME,ERROR_MESSAGE,Filename)
VALUES(source.ID,source.LOGIN_ID,source.ROUTE_NAME,source.REQUESTING_COMPANY,source.ADDRESS,source.CITY,source.STATE,source.ZIP,source.COUNTY,source.COUNTRY,source.USER_COMPANY,source.TARGET_COMPANY_ID,source.TARGET_COMPANY,source.REQUEST_DATE,source.RESULT,source.SERVICENAME,source.ERROR_MESSAGE,source.Filename)
;



	
UPDATE L
SET L.EVENTEND=CAST(GETDATE() AS DATETIME)
FROM LOG.tbl_storeproc L
INNER JOIN #t
ON L.EVENTID = #t.LATESTID
DROP TABLE IF EXISTS #t


	
	COMMIT TRANSACTION
END TRY
BEGIN CATCH
	IF @@trancount > 0 ROLLBACK TRANSACTION
	EXEC usp_error_handler
	RETURN 55555
END CATCH